### ISSUE TITLE
内置私有云，迁移过程优化

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#11132]
**What would you like to be added**:
第一，加入预调度或者迁移备选的宿主机是已经评估过是迁移可用的宿主机；
第二，如果可以，迁移过程中，我们把进度条（过程反馈）也加上。

**Comment by zexi** [comment]
第一步已经实现，可以通过预先调度结构过滤出可以迁移的宿主机。
第二步暂时不打算实现。
