### ISSUE TITLE
新建阿里云虚拟机不应该报部署失败

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11232]
**What happened**:
用阿里云自己的镜像，新建虚拟机
![image](https://user-images.githubusercontent.com/32036395/119784789-244f9580-bf01-11eb-8ba7-f9537038b57e.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
换个非uefi的镜像就可以，目前没有维护套餐和镜像之间的依赖关系

**Comment by zexi** [comment]
这个问题现在有修复吗？

**Comment by ioito** [comment]
3.8 支持创建时候后自动切换使用同配置的其他套餐
开启方法:
climc service-config --config enable_auto_switch_server_sku=true region2
