### ISSUE TITLE
高可用环境部署后，zone不应该有两个

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11293]
**What happened**:
# climc zone-list
+--------------------------------------+--------------------------------------+--------+----------------+
|                  ID                  |                 Name                 | Status | Cloudregion_ID |
+--------------------------------------+--------------------------------------+--------+----------------+
| ef7712dc-106f-4a07-81a4-3a3de116e736 | ced40e32-887b-40fc-8bc0-e019b95a218f | enable | default        |
| ced40e32-887b-40fc-8bc0-e019b95a218f | zone0                                | enable | default        |
+--------------------------------------+--------------------------------------+--------+----------------+
![image](https://user-images.githubusercontent.com/32036395/120596628-916da880-c476-11eb-8294-4c7cfe44c375.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
该问题已经通过 PR: https://github.com/yunionio/cloudpods-operator/pull/486 修复
