### ISSUE TITLE
部署高可用环境后glance服务对应的pod状态不应该是CrashLoopBackOff

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11292]
**What happened**:
![TnB2Gopntw](https://user-images.githubusercontent.com/32036395/120581314-311e3d00-c45d-11eb-9ee8-fd6b0ccb6cbf.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
PR: https://github.com/yunionio/cloudpods-operator/pull/462 fixes this issue.
