### ISSUE TITLE
windows系统的虚拟机迁移后用原密码重新登陆提示密码不正确

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11315]
**What happened**:

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by hoganlxj** [comment]
@zhasm

**Comment by zexi** [comment]
这个是外部导入的 windows 镜像，不是调的云平台迁移接口。
