### ISSUE TITLE
宿主机服务离线后其上面的虚拟机状态不应该还是running

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11314]
**What happened**:
宿主机自动下线后，上面的虚拟机状态还是运行中，应该是未知
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
通过默认关闭 host_health_check 解决

**Comment by zexi** [comment]
还需要验证测试下
