### ISSUE TITLE
新建移动云账号时移动云不应该显示一串字母

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11365]
**What happened**:
![lv9F0tyxt8](https://user-images.githubusercontent.com/32036395/121190825-00476900-c89e-11eb-8a79-0d7af120b13a.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/472
