### ISSUE TITLE
批量新建三台VMware虚拟机，不应该只有第一台生成密码

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11366]
**What happened**:
批量新建三台VMware虚拟机，只有第一台生成密码，另外两台密码没有生成
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by dengju2020** [comment]
目前2台正常，一台异常

**Comment by dengju2020** [comment]
https://bug.yunion.io/zentao/bug-view-8513.html
