### ISSUE TITLE
添加介绍云平台基础网络相关的文档

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11389]
**What part of the document needs to be added**:

介绍云平台网络资源的分层结构：

- 二层网路的概念
- VPC 的概念
- 子网的概念
- 以及以上资源的关系

对应文档可以放到：https://github.com/yunionio/docs/tree/master/content/zh/docs/howto/network

/assign @yousong

**Comment by yousong** [comment]
https://github.com/yunionio/docs/pull/270
