### ISSUE TITLE
Add some screenshots of README.md

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11445]
**What part of the document needs to be added**:

Add some screenshots to make the README.md look better.

Thought of the following to add:

- WebUI dashboard
- All kinds of platform vminstances display page
- Multi cloud account create page

**Comment by swordqiu** [comment]
* Login page
* climc cloudshell
* monitor dashboard
* baremetal create form
* vm create form

**Comment by zexi** [comment]
PR https://github.com/yunionio/docs/pull/299 add chinese version screenshots.
