### ISSUE TITLE
The difference between the commercial version and the community version. (商业版和社区版区别)

### ISSUE THREAD

**Issue by hanyouqing** [yunionio/cloudpods#11452]
**What part of the document needs to be added**:
More details of [the difference between the commercial version and the community version](https://www.yunion.cn/version/index.html) is expected.

Any questions about the topic are welcome.

**Comment by dong0320** [comment]
简单对比：https://www.yunion.cn/comparison/index.html
详细功能对比： https://www.yunion.cn/comparison-info/index.html
