### ISSUE TITLE
Document of how to add host networks

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11469]
**What part of the document needs to be added**:

Host service supports add more network bridges of different wires, we should document it.

```bash
$ cat /etc/yunion/host.conf  | grep -A 2 networks
networks:
- eth0/br0/10.168.26.187
- eth1/br1/wire-x
```

/assign @swordqiu

**Comment by dong0320** [comment]
https://www.cloudpods.org/zh/docs/onpremise/network/faq/addnetwork/
