### ISSUE TITLE
阿里云 windows虚机创建失败

### ISSUE THREAD

**Issue by ch476558901** [yunionio/cloudpods#11481]
地域及可用区：北京 | 阿里云 华北2(北京) | 阿里云 华北2 可用区A
规格：4C8G
镜像：Windows Server 2016 / Windows Server  2016 数据中心版 64位英文版 GPU定制

日志：
{
    "__reason__": "Failed to create specification ecs.t5-c1m2.xlarge.processCommonRequest: SDK.ServerError\nErrorCode: InvalidParameter.NotMatch\nRecommend: https://error-center.aliyun.com/status/search?Keyword=InvalidParameter.NotMatch&source=PopGw\nRequestId: 7E898751-ECB3-49E6-B887-09C0CCE32DDD\nMessage: the provided 'InstanceType -> instance_type_family: ecs.t5' and 'Image -> instance_type_family: include[ecs.gn5t]' are not matched.",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "ERROR"
}

{
    "__reason__": {
        "reason": {
            "__reason__": "Failed to create specification ecs.t5-c1m2.xlarge.processCommonRequest: SDK.ServerError\nErrorCode: InvalidParameter.NotMatch\nRecommend: https://error-center.aliyun.com/status/search?Keyword=InvalidParameter.NotMatch&source=PopGw\nRequestId: 7E898751-ECB3-49E6-B887-09C0CCE32DDD\nMessage: the provided 'InstanceType -> instance_type_family: ecs.t5' and 'Image -> instance_type_family: include[ecs.gn5t]' are not matched.",
            "__stage__": "OnDeployGuestComplete",
            "__status__": "ERROR"
        },
        "stage": "OnDeployGuestComplete"
    },
    "__stage__": "OnDeployGuestDescComplete",
    "__status__": "error",
    "__task_name__": "GuestDeployTask"
}

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/123224187-26a70e80-d504-11eb-85c5-3efb9808dc03.png)
![image](https://user-images.githubusercontent.com/13750250/123224245-3a527500-d504-11eb-88b9-a0711cbdf168.png)
镜像和套餐有冲突，可以换个非GUP的镜像试下

**Comment by ioito** [comment]
#11232

**Comment by ioito** [comment]
类似于 #11232

**Comment by ioito** [comment]
3.8 支持创建时候后自动切换使用同配置的其他套餐
开启方法:
climc service-config --config enable_auto_switch_server_sku=true region2
