### ISSUE TITLE
创建虚机时，很多区域和可用区无法选择

### ISSUE THREAD

**Issue by ch476558901** [yunionio/cloudpods#11482]
接入的阿里云
貌似创建的只能是阿里云上已有资源的区域

**Comment by ioito** [comment]
目前是这样设计的，原因三点
1. 管理员可以按照规划，在不同的区域下创建ip子网，限制普通用户创建资源的区域
2. 公有云也是需要先创建子网后(可能是要跳转创建，或默认创建)，才能创建虚拟机
3. 避免页面出现下拉框选项太多(同时对接多个云平台)
