### ISSUE TITLE
部署开源版本待优化的地方

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11485]
**What happened**:

部署最新的 v3.7 开源版本遇到了以下的问题，需要改进：

1. 使用 ocboot 按照 https://www.cloudpods.org/zh/docs/quickstart/allinone/ 文档进行安装，到最后一步会因为内核替换重启系统，但是没有提示用户登录 web 页面的用户名和密码
2. 登录前端后，需要手动启用宿主机并刷新页面，才能新建虚拟机
3. 导入镜像 https://iso.yunion.cn/vm-images/CentOS-7.6.1810-20210614.qcow2 新建虚拟机会失败

**Environment**:

- OS (e.g. `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): yn kernel

**Comment by zhasm** [comment]
https://github.com/yunionio/ocboot/pull/148
https://github.com/yunionio/ocboot/pull/149

**Comment by zexi** [comment]
> [yunionio/ocboot#148](https://github.com/yunionio/ocboot/pull/148)
> [yunionio/ocboot#149](https://github.com/yunionio/ocboot/pull/149)

这个 PR 解决第一个 “到最后一步会因为内核替换重启系统，但是没有提示用户登录 web 页面的用户名和密码” 的问题。

**Comment by zexi** [comment]
> 登录前端后，需要手动启用宿主机并刷新页面，才能新建虚拟机
该问题已经在 v3.7.4 修复
> 导入镜像 https://iso.yunion.cn/vm-images/CentOS-7.6.1810-20210614.qcow2 新建虚拟机会失败
目前测试该镜像没有问题，应该还是因为当时用户的环境资源太紧张导致

**Comment by zexi** [comment]
可以使用 ocboot 升级到最新的 v3.7.5 版本，参考文档：https://www.cloudpods.org/zh/docs/setup/upgrade/

```bash
# 比如我的环境目标机器 ip 是 10.168.26.185，升级到 v3.7.5
./ocboot.py upgrade  10.168.26.185 v3.7.5
```
