### ISSUE TITLE
通过系统镜像新建VMware虚拟机不应该报磁盘分配失败

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11505]
**What happened**:
{
    "__reason__": {
        "reason": {
            "image_id": "0374c1d1-de47-4672-8ba1-3d9352ca9c8b",
            "reason": {
                "__reason__": "runtime error: invalid memory address or nil pointer dereference",
                "__stage__": "OnImageCacheComplete",
                "__status__": "error"
            }
        },
        "stage": "OnImageCacheComplete"
    },
    "__stage__": "OnDiskPrepared",
    "__status__": "error",
    "__task_name__": "StorageCacheImageTask"
}
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by rainzm** [comment]
fixed
