### ISSUE TITLE
win虚机远程桌面ctrl+ alt +del 显示不支持，但貌似实际可用

### ISSUE THREAD

**Issue by ch476558901** [yunionio/cloudpods#11513]
![image](https://user-images.githubusercontent.com/74457737/123623792-73f6e900-d840-11eb-91de-66c5f61b0eca.png)

**Comment by zexi** [comment]
感谢反馈，我们验证下。

**Comment by zexi** [comment]
@ch476558901 这个虚拟机是不是其它云平台导入过来的？看起来不像是我们平台私有云的 vnc 终端。

**Comment by ch476558901** [comment]
> @ch476558901 这个虚拟机是不是其它云平台导入过来的？看起来不像是我们平台私有云的 vnc 终端。

这台虚拟机是在平台上创建的阿里云虚拟机

**Comment by ioito** [comment]
是使用什么vnc远程连接软件？我看和阿里云官方的vnc连接界面不一样

**Comment by zexi** [comment]
> 是使用什么vnc远程连接软件？我看和阿里云官方的vnc连接界面不一样

这个应该是我们内部的 webconsole 服务设置跳转的阿里云 vnc 连接，估计是这个连接地址的问题

**Comment by ioito** [comment]
https://g.alicdn.com/aliyun/ecs-console-vnc2/0.0.5/index.html?instanceId=i-2ze7227j5jwrfge53ad8&isWindows=True&password=HG4qc4&protocol=aliyun&vncUrl=wss%253A%252F%252Fbj01-vncproxy.aliyun.com%252Fwebsockify%252F%253Fs%253DNXN65JhJcKMq%25252B81BXxSSQnvvPDgmO4iQKIBGkKevWVkl%25252BKxOF6VE8gJMeLptNQh5#/
我们使用的是这个api，现在的url版本是0.0.5，替换到官方提供的最新0.0.8 依然可以复现这个问题，我们会反馈给阿里云官方，如有最新消息，会在这个issue下说明

**Comment by ioito** [comment]
这个问题已经找到原因是url参数isWindows=True不生效,需要isWindows=true才可以，上面的pr是修复这个问题
