### ISSUE TITLE
希望在cloudpods web页面添加一个 对磁盘cache driver变更的功能支持

### ISSUE THREAD

**Issue by centosredhat** [yunionio/cloudpods#11535]
**What would you like to be added**:
无论是更改系统盘还是挂载盘，都只能通过后台命令的方式对cache策略和driver驱动进行变更。

cache跟driver的变更，相对而言对用户虚拟机可用性影响还是挺大的，建议权限只能管理员角色操作，同时添加一点提示以告知不同选项的区别。

**Comment by zexi** [comment]
好的，目前添加了命令行修改的文档：

https://www.cloudpods.org/zh/docs/howto/compute/vminstance/tutorial/change_disk_driver/

后续会添加 web 界面的支持。

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/623
添加到master了

**Comment by zexi** [comment]
Thx.
