### ISSUE TITLE
docker image arm64 compatibility 

### ISSUE THREAD

**Issue by zhasm** [yunionio/cloudpods#11536]
**What happened**:
the following docker images currently do not support arm64:
[ERROR] registry.cn-beijing.aliyuncs.com/yunionio/baremetal-agent:v3.7.5
[ERROR] registry.cn-beijing.aliyuncs.com/yunionio/climc:v3.7.5
[ERROR] registry.cn-beijing.aliyuncs.com/yunionio/web-ee:v3.7.5

please update the base images.

**Comment by zexi** [comment]
Thanks for your report. I'll check this.

**Comment by zexi** [comment]
Baremetal-agent not support arm64 currently.
