### ISSUE TITLE
公有云上，云主机集群安装高可用失败

### ISSUE THREAD

**Issue by zhasm** [yunionio/cloudpods#11546]
安装过程遇到的问题：
* 在公有云上的云主机，不能设置 vip；db 不是 双主模式，因此不能安装高可用；解决方案：安装1 primary + 2master(host) 模式，没有安装高可用。
* 云主机之间端口不通, 6443, 2379, 2380等等，因此 2 和3 在join 1时 卡住；请客户全开放端口，解决。
* 所用的数据库是 5.6.8 的 mysql；而不是 mariadb；遇到兼容性问题。替换为我方的 mariadb，解决。

请在文档中说明上述注意事项，例如云主机是否允许部署高可用、常用端口开放策略（云主机之间端口全开放）、所用数据库版本选择（最好选择 mariadb-server 默认版本，不要使用 mysql 5.6及以下版本，防止索引长度 bug： Index column size too large. The maximum column size is 767 bytes.）

**Comment by dong0320** [comment]
https://github.com/yunionio/docs/pull/733

content/zh/docs/setup/config.md
