### ISSUE TITLE
私有云自建 k8s 集群存在的问题记录

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11549]
**What happened**:

- [ ] 安装前节点主机名不能是IP地址或者以数字开头，IP地址会导致k8s初始化失败，以数字开头节点无法注册，region报错Send error name starts with letter, and contains letter, number and - only 这点在咱们的安装文档里面我没有看到注明不让用IP地址或者数字
- [ ] k8s的etcd一直输出日志remote error: tls: bad certificate", ServerName "" 不知道是哪个组件输出的日志，另外建议    咱们在多节点安装部署时，建议primariy节点+master节点为3或者5 达到etcd高可用的效果
- [ ] 现在不支持高可用部署，比如部署完成的 k8s 集群 kubeconfig 和 node 的 kubelet.conf 都没有只想 HA 的 apiserver 地址
- [ ] VPC 子网的虚拟机目前不支持创建 k8s 集群
- [ ] 后端对 etcd 节点的奇数校验没有生效

**Environment**:

- OS (e.g. `cat /etc/os-release`): CentOS 7
- Version: v3.6.18

**Comment by solemnpending** [comment]
以字母开头创建的集群名称，不能大写，否则会导致创建k8s失败；

**Comment by zexi** [comment]
> 以字母开头创建的集群名称，不能大写，否则会导致创建k8s失败；

感谢反馈，能够复现

**Comment by solemnpending** [comment]
k8s创建节点时，每个节点磁盘只能限制到500GB，不能够满足个别生产环境的需求；

**Comment by zexi** [comment]
> 以字母开头创建的集群名称，不能大写，否则会导致创建k8s失败；

这个问题在这个 PR 里面解决了：https://github.com/yunionio/kubecomps/pull/43/files#diff-c00ee8365dacc17addf68666fbc3a545ec056c5be071ed40cd2bed98b6bca562R147
