### ISSUE TITLE
Unable to initialize a VM with VG name being same as the node where host-deployer is located

### ISSUE THREAD

**Issue by rainzm** [yunionio/cloudpods#11558]
**What happened**:

Unable to initialize a VM with VG name being same as the node where host-deployer is located

**Environment**:

- OS (e.g. `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux test-69-onecloud01 3.10.0-1062.4.3.el7.yn20191203.x86_64 #1 SMP Tue Dec 3 15:53:43 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rainzm** [comment]
解决此bug需要把host-deployer中的lvm2更新到 2.03.12 版本，利用其 devices options可以通过pv来过滤出正确的vgid，进而重命名，以防止重名带来的问题。lvm2.03.12 只在 centos 8 stream 中发现。
因此主要有两种方式解决此问题：
1. 如何为现在使用的fedora安装lvm2.03.12
2. 使用 centos 8 stream，目前只找到了一个非官方的 x86 架构的docker image，所以我们需要自己build arm64的docker image

**Comment by zexi** [comment]
@rainzm 这个镜像可以用吗？
https://hub.docker.com/layers/centos/library/centos/centos8/images/sha256-7723d6b5d15b1c64d0a82ee6298c66cf8c27179e1c8a458e719041ffd08cd091?context=explore

**Comment by rainzm** [comment]
使用 centos 8 作为base image，然后 `dnf install centos-release-stream -y` 就可以使用 centos stream repo 进而获得最新的lvm2。那么arm64的问题也解决了，centos8 docker image官方是支持arm64架构的。

**Comment by zexi** [comment]
> 使用 centos 8 作为base image，然后 `dnf install centos-release-stream -y` 就可以使用 centos stream repo 进而获得最新的lvm2。那么arm64的问题也解决了，centos8 docker image官方是支持arm64架构的。

👍🏻
