### ISSUE TITLE
ISO安装了OpenEuler 的虚拟机，保存镜像 root 密码不可用

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11550]
**What happened**:

平台上用ISO安装了OpenEuler的虚拟机，装完之后保存为qcow2镜像，然后用镜像安装虚拟机时配置的root密码不可用，另外镜像导入到openstack中会出现网卡名字不是eth0导致虚拟机无可用网络问题

**Environment**:

- OS (e.g. `cat /etc/os-release`): CentOS 7
- Version: v3.6.18

**Comment by mytting** [comment]
![image](https://user-images.githubusercontent.com/50027289/124689083-76c1a000-df0a-11eb-80a4-51ace685d55b.png)
OpenEuler用的是lvm分区

**Comment by zexi** [comment]
我这边能复现 OpenEuler 使用 lvm 保存镜像启动不了的问题， @rainzm 能帮忙看下吗？

![Uploading image.png…]()

**Comment by zexi** [comment]
通过把保存的镜像用 nbd 挂载起来，然后用 lvs 看到 VG 的 name 被换成 uuid 了

```bash
sh-5.0# lvs
  WARNING: Device mismatch detected for 9edc838b-9ebc-4c92-8dc8-bee6ea4faf69/swap which is accessing /dev/nbd11p2 instead of /dev/nbd0p2.
  WARNING: Device mismatch detected for 9edc838b-9ebc-4c92-8dc8-bee6ea4faf69/root which is accessing /dev/nbd11p2 instead of /dev/nbd0p2.
  LV   VG                                   Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root 9edc838b-9ebc-4c92-8dc8-bee6ea4faf69 -wi-a----- 27.09g
  swap 9edc838b-9ebc-4c92-8dc8-bee6ea4faf69 -wi-a-----  1.90g
```

应该是代码里面探测镜像操作系统导致的，里面有个逻辑是 rename LVM 的 VG。

> 我这边能复现 OpenEuler 使用 lvm 保存镜像启动不了的问题， @rainzm 能帮忙看下吗？
> 
> ![image](https://user-images.githubusercontent.com/10767027/124863131-2a995d00-dfe9-11eb-90b2-5d33785cdbfd.png)

**Comment by rainzm** [comment]
问题已经确认：
LVM中的LV active 之后的 device path 有两种：/dev/{vgname}/{lvname} 或者 /dev/mapper/{vgname}-{lvname}
代码中只对前一种进行了探测，导致没有找到可用的 device，因此对虚拟机的初始化工作会失败。
另外，也出发了另外一个bug，导致在进行清理工作时vg name没有被正确还原，所以由此镜像创建出来的机器无法正确找到设备。

**Comment by rainzm** [comment]
基于上述PR，测试完成：
1. 保存的镜像可以正确识别OpenEuler系统
2. 保存的镜像创建出来的机器能够完成初始化工作并正确开机

**Comment by zexi** [comment]
@mytting OpenEuler 相关问题已经修复，可以使用下面的命令升级环境里面的 host 服务镜像，然后再测试下：

```bash
# 升级 host 服务
$ kubectl set image  -n onecloud daemonset/default-host  host=registry.cn-beijing.aliyuncs.com/yunionio/host:v3.7-lzx-0708-1

# 升级 host-deployer 服务
$ kubectl set image  -n onecloud daemonset/default-host-deployer  *=registry.cn-beijing.aliyuncs.com/yunionio/host-deployer:v3.7-lzx-0708-1
```
