### ISSUE TITLE
阿里云账号同步磁盘问题

### ISSUE THREAD

**Issue by ch476558901** [yunionio/cloudpods#11578]
问题描述：有问题的磁盘在阿里云上是未挂载虚拟机的，阿里云账号添加到cloudpods后，发现同步下来的只有已挂载虚拟机的磁盘，未挂载虚拟机的磁盘没有同步到cloudpods

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/124593781-a2547400-de91-11eb-8296-f0ba6c34edb4.png)

@ch476558901 麻烦尝试在这里搜索下，是否可以搜索到未挂载的磁盘

**Comment by ch476558901** [comment]
重新导入账号能同步下来了，感谢支持
