### ISSUE TITLE
阿里云对象存储容量有7.4T，平台阿里云账号详情资源统计中  对象存储容量显示为93M

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#11608]
**What happened**:

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by hoganlxj** [comment]
平台中因为阿里云上对象存储数量较大，跳过平台的自动同步，该值应该返回 -1

**Comment by dong0320** [comment]
ok
