### ISSUE TITLE
前端选择中文，但是控制面板的 panel title 还是英文

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11616]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/125017923-a5747d80-e0a6-11eb-89cb-7e46a7c286aa.png)

**Environment**:

- Version: v3.7.5

**Comment by Easy-MJ** [comment]
目前title的数据是用户自己配置的，因此不能区分中英文，用户可以自己在配置磁贴修改磁贴名称
![a01](https://user-images.githubusercontent.com/11886313/125020343-42d1b080-e0ab-11eb-8e6d-1290fc860de4.png)

**Comment by zexi** [comment]
好的，不过这个体验并不好，后续可能要想办法优化下。
