### ISSUE TITLE
storage providers missing generic S3 providers

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#11625]
**What happened**:
on S3 bucket list, the provider filter seems missing the provider of generic S3 provider

![image](https://user-images.githubusercontent.com/1121362/125173611-c4802600-e1f2-11eb-9897-9335bd98b9ea.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/635
