### ISSUE TITLE
如何构建 kubecomps项目

### ISSUE THREAD

**Issue by apodemakeles** [yunionio/cloudpods#11632]
build kubeserver/main.go时失败，是缺少embed.THANOS_3_2_2_TGZ等几个变量的定义，这几个变量是通过代码生成的，要读取../../../static文件夹，但在项目源码中找不到。

**Comment by zexi** [comment]
@apodemakeles https://github.com/yunionio/kubecomps/pull/40 这个 PR 在 README 添加了一些编译的步骤。

**Comment by apodemakeles** [comment]
多谢
