### ISSUE TITLE
onecloud同步阿里云rds

### ISSUE THREAD

**Issue by YuXiaoDou** [yunionio/cloudpods#11689]
**onecloud同步阿里云rds，详情中同步出来的信息不全**:

**子网，最大IOPS，为空。未被同步下来。**:
![image](https://user-images.githubusercontent.com/82626778/126430506-b46ce33e-4f13-4cf5-adf8-412dbb7af9b1.png)

**Comment by zexi** [comment]
/assign @ioito 
麻烦看下这个问题

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/11674 网络同步已经在这里修复过了
iops不在rds实例上维护，是跟随在套餐上的。

**Comment by zexi** [comment]
@YuXiaoDou 这个问题两天前才修复，还没有正式发布新版本，麻烦用下面的命令暂时更新下环境里面的服务，然后再同步看下信息是否正确：

```bash
kubectl set image  -n onecloud deployment/default-region *=registry.cn-beijing.aliyuncs.com/yunionio/region:v3.7.0721.0
```

**Comment by YuXiaoDou** [comment]
> @YuXiaoDou 这个问题两天前才修复，还没有正式发布新版本，麻烦用下面的命令暂时更新下环境里面的服务，然后再同步看下信息是否正确：
> 
> ```shell
> kubectl set image  -n onecloud deployment/default-region *=registry.cn-beijing.aliyuncs.com/yunionio/region:v3.7.0721.0
> ```

好的，感谢支持。

**Comment by YuXiaoDou** [comment]
我已经升级至v3.7，但是详情展示依旧有问题
![image](https://user-images.githubusercontent.com/82626778/130719636-b42f8640-54b2-4318-ab24-71afc41348ea.png)
