### ISSUE TITLE
CloudShell UE improvements

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#11714]
**What would you like to be added**:
CloudShell UE improvements
1. auto adjust the height of main screen
2. auto adjust the size of cloudshell height
-----
目前存在问题是，打开cloudshell后，1. 上方区域的底部会被遮蔽，2. cloudshell的高度不是自动调整，会出现先最后一行文字在窗口显示区域的情况。导致用户体验不好，需要改进。

**Comment by zexi** [comment]
PR https://github.com/yunionio/dashboard/pull/661 fixes this issue.
