### ISSUE TITLE
用户信息页面，消息接收设置模块不断加载中

### ISSUE THREAD

**Issue by enhellowhy** [yunionio/cloudpods#11797]
进入用户信息页面时，消息接收设置模块不断加载中，点击“修改”，信息会显示出来

**Comment by tb365** [comment]
您能提供一下 浏览器控制台日志吗？
chrome > 开发者工具 >  console. 请看一下是否有报异常。

**Comment by rainzm** [comment]
可以提供一下版本嘛？可以通过以下方式获取：
https://www.cloudpods.org/zh/docs/setup/upgrade/#%E6%9F%A5%E7%9C%8B%E5%BD%93%E5%89%8D%E7%89%88%E6%9C%AC
可以提供一下截图以辅助描述bug嘛？

**Comment by enhellowhy** [comment]
集群版本：v3.7.6

![image](https://user-images.githubusercontent.com/18282440/128034935-117fe3cb-6840-4bb6-94a0-a241a076abdd.png)

浏览器console输出如下：
![image](https://user-images.githubusercontent.com/18282440/128035206-16f56251-e547-4fa9-a5d1-7ee4f1cc3a12.png)

点击修改，恢复:
![image](https://user-images.githubusercontent.com/18282440/128035385-eba12473-7d82-434f-95ee-24110f1d9c11.png)

**Comment by tb365** [comment]
感谢，我在本地环境验证一下。

**Comment by tb365** [comment]
> 集群版本：v3.7.6
> 
> ![image](https://user-images.githubusercontent.com/18282440/128034935-117fe3cb-6840-4bb6-94a0-a241a076abdd.png)
> 
> 浏览器console输出如下：
> ![image](https://user-images.githubusercontent.com/18282440/128035206-16f56251-e547-4fa9-a5d1-7ee4f1cc3a12.png)
> 
> 点击修改，恢复:
> ![image](https://user-images.githubusercontent.com/18282440/128035385-eba12473-7d82-434f-95ee-24110f1d9c11.png)

的确是页面的bug， 将在今天修复。

**Comment by zexi** [comment]
@tb365 等修复的 PR 合并后，再关闭 issue

**Comment by zexi** [comment]
商业版功能，已修复

**Comment by enhellowhy** [comment]
> 商业版功能，已修复

开源版本能不能修复下，感激orz

**Comment by zexi** [comment]
> > 商业版功能，已修复
> 
> 开源版本能不能修复下，感激orz

开源版本的前端没有这个页面吧？ @tb365

**Comment by enhellowhy** [comment]
> > > 商业版功能，已修复
> > 
> > 
> > 开源版本能不能修复下，感激orz
> 
> 开源版本的前端没有这个页面吧？ @tb365

有这个页面资源组件，我加了路由可以展示，所以也有这个问题。

**Comment by tb365** [comment]
> > > > 商业版功能，已修复
> > > 
> > > 
> > > 开源版本能不能修复下，感激orz
> > 
> > 
> > 开源版本的前端没有这个页面吧？ @tb365
> 
> 有这个页面资源组件，我加了路由可以展示，所以也有这个问题。

开源版目前是没有这个页面的。由于部分组件在开源版本中并不支持，目前这个页面去掉了的。
您把路由加上，功能上是存在问题的。

**Comment by zexi** [comment]
@enhellowhy 这个页面的配置应该还依赖其它的界面，那部分在商业版本里面，这部分代码放在开源的前端里面也不太干净，之后应该会重构下放到商业版本里面去，或者把这部分功能开放到开源版本。
目前如果要使用此功能，请参考文档切换成开源版本：
https://www.cloudpods.org/zh/docs/setup/ce-ee-switch/

**Comment by enhellowhy** [comment]
好吧，主要是我们要做一些二次开发，可能没办法直接用商业版，还是感谢你们~
