### ISSUE TITLE
【编排】在管理后台通过编排创建资源，指定了其他域，最后编排创建在了default域

### ISSUE THREAD

**Issue by dong0320** [yunionio/cloudpods#11924]
**What happened**:
![image](https://user-images.githubusercontent.com/43448298/129524868-40793e09-8054-4efb-b991-6e4837600e4b.png)
![image](https://user-images.githubusercontent.com/43448298/129524888-c83774d6-2918-49a1-8967-5dff0b565532.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
https://github.com/yunionio/kubecomps/pull/115
