### ISSUE TITLE
Open stack 访问 API 修改

### ISSUE THREAD

**Issue by uriddle** [yunionio/cloudpods#11981]
1.系统在纳管 Open stack 资源池时，只需要指定 authUrl ， 例如： http://ip:port/v3/; 
然后系统在同步资源时，会先获取访问API再查询基础资源；

2.请求帮助：是否能通过配置的形式，修改 open stack 的访问API，例如：

    "endpoints":{
        "compute":"http://ip:port/v2.1",
        "identity":"http://ip:port/v3/",
        "image":"http://ip:port",
        "network":"http://ip:port",
        "placement":"http://ip:port",
        "volumev2":"http://ip:port/%(project_id)s",
        "volumev3":"http://ip:port/v3/%(project_id)s"
    }

**Comment by ioito** [comment]
不建议写配置，因为endpoint都在keystone里面存储，如果需要更改，建议更改keystone存放的各个组件的endpoints，这样整个系统都能自适应

**Comment by uriddle** [comment]
@ioito 你好  , 感谢及时回复。

我不会去改动keystone里面存放的各个组件的endpoints。

我的意思是在接入open stack 时，系统获取到它的访问 API 是否有存储、修改的地方，因为现在因为网络的原因，从open stack接口获取的访问API不能直接访问。访问API如图：

![image](https://user-images.githubusercontent.com/22750410/130429033-3c174bdb-a821-4b31-b145-a691bea32ad0.png)


我需要自己去设置这里的所以端点，而不是通过访问 api 获取这些端点。

**Comment by zexi** [comment]
@uriddle 现在不支持在平台配置 openstack 的 endpoint，我们也是直接调用 openstack keystone api 拿到 endpoint，然后去访问各个 service 的 endpoint api。

可以试下创建一个 http 代理能否解决这个问题：
![image](https://user-images.githubusercontent.com/10767027/130442975-42293420-b43d-4b2e-9c8d-ec1e08baa8fd.png)

**Comment by uriddle** [comment]
好的
