### ISSUE TITLE
虚拟节点创建到指定的宿主机上

### ISSUE THREAD

**Issue by lileih** [yunionio/cloudpods#11982]
你好，请问如何把虚拟机创建到指定的宿主机上，期待回复，谢谢。

**Comment by zexi** [comment]
> 你好，请问如何把虚拟机创建到指定的宿主机上，期待回复，谢谢。

你好，前端可以通过在新建虚拟机表单的高级选项指定宿主机：
![image](https://user-images.githubusercontent.com/10767027/130715605-2de11015-ab01-4277-a2e9-68a0148f8ce2.png)

命令行的话，可以通过 *--prefer-host* 参数指定：

```
$ climc server-create --prefer-host $host_id_or_name
```

**Comment by zexi** [comment]
> 你好，请问如何把虚拟机创建到指定的宿主机上，期待回复，谢谢。

你好，前端可以通过在新建虚拟机表单的高级选项指定宿主机：
![image](https://user-images.githubusercontent.com/10767027/130715605-2de11015-ab01-4277-a2e9-68a0148f8ce2.png)

命令行的话，可以通过 *--prefer-host* 参数指定：

```
$ climc server-create --prefer-host $host_id_or_name
```
