### ISSUE TITLE
3.8 前端不应该访问费用相关 api

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11994]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/130635915-d63569e9-d8aa-4609-aae3-0293260c618d.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/1022
