### ISSUE TITLE
3.8 前端多云管理图标缺失

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#11993]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/130635742-f46d35a9-1eb3-4998-a60f-7a8587b99ae9.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

/assign @Easy-MJ

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/830
