### ISSUE TITLE
rds详情信息未被同步下来

### ISSUE THREAD

**Issue by YuXiaoDou** [yunionio/cloudpods#12002]
**What happened**:
v3.7版本rds功能模块同步下来之后详情信息与阿里云不一致
![image](https://user-images.githubusercontent.com/82626778/130758926-8bfe72dd-8d98-47a4-aa4d-a345cf852ef3.png)

**Comment by YuXiaoDou** [comment]
之前提过，然后给出的解决方案是从v3.6升级到v3.7，目前已经升级到3.7，详情信息没有改变，依旧是错误的

**Comment by zexi** [comment]
@YuXiaoDou 修复这个问题的代码才合并，预计这周 5 会发布一个 v3.7.7 的小版本，麻烦到时候升级到这个版本。
