### ISSUE TITLE
在系统镜像点击新建虚拟机后应该加上cpu架构的参数

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#12046]
**What happened**:
在系统镜像中，选择x86的镜像 点击新建虚拟机
虚拟机新建界面 镜像选择的是arm架构的值
![image](https://user-images.githubusercontent.com/32036395/131064470-23700094-cc7f-420d-a766-056711c70702.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/1095
