### ISSUE TITLE
VMware模板创建主机报vmdk not found错误

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#12109]
**What happened**:
![image](https://user-images.githubusercontent.com/1121362/132104363-e54473c0-6d61-4d15-b50a-1d13bf5b7823.png)

实际的模板镜像是：

![image](https://user-images.githubusercontent.com/1121362/132104395-ca1d44ba-fc6b-4d52-a917-880e606bd117.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by rainzm** [comment]
经过验证，看上去就是这个模板不可用。
