### ISSUE TITLE
Support for Proxmox

### ISSUE THREAD

**Issue by smilebasti** [yunionio/cloudpods#12111]
**What would you like to be added**:
As proxmox is my main Hypervisor but i am planning on going hybrid cloud. I found cloudpods but no documentation if Proxmox is supported. Would be a great addition.

**Comment by zexi** [comment]
We will consider supporting Proxmox in the future, maybe implemented in release 3.10.

**Comment by swordqiu** [comment]
https://github.com/yunionio/cloudpods/pull/14889
