### ISSUE TITLE
怎么修改glance在宿主机上存储镜像的地址

### ISSUE THREAD

**Issue by xionghao-github** [yunionio/cloudpods#12313]
我已经更改了glance的configmap为/home/*****
并且将glance的deployment的mountpath已做了修改为/home，可当我每次保存deployment后，再次查看时，这个mountpath就会又被改成默认的/opt/****，请教下，这个改如何修改，盼回复。十分感谢

**Comment by zexi** [comment]
目前 glance 建议修改 mountpath 为 /opt/cloud/workspace/data/glance/images 以外的路径，如果一定要修改，可以修改 default-glance deployment 里面的 volumes 为 hostPath

```bash
$ kubectl edit deployment -n onecloud default-glance

```
