### ISSUE TITLE
物理机转宿主机时，选择IP子网时不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#12352]
**What happened**:
物理机转宿主机，磁盘raid卡配置 选择 默认配置（最高冗余） ，网络 前端默认选择自动调度时 报错
![image](https://user-images.githubusercontent.com/32036395/135719440-769820ad-6414-4e8a-8ba5-529a019e9570.png)

**Environment**:
 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by Easy-MJ** [comment]
https://github.com/yunionio/dashboard/pull/1414
