### ISSUE TITLE
Azure云账号点击全量同步后不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#12454]
**What happened**:

[info 211018 16:35:20 taskman.(*STask).SetStageFailed(tasks.go:665)] XXX TASK CloudAccountSyncInfoTask failed: {"__reason__":"SyncCallSyncAccountTask: account.syncAccountStatus: providers[i].prepareCloudproviderRegions: CloudproviderCapabilityManager.setCapabilities: manager.TableSpec().InsertOrUpdate: query after insert failed: sql: no rows in result set","__stage__":"OnCloudaccountSyncReady","__status__":"ERROR"} on stage OnCloudaccountSyncReady
[info 211018 16:35:20 taskman.(*STask).NotifyParentTaskComplete(tasks.go:689)] notify_parent_task_complete: CloudAccountSyncInfoTask params {"__failed_reason":{"reason":{"__reason__":"SyncCallSyncAccountTask: account.syncAccountStatus: providers[i].prepareCloudproviderRegions: CloudproviderCapabilityManager.setCapabilities: manager.TableSpec().InsertOrUpdate: query after insert failed: sql: no rows in result set","__stage__":"OnCloudaccountSyncReady","__status__":"ERROR"},"stage":"OnCloudaccountSyncReady"},"__request_context":{"lang":"zh-CN","request_id":"23b67e-4683bf","service_name":"compute_v2","trace":{"debug":true,"duration":0,"id":"0.0","kind":"SERVER","local_endpoint":{"addr":"default-region","port":30888,"service_name":"compute_v2"},"name":"create","parent_id":"0","remote_endpoint":{"addr":"10.111.139.92","port":42676,"service_name":"apigateway"},"shared":false,"tags":{"resource":"cloudaccounts"},"timestamp":"2021-10-18T08:35:13.788746Z","trace_id":"99d72db9"}},"__stages":[{"complete_at":"2021-10-18T08:35:15Z","name":"on_init"},{"complete_at":"2021-10-18T08:35:20Z","name":"OnCloudaccountSyncReady"}]}

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
已解决
