### ISSUE TITLE
lbagent needs to restart to make new cert effective

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#12552]
**What happened**:
After updating cert of a https listener, the new cert did not take effect. Need to restart yunion-lbagent manually.

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/10767027/220368302-385e1c21-35c6-4aba-a5de-424363e050bb.png">
经过测试发现替换 listenser 的证书是生效的，没有问题，listenser 关联新的证书后，haproxy 对应 lb 的 crt 配置也变化了。
测试的 lbagent 版本为 v3.9.5。
![701ed91c-a1c9-4fa5-ac48-9c6fab241960](https://user-images.githubusercontent.com/10767027/220368455-bc02e1b2-7e21-4b0c-8c98-2ae7972fd2b2.jpeg)
以后遇到具体情况再分析
