### ISSUE TITLE
Vm`s not able to communicate with outside networks

### ISSUE THREAD

**Issue by Opswatch** [yunionio/cloudpods#12624]
I enabled the eip gateway, rebooted the all in one host, created 2 eip and assigned it to two vms, the vms can communicate to each other and the host using the eip network but their not able to communicate to the outside or ping the eip network gateway, is there something im missing in the setup?

**Comment by swordqiu** [comment]
@Opswatch How did you setup EIP gateway? In allinone setup, the most simple way is to adjust the follow configuration:

```
# /etc/yunion/host.conf
sdn_enable_eip_man: true
```
Then restart the default-host pod.

```
kubectl -n onecloud rollout restart daemonset default-host
```

Please make sure that Switch forward traffic destined to the EIP address pool to this host!

**Comment by Opswatch** [comment]
I setup the EIP gateway as in your example above so I have

home gateway/router(172.16.2.1) ----> all in one host ( 172.16.2.153 ) -----> vm with eip ( 172.16.2.156 )

the all in one host has no problems pinging the gateway/router and is also able to ping vms on their eips but the traffic seems to be contained to the all in one host, I checked the ovn settings and it seems to be working, maybe im still missing something in the setup?, the all in one host is running centos 7 minimal, default setup and then I ran the ocboot all in one setup, I then enabled the eip gateway.

**Comment by swordqiu** [comment]
I think you might need to configure another IP range of EIP, e.g. 172.16.4.0/24. Then, setup a static route on router:

```
ip route add 172.16.4.0/24 via 172.16.2.153
```

Then, allocate EIP from 172.16.4.0/24.

If EIP is allocated from 172.16.2.0/24, which is in the same subnet as router, the router will first try to arp resolve 172.16.2.156, but nobody will response this arp.

**Comment by Opswatch** [comment]
Awesome, thanks for the help that is what it was, Im able to communicate out now.
