### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by zzhzzhzz** [yunionio/cloudpods#12669]
Hello, after seeing the architecture diagram, I am thinking about how region sends the required information to other clients, such as Aliyuncli, to prepare for their access. Or I want to know whether my thinking is wrong. Could you please explain？

**Comment by swordqiu** [comment]
Region maintains a data structure called cloudaccount, which stores the credential to access a cloud provider. For example, a cloudaccount for Aliyun stores the AcessKey/SecretKey for an Aliyun account. The information of cloudaccount was input by administrator of the platform. Region will call API of cloud provider with the credential to pull list of resources or take action on resources, e.g. create a VM instance or start a VM.

**Comment by zzhzzhzz** [comment]
> Region maintains a data structure called cloudaccount, which stores the credential to access a cloud provider. For example, a cloudaccount for Aliyun stores the AcessKey/SecretKey for an Aliyun account. The information of cloudaccount was input by administrator of the platform. Region will call API of cloud provider with the credential to pull list of resources or take action on resources, e.g. create a VM instance or start a VM.

Hello, I would like to ask another question, using croma Start and run to schedule and process tasks, but I see that adding tasks to the task queue is only done once in startService, not in the multi-coroutine way, so how does the task stream into the task queue

**Comment by swordqiu** [comment]
We have an in-memory task queue, the code is at https://github.com/yunionio/cloudpods/blob/master/pkg/appsrv/workers.go. A task is enqueue by calling Run method. The going routine will consume tasks in queue.

There is another task manager whose state is maintained by database. The code in at https://github.com/yunionio/cloudpods/tree/master/pkg/cloudcommon/db/taskman. A task is scheduled by calling NewTask. The states are stored in database. The task proceeds by stages. The initial OnInit stage is called immediately after the task is created. The stage finishes by calling a remote procedure call, using at another node, e.g. a host agent. The next stage is invoke asyncronously by calling the task handler when the previous remote procuedure call finished at host agent.

**Comment by zzhzzhzz** [comment]
> We have an in-memory task queue, the code is at https://github.com/yunionio/cloudpods/blob/master/pkg/appsrv/workers.go. A task is enqueue by calling Run method. The going routine will consume tasks in queue.
> 
> There is another task manager whose state is maintained by database. The code in at https://github.com/yunionio/cloudpods/tree/master/pkg/cloudcommon/db/taskman. A task is scheduled by calling NewTask. The states are stored in database. The task proceeds by stages. The initial OnInit stage is called immediately after the task is created. The stage finishes by calling a remote procedure call, using at another node, e.g. a host agent. The next stage is invoke asyncronously by calling the task handler when the previous remote procuedure call finished at host agent.

Well, I know that task joins the task queue in that file, I would like to ask the above mentioned region to send command, is through cloudAccount and call API such as Ali cloud API, However, I found that region obtains the cloudaccount task from the database only when it starts the region service. In this case, if I want to add another cloudaccount later, do I need to restart the service service？

**Comment by swordqiu** [comment]
Not necessarily to restart thge service. Every time a new cloudaccount is created, the cloudaccount task will be started for this account.
