### ISSUE TITLE
虚拟机创建过程中若变更配置，之前填入的虚拟机其他配置不保留

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#12729]
**What happened**:
虚拟机创建过程中，若创建一个16c 64g 500g的虚拟机 ，选定后，又更改了内存为48g，
之前选定的磁盘500g 就没了回到初始值
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- centos 7.9
- Kernel (e.g. `uname -a`):
- onecloud 内核
v3.8.4

**Comment by GuoLiBin6** [comment]
解决：更改套餐时尽可能保留之前的系统盘配置信息
pr: https://github.com/yunionio/dashboard/pull/1614
