### ISSUE TITLE
details:xml_file_path /etc/libvirt/qemu not found

### ISSUE THREAD

**Issue by q316503265** [yunionio/cloudpods#12722]
导入kvm虚拟机时候提示这个目录不存在，但是宿主机目录是存在的，而且已经部署了计算节点，导入操作在宿主机进行

**Comment by zexi** [comment]
是用的 `climc servers-import-from-libvirt` 这个命令吗？
在执行这个命令的节点上 `cat  /etc/libvirt/qemu` 看下内容。

**Comment by q316503265** [comment]
> 

是的，/etc/libvirt/qemu是一个目录来的，下面都是xml文件

**Comment by zexi** [comment]
climc 是在容器里面执行还是后端宿主机上执行的？

/etc/libvirt/qemu 下面应该是类似这样的文件
```bash
$ ls /etc/libvirt/qemu
centos7.0-2.xml  centos7.0-aarch64.xml  centos7.0.xml  networks
```

如果执行 climc 的那台机器可以看到 /etc/libvirt/qemu 目录下面的文件，应该能导入成功才对。

**Comment by q316503265** [comment]
> climc 是在容器里面执行还是后端宿主机上执行的？
> 
> /etc/libvirt/qemu 下面应该是类似这样的文件
> 
> ```shell
> $ ls /etc/libvirt/qemu
> centos7.0-2.xml  centos7.0-aarch64.xml  centos7.0.xml  networks
> ```
> 
> 如果执行 climc 的那台机器可以看到 /etc/libvirt/qemu 目录下面的文件，应该能导入成功才对。

在宿主机执行的，发现你们host的容器里面没有挂载 /etc/libvirt/qemu这个目录，要自己挂载进去才能找到，而且导入kvm后获取不到磁盘信息

**Comment by zexi** [comment]
> > climc 是在容器里面执行还是后端宿主机上执行的？
> > /etc/libvirt/qemu 下面应该是类似这样的文件
> > ```shell
> > $ ls /etc/libvirt/qemu
> > centos7.0-2.xml  centos7.0-aarch64.xml  centos7.0.xml  networks
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果执行 climc 的那台机器可以看到 /etc/libvirt/qemu 目录下面的文件，应该能导入成功才对。
> 
> 在宿主机执行的，发现你们host的容器里面没有挂载 /etc/libvirt/qemu这个目录，要自己挂载进去才能找到，而且导入kvm后获取不到磁盘信息

感谢反馈，我们这边改下代码解决这个问题

**Comment by q316503265** [comment]
如上所述，挂载kvm配置目录到宿主机host的容器里面解决
