### ISSUE TITLE
ERROR: {"class":"BadRequestError","code":400,"details":"IPMI login info not correct: Ipmi can't fetch lan config"}

### ISSUE THREAD

**Issue by q316503265** [yunionio/cloudpods#12746]
物理机托管服务器导入失败，ipmi是正常的

托管pod日志如下：
[error 211125 18:43:43 ipmitool.GetSysInfo(ipmitool.go:165)] fru print 0 error: signal: killed
[error 211125 18:44:03 ipmitool.tryExecuteCommand(ipmitool.go:255)] Execute args [lan print 1] error: signal: killed, sleep 1s then try again
[warning 211125 18:44:17 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager DelayTaskWorkerManager has been busy for 2 cycles...
[warning 211125 18:44:17 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager bm_register_worker has been busy for 2 cycles...
[error 211125 18:44:24 ipmitool.tryExecuteCommand(ipmitool.go:255)] Execute args [lan print 1] error: signal: killed, sleep 2s then try again
[error 211125 18:44:46 ipmitool.tryExecuteCommand(ipmitool.go:255)] Execute args [lan print 1] error: signal: killed, sleep 4s then try again

ipmi的lan通道是1

**Comment by zexi** [comment]
bmc 是否打开了 `IPMI Over Lan` 的功能？

**Comment by q316503265** [comment]
> bmc 是否打开了 `IPMI Over Lan` 的功能？

开启了的，我用另外一台服务器测试脚本是提示成功了，但是代理pod报错如下
[info 211126 13:48:38 baremetal.(*SBaremetalManager).RegisterBaremetal(manager.go:320)] Find ipmi address 192.168.10.221
[info 211126 13:48:49 tasks.(*sBaremetalRegisterTask).getAccessDevMacAddr(bm_register.go:103)] Access dev is br1
[info 211126 13:48:49 appsrv.(*Application).ServeHTTP(appsrv.go:239)] w9nBLE-XaTfHchkgwoke1gy8m-E= 200 5a7b20 POST /baremetals/register-baremetal (192.168.10.107:40035) 11367.41ms
[error 211126 13:48:52 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:48:52 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:02 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:02 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:12 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:12 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[warning 211126 13:49:22 baremetal.(*SBaremetalInstance).getPowerStatus(manager.go:1705)] Use host sf107 ssh client get powerstatus: Host ssh config is empty
[warning 211126 13:49:22 baremetal.(*SBaremetalInstance).getPowerStatus(manager.go:1712)] Use server  ssh client get powerstatus: No server
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[warning 211126 13:49:22 baremetal.(*SBaremetalInstance).getPowerStatus(manager.go:1705)] Use host sf107 ssh client get powerstatus: Host ssh config is empty
[warning 211126 13:49:22 baremetal.(*SBaremetalInstance).getPowerStatus(manager.go:1712)] Use server  ssh client get powerstatus: No server
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[info 211126 13:49:22 baremetal.(*SBaremetalInstance).SyncStatus(manager.go:838)] Update baremetal 04b83372-5d7c-48a7-8f9f-395ab63b9182 to status unknown
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:22 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:32 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:32 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:42 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found
[error 211126 13:49:42 baremetal.(*SBaremetalInstance).GetRawIPMIConfig(manager.go:1301)] Unmarshal IPMIInfo error: Get: key not found

**Comment by zexi** [comment]
执行下面的命令看下这台物理机的 ipmi 信息：

```bash
# 找到这台物理机
$ climc host-list 

# 然后查看这台物理机的 ipmi 信息
$ climc host-ipmi $host_id
```

**Comment by q316503265** [comment]
> 执行下面的命令看下这台物理机的 ipmi 信息：
> 
> ```shell
> # 找到这台物理机
> $ climc host-list 
> 
> # 然后查看这台物理机的 ipmi 信息
> $ climc host-ipmi $host_id
> ```

和正常的能导入的物理机ipmi对比少了| pxe_boot    | true这个字段，有什么影响么？

**Comment by zexi** [comment]
> > 执行下面的命令看下这台物理机的 ipmi 信息：
> > ```shell
> > # 找到这台物理机
> > $ climc host-list 
> > 
> > # 然后查看这台物理机的 ipmi 信息
> > $ climc host-ipmi $host_id
> > ```
> 
> 和正常的能导入的物理机ipmi对比少了| pxe_boot | true这个字段，有什么影响么？

应该没有影响，可以用 ipmitool 获取下 power status 看下用户密码这些信息是否正确，比如 ipmi_ip 是 192.168.1.1, user 是 root, passwd 是 yourpasswd，执行如下命令看下结果：

```bash
$ ipmitool -I lanplus -H 192.168.1.1 -U root -P yourpasswd chassis power status
Chassis Power is on
```

**Comment by q316503265** [comment]
> 



> > > 执行下面的命令看下这台物理机的 ipmi 信息：
> > > ```shell
> > > # 找到这台物理机
> > > $ climc host-list 
> > > 
> > > # 然后查看这台物理机的 ipmi 信息
> > > $ climc host-ipmi $host_id
> > > ```
> > 
> > 
> > 和正常的能导入的物理机ipmi对比少了| pxe_boot | true这个字段，有什么影响么？
> 
> 应该没有影响，可以用 ipmitool 获取下 power status 看下用户密码这些信息是否正确，比如 ipmi_ip 是 192.168.1.1, user 是 root, passwd 是 yourpasswd，执行如下命令看下结果：
> 
> ```shell
> $ ipmitool -I lanplus -H 192.168.1.1 -U root -P yourpasswd chassis power status
> Chassis Power is on
> ```

执行这个命令是成功的，也显示这个信息，不过我看到获取的通道是8，但是实际通道是1

**Comment by zexi** [comment]
这个问题我再看下代码，如果不需要物理机目前的操作系统，可以先试试使用 PXE 引导注册。
