### ISSUE TITLE
导入的kvm虚拟机无法更新状态信息，远程控制功能无法使用

### ISSUE THREAD

**Issue by q316503265** [yunionio/cloudpods#12840]
1.从kvm导入的虚拟机点击更新装提示成功（sync_status=>ready），状态没有更新
2.在虚拟机和宿主机界面以及点击远程控制功能会弹出页面，但是界面是卡死的（sol提示连接无反应，ssh提示连接失败，端口没错）
3.宿主机和虚拟机点击安装agent无反应

**Comment by zexi** [comment]
是手动点了同步状态吗？

**Comment by q316503265** [comment]
> 是手动点了同步状态吗？

是的

**Comment by zexi** [comment]
> > 是手动点了同步状态吗？
> 
> 是的

试试不要手动同步状态，等状态主动变化试试，导入的过程可能有点长

**Comment by q316503265** [comment]
> > > 是手动点了同步状态吗？
> > 
> > 
> > 是的
> 
> 试试不要手动同步状态，等状态主动变化试试，导入的过程可能有点长

一晚上过去了，没啥改变

**Comment by zexi** [comment]
> > > > 是手动点了同步状态吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 试试不要手动同步状态，等状态主动变化试试，导入的过程可能有点长
> 
> 一晚上过去了，没啥改变

麻烦发下导入的命令，我本地试试，另外导入虚拟机的磁盘是多大的？

**Comment by q316503265** [comment]
> > > > > 是手动点了同步状态吗？
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 试试不要手动同步状态，等状态主动变化试试，导入的过程可能有点长
> > 
> > 
> > 一晚上过去了，没啥改变
> 
> 麻烦发下导入的命令，我本地试试，另外导入虚拟机的磁盘是多大的？

就是用你们官方文档的命令：
/opt/yunion/bin/climc --debug servers-import-from-libvirt server.yaml
虚拟机磁盘几百G这样

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/13681
该问题已解决，可以通过修改 host image 测试下：
kubectl -n onecloud set image daemonset default-host host=registry.cn-beijing.aliyuncs.com/yunionio/host:v3.8-0316.0
