### ISSUE TITLE
kvm的虚拟机热迁移时，点击同步状态后，虚拟机状态变为运行中

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#12924]
**What happened**:
kvm虚拟机热迁移，点击同步状态，虚拟机的状态由迁移中变为 运行中
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
FIXED: https://github.com/yunionio/cloudpods/pull/13085
