### ISSUE TITLE
ubuntu 安装

### ISSUE THREAD

**Issue by towithyou** [yunionio/cloudpods#13012]
ubuntu 20.04 安装报各种错误。有没有一些详细文档

TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************************************************************************************************************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"Image is up to date\" not in command_result.stdout or \"Already exists\" not in command_result.stdout' failed. The error was: error while evaluating conditional (\"Image is up to date\" not in command_result.stdout or \"Already exists\" not in command_result.stdout): 'dict object' has no attribute 'stdout'"}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
192.168.1.135              : ok=47   changed=13   unreachable=0    failed=1    skipped=20   rescued=0    ignored=0

**Comment by zexi** [comment]
@towithyou 我们暂时不支持在 ubuntu 上部署，目前支持的发行版为：
- CentOS 7
- Debian 10(Buster)
