### ISSUE TITLE
平台上NFS存储相关资源已经清空，删除该存储时，按钮置灰不可点击，提示“存储上还有快照”

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#13021]
**What happened**:
![image](https://user-images.githubusercontent.com/32036395/147319107-19f4a756-d463-4a95-ba4a-7469a33ac945.png)
![image](https://user-images.githubusercontent.com/32036395/147319463-c32bfb4b-8787-4400-9b90-63b5e3dfde5c.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by hoganlxj** [comment]
发现已经清空的存储下 还有fake-deleted的快照，导致存储无法在前端删除

**Comment by swordqiu** [comment]
https://github.com/yunionio/cloudpods/pull/14141
已修复
