### ISSUE TITLE
资源总数未包含裸金属资源数，导致管理页面显示资源超标

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#13044]
**What happened**:
资源总数未包含裸金属资源数，导致管理页面显示资源超标
**Environment**:
v3.6.22
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

资源总数未包含裸金属物理机的资源数（CPU，内存等），但已经占用的虚拟机的资源总数中却包含裸金属物理机使用的资源，导致
资源展示页面，显示红色，资源超标
![image](https://user-images.githubusercontent.com/19506558/147412508-2669dc76-ae41-49c0-a6e6-6ce6c787ebae.png)

**Comment by zexi** [comment]
好的，感谢反馈，我看下。

**Comment by swordqiu** [comment]
This issue was addressed by #14396
