### ISSUE TITLE
从镜像市场导入镜像，转换vmdk格式镜像失败

### ISSUE THREAD

**Issue by z-yfgit** [yunionio/cloudpods#13199]
**What happened**:
企业版从镜像市场导入镜像，转换vmdk格式镜像失败
**Environment**:

- OS (e.g. `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`): 3.10.0-1160.6.1.el7.yn20201125.x86_64
- Version (e.g. `climc version-list`):  企业版3.8.6

![Km0nM9e2Cl](https://user-images.githubusercontent.com/58453894/149323489-26ae400f-9a38-4706-b413-2b485d7808a9.png)

**Comment by z-yfgit** [comment]
重装，不选择minio，vmdk格式镜像可以保存成功，应该是和minio有关系

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/13293
