### ISSUE TITLE
宿主机宕机自动迁移不稳定生效

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#13335]
**What happened**:

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by swordqiu** [comment]
![image](https://user-images.githubusercontent.com/1121362/155838272-f1a3d5b2-a687-4805-a4b5-90f614f1b090.png)
![image](https://user-images.githubusercontent.com/1121362/155838296-2a081bb5-e171-4138-a283-bc5109cf8a93.png)
![image](https://user-images.githubusercontent.com/1121362/155838310-ecc7f9c2-f66f-42a5-b574-5a795c5adb18.png)

**Comment by wanyaoqi** [comment]
这里需要模拟宕机条件，如果宿主机正常关机的情况下，会发送 kill 信号给 host 服务，host 服务走的是正常的 offline 流程，不会触发宕机自动迁移。

测试的方式可以改为模拟断网条件，将宿主机的网卡 disable。

**Comment by zexi** [comment]
3.9 版本已经对宕机迁移做了很多优化，可以升级到 3.9 再测试
