### ISSUE TITLE
fail to upload large image from web console

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#13425]
**What happened**:
fail to upload large image more than 6.6G, report error "create upload fail unexpected EOF"
![image](https://user-images.githubusercontent.com/1121362/153618783-021922a9-43ee-479b-a3f1-9d08db4e08cf.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
目前从前端上传镜像的路径太长了，如下：
浏览器 -> k8s ingress -> nginx service -> yunion apigateway -> glance service
可以修改成以下路径试试：
浏览器 -> k8s ingress -> glance service

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods-operator/pull/936/files nginx配置timeout应该可以避免这个问题
