### ISSUE TITLE
onecloud-cluster 怎样部署 ？

### ISSUE THREAD

**Issue by GangLiCN** [yunionio/cloudpods#13501]
【问题】
按照官方文档的步骤 准备在现有k8s集群 部署cloudpods, operator已经部署成功，但是集群一直没有部署成功

[环境]
k8s: 1.19.8
OS:  CentOS 7.9
docker:  1.13.1

[步骤]
1. 编译onecloud-operator;
kubectl apply -f onecloud-operator.yaml
给节点打标签: kubectl label nodes k8s-master onecloud.yunion.io/controller=enable
检查pod的状态
kubectl get pods -n onecloud
输出如下：
NAME                                 READY   STATUS    RESTARTS   AGE
onecloud-operator-7fd65d6489-kwdkr   1/1     Running   0          5m2s

2. 下载 onecloud cluster 的 yaml 文件
wget https://raw.githubusercontent.com/yunionio/onecloud-operator/master/manifests/example-aliyun-onecloud-cluster.yaml -O onecloud-cluster.yaml

修改 yaml 文件，主要是修改 spec.mysql 里面内容，

3.  部署Cloudpods服务
检查pod的状态，只有三个pod,其他基础pod都没有
kubectl get pods -n onecloud
输出如下：
NAME                                 READY   STATUS                  RESTARTS   AGE
default-etcd-4z65pjht2t              1/1     Running                 0          2d23h
default-keystone-7459df946f-g67tk    1/1     Running                 0          2d23h
onecloud-operator-64b8896b9d-jlcvp   1/1     Running                 0          2d20h

4. 查看日志，没有错误，但是 一直在重复 更新 操作
I0218 06:06:51.536744       1 cluster_control.go:69] OnecloudCluster: [onecloud/default] updated successfully, spec: v1alpha1.MonitorStackSpec{Disable:false, Minio:v1alpha1.MonitorStackMinioSpec{Mode:"", AccessKey:"monitor-admin", SecretKey:"9uzYcUg9QneFHehf"}, Grafana:v1alpha1.MonitorStackGrafanaSpec{Disable:false, AdminUser:"admin", AdminPassword:"admin@123", Host:"", EnforceDomain:false, DisableSubpath:false, Subpath:"grafana", OAuth:v1alpha1.MonitorStackGrafanaSpecOAuth{Enabled:false, ClientId:"", ClientSecret:"", Scopes:"user", AuthURL:"", TokenURL:"", APIURL:"", AllowedDomains:"", AllowSignUp:false, RoleAttributePath:"projectName == 'system' && contains(roles, 'admin') && 'Admin' || 'Editor'"}}, Loki:v1alpha1.MonitorStackLokiSpec{Disable:false, ObjectStoreConfig:v1alpha1.ObjectStoreConfig{Bucket:"loki", Endpoint:"", AccessKey:"", SecretKey:""}}, Prometheus:v1alpha1.MonitorStackPrometheusSpec{Disable:(*bool)(0xc0007adbdc), ThanosSidecarSpec:v1alpha1.ThanosSidecarSpec{ObjectStoreConfig:v1alpha1.ObjectStoreConfig{Bucket:"thanos", Endpoint:"", AccessKey:"", SecretKey:""}}}, Thanos:v1alpha1.MonitorStackThanosSpec{ObjectStoreConfig:v1alpha1.ObjectStoreConfig{Bucket:"thanos", Endpoint:"", AccessKey:"", SecretKey:""}}}

【疑问】
官网提供的onecloud-cluster.yaml 是基于阿里云环境的，有没有 适用于本地测试的模板文件可供参考 ？

**Comment by GangLiCN** [comment]
删除掉副本和pod, 重新部署了一次，发现新错误，错误出在 default-region的初始化，错误如下：
container "region" in pod "default-region-5b8f6bb474-h69r6" is waiting to start: PodInitializing

区域是公有云，私有云的才有的概念，k8s只是做容器编排调度，不应该和区域打交道。

**Comment by hoganlxj** [comment]
参考下
https://www.cloudpods.org/zh/docs/quickstart/allinone/

**Comment by zexi** [comment]
> 删除掉副本和pod, 重新部署了一次，发现新错误，错误出在 default-region的初始化，错误如下： container "region" in pod "default-region-5b8f6bb474-h69r6" is waiting to start: PodInitializing
> 
> 区域是公有云，私有云的才有的概念，k8s只是做容器编排调度，不应该和区域打交道。

@GangLiCN G
kubectl logs -n  onecloud default-region-5b8f6bb474-h69r6 -c init 
看下日志的输出

**Comment by GangLiCN** [comment]
kubectl logs -n onecloud default-region-5b8f6bb474-h69r6 -c init
## 输出的日志如下：
[debug 220221 06:46:30 db.newTableSpec(tablespec.go:67)] table opslog_tbl maxDuration 720 hour maxSegements 6
[info 220221 06:46:30 models.init.58(guests.go:93)] init GuestManager
[info 220221 06:46:30 loader.init.0(loader.go:42)] Loading cloud providers ...
[info 220221 06:46:30 options.ParseOptions(options.go:277)] Use configuration file: /etc/yunion/region.conf
[info 220221 06:46:30 service.StartService(service.go:59)] Port V2 30888 is specified, use v2 port
[info 220221 06:46:30 service.StartService.func1(service.go:64)] Auth complete!!
[info 220221 06:46:30 consts.SetNonDefaultDomainProjects(consts.go:79)] set non_default_domain_projects to false
[info 220221 06:46:30 options.StartOptionManagerWithSessionDriver(manager.go:61)] OptionManager start to fetch service configs ...
[info 220221 06:46:30 watcher.(*SInformerSyncManager).startWatcher(watcher.go:82)]EndpointChangeManager: Start resource informer watcher for endpoint
[info 220221 06:46:30 informer.(*EtcdBackendForClient).StartClientWatch(etcd_client.go:84)] /onecloud/informer watched
[info 220221 06:46:30 informer.NewWatchManagerBySessionBg.func1(watcher.go:51)] callback with watchMan success.
[info 220221 06:46:30 options.optionsEquals(manager.go:110)] Options added: {"api_server":"https://10.6.6.5"}
[info 220221 06:46:30 watcher.(*SInformerSyncManager).startWatcher(watcher.go:82)]ServiceConfigManager: Start resource informer watcher for service
[info 220221 06:46:30 app.InitApp(app.go:31)] RequestWorkerCount: 8
[info 220221 06:46:30 appsrv.NewApplication(appsrv.go:109)] App hostId: 4OK3ZGeRuDCpYDpG1fvZogsTpjg= (compute_v2,default-region-5b8f6bb474-h69r6,10.233.90.56)
2022-02-21 06:46:30.808358 I | Allow hosts []
[info 220221 06:46:30 informer.(*EtcdBackendForClient).StartClientWatch(etcd_client.go:84)] /onecloud/informer watched
[info 220221 06:46:30 informer.NewWatchManagerBySessionBg.func1(watcher.go:51)] callback with watchMan success.
[info 220221 06:46:30 cloudcommon.InitDB(database.go:67)] using inmemory lockman
[info 220221 06:46:30 db.CheckSync(models.go:98)] Start check database schema ...
[info 220221 06:46:30 cloudcommon.startInitInformer.func1(database.go:101)] using etcd as resource informer backend
[fatal 220221 06:46:31 db.EnsureAppInitSyncDB(models.go:150)] model init db: clean duplicated cached loadbalancer certificates: Error 1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't42.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by GangLiCN** [comment]
日志中最后一行 "Expression https://github.com/yunionio/cloudpods/pull/1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't42.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" 似乎是mysql  初始化参数的设置问题 ?   我用的Mysql版本5.7.37.

**Comment by zexi** [comment]
> 日志中最后一行 "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't42.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" 似乎是mysql 初始化参数的设置问题 ? 我用的Mysql版本5.7.37.

试试用 mariadb 呢？

**Comment by GangLiCN** [comment]
此问题已解决，多谢恢复。



---- 回复的原邮件 ----
| 发件人 | Zexi ***@***.***> |
| 日期 | 2022年02月21日 18:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [yunionio/cloudpods] onecloud-cluster 怎样部署 ？ (Issue #13501) |

日志中最后一行 "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't42.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" 似乎是mysql 初始化参数的设置问题 ? 我用的Mysql版本5.7.37.

试试用 mariadb 呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zexi** [comment]
不客气
