### ISSUE TITLE
Could not find the requested service yunion-executor: host

### ISSUE THREAD

**Issue by redjack666** [yunionio/cloudpods#13680]
没安装服务 但在网路上也找到教学文 yunion 这个需要怎麽装
TASK [common : Enable yunion systemd services] ************************************************************************
failed: [192.168.150.145] (item=yunion-executor) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-executor", "msg": "Could not find the requested service yunion-executor: host"}

**Comment by zhasm** [comment]
@redjack666 您的环境是？目前只支持 centos7 (x86+arm64)， 以及 debian10 (x86+arm64)。
请执行如下命令，然后贴出运行结果，多谢~

```bash
cat /etc/os-release
```

谢谢~

**Comment by redjack666** [comment]
> @redjack666 您的环境是？目前只支持 centos7 (x86+arm64)， 以及 debian10 (x86+arm64)。 请执行如下命令，然后贴出运行结果，多谢~
> 
> ```shell
> cat /etc/os-release
> ```
> 
> 谢谢~

CentOS Linux release 7.9.2009

**Comment by zexi** [comment]
@redjack666 我在 centos 7.9 上安装没有问题，麻烦执行下面的命令排查下：

```bash
$ cat /etc/yum.repos.d/yunion.repo

$ yum search yunion-executor

$ yum install -y yunion-executor
```

**Comment by hoganlxj** [comment]
安装后是禁用NetworkManager后导致的，可以通过vnc连接进去后启用恢复
另外，在公有云部署cloudpods时需要把as_host设置为fasle
vim ~/ocboot/run.py
![image](https://user-images.githubusercontent.com/32036395/180420149-1803d5ed-0aa6-441c-88f6-2202b6110898.png)
