### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by liu304424818** [yunionio/cloudpods#13752]
[root@k8s-master01 cloudpodsoperator]# kubectl apply -f onecloud-operator.yaml
[root@k8s-master01 cloudpodsoperator]# kubectl logs -n onecloud onecloud-operator-6f98c58bb8-w7ppb 
F0322 08:27:06.391047       1 main.go:132] init CRD resources: failed to create CRD: unable to create crd onecloudclusters.onecloud.yunion.io: the server could not find the requested resource

**Comment by zexi** [comment]
请问k8s集群的版本是多少？

**Comment by zexi** [comment]
目前如果在已有 k8s 集群上部署，支持的版本为： 1.15 - 1.20 ，可参考文档：https://www.cloudpods.org/zh/docs/quickstart/k8s/
