### ISSUE TITLE
在centos7.9上执行./run.py 192.168.0.118总是会失败，报如下错误

### ISSUE THREAD

**Issue by KnightKevin** [yunionio/cloudpods#14045]
TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ******************************************************************************************************************************************
fatal: [192.168.0.118]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "init", "--control-plane-endpoint", "192.168.0.118:6443", "--mysql-host", "192.168.0.118", "--mysql-user", "root", "--mysql-password", "YT5kk6qaV37J", "--mysql-port", "3306", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunionio", "--apiserver-advertise-address", "192.168.0.118", "--node-ip", "192.168.0.118", "--onecloud-version", "v3.8.8", "--operator-version", "v3.8.8", "--pod-network-cidr", "10.40.0.0/16", "--service-cidr", "10.96.0.0/12", "--service-dns-domain", "cluster.local", "--addon-calico-ip-autodetection-method", "can-reach=192.168.0.118", "--enable-host-agent"], "delta": "0:00:00.159846", "end": "2022-04-17 16:42:02.162556", "msg": "non-zero return code", "rc": 1, "start": "2022-04-17 16:42:02.002710", "stderr": "error execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Mysql]: show grants for root@%: Error 1045: Access denied for user 'root'@'192.168.0.118' (using password: YES)\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Mysql]: show grants for root@%: Error 1045: Access denied for user 'root'@'192.168.0.118' (using password: YES)", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.8.8\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.8.8", "[preflight] Running pre-flight checks"]}

**Comment by zexi** [comment]
```bash
ERROR Mysql]: show grants for root@%: Error 1045: Access denied for user 'root'@'192.168.0.118' (using password: YES)"
```

@KnightKevin 检查下 mariadb 为什么连接不上？

**Comment by wqlxx** [comment]
我在centos7 2009版本里用了ocboot的`release/3.8`分支的代码，遇到相同的问题。

**Comment by zexi** [comment]
> 我在centos7 2009版本里用了ocboot的`release/3.8`分支的代码，遇到相同的问题。

也是 mysql 连接的问题吗？手动连接 mysql ，然后执行 `show grants for root@%` 能成功吗？

**Comment by KnightKevin** [comment]
> ```shell
> ERROR Mysql]: show grants for root@%: Error 1045: Access denied for user 'root'@'192.168.0.118' (using password: YES)"
> ```
> 
> @KnightKevin 检查下 mariadb 为什么连接不上？


我用命令行直接连接是可以的，换个主机远程连接也是可以的，可是执行/run.sh还是会报错，我重新安装linux也不行。
我的centos 也是2009这个版本`http://mirrors.aliyun.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso`。
不过我刚刚试了一下你发的这个命令`show grants for root@%`会报错，但是用`show grants for root@'%'`就对了

**Comment by heblug** [comment]
这个如何解决？

**Comment by zexi** [comment]
无法复现该问题，测试 centos  7.9 安装没有问题。
