### ISSUE TITLE
不能更新阿里云主机镜像列表

### ISSUE THREAD

**Issue by ss75710541** [yunionio/cloudpods#14065]
**不能更新阿里云主机镜像列表**:

我是2021年安装的 cloudpods, 最早是 3.6 版本，后来升级到 3.8.8。 使用多云创建阿里云的主机是，镜像列表与阿里云不同步，不能创建主机，没有找到更新阿里云镜像列表的地方，点全量更新也没有更新镜像列表。

**Environment**:

- OS (e.g. `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`): Linux iZ8vbgn5etvzy5zimpi4cwZ 5.4.130-1.yn20210710.el7.x86_64 #1 SMP Sat Jul 10 13:58:51 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

climc version-list

Get "https://172.26.117.99:30443/version": dial tcp 172.26.117.99:30443: connect: connection refused
+-----------------+---------------------------------------------------------+
|      Field      |                          Value                          |
+-----------------+---------------------------------------------------------+
| ansible         | release/3.8(cea0d759e22040203)                          |
| autoupdate      | release/3.8(dd6f789e22040203)                           |
| cloudevent      | release/3.8(cea0d759e22040203)                          |
| cloudid         | release/3.8(cea0d759e22040204)                          |
| cloudmeta       | ci/ucloud-basic-data-support(aedc811)                   |
| cloudnet        | release/3.8(cea0d759e22040203)                          |
| cloudproxy      | release/3.8(cea0d759e22040204)                          |
| compute_v2      | release/3.8(cea0d759e22040203)                          |
| devtool         | release/3.8(cea0d759e22040203)                          |
| etcd            | No valid publicURL endpoints for etcd in region region0 |
| identity        | release/3.8(cea0d759e22040203)                          |
| image           | release/3.8(cea0d759e22040203)                          |
| influxdb        | 404 page not found                                      |
| k8s             | 404 page not found                                      |
| log             | release/3.8(cea0d759e22040203)                          |
| monitor         | release/3.8(cea0d759e22040203)                          |
| notify          | release/3.8(cea0d759e22040203)                          |
| s3gateway       | release/3.8(cea0d759e22040203)                          |
| scheduler       | release/3.8(cea0d759e22040203)                          |
| torrent-tracker | <title>Not Found</title>                                |
| webconsole      | release/3.8(cea0d759e22040203)                          |
| yunionconf      | release/3.8(cea0d759e22040203)                          |
+-----------------+---------------------------------------------------------+

**Comment by ioito** [comment]
公有云镜像更新代码在 https://github.com/yunionio/cloudpods/blob/96e501b310fd32a3a7874f02220b1aa419f46c5b/pkg/compute/models/cloudregions.go#L1018

原理是我们会每天收集整理公有云镜像，并将这些数据放到阿里云对象存储里面，开源用户每隔一段时间检查镜像数据有没有变动，如果变动则会从阿里云对象存储里面拉取镜像信息进行更新

你要用的阿里云哪个region底下的哪个镜像，我查下数据

**Comment by ss75710541** [comment]
@ioito 所有的region 的镜像列表显示 的都一样都是
cloudpods 中只有 9 个大类的  镜像

阿里云总共有 14个大类的 镜像，我要使用的是Rock Linux 8.5

<img width="781" alt="image" src="https://user-images.githubusercontent.com/5858487/163988415-fd666758-bc1f-48d5-b1d0-e8bb8a065b42.png">

<img width="692" alt="image" src="https://user-images.githubusercontent.com/5858487/163988572-600e9756-61d6-489a-9fca-f80b418ea5ef.png">

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/163989229-9465f6dd-b892-4f87-bea8-924bb41e63c3.png)
有些镜像没有做发行版分类，可以先到Linux里面找下，这个我们下来做下优化，将它单独分类出来

**Comment by ss75710541** [comment]
@ioito 好的，可以创建 Rocky Linux 8.5 主机了，谢谢

**Comment by ioito** [comment]
不客气，我关issue了

**Comment by ss75710541** [comment]
@ioito 好的
