### ISSUE TITLE
cloudpods 删除云账号时报 No such module bill_tasks for version v1

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#14104]
**What happened**:
![image](https://user-images.githubusercontent.com/32036395/164581938-c383d701-4321-447c-bf25-29d295c1c450.png)
![image](https://user-images.githubusercontent.com/32036395/164581963-71f1bc95-9365-49cc-97d9-82e41c10e220.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by GuoLiBin6** [comment]
pr: https://github.com/yunionio/dashboard/pull/2673
