### ISSUE TITLE
选择套餐UI交互改进

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#14119]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/1121362/164709411-b182446b-4d33-4d62-b232-fb03a501ed40.png)
![image](https://user-images.githubusercontent.com/1121362/164709471-c85c5de9-2b5d-428f-bb02-1ce1dee0a673.png)

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/3270
