### ISSUE TITLE
oidc中获取token接口，返回的body缺少id_token字段

### ISSUE THREAD

**Issue by Davidzkeng** [yunionio/cloudpods#14209]
**What happened**:
获取token接口返回字段缺少id_token字段
![image](https://user-images.githubusercontent.com/25363240/167234608-c7c6f698-3f3c-4023-89ef-1f24fe9129ad.png)

跑了测试用例报错信息：
![Pd9qQNGXsJ](https://user-images.githubusercontent.com/25363240/167234848-ca36ce2a-a866-49c9-a90d-512c398f85d7.jpg)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
`NAME="CentOS Linux"
 VERSION="7 (Core)"
 ID="centos"
 ID_LIKE="rhel fedora" 
 VERSION_ID="7"
 PRETTY_NAME="CentOS Linux 7 (Core)"
 ANSI_COLOR="0;31"
 CPE_NAME="cpe:/o:centos:centos:7"
 HOME_URL="https://www.centos.org/"
 BUG_REPORT_URL="https://bugs.centos.org/"
 CENTOS_MANTISBT_PROJECT="CentOS-7"
 CENTOS_MANTISBT_PROJECT_VERSION="7"
 REDHAT_SUPPORT_PRODUCT="centos"
 REDHAT_SUPPORT_PRODUCT_VERSION="7"`
- Kernel (e.g. `uname -a`):
`Linux i-AC64A68D 3.10.0-1160.6.1.el7.yn20201125.x86_64 #1 SMP Sat Nov 21 12:06:27 CST 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by swordqiu** [comment]
This issue has been addressed by https://github.com/yunionio/cloudpods/pull/14249
