### ISSUE TITLE
baremetal server network  rate shows wrong 

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#14491]
**What happened**:
The NIC of baremetal server shows wrong rate .
10G shows 1G on the web ,and  can't change the rate manually 
**Environment**:
V3.8.8
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

Picture:
![image](https://user-images.githubusercontent.com/19506558/174701784-59e9c798-b898-4ef8-9043-4b289c2b5484.png)

**Comment by zexi** [comment]
@we14578 这个带宽应该是根据网络所在的二层网络(wire)决定的，修改 wire 的 bandwidth 应该就行了
