### ISSUE TITLE
baremetal  install  monitor agent can't show monit data 

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#14492]
**What happened**:
Baremetal server installed  the agent successful,but the monit  data shows empty .The agent could work on 
the VM.
**Environment**:
V3.8.8
- OS (e.g. `cat /etc/os-release`):
centos 7.6
- Kernel (e.g. `uname -a`):

V3.8.8

picture:
![image](https://user-images.githubusercontent.com/19506558/174704138-8167c891-345c-40ea-a2e8-7c817954d57e.png)
![image](https://user-images.githubusercontent.com/19506558/174704172-d99ecbf6-0a13-4f2e-a50f-f37cccbd78ba.png)

**Comment by zexi** [comment]
Fixed: https://github.com/yunionio/cloudpods/pull/14589
