### ISSUE TITLE
report `sql: no rows in result set` while moditify virtual disk driver of vm

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#14541]
**What happened**:

> sql: no rows in result set

**Environment**:

cloudpos latest base on cent79 2009

- OS (e.g. `cat /etc/os-release`):
  -  CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`):
  - Linux cloud-stack 3.10.0-1160.6.1.el7.yn20201125.x86_64

- request api
```json
{
  "method": "put",
  "url": "/v2/servers/undefined/disks/undefined",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json;charset=utf-8",
    "x-yunion-lang": "zh-CN"
  },
  "data": {
    "driver": "virtio",
    "cache_mode": "none"
  }
}
```

- response
```json
{
  "class": "UnclassifiedError",
  "code": 500,
  "details": "sql: no rows in result set",
  "time": "2022-06-29T01:13:16.773Z"
}
```

**Comment by zexi** [comment]
> **What happened**:
> 
> > sql: no rows in result set
> 
> **Environment**:
> 
> cloudpos latest base on cent79 2009
> 
> * OS (e.g. `cat /etc/os-release`):
>   
>   * CentOS Linux release 7.9.2009 (Core)
> * Kernel (e.g. `uname -a`):
>   
>   * Linux cloud-stack 3.10.0-1160.6.1.el7.yn20201125.x86_64
> 
> * request api
> 
> ```json
> {
>   "method": "put",
>   "url": "/v2/servers/undefined/disks/undefined",
undefined?
>   "headers": {
>     "Accept": "application/json, text/plain, */*",
>     "Content-Type": "application/json;charset=utf-8",
>     "x-yunion-lang": "zh-CN"
>   },
>   "data": {
>     "driver": "virtio",
>     "cache_mode": "none"
>   }
> }
> ```
> 
> * response
> 
> ```json
> {
>   "class": "UnclassifiedError",
>   "code": 500,
>   "details": "sql: no rows in result set",
>   "time": "2022-06-29T01:13:16.773Z"
> }
> ```
