### ISSUE TITLE
ssh代理节点无法创建,无法选择区域. 且平台只有 `云联壹云`

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#14548]
**What happened**:

**Environment**:
Cent7.9

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
3.10.0-1160.6.1.el7.yn20201125.x86_64

**Comment by dengju2020** [comment]
ssh代理节点可选择哪些平台及区域是根据平台纳管云账号来的，具体可参考文档：https://www.cloudpods.org/zh/docs/multicloud/network/sshproxy/tutorial/proxyendpoint/
