### ISSUE TITLE
All in One install, kubelet version is higher

### ISSUE THREAD

**Issue by oceanxie** [yunionio/cloudpods#14673]
**What happened**:
ALL IN One方式在一台全新机器上部署Cloudpods 服务，用的release/3.8分支，执行"./run.py ./config-allinone.yml"，ansiable在TASK [primary-master-node/setup_k8s : Use ocadm init first master node]阶段报错：[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: \"1.24.3\" Control plane version: \"1.15.8\".
默认拉了最新版的k8s，并没有安装指定版本的k8s.

**Environment**:
- OS (e.g. `cat /etc/os-release`): CentOS 7.6
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64

**Comment by zexi** [comment]
是否添加了 k8s 相关的 yum 源？
