### ISSUE TITLE
单机部署报错

### ISSUE THREAD

**Issue by chenshushan** [yunionio/cloudpods#14742]
TASK [primary-master-node/setup_cloud : Wait onecloud CRD created]

fatal: [188.188.188.189]: FAILED! => {"attempts": 30, "changed": true, "cmd": "kubectl get crd | grep onecloudcluster", "delta": "0:00:00.144014", "end": "2022-07-31 07:27:41.110629", "msg": "non-zero return code", "rc": 1, "start": "2022-07-31 07:27:40.966615", "stderr": "No resources found.", "stderr_lines": ["No resources found."], "stdout": "", "stdout_lines": []}

**Comment by zexi** [comment]
kubectl get pods -n onecloud 看下有没有 onecloud-operator-xxx 这个 pod，如果有的话，发下这个 pod 的日志

**Comment by rtnetkxy** [comment]
遇到同样的问题，kubectl get pods -n onecloud 显示为No resources found.
