### ISSUE TITLE
 工程`yunionio/qemu` 需要更新

### ISSUE THREAD

**Issue by GKilm** [yunionio/cloudpods#14749]
#14258 改变了pkg/image.go里调用函数open_qcow2的参数情况，提交信息里提到需要用到libqemuio2.12。
但在`yunionio/qemu`工程里，[0001-patch-for-2.12.patch](https://github.com/yunionio/qemu/blob/ad6b7098ccb8712d701a8b0e3fd2195f63e1c988/0001-patch-for-2.12.patch#L1219)里的open_qcow2并没有改变。

感谢。

**Comment by wanyaoqi** [comment]
@GKilm   https://github.com/yunionio/qemu/pull/3
这个repo的维护方式还没有想好，临时的这个 patch 提交上了
