### ISSUE TITLE
腾讯云国际版账号货币类型显示为人民币

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#14865]
**What happened**:
腾讯云国际版账号货币类型显示为人民币

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by swordqiu** [comment]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/1121362/187243767-68c0a916-de6c-4c2b-9c85-10922ddeda52.png">

**Comment by swordqiu** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/1121362/187311119-b452e4a0-6b3e-4bb3-b9fb-0790122d2bc6.png">

**Comment by ioito** [comment]
Closed #17644
