### ISSUE TITLE
点击项目详情中刷新按钮后，项目统计中Rds和Redis数量没有更新

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#14909]
**What happened**:
![image](https://user-images.githubusercontent.com/32036395/188053830-188d95b2-18c5-4c3a-a13a-65fd755628fb.png)
**Environment**:
在平台中分别新建一台Rds和Redis后，点击项目详情中刷新按钮后，Rds和Redis数量还是之前的值
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/3409
