### ISSUE TITLE
同步资源时通过配置可以忽略弹性伸缩主机，但是未忽略这些主机的磁盘

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#15025]
**What happened**:
![image](https://user-images.githubusercontent.com/1121362/191721301-024bf967-6efa-4dd0-be77-a0dbc82ab632.png)

![image](https://user-images.githubusercontent.com/1121362/191721405-e07758c4-c233-4713-8cee-7feedb197a13.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
Close #15231
