### ISSUE TITLE
k8s安装方式，如何获取sdk所需的auth信息

### ISSUE THREAD

**Issue by dyf991645** [yunionio/cloudpods#15061]
我是在已有的 Kubernetes 集群部署的cloudpod， 没有 ocadm，如何获取go sdk 所需的认证信息。

https://github.com/yunionio/cloudpods/tree/master/pkg/mcclient，README 中提到`Login to first controlplane node of your cluster and execute ocadm cluster rcadmin to get auth info.`

**Comment by zexi** [comment]
> 我是在已有的 Kubernetes 集群部署的cloudpod， 没有 ocadm，如何获取go sdk 所需的认证信息。
> 
> [https://github.com/yunionio/cloudpods/tree/master/pkg/mcclient，README](https://github.com/yunionio/cloudpods/tree/master/pkg/mcclient%EF%BC%8CREADME) 中提到`Login to first controlplane node of your cluster and execute ocadm cluster rcadmin to get auth info.`

你好，这部分文档还需要补充，目前可以用以下的方式获取：

```bash
# 通过 climc pod 的环境变量拿到相关认证信息
$ kubectl exec -n onecloud default-climc-74444b7cb7-5chnf -- env | egrep '^OS|^YUNION'
OS_USERNAME=sysadmin
OS_PASSWORD=ixtPb1Z3_crqS8YG
OS_REGION_NAME=YunionHQ
OS_AUTH_URL=https://default-keystone:30357/v3 #注意这里是 k8s 内部的 service ，在外部访问的话需要变化
OS_PROJECT_NAME=system
YUNION_INSECURE=true

# 找到外部的 keystone public endpoint
$ climc endpoint-list --search identity |grep public
| d5bc773393c54d108cdbb8812872e941 | region0   | 96b0d6edb931446280fe9f62b764fd51 | https://10.127.100.2:30500/v3     | public    | true    |

# 然后把上面 OS_AUTH_URL 环境变量改成 https://10.127.100.2:30500/v3 ，应该就可以了
```

最后拼出来的环境变量就是

```bash
OS_USERNAME=sysadmin
OS_PASSWORD=ixtPb1Z3_crqS8YG
OS_REGION_NAME=YunionHQ
OS_AUTH_URL=https://10.127.100.2:30500/v3
OS_PROJECT_NAME=system
YUNION_INSECURE=true
```

**Comment by dyf991645** [comment]
@zexi 谢谢，已经可以成功使用sdk了，然后还有一个问题：

我看sdk会调用v3/auth/tokens获取token以及endpoints，之后的请求会用到返回的endpoint。  
但是internalURL都是k8s的不带namespace 的 service地址，所以其他ns下无法访问。  
我在keystone数据控中的url中加上了service的namespace，并重启了keystone的pod，但是v3/auth/tokens返回的endpoint仍然没有带namespace。

请问有什么办法修改url？或者麻烦告知下keystone http服务的源码位置

**Comment by zexi** [comment]
> s，之后的请求会用到返回的endpoint

@dyf991645 这个 endpoint 是由 onecloud-operator 那个服务负责同步的，需要该 operator 的代码，给 internal 的 endpoint 加上 namespace ，在这个地方：https://github.com/yunionio/cloudpods-operator/blob/36372ae6b03ef64852f5799635e985cb2171739f/pkg/controller/onecloud_control.go#L379
