### ISSUE TITLE
使用netplan的Ubuntu虚拟机未正确初始化网络

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#15078]
**What happened**:
![image](https://user-images.githubusercontent.com/1121362/192543839-2cd63873-81d8-458c-8bae-c260bf344a3e.png)

![image](https://user-images.githubusercontent.com/1121362/192543983-2e58c368-49e2-453e-8c2d-ba70a441f50a.png)

![image](https://user-images.githubusercontent.com/1121362/192545030-86b4ded2-d795-4bde-88fb-e106fccf450c.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
需要实现下开机状态添加网卡需要更新 netplan 配置信息

**Comment by wanyaoqi** [comment]
需要通过QGA 方式注入
