### ISSUE TITLE
Fail to start VM with rbd disk

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#15239]
**What happened**:
{
    "__reason__": "Async start server failed: Start VM Failed ls: cannot access /opt/cloud/workspace/servers/b7a1b6f2-21dd-4799-88fe-ba6aa03f8566/STATEFILE*: No such file or directory\nchar device redirected to /dev/pts/2 (label charserial0)\nqemu-system-x86_64: -drive id=ide0-cd0,media=cdrom,if=none,file=rbd:oneclound/image_cache_b3561480-faef-4b09-8704-244e739978b8:mon_host=10.0.0.1;10.0.0.2;10.0.0.3;10.0.0.4;10.0.0.5;10.0.0.7;10.0.0.10:key=AQA08CZhf2lFGxAAqJRO3T9Swk4me3mebMzSgQ==:rados_mon_op_timeout=5:rados_osd_op_timeout=1200:client_mount_timeo: conf option client_mount_timeo has no value\n exit status 1",
    "__stage__": "OnStartComplete",
    "__status__": "error"
}

由于参数太长导致截断：
“rbd:oneclound/image_cache_b3561480-faef-4b09-8704-244e739978b8:mon_host=10.0.0.1;10.0.0.2;10.0.0.3;10.0.0.4;10.0.0.5;10.0.0.7;10.0.0.10:key=AQA08CZhf2lFGxAAqJRO3T9Swk4me3mebMzSgQ==:rados_mon_op_timeout=5:rados_osd_op_timeout=1200:client_mount_timeo”

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
未复现
