### ISSUE TITLE
bug: when upgrading to v3.9.3 it report "No package matching 'yunion-climc-ee' found available, installed or updated" 

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#15240]
**What happened**:

TASK [upgrade/common : Upgrade common packages] ********************************
fatal: [i-f378ff56]: FAILED! => {"changed": false, "msg": "No package matching 'yunion-climc-ee' found available, installed or updated", "rc": 126, "results": ["All packages providing yunion-ocadm are up to date", "All packages providing yunion-climc are up to date", "No package matching 'yunion-climc-ee' found available, installed or updated"]}

**Environment**:

REF: https://github.com/yunionio/ocboot/issues/530

**Comment by zexi** [comment]
@momofish issue moved here.

**Comment by zhasm** [comment]
solved.

**Comment by zexi** [comment]
@momofish The upgrade issue has been solved, please use the latest ocboot release/3.9 branch execute the upgrade command again.
