### ISSUE TITLE
单机部署报错

### ISSUE THREAD

**Issue by zhangr1008** [yunionio/cloudpods#15252]
CentOS 7.9 确定防火墙，selinux都关了

TASK [primary-master-node/setup_cloud : Create onecloud web login user admin] ***
fatal: [192.168.0.164]: FAILED! => {"changed": true, "cmd": "eval $(/opt/yunion/bin/ocadm cluster rcadmin)\n/opt/yunion/bin/climc user-create --password admin@123 --enabled admin\n", "delta": "0:00:10.298185", "end": "2022-10-27 22:20:42.172879", "msg": "non-zero return code", "rc": 1, "start": "2022-10-27 22:20:31.874694", "stderr": "{\"error\":{\"class\":\"ClientError\",\"code\":499,\"details\":\"Post \\\"https://192.168.0.164:30500/v3/auth/tokens\\\": net/http: TLS handshake timeout\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.0.164:30500/v3/auth/tokens\"}}}", "stderr_lines": ["{\"error\":{\"class\":\"ClientError\",\"code\":499,\"details\":\"Post \\\"https://192.168.0.164:30500/v3/auth/tokens\\\": net/http: TLS handshake timeout\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.0.164:30500/v3/auth/tokens\"}}}"], "stdout": "Post \"https://192.168.0.164:30500/v3/auth/tokens\": net/http: TLS handshake timeout", "stdout_lines": ["Post \"https://192.168.0.164:30500/v3/auth/tokens\": net/http: TLS handshake timeout"]}

**Comment by hoganlxj** [comment]
看着是keystone服务启动问题
1.查看keystone状态是否为Running
kubectl get pods -n onecloud |grep keystone
2.若keystone状态为Running，查看keystone日志中是否有error
kubectl logs -n onecloud default-keystone-XXX

**Comment by zhangr1008** [comment]
[root@cloudpods ~]# kubectl logs -n onecloud default-keystone-586f8d5f85-xnrzp |grep error
[error 2022-10-31 00:00:00 httperrors.HTTPError(httperrors.go:89)] Send error invalid token: expires_at 2022-10-30 22:21:38 +0000 UTC: expired token
[error 2022-10-31 00:00:00 auth.AuthenticateWithDelayDecision.func1(middleware.go:67)] Verify token failed: {"error":{"class":"InvalidCredentialError","code":401,"data":{"fields":[{}],"id":"invalid token %s"},"details":"invalid token guest_token: invalid token"}}
[error 2022-10-31 02:30:25 tokens.authUserByIdentityInternal(auth.go:100)] find no user with name admin
[error 2022-10-31 02:30:25 tokens.authUserByIdentity(auth.go:74)] authenticate fail for {"methods":["password"],"password":{"user":{"name":"admin","password":"***"}}} reason: UserNotFound
[error 2022-10-31 02:30:25 httperrors.HTTPError(httperrors.go:89)] Send error UserNotFound
[root@cloudpods ~]# kubectl logs -n onecloud default-keystone-586f8d5f85-xnrzp |grep Error
[error 2022-10-31 00:00:00 httperrors.HTTPError(httperrors.go:89)] Send error invalid token: expires_at 2022-10-30 22:21:38 +0000 UTC: expired token
[error 2022-10-31 00:00:00 auth.AuthenticateWithDelayDecision.func1(middleware.go:67)] Verify token failed: {"error":{"class":"InvalidCredentialError","code":401,"data":{"fields":[{}],"id":"invalid token %s"},"details":"invalid token guest_token: invalid token"}}
[error 2022-10-31 02:30:25 httperrors.HTTPError(httperrors.go:89)] Send error UserNotFound

我尝试过用WEB登录，报用户名和密码错误

**Comment by zexi** [comment]
@zhangr1008 在控制节点上执行下面的命令看下是否有 admin 这个 user ？
```bash
source <(ocadm cluster rcadmin)
climc user-list
```

**Comment by zhangr1008** [comment]
[root@cloudpods ~]# source <(ocadm cluster rcadmin)
[root@cloudpods ~]# climc user-list
Post "https://192.168.0.164:30500/v3/auth/tokens": net/http: TLS handshake timeout
{"error":{"class":"ClientError","code":499,"details":"Post \"https://192.168.0.164:30500/v3/auth/tokens\": net/http: TLS handshake timeout","request":{"body":"{\"auth\":{\"context\":{\"source\":\"cli\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"name\":\"s...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"209","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708"},"method":"POST","url":"https://192.168.0.164:30500/v3/auth/tokens"}}}

**Comment by zexi** [comment]
> https://192.168.0.164:30500

@zhangr1008 直接进入 climc pod 使用内部网络执行 user-list 看下能否成功：
```bash
# 进入 climc 容器：
```

**Comment by mingo0117** [comment]
> [root@cloudpods ~]# source <(ocadm cluster rcadmin) [root@cloudpods ~]# climc user-list Post "https://192.168.0.164:30500/v3/auth/tokens": net/http: TLS handshake timeout {"error":{"class":"ClientError","code":499,"details":"Post "[https://192.168.0.164:30500/v3/auth/tokens\](https://192.168.0.164:30500/v3/auth/tokens%5C)": net/http: TLS handshake timeout","request":{"body":"{"auth":{"context":{"source":"cli"},"identity":{"methods":["password"],"password":{"user":{"name":"s...ult"},"name":"system"}}}}","headers":{"Content-Length":"209","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708"},"method":"POST","url":"[https://192.168.0.164:30500/v3/auth/tokens"}}}](https://192.168.0.164:30500/v3/auth/tokens%22%7D%7D%7D)

问题和你一模一样，解决了么...
