### ISSUE TITLE
多网卡如何添加多个不同网段的子网，供虚拟机使用

### ISSUE THREAD

**Issue by goddnessheb** [yunionio/cloudpods#15260]
控制节点本身是130段的，其余两个网卡是125和140，添加的子网虚拟机网络不通

**Comment by zexi** [comment]
> 控制节点本身是130段的，其余两个网卡是125和140，添加的子网虚拟机网络不通

@goddnessheb 可参考文档：https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/host/
