### ISSUE TITLE
Allinone env fails randomly 

### ISSUE THREAD

**Issue by daqing613** [yunionio/cloudpods#15379]
Dear all, 

The Allinone env fails randomly, and I have no idea why this happens, could you please give me a clue why this happens or how to troubleshoot it? 

Service Unavailable: 
![image](https://user-images.githubusercontent.com/3414515/202146563-d8a51cf0-4a91-4526-b25b-7fb0a61473d7.png)

Pods status:
![image](https://user-images.githubusercontent.com/3414515/202146646-9b01e684-5e40-45c6-94b2-002ed2260ea0.png)

Deployment status:
![image](https://user-images.githubusercontent.com/3414515/202146735-f178863d-8a66-47f7-931f-f625bf35fc32.png)

And fails to retrieve logs from pods:
![image](https://user-images.githubusercontent.com/3414515/202146918-f9c85b37-0228-487e-ac2d-32591b34a29a.png)

Thanks in advance.

**Comment by zexi** [comment]
@daqing613 Please use the follow steps to find clues of this error:

1. Check the kubelet service log: 
```bash
journalctl -u kubelet --no-pager
```

2. This error may happended when the hostname of OS don't match the kubernetes node name:
```bash
# get kubernetes node name
kubectl get nodes -o wide

# get the OS hostname
hostname
```
