### ISSUE TITLE
nic name changed after migrating from vmware to cloudpods

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#15401]
**What happened**:

迁移前，VMwre虚拟机的网卡名称为ens160

![image](https://user-images.githubusercontent.com/1121362/202892813-74fe01b1-5d8e-4a51-94a9-b2b7203a7caf.png)

迁移后，变为ens4，导致netplan未能初始化ens4，需添加mac match的规则才能正确初始化。

![image](https://user-images.githubusercontent.com/1121362/202892830-d99e8103-780b-4453-bc07-170e7f68e557.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by wanyaoqi** [comment]
应该是装换后网卡 PCI 地址变了导致了

**Comment by dengju2020** [comment]
暂不处理
