### ISSUE TITLE
Ctrl-alt-delete not allowed for Aliyun Windows VM

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#15416]
**What happened**:
Ctrl-alt-delete not allowed for Aliyun Windows VM

![image](https://user-images.githubusercontent.com/1121362/203017442-985aba8d-66e9-4794-bd4d-bbb45cc98ef3.png)

![image](https://user-images.githubusercontent.com/1121362/203017337-a022de3f-2142-4292-9f90-e892c54fae4f.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
close https://github.com/yunionio/cloudpods/pull/15721
