### ISSUE TITLE
all in one 部署安装完后默认密码无法登录

### ISSUE THREAD

**Issue by pengcong08** [yunionio/cloudpods#15444]
使用默认用户名 admin 和 密码 admin@123 无法登录，哪里可以重置？
![image](https://user-images.githubusercontent.com/102506067/204093552-fb81b08c-c114-442a-995f-721e2225169f.png)

**Comment by hoganlxj** [comment]
请按下面步骤逐步排查
1.检查输入的密码admin@123后是否有空格
2.若账号密码输入正确，检查下后端服务是否都为Running，执行命令 kubectl get pods -A
3.若账号密码输入正确，且后端服务都是Running，重置admin用户的密码后再用登陆平台试下，重置命令
source <(ocadm cluster rcadmin)
climc user-update --password 新密码 admin
