### ISSUE TITLE
arm64环境下All in one部署失败。no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by chincccc** [yunionio/cloudpods#15520]
**What happened**:
All in one部署（服务器为鲲鹏920处理器 arm64指令集）
`fatal: [192.168.20.160]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--onecloud-version", "v3.9.2", "--operator-version", "v3.9.2"], "delta": "0:00:00.895722", "end": "2022-12-08 10:28:16.424276", "msg": "non-zero return code", "rc": 1, "start": "2022-12-08 10:28:15.528554", "stderr": "failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver\nno matching manifest for linux/arm64/v8 in the manifest list entries\n, error: exit status 1", "stderr_lines": ["failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver", "no matching manifest for linux/arm64/v8 in the manifest list entries", ", error: exit status 1"], "stdout": "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8", "stdout_lines": ["[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8"]}`
好像registry.cn-beijing.aliyuncs.com/yunion/  这个源里的kube-apiserver arm64分支被删除了，前段时间部署还是一切正常的（大概一个月前）
**Environment**:
- CPU：鲲鹏920 arm64

- OS (e.g. `cat /etc/os-release`):
- `NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"`
- Kernel (e.g. `uname -a`):
- `Linux cloudpods 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by chincccc** [comment]
通过临时方法解决了，通过其他源拉取了缺的包，再建了一个本地docker源，把全部包都推到这个本地源，再在config-allinone.yml中指定源地址为本地源。

希望官方能尽快把源补齐

**Comment by chincccc** [comment]
以下是3.9.2用到的全部docker镜像，方便碰到同样问题的小伙伴快速搭建本地源
`devtool:v3.9.1
scheduledtask:v3.9.1
kube-apiserver:v1.15.8
host:v3.9.1
loki:2.2.1
prometheus-operator:v0.37.0
pause:3.1
coredns:1.3.1
glance:v3.9.1
cloudid:v3.9.1
monitor:v3.9.1
k8s-sidecar:1.12.2
cloudevent:v3.9.1
local-path-provisioner:v0.0.11
telegraf:release-1.19.2-0
kube-proxy:v1.15.8
ansibleserver:v3.9.1
onecloud-operator:v3.9.1
cloudproxy:v3.9.1
metrics-server:v0.3.6
influxdb:1.7.7
kube-controller-manager:v1.15.8
region:v3.9.1
kubeserver:v3.9.1
calico-node:v3.12.1
grafana:6.7.1
etcd:3.4.6
notify:v3.9.1
calico-cni:v3.12.1
scheduler:v3.9.1
traefik:v1.7.34
promtail:2.2.1
busybox:1.28.0-glibc
onecloud-operator:v3.9.2
openvswitch:2.10.5-1
kube-state-metrics:v1.9.8
notify-plugins:v3.9.1
kube-scheduler:v1.15.8
logger:v3.9.1
vpcagent:v3.9.1
onecloud-service-operator:v3.9.1
apigateway:v3.9.1
esxi-agent:v3.9.1
yunionconf:v3.9.1
keystone:v3.9.1
host-deployer:v3.9.1
telegraf-init:release-1.19.2-0
calico-kube-controllers:v3.12.1
web:v3.9.1
minio:RELEASE.2021-06-17T00-10-46Z
climc:v3.9.1
region-dns:v3.9.1
telegraf-raid-plugin:release-1.6.4
sdnagent:v3.9.1
host-image:v1.0.4
cloudmon:v3.9.1
webconsole:v3.9.1`

**Comment by zexi** [comment]
@zhasm 请帮忙看下，registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8 里面相关的镜像是不是被删除了？
以前是有的

**Comment by zhasm** [comment]
@chincccc  已经重新推送镜像，我这边验证通过了，请您再次测试～

**Comment by zexi** [comment]
> @zhasm 请帮忙看下，registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8 里面相关的镜像是不是被删除了？ 以前是有的

现在有了 @chincccc @zhasm 

```bash
$ docker manifest inspect registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:f034ddac32efadf73097544d1eb954c889b5b583e57150289bcf6fd3d16957dc",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:b8d01a40d569c5c0aa5e4fcc8915ecc0394172190177026a8d22676b5c8004c9",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}

$ skopeo inspect  docker://registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8 --override-os linux
{
    "Name": "registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver",
    "Digest": "sha256:9345e00e2d20607de41cddc5e13f2358784f75410c1a394e3b3fe95856ada633",
    "RepoTags": [
        "v1.15.8-amd64",
        "v1.15.8-arm64",
        "v1.15.8"
    ],
    "Created": "2020-01-15T11:51:21.396450321Z",
    "DockerVersion": "18.09.3",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:9f9ba9541db23d4d404cb517c6da46064cb9d7ca089ed84f514c7b0fb78bfb8f",
        "sha256:07aa2ae0b8ddfebd5c245bebdbd1f6950f8423d19f3bd7c1c648de0346221fec"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:9f9ba9541db23d4d404cb517c6da46064cb9d7ca089ed84f514c7b0fb78bfb8f",
            "Size": 18557783,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:07aa2ae0b8ddfebd5c245bebdbd1f6950f8423d19f3bd7c1c648de0346221fec",
            "Size": 29033992,
            "Annotations": null
        }
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}

```

**Comment by chincccc** [comment]
> @chincccc 已经重新推送镜像，我这边验证通过了，请您再次测试～

kube-controller-manager:v1.15.8这个镜像的arm版好像也不存在源中
