### ISSUE TITLE
climc server-list --hypervisor not support cloudpods

### ISSUE THREAD

**Issue by WangAnge** [yunionio/cloudpods#15521]
**What happened**:

climc> server-list --hypervisor cloudpods
Usage: climc server-list [--wire WIRE] [--network NETWORK] [--disk DISK] [--host HOST] [--baremetal] [--gpu] [--secgroup SECGROUP] [--admin-secgroup ADMIN_SECGROUP] [--hypervisor {kvm,esxi,container,baremetal,aliyun,azure,aws,huawei,ucloud,zstack,openstack,google,ctyun}] [--region REGION] [--with-eip] [--without-eip] [--os-type {linux,windows,vmware}] [--vpc VPC] [--usable-server-for-eip USABLE_SERVER_FOR_EIP] [--without-user-meta] [--eip-associable] [--group GROUP] [--host-sn HOST_SN] [--ip-addr IP_ADDR] [--order-by-disk {asc,desc}] [--order-by-host {asc,desc}] [--order-by-network {asc,desc}] [--order-by-ip {asc,desc}] [--resource-type {shared,prepaid,dedicated}] [--billing-type {postpaid,prepaid}] [--scaling-group SCALING_GROUP] [--limit LIMIT] [--offset OFFSET] [--order-by ORDER_BY] [--order {desc,asc}] [--details] [--show-fail-reason] [--search SEARCH] [--meta] [--filter FILTER] [--joint-filter JOINT_FILTER] [--filter-any] [--admin] [--tenant|--project TENANT] [--project-domain PROJECT_DOMAIN] [--user USER] [--field FIELD] [--scope {system,domain,project,user}] [--system] [--pending-delete] [--pending-delete-all] [--delete-all] [--show-emulated] [--export-keys EXPORT_KEYS] [--export-file <EXPORT_FILE_PATH>] [--export-texts EXPORT_TEXTS] [--tags TAGS] [--no-tags NO_TAGS] [--user-tags USER_TAGS] [--cloud-tags CLOUD_TAGS] [--no-user-tags NO_USER_TAGS] [--no-cloud-tags NO_CLOUD_TAGS] [--project-tags PROJECT_TAGS] [--no-project-tags NO_PROJECT_TAGS] [--domain-tags DOMAIN_TAGS] [--no-domain-tags NO_DOMAIN_TAGS] [--manager MANAGER] [--account ACCOUNT] [--provider {OneCloud,VMware,Aliyun,Apsara,Qcloud,Azure,Aws,Huawei,OpenStack,Ucloud,ZStack,Google,Ctyun,Cloudpods,Nutanix,BingoCloud}] [--brand BRAND] [--cloud-env {public,private,onpremise,private_or_onpremise}] [--public-cloud] [--private-cloud] [--on-premise] [--managed] [--paging-marker PAGING_MARKER] [--paging-order {DESC,ASC}] [--order-by-tag ORDER_BY_TAG] [--delete DELETE] [--os-arch {i386,x86,x86_32,x86_64,arm,aarch32,aarch64}] [--vpc-provider VPC_PROVIDER] [--with-meta/--without-meta] [--with-user-meta/--without-user-meta] [--with-host/--without-host] [--help] [--zone ZONE]

Unknown argument 'cloudpods' for hypervisor, did you mean "ucloud"?

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
- uname -a
Linux bj-sc-d11-08u-controller-35 3.10.0-1160.6.1.el7.yn20201125.x86_64 #1 SMP Sat Nov 21 12:06:27 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zexi** [comment]
Fixed: https://github.com/yunionio/cloudpods/pull/15541
