### ISSUE TITLE
v3.9.5 compute service abnormal

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#15534]
**What happened**:
集群更新到V3.9.5后，前端页面会出现compute service abnormal 的弹窗，再刷新页面之后正常，但是这种现象会时不时出现。
出问题的时候，host日志会出现 链接region 异常的日志 
这种情况已经影响正常使用了
![abnormal](https://user-images.githubusercontent.com/19506558/206673963-97fe7357-8ef1-4938-9ee8-a4308806d9a3.png)

**Environment**:
集群是从v3.9.1 更新到v3.9.5 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by zexi** [comment]
可能是 region 服务 panic 了，需要看下 region 服务的日志：
 
```bash
kubectl logs -n onecloud --previous default-region-xxxx
```

**Comment by we14578** [comment]
之前的版本使用的master 版本支持incloud sphere ，现在v3.9.5 的版本中并没有这个featue，我已经手动在后端删除了原来添加的incloud spere 的云账号，但是我看日志还有 。

这是相关的日志
[root@master ~]# kubectl logs -n onecloud --previous default-region-5f66ff56f5-w4jm9 |grep -v info
[warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument default-security-rules
[warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument scheduled-task-queue-size
[warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac
[warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument minimal-sync-interval-seconds
2022/12/10 07:05:38 Allow hosts []
[warning 2022-12-10 07:05:38 mysql.NewTristateColumn(column.go:176)] TristateColumn enabled should have no nullable tag
[warning 2022-12-10 07:05:38 mysql.NewTristateColumn(column.go:176)] TristateColumn enabled should have no nullable tag
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 11
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 12
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 13
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 14
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 15
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 16
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 17
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 18
[warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 19
[error 2022-12-10 07:05:39 models.(*SStorageManager).SyncCapacityUsedForEsxiStorage(storages.go:778)] unable to GetProvider: Cloud provider is not enabled: InvalidStatusError
[fatal 2022-12-10 07:15:23 models.(*SGuest).GetDriver(guests.go:815)] Unsupported hypervisor incloudsphere

**Comment by zexi** [comment]
> 之前的版本使用的master 版本支持incloud sphere ，现在v3.9.5 的版本中并没有这个featue，我已经手动在后端删除了原来添加的incloud spere 的云账号，但是我看日志还有 。
> 
> 这是相关的日志 [root@master ~]# kubectl logs -n onecloud --previous default-region-5f66ff56f5-w4jm9 |grep -v info [warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument default-security-rules [warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument scheduled-task-queue-size [warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac [warning 221210 07:05:38 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument minimal-sync-interval-seconds 2022/12/10 07:05:38 Allow hosts [] [warning 2022-12-10 07:05:38 mysql.NewTristateColumn(column.go:176)] TristateColumn enabled should have no nullable tag [warning 2022-12-10 07:05:38 mysql.NewTristateColumn(column.go:176)] TristateColumn enabled should have no nullable tag [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 11 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 12 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 13 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 14 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 15 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 16 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 17 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 18 [warning 2022-12-10 07:05:39 appsrv.(*SWorkerManager).scheduleWithLock(workers.go:258)]CronJobWorkers: BUSY activeWork 4 detachedWork 0 max 4 queue: 19 [error 2022-12-10 07:05:39 models.(*SStorageManager).SyncCapacityUsedForEsxiStorage(storages.go:778)] unable to GetProvider: Cloud provider is not enabled: InvalidStatusError [fatal 2022-12-10 07:15:23 models.(*SGuest).GetDriver(guests.go:815)] Unsupported hypervisor incloudsphere

@ioito 请看下这个问题

**Comment by ioito** [comment]
先打下master镜像，替换region服务，把incloudsphere的账号删了，再回退到3.9版本，3.9版本不支持incloudsphere账号

**Comment by ioito** [comment]
检查下guests_tbl(hypervisor字段)和hosts_tbl(host_type)这两张表, 把没删的删掉

**Comment by nxsre** [comment]
> 检查下guests_tbl(hypervisor字段)和hosts_tbl(host_type)这两张表, 把没删的删掉

把相应的数据删掉就不再出现 "[fatal 2022-12-10 07:15:23 models.(*SGuest).GetDriver(guests.go:815)] Unsupported hypervisor incloudsphere"
