### ISSUE TITLE
k8sv1.20.6版导入时状态一直是创建

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#15535]
![image](https://user-images.githubusercontent.com/29140975/206856131-cd60a1df-62df-43c0-a9f3-f83982ad9ced.png)

**Comment by zexi** [comment]
没有复现这个问题，重启下 kubeserver 这个 pod 能状态能恢复吗？

**Comment by zexi** [comment]
> > 没有复现这个问题，重启下 kubeserver 这个 pod 能状态能恢复吗？
> 
> 在all in one 方式下部署的有这个问题，在Helm 方式下部署的没有问题，纳管是同一个k8s <img alt="未命名1671003419" width="877" src="https://user-images.githubusercontent.com/29140975/207536195-2f4aa38e-9f33-4d6c-9821-094a2a9b94f3.png"> <img alt="未命名1671003476" width="949" src="https://user-images.githubusercontent.com/29140975/207536208-da478026-ea2e-4389-b7a8-d6d26a0f81d9.png">

应该是网络的问题，allinone 的虚拟机和 k8s 集群里面部署的节点在同一个网络吗？

**Comment by hewenxiang** [comment]
> 

同一个网络

**Comment by zexi** [comment]
> > 
> 
> 同一个网络

看下 default-kubeserver 这个 pod 的日志有没有报错，另外进入 default-climc 这个 pod 执行 `climc k8s-cluster-sync $cluster` 可以同步纳管的集群，看下这样会不会恢复。

**Comment by zexi** [comment]
@hewenxiang 这个 PR 修复该问题：https://github.com/yunionio/kubecomps/pull/200
在下次正式发版之前，可暂时通过替换 default-kubeserver 镜像为：registry.cn-beijing.aliyuncs.com/zexi/kubeserver:fix-import 来解决，命令为：

```bash
$ kubectl set image -n onecloud deployments default-kubeserver *=registry.cn-beijing.aliyuncs.com/zexi/kubeserver:fix-import
```
