### ISSUE TITLE
纳管openstack yoga版 无法同步宿主机的内存和cpu

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#15536]
同步成功过一次，再一次同步时内存和cpu同步失败
![image](https://user-images.githubusercontent.com/29140975/206856403-679d41b8-80b1-480c-905f-fbbd85a92d59.png)
{"log":"[error 2022-12-10 13:12:36 db.(*SOpsLogManager).LogEvent(opslog.go:195)] logevent for an object without ID: *models.SCloudaccount\n","stream":"stderr","time":"2022-12-10T13:12:36.855070822Z"}
{"log":"[error 2022-12-10 13:12:36 db.(*SOpsLogManager).LogEvent(opslog.go:195)] logevent for an object without ID: *models.SCloudaccount\n","stream":"stderr","time":"2022-12-10T13:12:36.855455399Z"}
{"log":"[error 2022-12-10 13:12:36 taskman.execITask(tasks.go:525)] fail to find cloudaccount object \n","stream":"stderr","time":"2022-12-10T13:12:36.856693673Z"}
{"log":"[error 2022-12-10 13:12:39 openstack.(*SProject).GetStatus(project.go:58)] get project service token error: Authenticate: {\"error\":{\"class\":\"Unauthorized\",\"code\":401,\"details\":\"The request you have made requires authentication.\",\"request\":{\"headers\":{\"Content-Length\":\"197\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"http://172.16.0.68:5000/v3/auth/tokens\"}}} *errors.withStack\n","stream":"stderr","time":"2022-12-10T13:12:39.95255826Z"}
{"log":"[error 2022-12-10 13:12:40 openstack.(*SProject).GetStatus(project.go:58)] get project myproject token error: Authenticate: {\"error\":{\"class\":\"Unauthorized\",\"code\":401,\"details\":\"The request you have made requires authentication.\",\"request\":{\"headers\":{\"Content-Length\":\"199\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"http://172.16.0.68:5000/v3/auth/tokens\"}}} *errors.withStack\n","stream":"stderr","time":"2022-12-10T13:12:40.227035844Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule 56f1b3af-bf61-4b2a-b06e-ce33235309eb for secgroup default(32e747f7-c970-4646-bd8c-a49b91c04adb) error: ethertype: IPv6 remoteGroupId: 32e747f7-c970-4646-bd8c-a49b91c04adb\n","stream":"stderr","time":"2022-12-10T13:12:41.735588746Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule 60159707-daad-4b41-a87d-f4c96e0104e9 for secgroup default(32e747f7-c970-4646-bd8c-a49b91c04adb) error: ethertype: IPv4 remoteGroupId: 32e747f7-c970-4646-bd8c-a49b91c04adb\n","stream":"stderr","time":"2022-12-10T13:12:41.735603879Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule d9722b2b-dd21-4768-b4e6-618fd6fcadf1 for secgroup default(32e747f7-c970-4646-bd8c-a49b91c04adb) error: ethertype: IPv6 remoteGroupId: \n","stream":"stderr","time":"2022-12-10T13:12:41.735607223Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule 5579835b-59e1-41d0-97c1-d6f8e1c8498d for secgroup default(e8dc9599-0722-4405-bb69-18f8a736b9d1) error: ethertype: IPv4 remoteGroupId: e8dc9599-0722-4405-bb69-18f8a736b9d1\n","stream":"stderr","time":"2022-12-10T13:12:41.801472474Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule 9808f5ca-d321-4f49-9944-0b40f3a183e9 for secgroup default(e8dc9599-0722-4405-bb69-18f8a736b9d1) error: ethertype: IPv6 remoteGroupId: e8dc9599-0722-4405-bb69-18f8a736b9d1\n","stream":"stderr","time":"2022-12-10T13:12:41.801495703Z"}
{"log":"[error 2022-12-10 13:12:41 openstack.(*SSecurityGroup).GetRules(securitygroup.go:197)] failed to convert rule ca2a76f9-c377-4251-a6e9-92cda761517c for secgroup default(e8dc9599-0722-4405-bb69-18f8a736b9d1) error: ethertype: IPv6 remoteGroupId: \n","stream":"stderr","time":"2022-12-10T13:12:41.801501075Z"}
{"log":"[error 2022-12-10 13:12:41 models.syncIPv6Gateways(cloudsync.go:469)] GetICloudIPv6Gateways for vpc 98ec4129-cf6e-47d3-b2b9-1df8874ed084 failed GetICloudIPv6Gateways: NotImplementedError\n","stream":"stderr","time":"2022-12-10T13:12:41.873935688Z"}
{"log":"[error 2022-12-10 13:12:41 models.syncRegionSnapshotPolicies(cloudsync.go:1664)] GetISnapshotPolicies for region openstack-RegionOne failed GetISnapshotPolicies: NotImplementedError\n","stream":"stderr","time":"2022-12-10T13:12:41.895597346Z"}
{"log":"[error 2022-12-10 13:12:45 models.syncRegionLoadbalancerAcls(cloudsyncelb.go:61)] GetILoadBalancerAcls for region openstack-RegionOne failed region.GetLoadBalancerAcls: region.GetLoadbalancerListeners(): lbList: GetServiceURL(load-balancer, RegionOne, internal): No such service load-balancer: NotFoundError\n","stream":"stderr","time":"2022-12-10T13:12:45.512458029Z"}
{"log":"[error 2022-12-10 13:12:45 models.syncRegionLoadbalancerCertificates(cloudsyncelb.go:37)] GetILoadBalancerCertificates for region openstack-RegionOne failed NotImplementedError\n","stream":"stderr","time":"2022-12-10T13:12:45.512463472Z"}
{"log":"[error 2022-12-10 13:12:45 models.syncRegionLoadbalancers(cloudsyncelb.go:85)] GetILoadBalancers for region openstack-RegionOne failed region.GetLoadbalancers(): lbList: GetServiceURL(load-balancer, RegionOne, internal): No such service load-balancer: NotFoundError\n","stream":"stderr","time":"2022-12-10T13:12:45.512478347Z"}

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/15545
