### ISSUE TITLE
vmware 纳管后部署vm  timeout

### ISSUE THREAD

**Issue by OwenTest** [yunionio/cloudpods#15542]
"__reason__": "agentCreateGuest: SHost.CreateVM2: Task.WaitForResult: Post \"https://192.168.83.88/sdk\": read tcp 10.40.3.211:50734->192.168.83.88:443: i/o timeout",

**Comment by zexi** [comment]
请先按照如下顺序排查网络问题：
1. 看下部署服务的节点能够访问 192.168.33.88 
2. kubectl exec -ti -n onecloud default-region-xxx sh ，排查 pod 能否访问 192.168.83.88

**Comment by OwenTest** [comment]
1. 节点ping vcenter 83.88 是通的。
2. pod  sh后也是可以通讯的。

还是这个报错：

{
    "__reason__": "agentCreateGuest: SHost.CreateVM2: Task.WaitForResult: Post \"https://192.168.83.88/sdk\": read tcp 10.40.3.211:52018->192.168.83.88:443: i/o timeout",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}

**Comment by zexi** [comment]
> 1. 节点ping vcenter 83.88 是通的。
> 2. pod  sh后也是可以通讯的。
> 
> 还是这个报错：
> 
> { "**reason**": "agentCreateGuest: SHost.CreateVM2: Task.WaitForResult: Post "[https://192.168.83.88/sdk\](https://192.168.83.88/sdk%5C)": read tcp 10.40.3.211:52018->192.168.83.88:443: i/o timeout", "**stage**": "OnDeployGuestComplete", "**status**": "error" }

telnet 192.168.83.88 443 能通吗？如果不通请排查下服务是否监听在 443 端口，以及有没有防火墙限制之类的

**Comment by OwenTest** [comment]
telnet 443端口是通的，我改成同一个子网下，也会报这个错误。 防火墙没有做限制。

**Comment by dengju2020** [comment]
> 

Post "[https://192.168.83.88/sdk\](https://192.168.83.88/sdk%5C)  有一个反斜杠，是否是这个导致的？

方便可以添加沟通群：https://www.cloudpods.org/zh/docs/contact/

**Comment by ioito** [comment]
可以打个最新的esxi-agent的镜像替换下服务，看下是否可以修复这个问题

**Comment by OwenTest** [comment]
已经修复了，谢谢！


在 2023年1月16日，上午11:46，屈轩 ***@***.***> 写道：

﻿

可以打个最新的esxi-agent的镜像替换下服务，看下是否可以修复这个问题
