### ISSUE TITLE
保存虚拟机镜像状态一直是【等待保存】

### ISSUE THREAD

**Issue by jidesheng6** [yunionio/cloudpods#15640]
使用ISO启动安装系统后，关机保存镜像，持续了很长时间都是等待保存的状态，镜像保存不下来

是因为机器性能不行吗？还是别的原因？

![图片](https://user-images.githubusercontent.com/25132549/209791776-80873137-2b49-4c60-862c-3277430fac70.png)

![图片](https://user-images.githubusercontent.com/25132549/209791689-b074e3dd-e16a-498c-8673-02b7d90efd9e.png)

**Comment by jidesheng6** [comment]
感觉可能是机器性能不行。。。
上传了一个ISO上去，在保存的时候1分钟负载达到了75，平常情况机器负载一般不超过2
![图片](https://user-images.githubusercontent.com/25132549/209935295-7e18113f-80bd-4314-91d5-d6d40d61f3bb.png)

**Comment by dengju2020** [comment]
我们本地测试下，稍晚回复

**Comment by jidesheng6** [comment]
好的好的，我也重新找了台性能稍微好点的机子重新装了cloudpods再试试
