### ISSUE TITLE
系统镜像上传状态一直转圈，镜像不可用

### ISSUE THREAD

**Issue by fangfenghuang** [yunionio/cloudpods#15646]
**What happened**:
1. 界面上传系统镜像：镜像文件及镜像URL方式，文件传输完成后界面镜像状态一直处于已保存【转圈圈】状态(超过12h未保存完成)，非可用状态无法创建虚拟机

2. climc命令上传同样有该问题
```bash
climc image-upload --format qcow2 --os-type Linux --os-arch x86_64 --standard CentOS-7-x86_64-GenericCloud-1711.qcow2 ./CentOS-7-x86_64-GenericCloud-1711.qcow2
```
**Environment**:

- OS (e.g. `cat /etc/os-release`): centos:7
- Kernel (e.g. `uname -a`): 5.4.130-1.yn20221208.el7.x86_64
- Service Version (Execute: `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): release/3.9  （all-in-one）

**Comment by jidesheng6** [comment]
我也是一样的问题，今天中午闪现看到了DNSERROR，不确定会不会和这个有关

**Comment by zexi** [comment]
@fangfenghuang @jidesheng6 环境是使用 ocboot 部署在虚拟机里面，还是用 helm 部署到 k8s 集群里面的？
目前用 helm 部署的会有这个问题，直接用 ocboot 部署的还没有复现这个问题。

**Comment by jidesheng6** [comment]
@zexi 先说一下我这边情况：
1、我这边上传镜像一直会提示资源异常或保存失败；今天换了一台CPU性能稍微好点的用ocboot重新部署了cloudpods环境，就可以正常上传了
2、我之前开的issue那边提到的镜像导出长时间没反应，我今天看了一下已经成功导出了，只是我估计导出导了一晚上。

总体结论：

整体机器情况：
A机器：PVE里装的Centos7，CPU是E3-1260-lv5 
B机器：Windows上的vmware里装的Centos7，CPU是12500H

A机器的情况不乐观，反正负载很高，也就导致了各种问题的产生
B机器的情况还好，平均负载观察下来也都正常，部署过程走的也很流畅

总的来说有点不好意思，早该发现是机器性能不行的

**Comment by fangfenghuang** [comment]
> @fangfenghuang @jidesheng6 环境是使用 ocboot 部署在虚拟机里面，还是用 helm 部署到 k8s 集群里面的？ 目前用 helm 部署的会有这个问题，直接用 ocboot 部署的还没有复现这个问题。

我这边复现的场景是虚拟机all-in-one部署的两个环境都会复现上传一直处于非可用状态，但也有偶现可以上传成功的情况，另一个是用物理机all-in-one部署的集群就基本能顺利上传

**Comment by zexi** [comment]
> @fangfenghuang @jidesheng6 环境是使用 ocboot 部署在虚拟机里面，还是用 helm 部署到 k8s 集群里面的？ 目前用 helm 部署的会有这个问题，直接用 ocboot 部署的还没有复现这个问题。


通过 helm 部署的问题已经修复，PR 为： https://github.com/yunionio/cloudpods-operator/pull/766
ocboot 部署的 PR 为：https://github.com/yunionio/ocboot/pull/636 ，可通过 `helm upgrade` 升级来修复。

**Comment by zexi** [comment]
@fangfenghuang @jidesheng6 如果是机器性能问题，可以通过下面的命令配置下上传镜像后转换的目标格式，我能想到比较耗 cpu 的地方是上传镜像后，转换成目标格式的问题，默认情况会转换成 qcow2 和 vmdk 的格式，可以改成只用 qcow2 的试试：
```bash
climc service-config-edit glance
...
  target_image_formats:
  - qcow2
...
```

**Comment by fangfenghuang** [comment]
> @fangfenghuang @jidesheng6 如果是机器性能问题，可以通过下面的命令配置下上传镜像后转换的目标格式，我能想到比较耗 cpu 的地方是上传镜像后，转换成目标格式的问题，默认情况会转换成 qcow2 和 vmdk 的格式，可以改成只用 qcow2 的试试：
> 
> ```shell
> climc service-config-edit glance
> ...
>   target_image_formats:
>   - qcow2
> ...
> ```

改成qcow2后上传都成功了
