### ISSUE TITLE
notify webhook 消息事件丢失

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#15728]
**What happened**:
集群：v3.9.5
消息设置中，添加了机器人，验证可以通过机器人发送消息。
但是在发送的消息中，丢失了虚拟机创建事件的消息，只有虚拟机的磁盘创建成功的消息。
具体情况如图，正常的环境中是有server create事件的，异常环境中，只有disk create 事件的日志

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (Execute: `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/19506558/211021454-a0b5fe0a-7721-4ee8-a71b-164a34ef7f60.png">
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/19506558/211021497-74dc20bc-3374-43f5-8306-2619a1962b59.png">

**Comment by zexi** [comment]
@we14578

**Comment by zexi** [comment]
这个 PR https://github.com/yunionio/cloudpods/pull/15790 修复该问题
