### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by DonginKang** [yunionio/cloudpods#15767]
I'm trying to install that program, but I'm getting an error at the steps(TASK [mariadb : Change root password]) below. do you know how to solve

[root@ip-10-0-15-69 ocboot]# ./run.py 10.0.15.69
ansible-playbook 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
ip-10-0-15-69.ap-northeast-2.compute.internal
reuse current yaml: /root/ocboot/config-allinone-current.yml
ansible-playbook -e '{"no_reboot": "true", "onecloud_major_version": "v3_8"}' -i /tmp/host_inventory.yml ./onecloud/install-cluster.yml

PLAY [all] *******************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************
ok: [10.0.15.69]

TASK [utils/detect-os : gather os specific variables] ************************************************************************
ok: [10.0.15.69] => (item=/root/ocboot/onecloud/roles/utils/detect-os/vars/../vars/centos-x86_64.yml)

TASK [utils/detect-os : define non iso install mode] *************************************************************************
ok: [10.0.15.69]

PLAY [mariadb_node] **********************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************
ok: [10.0.15.69]

TASK [Install mariadb] *******************************************************************************************************
ok: [10.0.15.69]

TASK [Install mariadb on centos] *********************************************************************************************
ok: [10.0.15.69]

TASK [mariadb : Set discovered Ansible Python interpreter.] ******************************************************************
ok: [10.0.15.69]

TASK [Install mariadb python libs] *******************************************************************************************
skipping: [10.0.15.69]

TASK [mariadb : Copy my.cnf] *************************************************************************************************
ok: [10.0.15.69]

TASK [mariadb config hack] ***************************************************************************************************
changed: [10.0.15.69]

TASK [Enable mariadb] ********************************************************************************************************
ok: [10.0.15.69]

TASK [mariadb hack for uos] **************************************************************************************************
changed: [10.0.15.69]

TASK [mariadb : Change root password] ****************************************************************************************
[WARNING]: Module did not set no_log for update_password
failed: [10.0.15.69] (item=10.0.15.69) => {"ansible_loop_var": "item", "changed": false, "item": "10.0.15.69", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.0.15.69] (item=localhost) => {"ansible_loop_var": "item", "changed": false, "item": "localhost", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.0.15.69] (item=%) => {"ansible_loop_var": "item", "changed": false, "item": "%", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.0.15.69] (item=::1) => {"ansible_loop_var": "item", "changed": false, "item": "::1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.0.15.69] (item=127.0.0.1) => {"ansible_loop_var": "item", "changed": false, "item": "127.0.0.1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}

PLAY RECAP *******************************************************************************************************************
10.0.15.69                 : ok=11   changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by zhasm** [comment]
@DonginKang seems you are using 3.8. 
It is suggested to use 3.9. In this version, the mariadb section is more table. 
If you have no specific reasons to use 3.8, please try 3.9 instead, and let me know if you have any further problems.

**Comment by zhasm** [comment]
@DonginKang currently closed this issue. if you have further problems, feel free to reopen it. Thanks!
