### ISSUE TITLE
前端 k8s 集群界面查看失败日志报错

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#15910]
**What happened**:

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/10767027/217434328-d7bec832-9a99-43a8-9ba1-f82d7762b6ed.png">

**Environment**:

- Kernel (e.g. `uname -a`): CentOS 7
- Service Version (Execute: `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): release/3.10

/cc @GuoLiBin6

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/4127
