### ISSUE TITLE
虚拟机申请失败也会占用配额，导致还没达到配额上限就无法继续申请虚拟机

### ISSUE THREAD

**Issue by Sphrosyne** [yunionio/cloudpods#15998]
**What happened**:
虚拟机申请失败也会占用配额，导致还没达到配额上限就无法继续申请虚拟机
**Environment**:

- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux icTestothers002 3.10.0-1160.53.1.el7.yn20220518.x86_64 #1 SMP Wed May 18 02:17:25 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
3.9.1

![1676861688578](https://user-images.githubusercontent.com/67260782/219999323-e3acf320-92bf-4b6d-a5af-032ab8c351dd.png)

![1b9183c72718daa3dbfef7470822a49](https://user-images.githubusercontent.com/67260782/219999327-dd81eb56-3d72-4bf5-8c52-2e7fa6bf158d.png)

![0316b6c28abd10bd217212c93213ca9](https://user-images.githubusercontent.com/67260782/219999335-adad0c1c-3cd5-49ac-a826-c2743352a5f5.png)

**Comment by zexi** [comment]
@Sphrosyne 这个问题修复过了，可以升级到最新的 v3.9.7 版本后再试试。
