### ISSUE TITLE
删除云账号慢

### ISSUE THREAD

**Issue by momofish** [yunionio/cloudpods#16002]
**What happened**:
删除一个小规模云账号要10分钟以上，期望1分钟内完成

**Environment**:

- Version: 3.9.6

**Comment by ioito** [comment]
由于删除云账号是一条一条数据删除，所以如果数据量大的情况下是会比较慢一些，删除时会对表加锁，同时删除多个账号会更慢一些

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/17637 @momofish 这个改动可以在一分钟内完成删除
