### ISSUE TITLE
虚拟机热迁移后无法热添加虚拟网卡

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#16035]
**What happened**:
虚拟机热迁移后无法热添加虚拟网卡

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): release/3.10

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/pull/16101
