### ISSUE TITLE
无法为纳管的openstack主机设置免密登录

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#16045]
**What happened**:
openstack导入后，无法配置免密登陆，导致监控无法安装

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@ioito 看下

**Comment by hoganlxj** [comment]
https://github.com/yunionio/docs/pull/1269
