### ISSUE TITLE
T版本的openstack 虚拟机在cloudpods内vnc 连接打开报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#16089]
**What happened**:

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/16096/files#diff-98d97093eecd5f9e82e6e796c7beaba0760f9e1cd0bd16a4a1e3a9a7888aafb0
@ioito 需要加个文档说明下这个 option 怎么配置以及作用。

**Comment by ioito** [comment]
Close https://github.com/yunionio/docs/pull/1343
