### ISSUE TITLE
企业微信告警发送失败

### ISSUE THREAD

**Issue by Davidzkeng** [yunionio/cloudpods#16107]
**What happened**:

**Environment**:

- CentOS Linux:
- x86_64 GNU/Linux:

基于release3.10版本，监控发送企业微信告警，notify服务报错如下：

`Send error topic_type: missing input field`

![image](https://user-images.githubusercontent.com/25363240/222300545-504bb953-5e2c-49db-8f37-7e040d1c9c78.png)

**Comment by zexi** [comment]
@gouqi11 看下这个问题

**Comment by gouqi11** [comment]
notify服务异常修复pr:https://github.com/yunionio/cloudpods/pull/16169
