### ISSUE TITLE
登录页面访问接口问题

### ISSUE THREAD

**Issue by ChangJing89** [yunionio/cloudpods#16110]
1. 我从git上拉取dashboard代码启动后访问登录页面，调用的/api/v1/registers/status接口报错：头部中没有token：fetchAuthInfo: No token in header: InvalidCredentialError
2. 从git上的后端代码cloudpods中发现调用/api前会调用FetchAuthToken这个方法，报如上的错误，请求头并没有Authorization,这个token从何而来呢
3. 在cloudpods中并没有定位到registers这个api

**Comment by zexi** [comment]
> 1. 我从git上拉取dashboard代码启动后访问登录页面，调用的/api/v1/registers/status接口报错：头部中没有token：fetchAuthInfo: No token in header: InvalidCredentialError
> 2. 从git上的后端代码cloudpods中发现调用/api前会调用FetchAuthToken这个方法，报如上的错误，请求头并没有Authorization,这个token从何而来呢
> 3. 在cloudpods中并没有定位到registers这个api

@ChangJing89 这个应该是商业版本的代码，开源版本的前端应该不会调用这个接口，请问怎么复现这个步骤？

**Comment by zexi** [comment]
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/10767027/222697009-3bf5c9b7-1206-4746-8fe7-d65b84541d24.png">
我复现这个问题了，这个不影响使用，但是不应该调用这个 api , @easy-mj 请修复下这个问题。

**Comment by hoganlxj** [comment]
复现步骤
登陆页刷登陆url就可以复现

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/4411
