### ISSUE TITLE
单机服务 allinone 创建失败

### ISSUE THREAD

**Issue by lxd5866** [yunionio/cloudpods#16128]
**What happened**:

![image](https://user-images.githubusercontent.com/10388914/222900151-26c17869-6e67-4946-8c94-a3c0854eb55f.png)

**Environment**:
 centos7.9
  4c 8G 200Gssd

**Comment by zexi** [comment]
@lxd5866 这个问题是你用了 127.0.0.1 这个 ip 创建导致的，不能用 lo 这个网卡的 ip ，需要用 eth0 这种网卡上的 ip 。
<img width="905" alt="image" src="https://user-images.githubusercontent.com/10767027/223003141-9d557686-a91c-4812-bd9b-f9ab52831185.png">
