### ISSUE TITLE
openstack里面的资源重命名之后，在cloudpods里面不会更新

### ISSUE THREAD

**Issue by yzxiu** [yunionio/cloudpods#16139]
**What happened**:

openstack里面的资源(比如vps)重命名之后，即使重新同步数据，cloudpods里面不会更新。
release/3.9 版本

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

更新后：
![image](https://user-images.githubusercontent.com/13790023/223068137-ad75a26f-8cd7-4aca-b2c7-48236a09173f.png)

在cloudpods里面还是显示旧的名称：
![image](https://user-images.githubusercontent.com/13790023/223069521-acf5f277-2045-40f5-86ec-c630f26642f0.png)

**Comment by zexi** [comment]
@ioito 看下这个问题

**Comment by ioito** [comment]
3.10 会同步vpc名称，3.9确实没同步

**Comment by yzxiu** [comment]
> 3.10 会同步vpc名称，3.9确实没同步

资源重命名，删除等
这些操作，似乎都没有及时同步。

有些资源在openstack中删除了，到在cloudpods心理依然存在，还要外cloudpods中再删一次。

**Comment by ioito** [comment]
closes #16141 

若vpc底下的子网被其他资源使用，为了安全默认是不会删除的，只是将状态设置为异常，是需要人工判断手动去删
