### ISSUE TITLE
容器存储声明列表中存储容量那一列显示异常，管理员新建存储声明无法获取存储类列表

### ISSUE THREAD

**Issue by skw0823** [yunionio/cloudpods#16164]
What happened:
1.存储声明列表中存储容量那一列显示异常
![1](https://user-images.githubusercontent.com/13956104/223369305-fde5cb3e-2172-4c75-8e41-eafef14fbb31.png)

2.系统管理员创建存储声明，存储类列表无法获取
![808d1c1c-47f3-4fd8-83bd-5be4dced918a](https://user-images.githubusercontent.com/13956104/223369357-ad9f6519-9a62-4fc2-8ac4-a80c3930de14.jpeg)

**Comment by zexi** [comment]
https://github.com/yunionio/kubecomps/pull/234
解决此问题，需要升级 kubeserver 到 release/3.9 最新的版本。
