### ISSUE TITLE
NVME物理机转裸金属执行命令失败

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#16180]
一台NVME的物理机在纳管成功后对其进行转裸金属操作，这台机器的盘符在 yun os中 全部被识别为 nvmexx，但在转裸金属过程中出现关于sda3盘的报错如下：
{
    "__reason__": "Do deploy: Fail to resize root to 1751859: \"resize2fs /dev/sda3\" error: Process exited with status 1, cmd error: resize2fs 1.46.2 (28-Feb-2021)\nPlease run 'e2fsck -f /dev/sda3' first.\n\n",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}

手动登录该物理机，在yunos下执行 resize2fs /dev/sda3  确认没有该盘符，这种情况该怎么解决？

**Comment by tianchao001** [comment]
先暂时关闭。

**Comment by zackzhangkai** [comment]
> 一台NVME的物理机在纳管成功后对其进行转裸金属操作，这台机器的盘符在 yun os中 全部被识别为 nvmexx，但在转裸金属过程中出现关于sda3盘的报错如下： { "**reason**": "Do deploy: Fail to resize root to 1751859: "resize2fs /dev/sda3" error: Process exited with status 1, cmd error: resize2fs 1.46.2 (28-Feb-2021)\nPlease run 'e2fsck -f /dev/sda3' first.\n\n", "**stage**": "OnDeployGuestComplete", "**status**": "error" }
> 
> 手动登录该物理机，在yunos下执行 resize2fs /dev/sda3 确认没有该盘符，这种情况该怎么解决？

我也碰到了，没有绕过去，你解决了吗
