### ISSUE TITLE
kubeserver经常性panic

### ISSUE THREAD

**Issue by skw0823** [yunionio/cloudpods#16188]
**What happened**:
kubeserver 运行一段时间会出现painc，如图
![image](https://user-images.githubusercontent.com/13956104/224215669-6efae339-31ed-4e36-9578-12fcce05f09c.png)

**Comment by enhellowhy** [comment]
![62f884e6-793f-4bc0-8964-70b3eb07c1c5](https://user-images.githubusercontent.com/18282440/224292900-3dec1aa7-b690-481f-9567-d8d8006ccb22.jpeg)
删除集群的时候也会复现这个问题，目前已经定位问题代码。
![image](https://user-images.githubusercontent.com/18282440/224293361-1f879472-3623-4345-aa5d-8a6040ef2436.png)
是k8s resource的Informer重复调用了，可以按图注释掉goroutine部分代码，用factory的start就可以了。@zexi 泽玺可以再确认下这个逻辑对不对。

**Comment by zexi** [comment]
> ![62f884e6-793f-4bc0-8964-70b3eb07c1c5](https://user-images.githubusercontent.com/18282440/224292900-3dec1aa7-b690-481f-9567-d8d8006ccb22.jpeg) 删除集群的时候也会复现这个问题，目前已经定位问题代码。 ![image](https://user-images.githubusercontent.com/18282440/224293361-1f879472-3623-4345-aa5d-8a6040ef2436.png) 是k8s resource的Informer重复调用了，可以按图注释掉goroutine部分代码，用factory的start就可以了。@zexi 泽玺可以再确认下这个逻辑对不对。

@enhellowhy @skw0823 感谢反馈，是重复调用导致的，已修复：https://github.com/yunionio/kubecomps/pull/219
