### ISSUE TITLE
新建VMware虚拟机不应该报找不到IP子网

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#16234]
**What happened**:
![e224f03fba707178fb3a30c0119406f](https://user-images.githubusercontent.com/32036395/225231289-2a6e7dea-0c67-4e59-93d0-93cdd9546f42.jpg)

![1678790584028](https://user-images.githubusercontent.com/32036395/225231199-2c42ecc8-94e0-4fd7-863a-c1e03e288f38.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by dengju2020** [comment]
3.11已解决
