### ISSUE TITLE
添加备份机的虚拟机一直在复制数据状态卡住

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#16265]
**What happened**:
今天将集群升级至v3.9.8后，已添加备份机的虚拟机，在前端页面显示”数据复制“中，但磁盘只有30g，数据复制1小时后仍然在复制，判断虚拟机状态有问题。
之前查看相关的日志时，将default-host的bug level修改至debug，这次升级完成后，将bug level重新修改至info，修改完成后，rollout restart ds  default-host。
问题：
尝试通过同步虚拟机状态，以及后台指令restart虚拟机均无法改变当前虚拟机状态，解决这种状态只能通过 删除备份机的方式解除。

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
> host agent重启应该检查虚机 block-jobs状态

如果host-agent没有运行时block-jobs 成功或者失败是没法获取的，所以有block-jobs的时候不能重启 host-agent
