### ISSUE TITLE
容器集群创建出错，虚拟机无法调度，创建失败

### ISSUE THREAD

**Issue by skw0823** [yunionio/cloudpods#16289]
**What happened**:
容器集群创建，虚拟机无法调度，创建虚拟机失败，缺少了参数meidum
![9e384e88-cbf9-4456-83f8-b889f13b49dc](https://user-images.githubusercontent.com/13956104/227814673-085af912-d3be-455d-8115-25c16dab99c4.jpeg)

**Comment by zexi** [comment]
@skw0823 应该是参数传错了，看截图里面的 backend 为 'rbd/ssd' ，应该没有这种 backend ，应该传 backend: rbd ，medium: ssd
