### ISSUE TITLE
新装集群后，default-telegraf 一直崩溃的问题，是一个可复现的情况

### ISSUE THREAD

**Issue by bin1991** [yunionio/cloudpods#16282]
**What happened**:

**Environment**:

- OS (e.g. `CentOS Linux 7.9 (Core)`):
- Kernel (e.g. `5.4.130-1.yn20221208.el7.x86_64`):
- Service Version (e.g. `release/3.9` 当前最新版本):

新装集群后，default-telegraf 一直崩溃的问题，是一个可复现的情况，前台Web会一直报警，提示“宿主机下线”，“上报数据为空”
临时解决办法是重启 default-region 和所有 default-host ，如果还是继续报错，那么 default-telegraf 也需要重启；

不仅仅是新装，在之后的过程中也会出现，情况一样

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods-operator/pull/887
这个 PR 修复这个问题
