### ISSUE TITLE
vpcagent 同步报错

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#16298]
**What happened**:

3.10版本这个参数会导致删除容器集群的时候，overridePendingDelete=true，有一定的概率会触发vpcagent sync error

![img_v2_c2c0b146-c090-4cf7-be6f-0ed3763f86ag](https://user-images.githubusercontent.com/10767027/228116279-b71b0e51-c910-4a53-89b5-12f66c7cf647.jpg)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): master分支，  "gitCommit": "6d3c7e76f"

**Comment by dengju2020** [comment]
已处理
