### ISSUE TITLE
批量创建硬盘与普通创建硬盘参数不一致导致批量创建下发错误

### ISSUE THREAD

**Issue by shuai2016** [yunionio/cloudpods#16321]
使用java sdk创建硬盘，普通创建成功，使用相同的参数，批量创建失败

普通创建（Create），仅需要指定name、size、schedtags参数，可以创建成功

批量创建（BatchCreate），用上面的参数代码会直接报异常：Unsupported hypervisor，浏览器查看，状态为 初始化中，同步状态后变为 未知；
- 补充 hypervisor参数，代码不报错，浏览查看，状态为 调度失败，同步状态后变为 未知；
- 补充backend、project_id参数，创建成功
                   

下发的都是post请求的disks接口，请求体里都包含disk属性，批量增加一个count属性

正常来说，指定调度标签后，应该无需指定backend，但是这样批量创建会报错，普通创建可以成功

**Comment by zexi** [comment]
backend 这个是 bug ，正在解决

**Comment by shuai2016** [comment]
> @shuai2016 能否提供下创建的具体参数，我这边按照你的描述测试，没有复现出来问题。比如调度标签是存储的调度标签还是网络的调度标签？

创建磁盘，要使用存储标签。问题出现在批量创建上，我这边是用的java sdk，批量创建磁盘时，指定了调度标签，此时不指定backend，就会失败

**Comment by zexi** [comment]
> > @shuai2016 能否提供下创建的具体参数，我这边按照你的描述测试，没有复现出来问题。比如调度标签是存储的调度标签还是网络的调度标签？
> 
> 创建磁盘，要使用存储标签。问题出现在批量创建上，我这边是用的java sdk，批量创建磁盘时，指定了调度标签，此时不指定backend，就会失败

@shuai2016 麻烦看下调度失败的具体报错，用下面的命令：

```bash
climc scheduler-history-list 

# 找到失败的 session_id

# 根据 session_id 查看失败的日志
climc scheduler-history-show --log --raw $id 
```

然后把上述结果贴出来

**Comment by shuai2016** [comment]
> > > @shuai2016 能否提供下创建的具体参数，我这边按照你的描述测试，没有复现出来问题。比如调度标签是存储的调度标签还是网络的调度标签？
> > 
> > 
> > 创建磁盘，要使用存储标签。问题出现在批量创建上，我这边是用的java sdk，批量创建磁盘时，指定了调度标签，此时不指定backend，就会失败
> 
> @shuai2016 麻烦看下调度失败的具体报错，用下面的命令：
> 
> ```shell
> climc scheduler-history-list 
> 
> # 找到失败的 session_id
> 
> # 根据 session_id 查看失败的日志
> climc scheduler-history-show --log --raw $id 
> ```
> 
> 然后把上述结果贴出来

我这边只能操作java sdk，我把请求参数发出来
通过拦截，发现，请求的都是disks接口（POST https://10.119.1.1:30888/disks）
创建一个：

> {"disk":{"size":51200,"name":"ys-test-0406-a","schedtags":[{"resource_type":"storages","id":"xxxxx","strategy":"require"}]}}
正常；

批量创建：

> {"disk":{"size":51200,"name":"ys-test-0406-b","schedtags":[{"resource_type":"storages","id":"xxxxx","strategy":"require"}]},"count":2}
异常。

您可以看下源代码，是不是 批量创建（有count参数）时，逻辑有变化

**Comment by zexi** [comment]
> > > > @shuai2016 能否提供下创建的具体参数，我这边按照你的描述测试，没有复现出来问题。比如调度标签是存储的调度标签还是网络的调度标签？
> > > 
> > > 
> > > 创建磁盘，要使用存储标签。问题出现在批量创建上，我这边是用的java sdk，批量创建磁盘时，指定了调度标签，此时不指定backend，就会失败
> > 
> > 
> > @shuai2016 麻烦看下调度失败的具体报错，用下面的命令：
> > ```shell
> > climc scheduler-history-list 
> > 
> > # 找到失败的 session_id
> > 
> > # 根据 session_id 查看失败的日志
> > climc scheduler-history-show --log --raw $id 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后把上述结果贴出来
> 
> 我这边只能操作java sdk，我把请求参数发出来 通过拦截，发现，请求的都是disks接口（POST [https://127.0.0.1:30888/disks）](https://127.0.0.1:30888/disks%EF%BC%89) 创建一个：
> 
> > {"disk":{"size":51200,"name":"ys-test-0406-a","schedtags":[{"resource_type":"storages","id":"xxxxx","strategy":"require"}]}}
> > 正常；
> 
> 批量创建：
> 
> > {"disk":{"size":51200,"name":"ys-test-0406-b","schedtags":[{"resource_type":"storages","id":"xxxxx","strategy":"require"}]},"count":2}
> > 异常。
> 
> 您可以看下源代码，是不是 批量创建（有count参数）时，逻辑有变化

了解了，已复现，正在修复

**Comment by zexi** [comment]
@shuai2016 已修复，需要更新后端的 region 服务到临时版本：registry.cn-beijing.aliyuncs.com/yunionio/region:v3.9-lzx-0407.0，或者等我们发布下个 3.9 的版本再整体升级。
