### ISSUE TITLE
容器平台的deployments与statefulset前端无回传给后端，后端也不能直接解析

### ISSUE THREAD

**Issue by CloudCourierStation** [yunionio/cloudpods#16380]
![10417804-31b4-480c-9529-355a00d9bb45](https://user-images.githubusercontent.com/33771248/230559550-0c7a5bc4-56dc-4700-a741-668a2460dcb8.png)
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/33771248/230590587-96b6d968-f2b1-4a22-a2d7-f25d48035515.png">

**Comment by CloudCourierStation** [comment]
@zexi

**Comment by zexi** [comment]
https://github.com/yunionio/jsonutils/pull/53
@CloudCourierStation 等这个 PR 合并后，就可以解析 k8s 里面的自定义结构体
