### ISSUE TITLE
onecloud framework retain much memory and oom

### ISSUE THREAD

**Issue by willzgli** [yunionio/cloudpods#16393]
I use onecloud project (commit id: 423777c7750a, commited three years ago ) as my http server framework,  add my onw app handler, and run the server as container, but it always oom at last. I  captured the heap momory by go pprof. I had tried to find the reason from the releated code section, but failed. Coluld  someone help me to analyse it?

![image](https://user-images.githubusercontent.com/28667591/230768991-777688eb-7913-4e0d-a381-015d52377f4d.png)

**Comment by wanyaoqi** [comment]
Hi, It's hard to find the memory leak code from your screenshots.
You can update framework retest to verify is framework has memory leak.
And check your handler has memory leak.
