### ISSUE TITLE
备份机逻辑异常

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#16450]
**What happened**:
新建2台虚拟机，分别为reserver11，resrrdd，宿主机分别为node2-10-127-247-4,bm6891d0658a21
为2台虚拟机分别建立备份机，备份机的宿主机分别为bm6891d0658a21，node1-10-127-247-3
等待备份机数据同步完毕后，将宿主机bm6891d0658a21关闭。关闭之后resrrdd切换到备份机正常，可以ping通可以访问。
然后将宿主机bm6891d0658a2恢复
reserver11虚拟机前端显示同步异常，异常报告：
-----------------------
QMP Event result: &monitor.Event{Event:"\"QUORUM_REPORT_BAD\"", Data:map[string]interface {}{"error":"Input/output error", "node-name":"node_0", "sector-num":789336, "sectors-count":8, "type":"write"}, Timestamp:(*monitor.Timestamp)(0xc0014215e0)}
----------------------
之后手动同步该虚拟机状态，显示备份机关闭状态，手动开启后，等待数据同步完毕之后，正常
resrrdd 虚拟机，一直显示备份机恢复中
![image](https://user-images.githubusercontent.com/19506558/231423426-ba442447-1844-4c46-b6ed-4010a5c9da08.png)
手动同步虚拟机状态后，虚拟机显示运行中，宿主机已经切换为node1-10-127-247-3，备份机宿主机切换为bm6891d0658a21，但显示的前端备份机状态异常
![image](https://user-images.githubusercontent.com/19506558/231424309-b77caf87-1555-4f5f-a81d-7ac1fe60b532.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by TracyBin** [comment]
请问这个BUG有修复吗，另外关于备份机的实现技术原理在官方文档没有找到，后续是否可以补充一些简易的技术原理说明
