### ISSUE TITLE
监控面板添加图表时不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/cloudpods#16453]
**What happened**:
"GetMetricMeasurement by query {\"database\":\"telegraf\",\"domain_id\":\"default\",\"field\":\"usage_idle\",\"from\":\"1h\",\"measurement\":\"agent_cpu\",\"project\":\"e4789589e78f43f18465e8ffe89c13b5\",\"scope\":\"project\"}, filter \"tenant_id\" =~ /e4789589e78f43f18465e8ffe89c13b5/: getTagValues error: getTagValues query error {\"from\":\"1h\",\"metric_query\":[{\"data_source_id\":\"416b49ce-a50c-4d4a-8491-02414e771386\",\"from\":\"1h\",\"model\":{\"database\":\"telegraf\",\"group_by\":[{\"params\":[\"*\"],\"type\":\"field\"}],\"measurement\":\"agent_cpu\",\"select\":[[{\"params\":[\"usage_idle\"],\"type\":\"field\"},{\"type\":\"last\"}]],\"tags\":[{\"key\":\"\\\"tenant_id\\\"\",\"operator\":\"=~\",\"value\":\"/e4789589e78f43f18465e8ffe89c13b5/\"}]},\"to\":\"now\"}],\"show_meta\":false,\"skip_check_series\":false,\"to\":\"now\",\"unit\":false}: status code: 400 Bad Request: Influxdb invalid status"
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/16458
修复这个问题
