### ISSUE TITLE
如果集群的控制节点故障了没办法修复， 新建控制节点可以纳管之前的宿主机吗，在不影响在运行的虚拟机前提下

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#16657]

**Comment by jackgao2015** [comment]
数据库还在就可以恢复，如果数据库的数据没有了，就没办法了

**Comment by OSCAR2766** [comment]
> 数据库还在就可以恢复，如果数据库的数据没有了，找不到办法了

@jackgao2015 你好，请问控制节点挂了既然没办法恢复，那还在单独运行的计算节点上的虚拟机有办法导出来吗，重新部署在新的集群上。

**Comment by swordqiu** [comment]
@OSCAR2766 

可以这样恢复：在新集群创建同规格的虚拟机，把磁盘文件从计算节点拷贝出来，覆盖新虚拟机的磁盘文件
