### ISSUE TITLE
helm仓库在哪里

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#16727]

**Comment by jackgao2015** [comment]
推荐使用的Helm仓库的URL：
虚拟机Helm仓库：https://cloudpods-charts.oss-cn-hongkong.aliyuncs.com/
容器Helm仓库：https://apphub.aliyuncs.com/

**Comment by DSYZayn** [comment]
@jackgao2015 容器Helm仓库链接已无法访问，有没有目前推荐的容器仓库，网上找的一些在cloudpods平台上都不太兼容，会出现容器部署失败等各种问题。
