### ISSUE TITLE
[Feature] 新建 内置私有云 虚拟机数据盘的大小需要遵循 instance_capability 返回的大小

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#16747]
**What would you like to be added**:

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/10767027/232655437-34c10653-d6f3-4484-8f05-18e98751e21c.png">

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/4507
