### ISSUE TITLE
[求助/Help] 云管实例规格显示不全/云管阿里云套餐不全

### ISSUE THREAD

**Issue by shuboGe** [yunionio/cloudpods#16741]
在阿里云可用区H可以看到C6A规格的实例，但在云管中无法加载出此实例规格，云管缺少的实例规格较多。

![cloudpods](https://user-images.githubusercontent.com/50095637/232503399-6890077b-157a-43e1-85c8-3f95c077567e.png)
![aliyun](https://user-images.githubusercontent.com/50095637/232503419-e4153956-e775-4f9a-a062-a1a1f56f47a4.png)

**Comment by hoganlxj** [comment]
![image](https://user-images.githubusercontent.com/32036395/232648831-b4dd5ff5-3bd7-4033-9402-bc33f969a1c2.png)
我们本地测试环境有这个套餐，你在套餐菜单那里查看看有是否有这个套餐

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/232651728-c1a2394d-48ce-45a1-ac7a-26fa1db344e5.png)
阿里云个人账号和企业账号套餐会有部分差异，目前cloudpods阿里云使用的是企业版账号所使用的套餐，请检查你的账号类型

**Comment by jackgao2015** [comment]
@shuboGe  看一下是否可以解答你的问题，如果已经解决，请关闭issue，如果没有解决请接着回复哈

**Comment by shuboGe** [comment]
您好，我使用的是企业账号，我的账号权限为子账号，不知道是否会影响显示呢

**Comment by shuboGe** [comment]
![1681790453414](https://user-images.githubusercontent.com/50095637/232667948-ee335f86-bfbf-4548-8598-8f1352e4bb3e.png)
这里可以看到可用区H有此资源
![image](https://user-images.githubusercontent.com/50095637/232668158-84abb171-1214-426b-a4b7-5c548c9473ca.png)
dan's但是创建资源时就看不到此实例类型

**Comment by jackgao2015** [comment]
我看一下我们系统里面有没有

**Comment by jackgao2015** [comment]
我看了一下，我们系统里面是有的，不过我没有选区域，必须是华北2是么？
![image](https://user-images.githubusercontent.com/11387540/232688583-53ad909c-4cd2-49e1-ab19-177d3c97ba8e.png)

**Comment by jackgao2015** [comment]
我们系统里面选择华北2也是没有c6a这个套餐

**Comment by shuboGe** [comment]
是的，我们的资源都在华北2，另外我发现不选择可用区就会有

**Comment by shuboGe** [comment]
但是在阿里云华北2是可以下单的

**Comment by jackgao2015** [comment]
> 是的，我们的资源都在华北2，另外我发现不选择可用区就会有

这种情况下是可以创建华北2的c6a是么？

**Comment by hoganlxj** [comment]
> 是的，我们的资源都在华北2，另外我发现不选择可用区就会有

套餐也会根据可用区过滤的，华北2 可用区H 没有这个套餐就不会显示
，可以看下其他可用区是否有这个套餐

**Comment by shuboGe** [comment]
但是很奇怪 我们在阿里云的web控制台，华北2可用区H就可以看到CPU为AMD的虚拟机，已经发现挺长时间了，阿里云web端和云管的显示不同

**Comment by jackgao2015** [comment]
> 但是很奇怪 我们在阿里云的web控制台，华北2可用区H就可以看到CPU为AMD的虚拟机，已经发现挺长时间了，阿里云web端和云管的显示不同
@ioito 是否可以调API看一下，直接从阿里云的API拿到的数据里面，有没有c6a这个套餐（华北2可用区H）？
@shuboGe 我觉得大概率阿里云的API和web控制台给的数据是不一样的。当然了，得屈轩验证一下，如果API里面有，我们看看怎么修复吧，如果API里面没有，那这个确实没办法，只能客户去push阿里云改了。

（我看系统里面公有云的套餐列表有【刷新套餐】的功能，不过这种适合解决阿里云刚修改套餐数据，云管这边主动刷新拉取最新的数据）

**Comment by jackgao2015** [comment]
> > 但是很奇怪 我们在阿里云的web控制台，华北2可用区H就可以看到CPU为AMD的虚拟机，已经发现挺长时间了，阿里云web端和云管的显示不同
> 
> @ioito 是否可以调API看一下，直接从阿里云的API拿到的数据里面，有没有c6a这个套餐（华北2可用区H）？我找了一个企业账号，在云管侧华北2可用区H也是没有c6a的，如果有问题，那这个是共性问题。 @shuboGe 我觉得大概率阿里云的API和web控制台给的数据是不一样的。当然了，得屈轩验证一下，如果API里面有，我们看看怎么修复吧，如果API里面没有，那这个确实没办法，只能客户去push阿里云改了。
> 
> （我看系统里面公有云的套餐列表有【刷新套餐】的功能，不过这种适合解决阿里云刚修改套餐数据，云管这边主动刷新拉取最新的数据）

各位大佬，我好想弄清楚怎么回事了，现在云管里面的套餐数据（元数据）是通过我们公司云联壹云的阿里云账号（企业）获取的，我们公司的账号在阿里云web控制台华北2可用区H就没有c6a，也就是说在阿里云上公司不同可选的套餐也不同，这个问题我在阿里云上提一个技术支持工单看一下。有结果了，在这里反馈。

**Comment by jackgao2015** [comment]
阿里云技术支持的回复：经查询目前华北 2 （北京） H可用区没有计算型实例规格族c6a的库存，   如果需要此实例规格，建议选择可用区I，创建测试，谢谢。

另外，关于为什么不同企业的账号所查看到的套餐信息不一致，也没有回复，这件事情，也只能先这样了。

@shuboGe 使用华北2可用区i创建c6a套餐哈。可以详细看一下issue，有问题再回复，没有问题的话，把issue关了吧。我们都知道一下这件事情。

![image](https://user-images.githubusercontent.com/11387540/232950413-79588d98-5b14-426d-b84b-8b8931d7d024.png)

**Comment by jackgao2015** [comment]
@shuboGe 我先把issue关了，你有问题，再reopen就行
