### ISSUE TITLE
[BUG]虚拟机关机关不掉

### ISSUE THREAD

**Issue by guaguajia** [yunionio/cloudpods#16789]
**问题描述/What happened**:

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
k8s pod 没有报错，host日志存在报错，虚拟机关机关不掉，并且同步状态后依旧关闭不了

**Comment by jackgao2015** [comment]
![image](https://user-images.githubusercontent.com/11387540/232680692-eb069e30-a1fe-450a-9cd5-d7bb49fc8e1f.png)

**Comment by jackgao2015** [comment]
![image](https://user-images.githubusercontent.com/11387540/232680714-5f66d1fb-79df-45aa-8733-d881c86f7d4c.png)

**Comment by jackgao2015** [comment]
![image](https://user-images.githubusercontent.com/11387540/232680757-09b19e4d-7a20-4997-a1b3-d6d0305646c5.png)

**Comment by jackgao2015** [comment]
[logs.txt](https://github.com/yunionio/cloudpods/files/11258224/logs.txt)

**Comment by jackgao2015** [comment]
![image](https://user-images.githubusercontent.com/11387540/232680898-a75c9715-14c4-486b-a4d9-87f8042705cb.png)

**Comment by jackgao2015** [comment]
@guaguajia  之后把一些详细的记录也一并附上，更有利于问题的解决

**Comment by wanyaoqi** [comment]
@guaguajia  从你接口看着是正常的，你看下 region服务有报错吗，搜一下对应虚机 id

**Comment by guaguajia** [comment]
![微信截图_20230418140840](https://user-images.githubusercontent.com/44047014/232686517-9134f7be-a5de-4a79-94d0-be86ce56d54e.png)

**Comment by guaguajia** [comment]
[default-region-7b9f78b744-fwdmg_log.txt](https://github.com/yunionio/cloudpods/files/11258499/default-region-7b9f78b744-fwdmg_log.txt)

**Comment by jackgao2015** [comment]
@guaguajia  这个问题你临时关闭吧，后边有问题，你再打开。

**Comment by wanyaoqi** [comment]
> [default-region-dns-z4dk4_log.txt](https://github.com/yunionio/cloudpods/files/11258497/default-region-dns-z4dk4_log.txt)

这个日志只包含很短一段时间的，你找下对应虚机的关机日志（搜索虚机ID

**Comment by guaguajia** [comment]
问题解决了，重启一下region  和host 的pod  问题解决
