### ISSUE TITLE
[求助/Help]经典网络单网口配置报错

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16817]
按照以下文档https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/examples/#%E5%AE%BF%E4%B8%BB%E6%9C%BA%E7%AE%A1%E7%90%86%E5%8F%A3%E4%BD%BF%E7%94%A8%E9%9D%9E1%E7%9A%84vlan-id%E5%B9%B6%E4%B8%94%E4%BA%A4%E6%8D%A2%E6%9C%BA%E4%B8%8D%E6%94%AF%E6%8C%81%E8%AE%BE%E7%BD%AEtrunk%E5%8F%A3%E7%9A%84%E9%BB%98%E8%AE%A4vlan-id%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE 的方式

配置了/etc/yunion/host.conf文件
![image](https://user-images.githubusercontent.com/10016360/232950266-4fa272ff-983a-4825-b342-e32c86f7df6b.png)

设置了VLAN子接口
![image](https://user-images.githubusercontent.com/10016360/232950627-6a58db8e-9395-4f16-ab8d-158548241e2c.png)

![image](https://user-images.githubusercontent.com/10016360/232950432-00d3e08f-8795-4791-8678-57c2d54c3a7e.png)

然后重启了host服务，出现报错报错：
![image](https://user-images.githubusercontent.com/10016360/232949928-5d45130f-36be-4e60-950c-25dcf7eb8b9b.png)

**Comment by wanyaoqi** [comment]
单网卡应该配置 ip 地址，把这个 bcast0 替换成网卡对应的 ip 地址

**Comment by shuoshadow** [comment]
@wanyaoqi 这样是能启动，但是我的网络环境是需要按照文档上的方式配置
![image](https://user-images.githubusercontent.com/10016360/232954118-59b074aa-3b74-4bf8-bda6-d0f1cba8bebb.png)

把bcast0替换成ip，并不能解决虚拟机网络不通的问题

**Comment by jackgao2015** [comment]
稍等一下哈，晚会会有人回复你哈，要做一下验证

**Comment by shuoshadow** [comment]
@swordqiu 执行这个命令后，宿主机都不通了。br0配置的ip是宿主机的ip

**Comment by shuoshadow** [comment]
这个是由物理机转为宿主机的时候就自动配置的br0

**Comment by shuoshadow** [comment]
> 不对。宿主机的IP应该配置在 en0.30 上，这样宿主机使用VLAN 30和控制器通信。en0不配置IP，en0作为虚拟机接入的物理网口，是trunk模式。
> 
> > @swordqiu 执行这个命令后，宿主机都不通了。br0配置的ip是宿主机的ip

不知道你们有没有验证过。最开始br0是宿主机ip，en0是没有ip的，这个就是物理机转为宿主机最开始的样子。后面按照你们的文档创建了VLAN 30子接口，这个时候就多了en0.30，并且ip是宿主机ip。那后面的情况就是br0和en0.30都是同一个ip，en0是没有ip的，这都是按照文档的步骤来操作的。不知道文档是否是错的呢？

**Comment by swordqiu** [comment]
宿主机IP放到 en0.30 后，就应该把 br0 上的 IP 去掉。另外，从你的描述看，我感觉宿主机不用vlan也能上网，是不是宿主机不用vlan也可以啊？

你参考的这个模式是宿主机必须设置非1的vlan才能上网的情形才适用。如果宿主机不设置vlan也能上网，那应该采用"（单网口经典网络）计算节点单个网口，虚拟机使用多VLAN经典网络"

**Comment by jackgao2015** [comment]
@shuoshadow  问题已解决的话，记得关闭issue；没有结果继续回复哈。

**Comment by shuoshadow** [comment]
@jackgao2015 还没解决哈，但是现在不想处理这种单网口的机器了。现在的问题是之前执行了ovs-vsctl del-br br0 导致宿主机网络断了，宿主机处于unknown状态，无法删除虚拟机、无法回收成为物理机，无法通过web登录，无法通过命令climc host-ssh [id] 登录。
本来想通过IDRAC登录机器，但是无法获取到密码
![image](https://user-images.githubusercontent.com/10016360/233270979-63d0d422-3d91-439b-91b8-4690d68f08d1.png)
以及我从关闭的issue里看到的默认密码mosbaremetal也不行

现在我应该如何处理掉这个宿主机呢？
![image](https://user-images.githubusercontent.com/10016360/233271354-21159b23-2996-404f-9806-80098fff593e.png)

**Comment by shuoshadow** [comment]
删除网桥的问题自行解决了，把网桥重新添加回去，绑定en0, 设置网桥ip和掩码即可
