### ISSUE TITLE
[BUG]虚拟机自动挂起，恢复不了

### ISSUE THREAD

**Issue by guaguajia** [yunionio/cloudpods#16822]
**问题描述/What happened**:

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by guaguajia** [comment]
![2](https://user-images.githubusercontent.com/44047014/233239288-9ec6cbdb-6cc8-4421-95fc-8669e7a50184.png)

**Comment by jackgao2015** [comment]
试过同步状态么？

**Comment by guaguajia** [comment]
试过了，依旧不行

**Comment by guaguajia** [comment]
重启host 了  也不行

**Comment by jackgao2015** [comment]
好的，稍等一下，我找下开发

**Comment by wanyaoqi** [comment]
你应该是执行过 suspend， 在虚机 workspace目录(/opt/cloud/workspace/servers/<GUEST_ID>)有 STATEFILE 文件，可以把这个删除了再试试

**Comment by guaguajia** [comment]
是的，删除了就解决了， 非常感谢
