### ISSUE TITLE
云账号连接时常断开

### ISSUE THREAD

**Issue by chenshushan** [yunionio/cloudpods#16823]
云账号连接时常断开  无法从日志中获取到有效错误信息  应该怎么排查
![企业微信截图_16819568056228](https://user-images.githubusercontent.com/20243864/233240082-c31a20ad-ddd7-44c9-8c6c-6cfc6390b715.png)

（另外：排查过程中有个疑问：region模块下的云账号功能和cloudid模块有什么区别）

**Comment by ioito** [comment]
cloudid里面的云账号仅仅是缓存，也是从region那边拿的

**Comment by ioito** [comment]
连接断开可以先看下region服务的日志

**Comment by chenshushan** [comment]
好的  我那个云账号时常断开的问题应该怎么找到具体的错误日志呢

**Comment by chenshushan** [comment]
我看了   里面全是一些请求信息 没什么错误信息
![企业微信截图_16819580083067](https://user-images.githubusercontent.com/20243864/233242778-303c24cb-3f65-4ea1-8f75-b91477d52612.png)

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/16825/files 可能是这几个地方引起的，可以更新下region服务，等账号连接断开在看下日志

**Comment by chenshushan** [comment]
好的  我先试试

**Comment by ioito** [comment]
应该是reason为空吧，可以全局查，哪里调用了，在上层看下reason

**Comment by chenshushan** [comment]
reason可能会为空  但是我代码里面有个冒号  数据库保存的字符串没有冒号  全局搜存下来的字符串  也只有截图代码里的一个位置
![image](https://user-images.githubusercontent.com/20243864/233320353-c180de94-a03c-42d2-9937-762a3635cc1e.png)

**Comment by ioito** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/13750250/233339432-1ee74d95-34cd-41e1-b09e-4dbcda73f140.png">
我这边测试是可以的，你再往下追踪打印下

**Comment by chenshushan** [comment]
那么可能是代码没执行到这里了  我在更新状态那个方法里的日志也没有打印  还有其他更新云账号状态的地方吗

**Comment by chenshushan** [comment]
解决了  环境有问题  感谢配合

**Comment by ioito** [comment]
有配置可以在后端日志看打印的sql   debug_sqlchemy = true
