### ISSUE TITLE
[求助/Help]Vmware环境下IP子网数据不全

### ISSUE THREAD

**Issue by liuxinglan13** [yunionio/cloudpods#16832]
比如我设置了一个子网 172.16.85.1-100 
cloudpos显示 总计:100 使用:13
但实际在这个网段里实际被占用的IP起码是30个以上.

求助怎么排查原因？谢谢
![image](https://user-images.githubusercontent.com/8065828/233282008-078c883c-ce5f-4af2-ae02-39d9aff83cc8.png)
![image](https://user-images.githubusercontent.com/8065828/233282102-95a8cc28-d35c-4eeb-9d9b-97b269020e25.png)
![image](https://user-images.githubusercontent.com/8065828/233282174-013fd082-7098-4e5e-8ccf-fe716f6fb35b.png)
![image](https://user-images.githubusercontent.com/8065828/233282491-2c7570f2-7757-4f8d-8970-6f7aab1ba888.png)

**Comment by liuxinglan13** [comment]
![image](https://user-images.githubusercontent.com/8065828/233283175-16a6537b-a63b-4b60-b6e9-20e493bb812f.png)

**Comment by ioito** [comment]
控制节点发送arp请求到要查的ip，通过返回的mac地址去找对应的机器

**Comment by jackgao2015** [comment]
@ioito 这样的话，如果机器不开机，就不会标记IP已使用是吧？

**Comment by ioito** [comment]
是的，标记ip已使用代表这个ip网络是可达的

**Comment by liuxinglan13** [comment]
@ioito  你好 但是我现在遇到的问题是 有的IP在子网里已经 被占用了 但是IP子网里 没有刷新 能手动刷新嘛？

**Comment by ioito** [comment]
可以把预留ip手动释放出来
![image](https://user-images.githubusercontent.com/13750250/233327071-9a57fbe2-3762-4a08-a44f-cad5c065b46e.png)

**Comment by jackgao2015** [comment]
@liuxinglan13  看一下问题是否解决？如果已经解决了，请关闭一下issue哈；如果没有解决，请继续回复哈

**Comment by liuxinglan13** [comment]
@ioito  那 没有在子网里提现的IP 实际已经在占用了 怎么处理呢？

**Comment by ioito** [comment]
那就在预留ip里面手动录入这些ip

**Comment by liuxinglan13** [comment]
@ioito  原来可以这样 懂了 谢谢
