### ISSUE TITLE
求助新建虚拟机报错Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab chroot: failed to run command 'sh': Exec format error\n: exit status 126

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#16839]
一开始可以创建虚拟机，但今天突然无法创建虚拟机了，但以前创建的虚拟机还能正常使用。创建新的虚拟机时，报如下：
{
    "__reason__": "Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab chroot: failed to run command 'sh': Exec format error\n: exit status 126",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}

![image](https://user-images.githubusercontent.com/58723494/233547360-3d279b3d-83da-40b9-a354-67dfb837df42.png)

**Comment by wanyaoqi** [comment]
你这个虚机的镜像用的是什么镜像？

**Comment by szz1113-1119** [comment]
使用的是上传微信群中给的网址下载的CentOS-8-20220125.1.ppc64le.qcow2

**Comment by wanyaoqi** [comment]
你是x86的服务器吧，应该使用 x86的镜像，这个架构不支持

**Comment by szz1113-1119** [comment]
ok，谢谢，没注意ppc64le
