### ISSUE TITLE
[求助/Help]Cloudpos纳管VMware Vsan环境 二层子网 对应关系

### ISSUE THREAD

**Issue by liuxinglan13** [yunionio/cloudpods#16837]
不太明白 纳管VMware Vsan环境后 自动创建的这些二层子网 和VMWare中的 分布式交换机 是如何对应的？
我在创建IP子网的时候 需要怎么去选择对应的二层网络？
![image](https://user-images.githubusercontent.com/8065828/233526433-ebced762-296e-4fe3-b832-24aab8d7332c.png)
![image](https://user-images.githubusercontent.com/8065828/233526621-1b0e9c56-d6c8-45da-914a-e6586d441f9b.png)

**Comment by jackgao2015** [comment]
@liuxinglan13  看一下这篇文章是否可以解决到你的问题？
https://www.cloudpods.org/zh/docs/function_principle/multicloud/cloudaccounts/vmware_net/
