### ISSUE TITLE
[求助/Help]物理机转为宿主机后，宿主机的root密码怎么获取

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16841]
1. 执行`climc host-logininfo 3ea9f30c-8a7f-49e5-8056-04e64536ec05`
    输出：`ciphertext too short`
![image](https://user-images.githubusercontent.com/10016360/233593477-a06cb32e-8e2f-403d-997a-6929e392ea8f.png)

2. 用户名root，密码：mosbaremetal 也无法登录

以上两种方法都不行

**Comment by hoganlxj** [comment]
物理机转换宿主机的裸金属账号密码，就是宿主机的root密码，查看步骤如下
climc server-list --system --baremetal --host 3ea9f30c-8a7f-49e5-8056-04e64536ec05
climc server-logininfo $server_id

**Comment by shuoshadow** [comment]
@hoganlxj 谢谢，按照你的方法找到密码了
