### ISSUE TITLE
异常离线的服务器，按照文档删除磁盘信息，无法删除

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#16844]
![image](https://user-images.githubusercontent.com/58723494/233822315-cb976e2a-44b4-40c4-9228-d927345075fb.png)
这个也不行

**Comment by zexi** [comment]
> 

@szz1113-1119 按照这个文档试试呢？https://www.cloudpods.org/zh/docs/setup/removehost/

**Comment by szz1113-1119** [comment]
![image](https://user-images.githubusercontent.com/58723494/233826171-95c637bf-2738-4101-9a87-28b5e0467897.png)
不行，第一步j就执行不了

**Comment by szz1113-1119** [comment]
必须的删除那个磁盘

**Comment by szz1113-1119** [comment]
![image](https://user-images.githubusercontent.com/58723494/233826247-13073446-7326-4ea5-9cf8-d8938df4bd9b.png)
执行了z这个也不行

**Comment by szz1113-1119** [comment]
![image](https://user-images.githubusercontent.com/58723494/233827539-05879898-8521-40e2-8982-32ea9a88eff9.png)
![image](https://user-images.githubusercontent.com/58723494/233827555-2476a5c5-c511-4316-bd2b-0d4f8b3aa133.png)

**Comment by wanyaoqi** [comment]
Hi @szz1113-1119 ,这个应该是一个 bug，获取 master host时没有校验是否是 sql.ErrNoRows
在这个 pr 修复了： https://github.com/yunionio/cloudpods/pull/16848
我打了一个 3.9的镜像，如果你是3.9版本的话你更新一下 region 服务再试一下：registry.cn-hangzhou.aliyuncs.com/d3lx/region:3.9-0424

**Comment by jackgao2015** [comment]
单独修改组件版本，请参见 https://www.cloudpods.org/zh/docs/development/operator-intro/#%E5%8D%95%E7%8B%AC%E4%BF%AE%E6%94%B9%E7%BB%84%E4%BB%B6%E7%89%88%E6%9C%AC
