### ISSUE TITLE
cloudpods虚拟机的vrrp vip无法通信

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#16840]
我们在一台cloudpods 虚拟机上使用keepalived 起了一个vip，系统日志显示发送了该vip的arp，但我们的直连交换机 上却没收到。
我们排查了虚拟机上的 防火墙  selinux等配置 都是关闭状态。
我们发现宿主机上有诸多的防火墙配置。
是否和这个有关？

**Comment by zexi** [comment]
> 我们在一台cloudpods 虚拟机上使用keepalived 起了一个vip，系统日志显示发送了该vip的arp，但我们的直连交换机 上却没收到。 我们排查了虚拟机上的 防火墙 selinux等配置 都是关闭状态。 我们发现宿主机上有诸多的防火墙配置。 是否和这个有关？

@tianchao001 可以看下虚拟机的“来源 mac/ip 地址” 有没有关闭？
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/10767027/233562460-629eeece-0639-495b-915c-b968331ba050.png">

**Comment by tianchao001** [comment]
是开着的，这个需要关闭是吗

**Comment by hoganlxj** [comment]
是的

**Comment by zexi** [comment]
> 关闭以后确实可以了，这个逻辑是什么啊~~

@tianchao001 因为 keepalived 的 vip 并不属于这个虚拟机，默认开启的“源/目的检查”规则只允许虚拟机自己的 ip 出入。

**Comment by fangpsh** [comment]
提供另外一个思路，用平台支持的VIP，参考这个文档：
https://www.cloudpods.org/docs/guides/onpremise/network/vpc/vpcvip/

在反亲和组中绑定 VIP，好处是更显式 知道 IP用在了这个机器上。

<img width="421" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/b063d039-a011-401e-bcae-d3e2e42b5a78">
