### ISSUE TITLE
[求助/Help]请问在项目中怎么创建mysql的联合索引

### ISSUE THREAD

**Issue by 7Achilles** [yunionio/cloudpods#16865]
我先直接在mysql客户端上创建了一个联合索引，但是在启动项目时同步出错，所以我猜测需要在项目中创建这和个联合索引。所以在代码中应该怎么创建呢？

**Comment by swordqiu** [comment]
在这个表对应的model的init里加上索引的创建

例如，给 yunioncloud/elasticips_tbl 加索引，首先定位到 yunioncloud/elasticips_tbl 对应的model 是 compute ElasticipManager，对应代码是 pkg/compute/models/elasticips.go，则在该文件的 init 中增加：

ElasticipManager.TableSpec().AddIndex(is_unique, column1, column2, ...)

其中，is_unique 指示改index是否唯一，column1, column2,... 为索引包含的列的名称

**Comment by 7Achilles** [comment]
感谢，回复很及时也很详细~
