### ISSUE TITLE
[求助/Help] 托管一台物理机遇到的问题，需要协助看一下流程中那块有问题

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#16867]
1，搭建了一台控制节点，然后把另外一台物理机（已经安装好的系统）进行托管。
2，步骤：
           a, 首先添加为此控制节点的计算节点。
           b,然后在此计算节点中安装了ipmitool ，配置了ipmi信息（设置了IP、用户名、密码）;并在计算节点服务器中修改 /etc/yunion/host.conf，添加 dhcp_relay 配置项；
           c，在控制节点服务器上，重启了host服务，并执行了ocadm baremetal enable --node $node_name --listen-interface 命令，并观察 baremetal agent pod 状态查看是否启动成功，在命令结果中没有查询到此计算节点的baremetal服务。baremetal-agent 也没有注册到控制节点；
           
请问，流程是否正确，我该如何处理？
另外在问几个问题：
1，根据文档阅读，我理解，baremetal服务应该在计算节点，baremetal-agent在控制节点，是否理解正确？
2，上次在微信群中说计算节点不能和物理机这块混为一起使用，那不把此物理机添加为计算节点，那/etc/yunion/host.conf这个文件没有，我改如何配置host服务？

**Comment by hoganlxj** [comment]
流程是有问题的，添加的计算节点不能再被托管进来

**Comment by szz1113-1119** [comment]
![image](https://user-images.githubusercontent.com/58723494/234442021-caa19e73-c71c-449f-8771-cae34b8dbf8b.png)
那你们文档中这块是不是写错了，上面写的是到已经部署好的计算节点，修改host.conf文件

**Comment by szz1113-1119** [comment]
我大概了解了，我们现在系统安装后是无法使用物理机服务的，先在环境中的任意节点上启用Baremetal服务，在物理机那个页面的按钮才能使用，然后我们再进行下一步的物理机添加，在文档中
![image](https://user-images.githubusercontent.com/58723494/234446545-67eebca9-f9eb-41b2-95e2-8248348a23c8.png)
这块的计算节点是为了启动Baremetal服务，不知道我理解的是否正确？

**Comment by jackgao2015** [comment]
先关了，有问题再打开哈
