### ISSUE TITLE
[BUG]release3.9.9 allinone安装后系统内核还是3.10

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16864]
**问题描述/What happened**:
开始发现有个pod crash
![image](https://user-images.githubusercontent.com/10016360/234070113-ded87052-fbd1-4ff5-857a-beb143d4b94f.png)

后来查了下应该是内核问题
![image](https://user-images.githubusercontent.com/10016360/234069878-09d774f1-dbd9-4a21-b13f-4bb82a49fa5a.png)

**环境/Environment**:
[root@cloudpods ~]# uname -a
Linux cloudpods 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@cloudpods ~]# cat /etc/re
redhat-lsb/       redhat-release    request-key.conf  request-key.d/    resolv.conf       resolv.conf.save  
[root@cloudpods ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

![image](https://user-images.githubusercontent.com/10016360/234070535-222e4ae4-7915-4615-a30b-2bda0dd38fdb.png)

![image](https://user-images.githubusercontent.com/10016360/234070629-97a1bf3d-1e4d-48c9-8cfc-4a4ebc14804d.png)
-->

**Comment by zhasm** [comment]
@shuoshadow 
* 请在部署环境执行一下 `dmidecode | egrep -i 'manufacturer|product' |sort -u`，看一下机器类型是物理机还是虚拟机。
* 另外请在ocboot 目录，执行`grep as_host config-allinone-current.yml` 看看有无输出。

**Comment by shuoshadow** [comment]
> * dmidecode | egrep -i 'manufacturer|product' |sort -u

1. 是虚拟机
![image](https://user-images.githubusercontent.com/10016360/234158343-daf9df29-3c36-4fca-832a-117d5a9aa10d.png)

2. 配置文件是手动改的，as_host设置的值是false
![image](https://user-images.githubusercontent.com/10016360/234158732-b5e0c6e2-1437-470f-ad5d-6025ec746fc3.png)

所以原因是虚拟机部署应该设置as_host为true吗

**Comment by zhasm** [comment]
@shuoshadow 是的。可以设置两个参数：(确保缩进正确）
```yaml
as_host: true
as_host_on_vm: true
```
然后制定yml配置，重新跑一遍部署流程 python3 run.py config-allinone-current.yml ，
重启系统（如果没有自动重启），
等所有pods 正常Running，这些服务就正常 。

**Comment by shuoshadow** [comment]
好的，我尝试下

**Comment by zhasm** [comment]
@shuoshadow 上述步骤应该可以解决您反馈的问题。本issue 先关闭了。
如过您尝试后仍有问题，可以重开本issue或新开issue均可。
