### ISSUE TITLE
[求助/Help]baremetal-agent一直刷warning日志

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16869]
日志如下，日志中的ip `192.168.30.31` 是部署cloudpods的虚拟机ip：
![image](https://user-images.githubusercontent.com/10016360/234209755-094e2780-2963-459e-afcf-5b3c4a41f971.png)

baremetal-agent所在的机器配置了DHCP Relay

**Comment by shuoshadow** [comment]
@hoganlxj 
```
dhcp_relay:
- 192.168.30.31
- 67
```
配置应该没问题，按照文档上来的，而且也能新增物理机啥的

**Comment by zexi** [comment]
> 日志如下，日志中的ip `192.168.30.31` 是部署cloudpods的虚拟机ip： ![image](https://user-images.githubusercontent.com/10016360/234209755-094e2780-2963-459e-afcf-5b3c4a41f971.png)
> 
> baremetal-agent所在的机器配置了DHCP Relay

@shuoshadow 创建物理机的时候把 pxe 网卡 mac ‘4e:fc:0a:27:fc:6d’ 地址填上试试

**Comment by shuoshadow** [comment]
@zexi 我现在是已经添加了3台物理机了，并且已经转为宿主机了。可是这个日志还在刷

**Comment by shuoshadow** [comment]
@zexi 哦抱歉，日志已经不刷了，不知道啥原因，但是好了就行。谢谢。
