### ISSUE TITLE
[文档/Docs] 开发手册-手动部署开发集群

### ISSUE THREAD

**Issue by DearAS** [yunionio/cloudpods#16872]
【开发手册-手动部署开发集群】
该文档里面只列举了4个服务，其他的服务怎么启动以及配置，没有找到相关的文档。

请问如何启动eaxi-agent、images等其它服务，相关的文档在哪里？

**Comment by ioito** [comment]
暂时没有文档，可以先贴下报错信息

**Comment by ioito** [comment]
也可以找个正常的环境，用下面命令看下配置参数，其他服务也可以用这种方法看下
kubectl get cm -n onecloud default-esxi-agent -o yaml

**Comment by DearAS** [comment]
好的
