### ISSUE TITLE
镜像与存储对象之间的关系

### ISSUE THREAD

**Issue by chenshushan** [yunionio/cloudpods#16878]
请问 Storage  Storagecache  Storagecachedimage  Cachedimage  Cloudimage几个对象之间是什么关系  有什么作用

**Comment by ioito** [comment]
storage是就是块存储，例如宿主机上挂着的某个目录
storagecache是个关联表，主要是用做多个存储可以统一缓存镜像，如果没有这个表，可能每个storage存储都需要缓存镜像
cachedimages保存了公有云私有云镜像记录，同时也缓存了内置私有云glance里面的镜像记录
storagecachedimages是用来关联storagecache和cachedimage表
cloudimages保存了公有云镜像信息，用于快速同步镜像信息，只内部使用，是cachedimags的辅助表

**Comment by chenshushan** [comment]
storagecache对象就是专门用来缓存镜像的吗

**Comment by ioito** [comment]
可以这么理解，storagecache底下可以有多个镜像 通过storagecachedimages+cachedimags关联

**Comment by chenshushan** [comment]
好的 明白了  感谢解答
