### ISSUE TITLE
[BUG]容器管理页面容器声明无法关联

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#16885]
**问题描述/What happened**:
PVC声明后，状态为bound未使用状态，但在新创建的应用中无法关联该PVC，选项当中无此PVC
请求中显示对应的字段缺少unused:true 
https://boncstack.lbhyun.com/api/v1/persistentvolumeclaims?scope=system&unused=true&cluster=38948324-66d6-40f1-8409-0333b5a404c7&namespace=onecloud-monitoring   请求结果为空
https://boncstack.lbhyun.com/api/v1/persistentvolumeclaims?scope=system&cluster=38948324-66d6-40f1-8409-0333b5a404c7
这个请求是有请求结果的

**环境/Environment**:
onceloud  v3.9.8

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/issues/16164 和改问题一样，我尽快修复下

**Comment by we14578** [comment]
另外就是k8s默认的启动参数中，PVC是无法正常使用的，就是storage class创建之后，关联的PVC无法正常使用，实际上是kube-apiserver 启动缺少参数     - --feature-gates=RemoveSelfLink=false，否则sotrage class无法自动创建pv

**Comment by we14578** [comment]
删除有问题的PVC新建后正常
