### ISSUE TITLE
[求助/Help] 通过托管完成物理机添加后出现的问题

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#16880]
你好，通过托管完成物理机后，会自动产生裸金属服务器，我把裸金属服务器删除后，在物理机管理界面无法删除此物理机。状态禁用后，也无法删除，请问有什么方法可以手动删除托管后的物理机？

第二个问题：我删除了自动产生的裸金属服务器后，我想创建裸金属服务器，但无法创建，规格不显示，物理机那块也不显示。不知道为什么？

**Comment by hoganlxj** [comment]
两个都是因为，在回收站中没有 清除之前裸金属虚拟机导致的

**Comment by jackgao2015** [comment]
先关了，有问题再打开哈

**Comment by ChaoHsin-fang** [comment]
你好，我遇到的问题是一样的，但是去回收站删掉裸金属虚拟机，一直在删除中，很长时间了

**Comment by zexi** [comment]
> 你好，我遇到的问题是一样的，但是去回收站删掉裸金属虚拟机，一直在删除中，很长时间了

@ChaoHsin-fang 需要通过 bmc 看下物理机现在什么状态，有没有进入 PXE 系统，如果没有进入 PXE 系统就会删除不了。

**Comment by ChaoHsin-fang** [comment]
@zexi  有没有比较简洁的删除方式，比如删掉哪个库哪个表的哪条数据 可以删除
