### ISSUE TITLE
物理机转裸金属提示找不到rootfs

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#16884]
物理机转裸金属时，部署阶段报错：
{
    "__reason__": "Do deploy: Find rootfs error: Fail to find rootfs",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}
是磁盘问题吗？

**Comment by tianchao001** [comment]
![image](https://user-images.githubusercontent.com/17080656/234512761-e861b75d-8ad9-445d-8f14-d1ad5e0e0abb.png)

**Comment by hoganlxj** [comment]
用这个镜像 在虚拟机那里 新建虚拟机是否正常

**Comment by tianchao001** [comment]
是正常的

**Comment by tianchao001** [comment]
但实际只有sda这个盘~ 没有sda3分区，不知道是如何触发的这个问题

**Comment by tianchao001** [comment]
![image](https://user-images.githubusercontent.com/17080656/234517350-98eb18b9-03f4-4429-a24d-bfa7170d50b3.png)

**Comment by jackgao2015** [comment]
@tianchao001  看一下下边这个issue有用么？
https://github.com/yunionio/cloudpods/issues/16610

**Comment by zexi** [comment]
@tianchao001 用的装系统镜像是什么？

**Comment by jackgao2015** [comment]
有问题，再打开哈，这个先关了。
