### ISSUE TITLE
[求助/Help]创建虚拟机时，如果挂载数据盘会导致无法从web界面免密登录

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16886]
![image](https://user-images.githubusercontent.com/10016360/234538930-9166e140-93d5-4ba0-a775-90e3bb3ecd44.png)

![image](https://user-images.githubusercontent.com/10016360/234538999-381df9f1-227e-4562-b4ca-886ab428de8b.png)

如上图所示无法直接登录。

执行 `climc server-ssh $虚拟机id ` 能直接登录
![image](https://user-images.githubusercontent.com/10016360/234539164-d21f0771-84a1-4cd8-b044-2f8fdd6a8095.png)

使用web功能探测免密登录
![image](https://user-images.githubusercontent.com/10016360/234539456-aa19d169-4664-4e05-8126-1213737b486c.png)
![image](https://user-images.githubusercontent.com/10016360/234539535-9ab058a3-6672-4c58-a78f-3adfd058f7c1.png)
日志内容
```json
{
    "method_tried": [
        {
            "host": "192.168.40.253",
            "method": "direct",
            "port": 22,
            "reason": "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain: ssh protocol error",
            "sshable": false
        },
        {
            "method": "proxy_forward",
            "port": 0,
            "reason": "cannot find an endpoint for this server",
            "sshable": false
        }
    ],
    "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJHAd/2dUIUcK8MwfjddTTHjhGcgUM6ez6TxgNHHpnh6DcNhxyXKFwkBeZQiL+QtwBxdVqudbB+gGaUD4KX/o10uMY3mEorNSknd78VcbW9owI6m/GmRDQlCpC1LGfDFFT3/vIzqiC3MCUHJ5X6XcluehEfbFjhkBC/DNMy0vX1/aUB7jjlEVzV3J0Nnnb04y4lf8vRkX0+YSXj87GP5rQFRoSKa1AainATrZIy9Pwknoo7PCZ/cwxKB4GDKUZKOJ2elIh95uTy0+xWfFEyCOB10FrgQ+n2jquTDxiVPPTiNH7nB4CXOagMAcR5c0UTZMf6SjLNrHMXvO0LaYtZQvZ\n",
    "user": "cloudroot"
}
=============================
```

升级之前是能直接免密登录的

**Comment by ioito** [comment]
web ssh自动登录是依赖于cloudroot这个系统账号的自动注入
如果可以通过root登录到虚拟机，可以看下是否存在cloudroot这个用户
如果存在，看下虚拟机所在的项目, 再通过以下命令看下这个项目的默认公钥，然后再检查下cloudroot这个用户底下 /home/cloudroot/.ssh/是否记录了正确的ssh公钥信息
climc sshkeypair-show --project <project name>

**Comment by shuoshadow** [comment]
@ioito 
1. 查看是有cloudroot用户的
![image](https://user-images.githubusercontent.com/10016360/234543968-6ab259bf-47c7-48bc-8a48-13a36f5b0b24.png)

2.这个虚拟机的/home 目录下不存在cloudroot目录，也就不存在公钥信息了
![image](https://user-images.githubusercontent.com/10016360/234544356-fa3fa9dd-2ad7-448f-a1e8-990635450107.png)

3. 使用`climc sshkeypair-show --project system` 查看是有公钥和私钥信息的

所以是什么原因导致虚拟机上有cloudroot用户，但是没有cloudroot目录以及公钥信息呢？

**Comment by shuoshadow** [comment]
跟挂载了数据盘有关吗？我看cloudroot用户信息是/opt/cloudroot
![image](https://user-images.githubusercontent.com/10016360/234545274-cc79f302-32eb-4ebb-981f-2d1be9dd7635.png)

但是我看/opt下也没有cloudroot的目录
![image](https://user-images.githubusercontent.com/10016360/234545543-0c939904-6945-408c-9d18-7d3919539630.png)

**Comment by shuoshadow** [comment]
刚测试了下，确实不挂载数据盘能直接免密登录

@ioito 所以这个算bug吗？

**Comment by ioito** [comment]
不挂载数据盘时，/opt 目录底下有 cloudroot目录没，若有，挂载了数据盘相当于覆盖掉了 /opt/cloudroot目录
用户的创建理论上应该是在/home底下的

**Comment by shuoshadow** [comment]
我明白了，是挂载目录的问题，/opt下是cloudpods存放用户信息的路径
