### ISSUE TITLE
[求助/Help] 关于一些外部服务的解释

### ISSUE THREAD

**Issue by GKilm** [yunionio/cloudpods#16882]
在数据库`keystone`中，表`endpoint`中的一些数据并不是k8s内的服务，而是一些外部服务。
请问：
    1. 这些服务的用途是什么？
    2. 如果不期望依赖于互联网中的这些服务，而是期望独立搭建这些服务，应该怎么操作呢？
 
 外部服务名称如下所示
|name|url|
|----|----|
|torrent-tracker-internal|https://tracker.yunion.cn|
|cloudmeta-internal|https://meta.yunion.cn|
|offlinecloudmeta-internal|https://yunionmeta.oss-cn-beijing.aliyuncs.com|
|torrent-tracker-public|https://tracker.yunion.cn|
|cloudmeta-public|https://meta.yunion.cn|
|offlinecloudmeta-public|https://yunionmeta.oss-cn-beijing.aliyuncs.com|

**Comment by GKilm** [comment]
offlinecloudmeta这个服务有对应的工程么？

**Comment by ioito** [comment]
这个是内部服务，每天自动同步整理公有云套餐的
