### ISSUE TITLE
[BUG]页面显示问题，重复显示了

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#16881]
**问题描述/What happened**:
![34051bdc5aebb958cc2190260f22fc8](https://user-images.githubusercontent.com/58723494/234486790-005bbe11-4185-4918-9c7c-74eec80aa7b0.png)

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/4568 做去重处理

排查：
本地未复现，可能是由 access_ip 与 server_ips 重复导致，导致重复可能原因，有一台baremetal的物理机，然后转换成宿主机，通过宿主机注册用的 access ip是已有的网卡的一个ip，致使 server_ips（baremetal对应的server记录网卡 的ip）与之重复
