### ISSUE TITLE
[BUG]运维工具中的容器实例异常

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#16887]
**问题描述/What happened**:
运维工具->容器实例 部署的应用无法删除，删除显示报错
![image](https://user-images.githubusercontent.com/19506558/234541228-abeb123f-9c9c-4366-ac9c-15e2ea2192d9.png)

实际上我到后台发现实例并不存在 
部分后端日志如下：
![image](https://user-images.githubusercontent.com/19506558/234542476-6314a6a1-3cd8-4ca6-a5f0-9f72b0f7b0e2.png)

**环境/Environment**:
v3.9.8
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
感谢反馈，我先测试下
