### ISSUE TITLE
[求助/Help]迁移虚拟机不可选宿主机：host cpu microcode not match for live migrate

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16902]
![image](https://user-images.githubusercontent.com/10016360/234817683-7e8f0454-c37e-4550-bd99-fb1b9cd15add.png)

请问这是什么意思？能解决吗？

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/10016360/234817683-7e8f0454-c37e-4550-bd99-fb1b9cd15add.png)
> 
> 请问这是什么意思？能解决吗？

这个意思是目标宿主机的 CPU 和源宿主机 CPU 不一样，默认情况下是不允许热迁移的，因为不同宿主机 CPU 进行热迁移有可能失败。
前端界面进行热迁移的操作时，可以选择跳过 CPU 检查，就不会做这个判断了。

更多热迁移相关的解释可以参考文档：https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/migrate/#%E7%83%AD%E8%BF%81%E7%A7%BB

**Comment by shuoshadow** [comment]
好的了解，谢谢
