### ISSUE TITLE
[求助/Help]升级后，使用ISO安装虚拟机，提示”No bootable device“

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#16901]
![image](https://user-images.githubusercontent.com/11387540/234802291-9966d325-5571-4ad9-9d9e-6539441ced5d.png)

**Comment by shuoshadow** [comment]
请问这个bug修复了吗

**Comment by jackgao2015** [comment]
这个问题已经在最新的版本的里面修复了，稍等一下，今天会测试一下，没问题就更新一下相应的文件，可以升级到v3.10.1

**Comment by shuoshadow** [comment]
> 今天已经发布3.10.1的镜像，请升级到3.10.1

已升级，谢谢
