### ISSUE TITLE
[BUG] cloudpods3.9.9 安装在ARM机器银河麒麟V10，添加虚拟机启动报错

### ISSUE THREAD

**Issue by lishiyucn** [yunionio/cloudpods#16914]
**问题描述/What happened**:

**环境/Environment**:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5198932/234910336-4a17255a-e6aa-4cc6-a974-d88f1020508c.png">
银河麒麟V10 sp2 ARM 版本，CPU 鲲鹏920 24核心
新建arm虚拟机报错

{
    "__reason__": "Async start server failed: Start VM Failed ls: cannot access '/opt/cloud/workspace/servers/da525ef4-15ab-4db5-80a2-98bbe321ac67/STATEFILE*': No such file or directory\nqemu-system-aarch64: warning: Number of hotpluggable cpus requested (64) exceeds the recommended cpus supported by KVM (24)\nNumber of hotpluggable cpus requested (64) exceeds the maximum cpus supported by KVM (24)\n exit status 1",
    "__stage__": "OnStartComplete",
    "__status__": "error"
}

<img width="939" alt="image" src="https://user-images.githubusercontent.com/5198932/234910767-1daf8748-0775-491c-bb5d-a67cd2a3bb11.png">

**Comment by wanyaoqi** [comment]
Hi @lishiyucn , 3.9对支持的最大cpu数量没有做探测，是通过宿主机配置来控制的
看起来你的机器只能支持最大24个vcpu，修改 /etc/yunion/host.conf 中 max_hotplug_vcpu_count 为24，重启host服务再试试

**Comment by zhongyong** [comment]
我在8核16机的虚拟机部署v3.10.0后，安装kylin-v10报错如下，
Async start server failed: mu-system-aarch64: maxcpus must be equal to or greater than smp

**Comment by swordqiu** [comment]
此问题已经在3.10.1修复，请升级到3.10.1

> 我在8核16机的虚拟机部署v3.10.0后，安装kylin-v10报错如下， Async start server failed: mu-system-aarch64: maxcpus must be equal to or greater than smp
