### ISSUE TITLE
[求助/Help]使用新建vpc上的子网网段创建虚拟机，能访问经典网络，是正常的吗？

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16942]
新建的vpc:
![image](https://user-images.githubusercontent.com/10016360/236401609-1ca0c392-0069-49b9-9b36-e48110c3a3f7.png)

新建的虚拟机：
![image](https://user-images.githubusercontent.com/10016360/236401718-609055c2-ab13-419f-8b09-db2171b62fb4.png)

访问经典网络是通的，也能访问外网
![image](https://user-images.githubusercontent.com/10016360/236401870-1863494d-85bd-4844-aff2-afe9014cebda.png)

不能被经典网络访问
![image](https://user-images.githubusercontent.com/10016360/236403913-66825795-31a1-44a4-9b4c-cc8937cc420a.png)

这个正常吗？怎么做网络隔离呢？

**Comment by swordqiu** [comment]
vpc内主机默认可以主动访问外部网络，其原理是通过所在宿主机进行NAT对外访问。但是外部无法主动访问VPC内主机，必须通过EIP才能访问VPC内的虚拟机。

**Comment by shuoshadow** [comment]
@swordqiu 不同的vpc不是应该做隔离吗？我新建的vpc能访问default vpc，这个本身就是这么设计的吗？如果我希望做到vpc直接网络隔离，应该怎么做呢

**Comment by jackgao2015** [comment]
还有问题的话，让我打开就行
