### ISSUE TITLE
[BUG] 创建 K8s 集群前端报错

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#16947]
**问题描述/What happened**:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10767027/236443337-7935960e-788a-46b2-9a4e-e70558fef84d.png">

console 报错：TypeError: Cannot read properties of undefined (reading 'instance_capabilities')，导致无法选择集群的机器的磁盘。
 

**环境/Environment**:

test 环境

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): 
+------------------+----------------------------------------------------------------------------------------------------------------------+
|      Field       |                                                        Value                                                         |
+------------------+----------------------------------------------------------------------------------------------------------------------+
| ansible          | release/3.9(3bf577a78f23050414)                                                                                      |
| autoupdate       | release/3.9(ead7d9d823050414)                                                                                        |
| cloudevent       | release/3.9(3bf577a78f23050414)                                                                                      |
| cloudid          | release/3.9(3bf577a78f23050414)                                                                                      |
| cloudmeta        | ci/ucloud-basic-data-support(aedc811)                                                                                |
| cloudnet         | release/3.8(0dbbd1c4f22060414)                                                                                       |
| cloudproxy       | release/3.9(3bf577a78f23050414)                                                                                      |
| compute_v2       | release/3.9(654d47d52623050510)                                                                                      |
| devtool          | release/3.9(3bf577a78f23050414)                                                                                      |
| etcd             | {"etcdserver":"3.4.6","etcdcluster":"3.4.0"}                                                                         |
| external-service | GetServiceVersionURLs: catalog.GetServiceURLs: No valid internalURL endpoints for external-service in region region0 |
| identity         | release/3.9(3bf577a78f23050414)                                                                                      |
| image            | release/3.9(3bf577a78f23050414)                                                                                      |
| influxdb         | 404 page not found                                                                                                   |
| itsm             | release/3.9(96033a0)                                                                                                 |
| k8s              | 404 page not found                                                                                                   |
| log              | release/3.9(3bf577a78f23050414)                                                                                      |
| meter            | release/3.9(ead7d9d823050414)                                                                                        |
| monitor          | release/3.9(3bf577a78f23050414)                                                                                      |
| notify           | release/3.9(3bf577a78f23050414)                                                                                      |
| report           | release/3.9(ead7d9d823050414)                                                                                        |
| s3gateway        | release/3.8(0dbbd1c4f22060414)                                                                                       |
| scheduledtask    | release/3.9(3bf577a78f23050414)                                                                                      |
| scheduler        | release/3.9(3bf577a78f23050414)                                                                                      |
| suggestion       | release/3.9(ead7d9d823050414)                                                                                        |
| torrent-tracker  | <title>Not Found</title>                                                                                             |
| webconsole       | release/3.9(3bf577a78f23050414)                                                                                      |
| websocket        | release/3.9(ead7d9d823050414)                                                                                        |
| yunionagent      | master(6876e27123050414)                                                                                             |
| yunionconf       | release/3.9(3bf577a78f23050414)                                                                                      |
+------------------+----------------------------------------------------------------------------------------------------------------------+

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/4585
https://github.com/yunionio/dashboard/pull/4587
