### ISSUE TITLE
[求助/Help]cloudpods3.10版本，cloudshell连接关闭

### ISSUE THREAD

**Issue by ChangJing89** [yunionio/cloudpods#16955]
登录进入cloudpods,点击右上角的cloudshell,cloudshell闪退，提示connection closed! cloudshell closed

**Comment by hoganlxj** [comment]
我本地测试环境没有问题。你用的什么浏览器及版本？

**Comment by jackgao2015** [comment]
有问题，再打开哈，先关了。
