### ISSUE TITLE
[求助/Help]纳管物理机报错“Network not found”

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#16960]
<img width="797" alt="1f55b0f4fd8755eca992d808cc039d5" src="https://user-images.githubusercontent.com/29140975/236606332-143ae184-cbc1-479a-8044-d9613e3f3823.png">
纳管物理机，物理机跟cloudpods所在的机器不在同一个网络，但网络之间是互通的。 物理机也配置了ipmi

**Comment by hoganlxj** [comment]
需要在cloudpods中有新建  包含物理机ipmi地址 的IP子网（IP子网类型为ipmi）

**Comment by jackgao2015** [comment]
有问题，再打开哈，这个先关了。
