### ISSUE TITLE
[BUG]纳管天翼云失败

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#16961]
v3.10.0 在纳管天翼云时，因为accesskey无授权创建帐户失败，但前端并没有任何提示。因为天翼云的accesskey虽然是正确的。但还需要天翼云授权才能使用。

**Comment by hoganlxj** [comment]
天翼云版本是多少？

**Comment by jackgao2015** [comment]
@hewenxiang  你的描述是不是可以详细一点？截图、报错信息等等
你有必要看一下这个 https://github.com/yunionio/cloudpods/issues/16475

**Comment by jackgao2015** [comment]
天翼云是前几年对接的，有些日子没更新过了，可能会有问题，不过你遇到问题就提，我们持续支持
