### ISSUE TITLE
[求助/Help]根据文档/添加一个API的过程，一步步下来，使用 climc 编译后， 获取不到新添加的 API 接口函数

### ISSUE THREAD

**Issue by WongLun** [yunionio/cloudpods#16987]
按照https://www.cloudpods.org/zh/docs/development/add-api/ 文档内容：

- 首先，在pkg/compute/models/dns_zones.go 文件我添加了一个新的接口函数 GetDetailsExp (与文档给的GetDetailsExports方法有区别的)，编译无报错；

- 其次，在cmd/climc/shell/compute/dnszone.go 文件，添加了
 cmd.GetWithCustomShow("exp", func(result jsonutils.JSONObject) {
               ...
        }, &options.SDnsZoneIdOptions{})

- 然后按照步骤编译 climc 和 region、执行climc、测试命令 climc> dns-zone-exp <zone id>

就报错了：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa40bc3]

goroutine 1 [running]:
yunion.io/x/structarg.(*ArgumentParser).IsHelpSet(...)
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/vendor/yunion.io/x/structarg/structarg.go:1315
yunion.io/x/onecloud/cmd/climc/promputils.Executor({0xc00173f240?, 0x0?})
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/cmd/climc/promputils/executor.go:78 +0x1a3
github.com/c-bata/go-prompt.(*Prompt).Run(0xc00073f830)
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/vendor/github.com/c-bata/go-prompt/prompt.go:84 +0x745
yunion.io/x/onecloud/cmd/climc/entry.enterInteractiveMode(0xc0002dcb00, 0xc00003c240?)
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/cmd/climc/entry/climc.go:254 +0x1bd
yunion.io/x/onecloud/cmd/climc/entry.ClimcMain()
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/cmd/climc/entry/climc.go:354 +0x15f
main.main()
        /data/jenkins/workspace/iso/work/go/src/yunion.io/x/onecloud/cmd/climc/main.go:44 +0x17
        

       看起来好像是空指针的问题，但是，除了新增 api 函数外，我没有任何其他的改动；
       此外，我又将 添加文档中的示例 GetDetailsExports方法，改为 GetDetailsExport，相应的GetWithCustomShow 和 测试命令 climc> dns-zone-export <zone id>都修改(少一个s)，修改原接口编译后 climc 仍然得不到正确的结果。
       
       有劳作者抽空解答，是我按照文档操作步骤有问题，还是新增 api  还需要修改其他函数？？？😢😢😢

**Comment by WongLun** [comment]
使用的cloudpods版本为 3.10，系统环境为Centos 7.9

**Comment by zexi** [comment]
@WongLun 感觉是没有使用到你编译的 climc 二进制导致的，你编译的 climc 应该在项目的 **_output/bin/climc** 这个路径。

试试执行：

```bash
# cd 到执行 make cmd/climc 的目录
$ ./_output/bin/climc dns-zone-exp
```

**Comment by WongLun** [comment]
@zexi  感谢作者百忙之中的回复！！！😁
使用 $ ./_output/bin/climc dns-zone-exp  后，确实无指针报错啦！

但目前还有个新问题，以 cloudaccount.go中的 GetDetailsBalance 获取余额为例:

1. 
![image](https://github.com/yunionio/cloudpods/assets/41935773/11e6b475-ccd9-46b3-a8d6-9f175aa92cfe)
我增加了一个新的接口 test

2.  
![image](https://github.com/yunionio/cloudpods/assets/41935773/73a1209a-c2a4-4364-9c2f-3d7945740830)
在pkg/compute/models/cloudaccounts.go 中增加了 GetDetailsTest 接口（这个新接口与 GetDetailsBalance 除了函数名修改为Test，内部代码完全一致）

3.编译之后 原有的 GetDetailsBalance 接口能获取到余额，但是新增的 GetDetailsTest 接口获取不到余额，报 SpecNotFoundError 
 404 的错
![image](https://github.com/yunionio/cloudpods/assets/41935773/4e0c546d-7d09-44b0-a865-5f306609c045)


不知道为啥找不到资源😢😢😢，我这里新增 api 就改了个 test 的名字，还有其他地方需要修改吗？
期待作者的指导！！！！！！！！

**Comment by Xuyongheng1** [comment]
我同样按照官网文档， 尝试添加 一个 api ，也是报这个错误 😂

**Comment by ioito** [comment]
> @zexi 感谢作者百忙之中的回复！！！😁 使用 $ ./_output/bin/climc dns-zone-exp 后，确实无指针报错啦！
> 
> 但目前还有个新问题，以 cloudaccount.go中的 GetDetailsBalance 获取余额为例:
> 
> 
> ![image](https://user-images.githubusercontent.com/41935773/237264840-11e6b475-ccd9-46b3-a8d6-9f175aa92cfe.png) 我增加了一个新的接口 test
> 
> 
> ![image](https://user-images.githubusercontent.com/41935773/237265132-73a1209a-c2a4-4364-9c2f-3d7945740830.png) 在pkg/compute/models/cloudaccounts.go 中增加了 GetDetailsTest 接口（这个新接口与 GetDetailsBalance 除了函数名修改为Test，内部代码完全一致）
> 
> 3.编译之后 原有的 GetDetailsBalance 接口能获取到余额，但是新增的 GetDetailsTest 接口获取不到余额，报 SpecNotFoundError 404 的错 ![image](https://user-images.githubusercontent.com/41935773/237266380-4e0c546d-7d09-44b0-a865-5f306609c045.png)
> 
> 不知道为啥找不到资源😢😢😢，我这里新增 api 就改了个 test 的名字，还有其他地方需要修改吗？ 期待作者的指导！！！！！！！！

看起来是你没替换region镜像，就是你请求的还是原始的region服务

**Comment by ioito** [comment]
https://github.com/yunionio/docs/pull/1442/files
