### ISSUE TITLE
[BUG] 自定义数据 以文本形式 和 文件形式都不太行

### ISSUE THREAD

**Issue by lxd5866** [yunionio/cloudpods#17003]
**问题描述/What happened**:

**环境/Environment**:

version： 3.10

[
  {
    "action":"append",
    "path":"/etc/ssh/sshd_config",
    "content":"\nPasswordAuthentication yes\nPermitRootLogin yes\n",
  }
]

上传文件：
<img width="1789" alt="image" src="https://github.com/yunionio/cloudpods/assets/10388914/9ef794de-e0fa-4e94-bc1c-bfed851ba01d">

文本形式：
<img width="1091" alt="image" src="https://github.com/yunionio/cloudpods/assets/10388914/a9e032ae-befd-4e6c-8c47-3aa0ba746815">

**Comment by wanyaoqi** [comment]
@lxd5866  看起来是你的 json格式有问题，提交前可以尝试用json formatter 工具检查一下，下面是 formatter之后的，测试没问题
```
[{
	"action": "append",
	"path": "/etc/ssh/sshd_config",
	"content": "\nPasswordAuthentication yes\nPermitRootLogin yes\n"
}]
```
