### ISSUE TITLE
[BUG]编译碰到的问题，编译host-image和webconsole无法编译成功

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#17000]
**问题描述/What happened**:
1,编译host-image报错：
go build -mod vendor -ldflags "-w -X yunion.io/x/pkg/util/version.gitVersion=4a1f5e6a6fefcc -X yunion.io/x/pkg/util/version.gitCommit=4a1f5e6 -X yunion.io/x/pkg/util/version.gitBranch=main -X yunion.io/x/pkg/util/version.buildDate=2023-05-10T09:06:47Z -X yunion.io/x/pkg/util/version.gitTreeState=dirty -X yunion.io/x/pkg/util/version.gitMajor=0 -X yunion.io/x/pkg/util/version.gitMinor=0" -o /root/goproject/src/yunion.io/x/cloudpods/_output/bin/host-image yunion.io/x/onecloud/cmd/host-image
# yunion.io/x/onecloud/pkg/hostimage
pkg/hostimage/image.go:20:23: fatal error: libqemuio.h: No such file or directory
 #include "libqemuio.h"
                       ^
compilation terminated.

2，编译webconsole报错：
# yunion.io/x/onecloud/pkg/webconsole/command
pkg/webconsole/command/ssh_command.go:112:38: o.Options.SshToolPath undefined (type "yunion.io/x/onecloud/pkg/webconsole/options".WebConsoleOptions has no field or method SshToolPath)
pkg/webconsole/command/ssh_command.go:188:14: o.Options.SshpassToolPath undefined (type "yunion.io/x/onecloud/pkg/webconsole/options".WebConsoleOptions has no field or method SshpassToolPath)
pkg/webconsole/command/ssh_command.go:189:14: o.Options.SshToolPath undefined (type "yunion.io/x/onecloud/pkg/webconsole/options".WebConsoleOptions has no field or method SshToolPath)

![image](https://github.com/yunionio/cloudpods/assets/58723494/351aa017-e4a9-4d87-a02a-94b2fa8a028e)

**环境/Environment**:
centos7.9
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
最新的代码已经移除了ssh二进制调用，改用ssh库，你得拉取最新的master代码
host-image依赖qemu-dev开发包，yum安装之后再编译

**Comment by szz1113-1119** [comment]
sudo yum install qemu-kvm-devel是这个吗？执行了没有安装成功，编译host-image还是报相同的问题

**Comment by szz1113-1119** [comment]
能否给个对应的rpm安装包，
![image](https://github.com/yunionio/cloudpods/assets/58723494/e30a6a67-700f-4d92-9127-16db3a953e2f)

**Comment by ioito** [comment]
https://github.com/yunionio/qemu/ 用这个编译下qemu的包，将c的头文件放置到对应目录

**Comment by szz1113-1119** [comment]
wget https://raw.githubusercontent.com/yunionio/qemu/stable-4.2/0001-patch-for-4.2.patch这个无法下载，能帮忙看一下吗

**Comment by ioito** [comment]
你网有问题，不行就浏览器直接打开下载地址，复制粘贴下

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/635fe6b3-da38-45aa-b3fe-78c99fb90658)
![image](https://github.com/yunionio/cloudpods/assets/58723494/241f960c-eff5-41ff-8932-0dd6c03798af)
能否直接帮我生成一个头文件，我放一下。

**Comment by ioito** [comment]
打上patch, 源文件目录里面就有，find查找下

**Comment by szz1113-1119** [comment]
您好，libqemuio.h这个文件已经找到，我应该放到那个位置，您说放到对应的目录，没理解是指那块？

**Comment by szz1113-1119** [comment]
你好，libqemuio.h文件已经找到， 我放到了
![image](https://github.com/yunionio/cloudpods/assets/58723494/14bf77b8-5fab-4195-8d8d-f4bacb938382)
然后再执行make cmd/host-image，又包这个错误，这个头文件再那获取？
![image](https://github.com/yunionio/cloudpods/assets/58723494/c7b40986-f790-4ca2-ae60-bf9fcb62a25a)

**Comment by ioito** [comment]
网上找下c语言头文件基础知识看下
