### ISSUE TITLE
[BUG]物理机转为宿主机，存储识别成机械盘，实际是SSD

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17018]
**问题描述/What happened**:
![image](https://github.com/yunionio/cloudpods/assets/10016360/db395112-af44-45b3-aa2c-d262a3a3dc77)
![image](https://github.com/yunionio/cloudpods/assets/10016360/ac5dfae4-48e4-410f-a0f9-430e461385fb)

连续3个物理机都是这样
**环境/Environment**:
3.10.1

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@shuoshadow 这个存储的类型如果不准确，可以手动修改下，目前这个探测不是特别准确，因为有些 MegaRaid 基于 SSD 做的 PD 后，在操作系统里面标记的就是机械盘

**Comment by shuoshadow** [comment]
好的，那就手动改下好了。谢谢！
