### ISSUE TITLE
[求助/Help] 导入外部数据报错Unsupported provider RemoteFile

### ISSUE THREAD

**Issue by DearAS** [yunionio/cloudpods#17020]
![image](https://github.com/yunionio/cloudpods/assets/22094320/970ac52d-5a87-4cc7-aabd-a76953c291f9)

使用的v3.9版本 手动部署的开发集群。

前端新建云账号，选择外部数据，点击提交后提示该异常，不支持的类型。

**Comment by ioito** [comment]
外部数据导入3.10才支持
