### ISSUE TITLE
[文档/Docs] 从源代码部署的文档

### ISSUE THREAD

**Issue by DearAS** [yunionio/cloudpods#17021]
**What part of the document needs to be added**:
https://github.com/yunionio/cloudpods/issues/6901 这个issue中贴出了文档地址：https://docs.yunion.io/docs/contribute/contrib/

但是现在好像打不开了，请问这个最新的地址是多少

**Comment by ioito** [comment]
https://www.cloudpods.org/zh/docs/development/single_service_dev/
