### ISSUE TITLE
[求助/Help] 请问外部数据导入，如何导入虚拟机、主机等数据

### ISSUE THREAD

**Issue by DearAS** [yunionio/cloudpods#17036]
版本： 3.10
问题描述： 按照文档中示例的外部数据样例进行导入，发现region、zone等数据都成功导入进去了，但是就是没有主机相关的数据，请问虚拟机、主机这些数据如何导入。

![image](https://github.com/yunionio/cloudpods/assets/22094320/258b5bcc-97ad-4773-9bb8-e861f568f638)

**Comment by ioito** [comment]
https://www.cloudpods.org/zh/docs/development/remotefile/ host数据里面的zone_id是否可以和zone里面的id对应上，可以看下region的日志
