### ISSUE TITLE
[求助/Help]平台纳管京东云

### ISSUE THREAD

**Issue by czKim** [yunionio/cloudpods#17059]
version： v3.10.0
description： 在云账号新增了京东云账号，虚拟机资源没有同步进来。

**Comment by hoganlxj** [comment]
https://www.cloudpods.org/zh/docs/function_principle/multicloud/cloudaccounts/sync/ 参考这个排查下

**Comment by czKim** [comment]
![image](https://github.com/yunionio/cloudpods/assets/18141071/4a9c36b9-cdea-4edc-8625-753241365b40)
![image](https://github.com/yunionio/cloudpods/assets/18141071/f6c80e92-25e1-4d50-9295-7e62b071733e)
![image](https://github.com/yunionio/cloudpods/assets/18141071/9ed8afe8-c6e1-4202-a631-3b8fb96440b0)
![image](https://github.com/yunionio/cloudpods/assets/18141071/4f5eacd2-b64d-4c43-a35f-8eab4cea1eab)
![image](https://github.com/yunionio/cloudpods/assets/18141071/1a88e63f-db89-41e4-8fa5-e82dbcba1e7b)

这个问题排查的我都看了，都没啥问题啊

**Comment by hoganlxj** [comment]
> ![image](https://user-images.githubusercontent.com/18141071/238826730-4a9c36b9-cdea-4edc-8625-753241365b40.png) ![image](https://user-images.githubusercontent.com/18141071/238826813-f6c80e92-25e1-4d50-9295-7e62b071733e.png) ![image](https://user-images.githubusercontent.com/18141071/238826900-9ed8afe8-c6e1-4202-a631-3b8fb96440b0.png) ![image](https://user-images.githubusercontent.com/18141071/238827112-4f5eacd2-b64d-4c43-a35f-8eab4cea1eab.png) ![image](https://user-images.githubusercontent.com/18141071/238827297-1a88e63f-db89-41e4-8fa5-e82dbcba1e7b.png)
> 
> 这个问题排查的我都看了，都没啥问题啊

看下 region 对用pods中 日志 有报错信息没？

**Comment by czKim** [comment]
> 对用pods中

![image](https://github.com/yunionio/cloudpods/assets/18141071/c8d7fdd0-781a-4c0d-bb6b-9e7ae82cdc15)

**Comment by ioito** [comment]
麻烦问下是京东云云哪个区的资源没同步

**Comment by czKim** [comment]
> 麻烦问下是京东云云哪个区的资源没同步

云主机在华北-北京，可用区是天津武清1，我在log里搜关键字天津武清，没搜到，感觉好像是没有同步下来

**Comment by ioito** [comment]
安装好go开发环境执行以下操作
git clone https://github.com/yunionio/cloudmux.git
cd cloudmux && make cmd/jdcloudcli
./_output/bin/jdcloudcli --debug --access-key JDC_xxxxx --access-secret EDxxxxxx --region-id cn-north-1 instance-list

**Comment by zexi** [comment]
> 安装好go开发环境执行以下操作 git clone https://github.com/yunionio/cloudmux.git cd cloudmux && make cmd/jdcloudcli ./_output/bin/jdcloudcli --debug --access-key JDC_xxxxx --access-secret EDxxxxxx --region-id cn-north-1 instance-list

@czKim 麻烦执行这个命令试试看能否列出对应的虚拟机。
