### ISSUE TITLE
[求助/Help] All in one 在布署时缺少 https://iso.yunion.cn/kylin/v10-lance/3.9/aarch64/kylin-yunion.repo

### ISSUE THREAD

**Issue by zenithgp** [yunionio/cloudpods#17061]
All in one 在布署时报错（服务器系统是麒麟V10 sp3）
TASK [common : Add cloud rpm repository for Kylin] *****************************
fatal: [192.168.20.160]: FAILED! => {"changed": false, "dest": "/etc/yum.repos.d/kylin-yunion.repo", "elapsed": 0, "gid": 0, "group": "root", "mode": "0666", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 192, "state": "file", "status_code": 404, "uid": 0, "url": "https://iso.yunion.cn/kylin/v10-lance/3.9/aarch64/kylin-yunion.repo"}

**Comment by zhasm** [comment]
您好，目前正式支持 V10 sp2，不支持V10 sp3。
