### ISSUE TITLE
纳管一下火山云和百度云

### ISSUE THREAD

**Issue by zyqcn** [yunionio/cloudpods#17063]
什么时候兼容一下火山云和百度云

**Comment by ioito** [comment]
火山云会在这次的开源之夏完成 https://summer-ospp.ac.cn/org/projectlist?lang=zh&orgName=Cloudpods&pageNum=1&pageSize=50&programName
用百度云的也可以先自行进行二次开发
https://www.cloudpods.org/zh/docs/development/resource_sync/add-cloud/

**Comment by dengju2020** [comment]
火山云和百度云在3.11版本已经支持，预计年底发版
