### ISSUE TITLE
[求助/Help]按照 all in one 手册安装完后，新建虚拟机失败，报“Deploy guest fs : request deploy guest fs : context deadline exceeded”

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17071]
![image](https://github.com/yunionio/cloudpods/assets/11387540/31b022dd-ff9c-41d7-b32d-30f4c3ba44b4)

**Comment by jackgao2015** [comment]
向杰提示：“部署cloudpods的内核是带yn的吗”

**Comment by zexi** [comment]
这个时 host-deployer 服务启动失败导致的，可以执行 `kubectl get pods -n onecloud | grep host-deployer` 看下 pod 状态。
一般这个服务启动失败是因为内核没有 nbd 模块导致的，执行 `uname -a` 看下内核是不是 yn 的内核，centos 版本需要安装我们的内核才行。
