### ISSUE TITLE
[BUG] AWS负载均衡创建后端服务组提示失败，实际上AWS那边已经成功添加

### ISSUE THREAD

**Issue by zhouhs0019** [yunionio/cloudpods#17095]
**问题描述/What happened**:
1、AWS负载均衡创建监听端口会提示失败，实际已添加，https无法获取aws的证书
2、AWS负载均衡创建后端服务组提示失败，实际上AWS那边已经成功添加
3、AWS后端服务器组没有正确显示关联监听数量，都是0
4、AWS后端服务器组的后端服务器显示都为空

**Comment by zexi** [comment]
@ioito 帮忙看下这个问题

**Comment by ioito** [comment]
@zhouhs0019 你使用的是哪个版本，负载均衡在3.10进行了重构，3.9及之前的版本是存在比较多的问题
