### ISSUE TITLE
[求助/Help] 上传镜像问题，一直卡在99%不动。

### ISSUE THREAD

**Issue by DearAS** [yunionio/cloudpods#17099]
![image](https://github.com/yunionio/cloudpods/assets/22094320/b561a943-9d9e-4acf-ad80-d935143c2128)

部署方式： 手动部署开发集群
版本：v3.9

glance服务也没有报错信息。启动的服务有：apigateway、keystone、glance、region、yunionconf、monitor
请问大概是哪里的问题呢？

有试过用all in one方式部署的就可以上传成功。

**Comment by ioito** [comment]
这个主要需要看nginx和glance日志，你也可以加下日志代码调试下

**Comment by zexi** [comment]
> 这个主要需要看nginx和glance日志，你也可以加下日志代码调试下

@DearAS 用的什么浏览器吗？换个 chrome 浏览器试试？
