### ISSUE TITLE
系统里使用的表格可以单独开源出来吗

### ISSUE THREAD

**Issue by noday** [yunionio/cloudpods#17107]
这个表格挺好，除了列筛选其他功能都有，

**Comment by jackgao2015** [comment]
能否详细描述一下或者贴个图？

**Comment by jackgao2015** [comment]
你是指列表的前端代码？

**Comment by zexi** [comment]
> 这个表格挺好，除了列筛选其他功能都有，

@noday 是说的前端代码的资源列表那里吗？

**Comment by easy-mj** [comment]
@noday 我们使用的是开源的table组件 https://github.com/x-extends/vxe-table
