### ISSUE TITLE
[BUG]经典网络监控angent无法安装

### ISSUE THREAD

**Issue by we14578** [yunionio/cloudpods#17118]
**问题描述/What happened**:
经典网络虚拟机无法安装angent监控，显示
”please create usable Proxy Endpoint for server and try again: no suitable network to reach influxdb“
页面显示安装失败暂无可用的PE
![image](https://github.com/yunionio/cloudpods/assets/19506558/74b0e819-3d1a-4c0f-b352-0bc93f56e51c)

**环境/Environment**:
v3.10.1

**Comment by hoganlxj** [comment]
无法访问influxdb 导致

**Comment by shuoshadow** [comment]
同样的问题，我是因为这个bug无法访问influxdb https://github.com/yunionio/cloudpods/issues/16433

**Comment by dengju2020** [comment]
最新版本支持，可以升级试试
