### ISSUE TITLE
[求助/Help]网络接口是否插线识别错误

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17134]
![image](https://github.com/yunionio/cloudpods/assets/10016360/659005b0-451c-49b8-945c-0428fa8d3db2)

idrac中显示正常，网口灯也是正常的
![image](https://github.com/yunionio/cloudpods/assets/10016360/0ccc0b74-68d6-4996-9217-93ef0506e877)

![image](https://github.com/yunionio/cloudpods/assets/10016360/89e7842e-5351-4c49-94d8-50a7727e1d54)

![image](https://github.com/yunionio/cloudpods/assets/10016360/64076467-4b9c-43ab-b044-837fe09c025b)

**Comment by zexi** [comment]
@shuoshadow 网卡的探测是通过 pxe 系统里面的 /lib/mos/lsnic 脚本来做的，可以使用 `climc host-ssh $baremetal_id_or_name` ssh 进入系统里面，手动执行 /lib/mos/lsnic 看下输出的结果。
