### ISSUE TITLE
vnc和spice设备的密码和端口自定义

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17131]
怎么把自定义虚拟机vnc或spice协议的端口和密码！

**Comment by jackgao2015** [comment]
@swordqiu  今天中午你和lxj提到一个方案来应对 @zhongyong  的场景，方便的时候，把这个方案补充到这里哈，供 @zhongyong  参考

**Comment by swordqiu** [comment]
vnc/spice端口和密码每次虚拟机启动都会随机生成的，可以通过调用API获取到这些信息：

GET /servers/<sid>/vnc

Golang SDK: modules.Guests.GetSpecific(s, sid, "vnc", nil)

**Comment by zhongyong** [comment]
我的意思是否可以自己去固定设置一下，因为每次重启都要变，虽然可以后面通过sdk获取
