### ISSUE TITLE
[求助/Help] climc  joint-filter查询返回ResourceNotFoundError

### ISSUE THREAD

**Issue by baiweiyll** [yunionio/cloudpods#17132]
问题描述：使用climc通过 joint-filter查询虚拟机列表提示资源不存在
执行命令如下：
climc --debug server-list --meta --joint-filter "metadata.obj_id(id).value.in('blx','liuqiang')"
结果报错，返回
{"class":"ResourceNotFoundError","code":404,"details":"ListItems: listItemQueryFiltersRaw: {\"error\":{\"class\":\"ResourceNotFoundError\",\"code\":404,\"data\":{\"fields\":[\"metadat\"],\"id\":\"invalid joint resources %!s(MISSING)\"},\"details\":\"invalid joint resources metadat\"}}"}
执行climc --debug server-list --meta --joint-filter "metadataa.obj_id(id).value.in('blx','liuqiang')"命令，返回正确结果。
joint-filter是否不支持关联元数据查询？
如果直接使用climc metadata-list命令，感觉又没有climc  server-list filter的特性，比如我想查server的name包含某个字符，同时又存在某个元数据这样的数据应该使用什么命令？
谢谢!
climc版本信息如下所示：
 {
  "major": "0",
  "minor": "0",
  "gitVersion": "v3.9.0-29-gd0fb9f10dd3174",
  "gitBranch": "release/3.9",
  "gitCommit": "d0fb9f10dd",
  "gitTreeState": "clean",
  "buildDate": "2022-06-15T02:56:37Z",
  "goVersion": "go1.13.15",
  "compiler": "gc",
  "platform": "linux/arm64"
}

**Comment by ioito** [comment]
climc  server-list --user-tags blx=liuqiang --filter "name.contains('xxx')"

**Comment by ioito** [comment]
> 问题描述：使用climc通过 joint-filter查询虚拟机列表提示资源不存在 执行命令如下： climc --debug server-list --meta --joint-filter "metadata.obj_id(id).value.in('blx','liuqiang')" 结果报错，返回 {"class":"ResourceNotFoundError","code":404,"details":"ListItems: listItemQueryFiltersRaw: {"error":{"class":"ResourceNotFoundError","code":404,"data":{"fields":["metadat"],"id":"invalid joint resources %!s(MISSING)"},"details":"invalid joint resources metadat"}}"} 执行climc --debug server-list --meta --joint-filter "metadataa.obj_id(id).value.in('blx','liuqiang')"命令，返回正确结果。 joint-filter是否不支持关联元数据查询？ 如果直接使用climc metadata-list命令，感觉又没有climc server-list filter的特性，比如我想查server的name包含某个字符，同时又存在某个元数据这样的数据应该使用什么命令？ 谢谢! climc版本信息如下所示： { "major": "0", "minor": "0", "gitVersion": "v3.9.0-29-gd0fb9f10dd3174", "gitBranch": "release/3.9", "gitCommit": "d0fb9f10dd", "gitTreeState": "clean", "buildDate": "2022-06-15T02:56:37Z", "goVersion": "go1.13.15", "compiler": "gc", "platform": "linux/arm64" }

https://github.com/yunionio/pkg/pull/102/files 这个是导致metadataa的原因，其实后面的a换成任何字符都会这样

**Comment by baiweiyll** [comment]
> climc server-list --user-tags blx=liuqiang --filter "name.contains('xxx')"

好的，谢谢！
我使用的tags，tags是只支持完全相等过滤对吧，没法使用filter里面的contains或者like之类的语法吧？

**Comment by ioito** [comment]
> > climc server-list --user-tags blx=liuqiang --filter "name.contains('xxx')"
> 
> 好的，谢谢！ 我使用的tags，tags是只支持完全相等过滤对吧，没法使用filter里面的contains或者like之类的语法吧？

是的
