### ISSUE TITLE
[求助/Help]安装windows10虚拟机时挂载系统iso镜像后，无法挂载虚拟机驱动virtio的iso驱动，请问一下应该怎么解决。

### ISSUE THREAD

**Issue by wansen-wang** [yunionio/cloudpods#17149]
我的环境是allinone安装的，虚拟机是安装在宿主机上面的
![image](https://github.com/yunionio/cloudpods/assets/100327344/b579c5d2-c1d5-4519-9c27-66f5c9dc63b3)
在调整配置的界面也是没有办法添加第二个iso镜像。
![image](https://github.com/yunionio/cloudpods/assets/100327344/f40a2f1d-8e93-4df2-bafb-489b246004d2)
最终导致的结果就是安装系统时系统识别不到虚拟硬盘
![image](https://github.com/yunionio/cloudpods/assets/100327344/ee6021e3-9e31-40de-80df-585e8b825db4)
请问应该怎么解决！！

**Comment by swordqiu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/1121362/c991d488-c382-4893-afa5-4c9dd7809a3d)

我注意到您的windows.iso没有设置操作系统类型，请设置为Windows操作系统，然后再用改iso重新创建主机。

平台做了特殊处理，如果是从iso创建虚拟机，并且操作系统是windows，会把磁盘类型设置为ide，这样就能被windows安装程序识别出来了。安装完windows后，再卸载安装iso，加载virtio的驱动iso，把virtio的驱动安装上，这样就能识别virtio的磁盘了。

请参考 https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/create/#windows%E9%95%9C%E5%83%8F%E4%BC%98%E5%8C%96
制作镜像，尤其注意制作镜像前要从虚拟机内干净关机，windows 10需要去掉关机休眠的选项，否则创建的主机无法重置密码。
