### ISSUE TITLE
[求助/Help]添加物理机进行PXE引导时，卡在Loading Linux和Loading initrd

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17155]
![image](https://github.com/yunionio/cloudpods/assets/10016360/5a42627c-6a6c-46c8-ba67-1148349dd0ef)

![image](https://github.com/yunionio/cloudpods/assets/10016360/e5d60fa7-efc5-44c6-ba16-6232a145a949)

![image](https://github.com/yunionio/cloudpods/assets/10016360/e2ec0d7d-69e0-4018-af05-7e81a9e1ab96)

版本3.10.1

**Comment by shuoshadow** [comment]
@zexi 
```
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-01-f4-02-70-b8-bf-40" error: stat /opt/cloud/yunion/baremetal/grub.cfg-01-f4-02-70-b8-bf-40: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81EEC" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81EEC: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81EE" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81EE: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81E" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81E: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A8" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A8: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C: no such file or directory
[error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg" error: stat /opt/cloud/yunion/baremetal/grub.cfg: no such file or directory
```
但是引导的时候有这个日志，所以应该是请求了文件下载的。这个报错的原因是什么？

**Comment by zexi** [comment]
> @zexi
> 
> ```
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-01-f4-02-70-b8-bf-40" error: stat /opt/cloud/yunion/baremetal/grub.cfg-01-f4-02-70-b8-bf-40: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81EEC" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81EEC: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81EE" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81EE: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81E" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81E: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A8" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A8: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C: no such file or directory
> [error 2023-06-07 03:25:14 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg" error: stat /opt/cloud/yunion/baremetal/grub.cfg: no such file or directory
> ```
> 
> 但是引导的时候有这个日志，所以应该是请求了文件下载的。这个报错的原因是什么？

@shuoshadow 这个报错应该没问题，是 grub 引导下载 grub.cfg 尝试的路径，只要能引导进入 grub 界面，这个 error 可以忽略
