### ISSUE TITLE
SDK调用报权限不够

### ISSUE THREAD

**Issue by chenshushan** [yunionio/cloudpods#17178]
使用java SDK调用时出现如下错误   调用的账号为超级管理员admin  请问为什么会出现如下错误呢
![image](https://github.com/yunionio/cloudpods/assets/20243864/fee5298e-07c5-4c8e-9abd-658377500d93)

![企业微信截图_16853407942800](https://github.com/yunionio/cloudpods/assets/20243864/6ae715bf-ff3f-4569-9794-14d5bfc2da3f)

**Comment by swordqiu** [comment]
是不是这个用户认证没有明确设置项目或者项目ID？导致用户的token没有权限调用API

**Comment by chenshushan** [comment]
资源确实是在另一个项目下  可是我使用的是admin账号   我理解的是admin应该能获取所有域的所有项目下的资源吧
![image](https://github.com/yunionio/cloudpods/assets/20243864/eda040ad-9f3d-4607-99ad-58480da38aa5)

**Comment by swordqiu** [comment]
账号感觉是对的，有可能是服务有问题，重启一下scheduler服务试下？

**Comment by chenshushan** [comment]
后面排查下来可能是token没有刷新   我这样在外部使用session有问题吗  为什么会出现token不刷新的问题
![image](https://github.com/yunionio/cloudpods/assets/20243864/c06fd393-07ec-4d04-b022-acc01a8df4bd)

**Comment by swordqiu** [comment]
token默认是24小时过期，没有续期的办法，需要定期重新调用Authenticate接口获取新的token。

**Comment by chenshushan** [comment]
好的  我再做下token的管理
顺便问个问题  cloudpods提供了高可用的部署  但是我看到有本地缓存和本地锁  这些在多节点下会不会有问题

**Comment by swordqiu** [comment]
服务目前还是单副本的，所以不会有问题。高可用只是k8s集群的高可用，即如果3个节点的1个挂了，会在别的节点把单副本的服务快速恢复。如果把服务开启多副本，需要把锁换成etcd的锁。目前测试比较少。

**Comment by chenshushan** [comment]
本地缓存的数据大致有哪些呢  如果做成多副本怎么处理比较好呢

**Comment by swordqiu** [comment]
这个没有通用的规律，得看每个服务具体的实现。多副本的场景还有待测试。

**Comment by chenshushan** [comment]
好的 感谢解答
