### ISSUE TITLE
When I install Cloudpods, this error is reported, how can I replace the available image source?

### ISSUE THREAD

**Issue by weixingsheng666** [yunionio/cloudpods#17179]
fatal: [10.x.x.40]: FAILED! => {"changed": true, "cmd": "yum clean all\nyum -y --disablerepo='*' --enablerepo='yunion*' makecache\n", "delta": "0:00:01.154596", "end": "2023-05-29 14:10:23.338104", "msg": "non-zero return code", "rc": 1, "start": "2023-05-29 14:10:22.183508", "stderr": "https://iso.yunion.cn/%24contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error\nTrying other mirror.\n\n\n One of the configured repositories failed (Packages for Yunion Multi-Cloud Platform -),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=yunion-repo- ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable yunion-repo-\n        or\n            subscription-manager repos --disable=yunion-repo-\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=yunion-repo-.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from yunion-repo-: [Errno 256] No more mirrors to try.\nhttps://iso.yunion.cn/$contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error", "stderr_lines": ["https://iso.yunion.cn/%24contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error", "Trying other mirror.", "", "", " One of the configured repositories failed (Packages for Yunion Multi-Cloud Platform -),", " and yum doesn't have enough cached data to continue. At this point the only", " safe thing yum can do is fail. There are a few ways to work \"fix\" this:", "", "     1. Contact the upstream for the repository and get them to fix the problem.", "", "     2. Reconfigure the baseurl/etc. for the repository, to point to a working", "        upstream. This is most often useful if you are using a newer", "        distribution release than is supported by the repository (and the", "        packages for the previous distribution release still work).", "", "     3. Run the command with the repository temporarily disabled", "            yum --disablerepo=yunion-repo- ...", "", "     4. Disable the repository permanently, so yum won't use it by default. Yum", "        will then just ignore the repository until you permanently enable it", "        again or use --enablerepo for temporary usage:", "", "            yum-config-manager --disable yunion-repo-", "        or", "            subscription-manager repos --disable=yunion-repo-", "", "     5. Configure the failing repository to be skipped, if it is unavailable.", "        Note that yum will try to contact the repo. when it runs most commands,", "        so will have to try and fail each time (and thus. yum will be be much", "        slower). If it is a very temporary problem though, this is often a nice", "        compromise:", "", "            yum-config-manager --save --setopt=yunion-repo-.skip_if_unavailable=true", "", "failure: repodata/repomd.xml from yunion-repo-: [Errno 256] No more mirrors to try.", "https://iso.yunion.cn/$contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error"], "stdout": "Loaded plugins: fastestmirror\nCleaning repos: base centos-sclo-rh centos-sclo-sclo docker-ce-stable elrepo\n              : epel extras updates yunion-repo-\nCleaning up everything\nMaybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos\nLoaded plugins: fastestmirror", "stdout_lines": ["Loaded plugins: fastestmirror", "Cleaning repos: base centos-sclo-rh centos-sclo-sclo docker-ce-stable elrepo", "              : epel extras updates yunion-repo-", "Cleaning up everything", "Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos", "Loaded plugins: fastestmirror"]}

**Comment by zhasm** [comment]
@weixingsheng666 您好，看到您的centos 版本应该是7.3 的对吧？请升级到7.9，然后重新安装试试？

**Comment by zhasm** [comment]
@weixingsheng666 请反馈一下环境信息，谢谢：

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)

**Comment by weixingsheng666** [comment]
> @weixingsheng666 您好，看到您的centos 版本应该是7.3 的对吧？请升级到7.9，然后重新安装试试？
对，是 7.4的

**Comment by weixingsheng666** [comment]
> @weixingsheng666 请反馈一下环境信息，谢谢：
> 
> **环境/Environment**:
> 
> * OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


> * Kernel (e.g. `uname -a`):
Linux hydsoft 5.4.243-1.el7.elrepo.x86_64 #1 SMP Tue May 16 10:43:45 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux


> * Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
        Manufacturer: GenuineIntel
	Manufacturer: Intel Corporation
	Manufacturer Name: Intel
	Manufacturer: No Enclosure
	Manufacturer: Not Specified
	Manufacturer: VMware, Inc.
	Product Name: 440BX Desktop Reference Platform
	Product Name: VMware Virtual Platform

**Comment by zhasm** [comment]
@weixingsheng666 centos 7.4 版本太老，许多lib 都已经无法兼容了。请升级到最新版centos 7.9, 再进行安装。

**Comment by TracyBin** [comment]
遇到了同样的问题

`TASK [common : make cache] *****************************************************
fatal: [192.168.8.143]: FAILED! => {"changed": true, "cmd": "yum clean all\nyum -y --disablerepo='*' --enablerepo='yunion*' makecache\n", "delta": "0:00:01.485973", "end": "2023-08-18 10:40:23.600423", "msg": "non-zero return code", "rc": 1, "start": "2023-08-18 10:40:22.114450", "stderr": "https://iso.yunion.cn/%24contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error\n正在尝试其它镜像。\n\n\n One of the configured repositories failed (Packages for Yunion Multi-Cloud Platform -),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=yunion-repo- ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable yunion-repo-\n        or\n            subscription-manager repos --disable=yunion-repo-\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=yunion-repo-.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from yunion-repo-: [Errno 256] No more mirrors to try.\nhttps://iso.yunion.cn/$contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error", "stderr_lines": ["https://iso.yunion.cn/%24contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error", "正在尝试其它镜像。", "", "", " One of the configured repositories failed (Packages for Yunion Multi-Cloud Platform -),", " and yum doesn't have enough cached data to continue. At this point the only", " safe thing yum can do is fail. There are a few ways to work \"fix\" this:", "", "     1. Contact the upstream for the repository and get them to fix the problem.", "", "     2. Reconfigure the baseurl/etc. for the repository, to point to a working", "        upstream. This is most often useful if you are using a newer", "        distribution release than is supported by the repository (and the", "        packages for the previous distribution release still work).", "", "     3. Run the command with the repository temporarily disabled", "            yum --disablerepo=yunion-repo- ...", "", "     4. Disable the repository permanently, so yum won't use it by default. Yum", "        will then just ignore the repository until you permanently enable it", "        again or use --enablerepo for temporary usage:", "", "            yum-config-manager --disable yunion-repo-", "        or", "            subscription-manager repos --disable=yunion-repo-", "", "     5. Configure the failing repository to be skipped, if it is unavailable.", "        Note that yum will try to contact the repo. when it runs most commands,", "        so will have to try and fail each time (and thus. yum will be be much", "        slower). If it is a very temporary problem though, this is often a nice", "        compromise:", "", "            yum-config-manager --save --setopt=yunion-repo-.skip_if_unavailable=true", "", "failure: repodata/repomd.xml from yunion-repo-: [Errno 256] No more mirrors to try.", "https://iso.yunion.cn/$contentdir/7/3.10/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error"], "stdout": "已加载插件：fastestmirror\n正在清理软件源： base docker-ce-stable epel extras kubernetes updates\n               : yunion-repo-\nCleaning up list of fastest mirrors\n已加载插件：fastestmirror\nDetermining fastest mirrors", "stdout_lines": ["已加载插件：fastestmirror", "正在清理软件源： base docker-ce-stable epel extras kubernetes updates", "               : yunion-repo-", "Cleaning up list of fastest mirrors", "已加载插件：fastestmirror", "Determining fastest mirrors"]}`


`[root@harbor tasks]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@harbor tasks]# uname -a
Linux harbor 5.4.150-1.el7.elrepo.x86_64 #1 SMP Tue Sep 28 13:00:01 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@harbor tasks]# dmidecode | egrep -i 'manufacturer|product' |sort -u
	Manufacturer: 000000000000
	Manufacturer: GenuineIntel
	Manufacturer: Intel Corporation
	Manufacturer Name: Intel
	Manufacturer: No Enclosure
	Manufacturer: Not Specified
	Manufacturer: VMware, Inc.
	Product Name: 440BX Desktop Reference Platform
	Product Name: VMware Virtual Platform`
