### ISSUE TITLE
[求助/Help]使用docker compose安装后, 如何添加新节点?

### ISSUE THREAD

**Issue by cnsunfocus** [yunionio/cloudpods#17190]
3.10.1版本, 虚机+docker compose 部署

ocadm命令是不是只有k8s部署方式才可以用.
climc命令行没找到host相关的添加命令

**Comment by zexi** [comment]
> 3.10.1版本, 虚机+docker compose 部署
> 
> ocadm命令是不是只有k8s部署方式才可以用. climc命令行没找到host相关的添加命令

@cnsunfocus docker compose 目前只支持单节点 all in one 的方式部署，不支持添加节点，是一个快速部署体验的功能。

如果要在正式环境使用，还是需要用 ocboot 的方式来部署。ocboot 支持添加节点，以及高可用部署等功能。
