### ISSUE TITLE
[Docs] 发布日志 版本排序是否可以调整一下？

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17207]
# 结果
![aLECZZQ3tD](https://github.com/yunionio/cloudpods/assets/11387540/548a552a-4a2c-4a0e-bb89-38c6692e5e80)

# 期望
![FjmxFRfVQm](https://github.com/yunionio/cloudpods/assets/11387540/a3d87eb1-672a-432c-8968-c64bafd9510f)

**Comment by zexi** [comment]
https://github.com/yunionio/docs/pull/1509/files
已调整
