### ISSUE TITLE
使用Kubernetes Helm 安装Cloudpods时出现cluster.yaml文件的格式报错

### ISSUE THREAD

**Issue by weixingsheng666** [yunionio/cloudpods#17218]
(cloudpods_venv) [root@hydsoft cloudpods]# helm install --name-template default --namespace onecloud --debug  . -f values-dev.yaml  --create-namespace
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /wei_test/cloudpods/ocboot/charts/cloudpods

Error: INSTALLATION FAILED: YAML parse error on cloudpods/templates/cluster.yaml: error converting YAML to JSON: yaml: line 20: found character that cannot start any token
helm.go:84: [debug] error converting YAML to JSON: yaml: line 20: found character that cannot start any token
YAML parse error on cloudpods/templates/cluster.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:170
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:284
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:286
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:145
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:147
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598

helm安装版本是v3.12
系统是centos7.9
Kubernetes按文档要求安装了v1.24的

>>>>cluster.yaml内容如下：
{{ $cluster := .Values.cluster }}
{{ $mysql := .Values.cluster.mysql }}
# deploy onecloud cluster customize resource instance
apiVersion: "onecloud.yunion.io/v1alpha1"
kind: OnecloudCluster
metadata:
  name: {{ include "cloudpods.fullname" . }}
  annotations:
    onecloud.yunion.io/edition: "{{ .Values.cluster.edition }}"
    helm.sh/hook: post-install,post-upgrade,post-rollback
  labels:
    {{- include "cloudpods.labels" . | nindent 4 }}
spec:
  mysql:
    host: {{ template "cloudpods.cluster.mysql.host" . }}
    port: {{ $mysql.port }}
    username: {{ $mysql.user }}
    password: {{ $mysql.password }}
  region: "region0"
  imageRepository: "{{ $cluster.imageRepository }}"
  version: "{{ $cluster.version | default .Chart.AppVersion }}"
  loadBalancerEndpoint: "{{ $cluster.publicEndpoint }}"
  disableResourceManagement: {{ $cluster.disableResourceManagement }}
  productVersion: {{ $cluster.productVersion }}
  ansibleserver:
    service:
      nodePort: {{ int $cluster.ansibleserver.service.nodePort }}
  apiGateway:
    apiService:
      nodePort: {{ int $cluster.apiGateway.apiService.nodePort}}
    wsService:
      nodePort: {{ int $cluster.apiGateway.wsService.nodePort }}
  autoupdate:
    service:
      nodePort: {{ int $cluster.autoupdate.service.nodePort }}
  baremetalagent:
    disable: {{ $cluster.baremetalagent.disable }}
    requests:
      storage: {{ $cluster.baremetalagent.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  cloudevent:
    service:
      nodePort: {{ int $cluster.cloudevent.service.nodePort }}
  cloudid:
    service:
      nodePort: {{ int $cluster.cloudid.service.nodePort }}
  cloudnet:
    service:
      nodePort: {{ int $cluster.cloudnet.service.nodePort }}
  cloudproxy:
    service:
      nodePort: {{ int $cluster.cloudproxy.service.nodePort }}
  devtool:
    service:
      nodePort: {{ int $cluster.devtool.service.nodePort }}
  glance:
    service:
      nodePort: {{ int $cluster.glance.service.nodePort }}
    requests:
      storage: {{ $cluster.glance.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  influxdb:
    service:
      nodePort: {{ int $cluster.influxdb.service.nodePort }}
    requests:
      storage: {{ $cluster.influxdb.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  itsm:
    service:
      nodePort: {{ int $cluster.itsm.service.nodePort }}
  keystone:
    adminService:
      nodePort: {{ int $cluster.keystone.adminService.nodePort }}
    publicService:
      nodePort: {{ int $cluster.keystone.publicService.nodePort }}
  kubeserver:
    service:
      nodePort: {{ int $cluster.kubeserver.service.nodePort }}
  logger:
    service:
      nodePort: {{ int $cluster.logger.service.nodePort }}
  meter:
    service:
      nodePort: {{ int $cluster.meter.service.nodePort }}
    requests:
      storage: {{ $cluster.meter.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  monitor:
    service:
      nodePort: {{ int $cluster.monitor.service.nodePort }}
  onecloudServiceOperator:
    disable: true
    service:
      nodePort: {{ int $cluster.onecloudServiceOperator.service.nodePort }}
  regionDNS:
    disable: true
  regionServer:
    service:
      nodePort: {{ int $cluster.regionServer.service.nodePort }}
  report:
    service:
      nodePort: {{ int $cluster.report.service.nodePort }}
  s3gateway:
    service:
      nodePort: {{ int $cluster.s3gateway.service.nodePort }}
  scheduledtask:
    service:
      nodePort: {{ int $cluster.scheduledtask.service.nodePort }}
  scheduler:
    service:
      nodePort: {{ int $cluster.scheduler.service.nodePort }}
  suggestion:
    service:
      nodePort: {{ int $cluster.suggestion.service.nodePort }}
  webconsole:
    service:
      nodePort: {{ int $cluster.webconsole.service.nodePort }}
  yunionagent:
    service:
      nodePort: {{ int $cluster.yunionagent.service.nodePort }}
  yunionconf:
    service:
      nodePort: {{ int $cluster.yunionconf.service.nodePort }}
  monitorStack:
    disable: true

**Comment by weixingsheng666** [comment]
> > values-dev.yaml
> 
> 看下这个文件第20行 是否符合yaml的语法

values-dev.yaml这个文件第二十行是注释的。运行报的是cluster.yaml这个文件第二十行不符合语法，但是看了一下应该没啥问题，使用yaml在线检查时，这个文件却从第二行开始都是报错的，我觉的会不会是安装的哪个步骤出现问题了，但是看了一下又没找出来

**Comment by zexi** [comment]
> > > values-dev.yaml
> > 
> > 
> > 看下这个文件第20行 是否符合yaml的语法
> 
> values-dev.yaml这个文件第二十行是注释的。运行报的是cluster.yaml这个文件第二十行不符合语法，但是看了一下应该没啥问题，使用yaml在线检查时，这个文件却从第二行开始都是报错的，我觉的会不会是安装的哪个步骤出现问题了，但是看了一下又没找出来

@weixingsheng666 建议重新按照文档：https://www.cloudpods.org/zh/docs/quickstart/k8s/#%E9%83%A8%E7%BD%B2

用 git clone 下来，在不要修改 yaml 得情况下部署试试
