### ISSUE TITLE
[求助/Help] 阿里云主机centos 7.7 ，持续出现此错误，安装3.9版本失败

### ISSUE THREAD

**Issue by junjays** [yunionio/cloudpods#17227]
以run ip  方式安装或自定义配置安装均会出现此错误，已尝试阿里云centos 7.6 -7.9不同版本：

TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ********
fatal: [172.22.148.94]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "init", "--control-plane-endpoint", "172.22.148.94:6443", "--mysql-host", "172.22.148.94", "--mysql-user", "root", "--mysql-password", "wtmPwvz57p3M", "--mysql-port", "3306", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--apiserver-advertise-address", "172.22.148.94", "--node-ip", "172.22.148.94", "--onecloud-version", "v3.9.10", "--operator-version", "v3.9.10", "--pod-network-cidr", "10.40.0.0/16", "--service-cidr", "10.96.0.0/12", "--service-dns-domain", "cluster.local", "--addon-calico-ip-autodetection-method", "can-reach=172.22.148.94"], "delta": "0:05:14.297669", "end": "2023-06-01 16:51:34.444077", "msg": "non-zero return code", "rc": 1, "start": "2023-06-01 16:46:20.146408", "stderr": "\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.5. Latest validated version: 18.09\nerror execution phase wait-control-plane: couldn't initialize a Kubernetes cluster", "stderr_lines": ["\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.5. Latest validated version: 18.09", "error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster"], "stdout": "[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.9.10\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a OneCloud on Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'ocadm config images pull'\nvip is empty. no need to install keepalived.\n[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"\n[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"\n[kubelet-start] Activating the kubelet service\n[certs] Using certificateDir folder \"/etc/kubernetes/pki\"\n[certs] Generating \"front-proxy-ca\" certificate and key\n[certs] Generating \"front-proxy-client\" certificate and key\n[certs] Generating \"etcd/ca\" certificate and key\n[certs] Generating \"etcd/server\" certificate and key\n[certs] etcd/server serving cert is signed for DNS names [pod localhost] and IPs [172.22.148.94 127.0.0.1 ::1]\n[certs] Generating \"etcd/peer\" certificate and key\n[certs] etcd/peer serving cert is signed for DNS names [pod localhost] and IPs [172.22.148.94 127.0.0.1 ::1]\n[certs] Generating \"apiserver-etcd-client\" certificate and key\n[certs] Generating \"etcd/healthcheck-client\" certificate and key\n[certs] Generating \"ca\" certificate and key\n[certs] Generating \"apiserver-kubelet-client\" certificate and key\n[certs] Generating \"apiserver\" certificate and key\n[certs] apiserver serving cert is signed for DNS names [pod kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.22.148.94 172.22.148.94]\n[certs] Generating \"sa\" key and public key\n[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"\n[kubeconfig] Writing \"admin.conf\" kubeconfig file\n[kubeconfig] Writing \"kubelet.conf\" kubeconfig file\n[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file\n[kubeconfig] Writing \"scheduler.conf\" kubeconfig file\n[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"\n[control-plane] Creating static Pod manifest for \"kube-apiserver\"\n[control-plane] Creating static Pod manifest for \"kube-controller-manager\"\n[control-plane] Creating static Pod manifest for \"kube-scheduler\"\n[etcd] Creating static Pod manifest for local etcd in \"/etc/kubernetes/manifests\"\n[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory \"/etc/kubernetes/manifests\". This can take up to 4m0s\n[kubelet-check] Initial timeout of 40s passed.\n\nUnfortunately, an error has occurred:\n\ttimed out waiting for the condition\n\nThis error is likely caused by:\n\t- The kubelet is not running\n\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)\n\nIf you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:\n\t- 'systemctl status kubelet'\n\t- 'journalctl -xeu kubelet'\n\nAdditionally, a control plane component may have crashed or exited when started by the container runtime.\nTo troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.\nHere is one example how you may list all Kubernetes containers running in docker:\n\t- 'docker ps -a | grep kube | grep -v pause'\n\tOnce you have found the failing container, you can inspect its logs with:\n\t- 'docker logs CONTAINERID'", "stdout_lines": ["[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.9.10", "[preflight] Running pre-flight checks", "[preflight] Pulling images required for setting up a OneCloud on Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'ocadm config images pull'", "vip is empty. no need to install keepalived.", "[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"", "[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"", "[kubelet-start] Activating the kubelet service", "[certs] Using certificateDir folder \"/etc/kubernetes/pki\"", "[certs] Generating \"front-proxy-ca\" certificate and key", "[certs] Generating \"front-proxy-client\" certificate and key", "[certs] Generating \"etcd/ca\" certificate and key", "[certs] Generating \"etcd/server\" certificate and key", "[certs] etcd/server serving cert is signed for DNS names [pod localhost] and IPs [172.22.148.94 127.0.0.1 ::1]", "[certs] Generating \"etcd/peer\" certificate and key", "[certs] etcd/pe

**Comment by zexi** [comment]
```
The kubelet is not running\n\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled
```
看起来是这个问题导致的

**Comment by zhasm** [comment]
@junjays 
1. 请确保cpu、内存，大于4核8G；
2. 请贴一下kubelet 的日志，便于我们分析详情。谢谢！
