### ISSUE TITLE
虚拟机超卖比例在哪里调整？

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#17247]
我们在创建虚拟机时，宿主机还剩25%的cpu 及内存 磁盘  但提示可用资源不足，我怀疑是默认的超卖资源上限配置限制了，想问下 这个可以在哪里调整？

**Comment by wanyaoqi** [comment]
参考：https://www.cloudpods.org/zh/docs/web_ui/computing/resources/host/#%E8%B0%83%E6%95%B4%E8%B6%85%E5%94%AE%E4%B8%8A%E9%99%90
