### ISSUE TITLE
[求助/Help]集群部署时失败, cloud-operator提示 no route to host

### ISSUE THREAD

**Issue by cnsunfocus** [yunionio/cloudpods#17252]
版本3.10.1 使用的是ocboot自带的config-example-nodes.yml模板, 修改了ip地址.
使用高可用部署的脚本生成也有同样的问题
部署过程中提示
![1685957002887](https://github.com/yunionio/cloudpods/assets/3301715/95058823-d097-438f-80c3-7f5625d88148)

按照之前issue的建议查看了operator pod中的日志, 但是原issue没有结论. 
 operator pod中提示的ip地址, 并没有在部署模板中配置.

![image](https://github.com/yunionio/cloudpods/assets/3301715/f44df897-bf46-4964-8a82-f7320d87da18)

不知道是哪里出了问题?

**Comment by zexi** [comment]
> 版本3.10.1 使用的是ocboot自带的config-example-nodes.yml模板, 修改了ip地址. 使用高可用部署的脚本生成也有同样的问题 部署过程中提示 ![1685957002887](https://user-images.githubusercontent.com/3301715/243311212-95058823-d097-438f-80c3-7f5625d88148.png)
> 
> 按照之前issue的建议查看了operator pod中的日志, 但是原issue没有结论. operator pod中提示的ip地址, 并没有在部署模板中配置.
> 
> ![image](https://user-images.githubusercontent.com/3301715/243309808-f44df897-bf46-4964-8a82-f7320d87da18.png)
> 
> 不知道是哪里出了问题?

这个是 operator 从内部连不上 k8s apiserver 导致的，应该是网络相关的问题，执行下面命令看下网络信息：
```
ip addr
ip route 
```
再执行下面的命令看下 calico-node 这个 cni pod 的日志：
```bash
kubectl get pods -n kube-system | grep calico-node

# 找到上面 calico-node 的名称，查出日志
kubectl logs -n kube-system calico-node-xxxx
```
