### ISSUE TITLE
[BUG]启用USB透传后宿主机离线

### ISSUE THREAD

**Issue by Shuzhen049** [yunionio/cloudpods#17269]
**问题描述/What happened**:
1. 在宿主机上插入U盘。
2. 按照文档编辑/etc/yunion/host.conf，将disable_usb设置为false。
3. 删除宿主机上的default-host-xxxxx pod。
4. pod重建后，在web界面上发现宿主机处于离线状态。
在宿主机日志中有以下报错：
probeSyncIsolatedDevices: Sync device {"bus_id":"001:002","device_id":"1234","model_name":"LogiLink UDisk flash drive","vendor_id":"abcd"}: {"error":{"class":"BadRequestError","code":400,"details":"dev addr 001:002 registed","request":{"body":"{\"isolated_device\":{\"addr\":\"001:002\",\"detected_on_host\":true,\"dev_type\":\"USB\",\"host_id\":\"8e4e8d5f-fb..._device_id\":\"abcd:1234\"}}","headers":{"Content-Length":"196","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"a1c890a3"},"method":"POST","url":"https://default-region:30888/isolated_devices"}}}

5. 在禁用USB透传并重建pod后，宿主机能正常上线。

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): 
CentOS Linux release 7.9.2009 (Core)

- Kernel (e.g. `uname -a`):
 Linux cloudpods-1 5.4.130-1.yn20221208.el7.x86_64 #1 SMP Thu Dec 8 12:09:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
Manufacturer: innotek GmbH
Manufacturer: Oracle Corporation
Product Name: VirtualBox

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
+-----------------+----------------------------------------------+
|      Field      |                    Value                     |
+-----------------+----------------------------------------------+
| ansible         | release/3.10(dd50edcbee23053111)             |
| apimap          | release/3.10(dd50edcbee23053112)             |
| cloudevent      | release/3.10(dd50edcbee23053111)             |
| cloudid         | release/3.10(dd50edcbee23053112)             |
                                      |
 |                | <head><title>502 Bad Gateway</title></head>
                                      |
   |              | <center><h1>502 Bad Gateway</h1></center>
           |      | <hr><center>nginx/1.20.1</center>
                                     |
                                     |
| cloudmon        | release/3.10(dd50edcbee23053112)             |
| cloudproxy      | release/3.10(dd50edcbee23053111)             |
| compute_v2      | release/3.10(dd50edcbee23053112)             |
| devtool         | release/3.10(dd50edcbee23053112)             |
| etcd            | {"etcdserver":"3.4.6","etcdcluster":"3.4.0"} |
| identity        | release/3.10(dd50edcbee23053111)             |
| image           | release/3.10(dd50edcbee23053111)             |
| influxdb        | 404 page not found                           |
| k8s             | heads/v3.10.2-20230531.0(39dd43323053111)    |
| log             | release/3.10(dd50edcbee23053111)             |
| monitor         | release/3.10(dd50edcbee23053112)             |
| notify          | release/3.10(dd50edcbee23053111)             |
| scheduledtask   | release/3.10(dd50edcbee23053112)             |
| scheduler       | release/3.10(dd50edcbee23053112)             |
| torrent-tracker | <title>Not Found</title>                     |
| vpcagent        | release/3.10(dd50edcbee23053112)             |
| webconsole      | release/3.10(dd50edcbee23053111)             |
| yunionconf      | release/3.10(dd50edcbee23053111)             |
+-----------------+----------------------------------------------+

**Comment by wanyaoqi** [comment]
Hi @Shuzhen049 , 这个问题已经修复了 https://github.com/yunionio/cloudpods/pull/17258
可以合并一下pr后重新 打一个 region包
