### ISSUE TITLE
[求助/Help]我无法在v3.10.2中纳管移动云账户

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17268]
如题，在kubernetes上完成cloudpods v3.10.2部署后，我按照文档说明使用climc创建了用户，但是这里的移动云选项直接消失了。
![image](https://github.com/yunionio/cloudpods/assets/61458603/f24396ac-e212-4b1d-9b1d-3335c959886a)
上方有提示可以在“功能选择”功能中找到可用云平台配置，但是我并没有在右上角的对应图标的下拉栏中找到对应选项，请问这里提示的“联系管理员设置”是指什么功能呢？我该怎么启用这个功能呢？
感谢您在百忙中抽空解决我的问题，十分感谢！！

**Comment by hoganlxj** [comment]
https://www.cloudpods.org/zh/docs/setup/feature-config/  参考这个文档，打开移动云

**Comment by C4a15Wh** [comment]
好的，解决了，谢谢！

**Comment by xzzdhq** [comment]
> https://www.cloudpods.org/zh/docs/setup/feature-config/ 参考本文档，打开移动云

hello，想问一下，可以在发一次地址嘛，文档地址迁移了，打不开

**Comment by hoganlxj** [comment]
> > https://www.cloudpods.org/zh/docs/setup/feature-config/ 参考本文档，打开移动云
> 
> hello，想问一下，可以在发一次地址嘛，文档地址迁移了，打不开
https://www.cloudpods.org/docs/guides/cmp/cloudaccounts/cloudaccount#%E6%96%B0%E5%BB%BA%E7%A7%BB%E5%8A%A8%E4%BA%91%E8%B4%A6%E5%8F%B7
