### ISSUE TITLE
虚拟机设置密码

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17262]
1、通过iso安装window server2022后，安装guest-agent。
2、页面上面修改密码后，虚拟机密码生效。
3、但是管理界面密码不显示虚拟机密码和账号。

**Comment by hoganlxj** [comment]
这是我们的bug，已经在修复中

**Comment by wanyaoqi** [comment]
fixed: https://github.com/yunionio/cloudpods/pull/17277
