### ISSUE TITLE
使用Docker Compose部署的cloudpods怎么添加计算节点呀？

### ISSUE THREAD

**Issue by weixingsheng666** [yunionio/cloudpods#17274]

**Comment by zexi** [comment]
@weixingsheng666 和这个是同样的问题：https://github.com/yunionio/cloudpods/issues/17190，docker compose  目前只支持单节点 all in one 的方式部署，不支持添加节点，是一个快速部署体验的功能。

如果要在正式环境使用，还是需要用 ocboot 的方式来部署。ocboot 支持添加节点，以及高可用部署等功能。
