### ISSUE TITLE
[求助/Help] vpc gateway 不会向新开云主机的dhcp请求做响应

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#17270]
### 版本
- cloudpods 版本: v3.10.2
- all in one 部署.
- 宿主机: dell R730XD Centos7.9_2009 3.10.0-1160.6.1.el7.yn20201125.x86_64 #1 SMP Sat Nov 21 12:06:27 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
### 问题描述:

几天前由于遇到了一些问题 #17213 , 从 3.10.1 升级到 3.10.2. 升级完开通主机是OK 的. 今天发现, 新开通的云主机无法通过dhcp获取ip地址. 但是升级平台版本前开通的主机, 重启后是可以dhcp获取ip的.
抓包发现: 针对新开的机器, vpc gateway 不会做出 dhcp 响应, 而升级平台前开的机器会做 dhcp响应. 新开和升级之前已经开过的主机用是用一个 `VPCSubnet`

下图为新开的主机抓包, 只有请求, 没有响应.

![2023-06-09_16-44](https://github.com/yunionio/cloudpods/assets/44364154/5940ae0d-576a-4e3c-894e-effd5f9e12bb)

下图为升级平台前开的主机, 重启网卡能 `dhcp` 获得IP
![2023-06-09_16-41](https://github.com/yunionio/cloudpods/assets/44364154/c0a46634-0d5c-48b5-9d34-e96c5600fc63)

尝试重启过 host 和 vpcagent 这俩pod, 未果.

**Comment by wanyaoqi** [comment]
可以看下 vpcagent日志有没有报错

**Comment by saltfishh** [comment]
> 可以看下 vpcagent日志有没有报错

过滤哪个字段? default-vpcagent这个 pod 日志非常长

**Comment by wanyaoqi** [comment]
> 

@saltfishh 找一下 error 的日志，虚机id, 网卡 id相关的

**Comment by wanyaoqi** [comment]
> > > 
> > 
> > 
> > @saltfishh 找一下 error 的日志，虚机id, 网卡 id相关的
> 
> * 下面的就是 虚拟机的uuid
> 
> > [root@cloud-stack ~]# kubectl logs default-vpcagent-69bcfb5fbd-gpn84 -n onecloud | grep fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf -C5
> > "name="iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8"" 
> > 		"port_security=["00:22:69:4b:50:17 10.11.1.136/25"]" 
> > 		"type=""" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "ports" "@iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8" 
> > 	-- "--id=@gnrDefault" "create" "Logical_Router_Static_Route" 
> > 		"external_ids:"oc-ref"="gnrDefault/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"ip_prefix="10.11.1.136/32"" 
> > 		"nexthop="100.64.0.128"" 
> > 		"output_port="vpc-rh/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4"" 
> > 		"policy="src-ip"" 
> > 	-- "add" "Logical_Router" "vpc-ext-r/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4" "static_routes" "@gnrDefault" 
> > 	-- "--id=@acl0" "create" "ACL" 
> > 		"action="drop"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=1" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@acl0" 
> > 	-- "--id=@Acl1" "create" "ACL" 
> > 		"action="allow-related"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\" && arp"" 
> > 		"priority=2" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@Acl1" 
> > 	-- "--id=@acl2" "create" "ACL" 
> > 		"action="allow-related"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\" && ip4"" 
> > 		"priority=101" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@acl2" 
> > 	-- "--id=@qosVif0" "create" "QoS" 
> > 		"bandwidth:"rate"=1000000" 
> > 		"bandwidth:"burst"=2000000" 
> > 		"direction="from-lport"" 
> > 		"external_ids:"oc-ref"="qos/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"match="inport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=2000" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "qos_rules" "@qosVif0" 
> > 	-- "--id=@qosVif1" "create" "QoS" 
> > 		"bandwidth:"rate"=1000000" 
> > 		"bandwidth:"burst"=2000000" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="qos/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=1000" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "qos_rules" "@qosVif1"
> > : err: signal: killed, output:
> > [info 2023-06-09 08:41:01 ovn.(*Worker).Start(worker.go:86)] ovn: got new data from api helper
> > --
> > "name="iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8"" 
> > 		"port_security=["00:22:69:4b:50:17 10.11.1.136/25"]" 
> > 		"type=""" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "ports" "@iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8" 
> > 	-- "--id=@gnrDefault" "create" "Logical_Router_Static_Route" 
> > 		"external_ids:"oc-ref"="gnrDefault/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"ip_prefix="10.11.1.136/32"" 
> > 		"nexthop="100.64.0.128"" 
> > 		"output_port="vpc-rh/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4"" 
> > 		"policy="src-ip"" 
> > 	-- "add" "Logical_Router" "vpc-ext-r/f22f0f11-22b9-4508-86bd-cf37c0a7dfb4" "static_routes" "@gnrDefault" 
> > 	-- "--id=@acl0" "create" "ACL" 
> > 		"action="drop"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=1" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@acl0" 
> > 	-- "--id=@Acl1" "create" "ACL" 
> > 		"action="allow-related"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\" && arp"" 
> > 		"priority=2" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@Acl1" 
> > 	-- "--id=@acl2" "create" "ACL" 
> > 		"action="allow-related"" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="acl/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"log=false" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\" && ip4"" 
> > 		"priority=101" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "acls" "@acl2" 
> > 	-- "--id=@qosVif0" "create" "QoS" 
> > 		"bandwidth:"rate"=1000000" 
> > 		"bandwidth:"burst"=2000000" 
> > 		"direction="from-lport"" 
> > 		"external_ids:"oc-ref"="qos/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"match="inport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=2000" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "qos_rules" "@qosVif0" 
> > 	-- "--id=@qosVif1" "create" "QoS" 
> > 		"bandwidth:"rate"=1000000" 
> > 		"bandwidth:"burst"=2000000" 
> > 		"direction="to-lport"" 
> > 		"external_ids:"oc-ref"="qos/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff/fc4c518a-ccc7-43f7-8d93-ed9c70fa81cf/LANVPCSub-8"" 
> > 		"match="outport == \"iface-249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff-LANVPCSub-8\""" 
> > 		"priority=1000" 
> > 	-- "add" "Logical_Switch" "subnet/249c0bc2-c1fd-45a4-8fc3-c8bb69af39ff" "qos_rules" "@qosVif1"
> > : err: signal: killed, output:
> > [info 2023-06-09 09:27:41 ovn.(*Worker).Start(worker.go:93)] ovn: tick check

@saltfishh grep 一下 error 日志看看

**Comment by saltfishh** [comment]
@wanyaoqi 

> [error 2023-06-09 06:29:49 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 06:30:32 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:31:33 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:32:34 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:32:42 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 06:33:35 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:34:35 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:34:46 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:35:20 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:35:36 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 06:35:50 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 06:36:06 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 06:36:29 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:37:35 ovn.(*Worker).Start(worker.go:89)] ovn: List QoS:
[error 2023-06-09 06:37:43 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:38:03 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:38:58 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 06:39:30 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:39:38 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:40:22 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:40:30 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:40:40 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:41:24 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:42:41 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 06:43:29 ovn.(*Worker).Start(worker.go:95)] ovn: List ACL:
[error 2023-06-09 06:43:37 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:43:57 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:45:14 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 06:46:39 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 06:47:27 ovn.(*Worker).Start(worker.go:95)] ovn: List ACL:
[error 2023-06-09 06:47:35 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:48:05 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:49:20 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:49:28 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:50:14 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 06:50:35 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 06:51:07 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 06:51:40 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:52:00 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:52:50 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 06:53:38 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 06:54:41 ovn.(*Worker).Start(worker.go:95)] ovn: List QoS:
[error 2023-06-09 06:54:49 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:54:59 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:56:00 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:56:10 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:57:17 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 06:57:49 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 06:58:02 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 06:59:27 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 06:59:51 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:00:07 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:00:15 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:00:41 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:01:05 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:01:21 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:02:04 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:03:05 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:04:06 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:04:29 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Router:
[error 2023-06-09 07:06:26 ovn.(*Worker).Start(worker.go:89)] ovn: ClaimGuestnetwork:
: err: signal: killed, output: 2023-06-09T07:06:26Z|00002|timeval|WARN|Unreasonably long 7581ms poll interval (7439ms user, 140ms system)
[error 2023-06-09 07:06:34 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:07:28 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 07:07:37 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:08:33 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:09:21 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:09:44 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:10:15 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:11:41 ovn.(*Worker).Start(worker.go:89)] ovn: find dhcpopt:
[error 2023-06-09 07:11:57 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:12:05 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:12:23 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:13:22 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:13:38 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:13:46 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:14:06 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:15:05 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:15:21 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:16:28 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 07:18:24 ovn.(*Worker).Start(worker.go:89)] ovn: find dhcpopt:
[error 2023-06-09 07:18:32 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:18:48 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:19:40 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:20:09 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:21:03 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:21:40 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:22:11 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:23:05 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:24:37 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Static_Route:
[error 2023-06-09 07:24:48 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:25:06 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:26:15 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:26:58 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:27:56 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:28:12 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:29:37 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Static_Route:
[error 2023-06-09 07:31:02 ovn.(*Worker).Start(worker.go:89)] ovn: List QoS:
[error 2023-06-09 07:31:10 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:31:18 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:31:59 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:33:00 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:34:01 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:35:22 ovn.(*Worker).Start(worker.go:95)] ovn: List DNS:
[error 2023-06-09 07:36:25 ovn.(*Worker).Start(worker.go:89)] ovn: List QoS:
[error 2023-06-09 07:36:33 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:37:04 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:38:20 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router:
[error 2023-06-09 07:38:46 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Router:
[error 2023-06-09 07:39:06 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:40:07 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:41:39 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Static_Route:
[error 2023-06-09 07:42:01 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:42:09 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:43:24 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 07:44:41 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:45:02 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:45:10 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch:
[error 2023-06-09 07:46:03 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:47:28 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Port:
[error 2023-06-09 07:49:01 ovn.(*Worker).Start(worker.go:89)] ovn: List QoS:
[error 2023-06-09 07:49:40 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Router_Static_Route:
[error 2023-06-09 07:49:56 ovn.(*Worker).Start(worker.go:95)] ovn: List Logical_Switch_Port:
[error 2023-06-09 07:50:44 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:51:31 ovn.(*Worker).Start(worker.go:89)] ovn: List ACL:
[error 2023-06-09 07:51:39 ovn.(*Worker).Start(worker.go:89)] ovn: List Logical_Switch:
[error 2023-06-09 07:53:09 ovn.(*Worker).Start(worker.go:89)] ovn: ClaimGuestnetwork:
: err: signal: killed, output: 2023-06-09T07:53:08Z|00002|timeval|WARN|Unreasonably long 7488ms poll interval (7424ms user, 63ms system)

**Comment by wanyaoqi** [comment]
应该和这个是同一个问题 https://github.com/yunionio/cloudpods/issues/17273

**Comment by saltfishh** [comment]
> 应该和这个是同一个问题 #17273

解决了麻烦艾特一下

**Comment by saltfishh** [comment]
@wanyaoqi 重启宿主机后该问题消失. 但不知道为什么.

**Comment by saltfishh** [comment]
vpcagent回滚到 3.10.1 正常
