### ISSUE TITLE
[文档/Docs]文档给的流程简直太难搞了

### ISSUE THREAD

**Issue by Anbool** [yunionio/cloudpods#17280]
All in One 部署的管理节点，使用 ocboot 部署的计算节点，文档也没有说明什么情况下需要做哪些修改调整，只靠文档压根整个系统就跑不起来，真是服了。完全按照下面文档部署的计算节点，我就想知道为什么按照文档部署了，管理节点压根就看不到宿主机列表，搞人心态！
https://www.cloudpods.org/zh/docs/quickstart/allinone/
https://www.cloudpods.org/zh/docs/setup/host/

**Comment by ioito** [comment]
除了抱怨，没有任何有效反馈信息

**Comment by Anbool** [comment]
@ioito 你可算了吧，用户能说出这话，你们也不考虑考虑为什么？

**Comment by zhasm** [comment]
@Anbool 请参考文档： https://www.cloudpods.org/zh/docs/quickstart/allinone/#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA

如果已经解决您的问题，请关闭本issue。
如果文档对您没有帮助，请继续留言询问。
