### ISSUE TITLE
[求助/Help]大家好 想请问一下，cloudpods 的多k8s集群管理是通过直接对接受管集群的APIServer的方式吗？  文档中没有找到相关的信息

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17298]
是的，通过k8s的API管理集群

**Comment by zexi** [comment]
<img width="490" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/caa1c84b-450c-46e2-b9eb-d96680be839a">
<img width="498" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/25aff19d-2ea2-4996-ab03-630ce22ba959">
来自用户群的问题
