### ISSUE TITLE
安装报错，WARNING:Module did not set no_log for update_password[求助/Help]

### ISSUE THREAD

**Issue by llp520-jkcs** [yunionio/cloudpods#17297]

**Comment by Anbool** [comment]
放弃吧，别用了

**Comment by jackgao2015** [comment]
这个是mysql root 赋权有问题，可以手工登陆下mysql，执行里面给出赋权命令后，再重新安装下

**Comment by zhasm** [comment]
@llp520-jkcs  'raw mysql' 相关的代码早已废弃。请确保您的ocboot 为最新的代码，然后重新执行安装过程。

**Comment by llp520-jkcs** [comment]
lian
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 安装报错，WARNING:Module did not set no_log for update_password[求助/Help] (Issue #17297)





 
@llp520-jkcs  'raw mysql' 相关的代码早已废弃。请确保您的ocboot 为最新的代码，然后重新执行安装过程。

**Comment by llp520-jkcs** [comment]
lian
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 安装报错，WARNING:Module did not set no_log for update_password[求助/Help] (Issue #17297)





 
这个是mysql root 赋权有问题，可以手工登陆下mysql，执行里面给出赋权命令后，再重新安装下

**Comment by llp520-jkcs** [comment]
lian
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 安装报错，WARNING:Module did not set no_log for update_password[求助/Help] (Issue #17297)





 
@llp520-jkcs  'raw mysql' 相关的代码早已废弃。请确保您的ocboot 为最新的代码，然后重新执行安装过程。

**Comment by llp520-jkcs** [comment]
目前又发生了这个状况
![image](https://github.com/yunionio/cloudpods/assets/63503074/b301078a-4bb1-4af5-ad31-0d263a31cede)

**Comment by llp520-jkcs** [comment]
谢谢大家对我的问题解决，主要我是java.目前做部分运维

**Comment by llp520-jkcs** [comment]
![image](https://github.com/yunionio/cloudpods/assets/63503074/d2bba1d8-00bd-47d9-9eaa-6b7e7171d8de)

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/63503074/245727358-3ad279be-7f8a-410e-91b6-82b9950428d3.png)

@llp520-jkcs 这个代码版本太低了，是 2021 年的，应该用最近发布的版本才对：
参考文档这里用最新的 ocboot 代码：
https://www.cloudpods.org/zh/docs/quickstart/allinone/#%E5%AE%89%E8%A3%85cloudpods
<img width="1025" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/08db66dc-b73f-4d09-9fb8-3ef9e31f740c">

如果对应的环境无法访问 github ，可以在这里下载 3.10 版本的 https://github.com/yunionio/ocboot/archive/refs/tags/v3.10.3-20230614.0.tar.gz ocboot tar.gz 代码，然后上传到部署环境运行 。

**Comment by llp520-jkcs** [comment]
感谢你的解答，用了你发的tar包有效果。目前出现这个情况。还望再帮看下非常感谢

![image](https://github.com/yunionio/cloudpods/assets/63503074/e9a34f03-a28b-4c82-b89c-4e9665d7f506)

**Comment by zhasm** [comment]
@llp520-jkcs 
看起来安装快结束了，最后初始化环境时报错了。请手工执行一下这几个步骤，看看哪一步出错：

```bash
set -x
eval $(/opt/yunion/bin/ocadm cluster rcadmin)
/opt/yunion/bin/climc user-create --password admin@123 --enabled admin
source ~/.onecloud_rcadmin
/opt/yunion/bin/climc user-update --password admin@123 --enabled --allow-web-console admin
/opt/yunion/bin/climc project-add-user system admin admin

```

**Comment by llp520-jkcs** [comment]
你好感谢你对我的帮助
![image](https://github.com/yunionio/cloudpods/assets/63503074/885bfa70-b0c1-44c1-ac4d-62fe76941564)

**Comment by llp520-jkcs** [comment]
谢谢你。我现在还在搞。我是java负责人要我搞这个。想纳管多平台云服务。感谢你大佬



---原始邮件---
发件人: "Zexi ***@***.***&gt;
发送时间: 2023年6月14日(周三) 晚上10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] 安装报错，WARNING:Module did not set no_log for update_password[求助/Help] (Issue #17297)




  
你好感谢你对我的帮助 
  
@llp520-jkcs 感觉是之前用了旧的代码，后面又用新的代码部署，比较混乱导致的。建议参考这个文档重装下：
 https://www.cloudpods.org/zh/docs/quickstart/allinone/#4-%E5%A6%82%E4%BD%95%E9%87%8D%E8%A3%85
 
重装的大概流程是：
 # 执行 kubeadm reset -f 删除 kubernetes 集群 kubeadm reset -f # 重新运行 ocboot 的脚本 ./run.py xxxx

**Comment by zhasm** [comment]
@llp520-jkcs 如果是测试环境，建议把数据库里面的数据也清空一下：
数据库的密码在yaml文件里（config-allinone.yml）：

``` mysql
drop database if exists devtool            ;
drop database if exists glance             ;
drop database if exists itsm_engine        ;
drop database if exists kubeserver         ;
drop database if exists monitor            ;
drop database if exists notify             ;
drop database if exists yunionagent        ;
drop database if exists yunionansible      ;
drop database if exists yunioncloud        ;
drop database if exists yunioncloudevent   ;
drop database if exists yunioncloudid      ;
drop database if exists yunioncloudnet     ;
drop database if exists yunioncloudproxy   ;
drop database if exists yunionconf         ;
drop database if exists yunionlogger       ;
drop database if exists yunionmeter        ;
drop database if exists keystone           ;
drop database if exists webconsole         ;
drop database if exists report             ;
drop database if exists autoupdate         ;
drop database if exists grafana            ;
```

**Comment by llp520-jkcs** [comment]
这个服务器安装不上了，问题太多了。
