### ISSUE TITLE
你好由于那个环境问题很多。我有重新搞了台新的服务器出现这个错误

### ISSUE THREAD

**Issue by llp520-jkcs** [yunionio/cloudpods#17314]
![image](https://github.com/yunionio/cloudpods/assets/63503074/76aa86f4-4a9d-4028-a4e8-87bf6194e1ff)

**Comment by wanyaoqi** [comment]
@llp520-jkcs hi， 看着是安装 openvswitch时有依赖冲突，你这是什么操作系统。
可以尝试手动安装一下openvswitch `yum install openvswitch` , 解一下冲突

**Comment by hoganlxj** [comment]
@llp520-jkcs  这个是系统上unbound-libs 冲突，可以先用 rpm -e --nodeps unbound-libs-1.6.6-5.el7_8.x86_64 
再重新安装

**Comment by zhasm** [comment]
@llp520-jkcs 估计是新旧repo（或者iso部署、ocboot部署导致的）冲突的问题。
可以这样解决：
```bash
cd /etc/yum.repos.d
for i in yunion*repo; 
do
mv -fv $i $i.bak
done
```
这样，把旧的yunionrepo禁用一下。
然后重新跑安装，看看是否能触发问题？

**Comment by llp520-jkcs** [comment]
![image](https://github.com/yunionio/cloudpods/assets/63503074/984963cb-7478-409e-bc4c-b1e5ec52e1fb)

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/63503074/246345262-984963cb-7478-409e-bc4c-b1e5ec52e1fb.png)

@llp520-jkcs 端口 22 应该是不对的，22 端口一般是用于 ssh 登陆的，这里需要填 vcentor 的地址，端口一般是 443 。
可以参考这个文档：https://www.cloudpods.org/zh/docs/introduce/ui/vmware/
