### ISSUE TITLE
[求助/Help] 创建虚拟机磁盘分配失败

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17331]
大家好
创建虚拟机磁盘分配失败，宿主机为ESXI平台 默认分配的磁盘为KVM的格式，请问如何设置对应的磁盘格式
![image](https://github.com/yunionio/cloudpods/assets/32296103/4a11bde8-2fa9-468e-82e1-5fd17126860d)

**Comment by shengxianli** [comment]
/
![image](https://github.com/yunionio/cloudpods/assets/32296103/85330890-a5e4-4d96-8675-90e0397e858d)

**Comment by hoganlxj** [comment]
@shengxianli  exsi的虚拟机系统镜像是vmdk格式。在cloudpods 看下虚拟机所用的系统镜像是否有vmdk格式
![1687262157514](https://github.com/yunionio/cloudpods/assets/32036395/9a02be8e-3ba3-4d7d-bd79-c4b776f309e4)

**Comment by shengxianli** [comment]
> @shengxianli exsi的虚拟机系统镜像是vmdk格式。在cloudpods 看下虚拟机所用的系统镜像是否有vmdk格式 ![1687262157514](https://user-images.githubusercontent.com/32036395/247106897-9a02be8e-3ba3-4d7d-bd79-c4b776f309e4.png)
感谢回复。有这个格式。但是不知道为什么创建的时候是qcow2
![image](https://github.com/yunionio/cloudpods/assets/32296103/2300aa5d-5724-4926-bee5-8f51a072034e)

**Comment by hoganlxj** [comment]
> > @shengxianli exsi的虚拟机系统镜像是vmdk格式。在cloudpods 看下虚拟机所用的系统镜像是否有vmdk格式 ![1687262157514](https://user-images.githubusercontent.com/32036395/247106897-9a02be8e-3ba3-4d7d-bd79-c4b776f309e4.png)
> > 感谢回复。有这个格式。但是不知道为什么创建的时候是qcow2，用原生ISO镜像和封装的镜像创建都是qcow2，创建的平台已经指定VMware
> > ![image](https://user-images.githubusercontent.com/32296103/247383517-2300aa5d-5724-4926-bee5-8f51a072034e.png)

@shengxianli 可以点击磁盘名称，进入详情，查看操作日志，发下磁盘分配的错误

**Comment by shengxianli** [comment]
> > > @shengxianli exsi的虚拟机系统镜像是vmdk格式。在cloudpods 看下虚拟机所用的系统镜像是否有vmdk格式 ![1687262157514](https://user-images.githubusercontent.com/32036395/247106897-9a02be8e-3ba3-4d7d-bd79-c4b776f309e4.png)
> > > 感谢回复。有这个格式。但是不知道为什么创建的时候是qcow2，用原生ISO镜像和封装的镜像创建都是qcow2，创建的平台已经指定VMware
> > > ![image](https://user-images.githubusercontent.com/32296103/247383517-2300aa5d-5724-4926-bee5-8f51a072034e.png)
> 
> @shengxianli 可以点击磁盘名称，进入详情，查看操作日志，发下磁盘分配的错误

{
    "__reason__": {
        "reason": {
            "__reason__": {
                "reason": {
                    "image_id": "9e7acaa9-e06d-4f7f-8d77-a9f35489529a",
                    "reason": {
                        "__reason__": "fail to find valid ESXi agent",
                        "__status__": "ERROR"
                    }
                },
                "stage": "OnImageCacheComplete"
            },
            "__stage__": "OnIsoPrepareComplete",
            "__status__": "error",
            "__task_name__": "StorageCacheImageTask"
        },
        "stage": "OnIsoPrepareComplete"
    },
    "__stage__": "OnCdromPrepared",
    "__status__": "error",
    "__task_name__": "GuestInsertIsoTask"
}

**Comment by shengxianli** [comment]
@hoganlxj 
{
    "__reason__": {
        "reason": {
            "__reason__": {
                "reason": {
                    "image_id": "9e7acaa9-e06d-4f7f-8d77-a9f35489529a",
                    "reason": {
                        "__reason__": "fail to find valid ESXi agent",
                        "__status__": "ERROR"
                    }
                },
                "stage": "OnImageCacheComplete"
            },
            "__stage__": "OnIsoPrepareComplete",
            "__status__": "error",
            "__task_name__": "StorageCacheImageTask"
        },
        "stage": "OnIsoPrepareComplete"
    },
    "__stage__": "OnCdromPrepared",
    "__status__": "error",
    "__task_name__": "GuestInsertIsoTask"
}

**Comment by hoganlxj** [comment]
@shengxianli kubectl get pods -n onecloud -o wide |grep esxi-agent 执行看下

**Comment by shengxianli** [comment]
@hoganlxj 您好我是使用 [Docker Compose](https://docs.docker.com/compose/) 快速部署 Cloudpods CMP
好像没有这个功能
[root@cloud ~]#  kubectl get pods -n onecloud -o Wide |grep esxi-agent
-bash: kubectl: 未找到命令

如果我手动安装了kubectl ，会得到以下输出结果
  kubectl get pods -n onecloud -o Wide |grep esxi-agent
E0627 19:25:31.511881   13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0627 19:25:31.512695   13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0627 19:25:31.514721   13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0627 19:25:31.516482   13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0627 19:25:31.518219   13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by zexi** [comment]
> @hoganlxj 您好我是使用 [Docker Compose](https://docs.docker.com/compose/) 快速部署 Cloudpods CMP 好像没有这个功能 [root@cloud ~]# kubectl get pods -n onecloud -o Wide |grep esxi-agent -bash: kubectl: 未找到命令
> 
> 如果我手动安装了kubectl ，会得到以下输出结果 kubectl get pods -n onecloud -o Wide |grep esxi-agent E0627 19:25:31.511881 13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused E0627 19:25:31.512695 13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused E0627 19:25:31.514721 13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused E0627 19:25:31.516482 13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused E0627 19:25:31.518219 13036 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused The connection to the server localhost:8080 was refused - did you specify the right host or port?

@shengxianli 使用 Docker Compose 部署的服务目前只支持对接公有云，esxi 目前有问题，还没有修复。如果要管理 vmware 需要是用 all in one 部署的方式，这个是目前支持测试最完全的部署模式。

all in one 部署请参考文档：https://www.cloudpods.org/zh/docs/quickstart/allinone/

**Comment by shengxianli** [comment]
@zexi 好的谢谢
