### ISSUE TITLE
[求助/Help]麻烦问一下，system.uptime监控未获取到数据，宿主机正常运行，这个是啥情况？

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17343]
![image](https://github.com/yunionio/cloudpods/assets/11387540/0b61b91a-3ef1-414a-9fe2-159e3bbeba60)

**Comment by jackgao2015** [comment]
看下宿主机的系统时间是否正确？

**Comment by jackgao2015** [comment]
都正确的，因为这几台宿主机还在跑ceph

**Comment by hoganlxj** [comment]
@jackgao2015 问题排查思路
1.先确认宿主机系统时间是否为网络时间 或者和 控制节点上的系统时间是否同步
2.再看下告警宿主机对应的telegraf pods  （default-telegraf-XXX）状态是否为Running，或看下里面的日志（ kubectl logs -n onecloud default-telegraf-XXX  -c telegraf）是否有error
