### ISSUE TITLE
套餐同步后provider设置有误

### ISSUE THREAD

**Issue by chenshushan** [yunionio/cloudpods#17348]
添加阿里云账号后  同步套餐设置的provider是OneCloud
![image](https://github.com/yunionio/cloudpods/assets/20243864/fc6a0ee9-e3a5-4faa-a2fb-9050694e6510)

导致申请虚拟机时选不到套餐  无法创建
![image](https://github.com/yunionio/cloudpods/assets/20243864/c3c5f9ee-08ea-4f8d-9144-2afc8b673a4c)

删除账号重试也一样

**Comment by zexi** [comment]
@chenshushan 请问使用的版本是什么？v3.10.2 ?

**Comment by chenshushan** [comment]
群里已经解决了
![Screenshot_2023-06-21-16-09-01-61_e39d2c7de19156b0683cd93e8735f348](https://github.com/yunionio/cloudpods/assets/20243864/67f364d2-637f-4c06-b04b-02b2ef4de0af)

**Comment by ninghongwu** [comment]
今天刚添加华为云，等了很久都不显示套餐，只有阿里云能显示套餐

**Comment by chenshushan** [comment]
好的  已经解决了
