### ISSUE TITLE
[求助/Help]zstack纳管后，虚拟机的IP被提示“该IP地址无归属IP子网！请添加包含该IP地址的IP子网并重新同步云账号”

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#17353]
我有一个私有云Zstack，是扁平网络，添加到cloudpods后有这类警告。我删除zstack，提前创建了ip子网，重新添加还是会出现，请帮忙看下，感谢！
<img width="853" alt="1687336194859" src="https://github.com/yunionio/cloudpods/assets/59357035/74648937-e15a-4644-a852-3a66c4bbaf1d">

**Comment by ninghongwu** [comment]
<img width="521" alt="1687336711223" src="https://github.com/yunionio/cloudpods/assets/59357035/b37b191d-1e79-49d3-8be2-d5c8c0ef0278">

**Comment by hoganlxj** [comment]
@ninghongwu  问题排查步骤
1.先看下IP子网菜单中 按平台为zstack过滤，看是否有上述虚拟机的IP子网
2.若果没有，可以在云账号菜单那里，全量同步试下

**Comment by ninghongwu** [comment]
@hoganlxj 你好，我添加zstack后，会生成很多zstack相关的子网，但是就是有红色叹号的警告

**Comment by hoganlxj** [comment]
@ninghongwu 我们本地测试下

**Comment by ioito** [comment]
close #17370

**Comment by ninghongwu** [comment]
@ioito 好的，修复后麻烦给个消息，非常感谢

**Comment by zexi** [comment]
> @ioito 好的，修复后麻烦给个消息，非常感谢

@ninghongwu 代码已经合并了，可以用下面的命令单独更新 region 服务后再同步试试：

```bash
kubectl set image -n onecloud deploy/default-region *=registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-0627.0
```

**Comment by ninghongwu** [comment]
好的，我更新镜像试试

**Comment by ninghongwu** [comment]
可以了，感谢
