### ISSUE TITLE
对接proxmox，想在proxmox 上创建虚拟机，无法选择套餐

### ISSUE THREAD

**Issue by jinteng123** [yunionio/cloudpods#17359]
![图片](https://github.com/yunionio/cloudpods/assets/22409094/a9e253e3-5cd3-49a8-bdac-cdf749bf881f)

**Comment by jackgao2015** [comment]
最新版本的cloudpods对pve的纳管还处于只读的状态，也就是说只能同步pve的信息，还不能基于cloudpods创建pve的资源。
pve的写操作现在正在开发中。

**Comment by huashu2019** [comment]
啥时候能支持操作以及其它高级管理就好了，proxmox开源，同时稳定性很好。

**Comment by jackgao2015** [comment]
> 啥时候能支持操作以及其它高级管理就好了，proxmox开源，同时稳定性很好。

v3.11，不过v3.11的release时间待定

**Comment by jackgao2015** [comment]
留意一下官方公众号的发布信息

**Comment by ioito** [comment]
创建操作将在 https://github.com/yunionio/cloudpods/pull/17410 合并后支持
