### ISSUE TITLE
[求助/Help]负载均衡里面没有集群的选项

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17360]
大家好
使用 [Docker Compose](https://docs.docker.com/compose/) 快速部署 Cloudpods CMP 多云管理版本部署的，但是在负载均衡里面没有集群的选项，请问这个部署方式是没有这个功能吗
![image](https://github.com/yunionio/cloudpods/assets/32296103/8da55d41-58be-4fb2-bf0b-d9f2b9728f66)

**Comment by hoganlxj** [comment]
@shengxianli 是的。如果想用内置私有云，可以换成all in one的安装方式部署 https://www.cloudpods.org/zh/docs/quickstart/allinone/

**Comment by shengxianli** [comment]
> @shengxianli 是的。如果想用内置私有云，可以换成all in one的安装方式部署 https://www.cloudpods.org/zh/docs/quickstart/allinone/

谢谢回复。如果管理的都是VMware的机器，也可以吗，还是必须使用原生的Cloudpods

**Comment by hoganlxj** [comment]
> > @shengxianli 是的。如果想用内置私有云，可以换成all in one的安装方式部署 https://www.cloudpods.org/zh/docs/quickstart/allinone/
> 
> 谢谢回复。如果管理的都是VMware的机器，也可以吗，还是必须使用原生的Cloudpods

可以使用Docker  compose 快速部署的多云管理平台 管理VMware
