### ISSUE TITLE
[文档/Docs] 文档中心下方反馈链接失效

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#17365]
url： https://www.cloudpods.cn/zh/docs/web_ui/computing/server/servertemplate/
>Sorry to hear that. Please tell us how we can improve.
> 指向的地址是：https://github.com/yunionio/docs/issues/new

这个仓库关闭了issue，返回404，可能需要修改链接引导到这个仓库？

**Comment by zexi** [comment]
> url： https://www.cloudpods.cn/zh/docs/web_ui/computing/server/servertemplate/
> 
> > Sorry to hear that. Please tell us how we can improve.
> > 指向的地址是：https://github.com/yunionio/docs/issues/new
> 
> 这个仓库关闭了issue，返回404，可能需要修改链接引导到这个仓库？

@fangpsh 你好，感谢反馈，应该是你那边访问到旧的文档页面了，我们排查下。
新的文档应该是提交问题应该是直接跳转到: https://github.com/yunionio/cloudpods/issues/new?title=[Docs]%20%e7%bb%84%e4%bb%b6%e6%a6%82%e8%a7%88

**Comment by zexi** [comment]
@fangpsh 哦，我知道了，你访问的是 https://www.cloudpods.cn ，内容很久了，请用 https://www.cloudpods.org 访问文档。

**Comment by zexi** [comment]
https://www.cloudpods.cn/ 的内容也更新了
