### ISSUE TITLE
[BUG] 删除硬盘快照这儿是不是有bug啊

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17375]
在删除快照时云平台已经将快照删除了。但状态一直是删除中，最后报错，我以为是我写的代码问题，但openstack也存在同样的问题
<img width="877" alt="dc43a98c8e114bf2f801bfa588e6f41" src="https://github.com/yunionio/cloudpods/assets/29140975/4a695d19-70a7-45fd-a8e4-6d7b49879452">

**Comment by ioito** [comment]
Closed #17377 

@hewenxiang 将在上面的pr合并后修复

**Comment by zexi** [comment]
@hewenxiang 代码已经合并了，可以用下面的命令单独更新 region 服务后再同步试试：

```bash
kubectl set image -n onecloud deploy/default-region *=registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-0627.0
```

或者你自己更新代码打包也可以，参考文档：https://www.cloudpods.org/zh/docs/development/dev-env/#docker-%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91%E4%B8%8A%E4%BC%A0
