### ISSUE TITLE
[求助/Help]在创建快照等类似操作遇到的状态更新问题

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17376]
在创建快照代码执行完后有一个状态等态的代码 。但传入的状态是固定的值，不会再改变，那个这个等待一直到时间才结束，实际上在云平台资源已经创建成功了
以腾讯云代码为例
![image](https://github.com/yunionio/cloudpods/assets/29140975/b3a82a23-c314-439c-8b75-f4f2cd2c1d35)

这儿的snapshot状态值如果不是ready，那么就一直等待
山河云的快照创建时的初始值是pending,创建成功会变成available，所以如果才用同样的代码结构来操作的话这个等待一直到时间才结束。不知道其他云是也有这样的问题

**Comment by ioito** [comment]
需要实现快照的Refresh方法，在此方法里面更新下自身的状态
