### ISSUE TITLE
[求助/Help]纳管zstack具有哪些功能

### ISSUE THREAD

**Issue by huashu2019** [yunionio/cloudpods#17388]
纳管zstack具有哪些功能：
比如，能否能过cloudpods直接创建虚拟机，管理虚拟机以及删除等功能

**Comment by dengju2020** [comment]
@huashu2019 zstack对接是全功能的，支持资源纳管、新建及操作。

**Comment by zexi** [comment]
@huashu2019 
这里有支持的云平台功能支持情况列表可以参考：
https://www.cloudpods.org/zh/docs/function_principle/multicloud/

**Comment by jackgao2015** [comment]
> 纳管zstack具有哪些功能： 比如，能否能过cloudpods直接创建虚拟机，管理虚拟机以及删除等功能

@huashu2019 我看你最近提了好些issue，如果某些issue已经解决了，请顺手关闭哈，养成良好的习惯。这样我们可以把时间和精力留给那些没有解决的issue
