### ISSUE TITLE
[求助/Help]v3.9.8企业版本如何切换到开源版本

### ISSUE THREAD

**Issue by xiaoyuyun2016** [yunionio/cloudpods#17383]
# 切换到开源版的 web 前端
$ python3 ocboot.py ce <IP> 此命令无效。

**Comment by zexi** [comment]
@xiaoyuyun2016 另外可以用旧的切换办法试试：
https://www.cloudpods.org/v3.8/zh/docs/setup/ce-ee-switch/

**Comment by xiaoyuyun2016** [comment]
https://www.cloudpods.org/v3.8/zh/docs/setup/ce-ee-switch/

**Comment by jackgao2015** [comment]
> https://www.cloudpods.org/v3.8/zh/docs/setup/ce-ee-switch/

用这个解决了是吧？

**Comment by xiaoyuyun2016** [comment]
> > https://www.cloudpods.org/v3.8/zh/docs/setup/ce-ee-switch/
> 
> 用这个解决了是吧？

https://www.cloudpods.org/v3.8/zh/docs/setup/ce-ee-switch/这个可以解决，已经解决了。
