### ISSUE TITLE
[BUG] 高可用部署后glance crash

### ISSUE THREAD

**Issue by ghost** [yunionio/cloudpods#17381]
**问题描述/What happened**:

![image](https://github.com/yunionio/cloudpods/assets/31299373/ff873009-7f4c-437f-a5bd-926ee517d1c2)

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):centos7
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ruifl** [comment]
> @ruifl 有改过/etc/resolv.conf 文件没？ 然后 执行 kubectl rollout restart deployment -n kube-system coredns 再看下

没有改动，完全是按照http://docs-os.yunion.cn/zh/docs/setup/ha-ce/ 这个来的，请问/etc/resolv 中要加什么？

**Comment by ruifl** [comment]
另外cm 中配置是这样的
![image](https://github.com/yunionio/cloudpods/assets/31299373/15e160f1-639b-4502-98b0-844387eaa691)
，不是用本地存储吗？

**Comment by ruifaling** [comment]
部署完后并没有看到有minio的服务，这个需要自己单独部署，不在部署脚本里？

**Comment by zexi** [comment]
> 部署完后并没有看到有minio的服务，这个需要自己单独部署，不在部署脚本里？

@ruifaling minio 是会自动部署的，麻烦执行下面命令看下 minio pod 的运行状态：

```bash
kubectl get pods -n onecloud-minio
```

**Comment by ruifaling** [comment]
> > 部署完后并没有看到有minio的服务，这个需要自己单独部署，不在部署脚本里？
> 
> @ruifaling minio 是会自动部署的，麻烦执行下面命令看下 minio pod 的运行状态：
> 
> ```shell
> kubectl get pods -n onecloud-minio
> ```

没有，ns, deployment都没有创建 @zexi

**Comment by ruifaling** [comment]
而且，可以看到onecluster的cr中是spec是minio是enable,
![image](https://github.com/yunionio/cloudpods/assets/79310393/3d055660-3ad8-4e44-93de-0f430a19bde6)
但是status中没有找到minio
![image](https://github.com/yunionio/cloudpods/assets/79310393/6c97d826-a946-4b68-87d2-0a078ad05e91)

**Comment by ruifaling** [comment]
operator的日志 里有 
![image](https://github.com/yunionio/cloudpods/assets/79310393/12755e88-f75b-4b7a-a0b4-0561780efd9c)

**Comment by zexi** [comment]
> operator的日志 里有 ![image](https://user-images.githubusercontent.com/79310393/249371545-12755e88-f75b-4b7a-a0b4-0561780efd9c.png)

@ruifaling 这个是 kubeserver 部署 minio 失败的日志，可以用下面的方法先删除下 minio 的部署，等 operator 再部署试试：

```bash
# 查看下组件的状态，估计 minio 会是 undeploy_fail 的状态
climc k8s-cluster-components-status system-default

# 删除后试试
climc k8s-cluster-component-delete system-default minio
```

等5分钟左右，operator 会重新请求 kubeserver 创建 minio 组件，如果还是不行，麻烦把 kubeserver pod 服务的日志发出来看下。

**Comment by zexi** [comment]
![image](https://github.com/yunionio/cloudpods/assets/10767027/1909519c-08eb-420a-b45d-0b764e1454e6)
@ruifaling 这个是你提供的日志截图，感觉是 kubeserver 有 bug ，可以用下面的命令重启下 kubeserver 再删除 minio 试试：

```bash
kubectl rollout restart deployment -n onecloud default-kubeserver
```

另外请提供下部署的 kubeserver 版本，我记得好像修复过类似的 bug ，这个是获取版本的命令：

```bash
kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list
```

**Comment by ruifaling** [comment]
![image](https://github.com/yunionio/cloudpods/assets/79310393/e66384bc-a811-4f24-9842-0fa1313786bb)
@zexi 
没有kubeserver呢
另外我看到 cluster-info 这个configmap中的uid不是日志中的id,他俩是否应保持一致

**Comment by ruifaling** [comment]
重启kubeserver后minio 装上了，但是glance 还是报错
![image](https://github.com/yunionio/cloudpods/assets/79310393/eaec7eb1-6d99-440c-bedf-42bef223aa67)

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/79310393/249652138-e66384bc-a811-4f24-9842-0fa1313786bb.png) @zexi 没有kubeserver呢 另外我看到 cluster-info 这个configmap中的uid不是日志中的id,他俩是否应保持一致

@ruifaling 这两个 id 没有关系，那个报错是说没有找到 system-default 集群对应的 id

**Comment by zexi** [comment]
> 重启kubeserver后minio 装上了，但是glance 还是报错 ![image](https://user-images.githubusercontent.com/79310393/249653119-eaec7eb1-6d99-440c-bedf-42bef223aa67.png)

@ruifaling 那个报错好像和镜像上传没有关系，现在试试看能否成功上传虚拟机镜像？

**Comment by ruifaling** [comment]
![image](https://github.com/yunionio/cloudpods/assets/79310393/29161692-c8f2-4d02-9b43-1b7f54dd9c62)

**Comment by ruifaling** [comment]
而且总是中断

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/79310393/249654282-29161692-c8f2-4d02-9b43-1b7f54dd9c62.png)

@ruifaling 试试直接到控制节点上用命令行能否上传镜像成功？上传镜像的命令行操作参考这个文档：https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/upload/

如果命令行也上传失败，麻烦把 glance 服务的日志导出来看下

**Comment by ruifaling** [comment]
命令行上传成功

**Comment by ruifaling** [comment]
页面中断的后台也没有什么报错 @zexi

**Comment by zexi** [comment]
> 页面中断的后台也没有什么报错 @zexi

@ruifaling 有可能和这个是一样的问题：https://github.com/yunionio/cloudpods/issues/17318#issuecomment-1594508425

可以按照这个 issue 里面的解决办法设置下内核参数，然后再从前端上传镜像试试。
因为前端上传镜像的路径是 nginx -> apigateway -> glance ，路径较长，前面环节出错可能还没有到 glance 服务那里；
命令行上传是直接和 glance 服务通信的，如果命令行上传没有问题，能证明 glance 服务连接 minio 的路径是没有问题了。

**Comment by ruifaling** [comment]
问题解决，谢谢！

/close
