### ISSUE TITLE
[求助/Help]Cloudpods虚拟机支持超融合方式吗？

### ISSUE THREAD

**Issue by huashu2019** [yunionio/cloudpods#17389]
让kvm虚拟机，同时又是ceph
实现超融合，减少成本预算

**Comment by jackgao2015** [comment]
从我的角度讲，cloudpods不适合做超融合这种场景，cloudpods的底层架构更适合集群模式。
@swordqiu 有什么补充么？

**Comment by jackgao2015** [comment]
@swordqiu 剑哥，你来回答吧

**Comment by swordqiu** [comment]
可以参考这个博客：https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/

在cloudpods的底座k8s上部署rook-ceph来实现超融合。

**Comment by huashu2019** [comment]
宿主机 同时安装 kvm+k8s 来实现超融合？

**Comment by huashu2019** [comment]
同时实现  Kubernetes 集群？

**Comment by zexi** [comment]
> 同时实现 Kubernetes 集群？

@huashu2019 Cloudpods 服务以容器化的方式运行在 Kubernetes 集群之上，按照 [部署文档/多节点安装](https://www.cloudpods.org/zh/docs/quickstart/nodes/) 文档部署完 Cloudpods 之后，环境就有了一个完整的 Kubernetes 集群。

**Comment by zexi** [comment]
> > 同时实现 Kubernetes 集群？
> 
> @huashu2019 Cloudpods 服务以容器化的方式运行在 Kubernetes 集群之上，按照 [部署文档/多节点安装](https://www.cloudpods.org/zh/docs/setup/nodes/) 文档部署完 Cloudpods 之后，环境就有了一个完整的 Kubernetes 集群。

**Comment by charnet1019** [comment]
> 可以参考这个博客：https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/
> 
> 在cloudpods的底座k8s上部署rook-ceph来实现超融合。

如果按这个方案部署超融合集群，那么集群自有的管理数据库是否可以以容器化的方式运行呢？

**Comment by zexi** [comment]
> > 可以参考这个博客：https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/
> > 在cloudpods的底座k8s上部署rook-ceph来实现超融合。
> 
> 如果按这个方案部署超融合集群，那么集群自有的管理数据库是否可以以容器化的方式运行呢？

@charnet1019 数据库可以容器化运行，但生产环境并不建议这么使用。目前 docker compose 部署的测试环境就是把 mariadb 运行在容器里面的，可以参考代码：https://github.com/yunionio/ocboot/blob/master/compose/docker-compose.yml#L3-L18
