### ISSUE TITLE
[求助/Help]管理员没有普通项目的权限么？

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17382]
<img width="941" alt="image" src="https://github.com/yunionio/cloudpods/assets/11387540/54b4d801-0a94-4de0-b50a-3bc21fb3b4e8">

**Comment by jackgao2015** [comment]
你看一下这个用户在这个项目下的权限，可能需要管理员看

**Comment by yangqingwen666** [comment]
是从管理员切换到普通用户吗？切换的时候停留的页面（比如认证与安全的权限）是普通用户看不了的就会报权限不足

**Comment by jackgao2015** [comment]
切换到管理后台，看一下这个用户在你刚才那个项目里面什么权限

**Comment by ninghongwu** [comment]
这户是自带的admin用户，刚才加了MFA，重新登录好像就没普通项目钉权限了

<img width="740" alt="1687853797925" src="https://github.com/yunionio/cloudpods/assets/59357035/22d4dcb8-6428-4715-97b1-4bcc61cec9ea">

**Comment by jackgao2015** [comment]
@yangqingwen666 咱们复现一下吧，看看是不是有bug

**Comment by yangqingwen666** [comment]
@ninghongwu 是所有功能都不能使用了吗？

**Comment by yangqingwen666** [comment]
@ninghongwu 第一张图上显示所在项目是Huawei，但是看第二张图片，确实是加入了Huawei项目，但是没有分配权限，所以没有权限，你可以使用图上那个system项目/给项目的用户角色添加权限（比如给Huawei这个项目的admin角色添加sysadmin权限）

**Comment by jackgao2015** [comment]
> 这户是自带的admin用户，刚才加了MFA，重新登录好像就没普通项目钉权限了
> 
> <img alt="1687853797925" width="740" src="https://user-images.githubusercontent.com/59357035/249083163-22d4dcb8-6428-4715-97b1-4bcc61cec9ea.png">

你给这个用户在其他项目中都加上权限，你再切换一下呢？我感觉就是没有给授权，这个用户如你截图所示，在切换到其他的项目时，是没有权限的，所以报了权限不足。
你试一下？

**Comment by jackgao2015** [comment]
sysadmin的权限只有在system才有意义，你给这些用户改一下其他的角色，比如project_owner，就可以解决那个问题了。

**Comment by ninghongwu** [comment]
我看过admin角色是有sysadmin(任意)权限的，是最高权限了，等我加上其他权限再看看

**Comment by dengju2020** [comment]
> 我看过admin角色是有sysadmin(任意)权限的，是最高权限了，等我加上其他权限再看看

@ninghongwu  admin是管理员权限，用户可以在管理后台管理所有资源。但是如果要单独进入某个项目进行管理，需要单独授权。具体介绍可以看下文档：https://www.cloudpods.org/zh/docs/function_principle/auth_security/iam/principle/project/

**Comment by ninghongwu** [comment]
了解了，感谢
