### ISSUE TITLE
[求助/Help]逻辑上多region实现资源调度，而非采用纳管cloudpods方案的可行性

### ISSUE THREAD

**Issue by enhellowhy** [yunionio/cloudpods#17398]
如果不通过纳管cloudpods其他集群，只想通过一个集群实现逻辑上区分region的方案可行么？现在已经在后台新建一个region，这样会有什么影响么？

**Comment by jackgao2015** [comment]
一个region，多个zone，这种架构是支持的

**Comment by jackgao2015** [comment]
@swordqiu 有需要补充的么？

**Comment by jackgao2015** [comment]
目前还是推荐使用部署多套控制节点，然后使用cloudpods进行纳管。
