### ISSUE TITLE
[求助/Help]cloudpods是否支持多节点裸金属服务器管理

### ISSUE THREAD

**Issue by huashu2019** [yunionio/cloudpods#17393]
比如通过cloudpods管理，广州机房、上海机房、北京机房，同时实时三地裸金属服务器以及私有云？

**Comment by jackgao2015** [comment]
可以在广州机房、上海机房、北京机房各部署一套cloudpods做私有云平台，然后另外在部署一台作为多云管理平台，这种是可以的实现的。

多云管理
--广州私有云
--上海私有云
--北京私有云

这种是否能解答你的问题？

**Comment by huashu2019** [comment]
实际上就相当于3套cloudpods，谢谢
