### ISSUE TITLE
[BUG]虚机调整配置一个接口报错

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17394]
**问题描述/What happened**:

**环境/Environment**:
v3.10.1
没有这个接口或是什么问题，报500 /api/v1/cloud_sku_rates
![image](https://github.com/yunionio/cloudpods/assets/29140975/0dcf2580-05cd-41e9-81d8-52de10e00765)

**Comment by hoganlxj** [comment]
@hewenxiang 这个问题已经在v3.10.2修复，可以升级到v3.10.2版本。具体升级步骤参考
https://www.cloudpods.org/zh/docs/setup/upgrade/#%E5%8D%87%E7%BA%A7-cloudpods-%E6%9C%8D%E5%8A%A1
