### ISSUE TITLE
宿主机网卡mac地址不对导致服务离线

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#17391]
我们一台宿主机在发生重启后，网卡的mac地址与cloudpods记录的mac地址不一致，导致 host pod报错，请问有办法修改cloudpods的mac地址记录吗？
![image](https://github.com/yunionio/cloudpods/assets/17080656/3204e012-b028-45ba-8af7-2c2fa390ae32)
![image](https://github.com/yunionio/cloudpods/assets/17080656/5c4eecb3-edfd-4617-80db-0f6f0f45ec80)
![image](https://github.com/yunionio/cloudpods/assets/17080656/3220d463-d907-4721-a189-f0dc58d2991c)

**Comment by tianchao001** [comment]
这台宿主机之前有两张网卡被分配了dhcp，导致虚拟机无法创建成功，后来手动删除了一张无效网卡记录，一切恢复正常，但是在宿主机重启后，貌似记录的mac 和真正分配到IP的mac地址并不匹配。

**Comment by zexi** [comment]
> 我们一台宿主机在发生重启后，网卡的mac地址与cloudpods记录的mac地址不一致，导致 host pod报错，请问有办法修改cloudpods的mac地址记录吗？ ![image](https://user-images.githubusercontent.com/17080656/249330604-3204e012-b028-45ba-8af7-2c2fa390ae32.png) ![image](https://user-images.githubusercontent.com/17080656/249330769-5c4eecb3-edfd-4617-80db-0f6f0f45ec80.png) ![image](https://user-images.githubusercontent.com/17080656/249330985-3220d463-d907-4721-a189-f0dc58d2991c.png)

@tianchao001 可以通过使用climc命令来修改cloudpods的mac地址记录。可以参考文档：https://www.cloudpods.org/zh/docs/ops/hosterror/#%E5%AE%BF%E4%B8%BB%E6%9C%BAmac%E6%94%B9%E5%8F%98%E4%BC%9A%E5%AF%BC%E8%87%B4host%E6%9C%8D%E5%8A%A1%E7%A6%BB%E7%BA%BF%E9%9C%80%E8%A6%81%E6%9B%B4%E6%94%B9%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%9C%A8%E5%B9%B3%E5%8F%B0%E6%B3%A8%E5%86%8C%E7%9A%84mac%E5%9C%B0%E5%9D%80%E5%85%B7%E4%BD%93%E6%AD%A5%E9%AA%A4%E5%A6%82%E4%B8%8B。
