### ISSUE TITLE
[求助/Help]cloudpods私有云，支持自有数据库、负载均衡创建开通吗？

### ISSUE THREAD

**Issue by huashu2019** [yunionio/cloudpods#17390]
即然是私有云，肯定会设计到自有数据库以及负载均衡系统
通过界面还无法看出是否支持

如果支持应该怎么配置

**Comment by zexi** [comment]
@huashu2019 这里有负载均衡 LBAgent 的部署文档：https://www.cloudpods.org/zh/docs/function_principle/onpremise/lb/lbagent/ ，部署完 LBAgent 后，就可以使用负载均衡系统了。
使用的方式是到前端创建负载均衡集群：https://www.cloudpods.org/zh/docs/web_ui/network/lbcluster/lbcluster/
然后创建负载均衡均衡实例：https://www.cloudpods.org/zh/docs/web_ui/network/lb/

另外自建数据库(RDS) 目前不支持，只支持管理公有云的 RDS 数据库。

**Comment by huashu2019** [comment]
期待你们未来能够支持自建RDS
