### ISSUE TITLE
[求助/Help]可以把业务表格组件开源吗

### ISSUE THREAD

**Issue by thclouds** [yunionio/cloudpods#17409]
整体表格组件，带搜索、分页这些，整体做出一个业务表格开源出来
![image](https://github.com/yunionio/cloudpods/assets/85913244/75ee8f96-fe66-4164-9d7d-8d1b20a7faf2)

**Comment by thclouds** [comment]
这个表格非常棒

**Comment by jackgao2015** [comment]
之前也有人提过这个需求 https://github.com/yunionio/cloudpods/issues/17107
@easy-mj 要不咱们考虑考虑

**Comment by thclouds** [comment]
一般的表格组件带的搜索都比较难看且占空间，你们这种形式比较好，现在阿里云、腾讯云、华为云都用这种形式

**Comment by jackgao2015** [comment]
> 一般的表格组件带的搜索都比较难看且占空间，你们这种形式比较好，现在阿里云、腾讯云、华为云都用这种形式

@thclouds 好的好的，我们考虑一下

**Comment by noday** [comment]
请问有计划吗
