### ISSUE TITLE
[求助/Help]本地IDC（Vcenter）创建的虚拟机使用“ssh ${IP}”方式进行远程连接时，报500错误，怎么定位和解决问题？

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17408]
![image](https://github.com/yunionio/cloudpods/assets/11387540/5468c04e-dc0f-46a4-820c-862e9418e43b)

**Comment by hoganlxj** [comment]
看下web的服务是否正常，登陆部署cloudpods的服务器上，执行kubectl get pods -n onecloud |grep web 看下

**Comment by sixintadi** [comment]
这个服务正常，日志显示正常。
![image](https://github.com/yunionio/cloudpods/assets/77439317/33702127-ed53-4941-b1a3-18f97e765bd8)

**Comment by ioito** [comment]
需要看有关web-console相关的日志 @sixintadi 
执行以下命令，同时再进行ssh远程连接
kubectl logs -n onecloud default-web-xxxx web --tail 10 -f | grep web-console

**Comment by sixintadi** [comment]
![image](https://github.com/yunionio/cloudpods/assets/77439317/61bd25a5-3c41-4421-80ea-a6444439264e)

**Comment by sixintadi** [comment]
500的错误解决了，访问web域名和后台设置的不一致导致的；现在出现下面这个问题
![image](https://github.com/yunionio/cloudpods/assets/77439317/3d594ef9-6996-438a-abb9-6ff70386f889)

**Comment by sixintadi** [comment]
后面的问题也解决了，自己好了

**Comment by sixintadi** [comment]
补充说明：第一个问题ssh登录报500错误，需要在下面这个地方进行全局web访问设置为安装后台服务时，配置的ingress地址。
![image](https://github.com/yunionio/cloudpods/assets/77439317/ecff8df4-7152-4173-8ae5-ca2f006a9add)

**Comment by zexi** [comment]
> 补充说明：第一个问题ssh登录报500错误，需要在下面这个地方进行全局web访问设置为安装后台服务时，配置的ingress地址。 ![image](https://user-images.githubusercontent.com/77439317/250038794-ecff8df4-7152-4173-8ae5-ca2f006a9add.png)

@sixintadi 感谢补充
