### ISSUE TITLE
[求助/Help] 高可用部署后，导入openstack时连接成功，同步资源时连不上

### ISSUE THREAD

**Issue by ruifaling** [yunionio/cloudpods#17422]
![image](https://github.com/yunionio/cloudpods/assets/79310393/9e6d92e5-6679-48ef-a182-dcdccee9f0ad)
如图，高可用部署后块存储没有创建按钮导致导入openstack账号后无法使用

**Comment by ruifaling** [comment]
用的部署默认创建的admin 用户，在peimissions接口中看到所有storage相关的权限都是allow
![image](https://github.com/yunionio/cloudpods/assets/79310393/57104576-d488-447d-b373-0f7cf298b6fc)

**Comment by ioito** [comment]
openstack云账号导入后，不需要在cloudpods新建存储, 是依赖于openstack中的volume type https://docs.openstack.org/python-openstackclient/queens/cli/command-objects/volume-type.html
请在openstack环境创建相应的存储类型，然后同步完openstack账号就可以在cloudpods上看到对应的存储，改下存储可用大小就可以正常使用

**Comment by ruifaling** [comment]
openstack环境上有存储类型，但是同步完还是啥都没有 @ioito

**Comment by ruifaling** [comment]
@ioito  导入云账号的连接成功，但是同步资源的时候有连不上，这是为啥呢
![image](https://github.com/yunionio/cloudpods/assets/79310393/fc99ecde-5220-4b97-8ff2-27fbbfbc234c)

**Comment by ruifaling** [comment]
配置coredns后问题解决

/close
