### ISSUE TITLE
[文档/Docs] 用户反馈安装中的 mariadb 版本不准确

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#17438]
**What part of the document needs to be added**:

文档中写明：
”在公有云上部署环境时，建议部署Mariadb数据库，不要使用mysql 5.6及以下版本，防止索引长度 bug： Index column size too large. The maximum column size is 767 bytes.“

但是教程是直接 yum install -y mariadb-server，当前仓库里面的是5.5.68。

ansible 和文档中都没锁定和指明版本：
![80191688378500_ pic](https://github.com/yunionio/cloudpods/assets/10767027/f4210ab3-d30c-4530-954d-2e3168f04524)
![80201688378500_ pic](https://github.com/yunionio/cloudpods/assets/10767027/231d586a-9751-43cf-ada2-b2118d1ebfde)

debian10 装的是10.x ？
centos 是5.5.x？

<img width="1066" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/11a2d819-557e-4446-aa2c-67c6f0b66dc7">

我手里没debian 的机器，那如果在云上的话，rds，用户应该选mysql 5.7 还是mariadb 10.3 呢？

**Comment by hoganlxj** [comment]
https://github.com/yunionio/docs/pull/1563/commits/8343e4735784e43b672e8de33c1f8914e707196d

**Comment by fangpsh** [comment]
@hoganlxj 文档中写明：
”在公有云上部署环境时，建议部署Mariadb数据库，不要使用mysql 5.6及以下版本，防止索引长度 bug： Index column size too large. The maximum column size is 767 bytes.“
但是centos7 环境默认装上的版本是5.5.68，可能会存在上面这个问题吗？

**Comment by zexi** [comment]
> @hoganlxj 文档中写明： ”在公有云上部署环境时，建议部署Mariadb数据库，不要使用mysql 5.6及以下版本，防止索引长度 bug： Index column size too large. The maximum column size is 767 bytes.“ 但是centos7 环境默认装上的版本是5.5.68，可能会存在上面这个问题吗？

@fangpsh centos7 上建议都部署 mariadb ，我们没有在 centos 上测试过 mysql

**Comment by fangpsh** [comment]
@zexi 明白了，是我混淆了mariadb 版本和mysqld 版本。
