### ISSUE TITLE
[Feature]请问是否有计划支持联通云

### ISSUE THREAD

**Issue by ziisp** [yunionio/cloudpods#17436]
**What would you like to be added**:
目前用联通云的用户也不少了，是否有计划支持联通云

**Comment by ioito** [comment]
近期没有支持联通云的计划，若你有需求，可以根据文档 https://www.cloudpods.org/zh/docs/development/resource_sync/add-cloud/ 
自行进行二次开发对接

**Comment by ioito** [comment]
@ziisp  以下pr是增加联通云账号导入，具体资源管理，可以根据以上开发文档进行对接，贡献开源
https://github.com/yunionio/cloudpods/pull/17742/files
