### ISSUE TITLE
[文档/Docs] 能否出一期双网卡(宿主机外网内网)配置EIP的视频

### ISSUE THREAD

**Issue by dard777** [yunionio/cloudpods#17432]
EIP设置文档看了几遍有些没看明白， 能否出一期宿主机双网卡内外网配置EIP的视频？
多谢了，产品非常好。 要是能把私有云相关单独从多云纳管里剥离出来就更完美了。

**Comment by zexi** [comment]
@dard777 感谢建议，私有云和云管功能分别部署这个正在做，也有用户提过相同的问题：https://github.com/yunionio/cloudpods/issues/17413

**Comment by zexi** [comment]
@dard777 https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/vpc/eipgwhowto/ 这个是 eip 网关部署的文档，可以具体说下哪个部分不明白吗？

**Comment by dard777** [comment]
> @dard777 https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/vpc/eipgwhowto/ 这个是 eip 网关部署的文档，可以具体说下哪个部分不明白吗？

我们有一些不是太懂网络方面的，看了这部分文档，还是有点不太明白。 所以希望能出一份这方面的视频。 
实际场景我们在机房购买一台裸机，机房给了多个公有ip地址。 我们就希望能部署咱们cloudpods来进行私有云建设。
希望能把多的公有地址能绑定到虚拟机里， 能和宿主机的公网内网网络相通。  还有就是多个计算节点连起来后， 每台计算节点有几十个公有ip，我要怎么才能利用起来做eip。

**Comment by cnjack** [comment]
我也有类似的需求

**Comment by cnjack** [comment]
@dard777 朋友你搞定了吗？
