### ISSUE TITLE
[求助/Help]ovf/ova格式镜像问题

### ISSUE THREAD

**Issue by cnsunfocus** [yunionio/cloudpods#17439]
cloudpod 版本3.10.2  虚机allinone部署

有几台vmware 6.5上的虚机需要迁移,  做了以下几种尝试.

1.  cloudpod 接入vmware后, 在虚机上选择 "保存镜像" ,  等待一段时间后, vmware提示已完成, cloudpod侧的镜像保存成功, 但创建虚机时, 如果手动输入密码, 则提示错误, 如果使用镜像设置, 则错误同场景2
![image](https://github.com/yunionio/cloudpods/assets/3301715/bcd8d7d9-b5f3-4678-bebc-765fd166d34d)

<img width="599" alt="1688382086347" src="https://github.com/yunionio/cloudpods/assets/3301715/a4c95025-7938-4a82-8234-9880ebb182b2">

2. 手工在vmware上导入ovf模板并下载文件, 然后上传至cloudpod,并使用该镜像创建虚机, 结果是无法启动, 看提示是找不到正确的分区..

<img width="1046" alt="ee1edeaf6afdfd14bf84b2bf5f32daa" src="https://github.com/yunionio/cloudpods/assets/3301715/9edf1801-0f96-40f0-9ead-5bf5423bfaa2">

3. 创建主机镜像,   参考 文档种的命令, 此处使用的镜像为前两步中生成的系统镜像, 测试了两次
climc guest-image-create ovfhostimage --image   61e538b1-28b6-4d22-8c10-0f10fcae461c
创建后主机镜像正常生成, 但使用该镜像创建虚机后, 结果同第二步. 

<img width="872" alt="1688382613580" src="https://github.com/yunionio/cloudpods/assets/3301715/4aed1b80-8864-4507-8227-c6126a3da1a3">

另外文档中对ova处理的这一句如何理解?
<img width="682" alt="1688382655094" src="https://github.com/yunionio/cloudpods/assets/3301715/87ef876a-5479-4f25-8d1f-18975e6203c8">

4. 又补充了一个场景,  导出了ova格式文件, 创建虚机后提示no boot disk.......
![image](https://github.com/yunionio/cloudpods/assets/3301715/68ed4a74-b994-48f8-bdd1-97f71cfcc988)

**Comment by swordqiu** [comment]
感觉是因为这台主机用了跨多个盘的LVM，导致镜像初始化的时候，无法挂载磁盘进行初始化。

可以试下按第三步的方式，把ova分为多个vmdk导入，并且组合成主机镜像，再基于主机镜像创建主机。

把上传的多个vmdk镜像组合成主机镜像的方法为：

使用climc命令如下：

```bash
climc guest-image-create <name_of_guest_image> --image <id_of_image_1> --image <id_of_image_2> ...
```

例如：

```bash
climc guest-image-create centos6x-20230703 --image 28dfad71-d7b7-47dc-83f9-b8799ff0673d --image 0d8124be-3134-40f4-8d08-48571ac50a6a
```

**Comment by swordqiu** [comment]
@cnsunfocus

**Comment by cnsunfocus** [comment]
@swordqiu 感觉是分区表不对, 但这台虚机只有一个vmdk文件, 特意挑了个简单的虚机.  刚试了下qemu-img转成qcow2也是同样的问题, 和方式2结果一样.

**Comment by swordqiu** [comment]
会不会是initramfs包含驱动的原因？试下把磁盘驱动改为 ide 启动呢？前端在虚拟机详情磁盘列表可以已设置，后端可以用

```bash
climc server-disk-update --server <sid> --disk <diskid> --driver ide
```

**Comment by cnsunfocus** [comment]
改成ide可以了, 感谢
我再多测试一下
