### ISSUE TITLE
[求助/Help]添加裸金属服务器硬盘无法选择,

### ISSUE THREAD

**Issue by zhengkun19971003** [yunionio/cloudpods#17433]
![image](https://github.com/yunionio/cloudpods/assets/113098805/d2d20c61-768e-4b6a-8b49-009b0e59d9db)
  添加裸金属服务器，发现硬盘点不动

**Comment by zexi** [comment]
@zhengkun19971003 应该是硬盘没有探测到，可以ssh到物理机上，执行 /lib/mos/lsdisk 脚本看下，步骤如下：

climc host-ssh 物理机名称
/lib/mos/lsdisk

**Comment by zexi** [comment]
后面发现是宝德的服务器，用户选了 iso 引导，但宝德的机器不支持 iso 引导，所以进入 yunionos 系统失败了，选择 pxe 引导成功。
<img width="951" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/a0d80ab9-4b7b-4d9d-a21e-b0aa79b81fd7">
重新添加下宝德的物理机，宝德刀片服务器不支持 iso 引导，选 pxe 引导，然后把 pxe 网卡的 mac 地址填上。
