### ISSUE TITLE
[BUG]升级到3.10.3后, 远程登录终端后打印登录信息异常且很短时间内就会断开连接

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17442]
**问题描述/What happened**:
![image](https://github.com/yunionio/cloudpods/assets/10016360/7fd088f1-b5fb-47d9-b57f-9b7542716004)

![image](https://github.com/yunionio/cloudpods/assets/10016360/69d84d74-f220-4734-b84c-cb0411a8e83d)

打印信息不完整，并且信息出现在了第一行

且升级到3.10.3之后大概1分钟左右就会断开连接
![image](https://github.com/yunionio/cloudpods/assets/10016360/b7db4aea-5275-4b08-a5bb-4b1e8415c45a)

**环境/Environment**:
v3.10.3

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
> 

@shuoshadow 升级之前用的是ssh二进制进行连接的，新版本使用go原生ssh库 golang.org/x/crypto/ssh 
能告诉我你是配了哪个代理的timeout参数

**Comment by shuoshadow** [comment]
@ioito 是nginx中的read和send timeout
```
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
```

**Comment by dengju2020** [comment]
我们默认调高timeout时间

**Comment by ioito** [comment]
@shuoshadow 经过测试, 在部分版本浏览器可以稳定复现打印信息异常的问题
1. 可以通过更换cloudroot默认登录的shell由bash刚变更为zsh解决
2. 变更  /etc/bashrc 注释 [ "$PS1" = "\\s-\\v\\\$ " ] && PS1="[\u@\h \W]\\$ " 这一行也可以解决
3. 尝试升级浏览器(不一定能解决)

这个问题出现的根本原因是登录之后由server端发送了控制字符，控制光标进行了一次转移

**Comment by swordqiu** [comment]
看下升级xterm.js是否能解决问题 https://github.com/yunionio/cloudpods/issues/17669

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods-operator/pull/936/files nginx timeout改动 @shuoshadow

**Comment by ioito** [comment]
打印异常是由于有控制字符，以下是一个举例，常出现在windows浏览器
```bash
00000000: 4c61 7374 206c 6f67 696e 3a20 4d6f 6e20  Last login: Mon
00000010: 4175 6720 3134 2031 303a 3431 3a33 3620  Aug 14 10:41:36
00000020: 3230 3233 2066 726f 6d20 3130 2e31 3237  2023 from 10.127
00000030: 2e31 3030 2e32 dda1 b5d3 03b6 36c6 f756  .100.2......6..V
00000040: 4726 f6f7 4406 1757 46f2 d696 e737 4616  G&..D..WF....7F.
00000050: c6c2 d686 1303 13a7 e71b 5b3f 3130 3334  ..........[?1034
00000060: 685b 636c 6f75 6472 6f6f 7440 6175 746f  h[cloudroot@auto
00000070: 2d69 6e73 7461 6c6c 2d68 6130 3120 7e5d  -install-ha01 ~]
00000080: 241b 5b4b 20d2 0d1b 5b4b 1b5b 415b 636c  $.[K ...[K.[A[cl
00000090: 6f75 6472 6f6f 7440 6175 746f 2d69 6e73  oudroot@auto-ins
000000a0: 7461 6c6c 2d68 6130 3120 7e5d 24         tall-ha01 ~]$
```
