### ISSUE TITLE
[求助/Help] 编译抛错

### ISSUE THREAD

**Issue by yuanzhaoK** [yunionio/cloudpods#17454]
<img width="1012" alt="image" src="https://github.com/yunionio/cloudpods/assets/124442084/fa1fa4d4-d466-4acc-be1e-9c367502ff25">
按照开发教程 同时编译多个多架构的组件报错，这个该怎么解决

**Comment by zhasm** [comment]
> <img alt="image" width="1012" src="https://user-images.githubusercontent.com/124442084/251436772-fa1fa4d4-d466-4acc-be1e-9c367502ff25.png"> 按照开发教程 同时编译多个多架构的组件报错，这个该怎么解决

@yuanzhaoK 看一下`docker buildx ls`的配置？
* 需要确保`docker`的网关正确。(`ifconfig` 或`ip a` 里，能看到`docker0`)
* 需要确保`docker` 跨平台编译的各个节点正常运行。
