### ISSUE TITLE
[求助/Help]腾讯云allinone安装失败，failed to pull image

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17464]
虚拟机的配置信息如下：
![腾讯云allinone安装cloudpods报错，failed to pull image](https://github.com/yunionio/cloudpods/assets/11387540/a08443b7-8841-49d0-b26c-313f02116cae)

报错信息如下：
```bash
fatal: [172.19.0.4]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--onecloud-version", "v3.10.3", "--operator-version", "v3.10.3"], "delta": "0:01:35.004478", "end": "2023-07-09 15:26:21.914138", "msg": "non-zero return code", "rc": 1, "start": "2023-07-09 15:24:46.909660", "stderr": "failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver\nGet https://registry.cn-beijing.aliyuncs.com/v2/yunion/kube-apiserver/manifests/sha256:f034ddac32efadf73097544d1eb954c889b5b583e57150289bcf6fd3d16957dc: read tcp 172.19.0.4:44344->47.95.181.38:443: read: connection timed out\n, error: exit status 1", "stderr_lines": ["failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver", "Get https://registry.cn-beijing.aliyuncs.com/v2/yunion/kube-apiserver/manifests/sha256:f034ddac32efadf73097544d1eb954c889b5b583e57150289bcf6fd3d16957dc: read tcp 172.19.0.4:44344->47.95.181.38:443: read: connection timed out", ", error: exit status 1"], "stdout": "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8", "stdout_lines": ["[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8"]}
```

**Comment by jackgao2015** [comment]
目前发现在腾讯云香港的机器上发现了这个问题，其他像新加坡就没有这个问题。
根本问题是安装前， /etc/resolv.conf 有记录，安装时，/etc/resolv.conf 没有记录，导致阿里云对象存储的域名无法解析。
即使在 /etc/resolv.conf 增加了记录，能解析了，重跑还是会报错，/etc/resolv.conf 记录还是会丢失。

**Comment by zhasm** [comment]
> 虚拟机的配置信息如下： ![腾讯云allinone安装cloudpods报错，failed to pull image](https://user-images.githubusercontent.com/11387540/252134310-a08443b7-8841-49d0-b26c-313f02116cae.png)
> 
> 报错信息如下：
> 
> ```shell
> fatal: [172.19.0.4]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--onecloud-version", "v3.10.3", "--operator-version", "v3.10.3"], "delta": "0:01:35.004478", "end": "2023-07-09 15:26:21.914138", "msg": "non-zero return code", "rc": 1, "start": "2023-07-09 15:24:46.909660", "stderr": "failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver\nGet https://registry.cn-beijing.aliyuncs.com/v2/yunion/kube-apiserver/manifests/sha256:f034ddac32efadf73097544d1eb954c889b5b583e57150289bcf6fd3d16957dc: read tcp 172.19.0.4:44344->47.95.181.38:443: read: connection timed out\n, error: exit status 1", "stderr_lines": ["failed to pull image \"registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\": output: v1.15.8: Pulling from yunion/kube-apiserver", "Get https://registry.cn-beijing.aliyuncs.com/v2/yunion/kube-apiserver/manifests/sha256:f034ddac32efadf73097544d1eb954c889b5b583e57150289bcf6fd3d16957dc: read tcp 172.19.0.4:44344->47.95.181.38:443: read: connection timed out", ", error: exit status 1"], "stdout": "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8", "stdout_lines": ["[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8"]}
> ```
@jackgao2015 已经解决这个问题，请拉取最新的ocboot代码，重新部署。
