### ISSUE TITLE
[BUG]代码问题：desc传的是空值，没法判断，导致ubuntu镜像默认的用户是ubuntu 而展示的是root

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17468]
**问题描述/What happened**:
创建虚机获取默认用户问题
**环境/Environment**:
v3.10.1
<img width="823" alt="1300e47e6ebc9d819d475c6e783deb2" src="https://github.com/yunionio/cloudpods/assets/29140975/cb8d0bea-2054-45b9-841e-f135a9f8614d">
<img width="501" alt="19c7648c992759a6a72361e713d1db5" src="https://github.com/yunionio/cloudpods/assets/29140975/c7f0a929-5318-4813-b2af-de9cd19ced08">
这儿代码有问题,desc传的是空值 没法判断 导致ubuntu镜像默认的用户是ubuntu 而展示的是root

**Comment by ioito** [comment]
将在 https://github.com/yunionio/cloudpods/pull/17469/files 合并后修复
