### ISSUE TITLE
[求助/Help]All in One 的方式部署 Cloudpods 服务

### ISSUE THREAD

**Issue by sfwefqewgq** [yunionio/cloudpods#17467]
TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ********
fatal: [10.101.0.81]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "init", "--control-plane-endpoint", "10.101.0.81:6443", "--mysql-host", "10.101.0.81", "--mysql-user", "root", "--mysql-password", "v7UqjXmG4Z7w", "--mysql-port", "3306", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--apiserver-advertise-address", "10.101.0.81", "--node-ip", "10.101.0.81", "--enable-hugepage", "--onecloud-version", "v3.10.3", "--operator-version", "v3.10.3", "--pod-network-cidr", "10.40.0.0/16", "--service-cidr", "10.96.0.0/12", "--service-dns-domain", "cluster.local", "--addon-calico-ip-autodetection-method", "can-reach=10.101.0.81"], "delta": "0:00:00.050394", "end": "2023-07-10 14:18:40.116890", "msg": "non-zero return code", "rc": 1, "start": "2023-07-10 14:18:40.066496", "stderr": "error execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Mysql]: show grants for root@%: Error 1130: Host '10.101.0.81' is not allowed to connect to this MariaDB server\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Mysql]: show grants for root@%: Error 1130: Host '10.101.0.81' is not allowed to connect to this MariaDB server", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.10.3\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.10.3", "[preflight] Running pre-flight checks"]}

PLAY RECAP *********************************************************************
10.101.0.81                : ok=83   changed=40   unreachable=0    failed=1    skipped=19   rescued=0    ignored=0

**Comment by sfwefqewgq** [comment]
用IMAGE_REPOSITORY=docker.io/yunion ./run.py 10.101.0.81命令部署的

**Comment by hoganlxj** [comment]
@sfwefqewgq 执行 mysql -uroot -pv7UqjXmG4Z7w -h 10.101.0.81 能登陆成功吗？

**Comment by sfwefqewgq** [comment]
> 

连接拒绝

**Comment by sfwefqewgq** [comment]
刚开始密码没有修改成功，我登录mysql手动修改的，改成了v7UqjXmG4Z7w，把root权限也改了 改成允许远程登陆

**Comment by sfwefqewgq** [comment]
MariaDB [mysql]> SELECT host,user,password from user;
+-----------+------+-------------------------------------------+
| host      | user | password                                  |
+-----------+------+-------------------------------------------+
| localhost | root | *7CBF6D7745FAAEEAD037F0BF2F5C48A3D0EB4906 |
| cloudpods | root |                                           |
| 127.0.0.1 | root |                                           |
| ::1       | root |                                           |
| localhost |      |                                           |
| cloudpods |      |                                           |
| %         | root | *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B |
+-----------+------+-------------------------------------------+
7 rows in set (0.00 sec)

**Comment by hoganlxj** [comment]
@sfwefqewgq  还需要手工执行下面的grant语句
grant all privileges on *.* to `root`@`%` identified by 'v7UqjXmG4Z7w' with grant option; FLUSH PRIVILEGES;
另外，第一个安装时，有报数据库grant 报错没？

**Comment by sfwefqewgq** [comment]
grant all privileges on . to root@% identified by 'v7UqjXmG4Z7w' with grant option;有语法错误，之前执行的这个GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'; flush privileges;

**Comment by hoganlxj** [comment]
> grant all privileges on . to root@% identified by 'v7UqjXmG4Z7w' with grant option;有语法错误，之前执行的这个GRANT ALL PRIVILEGES ON _._ TO 'root'@'%' IDENTIFIED BY 'root'; flush privileges;

@sfwefqewgq 这个语句是有问题，用我提供的grant 语句，再重新安装

**Comment by sfwefqewgq** [comment]
这个是mariadb数据库，MariaDB [(none)]> grant all privileges on . to root@% identified by 'v7UqjXmG4Z7w' with grant option;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'to root@% identified by 'v7UqjXmG4Z7w' with grant option' at line 1   你发的语句报错

**Comment by sfwefqewgq** [comment]
可以连上数据库了，之前只改了root localhost的密码，现在改了root %的密码，可以连上数据库了，我再试一下重新安

**Comment by hoganlxj** [comment]
@sfwefqewgq 好的，这个是mariadb安装授权问题，再遇时，可以通过重新执行下面语句解决
MariaDB [(none)]> USE mysql;
MariaDB [(none)]> UPDATE user SET password=PASSWORD('v7UqjXmG4Z7w') WHERE User='root' AND Host = 'localhost';
MariaDB [(none)]> grant all privileges on *.* to `root`@`%` identified by 'v7UqjXmG4Z7w' with grant option; FLUSH PRIVILEGES;

**Comment by jackgao2015** [comment]
@sfwefqewgq  看一下部署的机器是否是推荐的系统版本，如果不是的话，可以重新建一台虚拟机，把原来的删掉，重新装一下。

**Comment by zexi** [comment]
该问题后面通过重新给数据库授权解决了。
