### ISSUE TITLE
保存镜像cpu架构识别错误

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17475]
麒麟的鲲鹏桌面版本安装后
![image](https://github.com/yunionio/cloudpods/assets/8031587/59970871-f715-4c47-a6a9-19be5f4fa3d6)
保存qcow镜像
![image](https://github.com/yunionio/cloudpods/assets/8031587/ed71c290-aac8-465e-84fd-ec167328f7e4)
CPU架构识别错误，系统镜像也识别不到。
![image](https://github.com/yunionio/cloudpods/assets/8031587/e15d58c9-1234-4b94-94f8-d00b97016d36)
![image](https://github.com/yunionio/cloudpods/assets/8031587/e0009d4e-698a-4321-b592-488ec817ca5a)
混合架构部署

**Comment by yangqingwen666** [comment]
@zhongyong 保存成功之后状态显示可用后架构还是不对吗？

**Comment by zhongyong** [comment]
嗯，需要手动修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月10日(周一) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] 保存镜像cpu架构识别错误 (Issue #17475)




 
@zhongyong 保存成功之后状态显示可用后架构还是不对吗？

**Comment by swordqiu** [comment]
银河麒麟的桌面版本吗？是否有iso下载路径，我们装一个试下。

**Comment by zhongyong** [comment]
V10sp1桌面2303 链接：https://pan.baidu.com/s/1nwEfkvU9Ft-EvfG9F0IF1w?pwd=ky10&nbsp;
提取码：ky10&nbsp;
--来自百度网盘超级会员V5的分享&nbsp;

我这里使用的是鲲鹏的版本






钟勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 保存镜像cpu架构识别错误 (Issue #17475)





 
银河麒麟的桌面版本吗？是否有iso下载路径，我们装一个试下。

**Comment by zexi** [comment]
@wanyaoqi 这个麻烦通过 iso 安装虚拟机，保存镜像测试下

**Comment by swordqiu** [comment]
这个PR应该修复了，https://github.com/yunionio/cloudpods/pull/17635
