### ISSUE TITLE
[求助/Help] 请问宿主机支持debian10吗？

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17489]
您好！我在cloudpods宿主机配置内发现要求计算节点的操作系统版本为centos7，请问是否支持debian10？如果支持请问有对应教程吗？

**Comment by wanyaoqi** [comment]
debian10 是支持的，可以使用 ocboot安装
https://www.cloudpods.org/zh/docs/setup/host/#使用-ocboot-添加对应节点

**Comment by wanyaoqi** [comment]
> @C4a15Wh debian10 是支持的，可以使用 ocboot安装 [https://www.cloudpods.org/zh/docs/setup/host/#使用-ocboot-添加对应节点](https://www.cloudpods.org/zh/docs/setup/host/#%E4%BD%BF%E7%94%A8-ocboot-%E6%B7%BB%E5%8A%A0%E5%AF%B9%E5%BA%94%E8%8A%82%E7%82%B9)

ocboot安装会判断操作系统，debian是支持的操作系统
