### ISSUE TITLE
跟进qcow镜像创建虚拟机后重置密码问题

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17491]
1、虚拟机使用麒麟sp1 2303的arm版本。
2、根据https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/create/和https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/qga/制作镜像。
3、安装qemu-guest-agent后，systemctl enableqemu-guest-agent和systemctl start qemu-guest-agent都报错告警。
4、然后保存镜像微qcow，在创建虚拟机后。
![image](https://github.com/yunionio/cloudpods/assets/8031587/3048aa2a-88ba-434b-9a0c-c253018559fa)
5、重置密码
![image](https://github.com/yunionio/cloudpods/assets/8031587/51a6377f-acf5-4b89-a214-6b1c787f5cc9)
正常情况应该提示重置失败，目前没提示重置失败。

我目前需要的就是能重置密码成功，然后管理页面也看到随机或者手动输入的新密码。
ps：根据麒麟qcow镜像创建的虚拟机是否可以创建非普通用户的账号和密码用于spice桌面进去登录账号。
![image](https://github.com/yunionio/cloudpods/assets/8031587/a9b1556a-7e6c-4377-acec-9a2fca96cbcb)
类似这里只有一个普通账号，是我创建虚拟机的时候都普通账号。

**Comment by wanyaoqi** [comment]
<img width="751" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/5480587c-123d-4b1c-b835-652f7aa56287">

**Comment by wanyaoqi** [comment]
<img width="837" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/bbbe09d0-5a79-4a8f-8822-404941056e90">
<img width="956" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/3163f97f-8e19-4646-9c2b-c12d03f865e9">

**Comment by wanyaoqi** [comment]
> <img alt="image" width="837" src="https://user-images.githubusercontent.com/18528551/252831985-bbbe09d0-5a79-4a8f-8822-404941056e90.png"> <img alt="image" width="956" src="https://user-images.githubusercontent.com/18528551/252832882-3163f97f-8e19-4646-9c2b-c12d03f865e9.png">

@zhongyong hi，我用麒麟sp1和 ouler测试安装 qga都没有问题。你的镜像是如何制作的？尝试重启一下虚机看是否能起到 qga成功。

**Comment by zhongyong** [comment]
我用的是麒麟和欧拉的鲲鹏版本的。你是不是用的arm的版本

**Comment by wanyaoqi** [comment]
> 我用的是麒麟和欧拉的鲲鹏版本的。你是不是用的arm的版本

全都是arm版本的

**Comment by zhongyong** [comment]
但是你用的麒麟是server我是桌面版本。

钟勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 跟进qcow镜像创建虚拟机后重置密码问题 (Issue #17491)





  
我用的是麒麟和欧拉的鲲鹏版本的。你是不是用的arm的版本
  
全都是arm版本的

**Comment by swordqiu** [comment]
确认qga问题是因为银河麒麟arm桌面版的qemu-guest-agent有问题，请等银河麒麟更新修复。

重置密码不报错是因为当前版本重置密码为异步操作，报错在操作日志才能看到。目前已经增加gqa的同步操作接口(https://github.com/yunionio/cloudpods/pull/17465)，等3.10.4或3.9.12发布。

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/pull/17508 
这个 pr 添加ARM虚机 qga相关参数。
