### ISSUE TITLE
[BUG]主机模板的顶部分类不生效

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17499]
**问题描述/What happened**:
展示主机模板的页面过滤参数无效
**环境/Environment**:
v3.10.1
![image](https://github.com/yunionio/cloudpods/assets/29140975/253d7194-158f-45fe-9c90-a45b476f5b5c)

**Comment by yangqingwen666** [comment]
好，我们看下，谢谢反馈

**Comment by ioito** [comment]
Closed #17520
