### ISSUE TITLE
[求助/Help]费用管理报错

### ISSUE THREAD

**Issue by dsl-zy** [yunionio/cloudpods#17498]
已开通SaaS版，着重试用 * 公有云/私有云费用管理与优化(FinOps)
已接入腾讯云和阿里云账号，状态正常；
费用-费用分析-云账号，报错如图
![image](https://github.com/yunionio/cloudpods/assets/139295394/b7bdbfa4-5b69-4c50-956d-7bd89088befe)

其他如，平台、项目、标签数据均不能正常获取展现，求助

**Comment by jackgao2015** [comment]
@dsl-zy 收到，这个问题我们看一下。
另外，SaaS环境现在维护的比较少，为了给您更好的使用体验，您还可以预约企业版的试用哈。
