### ISSUE TITLE
虚拟机的网卡突然无法获取ip地址

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17497]
![image](https://github.com/yunionio/cloudpods/assets/8031587/3d64469a-37b5-4db7-8fd9-34032a2c1b42)
![image](https://github.com/yunionio/cloudpods/assets/8031587/2a3280f7-92d9-45c4-8bc4-81b21a015b62)
![image](https://github.com/yunionio/cloudpods/assets/8031587/9e685a81-3964-4bf0-a550-f96682f9fa95)
更换ip重启网卡也失败
![Uploading image.png…]()

**Comment by hoganlxj** [comment]
@zhongyong 看下网卡配置？

**Comment by wanyaoqi** [comment]
@zhongyong 需要先排查一下虚机内网卡为什么会启动失败，查看一下 network 或者 network manager 日志

**Comment by zhongyong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/8031587/ebf4aff1-9a90-4312-9a48-7a6d74b89ef0)

**Comment by zhongyong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/8031587/22acbb79-aa4c-44c4-bfa4-c79d3563c66b)

**Comment by wanyaoqi** [comment]
@zhongyong 你贴的图没有有用的信息，你可以尝试重启 network manager 或者 手动执行 dhclient ，或者排查一下 eth0 的网络配置。尝试找一些有用的信息。

**Comment by zhongyong** [comment]
systemctl restart NetworkManager没起作用
使用了dhclient解决问题，可能和里面的安全组件有关系
![image](https://github.com/yunionio/cloudpods/assets/8031587/07b5c0ef-9561-4a4d-9b37-daac07e3077d)

**Comment by swordqiu** [comment]
国产软件会有授权的问题，以及安装了安全套件等原因，导致网络不通。需要先排查这些原因。
