### ISSUE TITLE
[文档/Docs] 参考文档操作暂停集群服务后, 无法重建服务, 集群崩溃

### ISSUE THREAD

**Issue by cnsunfocus** [yunionio/cloudpods#17492]
![image](https://github.com/yunionio/cloudpods/assets/3301715/2674a964-2a89-46c7-8055-ff02ce034b33)

按照上述步骤添加-stop-service操作后, 部分集群服务始终无法删除, 一直在重建.

重新删除参数后, 集群无法恢复 pod各种错误状态..... 重启机器也无法恢复了

![image](https://github.com/yunionio/cloudpods/assets/3301715/b1dfadfa-6faa-4717-b004-892e80f80d3a)

**Comment by hoganlxj** [comment]
@cnsunfocus 看下数据库服务起来没？ 如果数据库服务正常，看下keystone和region两个pods的状态是否为Running？

**Comment by zexi** [comment]
@cnsunfocus 看起来和这个是同样的问题：https://github.com/yunionio/cloudpods/issues/17496，已经修复过，可以更新 operator 镜像后再试试

**Comment by zexi** [comment]
可以把 operator 镜像更新成这个版本再试试：registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.10-0717.0
