### ISSUE TITLE
[求助/Help]在阿里云上的虚拟机安装完，貌似服务都没有起动。安装过程中也没有什么异常

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17501]
[root@cloudpods ~]# netstat -tlunp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      23724/mysqld        
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      581/rpcbind         
tcp        0      0 0.0.0.0:8118            0.0.0.0:*               LISTEN      2500/privoxy        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1299/sshd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1122/master         
tcp6       0      0 :::111                  :::*                    LISTEN      581/rpcbind         
tcp6       0      0 ::1:25                  :::*                    LISTEN      1122/master         
udp        0      0 0.0.0.0:68              0.0.0.0:*                           20998/dhclient      
udp        0      0 0.0.0.0:111             0.0.0.0:*                           581/rpcbind         
udp        0      0 127.0.0.1:323           0.0.0.0:*                           583/chronyd         
udp        0      0 0.0.0.0:748             0.0.0.0:*                           581/rpcbind         
udp6       0      0 :::111                  :::*                                581/rpcbind         
udp6       0      0 ::1:323                 :::*                                583/chronyd         
udp6       0      0 :::748                  :::*                                581/rpcbind         
[root@cloudpods ~]# netstat

**Comment by jackgao2015** [comment]
在什么环境安装的？安装过程中有无报错信息？
我（一个pm）刚才在阿里云上安装了一下，没什么问题，我也顺便写了一篇记录，可以看一下https://juejin.cn/post/7254829363023446071
看看是否能帮助你

**Comment by shengxianli** [comment]
@jackgao2015 感谢回复  我的版本是阿里云自带版本 CentOS Linux release 7.9.2009 (Core) ，在安装的时候我没有进行OPT挂载，但是也没有报错。我按您的文档操作一下试试

**Comment by shengxianli** [comment]
@jackgao2015 看来还真是没有分区的问题。现在解决了
