### ISSUE TITLE
[求助/Help] 添加计算节点后，climc无法查询到节点。

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17523]
机器类型 Dell PowerEdge R720
系统 Debian 10
使用如下命令添加计算节点: 
```
python3 ./ocboot.py add-node xxxxxxxx.120.5 xxxxxxxxx.120.2
```
ocboot运行过程中无异常，顺利完成了所有task。  
但完成后，登上网页控制台无法查看到节点，只显示了三个master节点。
即使使用climc查询也无法查询到任何信息，但使用kubelet get nodes的时候能看到新增节点。
  
---

使用kubectl查看相关pods状态，发现host容器退出，提示: 
```
Host instance init error: Prepare environment: hugepage 1024 nr 0
```
详细日志见下一条

**Comment by C4a15Wh** [comment]
[info 230713 22:04:59 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 230713 22:04:59 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/host.conf
[warning 230713 22:04:59 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac
[warning 230713 22:04:59 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-qmp-monitor
[warning 230713 22:04:59 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-health-checker
[warning 230713 22:04:59 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument disk-is-ssd
[warning 230713 22:04:59 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument health-driver
[info 230713 22:04:59 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:04:59 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/common/common.conf
[info 2023-07-13 22:04:59 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:04:59 hostman.(*SHostService).InitService(host_services.go:63)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-07-13 22:04:59 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-13 22:04:59 appsrv.NewApplication(appsrv.go:116)] App hostId: EdYbDfq8pNwgI8fXTZd0xBHc5g4= (host,gpu-worker-02,192.168.1.2)
2023/07/13 22:04:59 Allow hosts []
[info 2023-07-13 22:04:59 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-13 22:04:59 hostinfo.DetectCpuInfo(hostinfohelper.go:77)] cpuinfo freq 2926
[info 2023-07-13 22:04:59 hostinfo.NewHostInfo(hostinfo.go:2243)] CPU Model Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz Microcode 0x42e
[info 2023-07-13 22:05:00 hostinfo.NewHostInfo(hostinfo.go:2264)] Get kubelet container image Fs: /opt/docker, eviction config: {"evictionHard":{"imagefs.available":{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"memory.available":{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0}},"nodefs.available":{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"nodefs.inodesFree":{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}}}}
[error 2023-07-13 22:05:00 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:373)] tuned-adm profile virtual-host fail: exec: "tuned-adm": executable file not found in $PATH
[info 2023-07-13 22:05:00 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:404)] I/O Scheduler switch to none
[info 2023-07-13 22:05:00 fileutils2.ChangeBlkdevParameter(fileutils.go:202)] Set queue/scheduler of sda to none
[fatal 2023-07-13 22:05:00 hostman.(*SHostService).RunService(host_services.go:79)] Host instance init error: Prepare environment: hugepage 1024 nr 0
root@master-01:~/ocboot# kubectl log -n onecloud default-host-25l4v host
log is DEPRECATED and will be removed in a future version. Use logs instead.
[info 230713 22:10:01 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 230713 22:10:01 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/host.conf
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument health-driver
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-qmp-monitor
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-health-checker
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument disk-is-ssd
[info 230713 22:10:01 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:10:01 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/common/common.conf
[info 2023-07-13 22:10:01 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:10:01 hostman.(*SHostService).InitService(host_services.go:63)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-07-13 22:10:01 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-13 22:10:01 appsrv.NewApplication(appsrv.go:116)] App hostId: EdYbDfq8pNwgI8fXTZd0xBHc5g4= (host,gpu-worker-02,192.168.1.2)
2023/07/13 22:10:01 Allow hosts []
[info 2023-07-13 22:10:01 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-13 22:10:01 hostinfo.DetectCpuInfo(hostinfohelper.go:77)] cpuinfo freq 2777
[info 2023-07-13 22:10:01 hostinfo.NewHostInfo(hostinfo.go:2243)] CPU Model Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz Microcode 0x42e
[info 2023-07-13 22:10:02 hostinfo.NewHostInfo(hostinfo.go:2264)] Get kubelet container image Fs: /opt/docker, eviction config: {"evictionHard":{"imagefs.available":{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"memory.available":{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0}},"nodefs.available":{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"nodefs.inodesFree":{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}}}}
[error 2023-07-13 22:10:02 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:373)] tuned-adm profile virtual-host fail: exec: "tuned-adm": executable file not found in $PATH
[info 2023-07-13 22:10:02 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:404)] I/O Scheduler switch to none
[info 2023-07-13 22:10:02 fileutils2.ChangeBlkdevParameter(fileutils.go:202)] Set queue/scheduler of sda to none
[fatal 2023-07-13 22:10:02 hostman.(*SHostService).RunService(host_services.go:79)] Host instance init error: Prepare environment: hugepage 1024 nr 0
root@master-01:~/ocboot# kubectl log -n onecloud default-host-25l4v host
log is DEPRECATED and will be removed in a future version. Use logs instead.
[info 230713 22:10:01 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 230713 22:10:01 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/host.conf
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument health-driver
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-qmp-monitor
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-health-checker
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac
[warning 230713 22:10:01 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument disk-is-ssd
[info 230713 22:10:01 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:10:01 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/common/common.conf
[info 2023-07-13 22:10:01 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-13 22:10:01 hostman.(*SHostService).InitService(host_services.go:63)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-07-13 22:10:01 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-13 22:10:01 appsrv.NewApplication(appsrv.go:116)] App hostId: EdYbDfq8pNwgI8fXTZd0xBHc5g4= (host,gpu-worker-02,192.168.1.2)
2023/07/13 22:10:01 Allow hosts []
[info 2023-07-13 22:10:01 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-13 22:10:01 hostinfo.DetectCpuInfo(hostinfohelper.go:77)] cpuinfo freq 2777
[info 2023-07-13 22:10:01 hostinfo.NewHostInfo(hostinfo.go:2243)] CPU Model Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz Microcode 0x42e
[info 2023-07-13 22:10:02 hostinfo.NewHostInfo(hostinfo.go:2264)] Get kubelet container image Fs: /opt/docker, eviction config: {"evictionHard":{"imagefs.available":{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"memory.available":{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0}},"nodefs.available":{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"nodefs.inodesFree":{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}}}}
[error 2023-07-13 22:10:02 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:373)] tuned-adm profile virtual-host fail: exec: "tuned-adm": executable file not found in $PATH
[info 2023-07-13 22:10:02 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:404)] I/O Scheduler switch to none
[info 2023-07-13 22:10:02 fileutils2.ChangeBlkdevParameter(fileutils.go:202)] Set queue/scheduler of sda to none
[fatal 2023-07-13 22:10:02 hostman.(*SHostService).RunService(host_services.go:79)] Host instance init error: Prepare environment: hugepage 1024 nr 0

**Comment by C4a15Wh** [comment]
问题已解决，默认情况下计算节点的grub并未配置hugepage相关的内核参数，ocboot在安装过程中向/etc/default/grub追加了关于hugepage_size的参数，但该参数生效需要update-grub并重新引导机器。
故使用ocboot安装后应当重新引导机器才能使计算节点正常工作，建议向文档【添加计算节点】章节内追加该补充说明。

**Comment by zexi** [comment]
@C4a15Wh 收到，感谢反馈问题

**Comment by zexi** [comment]
> 问题已解决，默认情况下计算节点的grub并未配置hugepage相关的内核参数，ocboot在安装过程中向/etc/default/grub追加了关于hugepage_size的参数，但该参数生效需要update-grub并重新引导机器。 故使用ocboot安装后应当重新引导机器才能使计算节点正常工作，建议向文档【添加计算节点】章节内追加该补充说明。

@wanyaoqi @zhasm 请看下这个问题

**Comment by zexi** [comment]
https://github.com/yunionio/ocboot/blob/master/onecloud/roles/utils/kernel-check/tasks/main.yml#L41-L110
这里有设置 hugetbl 的逻辑
