### ISSUE TITLE
The way kubeserver checks the cluster status is incorrect

### ISSUE THREAD

**Issue by CloudCourierStation** [yunionio/cloudpods#17529]
source code
https://github.com/yunionio/kubecomps/blob/606c73ff552a338b420e9a14b1b04ef1658e460f/pkg/kubeserver/models/clusters.go#L996-L1005

If the cluster status is NotReay, you can still obtain the cluster version information，check the condition of the node instead

**Comment by zexi** [comment]
@CloudCourierStation 

Some public cloud clusters like AWS EKS don't label control nodes with "node-role.kubernetes.io/master".

Invoking cli.Discovery().ServerVersion() method is a better way than checking each node's status to check cluster's healthy.

So I think this logic shouldn't be changed, you can get each node's 'NotReady' status by viewing Web frontend page or  'list node API'.
