### ISSUE TITLE
[BUG] 3.10版本中的一些链接已经失效

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17537]
**问题描述/What happened**:
3.10版本中的一些链接已经失效

例如: PCI设备透传功能下，新建透传设备类型的表单中的文档指引链接已经失效，经查该部分文档已经迁移到docs.yunion.cn，而不是www.cloudpods.org，建议向社区文档补充这类内容。

**Comment by wanyaoqi** [comment]
@C4a15Wh hi, 我的环境跳转正常，清一下缓存试试呢https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/#其他通用pcipcie设备透传
https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/

**Comment by zexi** [comment]
@C4a15Wh 文档都以 https://www.cloudpods.org 的为主，这个是最新的文档，其他的文档可能有点旧，是用来给访问不了 github pages 的用户看的，更新会慢一些

**Comment by C4a15Wh** [comment]
好的，了解
