### ISSUE TITLE
[BUG]无法删除安全组缓存

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17536]
**问题描述/What happened**:
v3.10.1
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

![image](https://github.com/yunionio/cloudpods/assets/29140975/028a0e4c-002f-439e-ba9f-09f2496359ac)

**Comment by ioito** [comment]
麻烦贴下后端日志 @hewenxiang

**Comment by hewenxiang** [comment]
这个问题是我的华为帐户没权限创建和删除安全组，所以bug 应该是修改安全组这儿，不应该增加上安全组才对

**Comment by ioito** [comment]
@hewenxiang 那就应该选择有安全组缓存的安全组，这样就不会新建安全组了

**Comment by ioito** [comment]
3.11开始支持安全组一对一模式，不建议再使用安全组缓存这种用法
