### ISSUE TITLE
[求助/Help]帮忙解释一段代码

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17532]
大佬们，请教个go语言的问题，在kubecomps项目文件pkg/kubeserver/app/handlers.go里面出现这行代码，在什么情况下这个类型断言是true？
<img width="1027" alt="image" src="https://github.com/yunionio/cloudpods/assets/11387540/d88f45a4-dadd-4825-ba65-1344f2523d71">

**Comment by zexi** [comment]
> 大佬们，请教个go语言的问题，在kubecomps项目文件pkg/kubeserver/app/handlers.go里面出现这行代码，在什么情况下这个类型断言是true？ <img alt="image" width="1027" src="https://user-images.githubusercontent.com/11387540/253525273-d88f45a4-dadd-4825-ba65-1344f2523d71.png">

@jackgao2015 这个不一定是永远为 true ，因为有些是有类型的，比如 *v1.Pod 等，这个是根据 models 这个包下的资源联动的，比如下面的代码：
<img width="766" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/64b78a19-c7c4-4f16-893e-89230e7b0ae3">

pod 用的就是 new(v1.Pod)，但 ingress 就是用的 new(unstructured.Unstructured)

**Comment by EvanSung** [comment]
ingress从侧边页->"源信息" 点击更新，我测试过了，还是false。这里的Update传参是*runtime.Unknow类型（结构体指针类型，非接口指针），上层调用来自于pkg/kubeserver/models/clusterresource.go 文件的函数UpdateK8sObject
<img width="935" alt="image" src="https://github.com/yunionio/cloudpods/assets/20303669/ff24cd8b-4006-412f-bcd7-4647b4d94443">

**Comment by zexi** [comment]
> ingress从侧边页->"源信息" 点击更新，我测试过了，还是false。这里的Update传参是*runtime.Unknow类型（结构体指针类型，非接口指针），上层调用来自于pkg/kubeserver/models/clusterresource.go 文件的函数UpdateK8sObject <img alt="image" width="935" src="https://user-images.githubusercontent.com/20303669/253581664-ff24cd8b-4006-412f-bcd7-4647b4d94443.png">

@EvanSung 这里使用 runtime.Unknown 来更新应该没有问题，因为 *runtime.Unknown 的 DeepCopyObject 返回的是 Object 这个 interface{} ，可能底层的实现是 *unstructured.Unstructured 结构体
