### ISSUE TITLE
[BUG]云帐户资源统计bug

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17542]
**问题描述/What happened**:
v3.10.1
**环境/Environment**:

![image](https://github.com/yunionio/cloudpods/assets/29140975/095486bf-85bc-48d3-a371-4e422a0ad2b6)
展示的是一个也没使用，但实际上已经使用了两个
![image](https://github.com/yunionio/cloudpods/assets/29140975/e779970a-e1ba-49ef-b234-41847067de41)

**Comment by dengju2020** [comment]
@hewenxiang 感谢反馈，本地已复现，处理中，有结果会在这里更新

**Comment by ioito** [comment]
Closed #17602
上面这个pr修复这个问题
