### ISSUE TITLE
[BUG]创建硬盘，选择的是openstack平台，最终创建出来的平台不是openstack

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#17545]
**问题描述/What happened**:
v3.10.1
**环境/Environment**:
[
    "No matching resources",
    "{\"error\":{\"code\":400,\"details\":\"Error #01: Scheduler not found candidates by args {\\\"host_types\\\":[\\\"openstack\\\"],\\\"region_id\\\":\\\"83472eee-c5fa-41c6-8d12-9aa9bf8b3c68\\\",\\\"res_type\\\":\\\"host\\\",\\\"zone_id\\\":\\\"a8b4c6dc-7979-46d6-8b35-78b6e8f64145\\\"}\\n\",\"request\":{\"body\":\"{\\\"backup\\\":false,\\\"best_effort\\\":false,\\\"change_config\\\":false,\\\"count\\\":1,\\\"details\\\":false,\\\"disks\\\":[{\\\"backe...u_count\\\":0,\\\"vmem_size\\\":0}\",\"headers\":{\"Content-Length\":\"1283\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Request-Id\":\"6e2c1b-0f74ad\",\"X-Yunion-Lang\":\"zh-CN\",\"X-Yunion-Parent-Id\":\"0.0\",\"X-Yunion-Peer-Service-Name\":\"compute_v2\",\"X-Yunion-Remote-Addr\":\"default-scheduler:30887\",\"X-Yunion-Span-Id\":\"0.0.0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"8e2fa2c8\"},\"method\":\"POST\",\"url\":\"https://default-scheduler:30887/scheduler\"}}}"
]
![image](https://github.com/yunionio/cloudpods/assets/29140975/7422d8cf-a3c0-4531-a2c7-24efac1d15e4)

**Comment by ioito** [comment]
@hewenxiang 由于调度失败，导致没有选上对应的openstack的存储，因此无法和openstack平台关联起来，因此显示的是默认的平台

**Comment by ioito** [comment]
Closed #17606 
调度失败之后的资源，平台将置为unknonw @hewenxiang
