### ISSUE TITLE
[求助/Help] 安装部署 ocadm 报错

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#17557]
高可用安装时报错 Error: unknown flag: --enable-hugepage
kylinos v10 sp2 x86_64  onecloud_version: "v3.10.3"

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/0621518d-8b91-4913-b3d1-42e90e092eab)
yum仓库中的是3.9.1的版本，另外这个参数不支持。通过[iso.yun](https://iso.yunion.cn/kylin/v10-sword/3.10/x86_64/)查看3.10的版本和3.9的是一样的，应该是没有做更新

**Comment by zhasm** [comment]
@lvzhiweilv 
稍等，我更新一下repo。

**Comment by zhasm** [comment]
@lvzhiweilv repo已经更新。

请重置一下环境：
```bash
kubeadm reset -f;
/opt/yunion/bin/ocadm reset -f
rm -rf /etc/kubernetes/ /var/lib/etcd/
```
然后请重新跑一下安装流程，应该会自动安装最新的相关rpm。等您反馈~

**Comment by lvzhiweilv** [comment]
另外缺少kylin-yunion.repo 文件

**Comment by zhasm** [comment]
> 
@lvzhiweilv 好的，我检查一下。

**Comment by zhasm** [comment]
@lvzhiweilv 后续安装成功了吗？

**Comment by lvzhiweilv** [comment]
后续已经完成安装，另外openeuler是否可以正常使用了

**Comment by lvzhiweilv** [comment]
管理平台安装成功，在添加宿主机节点时出错：
(item=yunion-qemu-4.2.0) 
	=> {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "yunion-qemu-4.2.0", "msg": "Depsolve Error occured: 
	问题: conflicting requests
	- package yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64 does not have a compatible architecture
	- nothing provides libpthread.so.0(GLIBC_2.2.5)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides libpthread.so.0(GLIBC_2.3.2)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides libm.so.6(GLIBC_2.2.5)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides librt.so.1(GLIBC_2.2.5)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides libpthread.so.0(GLIBC_2.12)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides libpthread.so.0(GLIBC_2.3.3)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64
	- nothing provides libutil.so.1(GLIBC_2.2.5)(64bit) needed by yunion-qemu-4.2.0-4.2.0-20221215.ky10.ky10.x86_64", "rc": 1, "results": []}

管理平台 kylinos v10 sp2 x86_64，宿主机kylinos v10 sp2 aarch64 。

**Comment by zhasm** [comment]
2

> 后续已经完成安装，另外openeuler是否可以正常使用了

@lvzhiweilv openeuler 应该支持 openeuler-22.03-lts . 安装如有问题，请新开ticket.

> 管理平台 kylinos v10 sp2 x86_64，宿主机kylinos v10 sp2 aarch64 。 

收到，我这边先检查一下本地repo。

**Comment by zhasm** [comment]
@lvzhiweilv 

> 管理平台 kylinos v10 sp2 x86_64，宿主机kylinos v10 sp2 aarch64 。

请检查，您宿主机kylinos v10 sp2 aarch64  所使用的repo文件，是不是：https://iso.yunion.cn/kylin/v10/3.10/aarch64/kylin-yunion.repo
以及，这个文件是您手工拷贝上去的，还是安装流程(ocboot)自动获取的？

```bash
[yunion-kylin-arm-repo]
name=Packages for Yunion Multi-Cloud Platform -
baseurl=https://iso.yunion.cn/kylin/v10/3.10/aarch64
sslverify=0
failovermethod=priority
enabled=1
gpgcheck=0
```

**Comment by lvzhiweilv** [comment]
已经处理完成，是由于自己修改了ocboot下载文件导致的

**Comment by lvzhiweilv** [comment]
在添加计算节点完成后，climc host-list 显示0

**Comment by hoganlxj** [comment]
> 在添加计算节点完成后，climc host-list 显示0 ![图片](https://user-images.githubusercontent.com/25196014/254510011-64729437-63ae-4ebf-9fd9-5f56b8a7ec9c.png)
> 
> ![图片](https://user-images.githubusercontent.com/25196014/254510387-8d833b11-3b88-4940-a3d0-30697f68e5c1.png)

@lvzhiweilv  在cloudpods控制节点 执行kubectl get pods -o wide |grep host ，看是否有对应host 的pods
若没有，先启用host-agent
for node in `kubectl get nodes | awk 'NR>1 {print $1}'`; do ocadm node enable-host-agent --node $node; done
若有对应host的pods，可以参考下
https://www.cloudpods.org/zh/docs/quickstart/allinone/#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA

**Comment by lvzhiweilv** [comment]
> 

![图片](https://github.com/yunionio/cloudpods/assets/25196014/4204f9d3-dfe9-491b-a5ce-afb3b317c368)
docker ps -a 
![图片](https://github.com/yunionio/cloudpods/assets/25196014/ab14ed6f-1ebb-4f4d-a696-2239f401790f)

**Comment by hoganlxj** [comment]
> kubectl get pods -o wide -n onecloud |grep host

@lvzhiweilv 执行 kubectl get pods -o wide -n onecloud |grep host

**Comment by lvzhiweilv** [comment]
> kubectl get pods -o wide -n onecloud |grep host

![图片](https://github.com/yunionio/cloudpods/assets/25196014/f0b4f035-7b96-4a73-8d46-8f1e171e6704)

**Comment by hoganlxj** [comment]
@lvzhiweilv   
export KUBECONFIG=/etc/kubernetes/admin.conf
kubectl get pods -o wide -n onecloud |grep host

**Comment by lvzhiweilv** [comment]
> 

![图片](https://github.com/yunionio/cloudpods/assets/25196014/2b206ca3-2f0d-484d-9811-064d5f653cb2)

**Comment by zhasm** [comment]
@lvzhiweilv 
`kubectl -n onecloud logs -f default-host-health-<ID补全> `，看一下日志？

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/16c0c68c-747a-48a4-b66c-28fb5aa1928a)

![图片](https://github.com/yunionio/cloudpods/assets/25196014/3cd6b7e5-01c9-43c8-8129-31b9f5e411ee)

![图片](https://github.com/yunionio/cloudpods/assets/25196014/554b5a90-5e32-45d4-81ba-84c4c9437ac6)

**Comment by zhasm** [comment]
@lvzhiweilv
`kubectl get pods  -o wide -A |grep etcd `
看一下所有的etcd的状态，如果不是running，删掉相关 pod一下，然后看看能否恢复正常。

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/88c99484-ec44-43d5-9d66-48d770280bc8)
etc状态异常的全部删除后，仅剩一个etc节点running

**Comment by zhasm** [comment]
@lvzhiweilv 删除之后，现在所有节点都正常了吗？

**Comment by lvzhiweilv** [comment]
还是不行

**Comment by lvzhiweilv** [comment]
如果现在将控制节点和计算节点重置，重新进行部署该如何操作

**Comment by zhasm** [comment]
@lvzhiweilv 

[如何卸载平台](https://www.cloudpods.org/zh/docs/setup/uninstall/)
如有其他问题，请新开issue～
