### ISSUE TITLE
 添加VMware探测网络失败[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17556]
添加VMware宿主机同步失败
![image](https://github.com/yunionio/cloudpods/assets/32296103/c3e4fbb9-02e9-4005-bb2e-8d8682bf06ee)
![image](https://github.com/yunionio/cloudpods/assets/32296103/9dd0ce4f-7b52-4627-ba75-f75a916a1d69)
错误日志
![image](https://github.com/yunionio/cloudpods/assets/32296103/33e30afe-ea90-4e45-a052-dc0d0b649758)

{
    "error": "fail to find zone of esxi: no valid on-premise networks: NotFoundError"
}

**Comment by dengju2020** [comment]
@shengxianli 先看下文档，看看是否可以排查下原因。https://www.cloudpods.org/zh/docs/function_principle/multicloud/cloudaccounts/vmware_net/

**Comment by swordqiu** [comment]
@shengxianli

**Comment by shengxianli** [comment]
@swordqiu @dengju2020 是我子网配置有问题 感谢各位

**Comment by shengxianli** [comment]
@swordqiu @dengju2020 同时请教个问题，在创建二层子网的时候，没有其他VPC的待选项

**Comment by shengxianli** [comment]
@swordqiu @dengju2020 请教一下 创建二层子网 VPC只能选择默认的，不能选择我自己创建的
![image](https://github.com/yunionio/cloudpods/assets/32296103/9ca62908-a1f3-4bca-a022-ef4d73876861)

**Comment by swordqiu** [comment]
只有经典网络才有二层网络的概念。这里只有Default VPC是经典网络。
