### ISSUE TITLE
[求助/Help] 如何在一台服务器中彻底卸载和清除cloudpods相关信息，想重新安装，不想重装系统

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#17562]

**Comment by zexi** [comment]
@szz1113-1119 https://www.cloudpods.org/zh/docs/quickstart/allinone/#4-%E5%A6%82%E4%BD%95%E9%87%8D%E8%A3%85 
可以参考这个文档进行重装
