### ISSUE TITLE
[BUG] Cloudpods未能很好地识别到处在阵列卡下的SSD

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17569]
**问题描述/What happened**:
我们将一台曙光X730-G30(超微X11DGO-T)配置为了计算节点，该机器使用MegaRAID S.A.S. 9631-8I阵列卡启动了一个全闪磁盘阵列(RAID-0)，但Cloudpods在系统中将其识别为了机械盘，我不清楚是哪里出现了问题...

**环境/Environment**:
系统 Debian 10
内核 4.19
机器 X730-G30
阵列卡 9631-8I

**Comment by C4a15Wh** [comment]
该问题在Dell H330/H710阵列卡下仍能复现，所以推测可能对于其他在阵列卡下的高速SSD都存在该问题...

**Comment by fangpsh** [comment]
可以先临时手工修改存储介质，在存储那里。

**Comment by zexi** [comment]
> 该问题在Dell H330/H710阵列卡下仍能复现，所以推测可能对于其他在阵列卡下的高速SSD都存在该问题...

@C4a15Wh 这里有探测存储的代码：https://github.com/yunionio/cloudpods/blob/release/3.10/pkg/hostman/storageman/storage_local.go#L226-L236

可以登陆宿主机，执行命令看下输出的是什么：

```bash
# 比如要看 /opt/cloud/workspace/disks 目录对应的 medium type 是什么
$ lsblk -d -o name,rota $(df -P /opt/cloud/workspace/disks | awk 'NR==2{print $1}') 
NAME ROTA
sdc3    1  # ROTA 为1表示机械盘
```

**Comment by C4a15Wh** [comment]
```
root@gpu-worker-04:~# lsblk -d -o name,rota $(df -P /opt/cloud/workspace/disks | awk 'NR==2{print $1}')
NAME ROTA
sda1    1
root@gpu-worker-04:~#
```
这边输出的是机械盘

**Comment by C4a15Wh** [comment]
已手动修正介质类型
