### ISSUE TITLE
[求助/Help] 服务器以前是计算节点，现在重装安装了一下，安装为控制节点，然后执行命令如下图，此问题如何解决

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#17563]
![image](https://github.com/yunionio/cloudpods/assets/58723494/9c2dbec2-aa41-4c61-837f-93d0a5b3532e)

截图中的192.168.1.12在网卡中配置的是DNS1，为啥打印会报IP：53的问题？

**Comment by szz1113-1119** [comment]
另外，此服务器以前是另一个控制节点的计算节点，我已经卸载完成了，但是我装完此服务器为控制节点后，再添加自身为控制节点时，会报节点已存在。
![image](https://github.com/yunionio/cloudpods/assets/58723494/1ba47f2d-a0bd-49cd-ad3d-a82beb4ae827)

**Comment by szz1113-1119** [comment]
另外添加计算节点时，报如下错误
![image](https://github.com/yunionio/cloudpods/assets/58723494/783b5fab-95fd-4b3a-9559-3bbfc1828b26)

**Comment by hoganlxj** [comment]
> 另外，此服务器以前是另一个控制节点的计算节点，我已经卸载完成了，但是我装完此服务器为控制节点后，再添加自身为控制节点时，会报节点已存在。 ![image](https://user-images.githubusercontent.com/58723494/254234895-1ba47f2d-a0bd-49cd-ad3d-a82beb4ae827.png)

这台机器本身已经是k8s的节点，不能再次添加。另外，cloudpods的控制节点/计算节点可以是同一台服务器。
在cloudpods控制节点上启用host-agent后，该节点就可以变为计算节点。命令如下
for node in `kubectl get nodes | awk 'NR>1 {print $1}'`; do ocadm node enable-host-agent --node $node; done

**Comment by hoganlxj** [comment]
> 另外添加计算节点时，报如下错误 ![image](https://user-images.githubusercontent.com/58723494/254237204-783b5fab-95fd-4b3a-9559-3bbfc1828b26.png)

@szz1113-1119 看下ocadm的版本是多少？
在cloudpods的控制节点执行 ocadm version 
cloudpods的是那个版本？

**Comment by zhasm** [comment]
@szz1113-1119 
完全卸载的命令。注意，最后有一个reboot，需要重启机器，来卸载虚拟网卡。
```bash
kubeadm reset -f;
/opt/yunion/bin/ocadm reset -f
rm -rf /etc/kubernetes/ /var/lib/etcd/
reboot
```

**Comment by szz1113-1119** [comment]
> @szz1113-1119 完全卸载的命令。注意，最后有一个reboot，需要重启机器，来卸载虚拟网卡。
> 
> ```shell
> kubeadm reset -f;
> /opt/yunion/bin/ocadm reset -f
> rm -rf /etc/kubernetes/ /var/lib/etcd/
> reboot
> ```

你好，我根据你提供的完全卸载命令进行了操作，对234服务器进行卸载后，在控制节点62.49上重新添加234为计算节点，发现有两个问题，
第一，以前添加计算节点时，234服务器会重启，但这次不重启了，如下图所示：
![image](https://github.com/yunionio/cloudpods/assets/58723494/179153fd-6855-41ab-80f6-91abe401cbf2)

第二，添加完成后，发现，nodes有234节点了，但是没有添加对应的chassis id，如下图所示，
![image](https://github.com/yunionio/cloudpods/assets/58723494/870995c5-99e4-44f1-aeb0-023c29679fbb)

从而导致在页面也没有刷新出对应的宿主机

climc host-list无法查到234服务器的计算节点。

**Comment by hoganlxj** [comment]
@szz1113-1119 

> > @szz1113-1119 完全卸载的命令。注意，最后有一个reboot，需要重启机器，来卸载虚拟网卡。
> > ```shell
> > kubeadm reset -f;
> > /opt/yunion/bin/ocadm reset -f
> > rm -rf /etc/kubernetes/ /var/lib/etcd/
> > reboot
> > ```
> 
> 你好，我根据你提供的完全卸载命令进行了操作，对234服务器进行卸载后，在控制节点62.49上重新添加234为计算节点，发现有两个问题， 第一，以前添加计算节点时，234服务器会重启，但这次不重启了，如下图所示： ![image](https://user-images.githubusercontent.com/58723494/254304436-179153fd-6855-41ab-80f6-91abe401cbf2.png)
> 
> 第二，添加完成后，发现，nodes有234节点了，但是没有添加对应的chassis id，如下图所示， ![image](https://user-images.githubusercontent.com/58723494/254304239-870995c5-99e4-44f1-aeb0-023c29679fbb.png)
> 
> 从而导致在页面也没有刷新出对应的宿主机
> 
> climc host-list无法查到234服务器的计算节点。

@szz1113-1119   在控制节点执行  climc network-list --limit 0 
看下返回结果是否有 234服务器的IP子网，若没有，请创建包含宿主机网段的IP子网 。
