### ISSUE TITLE
[BUG]添加计算节点成功，无法显示

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#17577]
**问题描述/What happened**:

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):kylinos v10 aarch
- Kernel (e.g. `uname -a`):4.19.90
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):3.10

查看注册宿主机
[root@cloudpods-1 ~]# climc host-list
***  Total: 0  ***
[root@cloudpods-1 ~]# kubectl -n onecloud get pods -o wide | grep 10.1.99.30 
default-host-health-h2glj                           1/1     Running            0          5h18m   10.1.99.30      cloudpods-s1   <none>           <none>
default-host-image-gfprr                            1/1     Running            0          5h18m   10.1.99.30      cloudpods-s1   <none>           <none>
default-host-mrctx                                  3/3     Running               1          5h18m   10.1.99.30      cloudpods-s1   <none>           <none>
default-telegraf-4r8n7                              1/1     Init:CrashLoopBackOff            0          5h18m   10.1.99.30      cloudpods-s1   <none>           <none>

通过查看docker日志，发现缺少/etc/telegraf/telegraf.conf 。判断为缺少telegraf的安装和配置导致

**Comment by zhasm** [comment]
@lvzhiweilv 
重启 telegraf  相关pod？

**Comment by lvzhiweilv** [comment]
重启之后计算节点的状态
[root@cloudpods-1 ~]# kubectl get pods -A  -o wide | grep telegraf
onecloud             default-telegraf-r4mmm                              0/1     Init:CrashLoopBackOff   4          102s    10.1.99.30      cloudpods-s1   <none>           <none>
查看pods中docker日志如下：
[root@cloudpods-S1 ~]# docker logs -f b1f90aee84af
2023/07/20 07:53:17 stat telegraf config file error stat /etc/telegraf/telegraf.conf: no such file or directory

**Comment by lvzhiweilv** [comment]
> 重启之后计算节点的状态 [root@cloudpods-1 ~]# kubectl get pods -A -o wide | grep telegraf onecloud default-telegraf-r4mmm 0/1 Init:CrashLoopBackOff 4 102s 10.1.99.30 cloudpods-s1 查看pods中docker日志如下： [root@cloudpods-S1 ~]# docker logs -f b1f90aee84af 2023/07/20 07:53:17 stat telegraf config file error stat /etc/telegraf/telegraf.conf: no such file or directory
应该是添加计算节点的脚本中没有安装和配置相关服务

**Comment by hoganlxj** [comment]
@lvzhiweilv  计算节点是物理机吗？发下添加计算节点的命令？

**Comment by wanyaoqi** [comment]
@lvzhiweilv telegraf 服务依赖 host-agent 启动成功，查看一下 host-agent 日志
`kubectl logs -n onecloud -c host <host POD> `

**Comment by lvzhiweilv** [comment]
> @lvzhiweilv 计算节点是物理机吗？发下添加计算节点的命令？

是物理机 ./ocboot.py add-node 10.1.1.12 10.1.99.30

**Comment by lvzhiweilv** [comment]
> 

[root@cloudpods-1 ~]# kubectl logs -n onecloud -c host default-host-mrctx| more
[info 230720 00:59:30 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 230720 00:59:30 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/host.conf
[warning 230720 00:59:30 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument disk-is-ssd
[warning 230720 00:59:30 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-qmp-monitor
[warning 230720 00:59:30 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-health-checker
[warning 230720 00:59:30 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument enable-rbac
[warning 230720 00:59:30 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1214)] Cannot find argument health-driver
[info 230720 00:59:30 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-20 00:59:30 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/common/common.conf
[info 2023-07-20 00:59:30 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-20 00:59:30 hostman.(*SHostService).InitService(host_services.go:63)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-07-20 00:59:30 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-20 00:59:30 appsrv.NewApplication(appsrv.go:116)] App hostId: 4fDlUDl6XrIb-LdigCU19aN-zRQ= (host,cloudpods-S1,10.1.99.30)
2023/07/20 00:59:30 Allow hosts []
[info 2023-07-20 00:59:30 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-20 00:59:30 hostinfo.DetectCpuInfo(hostinfohelper.go:77)] cpuinfo freq 0
[error 2023-07-20 00:59:30 sysutils.ParseCPUInfo(sysutils.go:122)] Failed to get cpu MHz
[error 2023-07-20 00:59:30 sysutils.ParseCPUInfo(sysutils.go:125)] Failed to get cpu cache size
[info 2023-07-20 00:59:30 hostinfo.NewHostInfo(hostinfo.go:2243)] CPU Model Phytium,FT-2000+/64 Microcode 2
[info 2023-07-20 00:59:30 hostinfo.NewHostInfo(hostinfo.go:2264)] Get kubelet container image Fs: /opt/docker, eviction config: {"evictionHard":{"imagefs.available":{"Signal":"i
magefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"memory.available":{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"1
00Mi","Percentage":0}},"nodefs.available":{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"nodefs.inodesFree":{"Signal":"nodefs.i
nodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}}}}
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:404)] I/O Scheduler switch to bfq
[info 2023-07-20 00:59:32 fileutils2.ChangeBlkdevParameter(fileutils.go:202)] Set queue/scheduler of sdb to bfq
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).Init(hostinfo.go:196)] Start detectHostInfo
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:855)] KVM API VERSION 12
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:860)] KVM CAP MAX VCPUS: 512
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:868)] KVM CAP NR VCPUS: 64
[error 2023-07-20 00:59:32 sysutils.isNestSupport(kvm.go:160)] exit status 1
[error 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectOsDist(hostinfo.go:740)] exit status 1
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectOsDist(hostinfo.go:750)] DetectOsDist  
[error 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectOsDist(hostinfo.go:752)] Failed to detect distribution info
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectQemuVersion(hostinfo.go:822)] Detect qemu version is 4.2.0
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectOvsVersion(hostinfo.go:963)] Detect OVS version is 2.10.5
[info 2023-07-20 00:59:32 hostinfo.(*SHostInfo).detectOvsKOVersion(hostinfo.go:980)] kernel module openvswitch vermagic:       4.19.90-24.4.v2101.ky10.aarch64 SMP mod_unload mod
versions aarch64
WARNING: failed to determine memory area for node: open /sys/devices/system/node/node2/hugepages: no such file or directory
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).Init(hostinfo.go:207)] Start parseConfig
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).generateLocalNetworkConfig(hostinfo.go:238)] Find dev: br0 ip: 10.1.99.30
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).generateLocalNetworkConfig(hostinfo.go:258)] port eno1 link type device
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).generateLocalNetworkConfig(hostinfo.go:294)] bridge name br0
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).parseConfig(hostinfo.go:308)] Generate network config eno1/br0/10.1.99.30
[info 2023-07-20 00:59:33 hostinfo.NewNIC(hostinfohelper.go:233)] IP 10.1.99.30/br0/eno1
[info 2023-07-20 00:59:33 hostinfo.NewNIC(hostinfohelper.go:286)] Confirm to configuration!!
[info 2023-07-20 00:59:33 hostinfo.(*SNIC).SetupDhcpRelay(hostinfohelper.go:202)] Not enable dhcp relay on nic: &hostinfo.SNIC{Inter:"eno1", Bridge:"br0", Ip:"10.1.99.30", Netwo
rk:"", WireId:"", Mask:24, Bandwidth:1000, BridgeDev:(*hostbridge.SOVSBridgeDriver)(0x4001773470), dhcpServer:(*hostdhcp.SGuestDHCPServer)(0x40018549f0)}
[info 2023-07-20 00:59:33 hostinfo.(*SHostInfo).setupOvnChassis(hostinfo.go:225)] Start setting up ovn chassis
[info 2023-07-20 00:59:33 hostman.(*SHostService).RunService.func1(host_services.go:83)] Auth complete!!
[info 2023-07-20 00:59:33 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-07-20 00:59:33 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-07-20 00:59:33 storageman.StartSnapshotRecycle(storage_base.go:484)] Snapshot recyle job started
[info 2023-07-20 00:59:33 guestman.NewGuestCpuSetCounter(guesthelper.go:187)] NewGuestCpuSetCounter from topo: {"architecture":"numa","nodes":[{"caches":[{"level":1,"logical_pro
cessors":[0],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[1],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[2],"size_byte
s":32768,"type":"instruction"},{"level":1,"logical_processors":[3],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[4],"size_bytes":32768,"type":"instru
ction"},{"level":1,"logical_processors":[5],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[6],"size_bytes":32768,"type":"instruction"},{"level":1,"log
ical_processors":[7],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[0],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[1],"size_byt
es":32768,"type":"data"},{"level":1,"logical_processors":[2],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[3],"size_bytes":32768,"type":"data"},{"level":1,"
logical_processors":[4],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[5],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[6],"size_bytes":
32768,"type":"data"},{"level":1,"logical_processors":[7],"size_bytes":32768,"type":"data"},{"level":2,"logical_processors":[0,1,2,3],"size_bytes":33554432,"type":"unified"},{"le
vel":2,"logical_processors":[4,5,6,7],"size_bytes":33554432,"type":"unified"}],"cores":[{"id":0,"index":0,"logical_processors":[0],"total_threads":1},{"id":1,"index":1,"logical_
processors":[1],"total_threads":1},{"id":2,"index":2,"logical_processors":[2],"total_threads":1},{"id":3,"index":3,"logical_processors":[3],"total_threads":1},{"id":4,"index":4,
"logical_processors":[4],"total_threads":1},{"id":5,"index":5,"logical_processors":[5],"total_threads":1},{"id":6,"index":6,"logical_processors":[6],"total_threads":1},{"id":7,"
index":7,"logical_processors":[7],"total_threads":1}],"distances":[10,20,40,30,20,30,50,40],"id":0,"memory":{"supported_page_sizes":[2097152,536870912],"total_physical_bytes":33
285996544,"total_usable_bytes":32273596416}},{"caches":[{"level":1,"logical_processors":[8],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[9],"size_by
tes":32768,"type":"instruction"},{"level":1,"logical_processors":[10],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[11],"size_bytes":32768,"type":"in
struction"},{"level":1,"logical_processors":[12],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[13],"size_bytes":32768,"type":"instruction"},{"level":
1,"logical_processors":[14],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[15],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors
":[8],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[9],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[10],"size_bytes":32768,"type":"dat
a"},{"level":1,"logical_processors":[11],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[12],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors"
:[13],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[14],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[15],"size_bytes":32768,"type":"da
ta"},{"level":2,"logical_processors":[8,9,10,11],"size_bytes":33554432,"type":"unified"},{"level":2,"logical_processors":[12,13,14,15],"size_bytes":33554432,"type":"unified"}],"
cores":[{"id":10,"index":0,"logical_processors":[10],"total_threads":1},{"id":11,"index":1,"logical_processors":[11],"total_threads":1},{"id":12,"index":2,"logical_processors":[
12],"total_threads":1},{"id":13,"index":3,"logical_processors":[13],"total_threads":1},{"id":14,"index":4,"logical_processors":[14],"total_threads":1},{"id":15,"index":5,"logica
l_processors":[15],"total_threads":1},{"id":8,"index":6,"logical_processors":[8],"total_threads":1},{"id":9,"index":7,"logical_processors":[9],"total_threads":1}],"distances":[2
0,10,30,20,30,20,40,30],"id":1,"memory":{"supported_page_sizes":[2097152,536870912],"total_physical_bytes":34359738368,"total_usable_bytes":33214431232}}]}
[info 2023-07-20 00:59:33 hostdhcp.(*SGuestDHCPServer).Start(dhcpserver.go:72)] SGuestDHCPServer starting ...
[info 2023-07-20 00:59:33 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:134)] KVM max cpus count: 64
[info 2023-07-20 00:59:33 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:152)] Machine type virt max cpus: 64
[error 2023-07-20 00:59:35 hostinfo.(*SHostInfo).GetMasterNicIpAndMask(hostinfo.go:988)] MasterNic (*netutils2.SNetInterface)(nil)
[error 2023-07-20 00:59:35 hostinfo.(*SHostInfo).onFail(hostinfo.go:1068)] register failed: try create network: find_matched == false
[error 2023-07-20 00:59:35 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...
goroutine 706 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x20
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x60
panic({0x214e6a0, 0x2dc5410})
	/usr/lib/go/src/runtime/panic.go:838 +0x20c
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0x4000c8e180, {0x214e6a0?, 0x2dc5420?})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1070 +0xd8
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).tryCreateNetworkOnWire(0x4d68b00?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1095 +0x5a0
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).fetchAccessNetworkInfo(0x4000c8e180)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1128 +0x588
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0x40011b7901?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1055 +0x28
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x60
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x70
[error 2023-07-20 01:00:05 hostinfo.(*SHostInfo).GetMasterNicIpAndMask(hostinfo.go:988)] MasterNic (*netutils2.SNetInterface)(nil)
[error 2023-07-20 01:00:05 hostinfo.(*SHostInfo).onFail(hostinfo.go:1068)] register failed: try create network: find_matched == false
[error 2023-07-20 01:00:05 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...

**Comment by zexi** [comment]
@lvzhiweilv 这里有一些排查计算节点 host 服务启动失败的文档，可以参考下：https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/#%E6%9F%A5%E7%9C%8Bhost%E6%9C%8D%E5%8A%A1%E7%9A%84%E6%97%A5%E5%BF%97

**Comment by zexi** [comment]
> [error 2023-07-20 00:59:35 hostinfo.(*SHostInfo).GetMasterNicIpAndMask(hostinfo.go:988)] MasterNic (*netutils2.SNetInterface)(nil)
[error 2023-07-20 00:59:35 hostinfo.(*SHostInfo).onFail(hostinfo.go:1068)] register failed: try create network: find_matched == false
[error 2023-07-20 00:59:35 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...
goroutine 706 [running]:
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
/usr/lib/go/src/runtime/debug/stack.go:16 +0x20
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x60
panic({0x214e6a0, 0x2dc5410})
/usr/lib/go/src/runtime/panic.go:838 +0x20c
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0x4000c8e180, {0x214e6a0?, 0x2dc5420?})
/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1070 +0xd8
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).tryCreateNetworkOnWire(0x4d68b00?)
/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1095 +0x5a0
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).fetchAccessNetworkInfo(0x4000c8e180)
/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1128 +0x588
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0x40011b7901?)
/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1055 +0x28
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x60
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x70
[error 2023-07-20 01:00:05 hostinfo.(*SHostInfo).GetMasterNicIpAndMask(hostinfo.go:988)] MasterNic (*netutils2.SNetInterface)(nil)
[error 2023-07-20 01:00:05 hostinfo.(*SHostInfo).onFail(hostinfo.go:1068)] register failed: try create network: find_matched == false
[error 2023-07-20 01:00:05 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...

@lvzhiweilv 应该是没有找到宿主机对应的网络，需要创建下，参考这个文档解决：https://www.cloudpods.org/zh/docs/ops/hosterror/#%E5%AE%BF%E4%B8%BB%E6%9C%BA%E7%9A%84host%E6%9C%8D%E5%8A%A1%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5%E4%B8%94%E6%8A%A5%E9%94%99fail-to-get-network-infono-networks%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3

**Comment by lvzhiweilv** [comment]
climc network-create bcast0 host02  10.168.222.226  10.168.222.226 24 --gateway 10.168.222.1
链接中的各种信息该如何和现有环境对应。谢谢

**Comment by zexi** [comment]
> climc network-create bcast0 host02 10.168.222.226 10.168.222.226 24 --gateway 10.168.222.1 链接中的各种信息该如何和现有环境对应。谢谢

@lvzhiweilv 执行下面的命令看下添加的计算的网络信息，麻烦把下面命令的输出贴下，需要根据当前节点的网络信息对应下：

```bash
# 查看网卡 ip
$ ip a

# 查看路由
$ ip route
```

**Comment by lvzhiweilv** [comment]
> 
#计算节点
[root@cloudpods-S1 ~]# ip ad 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master ovs-system state UP group default qlen 1000
    link/ether b4:05:5d:9a:46:68 brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b4:05:5d:9a:46:69 brd ff:ff:ff:ff:ff:ff
4: eno3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether b4:05:5d:9a:46:66 brd ff:ff:ff:ff:ff:ff
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether b4:05:5d:9a:46:67 brd ff:ff:ff:ff:ff:ff
6: cni0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether ee:22:c7:3e:e5:e7 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.1/16 brd 10.88.255.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::ec22:c7ff:fe3e:e5e7/64 scope link 
       valid_lft forever preferred_lft forever
9: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether a6:0e:95:ec:f6:69 brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.1/32 brd 10.96.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.101.127.185/32 brd 10.101.127.185 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.101.245.128/32 brd 10.101.245.128 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.103.17.226/32 brd 10.103.17.226 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.108.244.162/32 brd 10.108.244.162 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.100.71.19/32 brd 10.100.71.19 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.109.225.60/32 brd 10.109.225.60 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.109.74.241/32 brd 10.109.74.241 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.101.71.222/32 brd 10.101.71.222 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.106.88.88/32 brd 10.106.88.88 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.101.190.223/32 brd 10.101.190.223 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.109.128.228/32 brd 10.109.128.228 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.103.137.78/32 brd 10.103.137.78 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.107.170.124/32 brd 10.107.170.124 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.104.126.171/32 brd 10.104.126.171 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.101.6.133/32 brd 10.101.6.133 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.110.136.245/32 brd 10.110.136.245 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.111.191.220/32 brd 10.111.191.220 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.103.174.245/32 brd 10.103.174.245 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.106.120.156/32 brd 10.106.120.156 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.102.201.44/32 brd 10.102.201.44 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.98.94.168/32 brd 10.98.94.168 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.109.85.101/32 brd 10.109.85.101 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.110.28.135/32 brd 10.110.28.135 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.99.60.244/32 brd 10.99.60.244 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.26.135/32 brd 10.96.26.135 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.219.167/32 brd 10.96.219.167 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.111.236.46/32 brd 10.111.236.46 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
10: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ee:56:28:b7:0e:09 brd ff:ff:ff:ff:ff:ff
11: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether b4:05:5d:9a:46:68 brd ff:ff:ff:ff:ff:ff
    inet 10.1.99.30/24 brd 10.1.99.255 scope global br0
       valid_lft forever preferred_lft forever
12: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.40.245.192/32 brd 10.40.245.192 scope global tunl0
       valid_lft forever preferred_lft forever
16: brvpc: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 7a:fb:6e:db:d6:47 brd ff:ff:ff:ff:ff:ff
17: brtap: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 1a:a6:74:5f:c7:48 brd ff:ff:ff:ff:ff:ff
20: caliec5b88df7a0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever

[root@cloudpods-S1 ~]# ip route
default via 10.1.99.254 dev br0 
10.1.99.0/24 dev br0 src 10.1.99.30 
10.40.19.128/26 via 10.1.1.15 dev tunl0 proto bird onlink 
10.40.72.0/26 via 10.1.1.13 dev tunl0 proto bird onlink 
10.40.84.64/26 via 10.1.1.14 dev tunl0 proto bird onlink 
blackhole 10.40.245.192/26 proto bird 
10.40.245.193 dev caliec5b88df7a0 scope link 
10.88.0.0/16 dev cni0 proto kernel scope link src 10.88.0.1 linkdown

**Comment by hoganlxj** [comment]
> 10.1.99.30
在部署cloudpods的控制节点上执行 
climc network-create bcast0 adm0 10.1.99.30 10.1.99.30 24 --gateway 10.1.99.254

**Comment by lvzhiweilv** [comment]
adm0这个ip子网已经存在，且是管理集群使用的ip网段10.1.1.13。bcast0这个二层网络也已经存在，这样还可以直接创建么

**Comment by hoganlxj** [comment]
> adm0这个ip子网已经存在，且是管理集群使用的ip网段10.1.1.13。bcast0这个二层网络也已经存在，这样还可以直接创建么
@lvzhiweilv 可以换成adm1
climc network-create bcast0 adm1 10.1.99.30 10.1.99.30 24 --gateway 10.1.99.254

**Comment by zhasm** [comment]
等xj有时间帮我模拟一下环境，我来测试、修复。
