### ISSUE TITLE
[Feature] 建议Daemon虚拟机 修改描述

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#17573]
<img width="267" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/5221082c-f9b7-4da8-852b-7748b0dc15be">

刚刚重启一台宿主机，发现vm 都没起来。搜索“自动启动”找到这个issue：https://github.com/yunionio/cloudpods/issues/12441

查询对应pr，才知道 “Daemon虚拟机” 是宿主机重启后，自动启动的意思，个人觉得这个概念/表述不太直观，在Google 中搜索“Daemon虚拟机” 也未找到其他类似的说法，大家知道daemon 进程的意思，但是daemon 虚拟机，国人估计一时难以理解为是守护的意思，
建议可否修改成 (开机自启动/Start at boot) 等类似的表达。

**Comment by fangpsh** [comment]
exsi，网上搜的图：
<img width="738" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/2f83a779-a14b-46dd-b6e7-2df40bcdd00c">

**Comment by jackgao2015** [comment]
@dengju2020  @yangqingwen666

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/4971

**Comment by dengju2020** [comment]
@fangpsh 感谢反馈，已优化文案。等月底发版即可更新。
