### ISSUE TITLE
[求助/Help]系统镜像一些问题

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17571]
大家好：
系统镜像如何修改小一点
![image](https://github.com/yunionio/cloudpods/assets/32296103/f8dd77a5-b06a-4528-a1c0-b2d99dc69243)
镜像缓存报错，请问如何安装agent,在文档中没有搜索到相关内容，
{
    "image_id": "dffdeed0-1700-49c2-81a9-8d3a35c8b047",
    "reason": {
        "__reason__": "fail to find valid ESXi agent",
        "__status__": "ERROR"
    }
}

**Comment by hoganlxj** [comment]
@shengxianli 系统镜像的最小磁盘容量不能往下调整。
在部署cloudpods的机器上查看有esxi-agent的pods，命令如下 
kubectl get pods -n onecloud |grep esxi-agent
若exsi-agent的pods存在，看下pods的日志是否有报错

**Comment by shengxianli** [comment]
@hoganlxj 谢谢回复  

default-esxi-agent-647766b788-fwsfn                  1/1     Running   4          6d5h

我这个是all in one的环境。刚发现这个问题也会导致无法创建虚拟机。挺奇怪。

**Comment by shengxianli** [comment]
@hoganlxj 
[root@cloudpods ~]# kubectl get pods -n onecloud |grep default-esxi-agent
default-esxi-agent-79f9b7fb8c-nqmlf                  1/1     Running   0          5m2s
[root@cloudpods ~]# kubectl logs -n onecloud default-esxi-agent-79f9b7fb8c-nqmlf -f 
[info 230720 07:47:27 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/esxi-agent.conf
[info 230720 07:47:27 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-20 07:47:27 service.(*SExsiAgentService).StartService(esxi_agent_service.go:50)] No cachepath, use default /opt/cloud/workspace/esxi_agent/image_cache
[info 2023-07-20 07:47:27 service.(*SExsiAgentService).StartService(esxi_agent_service.go:58)] No agent temp path, use default /opt/cloud/workspace/esxi_agent/agent_tmp
[info 2023-07-20 07:47:27 service.(*SExsiAgentService).InitLockman(esxi_agent_service.go:96)] using inmemory lockman
[info 2023-07-20 07:47:27 service.(*SExsiAgentService).StartService.func1(esxi_agent_service.go:69)] auth complete
[info 2023-07-20 07:47:27 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-07-20 07:47:27 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-07-20 07:47:27 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-20 07:47:27 appsrv.NewApplication(appsrv.go:116)] App hostId: UZ-RxUxdtUrWGyNCqTZ6Fn84Bhw= (esxi-agent,default-esxi-agent-79f9b7fb8c-nqmlf,10.40.244.218)
2023/07/20 07:47:27 Allow hosts []
[info 2023-07-20 07:47:27 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-20 07:47:27 agent.(*SBaseAgent).register(agent.go:139)] esxiagent esxiagent-10.40.244.218:701f4331-a814-4f14-86dd-e7c88aef1f12 register success, do offline
[info 2023-07-20 07:47:27 agent.(*SBaseAgent).startRegister(agent.go:118)] Register success!
[info 2023-07-20 07:47:27 app.ServeForeverExtended(app.go:57)] Start listen on https://0.0.0.0:30883, isMaster: true

**Comment by shengxianli** [comment]
@hoganlxj
我又进行了一次测试。发现如果我建立了2层网络和子网。，创建虚拟机和镜像缓存都会"reason": "fail to find valid ESXi agent",
如果不建立子网。直接导入VMware宿主机就不会有问题。

**Comment by dengju2020** [comment]
@swordqiu 帮忙看下这个问题

**Comment by swordqiu** [comment]
cloudpods有可用区（zone）的概念，IP子网都是在可用区方位内，通常可以根据IP地址判断资源的归属可用区。

fail to find valid ESXi agent 含义是在指定可用区找不到可用的EsxiAgent，EsxiAgent启动的时候，会根据配置里的zone参数或者是根据监听的IP地址判断归属的可用区。感觉是默认的esxiagent没有正常注册上来。或者是虚拟机在一个新的zone，该zone还未配置esxiagent。

fail to find zone of esxi：同样，在导入esxi宿主机的时候也需要根据esxi的IP地址查找对应的可用区。这个错误说明，找不到跟这台esxi宿主机匹配的IP子网。

**Comment by shengxianli** [comment]
@swordqiu 那这个是不是属于BUG了

**Comment by shengxianli** [comment]
@hoganlxj 系统镜像的最小磁盘容量不能往下调整  这个限制是不是考虑后续升级可以改下。在本地资源紧缺的情况下，有些服务其实并不需要这种稍大硬盘

**Comment by mrgaozy** [comment]
kubectl -n onecloud logs default-cloudpods-host-deployer-9kj7p
[info 240711 12:18:51 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 240711 12:18:51 options.parseOptions(options.go:359)] Set log level to "info"
[info 2024-07-11 12:18:51 options.parseOptions(options.go:336)] Use configuration file: /etc/yunion/common/common.conf
[info 2024-07-11 12:18:51 options.parseOptions(options.go:359)] Set log level to "info"
[info 2024-07-11 12:18:51 deployserver.(*SDeployService).InitService(deployserver.go:481)] exec socket path: /var/run/onecloud/exec.sock
[error 2024-07-11 12:18:51 seclib2.InitTLSConfig(tls.go:129)] read tls certfile fail open /etc/yunion/pki/service.crt: no such file or directory
[error 2024-07-11 12:18:51 mcclient.NewClient(mcclient.go:67)] load TLS failed open /etc/yunion/pki/service.crt: no such file or directory
[error 2024-07-11 12:18:51 auth.(*authManager).startRefreshRevokeTokens(auth.go:193)] refreshRevokeTokens: No valid admin token credential
[error 2024-07-11 12:18:51 auth.(*authManager).authAdmin(auth.go:269)] Admin auth failed: {"error":{"class":"UserNotFound","code":404,"details":"idp: UserNotFound","request":{"body":"{\"auth\":{\"context\":{\"source\":\"srv\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"domain\":...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"238","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-cloudpods-keystone:30357","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"eed9b25f"},"method":"POST","url":"https://default-cloudpods-keystone:30357/v3/auth/tokens"}}}
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/log.Fatalf({0x132f308, 0x19}, {0xc00066d4b8, 0x1, 0x1})
	/root/go/src/yunion.io/x/onecloud/vendor/yunion.io/x/log/log.go:138 +0x32
yunion.io/x/onecloud/pkg/mcclient/auth.AsyncInit(0xc00046eae0, 0x80?, 0xf2?, {0xc000954fa0, 0xc000625568?}, {0xc000954fe0, 0x7f8d86a6a5b8?}, 0x0)
	/root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go:448 +0xd9
yunion.io/x/onecloud/pkg/mcclient/auth.Init(...)
	/root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go:455
yunion.io/x/onecloud/pkg/cloudcommon/app.InitAuth(0x1fe6c20, 0x13b07b8)
	/root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/app/auth.go:75 +0x40c
yunion.io/x/onecloud/pkg/hostman/hostdeployer/deployserver.(*SDeployService).InitService(0xc000210800)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostdeployer/deployserver/deployserver.go:487 +0x218
yunion.io/x/onecloud/pkg/cloudcommon/service.(*SServiceBase).StartService(0xc000128438)
	/root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/service/services.go:53 +0x9b
main.main()
	/root/go/src/yunion.io/x/onecloud/cmd/host-deployer/main.go:28 +0xe5
[fatal 2024-07-11 12:18:51 auth.AsyncInit(auth.go:448)] Auth manager init err: authAdmin: {"error":{"class":"UserNotFound","code":404,"details":"idp: UserNotFound","request":{"body":"{\"auth\":{\"context\":{\"source\":\"srv\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"domain\":...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"238","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-cloudpods-keystone:30357","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"eed9b25f"},"method":"POST","url":"https://default-cloudpods-keystone:30357/v3/auth/tokens"}}}
所有的 default-cloudpods-host-deployer 都报这个错误
