### ISSUE TITLE
维护模式无法进入

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#17596]
1、三台服务器的混构集群。2台鲲鹏服务器1台x86服务器。
2、primary_master_node master_nodes 为鲲鹏服务器，还有一台计算节点是x86服务器。
3、目前想把master_nodes 节点服务器下线，让整个集群正常工作。web上面master_nodes 无法进入维护模式，master_nodes 关机整个集群功能出现异常。虚拟机正常。求解怎么解决？
版本为3.9.12
如果直接按照这个https://www.cloudpods.org/zh/docs/setup/removehost/方式执行会不会也导致集群崩溃?

**Comment by zhongyong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/8031587/6bea72d6-1852-4310-bd29-22c524b2ddc3)
镜像无法获取

**Comment by hoganlxj** [comment]
@zhongyong 几台控制节点？

**Comment by zhongyong** [comment]
开始的时候根据这个部署的？看起像2个控制节点。 最好一台node2节点是x86是最后添加的。
![image](https://github.com/yunionio/cloudpods/assets/8031587/f04c3121-46ce-481e-995a-9ec393cc4eb5)
66 67是集群

**Comment by hoganlxj** [comment]
@zhongyong  66是不能下线的，因为数据库在66上。如下线67，服务会起到66上，不会影响整个平台使用

**Comment by zhongyong** [comment]
67下线了镜像功能没法使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月24日(周一) 中午1:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] 维护模式无法进入 (Issue #17596)




 
@zhongyong  66是不能下线的，因为数据库在66上。如下线67，服务会起到66上，不会影响整个平台使用

**Comment by hoganlxj** [comment]
> @zhongyong 66是不能下线的，因为数据库在66上。如下线67，服务会起到66上，不会影响整个平台使用

@zhongyong 登陆到66，看下服务的pods，看有那些服务没有起来？

**Comment by zhongyong** [comment]
好的，晚点试试，目前就是67下线了没的把67的pod迁移到66上面。




钟勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] 维护模式无法进入 (Issue #17596)





  
@zhongyong 66是不能下线的，因为数据库在66上。如下线67，服务会起到66上，不会影响整个平台使用
  
@zhongyong 登陆到66，看下服务的pods，看有那些服务没有起来？
