### ISSUE TITLE
[求助/Help]新建完虚拟机后，连接报超时

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#17595]
![1690166424410](https://github.com/yunionio/cloudpods/assets/58723494/68316c29-a2d6-4b1a-bb28-3fc755a681bf)
请问这个是怎么回事？

**Comment by hoganlxj** [comment]
@szz1113-1119 可以vnc登陆进去看下，虚拟机启动完成没？ 另外，可以看下虚拟机的sshd服务是否正常，以及是否允许root登陆？

**Comment by szz1113-1119** [comment]
![1690176419552](https://github.com/yunionio/cloudpods/assets/58723494/34327c53-988a-4bb0-a3b6-244e58d6de17)
VNC无法进入

**Comment by hoganlxj** [comment]
> ![1690176419552](https://user-images.githubusercontent.com/58723494/255489630-34327c53-988a-4bb0-a3b6-244e58d6de17.png) VNC无法进入
@szz1113-1119 是没有进入系统，看着是系统镜像有问题，可以额换个镜像试下？

**Comment by yindex** [comment]
可能是启动顺序问题？

**Comment by hoganlxj** [comment]
@yindex 可以修改下虚拟机的引导顺序，再重启试下，若还是出现上面的问题，应该是镜像本身有问题
![image](https://github.com/yunionio/cloudpods/assets/32036395/697feac1-db87-4a06-8b49-3e22c67aa719)
