### ISSUE TITLE
[求助/Help]image服务异常排查方法

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#17609]
在准备添加系统镜像及主机镜像时报错
{
  "class": "ServiceAbnormal",
  "code": 499,
  "details": "image服务异常，请检查服务状态",
  "time": "2023-07-24T16:49:33+08:00"
}
该如何排查，谢谢

**Comment by yangqingwen666** [comment]
> 在准备添加系统镜像及主机镜像时报错 { "class": "ServiceAbnormal", "code": 499, "details": "image服务异常，请检查服务状态", "time": "2023-07-24T16:49:33+08:00" } 该如何排查，谢谢

第一步查一下服务名：kubectl get pods -A |grep glance
第二步查一下服务的日志看一下：kubectl logs -n onecloud default-glance-xxxxxx-xxxxxx -f
![753d2de6-b79b-4b26-b7fe-afb56dd70551](https://github.com/yunionio/cloudpods/assets/107830554/a6e3659b-ca9f-4702-9c59-f3a2ac40a25c)

**Comment by lvzhiweilv** [comment]
[root@cloudpods-1 opt]# kubectl logs -n onecloud default-glance-67cfddbdc6-zhxsf -f
[debug 230724 09:52:49 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize guestimagejoints
[info 230724 09:52:49 options.ParseOptions(options.go:314)] Use configuration file: /etc/yunion/glance.conf
[info 230724 09:52:49 options.ParseOptions(options.go:336)] Set log level to "info"
[info 2023-07-24 09:52:49 service.StartService(service.go:84)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-07-24 09:52:49 service.StartService(service.go:90)] Target image formats []string{"qcow2", "vmdk"}
[info 2023-07-24 09:52:50 service.StartService.func1(service.go:93)] Auth complete!!
[info 2023-07-24 09:52:50 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-07-24 09:52:50 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-07-24 09:52:50 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-07-24 09:52:50 appsrv.NewApplication(appsrv.go:116)] App hostId: atfDUDHeb4NT9kRQzMQ0A5mX7Vo= (image,default-glance-67cfddbdc6-zhxsf,10.40.19.143)
2023/07/24 09:52:50 Allow hosts []
[info 2023-07-24 09:52:50 appsrv.(*Application).SetDefaultTimeout(appsrv.go:132)] adjust application default timeout to 60.000000 seconds
[info 2023-07-24 09:52:50 cloudcommon.InitDB(database.go:79)] database dialect: mysql sqlStr: glance:kfS5Rhb6TVj8yzsq@tcp(10.1.1.16:3306)/glance?charset=utf8&parseTime=True
[info 2023-07-24 09:52:50 cloudcommon.InitDB(database.go:111)] using inmemory lockman
[info 2023-07-24 09:52:50 db.CheckSync(models.go:115)] Start check database schema: autoSync(true), enableChecksumTables(false), skipInitChecksum(false)
[info 2023-07-24 09:52:50 db.setDbConnection(database.go:60)] Total 43 db workers, set db connection max
[info 2023-07-24 09:52:50 options.StartOptionManagerWithSessionDriver(manager.go:63)] OptionManager start to fetch service configs ...
[info 2023-07-24 09:52:50 options.optionsEquals(manager.go:114)] Options changed: {"storage_driver":["local","s3"]}
[info 2023-07-24 09:52:50 service.StartService(service.go:115)] deploy server socket path: /var/run/onecloud/deploy.sock
[info 2023-07-24 09:52:50 app.ServeForeverExtended(app.go:57)] Start listen on https://0.0.0.0:30292, isMaster: true
[fatal 2023-07-24 09:54:28 service.initS3(service.go:169)] failed init s3 client new minio client: fetchBuckets: client.ListBuckets: Get "http://minio.onecloud-minio:9000/": dial tcp: lookup minio.onecloud-minio on 10.96.0.10:53: no such host

**Comment by swordqiu** [comment]
这个错误是找不到minio的服务，只有高可用部署才会自动使用minio作为镜像存储。确认一下是否是高可用部署？看下minio的pod是否正常？

**Comment by lvzhiweilv** [comment]
使用ocboot部署的三节点高可用集群，kubectl get pods -A | grep minio ，没有minio的pod

**Comment by hoganlxj** [comment]
@lvzhiweilv 执行这个命令后，再看下有minio的pods没？
climc k8s-cluster-component-update --force system-default minio

**Comment by lvzhiweilv** [comment]
已解决
