### ISSUE TITLE
[BUG]虚拟机更名不成功

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17601]
**问题描述/What happened**:
ESXI虚拟机更名显示更新成功，但实际并未生效
![image](https://github.com/yunionio/cloudpods/assets/32296103/8c8c0a8a-4897-4be5-972c-d968fba03774)
![image](https://github.com/yunionio/cloudpods/assets/32296103/5bbba7e7-9878-4512-a421-973dfd382825)
![image](https://github.com/yunionio/cloudpods/assets/32296103/4553079f-4f5d-40b9-ac13-f51dfc7779b7)
**环境/Environment**:
v3.10.3

**Comment by ioito** [comment]
目前尚未支持同步更改esxi的虚拟机名称，只更新本地虚拟机名称

**Comment by shengxianli** [comment]
@ioito 收到谢谢

**Comment by hoganlxj** [comment]
已解决
