### ISSUE TITLE
ESXI安装Windows指定IP和登录密码不生效[BUG]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17613]
**问题描述/What happened**:
ESXI安装Windows指定IP和登录密码不生效
**环境/Environment**:
v3.10.3
![image](https://github.com/yunionio/cloudpods/assets/32296103/4284bc4a-26f1-4f47-bb3c-191886c6eeb9)
封装的系统镜像安装Windows指定IP和登录密码不生效，IP是DHCP生成的随机IP。密码使用的是封装镜像当时生成的密码

**Comment by swordqiu** [comment]
@shengxianli 这个问题跟 https://github.com/yunionio/cloudpods/issues/17646 重复了，抱歉没有及时回复。我们在哪里讨论吧。这个issue先关了。
