### ISSUE TITLE
[求助/Help] 在Centos7.9上安装报错

### ISSUE THREAD

**Issue by zhuhedong** [yunionio/cloudpods#17614]
安装的3.10版本 

![Weixin Screenshot_20230725164100](https://github.com/yunionio/cloudpods/assets/44915307/dc7bafa3-0fc1-466f-bf05-7f5f8b565f40)

**Comment by zhasm** [comment]
@zhuhedong 
手工执行以下，看看输出：
```bash
export KUBECONFIG=/etc/kubernetes/admin.conf
kubectl -n onecloud patch onecloudcluster default --type='json' -p '[{"op": "replace", "path": "/spec/productVersion", "value": "FullStack"}]'

```

**Comment by zhuhedong** [comment]
![Weixin Screenshot_20230725171014](https://github.com/yunionio/cloudpods/assets/44915307/3a08b6e0-612f-4688-9d49-bc5e59c146c9)

**Comment by hoganlxj** [comment]
@zhuhedong 看着k8s集群没有部署成功，是全新部署的环境吗？ 部署cloudpods的机器什么配置？

**Comment by zhasm** [comment]
@zhuhedong 完整重跑一遍部署流程，看看怎样？

**Comment by jackgao2015** [comment]
@zhasm 
看看是否有需要参考一下用户写的几个部署过程：
阿里云 https://juejin.cn/post/7254829363023446071
腾讯云 https://juejin.cn/post/7253605936145137725
Azure https://juejin.cn/post/7250025436016148541

**Comment by zhuhedong** [comment]
全新安装的系统，

**Comment by jackgao2015** [comment]
> 全新安装的系统，

@zhuhedong 好的，是否可以重装一下系统，然后根据 https://juejin.cn/post/7254829363023446071 的命令行提示，重新安装一下？咱们是想体验私有云还是多云管理？

**Comment by zexi** [comment]
> 安装的3.10版本
> 
> ![Weixin Screenshot_20230725164100](https://user-images.githubusercontent.com/44915307/255844074-dc7bafa3-0fc1-466f-bf05-7f5f8b565f40.png)

@zhuhedong 这个报错看起来是 kube-apiserver 这个服务没有起来，因为连接 192.168.1.20:6443 服务拒绝了。

可以用下面命令看下 kube-apiserver 和 etcd 容器有没有启动

```bash
$ docker ps -a | egrep 'kube-apiserver|etcd'
```

**Comment by zhuhedong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/44915307/8c43b23f-f992-48c0-8f3b-d98a37de73b9)

**Comment by zhasm** [comment]
@zhuhedong 
看一下 kube-apiserver 对应docker container 的日志？

**Comment by zhuhedong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/44915307/5762795f-c39a-44b4-8b35-b31a853ac798)

**Comment by zhuhedong** [comment]
@zhasm 我已经重装了几次了， 反正各种问题。。。

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/44915307/256086648-5762795f-c39a-44b4-8b35-b31a853ac798.png)

@zhuhedong 这个报错是连不上 etcd ，需要看下 etcd 容器的日志，可以不用一直重装，先找到这个 etcd 启动不了的原因。
因为 etcd 起不来会导致后续的服务都启动不了。

**Comment by zhuhedong** [comment]
@zexi  出现了两个 
![image](https://github.com/yunionio/cloudpods/assets/44915307/476a1f12-1dc1-44f7-a863-b8867de70f60)

**Comment by zexi** [comment]
> @zexi 出现了两个 ![image](https://user-images.githubusercontent.com/44915307/256214822-476a1f12-1dc1-44f7-a863-b8867de70f60.png)

@zhuhedong 两个的日志都发下呢，另外也看下 /etc/kubernetes/pki/apiserver-etcd-client.crt 的证书日期对不对，用下面的命令：

```bash
openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt  -noout -text
```
