### ISSUE TITLE
[BUG] Cloudpods在Debian 10系统下不支持Ceph Pacific及更高的版本

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17628]
## 问题描述、环境: 
详见[#19573](https://github.com/yunionio/cloudpods/issues/17593)。

---

本篇主要提一下这个问题的原因，以及怎么彻底解决该问题。
## 原因
cloudpods目前向ceph集群查询信息，是通过在shell里面通过宿主机的ceph-common组件(/usr/bin/ceph)进行查询。但在debian10、centos7上的ceph-common最多更新到12.2.11(L版): 
```
root@master-02:/etc/apt# ceph -v
ceph version 12.2.11 (26dc3775efc7bb286a1d6d66faee0ba30ea23eee) luminous (stable)
root@master-02:/etc/apt#
```
这个版本**(L版)的ceph-common client仍然可以连接到ceph pacific的monitor server，但在执行其他操作时会出现timeout error**。考虑到代码相差久远，这确实是ceph项目内部向下兼容问题可能导致的事情，所以我个人认为cloudpods应该适配一下debian12，或者使用go-ceph代替ceph-common(本来这活也不该给ceph-common干啊！)
## 解决方案1
**警告: 本篇操作在[DontBreakDebian](https://wiki.debian.org/DontBreakDebian)中是不被推荐的，请勿在生产环境执行，如果有其他代替方案请勿尝试本issue的操作！！！**
先用debian stable的apt源代替当前的源
```
cd /etc/apt
#备份sources.list
cp sources.list sources.list.bak
rm sources.list
```
然后向source.list写入: 
```
deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free non-free-firmware
# deb-src http://mirrors.ustc.edu.cn/debian stable main contrib non-free non-free-firmware
deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free non-free-firmware
# deb-src http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free non-free-firmware

# deb http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free non-free-firmware
# deb-src http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free non-free-firmware
```
注意: 接下来的操作必须一口气完成，中间**不能退出登录**、**不能断开SSH**、**不能重启操作系统**！！
注意: 接下来的操作必须一口气完成，中间**不能退出登录**、**不能断开SSH**、**不能重启操作系统**！！
注意: 接下来的操作必须一口气完成，中间**不能退出登录**、**不能断开SSH**、**不能重启操作系统**！！
否则ssh连接会报错“kex_exchange_identification: Connection closed by remote host”，而且无法正常通过物理键鼠、iDRAC等方式登录系统！！！
**高危操作，请勿在生产环境执行，如有替代方案请勿执行此方案**
update本地源，并升级相关软件包
```
apt update
apt upgrade
apt install ceph-common
```
第一次安装大概率会失败，导致apt罢工。因为libc6:amd64包缺少libcrypt.so.1(libcrypt1:i386)，但又因为此时apt无法工作，所以需要手动添加相关动态链接库文件。
**P.S: 事前添加并没有效果，相关文件会被自动删除，所以需要装到一半的时候补一下。**
```
curl https://srdev.eos-chengdu-1.cmecloud.cn/Packages/libcrypt.a -o /usr/lib/x86_64-linux-gnu/libcrypt.a
curl https://srdev.eos-chengdu-1.cmecloud.cn/Packages/libcrypt.so.1 -o /usr/lib/x86_64-linux-gnu/libcrypt.so.1
curl https://srdev.eos-chengdu-1.cmecloud.cn/Packages/libcrypt.so -o /usr/lib/x86_64-linux-gnu/libcrypt.so
```
补全后需要手动fix-broken，然后再次安装ceph-common
```
apt -f install
apt install ceph-common
```
之后ceph-common的版本即变更为ceph pacific: 
```
root@master-03:/etc/apt# ceph -v
ceph version 16.2.11 (3cf40e2dca667f68c6ce3ff5cd94f01e711af894) pacific (stable)
root@master-03:/etc/apt#
```
然后收一下尾，更改/etc/default/grub下的GRUB_DEFAULT值，使update后的内核版本不变，避免新内核出现兼容问题，该操作就不再赘述。
## 方案1操作失败的补救方法
如果你是个笨比，不小心关掉了ssh，或者有其他情况导致安装中断，而且进不去系统，你需要挂载并启动到[debian 12安装镜像](https://mirrors.163.com/debian-cd/current/amd64/iso-cd/debian-12.1.0-amd64-netinst.iso)并以rescue-mode启动，配置好网络和键盘，然后在机器上的主分区启动一个shell，并继续未完成的操作，操作结束后重启即可正常启动。
## 解决方案2
更改cephutils(yunion.io/x/onecloud/pkg/util/cephutils)的源代码，引入[go-ceph](https://github.com/ceph/go-ceph)代替宿主机的ceph-common。  
笔者自己改了一个版本，试了一下是可行的，不过由于时间和精力原因没能进一步测试。  
cloudpods的todolist里面也有使用go-ceph代替ceph-common的方案的计划，想必也是在做了，这个方案就需要yunion的朋友们落实了。
~~另外能不能别用hard-code啊，我看到现场拼接字符串生成ceph.conf和keyring的时候真的没绷住，拜托拜托~~

**Comment by wanyaoqi** [comment]
@C4a15Wh 感谢反馈，在 debian 操作系统上使用 ceph-common 是在支持 debian 上没考虑到的问题。
go-ceph 每个 version 支持的 ceph 版本也是有限的，使用 ceph-common 的目的应该是让使用者安装与 ceph 集群匹配版本的客户端

**Comment by wanyaoqi** [comment]
并且我们还遇到过一些基于 ceph 二次开发的厂商，由于他们不能够完全的兼容 ceph 标准库，所以使用 go-ceph 也会有一些问题

**Comment by zexi** [comment]
@C4a15Wh 这个文档里面有说明一些使用 ceph-common 命令行工具的原因：
https://www.cloudpods.org/zh/docs/development/ceph/

**Comment by C4a15Wh** [comment]
方案1其实就是直接把系统升级到debian12，然后再安装相关软件包...  
由于libc存在依赖问题，实际上还会动libvirt之类的库，因此**不能有虚拟机在被升级的宿主机上运行**。  
而且这个操作对宿主机环境有严苛要求，一般来讲在minimal模式下安装的系统可以顺利升级，但实测如果宿主机存在某软件包**依赖debian10版本的其他软件包**并且**在debian12没有对应升级版软件包**，就会导致升级无法正常进行，除非**删除该软件包**。  
综上，应当尽量代替方案1，这并不是一个非常好的方案

**Comment by C4a15Wh** [comment]
> @C4a15Wh 感谢反馈 go-ceph 每个 version 支持的 ceph 版本也是有限的，使用 ceph-common 的目的应该是让使用者安装与 ceph 集群匹配版本的客户端

能不能同时引用多个版本的go-ceph，然后在不同的package里面分别封装相关函数，让用户创建RBD的时候选择Ceph版本

**Comment by C4a15Wh** [comment]
> 并且我们还遇到过一些基于 ceph 二次开发的存储服务，由于他们不能够完全的兼容 ceph 标准库，所以使用 go-ceph 也会有一些问题

可不可以提供多个选项，让用户自由选择使用本机ceph-common和go-ceph的特定版本

**Comment by wanyaoqi** [comment]
> 

@C4a15Wh go-ceph版本是要在编译的时候确定的，而且不同的版本 api可能有变化，这样应该做不到。还有一种解决方案是起一个安装好指定版本的 ceph-common 容器，可能在不同的操作系统兼容性上会好一点

**Comment by C4a15Wh** [comment]
也可以，rook-ceph的toolbox就是这样

**Comment by C4a15Wh** [comment]
> > 
> 
> @C4a15Wh go-ceph版本是要在编译的时候确定的，而且不同的版本 api可能有变化，这样应该做不到。还有一种解决方案是起一个安装好指定版本的 ceph-common 容器，可能在不同的操作系统兼容性上会好一点

是不是可以多起几个package
例如cephutils-v16，就用go-ceph-v0.22.0
cephutils-v14，就用go-ceph-v0.16.0
cephutils-v12，就用go-ceph-v0.4.0
这样

**Comment by C4a15Wh** [comment]
然后创建的时候要求用户填写ceph版本，根据ceph版本调用对应封装好的cephutils

**Comment by zexi** [comment]
> > > 
> > 
> > 
> > @C4a15Wh go-ceph版本是要在编译的时候确定的，而且不同的版本 api可能有变化，这样应该做不到。还有一种解决方案是起一个安装好指定版本的 ceph-common 容器，可能在不同的操作系统兼容性上会好一点
> 
> 是不是可以多起几个package 例如cephutils-v16，就用go-ceph-v0.22.0 cephutils-v14，就用go-ceph-v0.16.0 cephutils-v12，就用go-ceph-v0.4.0 这样

@C4a15Wh 这个思路可以，不过我感觉 go mod 好像不支持这种同一个 package 不同版本的管理。
感觉 @wanyaoqi 说的启动不同的版本 ceph-common toolbox 的容器更容易实现。

**Comment by C4a15Wh** [comment]
也可以，不过通过shell调用ceph是否有点太过粗鲁？  
能不能优化成: 将ceph通信组件单独拆分为一个独立的ceph-agent-service，连接不同版本的rbd就启动不同版本的agent-service？

**Comment by C4a15Wh** [comment]
目前逻辑上，每次新建client都需要用hard-code的方式拼接一个conf文件和keyring，这样不但不方便用户自定义连接参数（例如用户方面，为什么我一定要用ceph.admin登录mon server呢？），而且将文件写入到/tmp目录下本身就存在极高的安全隐患，严重情况下还会泄露ceph.admin的key。  
ceph-common并不是最佳的实现思路，尤其是考虑到安全方面，go-ceph应该是一个更好的方案。

**Comment by swordqiu** [comment]
刚补充了一下ceph存储的文档，可以看下 https://www.cloudpods.org/zh/docs/function_principle/onpremise/storage/blockstorage/ceph/ @C4a15Wh

**Comment by C4a15Wh** [comment]
好的，建议补充升级方法

**Comment by swordqiu** [comment]
拟采用 https://github.com/yunionio/cloudpods/issues/17668 解决此问题，本issue关闭。
