### ISSUE TITLE
[求助/Help] 虚拟机配置EIP不生效 & 关于SDNAgent服务和EIP网关服务

### ISSUE THREAD

**Issue by C4a15Wh** [yunionio/cloudpods#17639]
# 虚拟机配置EIP不生效

## 环境信息
Cloudpods版本: 3.10
系统: Debian 10

您好！我今天尝试将三个空闲的公网IP(114.xx.3.130-132)划给cloudpods用作虚拟机的弹性公网IP，但是创建并分配EIP到VM后: 
1) 宿主机并没有3.130的路由（ip route | grep 3.130没有结果）；
2) ping该被分配的公网IP并不能ping通；
3) 如果将宿主机的一个网口直通给vm，然后让vm通过该网口获取IP，则可以正常拿到IP；

相关命令行结果如下: 
```
root@gpu-worker-04:~# ip route
default via 192.168.1.1 dev br0
blackhole 10.40.42.0/26 proto bird
10.40.42.1 dev cali762a438c286 scope link
10.40.42.2 dev cali709d5076056 scope link
10.40.42.3 dev calie19873e6cf7 scope link
10.40.73.192/26 via 192.168.1.3 dev tunl0 proto bird onlink
10.40.90.192/26 via 192.168.1.2 dev tunl0 proto bird onlink
10.40.128.0/26 via 192.168.1.9 dev tunl0 proto bird onlink
10.40.133.128/26 via 192.168.1.7 dev tunl0 proto bird onlink
10.40.146.0/26 via 192.168.1.8 dev tunl0 proto bird onlink
10.40.172.64/26 via 192.168.1.4 dev tunl0 proto bird onlink
10.40.184.64/26 via 192.168.1.5 dev tunl0 proto bird onlink
10.40.222.0/26 via 192.168.1.6 dev tunl0 proto bird onlink
100.64.0.0/17 dev brmapped proto kernel scope link src 100.64.0.132
192.168.1.0/24 dev br0 src 192.168.1.10
root@gpu-worker-04:~#
```
参数: 
![image](https://github.com/yunionio/cloudpods/assets/61458603/940ccf9e-7cbd-44b5-a59d-ba1b12ca5452)
![image](https://github.com/yunionio/cloudpods/assets/61458603/e7db3960-8426-4f75-b461-2d4da5d74ece)
![image](https://github.com/yunionio/cloudpods/assets/61458603/e7e4b071-7d4d-45a6-9891-442e5d1e742a)

---

# 关于SDNAgent服务和EIP网关服务

查看了cloudpods过往的issue，发现有提到一个 EIP网关 的服务，相关文档: [github](https://github.com/yunionio/sdnagent/tree/master/build/sdnagent/root/usr/share/sdnagent/ansible/templates) 、 [cloudpods](https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/vpc/eipgwhowto/#%E4%B8%BB%E5%A4%87%E9%AB%98%E5%8F%AF%E7%94%A8eip%E7%BD%91%E5%85%B3)。  

查看ansible-playbook后，发现sdnagent仅支持rhel系(centos)，软件包为rpm格式。但我也有观察到现在宿主机上有部署一个host-sdnagent的容器，在sdnagent的仓库内确实发现了容器化的dockerfile。  

请问如果是这样的话，是否代表Cloudpods 3.10已经在安装的时候附带并以容器化形式部署了SDNAgent，而不再需要我进行部署？  

此外，我未在宿主机上发现systemd管理的openvswitch服务，查看sdnagent源码后发现openvswitch组件似乎已经跟随SDNAgent一起容器化，请问是这样吗？

**Comment by C4a15Wh** [comment]
补充子网信息
IP: 114.xx.3.130-132
子网掩码: 255.255.255.192(/26)
网关: 114.xx.3.190

**Comment by C4a15Wh** [comment]
日志有点大，我直接放群里了
![image](https://github.com/yunionio/cloudpods/assets/61458603/c3d10789-463a-4f6b-a99d-1bc3a1234fbf)

**Comment by swordqiu** [comment]
是这样，如果是AllInOne部署并部署了host服务，则第一个节点已经是一个EIP网关。这种情况不需要额外部署EIP网关。

配置EIP同事需要在物理网络交换机配置到EIP网络的静态路由。请看下这个文档：https://www.cloudpods.org/zh/docs/function_principle/onpremise/network/vpc/eiphowto/ 

如果还有问题，请继续留言。

@C4a15Wh

**Comment by C4a15Wh** [comment]
我是HA部署的，但每个宿主机上都有host-sdnagent容器，我还需要部署EIP网关吗？

**Comment by C4a15Wh** [comment]
如果是的话，要怎么部署？我是debian系统，似乎没有适用于debian的deb包，只有rpm包

**Comment by C4a15Wh** [comment]
已经放弃EIP方案，虚机拿公网IP下还是建议直接给到l2-bcast VPC的IP网段。
