### ISSUE TITLE
[求助/Help]cloudpods上不显示Zstack的镜像

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#17689]
纳管Zstack后，创建虚拟机里镜像不显示，麻烦看看，谢谢
![image](https://github.com/yunionio/cloudpods/assets/59357035/035cc60e-a897-4d07-ae76-cb62e2a7c029)
![image](https://github.com/yunionio/cloudpods/assets/59357035/0a0052fe-8556-4d35-8e4f-58af352d0153)

**Comment by ioito** [comment]
切换到管理后台正常么，再看下浏览器控制台有什么报错没 @ninghongwu

**Comment by ninghongwu** [comment]
@ioito  从管理后台创建zstack也不显示镜像，浏览器没有出现报错呢

**Comment by ioito** [comment]
执行下面的命令，看下返回有镜像没 @ninghongwu 
```shell
climc cached-image-list --scope system --provider ZStack 
```

**Comment by ninghongwu** [comment]
@ioito 没有😂
![image](https://github.com/yunionio/cloudpods/assets/59357035/92585d08-20bd-414e-b634-cddd85712a50)

**Comment by ioito** [comment]
能截图看下zstack平台上的镜像列表么 @ninghongwu

**Comment by ninghongwu** [comment]
@ioito 
![image](https://github.com/yunionio/cloudpods/assets/59357035/5569ab53-294e-4265-a608-fe13a0781f8e)

![image](https://github.com/yunionio/cloudpods/assets/59357035/0a811523-b335-43c0-94bb-a352fadbce42)

**Comment by ninghongwu** [comment]
@ioito to同步是成功的，日志里面空白的
<img width="874" alt="1691141446495" src="https://github.com/yunionio/cloudpods/assets/59357035/7d456cf1-2fa9-45d4-88c4-3418f1c71557">

**Comment by ioito** [comment]
需要看的是后端region那段时间的同步日志 https://github.com/yunionio/cloudpods/blob/ad777523c91575fdf69f8b5b21e14a87d261789d/pkg/compute/models/cloudsync.go#L2173 这是镜像同步的那段输出代码 @ninghongwu

**Comment by ninghongwu** [comment]
@ioito 不好意思，没太明白，是要增加这行代码吗 
log.Infof("syncCloudImages for %s result: %s", storageCachePairs[i].local.GetName(), msg)

**Comment by ioito** [comment]
> @ioito 不好意思，没太明白，是要增加这行代码吗 log.Infof("syncCloudImages for %s result: %s", storageCachePairs[i].local.GetName(), msg)

syncCloudImages这是日志的关键字，根据这个看下日志的输出
