### ISSUE TITLE
[求助/Help]添加 PVE 资源的入口在哪？

### ISSUE THREAD

**Issue by New-GitHub** [yunionio/cloudpods#17708]
当前产品：Cloudpods
软件版本：v3.10.4
安装方式：Docker Compose

问题：从公众号获取到v3.10.4版本添加了对PVE资源的生命周期管理。测试环境中未找到添加PVE资源的入口，求助。

**Comment by jackgao2015** [comment]
@New-GitHub  可以在 issue 里面搜一下。
看一下这个issue https://github.com/yunionio/cloudpods/issues/15829

**Comment by New-GitHub** [comment]
太棒了。
