### ISSUE TITLE
[BUG] centos 7.9 系统 安装报错， Change root password    Ansible 执行不了

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#17734]
**问题描述/What happened**:

<img width="748" alt="9b9a0db6219ae6d5cb368802a7c6126" src="https://github.com/yunionio/cloudpods/assets/48039439/ea67a601-4651-40d7-9c3b-969971de6d20">

TASK [mariadb : Change root password] ******************************************
failed: [10.158.159.8] (item=localhost) => {"ansible_loop_var": "item", "changed": false, "item": "localhost", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.158.159.8] (item=%) => {"ansible_loop_var": "item", "changed": false, "item": "%", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.158.159.8] (item=::1) => {"ansible_loop_var": "item", "changed": false, "item": "::1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
failed: [10.158.159.8] (item=127.0.0.1) => {"ansible_loop_var": "item", "changed": false, "item": "127.0.0.1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}

**环境/Environment**:

cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

**Comment by hoganlxj** [comment]
@sun3book 在10.158.159.8上 能用 mysql -u root -p 登陆吗？

**Comment by sun3book** [comment]
没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。

**Comment by sun3book** [comment]
> 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。

没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。

**Comment by sun3book** [comment]
> @sun3book 在10.158.159.8上 已经安装过mysql吗？

没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。

**Comment by hoganlxj** [comment]
> > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> 
> 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
可以把mysql卸载，再执行安装试下
yum -y remove mariadb*
rm -rf /var/lib/mysql
rm -rf /etc/my.conf

**Comment by zhasm** [comment]
@sun3book 
看起来是mariadb 无法授权的问题。请按照上面 @hoganlxj 的方法试一下。保险起见，可以
```bash
yum -y remove mariadb*
mv  -f /var/lib/mysql /var/lib/mysql.$(date +"%Y%m%d-%H%M").bak  # 保留原始数据
rm -rf /etc/my.conf
```
然后重新执行 `ocboot` 的安装过程。

**Comment by niconical** [comment]
> @sun3book 看起来是残留的 mariadb ，用户名密码已经更改过，本次重装ocboot，新生成的随机密码无法登陆原来的`mysql`，因此无法授权的问题。请按照上面 @hoganlxj 的方法试一下。保险起见，可以
> 
> ```shell
> yum -y remove mariadb*
> mv  -f /var/lib/mysql /var/lib/mysql.$(date +"%Y%m%d-%H%M").bak  # 保留原始数据
> rm -rf /etc/my.conf
> ```
> 
> 然后重新执行 `ocboot` 的安装过程。

`ocboot` 目前有卸载脚本吗，我也遇到过重复安装需要手动删除很多文件的情况，如果不手动删除遗留文件，ansible 会 skip 很多 task 最终导致安装失败。

**Comment by sun3book** [comment]
> > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > 
> > 
> > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > 可以把mysql卸载，再执行安装试下
> > yum -y remove mariadb*
> > rm -rf /var/lib/mysql
> > rm -rf /etc/my.conf

这样清理后再执行安装，有新的报错：

TASK [primary-master-node/setup_k8s : Pull ocadm images on node] ***************
fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

![image](https://github.com/yunionio/cloudpods/assets/48039439/edfb841b-5141-47b8-a36e-a9f0b3b739b6)

**Comment by hoganlxj** [comment]
> > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > 
> > > 
> > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > 可以把mysql卸载，再执行安装试下
> > > yum -y remove mariadb*
> > > rm -rf /var/lib/mysql
> > > rm -rf /etc/my.conf
> 
> 这样清理后再执行安装，有新的报错：
> 
> TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> 
> ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)

看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？

**Comment by sun3book** [comment]
> 


cd  /opt/yunion/bin
-bash: cd: /opt/yunion/bin: 没有那个文件或目录

**Comment by sun3book** [comment]
> cd /opt/yunion/bin
> -bash: cd: /opt/yunion/bin: 没有那个文件或目录

cd /opt/yunion/bin
-bash: cd: /opt/yunion/bin: 没有那个文件或目录

> > > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > > 
> > > > 
> > > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > > 可以把mysql卸载，再执行安装试下
> > > > yum -y remove mariadb*
> > > > rm -rf /var/lib/mysql
> > > > rm -rf /etc/my.conf
> > 
> > 
> > 这样清理后再执行安装，有新的报错：
> > TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> > ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)
> 
> 看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？

cd /opt/yunion/bin
-bash: cd: /opt/yunion/bin: 没有那个文件或目录

**Comment by hoganlxj** [comment]
https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/

> > cd /opt/yunion/bin
> > -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> 
> cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> 
> > > > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > > > 
> > > > > 
> > > > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > > > 可以把mysql卸载，再执行安装试下
> > > > > yum -y remove mariadb*
> > > > > rm -rf /var/lib/mysql
> > > > > rm -rf /etc/my.conf
> > > 
> > > 
> > > 这样清理后再执行安装，有新的报错：
> > > TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> > > ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)
> > 
> > 
> > 看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？
> 
> cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录

https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/  手工安装下 这几个rpm后，再重新执行安装试下

**Comment by zhasm** [comment]
@sun3book 
安装的ocboot 目录，是否干净？是否在调试时去掉了某些步骤？
原始程序会有一个
` - name: install latest packages via loop` 
的步骤，来确保安装二进制的最新版～

**Comment by sun3book** [comment]
> name: install latest packages via loop

干净的，目录都删了，重新 github拉取的

**Comment by zhasm** [comment]
> 

@sun3book 如果安装不上，应该报错才对。后续我加一个校验，确保二进制存在，获取版本信息正常。
目前问题解决了吗？

**Comment by sun3book** [comment]
> https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/
> 
> > > cd /opt/yunion/bin
> > > -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > 
> > 
> > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > > > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > > > > 
> > > > > > 
> > > > > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > > > > 可以把mysql卸载，再执行安装试下
> > > > > > yum -y remove mariadb*
> > > > > > rm -rf /var/lib/mysql
> > > > > > rm -rf /etc/my.conf
> > > > 
> > > > 
> > > > 这样清理后再执行安装，有新的报错：
> > > > TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> > > > ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)
> > > 
> > > 
> > > 看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？
> > 
> > 
> > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> 
> https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/ 手工安装下 这几个rpm后，再重新执行安装试下

[root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-ee-v3.10.4-23080107.x86_64.rpm
	file /opt/yunion/bin/climc-ee from install of yunion-climc-ee-v3.10.4-23080107.x86_64 conflicts with file from package yunion-climc-ee-v3.10.3-23063014.x86_64
[root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-v3.10.4-23080107.x86_64.rpm
	软件包 yunion-climc-v3.10.4-23080107.x86_64 已经安装
[root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm
错误：依赖检测失败：
	gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
[root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm
错误：依赖检测失败：
	gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
	telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要
[root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-ocadm-3.10.4-1.x86_64.rpm
	软件包 yunion-ocadm-3.10.4-1.x86_64 已经安装

**Comment by zhasm** [comment]
@sun3book 
```bash
for i in /etc/yum.repos.d/*yunion*.repo
do
   echo "repo name: $i"
    cat $i
done
看一下yunion repo是否存在；

如果存在，且配置正确，直接使用下面的语句安装，来自动解决依赖问题：
```bash
yum install -y yunion-climc-ee yunion-climc yunion-lbagent yunion-ocadm yunion-sdnagent
```

**Comment by hoganlxj** [comment]
> > https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/
> > > > cd /opt/yunion/bin
> > > > -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > 
> > > 
> > > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > > > > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > > > > > 可以把mysql卸载，再执行安装试下
> > > > > > > yum -y remove mariadb*
> > > > > > > rm -rf /var/lib/mysql
> > > > > > > rm -rf /etc/my.conf
> > > > > 
> > > > > 
> > > > > 这样清理后再执行安装，有新的报错：
> > > > > TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> > > > > ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)
> > > > 
> > > > 
> > > > 看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？
> > > 
> > > 
> > > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > 
> > 
> > https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/ 手工安装下 这几个rpm后，再重新执行安装试下
> 
> [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-ee-v3.10.4-23080107.x86_64.rpm file /opt/yunion/bin/climc-ee from install of yunion-climc-ee-v3.10.4-23080107.x86_64 conflicts with file from package yunion-climc-ee-v3.10.3-23063014.x86_64 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-v3.10.4-23080107.x86_64.rpm 软件包 yunion-climc-v3.10.4-23080107.x86_64 已经安装 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm 错误：依赖检测失败： gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm 错误：依赖检测失败： gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-ocadm-3.10.4-1.x86_64.rpm 软件包 yunion-ocadm-3.10.4-1.x86_64 已经安装

看下/opt/yunion/bin 有ocadm和climc的二进制文件没？ 若没有需要手工删除
yum -y remove yunion-climc* yunion-ocadm 
再安装下 yunion-climc-v3.10.4-23080107.x86_64 和 yunion-ocadm-3.10.4-1.x86_64

**Comment by sun3book** [comment]
> > > https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/
> > > > > cd /opt/yunion/bin
> > > > > -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > > 
> > > > 
> > > > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > > > > > > > @sun3book 在10.158.159.8上 已经安装过mysql吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没有安装过mysql，是之前安装过 cloudpods 。按文档执行过卸载之后 再执行了安装。
> > > > > > > > 可以把mysql卸载，再执行安装试下
> > > > > > > > yum -y remove mariadb*
> > > > > > > > rm -rf /var/lib/mysql
> > > > > > > > rm -rf /etc/my.conf
> > > > > > 
> > > > > > 
> > > > > > 这样清理后再执行安装，有新的报错：
> > > > > > TASK [primary-master-node/setup_k8s : Pull ocadm images on node] *************** fatal: [10.158.159.8]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm config images pull --image-repository registry.cn-beijing.aliyuncs.com/yunion --onecloud-version v3.10.4 --operator-version v3.10.4", "msg": "[Errno 2] 没有那个文件或目录: b'/opt/yunion/bin/ocadm': b'/opt/yunion/bin/ocadm'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
> > > > > > ![image](https://user-images.githubusercontent.com/48039439/259287195-edfb841b-5141-47b8-a36e-a9f0b3b739b6.png)
> > > > > 
> > > > > 
> > > > > 看下 /opt/yunion/bin 目录是否有ocadm的二进制文件？
> > > > 
> > > > 
> > > > cd /opt/yunion/bin -bash: cd: /opt/yunion/bin: 没有那个文件或目录
> > > 
> > > 
> > > https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/ 手工安装下 这几个rpm后，再重新执行安装试下
> > 
> > 
> > [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-ee-v3.10.4-23080107.x86_64.rpm file /opt/yunion/bin/climc-ee from install of yunion-climc-ee-v3.10.4-23080107.x86_64 conflicts with file from package yunion-climc-ee-v3.10.3-23063014.x86_64 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-climc-v3.10.4-23080107.x86_64.rpm 软件包 yunion-climc-v3.10.4-23080107.x86_64 已经安装 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm 错误：依赖检测失败： gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-lbagent-v3.10.4-23080107.x86_64.rpm 错误：依赖检测失败： gobetween >= 0.7.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 haproxy >= 1.8.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 keepalived >= 2.0.0 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 telegraf >= 1.5 被 yunion-lbagent-v3.10.4-23080107.x86_64 需要 [root@zhcx-cloudpods01 ocboot]# rpm -i https://iso.yunion.cn/centos/7/3.10/x86_64/rpms/updates/yunion-ocadm-3.10.4-1.x86_64.rpm 软件包 yunion-ocadm-3.10.4-1.x86_64 已经安装
> 
> 看下/opt/yunion/bin 有ocadm和climc的二进制文件没？ 若没有需要手工删除 yum -y remove yunion-climc* yunion-ocadm yunion-executor* 再安装下 yunion-climc-v3.10.4-23080107.x86_64 和 yunion-ocadm-3.10.4-1.x86_64

这个办法有效，按照这个来操作，安装成功

yum -y remove yunion-climc* yunion-ocadm 
wget -O /etc/yum.repos.d/yunion.repo https://iso.yunion.cn/centos/7/3.10/x86_64/yunion.repo
yum makecache
yum install -y yunion-climc-ee yunion-climc yunion-lbagent yunion-ocadm yunion-sdnagent

**Comment by zhasm** [comment]
@sun3book 您好～是否还有其他问题～
如有本问题还有遗留，欢迎继续留言反馈
如果本问题已经解决，请关闭本issue
如果还有新的问题，请新开issue~
多谢～
