### ISSUE TITLE
[BUG]裸金属装机装机失败

### ISSUE THREAD

**Issue by liyibo123456** [yunionio/cloudpods#17738]
**问题描述/What happened**:
裸金属装机装机失败报错日志rootfs not find

**环境/Environment**:
OS : centos7.9
Kernel: 5.4.130-1.yn20221208.el7.x86_64
Host: Lenovo ThinkServer SE550V2
Service Version : 3.10.4
查看了baremetal-agent 的pods 日志,报错如下:
![image](https://github.com/yunionio/cloudpods/assets/49019416/352564e6-8de4-44e5-9e5a-3f0517e6bbd1)

**Comment by liyibo123456** [comment]
@zexi 装机镜像用得是官网网盘列举的镜像，CentOS-7.9.2009-20220327.qcow2

**Comment by hoganlxj** [comment]
@liyibo123456 可以换个镜像试下
