### ISSUE TITLE
[BUG]虚拟机设置磁盘速度，无论限速多少，都会导致服务器执行任何命令都卡住

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17733]
**问题描述/What happened**:
虚拟机设置磁盘速度后，无论设置的值是多大，都会导致虚拟机基本无法再执行任何命令
![image](https://github.com/yunionio/cloudpods/assets/10016360/dee35335-eae7-4ff2-bbcd-ebd70bbfa4c9)

连yum安装或者sudo -i切换用户都能卡住

测速工具也跑不起来
![image](https://github.com/yunionio/cloudpods/assets/10016360/7e5cc1b5-4162-45df-8433-4f4db129e7a6)

**环境/Environment**:
操作系统：CentOS7.9
内核：3.10.0-1160.80.1.el7.x86_64
磁盘大小：100G

cloudpods版本：3.10.4

**Comment by wanyaoqi** [comment]
@shuoshadow 感谢反馈，我们验证一下

**Comment by wanyaoqi** [comment]
前端传参有问题，bps传的是 byte/s，不是 M/s
