### ISSUE TITLE
[BUG] 创建虚拟机，操作系统选择从ISO启动，创建完成后虚拟机系统盘显示为数据盘

### ISSUE THREAD

**Issue by labose** [yunionio/cloudpods#17736]
**问题描述/What happened**:创建虚拟机，操作系统选择从ISO启动，创建完成后虚拟机系统盘显示为数据盘

**环境/Environment**:
![1691568724908](https://github.com/yunionio/cloudpods/assets/74222239/888c92f2-90d9-4489-9b5b-8182390e6172)
![1691568724926](https://github.com/yunionio/cloudpods/assets/74222239/ebccfc83-990e-48c5-b30e-d7750eeebbba)

- OS (e.g. `cat /etc/os-release`):CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 5.4.130-1.yn20221208.el7.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`):Manufacturer: Intel
        Manufacturer: Micron
        Manufacturer: Samsung
        Manufacturer: Supermicro
        Manufacturer: To Be Filled By O.E.M.
        Product Name: X9DRL-3F/iF
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):release/3.10(3b4258809123080100)

**Comment by jackgao2015** [comment]
@labose 可以直接用这种qcow2的镜像创建机器就可以先避免这个问题
[centos](http://cloud.centos.org/centos/7/images/): http://cloud.centos.org/centos/7/images/
[ubuntu](https://cloud-images.ubuntu.com/): https://cloud-images.ubuntu.com/
也可以访问 https://docs.openstack.org/image-guide/obtain-images.html 获得更多的虚拟机镜像。

**Comment by wanyaoqi** [comment]
@labose 从iso创建的机器无法确定哪个盘为系统盘，所以默认都显示为数据盘
