### ISSUE TITLE
[BUG] 对接 vmware ，创建子网后执行同步，虚拟机可以同步进来，但是没同步到对应子网中

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#17744]
**问题描述/What happened**:
已提前创建好子网，如下图：

![image](https://github.com/yunionio/cloudpods/assets/48039439/6250b3d5-fddc-4be0-988f-4f316eee5b06)

账号同步后，虚拟机同步进子网里边，显示 “该IP地址无归属IP子网！请添加包含该IP地址的IP子网并重新同步云账号”
![image](https://github.com/yunionio/cloudpods/assets/48039439/7a9fb8d3-23a0-4812-8dcc-c66f6ab00210)

**环境/Environment**:

cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by hoganlxj** [comment]
@sun3book 确认下 IP子网所属的二层网络  和虚拟机所在宿主机 的 是否一致？ 若不一致，新建IP子网所属二层网络 要和宿主机所在的二层网络是同一个，然后全量同步下 云账号

**Comment by sun3book** [comment]
> @sun3book 确认下 IP子网所属的二层网络 和虚拟机所在宿主机 的 是否一致？ 若不一致，新建IP子网所属二层网络 要和宿主机所在的二层网络是同一个，然后全量同步下 云账号

原来是这样玩的，我明白了。  

vcenter 里边 ，规划的网络 宿主 和 虚拟机 是在 不同 子网的。
