### ISSUE TITLE
缓存镜像失败[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17748]
有个10G的镜像缓存失败。其它5G左右的镜像缓存没问题。难道是镜像太大了吗
{
    "image_id": "1f1e9a54-e187-4212-8f4b-5a4d03d506c5",
    "reason": {
        "__reason__": "AcquireImage: remoteFile.Fetch: download: Remote file fetch GET https://default-glance:30292/v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system error 400",
        "__stage__": "OnImageCacheComplete",
        "__status__": "error"
    }
}

**Comment by ioito** [comment]
@shengxianli 需要看下那段时间的glance后台日志

**Comment by shengxianli** [comment]
@ioito 
[info 2023-08-11 09:07:53 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 d4070c-3148d1 HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?details=true&is_guest_image=false&scope=system&show_emulated=true&show_fail_reason=true (10.0.254.17:33002:apigateway) 17.13ms
[info 2023-08-11 09:07:54 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 ca32d0-9d8b83 GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5/subformats (10.0.254.17:33002:apigateway) 3.42ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 5f3e41-3da832-f1054a HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5 (10.0.254.17:57490:compute_v2) 4.97ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 5f3e41-3da832-d75c13 HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5 (10.0.254.17:57490:compute_v2) 5.00ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 6aad44 HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53644) 6.31ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 d28c73 GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53646) 6.64ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 d79ba6 HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53650) 5.40ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 c09daf GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53652) 7.22ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 be739b HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53654) 5.96ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 ca08eb GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53658) 5.98ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 09778d HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53660) 5.17ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 c99cef GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53662) 6.68ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 34f1e7 HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53666) 5.63ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 62cfe6 GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53668) 7.35ms
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 200 65897a HEAD /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53672) 6.12ms
[error 2023-08-11 09:08:05 httperrors.HTTPError(httperrors.go:110)] Send error cannot download in status queued
[info 2023-08-11 09:08:05 appsrv.(*Application).ServeHTTP(appsrv.go:284)] d8qyq8rJs3avo5Vwo4kj576y7hs= 400 792416 GET /v1/images/1f1e9a54-e187-4212-8f4b-5a4d03d506c5?format=vmdk&scope=system (10.0.254.17:53674) 7.47ms

**Comment by zexi** [comment]
@shengxianli 这个日志看起来没有问题，要不把所有的日志导出来看下

**Comment by shengxianli** [comment]
[log.txt](https://github.com/yunionio/cloudpods/files/12320583/log.txt)
@zexi 请查收谢谢

**Comment by ioito** [comment]
看下镜像 1f1e9a54-e187-4212-8f4b-5a4d03d506c5 的状态，看日志是这个镜像状态时queue状态

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/6255dacf-c150-4575-9563-3b6285abb644)
@ioito 哦这个状态是等待保存状态，
这个镜像是我在https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/common/
这里下载的2016的镜像 qemu-img convert -f qcow2 file.qcow2 -O vmdk file.vmdk
通过此方式转换成VMDK后上传的。
原因是我想测试这个问题（https://github.com/yunionio/cloudpods/issues/17646）是否是我自己封装镜像的问题

**Comment by shengxianli** [comment]
可能是我镜像封装的问题，发现你们官方的镜像内涵了VM格式了
