### ISSUE TITLE
[求助/Help]使用ISO创建的虚拟机，保存镜像后，再创建机器，平台无法设置账号密码，也无法使用 web ssh

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17753]
参考了制作镜像的文档，跑完所有流程，还是不行
制作镜像：https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/create/#centos%E9%95%9C%E5%83%8F%E4%BC%98%E5%8C%96

**Comment by Mrliuch** [comment]
使用centos制作VMware镜像，创建虚拟机设置自定义密码后启动虚拟机不生效，密码还是之前centos模板内的

**Comment by Mrliuch** [comment]
> 使用centos制作VMware镜像，创建虚拟机设置自定义密码后启动虚拟机不生效，密码还是之前centos模板内的

已解决，创建虚拟机期间不能刷新页面，等待创建完成密码会被修改，包括自定义密码和随机生成的都试过

**Comment by Mrliuch** [comment]
> > 使用centos制作VMware镜像，创建虚拟机设置自定义密码后启动虚拟机不生效，密码还是之前centos模板内的
> 
> 已解决，创建虚拟机期间不能刷新页面，等待创建完成密码会被修改，包括自定义密码和随机生成的都试过

希望官方可以修复这个问题，创建期间刷新页面不影响后续初始化操作

**Comment by jackgao2015** [comment]
> 直接使用qcow2的镜像也有问题 https://mirrors.cloud.tencent.com/centos-cloud/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2

使用最新版的cloudpods没有复现这个问题，应该是之前的集群有问题或者相关服务不正常。

**Comment by jackgao2015** [comment]
> 参考了制作镜像的文档，跑完所有流程，还是不行 制作镜像：https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/create/#centos%E9%95%9C%E5%83%8F%E4%BC%98%E5%8C%96

发现没问题了/捂脸哭

**Comment by dengju2020** [comment]
> 问题，创建期间刷新页面不影响后

@Mrliuch  刷新页面不会影响密码修改，方便可以导出host-deployer的日志
