### ISSUE TITLE
宿主机状态显示未知

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#17759]
我们有一台宿主机，状态显示未知，查看操作日志，最后一次更新宿主机状态是3月份，查看这个宿主机上的pod default-host   default-host-deployer  default-host-image 等运行正常，查看  default-host  host 容器日志，发现它一直在正常管理该宿主机上的虚拟机，并且该宿主机上的虚拟机也全部是正常运行状态，想问下  那这个宿主机的状态未知可能是哪里的问题？

**Comment by wanyaoqi** [comment]
@tianchao001 这个状态是 baremetal-agent探测的，可以看下 baremetal-agent 日志

**Comment by tianchao001** [comment]
我重启了一下 agent的pod 然后agent对其他宿主机都更新了状态，但唯独没有这台宿主机的日志，这是为啥？ 
如果说 这台机器的ipmi密码不对了，那会造成 agent没有探测日志的情况吗？

**Comment by wanyaoqi** [comment]
@tianchao001 你指的是什么日志，操作日志还是 baremetal-agent 的日志。如果密码不对 baremetal-agent应该会有日志

**Comment by tianchao001** [comment]
是baremetal-agent 的日志，但我重启了 baremetal-agent 后， 其他宿主机的状态同步日志都正常输出，唯独状态未知这台宿主机 没有任何日志输出，并且 状态也一直是未知

**Comment by wanyaoqi** [comment]
@tianchao001 你找一些 Error 级别的日志看下，可以 grep [error

**Comment by tianchao001** [comment]
我grep 这台异常宿主机的 主机名  ipmi地址 以及你说的 [error 都没看到这台机器在baremetal-agent的日志信息。。。

**Comment by tianchao001** [comment]
另外 我想问下  如何修改ipmi的密码呀？

**Comment by hoganlxj** [comment]
@tianchao001 使用climc host-update 来修改

**Comment by hoganlxj** [comment]
@tianchao001 使用climc host-update 来修改

**Comment by tianchao001** [comment]
嗯，现在更新密码完成了，有办法主动同步下宿主机状态吗

**Comment by wanyaoqi** [comment]
@tianchao001 可以试下 climc host-syncstatus
