### ISSUE TITLE
[BUG] cloudpods 纳管 VMware, windows server 2022 虚拟机创建完之后，网络设置里 dns 是空的

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#17768]
**问题描述/What happened**:

cloudpods 纳管 VMware,  虚拟机创建完之后，域名无法访问，ip 通，进去看网络设置发现 dns 是空的.  目前创建 windows 虚拟机出现这样的情况，系统版本是 window server 2022. 创建 linux虚拟机 正常。

![d6915b3a01a6732047a367bda49cfc6](https://github.com/yunionio/cloudpods/assets/48039439/4b2df49b-2b45-4e68-bf6d-42fb23f83a0c)

![36bc333aa95aa1da58e6db4601d69b7](https://github.com/yunionio/cloudpods/assets/48039439/e1121c8f-0798-4359-b227-3c6c3852c82d)

**环境/Environment**:

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

cloudpods:  3.10.4

**Comment by jackgao2015** [comment]
<img width="375" alt="image" src="https://github.com/yunionio/cloudpods/assets/11387540/0537bfa4-febe-463e-96e1-dba77cec3f27">

**Comment by swordqiu** [comment]
kubectl -n onecloud edit daemonset default-host-deployer
替换image为：registry.cn-beijing.aliyuncs.com/swordqiu/host-deployer:qj-dev-20230815-3.10
测试一下，最好2012,2016,2019都测试一下。

@sun3book

**Comment by sun3book** [comment]
> registry.cn-beijing.aliyuncs.com/swordqiu/host-deployer:qj-dev-20230815-3.10-1

确实修复好了，验证了 window 2016 ,window 2019, windows 2022 。IP和dns设置都可以正常透传到虚拟机里边了。 window 2012 未验证
