### ISSUE TITLE
VMwere虚拟机迁移问题[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17760]
当前产品
Cloudpods
软件版本
v3.10.3
VM虚拟机进行迁移的时候，宿主机列表内没有其它宿主机可选，只有虚拟机所在的宿主机，不可选宿主机为空
![image](https://github.com/yunionio/cloudpods/assets/32296103/d91a55d1-628b-42c6-b526-2c7c50e1907c)

**Comment by hoganlxj** [comment]
@shengxianli 切换不可选宿主机tab，看下 宿主机为什么不能被选择

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/711b4c3a-3356-441b-a9be-55ec11ebc437)
@hoganlxj

**Comment by hoganlxj** [comment]
@shengxianli 在cloudpods中  VMware平台的宿主机有多少个？

**Comment by shengxianli** [comment]
@hoganlxj 目前有4台

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/2ab4faca-bb32-46c9-a532-f83efb538b56)

**Comment by shengxianli** [comment]
@hoganlxj 请问这个问题还在关注吗

**Comment by yangqingwen666** [comment]
> 

看一下控制台API请求

**Comment by shengxianli** [comment]
@yangqingwen666 控制台API请求在哪里

**Comment by ioito** [comment]
> @yangqingwen666 控制台API请求在哪里

浏览器右击检查，看网络请求

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/64805327-b8e3-4929-b4b2-b039cfb5cf4b)
![image](https://github.com/yunionio/cloudpods/assets/32296103/665c94a2-17dd-4bbb-86c7-09b5fe3fc2ee)

**Comment by ioito** [comment]
有关host, server相关的请求payload和response都完整截图下

**Comment by shengxianli** [comment]
@ioito ![image](https://github.com/yunionio/cloudpods/assets/32296103/ce7b5568-a8c6-4fea-a179-d7b0e2e9661b)
![image](https://github.com/yunionio/cloudpods/assets/32296103/ed4a397f-216d-45c7-832f-fe0729a6b10b)

**Comment by ioito** [comment]
另外开个浏览器tab页, 类似下图，将里面的参数每次只去掉一个，保留其他参数，看是哪个参数影响了返回结果
<img width="1185" alt="image" src="https://github.com/yunionio/cloudpods/assets/13750250/df42e02f-b0c9-4c2b-96ce-bddb3929f10f">

**Comment by shengxianli** [comment]
@ioito 
1.api/v2/hosts?scope=system&show_fail_reason=true&host_type=esxi
<img width="1231" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/d0033e71-4df8-472f-a215-665b4876a518">

1. api/v2/hosts?scope=system&show_fail_reason=true&limit=10
<img width="1239" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/a72f009b-97ed-4290-a0cc-7900de8379a4">



api/v2/hosts?scope=system&host_type=esxi&limit=10

<img width="1290" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/03d0b24b-a324-4ab3-bda8-8c986b5cfb38">

api/v2/hosts?show_fail_reason=true&host_type=esxi&limit=10
<img width="1271" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/31dafd98-36fe-4377-a9ec-5784b28b05ea">

**Comment by ioito** [comment]
<img width="587" alt="image" src="https://github.com/yunionio/cloudpods/assets/13750250/b64689f0-c81b-4d75-adbd-e209833cb93a">
我的意思是你的环境这些参数，不是我发的那个图

**Comment by ioito** [comment]
执行下面的命令看下结果
`climc host-list --scope system --manager 417960e6-b8ae-44d6-8256-860e5f30ec85`

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/3b118602-bc7e-4b20-b648-6f4c94b910de)

**Comment by ioito** [comment]
你要迁移的这台虚拟机所在的环境只有一个宿主机，你是想迁移到其他vmware环境？这个不支持

**Comment by shengxianli** [comment]
同一个子网下现在有2台
![image](https://github.com/yunionio/cloudpods/assets/32296103/3e46fbef-fad2-4175-8b95-d6708724ebe6)

**Comment by ioito** [comment]
不支持跨vmware环境迁移，这是前提，跟网络无关

**Comment by shengxianli** [comment]
哦哦我以为可以跨vm服务器进行迁移，请教一下如何放置到一个环境内

**Comment by ioito** [comment]
用vcenter将各个宿主机统一管理起来，具体的可以找vmware相关的资料或群

**Comment by shengxianli** [comment]
@ioito 多谢
