### ISSUE TITLE
[BUG]v3.10.4控制台，裸金属装机时候，选择不了网络

### ISSUE THREAD

**Issue by liyibo123456** [yunionio/cloudpods#17779]
**问题描述/What happened**:
v3.10.4控制台，裸金属装机时候，选择不了网络，我这边回退到v3.10.2是正常的
![e70fa7a2ae41eb75bda4ae4ddde90b5](https://github.com/yunionio/cloudpods/assets/49019416/e68a2cd9-a965-45ec-9621-a47ec3aa323c)
**环境/Environment**:
OS : centos7.9
Kernel: 5.4.130-1.yn20221208.el7.x86_64
Host: Lenovo ThinkServer SE550V2
Service Version : 3.10.4

**Comment by zexi** [comment]
@liyibo123456 麻烦看下浏览器调试模式下， console 里面有没有报错？

**Comment by liyibo123456** [comment]
@zexi 
![image](https://github.com/yunionio/cloudpods/assets/49019416/1e7ae14e-e789-4c64-bf94-645ea063817d)

**Comment by easy-mj** [comment]
@liyibo123456 麻烦把这个接口（/api/v2/zones/xxxxx-xxxx-xxxx-xxxx-xxxxxxx/capability）返回的数据信息发一下

**Comment by zexi** [comment]
@liyibo123456 这个问题可能已经修复过了，可以把 default-web 这个 deployment 里面的 web 容器镜像换成下面这个试试：
registry.cn-beijing.aliyuncs.com/yunionio/web:v3.10-0818.0

**Comment by zhanghn8** [comment]
这个 image 可以了 之前用的是 docker hub 上的 yunion/web:v3.10.4
