### ISSUE TITLE
[求助/Help]三级权限应该怎么开

### ISSUE THREAD

**Issue by yqian1226** [yunionio/cloudpods#17771]
想知道更多关于三级权限的东西，并且三级权限不知道怎么开

**Comment by yangqingwen666** [comment]
> 想知道更多关于三级权限的东西，并且三级权限不知道怎么开

你好，我们开源版不支持开启三级权限

**Comment by zexi** [comment]
@yqian1226 目前只有商业版本支持3级权限，开源文档里面的内容写的有点问题，@yangqingwen666 需要修改下相关文档内容。

**Comment by yqian1226** [comment]
你好，商用版本，预配额申请工单流程怎么开启



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月18日(周五) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]三级权限应该怎么开 (Issue #17771)




  
想知道更多关于三级权限的东西，并且三级权限不知道怎么开
  
你好，我们开源版不支持开启三级权限
