### ISSUE TITLE
[BUG] cloudpods 纳管 vmware虚拟机,  创建虚拟机 不支持在线 扩容磁盘, vmware里边创建虚拟机支持磁盘在线扩容

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#17778]
**问题描述/What happened**:

![7ecbc5aa915f085766be96f480c0253](https://github.com/yunionio/cloudpods/assets/48039439/f9e18e3d-6999-4d6f-a50e-685723ad5e21)

![1692164996076](https://github.com/yunionio/cloudpods/assets/48039439/1f53e8b2-926b-403b-a52d-38165e03ffb9)

![1692165099539](https://github.com/yunionio/cloudpods/assets/48039439/ad5a5c9f-a5fa-449e-aacb-a41e2302f91c)

![image](https://github.com/yunionio/cloudpods/assets/48039439/6dc712e3-0284-41a7-8a14-4103f49f95d9)

![1692165171531](https://github.com/yunionio/cloudpods/assets/48039439/86e2b462-32f6-4e2f-a8c9-20e9574e3b10)

分析不能扩容的原因是模板中设置的sata磁盘驱动没有生效，在vmware里边直接创建 scsi驱动的磁盘，是可以支持在线扩容的。

**环境/Environment**:

centos 7.9

cloudpod 3.10.4

**Comment by sun3book** [comment]
换成 scsi 驱动了，cloudpod中 虚拟机创建  可以套用上了 scsi 驱动控制器， 回vmware中可以 在线扩容了。   cloudpod 控制台这里还显示  vmware 不支持在线扩容磁盘，应该是 cloudpod这里没打开在线扩容功能。

**Comment by swordqiu** [comment]
@sun3book  3.11支持了，请等待3.11发布
