### ISSUE TITLE
[求助/Help] pve 虚拟机功能不支持vnc远程、机器删除、密码重置登

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#17774]
对，机器创建指令是能用的，但VNC远程、机器删除、密码重置等都不可用，虚拟机管理的IP列也大多数不显示（有个别又能显示，不知原因）
所以想了解下，这些常用的管理功能，新版本是否会集成
![image](https://github.com/yunionio/cloudpods/assets/11387540/a726594d-abaa-4ff7-b1c2-d3871867936e)
我是用docker-compose装的，难道跟这个有关系？

**Comment by jackgao2015** [comment]
1. 虚拟机“重装系统”功能提示不支持
2. proxmox后端把机器删除后，虚拟机管理不会自动同步清除（有开启自动同步功能，后端新增机器会同步）
3. 新建主机模板时，操作系统只有一个“从ISO启动”选项，导致无法导入已存在模板。ZSTACK是正常的，有“私有云镜像|公共镜像|自定义镜像”选项。

**Comment by SlyChen** [comment]
这个是暂时没规划吗？

**Comment by ioito** [comment]
> 这个是暂时没规划吗？

v3.11 已经支持vnc 删除功能，密码重置pve本身并不支持，所以做不到
