### ISSUE TITLE
climc host-update更新ipmi问题

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#17785]
使用climc host-update --ipmi-ip-addr 更新ipmi地址时，多次出现更改无效的情况，这个会和ipmi 密码错误有关吗？
就是说  在更新ipmi地址时  cloudpods 会去探测这个ipmi是不是可访问的吗？
另外，ipmi地址管理是哪个组件负责的？ 我查看region 组件的pod日志，也没有找到更新ipmi动作相关的信息。

**Comment by zexi** [comment]
@tianchao001 是 region 和 baremetal-agent 共同负责的，更新之前可以用 ipmitool 工具试下访问有没有问题，然后这样试下：

```bash
# 更新地址后
climc host-update --ipmi-ip-addr 

# 探测下
climc host-ipmi-probe $host_id
```

**Comment by tianchao001** [comment]
![image](https://github.com/yunionio/cloudpods/assets/17080656/15cc3bf0-aefa-4a78-b8a6-19e1043390eb)
![image](https://github.com/yunionio/cloudpods/assets/17080656/ff7b16ad-563a-4efc-bca6-ec64f78a249c)

**Comment by tianchao001** [comment]
请求失败了，是不是和机器当前的状态有关系？ 如何重置这种状态？

**Comment by hoganlxj** [comment]
@tianchao001 host-ipmi-probe 执行一次就可以。可以同步状态试下 ，还有问题可以看下baremetal-agent的日志

**Comment by tianchao001** [comment]
![image](https://github.com/yunionio/cloudpods/assets/17080656/1f160fd9-5e74-45b6-882e-be9167aeeea8)
日志里显示更新成功了。但控制台及命令返回结果里 没有更新成功

**Comment by tianchao001** [comment]
整个问题大概是这样的：
我们的机器换网段了，老的ipmi地址和pxe地址都失效了，我们尝试更新平台上的 上述两个地址，pxe地址更新成功了。
但是ipmi地址 在执行update命令后，命令返回的结果显示 ipmi_ip地址 还是老地址，ipmi_info里是新地址。
这个时候再去执行探测climc host-ipmi-probe   就一直卡住了。
手动执行syncstatus命令  倒是用的新的ipmi地址同步的服务器状态。

但是控制台显示出来的物理机Ipmi仍然是老的地址。
再次尝试更新 ipmi地址仍然是上述问题的循环，命令返回结果里还是老地址。

**Comment by tianchao001** [comment]
@zexi

**Comment by tianchao001** [comment]
最终解决办法：删掉物理机重新纳管。
