### ISSUE TITLE
[求助/Help]无法为hypervisor esxi添加安全组

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17782]
ID:
da20f2fd-a29c-4061-8070-a1fb9c8acd2a
错误消息:
UnsupportOperationError
无法为hypervisor esxi添加安全组
错误源信息:
{
  "class": "UnsupportOperationError",
  "code": 406,
  "details": "无法为hypervisor esxi添加安全组",
  "request": {
    "body": {
      "server": {
        "secgroup_ids": [
          "41ae15e3-39db-482e-8463-edb9155e5bac"
        ]
      }
    },
    "headers": {
      "Content-Length": "68",
      "Content-Type": "application/json",
      "User-Agent": "yunioncloud-go/201708",
      "X-Auth-Token": "*",
      "X-Request-Id": "883ae6",
      "X-Yunion-Lang": "zh-CN",
      "X-Yunion-Parent-Id": "0",
      "X-Yunion-Peer-Service-Name": "apigateway",
      "X-Yunion-Remote-Addr": "default-region:30888",
      "X-Yunion-Span-Id": "0.0",
      "X-Yunion-Span-Name": "",
      "X-Yunion-Strace-Debug": "true",
      "X-Yunion-Strace-Id": "80db0cb7"
    },
    "method": "POST",
    "url": "https://default-region:30888/servers/da20f2fd-a29c-4061-8070-a1fb9c8acd2a/add-secgroup"
  },
  "time": "2023-08-17T10:47:54+08:00"
} 
请求:
{
  "method": "post",
  "url": "/v2/servers/add-secgroup",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json;charset=utf-8",
    "x-yunion-lang": "zh-CN"
  },
  "data": {
    "secgroup_ids": [
      "41ae15e3-39db-482e-8463-edb9155e5bac"
    ]
  },
  "params": {
    "id": [
      "da20f2fd-a29c-4061-8070-a1fb9c8acd2a"
    ]
  }
}

**Comment by ioito** [comment]
esxi 本身不支持安全组 @shengxianli
