### ISSUE TITLE
[Feature] 支持 Suse 发行版的虚拟机镜像

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#17799]
**What would you like to be added**:

现在不支持 suse 镜像创建虚拟机，需要支持：suse sp15.4 and SUSE Linux Enterprise Micro 5.4 这两个版本

看了下代码，里边没有支持 suse pkg/hostman/guestfs/fsdriver/drivers.go fsdriver

![image](https://github.com/yunionio/cloudpods/assets/10767027/d5815cd8-fa25-437f-b5fb-c9f60e4f80c3)

https://github.com/yunionio/cloudpods/issues/17710#issuecomment-1678463749
https://github.com/yunionio/cloudpods/issues/17710#issuecomment-1679972319

**Comment by zhanghn8** [comment]
可以，非常感谢

**Comment by zhanghn8** [comment]
@zexi  suse 啥时候开始适配啊

**Comment by zexi** [comment]
适配代码：https://github.com/yunionio/cloudpods/pull/18183

**Comment by zexi** [comment]
等待合并

**Comment by zexi** [comment]
去掉 stale 标签

**Comment by zexi** [comment]
@zhanghn8 https://github.com/yunionio/cloudpods/pull/18183 已适配。
