### ISSUE TITLE
[求助/Help]域配额中超配是从哪里扣除

### ISSUE THREAD

**Issue by yqian1226** [yunionio/cloudpods#17810]
在当前域已有20个安全组的情况下，把当前域的安全组配额更改为10，会更改成功。此时配额情况为20/10，那当前域下超额的10个安全组，这配额是哪里来的
为什么会修改成功，此处应该提示不能修改配额为小于当前资源的数量吧

**Comment by ioito** [comment]
https://www.cloudpods.org/zh/docs/function_principle/misc/configuration/ 配额功能默认是关闭的，要提示需要开启配额功能

**Comment by yqian1226** [comment]
> https://www.cloudpods.org/zh/docs/function_principle/misc/configuration/ 配额功能默认是关闭的，要提示需要开启配额功能

上诉问题的前提就是我已经开启了配额功能

**Comment by ioito** [comment]
目前修改配额数量是没有限制的，只是在创建资源时会判断是不是超过配额

**Comment by dengju2020** [comment]
> 在当前域已有20个安全组的情况下，把当前域的安全组配额更改为10，会更改成功。此时配额情况为20/10，那当前域下超额的10个安全组，这配额是哪里来的 为什么会修改成功，此处应该提示不能修改配额为小于当前资源的数量吧

目前逻辑只在新建相应资源的时候校验配额，在修改相应配额的时候，不做检查。这样使用上更方便一些。
