### ISSUE TITLE
商用版本，预配额申请工单流程怎么开启

### ISSUE THREAD

**Issue by yqian1226** [yunionio/cloudpods#17813]
你好，商用版本，预配额申请工单流程怎么开启

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月18日(周五) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]三级权限应该怎么开 (Issue #17771)

  
想知道更多关于三级权限的东西，并且三级权限不知道怎么开
  
你好，我们开源版不支持开启三级权限
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

_Originally posted by @yqian1226 in https://github.com/yunionio/cloudpods/issues/17771#issuecomment-1685726779_

**Comment by ioito** [comment]
@yqian1226 开源代码里面不包含这部分内容，商业部分需要付费

**Comment by dengju2020** [comment]
> ```
>           你好，商用版本，预配额申请工单流程怎么开启
> ```
> 
> ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年8月18日(周五) 晚上6:59 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [yunionio/cloudpods] [求助/Help]三级权限应该怎么开 (Issue #17771)
> 
> 想知道更多关于三级权限的东西，并且三级权限不知道怎么开
> 
> 你好，我们开源版不支持开启三级权限
> 
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> _Originally posted by @yqian1226 in [#17771 (comment)](https://github.com/yunionio/cloudpods/issues/17771#issuecomment-1685726779)_

@yqian1226 目前项目或者域的配额还为支持通过工单申请，只有管理员在后台进行配置，如需要可以定制开发
