### ISSUE TITLE
[BUG]删除了裸金属，物理机显示关机状态，然后点击开机，就显示在维护中一直卡着

### ISSUE THREAD

**Issue by zhanghn8** [yunionio/cloudpods#17817]
**问题描述/What happened**:

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): Linux cloudpods-node 5.4.130-1.yn20221208.el7.x86_64 #1 SMP Thu Dec 8 12:09:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): v3.10.4

![image](https://github.com/yunionio/cloudpods/assets/33741198/f7954fd9-3b01-49d5-afae-ecb65f8b36fd)
![image](https://github.com/yunionio/cloudpods/assets/33741198/f0574eaa-2c66-4786-9dae-55d059542548)

**Comment by hoganlxj** [comment]
@zhanghn8  物理机同步状态 试下
