### ISSUE TITLE
[求助/Help]公有云资源同步异常

### ISSUE THREAD

**Issue by dsl-zy** [yunionio/cloudpods#17827]
请教下，
cloudpod版本v3.10.3，
已接入账号：腾讯云公有云   账号权限为全局只读
问题：云资源同步，虚拟机cvm的部分信息如ip、mac、磁盘缺失，其他配置信息如主机名，cpu内存规格等是能正常获取的，自查订阅中同步区域是启用且同步日志无异常，可能是哪方面导致的问题，谢谢；
如图，为同一个账号下，部分cvm信息同步完整，部分cvm信息缺失；
![image](https://github.com/yunionio/cloudpods/assets/139295394/a8f28baa-413d-4ce3-a51f-1dd703bfe37f)

**Comment by ioito** [comment]
后台执行
`
# xxxx 需要替换为真正环境的pod信息
kubectl logs -n onecloud default-region-xxxx --tail 10 -f
`
前端找一台缺失信息的实力，点击下同步状态
看上面命令的输出信息，关键字为 syncVMNics syncVMDisks

@dsl-zy

**Comment by ioito** [comment]
后面再有同步异常可直接查看虚拟机的操作日志 https://github.com/yunionio/cloudpods/pull/17828/files

**Comment by dsl-zy** [comment]
同步日志如附件，有报错信息，请协查
[logs-default-region.txt](https://github.com/yunionio/cloudpods/files/12417038/logs-default-region.txt)

**Comment by ioito** [comment]
registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-tencentcloud-solo @dsl-zy 使用这个镜像试下
是由于 https://github.com/yunionio/cloudmux/pull/398/files 这里panic引起的

**Comment by dsl-zy** [comment]
#  kubectl get deploy default-region -n onecloud -o yaml|grep -i registry.cn-beijing.aliyuncs.com/yunionio/region
        image: registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-tencentcloud-solo
        image: registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-tencentcloud-solo

尝试切换这个镜像，还是同样的报错，请协查

**Comment by ioito** [comment]
再试下这个镜像
`registry.cn-beijing.aliyuncs.com/yunionio/region:v3.10-0825-solo`

有可能是由于#17856 引起的
麻烦再执行下命令，看下输入结果
`
`

**Comment by dsl-zy** [comment]
region:v3.10-0825-solo  这个镜像奏效了，缺失信息已能正常同步，感谢；是否升级到最新版本能彻底解决这个问题？

**Comment by ioito** [comment]
我给的这个镜像已经算是最新的镜像了，或者等下次发出小版本再升级也可以的 @dsl-zy
