### ISSUE TITLE
[求助/Help]阿里云VNC无法连接

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17822]
连接状态:Failed to license verification.

**Comment by ioito** [comment]
可以说明下是哪里报错么，截图也行

**Comment by shengxianli** [comment]
@ioito 
![image](https://github.com/yunionio/cloudpods/assets/32296103/6d3afb02-735a-4c56-90f5-6b0858559466)

**Comment by shengxianli** [comment]
顺便问下。PODS里面修改云上的安全组规则，没有同步到云上 是license限制吗

**Comment by ioito** [comment]
阿里云vnc不可用是因为控制台地址变了， #17837 这个是修复 @shengxianli 
安全组规则目前是设计如此，跟license没有关系

**Comment by shengxianli** [comment]
@ioito 好的谢谢。我看下文档

**Comment by shengxianli** [comment]
@ioito 不好意思。我采用的All in One 安装方式，没有options.go这个文件

**Comment by shengxianli** [comment]
@ioito 不好意哦 我使用的方式为all in one  目前升级到最新v3.10.4 还是有这个问题 ，也没有找到这个options.go文件

**Comment by ioito** [comment]
@shengxianli 可以使用这个镜像 registry.us-west-1.aliyuncs.com/yunion-dev/webconsole:master-20230823194017-solo

**Comment by shengxianli** [comment]
@ioito 感谢回复
容器起来之后远程的连接还是没有变化。我尝试关闭原有的webconsole，但是无法关掉。还望进一步指教
![image](https://github.com/yunionio/cloudpods/assets/32296103/85290045-8db9-4073-ac1f-6de179a13cc9)

**Comment by ioito** [comment]
@shengxianli 
<img width="1071" alt="image" src="https://github.com/yunionio/cloudpods/assets/13750250/8bcf03cc-ffbc-4c36-ba53-7751af31a738">
是这个

**Comment by shengxianli** [comment]
@ioito 谢谢回复 我理解的是不是加你这个参数去启动docker 。加上了之后，提示缺少webconsole.conf
[root@IT-Cloudpods ~]#  docker run  registry.us-west-1.aliyuncs.com/yunion-dev/webconsole:master-20230823194017-solo /opt/yunion/bin/webconsole --config /etc/yunion/webconsole.conf
[info 230831 09:56:56 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/webconsole.conf
[fatal 230831 09:56:56 options.ParseOptions(options.go:321)] Parse configuration file: open /etc/yunion/webconsole.conf: no such file or directory
我把别的容器的配置文件 放进去会报错。
![image](https://github.com/yunionio/cloudpods/assets/32296103/90fc45f8-360c-4b8b-9506-e44a013c0985)

**Comment by ioito** [comment]
> @ioito 谢谢回复 我理解的是不是加你这个参数去启动docker 。加上了之后，提示缺少webconsole.conf [root@IT-Cloudpods ~]# docker run registry.us-west-1.aliyuncs.com/yunion-dev/webconsole:master-20230823194017-solo /opt/yunion/bin/webconsole --config /etc/yunion/webconsole.conf [info 230831 09:56:56 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/webconsole.conf [fatal 230831 09:56:56 options.ParseOptions(options.go:321)] Parse configuration file: open /etc/yunion/webconsole.conf: no such file or directory 我把别的容器的配置文件 放进去会报错。 ![image](https://user-images.githubusercontent.com/32296103/264608253-90fc45f8-360c-4b8b-9506-e44a013c0985.png)

不是，这个是配置文件内的东西，新的镜像会直接应用这个参数，并不需要任何变化去启动docker

**Comment by shengxianli** [comment]
@ioito 谢谢回复
我用您发的镜像 直接启动，没有服务运行。或者我启动的时候要加什么参数么。我现在有点迷糊啦
![image](https://github.com/yunionio/cloudpods/assets/32296103/ebbf943b-848c-411e-bc73-47a967e1ac61)

**Comment by ioito** [comment]
> @ioito 谢谢回复 我用您发的镜像 直接启动，没有服务运行。或者我启动的时候要加什么参数么。我现在有点迷糊啦 ![image](https://user-images.githubusercontent.com/32296103/264613930-ebbf943b-848c-411e-bc73-47a967e1ac61.png)

不能直接启动，你要放到k8s环境里面

**Comment by shengxianli** [comment]
@ioito 多谢已经搞定
