### ISSUE TITLE
[BUG] 批量新建虚拟机时，一些虚拟机网络配置为空，导致网络无法连接

### ISSUE THREAD

**Issue by Shuzhen049** [yunionio/cloudpods#17836]
**问题描述/What happened**:
在管理控制台中新建虚拟机，选择大于1的数量。虚拟机操作系统为CentOS 7，使用的镜像是CentOS-7-x86_64-GenericCloud-2211.qcow2。
执行完新建操作后，检查虚拟机网络，发现有一些虚拟机的网络不通，定位到虚拟机的网络配置文件ifcfg-eth0为空。
手动写入配置后，可以通过dhcp获取IP地址。
执行了3次新建任务，2次创建2台，1次创建3台。
只有一次新建2台的任务配置成功。另一次创建2台的任务，有一台虚拟机的网络配置为空。
创建3台的任务，有两台虚拟机的网络配置为空。
出现问题的概率比较高。

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): CentOS 7.9.2009
- Kernel (e.g. `uname -a`): 5.4.130-1.yn20221208.el7.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`) VMWare Virtual Platform
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

![image](https://github.com/yunionio/cloudpods/assets/136044783/5a5a7d58-93eb-42b1-b586-3673ee983fa2)

**Comment by wanyaoqi** [comment]
@Shuzhen049 新建的虚机密码都是正确的吗，可以登陆进去吗

**Comment by Shuzhen049** [comment]
虚拟机的密码都是正确的，可以登录进去。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] [BUG] 批量新建虚拟机时，一些虚拟机网络配置为空，导致网络无法连接 (Issue #17836)





 
@Shuzhen049 新建的虚机密码都是正确的吗，可以登陆进去吗

**Comment by hoganlxj** [comment]
@Shuzhen049 新建虚拟机的IP子网 所属vpc 是默认的default，还是手工新建的？

**Comment by Shuzhen049** [comment]
不是默认的default，是手工新建的vpc，在上面创建了IP子网。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] [BUG] 批量新建虚拟机时，一些虚拟机网络配置为空，导致网络无法连接 (Issue #17836)





 
@Shuzhen049 新建虚拟机的IP子网 所属vpc 是默认的default，还是手工新建的？

**Comment by Shuzhen049** [comment]
又碰到一个问题。新建3台虚拟机时，选择手工输入管理员密码，存储使用RBD，网络选择手工新建的vpc及其子网。只有第一个分配IP的虚拟机密码配置成功，其他两台点击界面上的“密码”图标，显示“无密钥信息”，控制台也无法用手工输入的密码登录。但是在能登录的虚拟机上ping其他两台虚拟机的IP地址，是可以通的。

**Comment by hoganlxj** [comment]
> 不是默认的default，是手工新建的vpc，在上面创建了IP子网。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yunionio/cloudpods" ***@***.***&gt;; 发送时间:&nbsp;2023年8月24日(星期四) 中午11:23 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yunionio/cloudpods] [BUG] 批量新建虚拟机时，一些虚拟机网络配置为空，导致网络无法连接 (Issue #17836) @Shuzhen049 新建虚拟机的IP子网 所属vpc 是默认的default，还是手工新建的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
执行下这个命令，发下vpcagent-0825.log
kubectl logs -n onecloud $(kubectl get pods -n onecloud |grep vpcagent|awk '{print $1}') > vpcagent-0825.log

**Comment by Shuzhen049** [comment]
确实有个host-deployer容器是Pending状态，我尝试过重启，但没用。














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] [BUG] 批量新建虚拟机时，一些虚拟机网络配置为空，导致网络无法连接 (Issue #17836)





  
又碰到一个问题。新建3台虚拟机时，选择手工输入管理员密码，存储使用RBD，网络选择手工新建的vpc及其子网。只有第一个分配IP的虚拟机密码配置成功，其他两台点击界面上的“密码”图标，显示“无密钥信息”，控制台也无法用手工输入的密码登录。但是在能登录的虚拟机上ping其他两台虚拟机的IP地址，是可以通的。
  
@Shuzhen049 需要看一下这两台虚机的部署日志，如果没有秘钥信息应该是部署失败了
 kubectl get pods -n onecloud -o wide -l app=host-deployer kubectl logs -n onecloud <POD_NAME&gt;

**Comment by wanyaoqi** [comment]
@Shuzhen049 pending 应该是节点没有启用host-agent。你可以使用 kubectl describe -n onecloud <POD_NAME>

**Comment by wanyaoqi** [comment]
> 在管理控制台中新建虚拟机，选择大于1的数量。虚拟机操作系统为CentOS 7，使用的镜像是CentOS-7-x86_64-GenericCloud-2211.qcow2

这个镜像是哪里下载的

**Comment by zexi** [comment]
@Shuzhen049 可以更新到 v3.10.5 最新版本试试，解决了之前 vpc 网络 dhcp 有概率分配网络失败的问题
