### ISSUE TITLE
[求助/Help] 希望增加在现有的k8s集群中部署私有云组件

### ISSUE THREAD

**Issue by 370569218** [yunionio/cloudpods#17865]
希望增加在现有的k8s集群中部署私有云组件，目前不支持在自建k8s中部署私有云组件，通过helm只能部署云管平台，
 一般企业都有自己维护的k8s版本和集群，
看文档因为内置私有云需要节点上面安装配置 qemu, openvswitch 等各种虚拟化软件，这个可以通过配置节点 ssh账号信息的方式来进行安装不就解决在节点安装组件的问题了吗

**Comment by zexi** [comment]
@370569218 这个目前不好做，这些软件不仅要安装，还有内核参数的配置，以及涉及系统的重启等操作。可变的因素比较多，我们也无法确定 k8s 集群节点的操作系统是什么，如果是 centos7 的话，还比较好适配，但如果是其它的发行版，就不一定能成功了。
