### ISSUE TITLE
物理机转裸金属磁盘识别问题

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#17870]
物理机转裸金属时，识别磁盘的盘符 sda  sdb  sdc 这个顺序是根据磁盘什么属性排序的？
因为我们发生一个线上的问题：
  一台物理机有三块硬盘，两块800G和一块3.5T，都是ssd，我们本意是想把系统安装到800G磁盘上，但选中800G盘并安装完成后发现 系统被安装到了3.5T硬盘上，虽然/分区仍然是800G，但这个800G是从3.5T盘上分出来的，并不是上述两块800G 裸盘。
  我们进一步追查发现 3.5TB的磁盘被识别为sda，其他两块800G盘被识别为 sdb sdc。
然后我们进入了这台机器的BMC管理界面，发现这台机器的存储信息中，三块盘的信息如下：
![img_v2_cc3d9868-b663-45c7-9323-3628b3a469dg](https://github.com/yunionio/cloudpods/assets/17080656/bcc7e7c7-0091-462c-bb5e-b97c5df540ba)

从截图看，磁盘的插槽顺序从0到2正确的，但Drive id排序是相反的，根据这个情况，我们想确认下，cloudpdos 转裸金属时，识别磁盘顺序是根据  slot识别的  还是drive id？

**Comment by hoganlxj** [comment]
@tianchao001 是根据slot。物理机安装操作系统时，磁盘配置中第一块盘选800G磁盘还是3.5T 的盘？
 climc server-create-params <server_id>  查看 baremetal_disk_configs

**Comment by zexi** [comment]
@tianchao001 麻烦把 baremetal-agent 的日志导出来放到这里看下

**Comment by zexi** [comment]
@tianchao001 一直没有收到回复，我先关闭 issue 了，如果有后续日志回复，可以随时打开这个 issue 。
