### ISSUE TITLE
[BUG]宿主机管理口使用非1的VLAN ID，对应default-host-xxx的配置解析异常

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#17913]
**问题描述/What happened**:
一、官网手册如图：
![image](https://github.com/yunionio/cloudpods/assets/46590985/17e37900-7056-4e44-a43b-40f2a6974f12)

二、我用的是team，实际配置如下
1. 网卡配置
![image](https://github.com/yunionio/cloudpods/assets/46590985/4245768b-44f0-4ba9-be8d-058168693606)

2. /etc/yunion/host.conf配置
![image](https://github.com/yunionio/cloudpods/assets/46590985/4616a7f3-e055-4f0a-be45-5866f4ed88b3)

3. 配置完成后，重启default-host-xxx日志如下
![image](https://github.com/yunionio/cloudpods/assets/46590985/41a81511-64ad-4592-9a91-cdaf45ef07ae)

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): centos7.9
- Kernel (e.g. `uname -a`): Linux szbwx-ops-phy-test02 5.4.130-1.yn20221208.el7.x86_64 #1 SMP Thu Dec 8 12:09:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
  	Manufacturer: 002C069D002C
	Manufacturer: DELL
	Manufacturer: Dell Inc.
	Manufacturer: Intel
	Memory Subsystem Controller Manufacturer ID: Unknown
	Memory Subsystem Controller Product ID: Unknown
	Module Manufacturer ID: Unknown
	Module Product ID: Unknown
	Product Name: 06WXJT
	Product Name: PowerEdge R740xd
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
![image](https://github.com/yunionio/cloudpods/assets/46590985/be219073-9ba6-4602-b4d0-e3e372073f47)

**Comment by swordqiu** [comment]
我看你的bond0桥接到br0，归属二层网络bcast0，这种情况，bond0上不应该配置IP地址。如果还没有br0，则可以在host启动前设置 ifconfig bond0 0，然后再启动host。如果br0已经创建，请执行 ovs-vsctl show 确保 br0 下的物理网口只有 bond0，并且确认 br0 的IP地址是类似 169.254.x.x 的地址。如果不是，可以把 br0 删除 (ovs-vsctl del-br br0)，再重启 bond0 (确保 bond0 上没有IP）.

@SlyChen

**Comment by SlyChen** [comment]
感谢，是我看文档不够仔细。按下图模式，把host.conf的网络配置指向team0，而不是team0.3020就可以了。
![image](https://github.com/yunionio/cloudpods/assets/46590985/77c49366-91a3-4b3b-a43f-03ddb7f0392c)

**Comment by SimonXu666j** [comment]
@SlyChen 后面你的/etc/yunion/host.conf 怎么修改的
