### ISSUE TITLE
[求助/Help]宿主机磁盘故障后，按官网文档下线计算节点，重新添加物理机后转宿主机host服务启动异常

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17921]
官网下线计算节点文档：https://www.cloudpods.org/zh/docs/setup/removehost/
因为宿主机已经无法连接，因此文档中要在宿主机中的操作都无法执行。

======================

![image](https://github.com/yunionio/cloudpods/assets/10016360/36a7100b-ed01-4381-83e8-5a71601c0407)

查看init容器日志：
```shell
[root@cloudpods ~]# kubectl logs -f default-telegraf-b9rqb -n onecloud -c telegraf-init
2023/09/04 10:16:25 stat telegraf config file error stat /etc/telegraf/telegraf.conf: no such file or directory
```

登录宿主机查看，确实没有配置文件
![image](https://github.com/yunionio/cloudpods/assets/10016360/3d0edb03-166c-40d4-b449-28a6b1098884)

宿主机状态也是有问题：
![image](https://github.com/yunionio/cloudpods/assets/10016360/dcc6140e-ecc5-4195-8fe0-45d22ec91a34)

**Comment by swordqiu** [comment]
这个问题是因为 host 服务没有正确初始化化，telegraf 的配置是 host 生成的。可以先看下 host 容器的日志，确认原因。
参考：https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/

**Comment by swordqiu** [comment]
@shuoshadow

**Comment by shuoshadow** [comment]
@swordqiu 你好，我看了default-host服务中的host容器启动有这个报错，能帮忙看下是什么原因导致的吗？
![image](https://github.com/yunionio/cloudpods/assets/10016360/5253d44d-d0f7-4e3e-a74d-4847722ccd8b)

**Comment by shuoshadow** [comment]
![image](https://github.com/yunionio/cloudpods/assets/10016360/8a7fef3c-01fa-4c25-90aa-10b4face9907)

**Comment by swordqiu** [comment]
registry.cn-beijing.aliyuncs.com/swordqiu/host:qj-dev-3.10-20230906

**Comment by zexi** [comment]
> registry.cn-beijing.aliyuncs.com/swordqiu/host:qj-dev-3.10-20230906 可以替换 default-host 的镜像为这个镜像，看是否有报错

@shuoshadow

**Comment by shuoshadow** [comment]
好的 我试试
