### ISSUE TITLE
[Feature]建议 centos安装硬盘容量解除200G限制。

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17942]
**What would you like to be added**:

**Comment by wanyaoqi** [comment]
<img width="963" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/b9c835c2-96b2-4cac-b41a-ea3ddb9919b8">
@shengxianli 系统应该是限制2048G，200G是哪里

**Comment by shengxianli** [comment]
![image](https://github.com/yunionio/cloudpods/assets/32296103/bf34695f-6ff9-4408-89f9-c08c7306067c)
@wanyaoqi 自定义镜像这里。200G  有点浪费存储空间

**Comment by wanyaoqi** [comment]
@shengxianli 这个是你上传或者保存的镜像大小，是不能缩减的。你需要重新上传或者保存一个更小的

**Comment by shengxianli** [comment]
@wanyaoqi 明白了多谢
