### ISSUE TITLE
[求助/Help]请问秘钥信息如何手动修改填入

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17958]
![image](https://github.com/yunionio/cloudpods/assets/32296103/9e3b0301-8225-46cd-b806-ec9f92b357aa)
另外私有云是不支持配置标签嘛。写完标签同步完就会消失

**Comment by ioito** [comment]
目前不支持手动修改秘钥信息，你说的私有云是指哪个平台，有些没实现标签同步就会同步消失 @shengxianli

**Comment by shengxianli** [comment]
@ioito 是VMware平台的。希望可以增加手动修改秘钥。方便管理私有云同步上去的

**Comment by ioito** [comment]
> @ioito 是VMware平台的。希望可以增加手动修改秘钥。方便管理私有云同步上去的

可以尝试再次绑定下秘钥，vmware最新版是支持了名称和标签同步到vmware

**Comment by zexi** [comment]
> > @ioito 是VMware平台的。希望可以增加手动修改秘钥。方便管理私有云同步上去的
> 
> 可以尝试再次绑定下秘钥，vmware最新版是支持了名称和标签同步到vmware

@shengxianli
