### ISSUE TITLE
[求助/Help]新建centos虚拟机，会有一定概率无法免密登录

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#17973]
![image](https://github.com/yunionio/cloudpods/assets/10016360/6b8653bb-a1e0-4440-9898-3f172d04defc)
![image](https://github.com/yunionio/cloudpods/assets/10016360/a39f2aa5-ea3f-4fcc-a94f-af7df3b5ed2f)

应该如何排查这种情况？Ubuntu每次创建都没有问题，就centos不行

**Comment by wanyaoqi** [comment]
@shuoshadow 确认一下虚机是部署成功的，虚机的网络是否是通的，可以 vnc 登录到虚机里面排查一下
