### ISSUE TITLE
[求助/Help]新建虚拟机没法装机,vnc连接不了

### ISSUE THREAD

**Issue by yuyc** [yunionio/cloudpods#17984]
这是虚拟机创建参数
![image](https://github.com/yunionio/cloudpods/assets/15811147/058bc2ce-a4d6-41b0-8046-9c01348afaa0)

**Comment by wanyaoqi** [comment]
![image](https://github.com/yunionio/cloudpods/assets/18528551/25c4330e-f815-494c-be73-640036b2463d)

@yuyc  执行一下 `climc service-config-show common` 看下里面 api_server 配置

**Comment by wanyaoqi** [comment]
@yuyc api_server 不方便展示？是否和你浏览器中输入的地址一样

**Comment by yuyc** [comment]
> @yuyc api_server 不方便展示？是否和你浏览器中输入的地址一样

是一样的哈。

**Comment by yuyc** [comment]
> @yuyc api_server 不方便展示？是否和你浏览器中输入的地址一样

有其他地方能看我vnc连接失败的日志吗?

**Comment by wanyaoqi** [comment]
> > @yuyc api_server 不方便展示？是否和你浏览器中输入的地址一样
> 
> 有其他地方能看我vnc连接失败的日志吗?

@yuyc 可以看下 webconsole 服务日志 `kubectl get pods -n onecloud -o wide |grep webcon`

**Comment by yuyc** [comment]
#kubectl logs -f default-webconsole-749b5f5c8-rc22r -n onecloud


[info 2023-09-11 16:03:00 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 cc264e-7d920e POST /webconsole/server/def09d1c-e0fb-4b7b-80dd-481ee45dea56 (10.0.168.98:56546:apigateway) 55.23ms
[error 2023-09-11 16:03:00 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

**Comment by wanyaoqi** [comment]
https://stackoverflow.com/questions/65309160/client-is-not-using-the-websocket-protocol-upgrade-token-not-found-in-connec @yuyc 你使用的是什么浏览器

**Comment by yuyc** [comment]
微软的edge浏览器

**Comment by yuyc** [comment]
> https://stackoverflow.com/questions/65309160/client-is-not-using-the-websocket-protocol-upgrade-token-not-found-in-connec @yuyc 你使用的是什么浏览器

我试了一下，换成chrome也一样

**Comment by yuyc** [comment]
[info 2023-09-11 14:25:51 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 f451c8-8be387 POST /webconsole/server/5a358898-2bb1-453b-8870-ad4b0c4dd9c8 (10.0.168.98:60744:apigateway) 95.99ms
[error 2023-09-11 14:25:51 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[info 2023-09-11 14:26:32 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 a068f6-80d5d0 POST /webconsole/server/5a358898-2bb1-453b-8870-ad4b0c4dd9c8 (10.0.168.98:33122:apigateway) 53.71ms
[error 2023-09-11 14:26:32 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[warning 2023-09-11 14:27:23 session.(*SSessionManager).Get(session.go:94)] Protol: "vnc", Token: bjM611cs_3M84m-dDm7726VZp1H8DVUMrTQ5TaKGVEoPhT7oklBKBcFzXVG-BMIYtHSgIg==, Session: 5a358898-2bb1-453b-8870-ad4b0c4dd9c8 can't be accessed during 5m0s, last accessed at: 2023-09-11 14:26:32.582366088 +0000 UTC m=+605793.045989365
[error 2023-09-11 14:27:23 httperrors.HTTPError(httperrors.go:110)] Send error session not found
[info 2023-09-11 14:27:52 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 a89287-b42111 POST /webconsole/server/5a358898-2bb1-453b-8870-ad4b0c4dd9c8 (10.0.168.98:34288:apigateway) 38.12ms
[error 2023-09-11 14:27:52 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[info 2023-09-11 14:30:00 splitable.PurgeAll.func1(purge.go:38)] purge splitable command_log_tbl
[info 2023-09-11 15:54:10 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 348964-31afbd POST /webconsole/server/def09d1c-e0fb-4b7b-80dd-481ee45dea56 (10.0.168.98:49210:apigateway) 99.80ms
[error 2023-09-11 15:54:10 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[info 2023-09-11 15:54:18 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 8392c1-a2ad50 POST /webconsole/ssh/10.0.175.100 (10.0.168.98:49352:apigateway) 1082.44ms
[info 2023-09-11 16:03:00 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 cc264e-7d920e POST /webconsole/server/def09d1c-e0fb-4b7b-80dd-481ee45dea56 (10.0.168.98:56546:apigateway) 55.23ms
[error 2023-09-11 16:03:00 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[info 2023-09-11 16:29:39 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jfB9TP-p2kpzhlm6j8r265Oi6_g= 200 5a30f7-e23eef POST /webconsole/server/def09d1c-e0fb-4b7b-80dd-481ee45dea56 (10.0.168.98:52290:apigateway) 104.44ms
[error 2023-09-11 16:29:39 server.(*WebsockifyServer).ServeHTTP(websockify_server.go:75)] New websocket connection error: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

**Comment by yuyc** [comment]
> https://stackoverflow.com/questions/65309160/client-is-not-using-the-websocket-protocol-upgrade-token-not-found-in-connec @yuyc 你使用的是什么浏览器

找到了一个可能的原因，我的web前端做了nginx反向代理。还是不行
    location /webconsole/ {
        proxy_pass http://10.0.180.200:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

**Comment by wanyaoqi** [comment]
> 

@yuyc 应该是这个nginx 代理的原因，把websocket的header过滤掉了 。得研究一下 nginx配置保留之前的 header

**Comment by yuyc** [comment]
> > 
> 
> @yuyc 应该是这个nginx 代理的原因，把websocket的header过滤掉了 。得研究一下 nginx配置保留之前的 header

能给一下uri连接吗？

**Comment by yuyc** [comment]
已经解决了。调整一下nginx的配置就行了，支持websocket
