### ISSUE TITLE
[求助/Help]官方提供的镜像显示支持vmdk格式，部署完进入了维护模式

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#17997]
![image](https://github.com/yunionio/cloudpods/assets/32296103/9f608ceb-19dc-4307-8f00-edba3e8a8af5)
![image](https://github.com/yunionio/cloudpods/assets/32296103/f88b72a4-b3ad-41b7-8514-e3230435111e)
![image](https://github.com/yunionio/cloudpods/assets/32296103/4fb6ab25-cd09-4f4b-81bf-7dabffac786d)

**Comment by zexi** [comment]
@shengxianli 看起来是镜像里面没有对应的驱动，试试这个呢：https://iso.yunion.cn/vm-images/CentOS-7.6.1810-20190430.qcow2

**Comment by shengxianli** [comment]
@zexi 谢谢 这个可以了 要是7.9的就更好了

**Comment by zexi** [comment]
@shengxianli 可以参考文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/create/ 自己制作镜像
