### ISSUE TITLE
[求助/Help] 托管物理机删除裸金属后，通过带外jnlp远程窗口无法键入任何按键

### ISSUE THREAD

**Issue by kpswen** [yunionio/cloudpods#18003]
1.我们现在托管物理机遇到一个问题，裸金属删除后通过带外jnlp远程窗口无法键入任何按键，服务器是曙光I620-G20；请问是否有办法修复？

2.还存在一个问题，删除裸金属托管的服务器操作系统也直接被干掉了，是不是不太合理？

**Comment by zexi** [comment]
@kpswen 
1. 可以试试其它的远程窗口是否可以输入？一般 bmc 还有 h5 的远程窗口。另外这个问题还没有遇到过，在服务器 bios 的阶段也无法输入按键吗？
2. 如果是已经管理进来的物理机，删除是会清理硬盘，拆 raid 的。
   如果是想只清理平台的记录，不删除操作系统，可以用命令行操作：
   ```bash
   # 查询物理机记录
   $ climc host-list --host-type baremetal
   # 清理记录，$id 为要清理的物理机 id
   $ climc host-purge $id
   ```

**Comment by kpswen** [comment]
1.曙光这款服务器比较旧，没有其他方式的远程窗口；在服务器bios的阶段也无法输入按键。只能去机房接入实体设备才能操作。
2.纳管进来的物理机存在资产信息读取不正确的清空下，想删除这条记录，就会出现严重的事故；是否可以新增手动更改按钮，更新因系统读取不正确时调整资产信息的功能？

**Comment by zexi** [comment]
> 1.曙光这款服务器比较旧，没有其他方式的远程窗口；在服务器bios的阶段也无法输入按键。只能去机房接入实体设备才能操作。 2.纳管进来的物理机存在资产信息读取不正确的清空下，想删除这条记录，就会出现严重的事故；是否可以新增手动更改按钮，更新因系统读取不正确时调整资产信息的功能？

@kpswen 
1. 问题1这个情况感觉是固件的问题，试试升级下 bmc 固件能否解决
2. 目前是哪些信息需要更新？

**Comment by zexi** [comment]
等待用户反馈
