### ISSUE TITLE
[求助/Help]openeuler安装cloudpods报错“No file was found when using first_found”

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#18013]
操作系统信息：
cat /etc/os-release 
NAME="openEuler"
VERSION="22.03 (LTS-SP2)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP2)"
ANSI_COLOR="0;31"

部署yml信息：
[root@localhost ~]# cat ocboot/config-k8s-ha.yml 
primary_master_node:
  hostname: 10.1.1.13
  use_local: false
  user: root
  onecloud_version: "v3.10.5"
  db_host: 10.1.1.16
  db_user: "root"
  db_password: "Cctv@123"
  db_port: "3306"
  skip_docker_config: true
  image_repository: registry.cn-beijing.aliyuncs.com/yunionio
  ha_using_local_registry: false
  node_ip: "10.1.1.13"
  ip_autodetection_method: "can-reach=10.1.1.13"
  controlplane_host: 10.1.1.12
  controlplane_port: "6443"
  as_host: true
  high_availability: true
  use_ee: false
  enable_minio: true
  registry_mirrors:
  - https://lje6zxpk.mirror.aliyuncs.com
  insecure_registries:
  - 10.1.1.13:5000
  host_networks: "ens192/br0/10.1.1.13"

master_nodes:
  controlplane_host: 10.1.1.12
  controlplane_port: "6443"
  as_controller: true
  as_host: true
  ntpd_server: "10.1.1.13"
  registry_mirrors:
  - https://lje6zxpk.mirror.aliyuncs.com
  high_availability: true
  hosts:
  - user: root
    hostname: "10.1.1.14"
    host_networks: "ens192/br0/10.1.1.14"
  - user: root
    hostname: "10.1.1.15"
    host_networks: "ens192/br0/10.1.1.15"

报错信息：

TASK [utils/misc-check : Check if OS is supported] *****************************
ok: [10.1.1.14] => {
    "changed": false,
    "msg": "Os distribution openEuler is supported"
}
ok: [10.1.1.15] => {
    "changed": false,
    "msg": "Os distribution openEuler is supported"
}
ok: [10.1.1.13] => {
    "changed": false,
    "msg": "Os distribution openEuler is supported"
}

TASK [utils/misc-check : Check if OS VERSION is supported] *********************
ok: [10.1.1.14] => (item='22' is version('22', '==')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22' is version('22', '==')",
    "msg": "All assertions passed"
}
ok: [10.1.1.14] => (item='22.03' is version('22.03', '>=')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22.03' is version('22.03', '>=')",
    "msg": "All assertions passed"
}
ok: [10.1.1.15] => (item='22' is version('22', '==')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22' is version('22', '==')",
    "msg": "All assertions passed"
}
ok: [10.1.1.15] => (item='22.03' is version('22.03', '>=')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22.03' is version('22.03', '>=')",
    "msg": "All assertions passed"
}
ok: [10.1.1.13] => (item='22' is version('22', '==')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22' is version('22', '==')",
    "msg": "All assertions passed"
}
ok: [10.1.1.13] => (item='22.03' is version('22.03', '>=')) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "'22.03' is version('22.03', '>=')",
    "msg": "All assertions passed"
}

TASK [common : Set facts] ******************************************************
ok: [10.1.1.14]
ok: [10.1.1.15]
ok: [10.1.1.13]

TASK [common : Import task "v3_10_online.yml"] *********************************
included: /root/ocboot/onecloud/roles/common/tasks/v3_10_online.yml for 10.1.1.14, 10.1.1.15, 10.1.1.13

TASK [common : Add cloud rpm repository] ***************************************
skipping: [10.1.1.14]
skipping: [10.1.1.15]
skipping: [10.1.1.13]

TASK [common : Add cloud rpm repository for Kylin] *****************************
skipping: [10.1.1.14]
skipping: [10.1.1.15]
skipping: [10.1.1.13]

TASK [common : make cache] *****************************************************
skipping: [10.1.1.14]
skipping: [10.1.1.15]
skipping: [10.1.1.13]

TASK [common : install libselinux-python for arm64 centos] *********************
skipping: [10.1.1.14]
skipping: [10.1.1.15]
skipping: [10.1.1.13]

TASK [common : Import OS Arch tasks] *******************************************
fatal: [10.1.1.14]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
fatal: [10.1.1.15]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
fatal: [10.1.1.13]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}

PLAY RECAP *********************************************************************
10.1.1.13                  : ok=29   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0
10.1.1.14                  : ok=29   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0
10.1.1.15                  : ok=29   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0

**Comment by zexi** [comment]
@zhasm 看下这个问题

**Comment by zhasm** [comment]
@lvzhiweilv 

多谢反馈。

1. openeuler 的支持，在ocboot 的 master 分支实现了，请确保您所用的ocboot 是master分支，而不是release/3.9, release/3.10等。
2. 如果切换到master，仍然报以上错误，请在命令行之前，加上 ANSIBLE_VERBOSITY=4 ，例如：

```bash
ANSIBLE_VERBOSITY=4 python3 run.py <your ip or config.yaml>
```
然后截取一下报错的关键信息贴出来，看一下这一步所需的描述文件。

**Comment by lvzhiweilv** [comment]
@zhasm 部署完成，但是添加计算节点时，还是有初始化网络的问题。

**Comment by zexi** [comment]
> @zhasm 部署完成，但是添加计算节点时，还是有初始化网络的问题。

@lvzhiweilv 麻烦把具体的错误日志贴出来

**Comment by zexi** [comment]
> @zhasm 部署完成，但是添加计算节点时，还是有初始化网络的问题。

@lvzhiweilv 添加计算节点网络的问题可以参考这个文档进行排查：https://www.cloudpods.org/zh/docs/quickstart/allinone-converge/#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA
