### ISSUE TITLE
[求助/Help] 修改mysql VIP

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#18019]
由于更改mysql VIP的IP，数据库的内容不变，不知道需要更改哪个配置才能生效

**Comment by SlyChen** [comment]
你可以试下这个，Server字段就是MYSQL VIP：kubectl -n kube-system edit cm ocadm-config

**Comment by xxhacker** [comment]
ocadm-config 这个只是一个configmap，我查看下了一下，没有对应的deployment/daemonset，修改了也没有用

**Comment by zexi** [comment]
@xxhacker 这个 mysql 变了修改起来比较麻烦，可以这样试下：

```bash
kubectl edit oc -n onecloud default
# 把里面 spec.mysql 对应的 ip 改掉
```

<img width="534" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/c679cc53-5523-4c18-8f50-3bd785ef737c">


然后把 onecloud namespace 里面 default 开头的 configmap 删掉，这些 configmap 会被 onecloud-operator 服务新建：
```bash
kubectl get configmap -n onecloud | grep default- | awk '{print $1}' | xargs -n 1 kubectl delete configmap -n onecloud
```

等到所有的 configmap 新建后，再参考这个文档： https://www.cloudpods.org/zh/docs/ops/k8s/halt_cluster/ 把所有服务相关的 pod 停止后再启动下。
