### ISSUE TITLE
[求助/Help]

### ISSUE THREAD

**Issue by zifeng153** [yunionio/cloudpods#18012]
接口文档中的keystone v2 认证接口，通过用户名/密码或者 token 认证 请求方式为：post:,  路径为： http://prod-cn.your-api-server.com/v2.0/tokensserver.com/v2.0/tokens 

若是域 http://prod-cn.your-api-server.com换为本地登录cloudpods后的域路径，会报405,请问这是什么原因呢！

或者说我本地有了登录cloudpods平台的账号和密码，我怎么用这个账号密码配合我本地cloudpods平台路径来通过接口文档的认证呢！ 

还望指教，谢谢！

**Comment by ioito** [comment]
https://www.cloudpods.org/zh/docs/development/apisdk/01_api/
你少了端口, 请求地址应该是
http://prod-cn.your-api-server.com:30500/v2.0/tokensserver.com/v2.0/tokens

**Comment by zifeng153** [comment]
你好

我这把这个地址http://prod-cn.your-api-server.com:30500/v2.0/tokensserver.com/v2.0/tokens 中的   http://prod-cn.your-api-server.com:30500换成为本地登录平台后的域和端口号，后面的v2.0/tokensserver.com/v2.0/tokens不变，利用postman发起post请求  还是报405  

https://www.cloudpods.org/zh/docs/development/apisdk/01_api/ 这个地址，因为我这边是通过前端的方式想来达成这个接口api的验证成功，那个地址里的内容我看不明白

从接口文档上看，目前我看到是keystone v2 认证接口，通过用户名/密码或者 token 认证，但是这个路径http://prod-cn.your-api-server.com/v2.0/tokens，如我前面所说，我换成我本地登录平台后的域名就会报405.

目前我这只有账户名和密码，以及我登录平台后的域名，通过这接口文档上的哪种方式能够在前端通过postman完成接口认证呢！

还望指教，谢谢!

**Comment by ioito** [comment]
sorry, 多贴了一些path，应该是http://prod-cn.your-api-server.com:30500/v2.0/token @zifeng153 
建议用v3的token接口去认证

**Comment by zifeng153** [comment]
你好

现在不论v2和v3的方式，我配上本地的域名后，加不加端口，postman请求都会是405的情况。像是本地平台和这个接口文档没有关联起来

存在这种本地平台和公共接口文档不关联的情况么，望指教，谢谢

**Comment by ioito** [comment]
> 405

用ip呢，看起来请求都没有到cloudpods，可以看下default-web这个pod日志 @zifeng153

**Comment by zifeng153** [comment]
好的，谢谢，我再试试
