### ISSUE TITLE
[求助/Help] 改为磁盘驱动为virtio 蓝屏

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#18017]
我装了一台win server 2016虚拟机，并装了virtio驱动，然后启动虚拟机的时候指定磁盘驱动为virtio，结果就蓝屏了，提示INACCESSIBLE BOOT DEVICE,感觉就早不到启动硬盘了，改为磁盘驱动为scsi就正常了

**Comment by wanyaoqi** [comment]
@xxhacker 指定 virtio 驱动后端是使用 virtio-blk，scsi 后端是使用 virtio-scsi 驱动。
你安装的windows virtio驱动是否有安装 virtio-blk驱动

**Comment by xxhacker** [comment]
@wanyaoqi 我查看了一下我装的驱动virtio-win-0.1.229.iso，这个驱动里面有virtio-scsi，没有virtio-blk

**Comment by wanyaoqi** [comment]
> ，

@xxhacker 我不太确定是哪个驱动，可以把 virtio相关的都装一遍，应该没什么坏处

**Comment by wanyaoqi** [comment]
> > ，
> 
> @xxhacker 我不太确定是哪个驱动，可以把 virtio相关的都装一遍，应该没什么坏处



> @wanyaoqi 我查看了一下我装的驱动virtio-win-0.1.229.iso，这个驱动里面有virtio-scsi，没有virtio-blk

**Comment by zexi** [comment]
@xxhacker 等待你的反馈

**Comment by SlyChen** [comment]
我用的windows2012R2，也有同样现象，几个不同类型的驱动都装了，要换到virtio就蓝屏。
![image](https://github.com/yunionio/cloudpods/assets/46590985/2592f010-40e6-4fa5-9e8f-4862ffdb2c72)

**Comment by yulongz** [comment]
windows server 2022 按照官网安装virtio-win驱动(试验了virtio-win-0.1.229.iso和virtio-win-0.1.262.iso)后虚机正常，但是保存为镜像再创建新的虚机，就出现蓝屏INACCESSIBLE BOOT DEVICE。

**Comment by yulongz** [comment]
> windows server 2022 按照官网安装virtio-win驱动(试验了virtio-win-0.1.229.iso和virtio-win-0.1.262.iso)后虚机正常，但是保存为镜像再创建新的虚机，就出现蓝屏INACCESSIBLE BOOT DEVICE。

镜像属性的磁盘驱动要改成ide，或者已经创建的虚机的磁盘驱动更新成ide，虚机能正常创建和启动。

**Comment by yulongz** [comment]
没时间深入源码梳理整个流程，我只是根据现在现状猜测下问题。
1、是windows server 2022 iso进行安装的时候，磁盘驱动自动识别到ide(这里现在scsi驱动再安装，在win安装过程中磁盘选择页面会显示没有任何磁盘)，虚机安装完毕打成qcow2镜像。
2、通过qcow2镜像创建新的虚机时，可以看到新虚机的磁盘驱动使用的scsi(固态盘驱动)，直接导致虚机运行后显示INACCESSIBLE BOOT DEVICE，识别不到磁盘。
3、将新需求的磁盘驱动修改为ide后，重新启动新虚机，此时就能正常进入虚机。

这里的问题在于，创建qcow2镜像的时候，磁盘驱动的值仍然为”系统自动选择“，也就是创建虚机时驱动并不是ide，而变成创建虚机的默认磁盘驱动。

”DefaultDiskDriver    string `help:"default disk driver" choices:"scsi|virtio|ide" default:"scsi"`“

所以这里两种方式处理回复正常：
1、镜像属性的磁盘驱动要改成ide，后续通过镜像创建新虚机会使用磁盘驱动为ide方式。
2、已经创建的虚机需要修改磁盘驱动更新成ide方式，虚机重启也能正常启动。
