### ISSUE TITLE
[文档/Docs]主节点的pod一直起不来是怎么回事呀

### ISSUE THREAD

**Issue by Misswjy** [yunionio/cloudpods#18022]
主节点的pod一直起不来是怎么回事呀
[root@primary-master ~]# kubectl get pods -A -o wide
NAMESPACE             NAME                                                 READY   STATUS                  RESTARTS   AGE     IP              NODE             NOMINATED NODE   READINESS GATES
kube-system           calico-kube-controllers-856d747d65-q92pn             1/1     Running                 0          27m     10.40.39.37     master-1         <none>           <none>
kube-system           calico-node-9g5vm                                    1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           calico-node-nx5qs                                    1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           calico-node-vm4ft                                    1/1     Running                 2          76m     172.19.25.211   primary-master   <none>           <none>
kube-system           coredns-56544bb445-6q7n6                             1/1     Running                 0          49m     10.40.205.193   master-2         <none>           <none>
kube-system           coredns-56544bb445-wgtfd                             1/1     Running                 0          27m     10.40.39.40     master-1         <none>           <none>
kube-system           etcd-master-1                                        1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           etcd-master-2                                        1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           etcd-primary-master                                  1/1     Running                 3          75m     172.19.25.211   primary-master   <none>           <none>
kube-system           keepalived-master-1                                  1/1     Running                 3          66m     172.19.25.212   master-1         <none>           <none>
kube-system           keepalived-master-2                                  1/1     Running                 4          66m     172.19.25.213   master-2         <none>           <none>
kube-system           keepalived-primary-master                            1/1     Running                 10         75m     172.19.25.211   primary-master   <none>           <none>
kube-system           kube-apiserver-master-1                              1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           kube-apiserver-master-2                              1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           kube-apiserver-primary-master                        1/1     Running                 4          75m     172.19.25.211   primary-master   <none>           <none>
kube-system           kube-controller-manager-master-1                     1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           kube-controller-manager-master-2                     1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           kube-controller-manager-primary-master               1/1     Running                 5          75m     172.19.25.211   primary-master   <none>           <none>
kube-system           kube-proxy-6jllx                                     1/1     Running                 2          76m     172.19.25.211   primary-master   <none>           <none>
kube-system           kube-proxy-7k7zh                                     1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           kube-proxy-bkvx8                                     1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           kube-scheduler-master-1                              1/1     Running                 1          66m     172.19.25.212   master-1         <none>           <none>
kube-system           kube-scheduler-master-2                              1/1     Running                 1          66m     172.19.25.213   master-2         <none>           <none>
kube-system           kube-scheduler-primary-master                        1/1     Running                 4          75m     172.19.25.211   primary-master   <none>           <none>
kube-system           metrics-server-7f98fcdfcb-lhf2x                      1/1     Running                 0          27m     10.40.39.42     master-1         <none>           <none>
kube-system           traefik-ingress-controller-42pdv                     1/1     Running                 2          76m     172.19.25.211   primary-master   <none>           <none>
kube-system           traefik-ingress-controller-sr4r8                     1/1     Running                 1          65m     172.19.25.213   master-2         <none>           <none>
kube-system           traefik-ingress-controller-xn8vz                     1/1     Running                 1          64m     172.19.25.212   master-1         <none>           <none>
local-path-storage    local-path-provisioner-65765575dc-l5vht              1/1     Running                 0          27m     172.19.25.213   master-2         <none>           <none>
onecloud-minio        minio-0                                              1/1     Running                 0          30m     10.40.39.28     master-1         <none>           <none>
onecloud-minio        minio-1                                              1/1     Running                 0          30m     10.40.205.220   master-2         <none>           <none>
onecloud-minio        minio-2                                              1/1     Running                 0          9m12s   10.40.142.132   primary-master   <none>           <none>
onecloud-minio        minio-3                                              1/1     Running                 0          9m23s   10.40.142.191   primary-master   <none>           <none>
onecloud-monitoring   monitor-grafana-5697c9bbc6-4rmhf                     1/1     Running                 0          23m     10.40.205.237   master-2         <none>           <none>
onecloud-monitoring   monitor-kube-state-metrics-6c97499758-rl8mp          1/1     Running                 0          23m     10.40.205.238   master-2         <none>           <none>
onecloud-monitoring   monitor-loki-0                                       1/1     Running                 0          22m     10.40.39.45     master-1         <none>           <none>
onecloud-monitoring   monitor-minio-0                                      1/1     Running                 0          30m     10.40.39.25     master-1         <none>           <none>
onecloud-monitoring   monitor-minio-1                                      1/1     Running                 0          9m15s   10.40.142.129   primary-master   <none>           <none>
onecloud-monitoring   monitor-minio-2                                      1/1     Running                 0          30m     10.40.205.217   master-2         <none>           <none>
onecloud-monitoring   monitor-minio-3                                      1/1     Running                 0          30m     10.40.205.218   master-2         <none>           <none>
onecloud-monitoring   monitor-monitor-stack-operator-54d8c46577-fn22b      1/1     Running                 0          23m     10.40.39.44     master-1         <none>           <none>
onecloud-monitoring   monitor-promtail-9z2n7                               1/1     Running                 1          23m     10.40.142.189   primary-master   <none>           <none>
onecloud-monitoring   monitor-promtail-k74vx                               1/1     Running                 0          23m     10.40.205.239   master-2         <none>           <none>
onecloud-monitoring   monitor-promtail-v4sl6                               1/1     Running                 0          23m     10.40.39.43     master-1         <none>           <none>
onecloud              default-ansibleserver-75c6db9d8f-7rxvv               1/1     Running                 5          27m     10.40.39.41     master-1         <none>           <none>
onecloud              default-apigateway-676fbbf7d7-98k5g                  1/1     Running                 0          41m     10.40.205.206   master-2         <none>           <none>
onecloud              default-apimap-5d8755b6c6-pfc6t                      1/1     Running                 0          42m     10.40.39.13     master-1         <none>           <none>
onecloud              default-climc-9bc7cb6c9-r2dxm                        1/1     Running                 0          27m     10.40.205.232   master-2         <none>           <none>
onecloud              default-cloudevent-748c59cd75-brn8g                  1/1     Running                 3          27m     10.40.205.235   master-2         <none>           <none>
onecloud              default-cloudid-7cfbdb9cd9-v2q78                     1/1     Running                 0          28m     10.40.39.30     master-1         <none>           <none>
onecloud              default-cloudmon-68d979c859-9clsc                    1/1     Running                 0          35m     10.40.39.17     master-1         <none>           <none>
onecloud              default-cloudproxy-847747f9f9-j4jgh                  1/1     Running                 0          28m     10.40.205.223   master-2         <none>           <none>
onecloud              default-devtool-7fbf656c4-zgx6x                      1/1     Running                 0          28m     10.40.39.36     master-1         <none>           <none>
onecloud              default-esxi-agent-56bd4b7576-8v2qc                  1/1     Running                 0          43m     10.40.205.200   master-2         <none>           <none>
onecloud              default-etcd-q2gqfj948m                              1/1     Running                 0          44m     10.40.205.194   master-2         <none>           <none>
onecloud              default-etcd-x7rflzbszw                              1/1     Running                 0          11m     10.40.142.190   primary-master   <none>           <none>
onecloud              default-etcd-xpdspg48c2                              1/1     Running                 0          44m     10.40.39.3      master-1         <none>           <none>
onecloud              default-glance-6c4bb77fb-r8z2f                       1/1     Running                 0          28m     10.40.39.29     master-1         <none>           <none>
onecloud              default-host-6kmzw                                   3/3     Running                 2          42m     172.19.25.212   master-1         <none>           <none>
onecloud              default-host-deployer-7tr9n                          1/1     Running                 0          42m     10.40.205.204   master-2         <none>           <none>
onecloud              default-host-deployer-nkx4f                          0/1     CrashLoopBackOff        22         42m     10.40.142.188   primary-master   <none>           <none>
onecloud              default-host-deployer-rj6kx                          1/1     Running                 0          42m     10.40.39.16     master-1         <none>           <none>
onecloud              default-host-health-2lwk6                            1/1     Running                 0          42m     172.19.25.212   master-1         <none>           <none>
onecloud              default-host-health-nm6v2                            1/1     Running                 0          42m     172.19.25.213   master-2         <none>           <none>
onecloud              default-host-health-rnmc7                            1/1     Running                 4          42m     172.19.25.211   primary-master   <none>           <none>
onecloud              default-host-image-2tnlf                             0/1     CrashLoopBackOff        22         42m     172.19.25.211   primary-master   <none>           <none>
onecloud              default-host-image-bpp2x                             1/1     Running                 0          42m     172.19.25.212   master-1         <none>           <none>
onecloud              default-host-image-crmhm                             1/1     Running                 0          42m     172.19.25.213   master-2         <none>           <none>
onecloud              default-host-jzrqw                                   3/3     Running                 3          42m     172.19.25.213   master-2         <none>           <none>
onecloud              default-host-qrpxj                                   2/3     CrashLoopBackOff        28         42m     172.19.25.211   primary-master   <none>           <none>
onecloud              default-influxdb-5867957456-l65bd                    1/1     Running                 0          44m     10.40.39.5      master-1         <none>           <none>
onecloud              default-keystone-5f696b8749-8q87t                    1/1     Running                 0          44m     10.40.39.6      master-1         <none>           <none>
onecloud              default-kubeserver-6c9bd84c86-6fwkz                  1/1     Running                 1          27m     10.40.39.39     master-1         <none>           <none>
onecloud              default-logger-66bb688475-ntvk5                      1/1     Running                 0          28m     10.40.39.33     master-1         <none>           <none>
onecloud              default-monitor-5bfb5b8485-f7gsj                     1/1     Running                 5          27m     10.40.39.38     master-1         <none>           <none>
onecloud              default-notify-74957d5b75-49nwq                      1/1     Running                 0          28m     10.40.205.231   master-2         <none>           <none>
onecloud              default-onecloud-service-operator-56f775846b-2rbct   1/1     Running                 0          35m     10.40.205.207   master-2         <none>           <none>
onecloud              default-ovn-north-55c4ffdb45-zw8f8                   1/1     Running                 0          43m     10.40.39.11     master-1         <none>           <none>
onecloud              default-region-76f9f9c758-zr7xt                      1/1     Running                 0          44m     10.40.205.195   master-2         <none>           <none>
onecloud              default-region-dns-c4xpd                             1/1     Running                 0          43m     172.19.25.213   master-2         <none>           <none>
onecloud              default-region-dns-fhnk7                             1/1     Running                 0          43m     172.19.25.212   master-1         <none>           <none>
onecloud              default-region-dns-p2lk4                             1/1     Running                 2          43m     172.19.25.211   primary-master   <none>           <none>
onecloud              default-scheduledtask-84896bc56c-wrs64               1/1     Running                 0          28m     10.40.205.222   master-2         <none>           <none>
onecloud              default-scheduler-6b88ffff54-sqwm8                   1/1     Running                 0          41m     10.40.205.205   master-2         <none>           <none>
onecloud              default-telegraf-6mxps                               1/1     Running                 0          44m     172.19.25.213   master-2         <none>           <none>
onecloud              default-telegraf-964gq                               1/1     Running                 0          44m     172.19.25.212   master-1         <none>           <none>
onecloud              default-telegraf-fltp2                               0/1     Init:CrashLoopBackOff   25         44m     172.19.25.211   primary-master   <none>           <none>
onecloud              default-vpcagent-94c8fb984-5dmlr                     1/1     Running                 3          27m     10.40.205.236   master-2         <none>           <none>
onecloud              default-web-58789967cd-tx8l4                         1/1     Running                 7          43m     10.40.205.198   master-2         <none>           <none>
onecloud              default-webconsole-7574b78ddd-5xshk                  1/1     Running                 0          28m     10.40.205.225   master-2         <none>           <none>
onecloud              default-yunionconf-65796966bb-xmdcs                  1/1     Running                 0          28m     10.40.39.32     master-1         <none>           <none>
onecloud              onecloud-operator-8c79d9b78-mxf8r                    1/1     Running                 0          11m     10.40.39.46     master-1         <none>           <none>

[root@primary-master ~]# kubectl logs default-host-deployer-nkx4f -n onecloud
[info 230915 03:56:54 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/host.conf
[fatal 230915 03:56:54 options.ParseOptions(options.go:321)] Parse configuration file: open /etc/yunion/host.conf: no such file or directory

[root@primary-master ~]# kubectl logs default-host-image-2tnlf  -n onecloud
[info 230915 03:56:36 options.ParseOptions(options.go:308)] Use configuration file: /etc/yunion/host.conf
[fatal 230915 03:56:36 options.ParseOptions(options.go:311)] Parse configuration file: open /etc/yunion/host.conf: no such file or directory

[root@primary-master ~]# kubectl logs default-host-qrpxj  -n onecloud
Error from server (BadRequest): a container name must be specified for pod default-host-qrpxj, choose one of: [host ovn-controller sdnagent]

[root@primary-master ~]# kubectl logs default-telegraf-fltp2  -n onecloud
Error from server (BadRequest): container "telegraf" in pod "default-telegraf-fltp2" is waiting to start: PodInitializing
[root@primary-master ~]#

**Comment by Misswjy** [comment]
我发现是/etc/yunion/下面没host.conf，我把其它节点的复制过去了，把ip改了 现在只有一个没起来
[root@primary-master ~]# kubectl get pods -A -o wide
NAMESPACE             NAME                                                 READY   STATUS                  RESTARTS   AGE   IP              NODE             NOMINATED NODE   READINESS GATES
kube-system           calico-kube-controllers-856d747d65-q92pn             1/1     Running                 0          36m   10.40.39.37     master-1         <none>           <none>
kube-system           calico-node-9g5vm                                    1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           calico-node-nx5qs                                    1/1     Running                 1          75m   172.19.25.213   master-2         <none>           <none>
kube-system           calico-node-vm4ft                                    1/1     Running                 2          85m   172.19.25.211   primary-master   <none>           <none>
kube-system           coredns-56544bb445-6q7n6                             1/1     Running                 0          58m   10.40.205.193   master-2         <none>           <none>
kube-system           coredns-56544bb445-wgtfd                             1/1     Running                 0          36m   10.40.39.40     master-1         <none>           <none>
kube-system           etcd-master-1                                        1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           etcd-master-2                                        1/1     Running                 1          75m   172.19.25.213   master-2         <none>           <none>
kube-system           etcd-primary-master                                  1/1     Running                 3          84m   172.19.25.211   primary-master   <none>           <none>
kube-system           keepalived-master-1                                  1/1     Running                 3          75m   172.19.25.212   master-1         <none>           <none>
kube-system           keepalived-master-2                                  1/1     Running                 4          75m   172.19.25.213   master-2         <none>           <none>
kube-system           keepalived-primary-master                            1/1     Running                 10         84m   172.19.25.211   primary-master   <none>           <none>
kube-system           kube-apiserver-master-1                              1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           kube-apiserver-master-2                              1/1     Running                 1          74m   172.19.25.213   master-2         <none>           <none>
kube-system           kube-apiserver-primary-master                        1/1     Running                 4          84m   172.19.25.211   primary-master   <none>           <none>
kube-system           kube-controller-manager-master-1                     1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           kube-controller-manager-master-2                     1/1     Running                 1          74m   172.19.25.213   master-2         <none>           <none>
kube-system           kube-controller-manager-primary-master               1/1     Running                 5          84m   172.19.25.211   primary-master   <none>           <none>
kube-system           kube-proxy-6jllx                                     1/1     Running                 2          85m   172.19.25.211   primary-master   <none>           <none>
kube-system           kube-proxy-7k7zh                                     1/1     Running                 1          75m   172.19.25.213   master-2         <none>           <none>
kube-system           kube-proxy-bkvx8                                     1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           kube-scheduler-master-1                              1/1     Running                 1          75m   172.19.25.212   master-1         <none>           <none>
kube-system           kube-scheduler-master-2                              1/1     Running                 1          74m   172.19.25.213   master-2         <none>           <none>
kube-system           kube-scheduler-primary-master                        1/1     Running                 4          84m   172.19.25.211   primary-master   <none>           <none>
kube-system           metrics-server-7f98fcdfcb-lhf2x                      1/1     Running                 0          36m   10.40.39.42     master-1         <none>           <none>
kube-system           traefik-ingress-controller-42pdv                     1/1     Running                 2          84m   172.19.25.211   primary-master   <none>           <none>
kube-system           traefik-ingress-controller-sr4r8                     1/1     Running                 1          74m   172.19.25.213   master-2         <none>           <none>
kube-system           traefik-ingress-controller-xn8vz                     1/1     Running                 1          73m   172.19.25.212   master-1         <none>           <none>
local-path-storage    local-path-provisioner-65765575dc-l5vht              1/1     Running                 0          36m   172.19.25.213   master-2         <none>           <none>
onecloud-minio        minio-0                                              1/1     Running                 0          39m   10.40.39.28     master-1         <none>           <none>
onecloud-minio        minio-1                                              1/1     Running                 0          39m   10.40.205.220   master-2         <none>           <none>
onecloud-minio        minio-2                                              1/1     Running                 0          17m   10.40.142.132   primary-master   <none>           <none>
onecloud-minio        minio-3                                              1/1     Running                 0          18m   10.40.142.191   primary-master   <none>           <none>
onecloud-monitoring   monitor-grafana-5697c9bbc6-4rmhf                     1/1     Running                 0          32m   10.40.205.237   master-2         <none>           <none>
onecloud-monitoring   monitor-kube-state-metrics-6c97499758-rl8mp          1/1     Running                 0          32m   10.40.205.238   master-2         <none>           <none>
onecloud-monitoring   monitor-loki-0                                       1/1     Running                 0          31m   10.40.39.45     master-1         <none>           <none>
onecloud-monitoring   monitor-minio-0                                      1/1     Running                 0          39m   10.40.39.25     master-1         <none>           <none>
onecloud-monitoring   monitor-minio-1                                      1/1     Running                 0          17m   10.40.142.129   primary-master   <none>           <none>
onecloud-monitoring   monitor-minio-2                                      1/1     Running                 0          39m   10.40.205.217   master-2         <none>           <none>
onecloud-monitoring   monitor-minio-3                                      1/1     Running                 0          39m   10.40.205.218   master-2         <none>           <none>
onecloud-monitoring   monitor-monitor-stack-operator-54d8c46577-fn22b      1/1     Running                 0          32m   10.40.39.44     master-1         <none>           <none>
onecloud-monitoring   monitor-promtail-9z2n7                               1/1     Running                 1          32m   10.40.142.189   primary-master   <none>           <none>
onecloud-monitoring   monitor-promtail-k74vx                               1/1     Running                 0          32m   10.40.205.239   master-2         <none>           <none>
onecloud-monitoring   monitor-promtail-v4sl6                               1/1     Running                 0          32m   10.40.39.43     master-1         <none>           <none>
onecloud              default-ansibleserver-75c6db9d8f-7rxvv               1/1     Running                 5          36m   10.40.39.41     master-1         <none>           <none>
onecloud              default-apigateway-676fbbf7d7-98k5g                  1/1     Running                 0          50m   10.40.205.206   master-2         <none>           <none>
onecloud              default-apimap-5d8755b6c6-pfc6t                      1/1     Running                 0          51m   10.40.39.13     master-1         <none>           <none>
onecloud              default-climc-9bc7cb6c9-r2dxm                        1/1     Running                 0          36m   10.40.205.232   master-2         <none>           <none>
onecloud              default-cloudevent-748c59cd75-brn8g                  1/1     Running                 3          36m   10.40.205.235   master-2         <none>           <none>
onecloud              default-cloudid-7cfbdb9cd9-v2q78                     1/1     Running                 0          37m   10.40.39.30     master-1         <none>           <none>
onecloud              default-cloudmon-68d979c859-9clsc                    1/1     Running                 0          43m   10.40.39.17     master-1         <none>           <none>
onecloud              default-cloudproxy-847747f9f9-j4jgh                  1/1     Running                 0          37m   10.40.205.223   master-2         <none>           <none>
onecloud              default-devtool-7fbf656c4-zgx6x                      1/1     Running                 0          37m   10.40.39.36     master-1         <none>           <none>
onecloud              default-esxi-agent-56bd4b7576-8v2qc                  1/1     Running                 0          51m   10.40.205.200   master-2         <none>           <none>
onecloud              default-etcd-q2gqfj948m                              1/1     Running                 0          53m   10.40.205.194   master-2         <none>           <none>
onecloud              default-etcd-x7rflzbszw                              1/1     Running                 0          20m   10.40.142.190   primary-master   <none>           <none>
onecloud              default-etcd-xpdspg48c2                              1/1     Running                 0          53m   10.40.39.3      master-1         <none>           <none>
onecloud              default-glance-6c4bb77fb-r8z2f                       1/1     Running                 0          37m   10.40.39.29     master-1         <none>           <none>
onecloud              default-host-6kmzw                                   3/3     Running                 2          50m   172.19.25.212   master-1         <none>           <none>
onecloud              default-host-deployer-7tr9n                          1/1     Running                 0          51m   10.40.205.204   master-2         <none>           <none>
onecloud              default-host-deployer-nkx4f                          1/1     Running                 24         51m   10.40.142.188   primary-master   <none>           <none>
onecloud              default-host-deployer-rj6kx                          1/1     Running                 0          51m   10.40.39.16     master-1         <none>           <none>
onecloud              default-host-health-2lwk6                            1/1     Running                 0          50m   172.19.25.212   master-1         <none>           <none>
onecloud              default-host-health-nm6v2                            1/1     Running                 0          50m   172.19.25.213   master-2         <none>           <none>
onecloud              default-host-health-rnmc7                            1/1     Running                 4          50m   172.19.25.211   primary-master   <none>           <none>
onecloud              default-host-image-2tnlf                             1/1     Running                 24         51m   172.19.25.211   primary-master   <none>           <none>
onecloud              default-host-image-bpp2x                             1/1     Running                 0          51m   172.19.25.212   master-1         <none>           <none>
onecloud              default-host-image-crmhm                             1/1     Running                 0          51m   172.19.25.213   master-2         <none>           <none>
onecloud              default-host-jzrqw                                   3/3     Running                 3          50m   172.19.25.213   master-2         <none>           <none>
onecloud              default-host-qrpxj                                   3/3     Running                 31         50m   172.19.25.211   primary-master   <none>           <none>
onecloud              default-influxdb-5867957456-l65bd                    1/1     Running                 0          53m   10.40.39.5      master-1         <none>           <none>
onecloud              default-keystone-5f696b8749-8q87t                    1/1     Running                 0          52m   10.40.39.6      master-1         <none>           <none>
onecloud              default-kubeserver-6c9bd84c86-6fwkz                  1/1     Running                 1          36m   10.40.39.39     master-1         <none>           <none>
onecloud              default-logger-66bb688475-ntvk5                      1/1     Running                 0          37m   10.40.39.33     master-1         <none>           <none>
onecloud              default-monitor-5bfb5b8485-f7gsj                     1/1     Running                 5          36m   10.40.39.38     master-1         <none>           <none>
onecloud              default-notify-74957d5b75-49nwq                      1/1     Running                 0          37m   10.40.205.231   master-2         <none>           <none>
onecloud              default-onecloud-service-operator-56f775846b-2rbct   1/1     Running                 0          43m   10.40.205.207   master-2         <none>           <none>
onecloud              default-ovn-north-55c4ffdb45-zw8f8                   1/1     Running                 0          51m   10.40.39.11     master-1         <none>           <none>
onecloud              default-region-76f9f9c758-zr7xt                      1/1     Running                 0          52m   10.40.205.195   master-2         <none>           <none>
onecloud              default-region-dns-c4xpd                             1/1     Running                 0          51m   172.19.25.213   master-2         <none>           <none>
onecloud              default-region-dns-fhnk7                             1/1     Running                 0          51m   172.19.25.212   master-1         <none>           <none>
onecloud              default-region-dns-p2lk4                             1/1     Running                 2          51m   172.19.25.211   primary-master   <none>           <none>
onecloud              default-scheduledtask-84896bc56c-wrs64               1/1     Running                 0          37m   10.40.205.222   master-2         <none>           <none>
onecloud              default-scheduler-6b88ffff54-sqwm8                   1/1     Running                 0          50m   10.40.205.205   master-2         <none>           <none>
onecloud              default-telegraf-6mxps                               1/1     Running                 0          53m   172.19.25.213   master-2         <none>           <none>
onecloud              default-telegraf-964gq                               1/1     Running                 0          53m   172.19.25.212   master-1         <none>           <none>
onecloud              default-telegraf-fltp2                               0/1     Init:CrashLoopBackOff   27         53m   172.19.25.211   primary-master   <none>           <none>
onecloud              default-vpcagent-94c8fb984-5dmlr                     1/1     Running                 3          36m   10.40.205.236   master-2         <none>           <none>
onecloud              default-web-58789967cd-tx8l4                         1/1     Running                 7          52m   10.40.205.198   master-2         <none>           <none>
onecloud              default-webconsole-7574b78ddd-5xshk                  1/1     Running                 0          37m   10.40.205.225   master-2         <none>           <none>
onecloud              default-yunionconf-65796966bb-xmdcs                  1/1     Running                 0          37m   10.40.39.32     master-1         <none>           <none>
onecloud              onecloud-operator-8c79d9b78-mxf8r                    1/1     Running                 0          19m   10.40.39.46     master-1         <none>           <none>

**Comment by Misswjy** [comment]
[root@primary-master ~]# kubectl get pods default-telegraf-fltp2 -A -o wide
error: a resource cannot be retrieved by name across all namespaces
[root@primary-master ~]# kubectl get pods default-telegraf-fltp2 -n onecloud  -o wide
NAME                     READY   STATUS                  RESTARTS   AGE   IP              NODE             NOMINATED NODE   READINESS GATES
default-telegraf-fltp2   0/1     Init:CrashLoopBackOff   27         54m   172.19.25.211   primary-master   <none>           <none>
[root@primary-master ~]# kubectl logs default-telegraf-fltp2  -n onecloud
Error from server (BadRequest): container "telegraf" in pod "default-telegraf-fltp2" is waiting to start: PodInitializing
[root@primary-master ~]# kubectl describe pod  default-telegraf-fltp2  -n onecloud
Name:           default-telegraf-fltp2
Namespace:      onecloud
Priority:       0
Node:           primary-master/172.19.25.211
Start Time:     Fri, 15 Sep 2023 11:15:50 +0800
Labels:         app=telegraf
                app.kubernetes.io/component=telegraf
                app.kubernetes.io/instance=onecloud-cluster-qcr9
                app.kubernetes.io/managed-by=onecloud-operator
                app.kubernetes.io/name=onecloud-cluster
                controller-revision-hash=6c5c89665
                pod-template-generation=2
Annotations:    onecloud.yunion.io/last-applied-configuration:
                  {"volumes":[{"name":"etc-telegraf","hostPath":{"path":"/etc/telegraf","type":"DirectoryOrCreate"}},{"name":"proc","hostPath":{"path":"/pro...
Status:         Pending
IP:             172.19.25.211
Controlled By:  DaemonSet/default-telegraf
Init Containers:
  telegraf-init:
    Container ID:  docker://6270795fcfcb3dc1de4ffd79f920e98f86c121b72c8a08e410338b5f93c6cc16
    Image:         registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init:release-1.19.2-0
    Image ID:      docker-pullable://registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init@sha256:dbda0b59b2506e76fd33547de7e13bc701b6571b4134485d1d96493b269b770e
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/telegraf-init
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 15 Sep 2023 12:06:47 +0800
      Finished:     Fri, 15 Sep 2023 12:06:47 +0800
    Ready:          False
    Restart Count:  27
    Environment:
      NODENAME:       (v1:spec.nodeName)
      INFLUXDB_URL:  https://default-influxdb:30086
    Mounts:
      /etc/telegraf from etc-telegraf (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from onecloud-operator-token-84nzg (ro)
Containers:
  telegraf:
    Container ID:  
    Image:         registry.cn-beijing.aliyuncs.com/yunionio/telegraf:release-1.19.2-2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      /usr/bin/telegraf
      -config
      /etc/telegraf/telegraf.conf
      -config-directory
      /etc/telegraf/telegraf.d
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      HOST_ETC:           /hostfs/etc
      HOST_PROC:          /hostfs/proc
      HOST_SYS:           /hostfs/sys
      HOST_MOUNT_PREFIX:  /hostfs
    Mounts:
      /dev from dev (rw)
      /etc/telegraf from etc-telegraf (rw)
      /hostfs from root (ro)
      /hostfs/proc from proc (ro)
      /hostfs/sys from sys (ro)
      /opt/cloud from cloud (rw)
      /var/run from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from onecloud-operator-token-84nzg (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  etc-telegraf:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/telegraf
    HostPathType:  DirectoryOrCreate
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  Directory
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run
    HostPathType:  Directory
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  cloud:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cloud
    HostPathType:  Directory
  onecloud-operator-token-84nzg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  onecloud-operator-token-84nzg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/controlplane:NoSchedule
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason          Age                   From                     Message
  ----     ------          ----                  ----                     -------
  Normal   Scheduled       54m                   default-scheduler        Successfully assigned onecloud/default-telegraf-fltp2 to primary-master
  Normal   Pulled          53m (x5 over 54m)     kubelet, primary-master  Container image "registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init:release-1.19.2-0" already present on machine
  Normal   Created         53m (x5 over 54m)     kubelet, primary-master  Created container telegraf-init
  Normal   Started         53m (x5 over 54m)     kubelet, primary-master  Started container telegraf-init
  Warning  BackOff         39m (x70 over 54m)    kubelet, primary-master  Back-off restarting failed container
  Warning  FailedMount     34m                   kubelet, primary-master  MountVolume.SetUp failed for volume "onecloud-operator-token-84nzg" : couldn't propagate object cache: timed out waiting for the condition
  Normal   SandboxChanged  34m                   kubelet, primary-master  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          32m (x4 over 34m)     kubelet, primary-master  Container image "registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init:release-1.19.2-0" already present on machine
  Normal   Created         32m (x4 over 34m)     kubelet, primary-master  Created container telegraf-init
  Normal   Started         32m (x4 over 34m)     kubelet, primary-master  Started container telegraf-init
  Warning  BackOff         32m (x11 over 34m)    kubelet, primary-master  Back-off restarting failed container
  Normal   Pulled          27m (x4 over 29m)     kubelet, primary-master  Container image "registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init:release-1.19.2-0" already present on machine
  Normal   Created         27m (x4 over 29m)     kubelet, primary-master  Created container telegraf-init
  Normal   Started         27m (x4 over 29m)     kubelet, primary-master  Started container telegraf-init
  Warning  BackOff         24m (x27 over 29m)    kubelet, primary-master  Back-off restarting failed container
  Normal   SandboxChanged  19m                   kubelet, primary-master  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          18m (x4 over 19m)     kubelet, primary-master  Container image "registry.cn-beijing.aliyuncs.com/yunionio/telegraf-init:release-1.19.2-0" already present on machine
  Normal   Created         18m (x4 over 19m)     kubelet, primary-master  Created container telegraf-init
  Normal   Started         18m (x4 over 19m)     kubelet, primary-master  Started container telegraf-init
  Warning  BackOff         4m46s (x70 over 19m)  kubelet, primary-master  Back-off restarting failed container

**Comment by zexi** [comment]
@Misswjy 麻烦执行下下面的命令，把每个 node 的 labels 显示出来：

```bash
kubectl get nodes --show-labels
```

**Comment by zexi** [comment]
等待用户反馈
