### ISSUE TITLE
[求助/Help] 关闭不必要的组件

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#18023]
我想在集群中关闭esxiagent这个组件，是修改kubectl edit oc -n onecloud default，把esxi下面disable改成true,改了后我发现还是有这个esxi-agent这个pod，还是直接通过K8S命令把kubectl delete deployments.apps default-esxi-agent -n onecloud？

**Comment by zexi** [comment]
@xxhacker 修改 oc 里面的 esxi disable 为 true ，只是说删除 default-esxi-agent 后不会自动新建了，需要再手动 delete 这个 deployment 后就可以了。
