### ISSUE TITLE
[求助/Help] 虚拟机监控问题-虚拟机监控没有数据（非agent）

### ISSUE THREAD

**Issue by ruifaling** [yunionio/cloudpods#18041]
在openstack上部署了telegraf和influxdb，telegraf 开启了libvirt插件，influxdb里已经采集到虚拟机的数据，但是在cloudpods 页面上还是没有监控数据

**Comment by ruifaling** [comment]
influxdb 数据表
![infludb](https://github.com/yunionio/cloudpods/assets/79310393/d5ee1215-d5ab-4aae-820e-5dbb8d975d82)

**Comment by zexi** [comment]
@ruifaling 系统自带有 influxdb ，不需要额外安装，现在你的问题是说新建的 openstack 虚拟机在 cloudpods 平台这边没有监控数据吗？

**Comment by ruifaling** [comment]
@zexi 是的，cloudpods里的监控数据不是来自于宿主机的 telegraf吗？

**Comment by zexi** [comment]
> @zexi 是的，cloudpods里的监控数据不是来自于宿主机的 telegraf吗？

@ruifaling openstack 的虚拟机应该是从 openstack 平台查询的吧，这个虚拟机在 openstack 那边有监控吗？

**Comment by ruifaling** [comment]
openstack 上有装telegraf，监控了虚拟机，从openstack的influxdb里能看到这个虚机的监控数据，但是cloudpods里没有
![image](https://github.com/yunionio/cloudpods/assets/79310393/e8cb84b9-eb15-4de0-9cfa-ae1ec34cc58b)

**Comment by ruifaling** [comment]
需要做什么样的转换和设置呢

**Comment by ioito** [comment]
非agent不支持监控
