### ISSUE TITLE
[求助/Help]宿主机计算节点下线后重新加入，状态一直为初始化且报警为nodata

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#18045]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/1b7472a1-a8c4-4378-8f16-137d391a3f4a)

按照文档https://www.cloudpods.org/zh/docs/setup/removehost/进行计算节点下线重启，重新加入后，宿主机状态一直为初始化
已经将宿主机所有服务进行重启，查看host日志如下：
kubectl -n onecloud logs default-host-wr2h9 -c host --since 10m -f
[info 230919 02:00:01 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 230919 02:00:01 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/host.conf
[info 230919 02:00:01 options.ParseOptions(options.go:340)] Set log level to "info"
[info 2023-09-19 02:00:01 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/common/common.conf
[info 2023-09-19 02:00:01 options.ParseOptions(options.go:340)] Set log level to "info"
[info 2023-09-19 02:00:01 hostman.(*SHostService).InitService(host_services.go:63)] exec socket path: /var/run/onecloud/exec.sock
[info 2023-09-19 02:00:01 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-09-19 02:00:01 appsrv.NewApplication(appsrv.go:118)] App hostId: Nh_yef-Fb1tycXia4bsqL6uF2eQ= (host,cloudpods-Client-1,10.1.99.30)
2023/09/19 02:00:01 Allow hosts []
[info 2023-09-19 02:00:01 appsrv.(*Application).SetDefaultTimeout(appsrv.go:134)] adjust application default timeout to 60.000000 seconds
[info 2023-09-19 02:00:01 hostinfo.DetectCpuInfo(hostinfohelper.go:77)] cpuinfo freq 0
[error 2023-09-19 02:00:01 sysutils.ParseCPUInfo(sysutils.go:122)] Failed to get cpu MHz
[error 2023-09-19 02:00:01 sysutils.ParseCPUInfo(sysutils.go:125)] Failed to get cpu cache size
[info 2023-09-19 02:00:01 hostinfo.NewHostInfo(hostinfo.go:2318)] CPU Model 0x662 Microcode 2
[info 2023-09-19 02:00:02 hostinfo.NewHostInfo(hostinfo.go:2338)] Get kubelet container image Fs: /opt/docker, eviction config: {"evictionHard":{"imagefs.available":{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"memory.available":{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0}},"nodefs.available":{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}},"nodefs.inodesFree":{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05}}}}
[info 2023-09-19 02:00:03 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:403)] I/O Scheduler switch to bfq
[info 2023-09-19 02:00:03 fileutils2.ChangeBlkdevParameter(fileutils.go:202)] Set queue/scheduler of sdb to bfq
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).getKubeReservedMemMb(hostinfo.go:1512)] Kubelet memory threshold subtracted: 100MB
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).Init(hostinfo.go:195)] Start detectHostInfo
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:864)] KVM API VERSION 12
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:869)] KVM CAP MAX VCPUS: 512
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectKVMMaxCpus(hostinfo.go:877)] KVM CAP NR VCPUS: 64
[error 2023-09-19 02:00:04 sysutils.isNestSupport(kvm.go:160)] exit status 1
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectOsDist(hostinfo.go:757)] DetectOsDist openEuler 22.03
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectQemuVersion(hostinfo.go:831)] Detect qemu version is 4.2.0
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectOvsVersion(hostinfo.go:972)] Detect OVS version is 2.10.5
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).detectOvsKOVersion(hostinfo.go:989)] kernel module openvswitch vermagic:       5.10.0-153.12.0.92.oe2203sp2.aarch64 SMP mod_unload modversions aarch64
WARNING: failed to determine memory area for node: open /sys/devices/system/node/node2/hugepages: no such file or directory
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).Init(hostinfo.go:206)] Start parseConfig
[info 2023-09-19 02:00:04 hostinfo.NewNIC(hostinfohelper.go:233)] IP 10.1.99.30/br0/eno1
[info 2023-09-19 02:00:04 hostinfo.NewNIC(hostinfohelper.go:286)] Confirm to configuration!!
[info 2023-09-19 02:00:04 hostinfo.(*SNIC).SetupDhcpRelay(hostinfohelper.go:202)] Not enable dhcp relay on nic: &hostinfo.SNIC{Inter:"eno1", Bridge:"br0", Ip:"10.1.99.30", Network:"", WireId:"", Mask:24, Bandwidth:1000, BridgeDev:(*hostbridge.SOVSBridgeDriver)(0x4001167b60), dhcpServer:(*hostdhcp.SGuestDHCPServer)(0x400138a390)}
[info 2023-09-19 02:00:04 hostinfo.(*SHostInfo).setupOvnChassis(hostinfo.go:224)] Start setting up ovn chassis
[info 2023-09-19 02:00:05 hostman.(*SHostService).RunService.func1(host_services.go:84)] Auth complete!!
[info 2023-09-19 02:00:05 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-09-19 02:00:05 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-09-19 02:00:05 storageman.StartSnapshotRecycle(storage_base.go:490)] Snapshot recyle job started
[info 2023-09-19 02:00:05 guestman.NewGuestCpuSetCounter(guesthelper.go:187)] NewGuestCpuSetCounter from topo: {"architecture":"numa","nodes":[{"caches":[{"level":1,"logical_processors":[0],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[1],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[2],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[3],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[4],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[5],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[6],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[7],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[0],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[1],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[2],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[3],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[4],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[5],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[6],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[7],"size_bytes":32768,"type":"data"},{"level":2,"logical_processors":[0,1,2,3],"size_bytes":33554432,"type":"unified"},{"level":2,"logical_processors":[4,5,6,7],"size_bytes":33554432,"type":"unified"}],"cores":[{"id":0,"index":0,"logical_processors":[0],"total_threads":1},{"id":1,"index":1,"logical_processors":[1],"total_threads":1},{"id":2,"index":2,"logical_processors":[2],"total_threads":1},{"id":3,"index":3,"logical_processors":[3],"total_threads":1},{"id":4,"index":4,"logical_processors":[4],"total_threads":1},{"id":5,"index":5,"logical_processors":[5],"total_threads":1},{"id":6,"index":6,"logical_processors":[6],"total_threads":1},{"id":7,"index":7,"logical_processors":[7],"total_threads":1}],"distances":[10,20,40,30,20,30,50,40],"id":0,"memory":{"supported_page_sizes":[1073741824,2097152,33554432,65536],"total_physical_bytes":33285996544,"total_usable_bytes":31773851648}},{"caches":[{"level":1,"logical_processors":[8],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[9],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[10],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[11],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[12],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[13],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[14],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[15],"size_bytes":32768,"type":"instruction"},{"level":1,"logical_processors":[8],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[9],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[10],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[11],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[12],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[13],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[14],"size_bytes":32768,"type":"data"},{"level":1,"logical_processors":[15],"size_bytes":32768,"type":"data"},{"level":2,"logical_processors":[8,9,10,11],"size_bytes":33554432,"type":"unified"},{"level":2,"logical_processors":[12,13,14,15],"size_bytes":33554432,"type":"unified"}],"cores":[{"id":10,"index":0,"logical_processors":[10],"total_threads":1},{"id":11,"index":1,"logical_processors":[11],"total_threads":1},{"id":12,"index":2,"logical_processors":[12],"total_threads":1},{"id":13,"index":3,"logical_processors":[13],"total_threads":1},{"id":14,"index":4,"logical_processors":[14],"total_threads":1},{"id":15,"index":5,"logical_processors":[15],"total_threads":1},{"id":8,"index":6,"logical_processors":[8],"total_threads":1},{"id":9,"index":7,"logical_processors":[9],"total_threads":1}],"distances":[20,10,30,20,30,20,40,30],"id":1,"memory":{"supported_page_sizes":[1073741824,2097152,33554432,65536],"total_physical_bytes":34359738368,"total_usable_bytes":32738283520}}]}
[info 2023-09-19 02:00:05 hostdhcp.(*SGuestDHCPServer).Start(dhcpserver.go:72)] SGuestDHCPServer starting ...
[info 2023-09-19 02:00:05 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:143)] KVM max cpus count: 64
[info 2023-09-19 02:00:05 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:161)] Machine type virt max cpus: 64
[info 2023-09-19 02:00:05 guestman.(*SGuestManager).InitPythonPath.func1(guestman.go:176)] Python path /usr/bin/python
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).ensureMasterNetworks(hostinfo.go:1207)] Master ip 10.1.99.30 to fetch wire
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).initZoneInfo(hostinfo.go:1249)] Start GetZoneInfo b814020e-75ae-46d5-8f38-c666d2e67b9e
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).initHostRecord(hostinfo.go:1155)] host health manager on host down 
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).doSendPhysicalNicInfo(hostinfo.go:1649)] upload physical nic: eno1(b4:05:5d:9a:46:68)
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).doUploadNicInfoInternal(hostinfo.go:1662)] Upload NIC br: if:eno1
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).doSendPhysicalNicInfo(hostinfo.go:1649)] upload physical nic: eno2(b4:05:5d:9a:46:69)
[info 2023-09-19 02:00:07 hostinfo.(*SHostInfo).doUploadNicInfoInternal(hostinfo.go:1662)] Upload NIC br: if:eno2
[info 2023-09-19 02:00:08 hostinfo.(*SHostInfo).doSendPhysicalNicInfo(hostinfo.go:1649)] upload physical nic: eno3(b4:05:5d:9a:46:66)
[info 2023-09-19 02:00:08 hostinfo.(*SHostInfo).doUploadNicInfoInternal(hostinfo.go:1662)] Upload NIC br: if:eno3
[info 2023-09-19 02:00:08 hostinfo.(*SHostInfo).doSendPhysicalNicInfo(hostinfo.go:1649)] upload physical nic: eno4(b4:05:5d:9a:46:67)
[info 2023-09-19 02:00:08 hostinfo.(*SHostInfo).doUploadNicInfoInternal(hostinfo.go:1662)] Upload NIC br: if:eno4
[info 2023-09-19 02:00:08 isolated_device.getPassthroughGPUS(gpu.go:66)] filter address []
[info 2023-09-19 02:00:08 isolated_device.(*PCIDevice).IsBootVGA(gpu.go:368)] PCI address 0b:00.0 is boot_vga: /sys/devices/pci0000:00/0000:00:00.0/0000:01:00.0/0000:02:0c.0/0000:0a:00.0/0000:0b:00.0/boot_vga
[info 2023-09-19 02:00:08 isolated_device.(*PCIDevice).forceBindVFIOPCIDriver(gpu.go:386)] &isolated_device.PCIDevice{Addr:"0b:00.0", ClassName:"VGA compatible controller", ClassCode:"0300", VendorName:"ASPEED Technology, Inc.", VendorId:"1a03", DeviceName:"ASPEED Graphics Family", DeviceId:"2000", SubvendorName:"ASPEED Technology, Inc.", SubvendorId:"1a03", SubdeviceName:"ASPEED Graphics Family", SubdeviceId:"2000", ModelName:"", RestIOMMUGroupDevs:[]*isolated_device.PCIDevice(nil)} is boot vga card, skip it
[warning 2023-09-19 02:00:08 isolated_device.getPassthroughGPUS(gpu.go:90)] GPU {"bus_id":"0b:00.0","class_code":"0300","class_name":"VGA compatible controller","device_id":"2000","device_name":"ASPEED Graphics Family","subdevice_id":"2000","subdevice_name":"ASPEED Graphics Family","subvendor_id":"1a03","subvendor_name":"ASPEED Technology, Inc.","vendor_id":"1a03","vendor_name":"ASPEED Technology, Inc."} use kernel driver "ast", skip it
[info 2023-09-19 02:00:08 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:209)] Storage /opt/cloud/workspace/disks and kubelet imageFs /opt/docker share same device /dev/sdb1
[info 2023-09-19 02:00:08 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:221)] Storage /opt/cloud/workspace/disks sizeMb 3208522, usablePercent 0.950000
[info 2023-09-19 02:00:08 storageman.(*SLocalStorage).SyncStorageInfo(storage_local.go:255)] Sync storage info /host_10.1.99.30_local_storage_0
[info 2023-09-19 02:00:08 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1878)] storage id 
[error 2023-09-19 02:00:08 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1880)] storage config %!s(<nil>)
[error 2023-09-19 02:00:08 timeutils2.AddTimeout.func1.1(timeutils.go:31)] runtime error: invalid memory address or nil pointer dereference
goroutine 657 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x20
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x60
panic({0x2255500, 0x4d1a510})
	/usr/lib/go/src/runtime/panic.go:838 +0x20c
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onSyncStorageInfoSucc(0x400131fb00?, {0x2e15708, 0x400131fb00}, {0x0, 0x0})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1881 +0x110
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStoragesInternal(0x4000d40180, {0x52cd780?, 0x4000d40180?, 0x0?})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1868 +0x3b8
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStorages(0x4000d40180?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1736 +0x6c
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0x4000d40180)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1098 +0x128
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x60
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x70
[info 2023-09-19 02:01:05 ovnutils.configBridgeMtu.func1(ovnutils.go:42)] set brvpc MTU to 1500 success!

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/4ee67734-d5cc-4c17-966a-266e09732858)

**Comment by wanyaoqi** [comment]
@lvzhiweilv 你使用的是哪个版本，可以贴一下版本信息

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/22bcb78f-ff90-4435-8869-69d379819df4)

**Comment by wanyaoqi** [comment]
@lvzhiweilv  你使用 climc storage-list 看下是否有输出

**Comment by lvzhiweilv** [comment]
![图片](https://github.com/yunionio/cloudpods/assets/25196014/f2b7d05d-a0cd-4412-a72a-93e3c3e416f5)

**Comment by wanyaoqi** [comment]
@lvzhiweilv 只有一台宿主机么

**Comment by fangpsh** [comment]
我遇到类似的情况，也是下线后重新加入。
host 服务日志：
```
[info 2023-09-19 03:06:42 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:216)] Storage /opt/cloud/workspace/disks and kubelet nodeFs share same device /dev/mapper/centos-root
[info 2023-09-19 03:06:42 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:221)] Storage /opt/cloud/workspace/disks sizeMb 3620934, usablePercent 0.950000
[info 2023-09-19 03:06:42 storageman.(*SLocalStorage).SyncStorageInfo(storage_local.go:255)] Sync storage info /host_192.168.8.13_local_storage_0
[info 2023-09-19 03:06:42 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1878)] storage id
[error 2023-09-19 03:06:42 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1880)] storage config %!s(<nil>)
[error 2023-09-19 03:06:42 timeutils2.AddTimeout.func1.1(timeutils.go:31)] runtime error: invalid memory address or nil pointer dereference
goroutine 632 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x59
panic({0x2955860, 0x542b8f0})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onSyncStorageInfoSucc(0xc001233200?, {0x3515078, 0xc001233200}, {0x0, 0x0})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1881 +0x15f
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStoragesInternal(0xc00093c180, {0x59deb68?, 0x0?, 0x0?})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1868 +0x514
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStorages(0xc00093c180?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1736 +0x6d
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc00093c180)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1098 +0x14f
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x5c
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x65


```

```
climc storage-list
        +--------------------------------------+-----------------------------------+----------+----------------------+---------+--------------+-------------+---------+--------------+
        |                  ID                  |               Name                | Capacity | Actual_capacity_used | Status  | Storage_type | Medium_type | Enabled | public_scope |
        +--------------------------------------+-----------------------------------+----------+----------------------+---------+--------------+-------------+---------+--------------+
        | bb172ddb-6d1f-4a2b-8c33-8eed0786f598 | host_192.168.8.13_local_storage_0 | 3811510  | 5916                 | offline | local        | rotate      | true    | system       |


```

看起来是storage 同名，无法创建，使用`climc storage-delete ` 删除之后，再删除pod，重启服务即可。

**Comment by fangpsh** [comment]
@wanyaoqi  是3.10.5 修改了部分逻辑吗，印象中3.10.4 和之前版本，我也有重新删除再加入过，没遇到这种情况。

**Comment by wanyaoqi** [comment]
@lvzhiweilv @fangpsh 看起来是宿主机下线，宿主机上的存储没有清楚导致的

**Comment by lvzhiweilv** [comment]
@ wanyaoqi 目前仅加了一台宿主机，看到我的存储的状态是online

**Comment by wanyaoqi** [comment]
> limc storage-delete

@lvzhiweilv 可以先安装这个方法，先 storage-delete 删除这个存储后重启一下host-agent试试
