### ISSUE TITLE
[BUG] 使用 feature-config-k8s 打开 k8s 管理功能失效

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#18050]
**问题描述/What happened**:

climc feature-config-$feature --switch {on|off}

以上命令来控制功能，没生效，过一段时间设置会自动还原。

<img width="1236" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/62d60770-fdee-4dcf-b101-d9754edb5c91">

**Comment by zexi** [comment]
通过该 PR 修复了：https://github.com/yunionio/cloudpods-operator/pull/959/files
目前解决办法是升级 operator 镜像到 registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.10-0919.1，命令如下：

```bash
kubectl set image -n onecloud deployment/onecloud-operator *=registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.10-0919.1

```

**Comment by chenjacken** [comment]
收到，验证过，问题已解决。谢谢。
