### ISSUE TITLE
[BUG]创建ZStack私有云虚拟机问题

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18057]
zstack上不涉及磁盘类型的，但是cloudpods平台上要选择，无法提交创建
![image](https://github.com/yunionio/cloudpods/assets/59357035/9a365265-704a-4b66-9306-4e4c45127061)
![image](https://github.com/yunionio/cloudpods/assets/59357035/aa522fe6-0270-4886-acbf-aaf0d6de6ee0)

**Comment by easy-mj** [comment]
方便把capability接口的返回信息发一下吗？

**Comment by ninghongwu** [comment]
@easy-mj 不好意思，怎么看capability接口的返回信息呢

**Comment by ioito** [comment]
浏览器右击检查，看网络请求 @ninghongwu

**Comment by ninghongwu** [comment]
@easy-mj @ioito 这个行吗，还需要提供哪些信息

![image](https://github.com/yunionio/cloudpods/assets/59357035/3bfe86c0-cd59-457b-bd56-20f0a7cba50c)

**Comment by ioito** [comment]
![image](https://github.com/yunionio/cloudpods/assets/13750250/f23d1489-ac05-4485-bf48-1e22639bab57)
这条请求的返回结果

**Comment by ninghongwu** [comment]
@ioito  response结果如下：

{
    "auto_alloc_network_count": 47,
    "available_host_count": 0,
    "brands": [
        "ZStack"
    ],
    "compute_engine_brands": [
        "ZStack"
    ],
    "data_storage_types": [],
    "data_storage_types2": {},
    "data_storage_types3": {},
    "disabled_brands": [],
    "gpu_models": [],
    "hypervisors": [
        "zstack"
    ],
    "instance_capabilities": [
        {
            "default_account": {
                "linux": {
                    "changeable": false,
                    "default_account": "root"
                },
                "windows": {
                    "changeable": false,
                    "default_account": "Administrator"
                }
            },
            "hypervisor": "zstack",
            "provider": "ZStack"
        }
    ],
    "max_data_disk_count": 12,
    "max_nic_count": 1,
    "min_data_disk_count": 0,
    "min_nic_count": 1,
    "network_manage_brands": [
        "OneCloud",
        "ZStack"
    ],
    "pci_model_types": [],
    "public_network_count": 47,
    "resource_types": [
        "shared"
    ],
    "sched_policy_support": true,
    "specs": {
        "hosts": {
            "cpu:32/manufacture:ZStack/mem:772473M/model:Unknown/nic:0": {
                "count": 1,
                "cpu": 32,
                "manufacture": "ZStack",
                "mem": 772473,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:32/manufacture:ZStack/mem:773797M/model:Unknown/nic:0": {
                "count": 1,
                "cpu": 32,
                "manufacture": "ZStack",
                "mem": 773797,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:44/manufacture:ZStack/mem:708782M/model:Unknown/nic:0": {
                "count": 1,
                "cpu": 44,
                "manufacture": "ZStack",
                "mem": 708782,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:44/manufacture:ZStack/mem:772474M/model:Unknown/nic:0": {
                "count": 2,
                "cpu": 44,
                "manufacture": "ZStack",
                "mem": 772474,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:44/manufacture:ZStack/mem:772529M/model:Unknown/nic:0": {
                "count": 1,
                "cpu": 44,
                "manufacture": "ZStack",
                "mem": 772529,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:44/manufacture:ZStack/mem:773793M/model:Unknown/nic:0": {
                "count": 2,
                "cpu": 44,
                "manufacture": "ZStack",
                "mem": 773793,
                "model": "Unknown",
                "nic_count": 0
            },
            "cpu:57/manufacture:ZStack/mem:772465M/model:Unknown/nic:0": {
                "count": 1,
                "cpu": 57,
                "manufacture": "ZStack",
                "mem": 772465,
                "model": "Unknown",
                "nic_count": 0
            }
        },
        "isolated_devices": {}
    },
    "storage_types": [],
    "storage_types2": {},
    "storage_types3": {},
    "usable": true
}

**Comment by ioito** [comment]
@ninghongwu 再执行下以下命令，看下返回结果
`climc storage-list --scope system --show-emulated --provider ZStack`

**Comment by ninghongwu** [comment]
@ioito 是没有读到存储吗
[root@clouds-manager ~]# climc storage-list --scope system --show-emulated --provider ZStack
***  Total: 0  ***

**Comment by ioito** [comment]
> @ioito 是没有读到存储吗 [root@clouds-manager ~]# climc storage-list --scope system --show-emulated --provider ZStack *** Total: 0 ***

看起来是的，没有通过api拉取到存储，可能后端region服务有异常，需要提取下region的日志

**Comment by zexi** [comment]
@ninghongwu 麻烦把后端 region 服务的日志发下，用下面的方式：

```bash
# 把 region pod 的日志重定向到 /tmp/region.log
kubectl get pods -n onecloud -o wide | grep default-region | grep -v dns | awk '{print $1}' | xargs -I{} kubectl logs -n onecloud {} > /tmp/region.log
```

然后把 /tmp/region.log 放上来，或者也可以自己先看下有没有报错

**Comment by ninghongwu** [comment]
@zexi @ioito 最近zstack增加了本地存储，能识别到宿主机的本地存储，但是SAN存储识别不到，region log上传了麻烦看下，谢谢
[region.log](https://github.com/yunionio/cloudpods/files/13455441/region.log)


[root@clouds-manager ~]# climc storage-list --scope system --show-emulated --provider ZStack
+--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+
|                  ID                  |                Name                | Capacity | Actual_capacity_used | Status | Storage_type | Medium_type | Enabled | public_scope |
+--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+
| 578243c3-6777-488c-8a13-0e22062a1511 | LocalDatastore/Host23-Local        | 15808008 | 0                    | online | localstorage | rotate      | true    | system       |
| 31225eeb-1297-40a2-8834-0bf2baa0fe8e | LocalDatastore/Host22-Local        | 13519880 | 0                    | online | localstorage | rotate      | true    | system       |
| 50350ae0-e641-4b29-885b-5c1c4036c2f1 | LocalDatastore/Host21-Local        | 6655496  | 0                    | online | localstorage | rotate      | true    | system       |
| 0e5be172-8fd2-450f-8d20-212ca90092ad | LocalDatastore/Host20-Local        | 10089224 | 0                    | online | localstorage | rotate      | true    | system       |
| 160af3b7-4a1f-4754-8aa4-b8d97d3b71f2 | LocalDatastore-Host19/Host19-Local | 13726728 | 0                    | online | localstorage | rotate      | true    | system       |
+--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+
***  Total: 5 Pages: 1 Limit: 20 Offset: 0 Page: 1  ***

**Comment by zexi** [comment]
> @zexi @ioito 最近zstack增加了本地存储，能识别到宿主机的本地存储，但是SAN存储识别不到，region log上传了麻烦看下，谢谢 [region.log](https://github.com/yunionio/cloudpods/files/13455441/region.log)
> 
> [root@clouds-manager ~]# climc storage-list --scope system --show-emulated --provider ZStack +--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+ | ID | Name | Capacity | Actual_capacity_used | Status | Storage_type | Medium_type | Enabled | public_scope | +--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+ | 578243c3-6777-488c-8a13-0e22062a1511 | LocalDatastore/Host23-Local | 15808008 | 0 | online | localstorage | rotate | true | system | | 31225eeb-1297-40a2-8834-0bf2baa0fe8e | LocalDatastore/Host22-Local | 13519880 | 0 | online | localstorage | rotate | true | system | | 50350ae0-e641-4b29-885b-5c1c4036c2f1 | LocalDatastore/Host21-Local | 6655496 | 0 | online | localstorage | rotate | true | system | | 0e5be172-8fd2-450f-8d20-212ca90092ad | LocalDatastore/Host20-Local | 10089224 | 0 | online | localstorage | rotate | true | system | | 160af3b7-4a1f-4754-8aa4-b8d97d3b71f2 | LocalDatastore-Host19/Host19-Local | 13726728 | 0 | online | localstorage | rotate | true | system | +--------------------------------------+------------------------------------+----------+----------------------+--------+--------------+-------------+---------+--------------+ *** Total: 5 Pages: 1 Limit: 20 Offset: 0 Page: 1 ***

@ninghongwu 请重新打开这个 issue ，或者关于此问题提一个新的 issue ，被关闭了的 issue 我们很难注意到。
