### ISSUE TITLE
[求助/Help]在创建虚拟机时报错

### ISSUE THREAD

**Issue by lvzhiweilv** [yunionio/cloudpods#18055]
{
  "class": "UnclassifiedError",
  "code": 500,
  "details": "found module by prices: No such module prices",
  "time": "2023-09-19T16:52:54+08:00"
}
![图片](https://github.com/yunionio/cloudpods/assets/25196014/d42cbada-ff3a-49cc-91eb-ca019fc7ad7b)

**Comment by ioito** [comment]
开源版不应该会有这个api请求，你之前切换过企业版本么，还是自己打包的前端镜像

**Comment by lvzhiweilv** [comment]
@ioito 之前切换过企业版，然后有切换回开源版的。

**Comment by ioito** [comment]
https://github.com/yunionio/dashboard/actions/workflows/docker.yml 在这里找一个自动打包好的前端镜像替换下试试

**Comment by zexi** [comment]
@lvzhiweilv 把前端镜像替换成这个版本试试：

registry.cn-beijing.aliyuncs.com/yunionio/web:v3.10-1007.0
