### ISSUE TITLE
控制节点的服务器重启服务器后出现的问题

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#18051]
你好，问一下，我的控制节点的49服务器异常宕机后，重启服务器后，执行 kubectl get pods -n onecloud -o wide
报：The connection to the server 192.166.62.49:6443 was refused - did you specify the right host or port?

另外有次执行成功了，查看到到49服务器上的pod都是errror和CrashLoopBackOff 
查看了一个pod的日志，报：
![image](https://github.com/yunionio/cloudpods/assets/58723494/0fddbea3-98bd-472f-a3a3-1beb55635c30)

![image](https://github.com/yunionio/cloudpods/assets/58723494/4732da15-d0fd-460c-af29-5d3487945575)
![image](https://github.com/yunionio/cloudpods/assets/58723494/275e1f38-960f-4ac0-b923-015f507c00cf)

访问页面，报这个
![image](https://github.com/yunionio/cloudpods/assets/58723494/812c8548-cbd7-4b96-a09f-c68c1cd722db)

服务器异常缓慢，
![image](https://github.com/yunionio/cloudpods/assets/58723494/f6fa0b2e-6c34-438f-804c-b1eb3053c309)

请帮忙看看如何处理。

**Comment by wanyaoqi** [comment]
@szz1113-1119 刚重启的时候kubelet可能在重启pod， 所以负载很高。你需要用 kubectl -n onecloud describe pod <POD>  或者 kubectl logs 看下pod为什么没起来。一般来说需要先启动 keystone , etcd, region 这几个pod

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/b31e7140-a623-4897-a480-bd4f9590760a)
执行命令会报访问6443拒绝，更别说执行其他命令了，上面有对应的pod的日志

**Comment by szz1113-1119** [comment]
能否我重新搭建一个控制节点，然后吧数据库数据导出，然后迁移到另外一台控制节点服务器，其他宿主机如何迁移，需要大神指点

**Comment by szz1113-1119** [comment]
另外问一下，mysql的用户名密码，默认是多少

**Comment by wanyaoqi** [comment]
> ![image](https://user-images.githubusercontent.com/58723494/269130575-b31e7140-a623-4897-a480-bd4f9590760a.png) 执行命令会报访问6443拒绝，更别说执行其他命令了，上面有对应的pod的日志

6443是 k8s apiserver没起来，具体要看相应的容器日志。docker ps -a | grep apiserver，然后 docker logs。可能是你这个集群的 etcd 没有起来。

> 另外问一下，mysql的用户名密码，默认是多少

mysql密码需要看 oc 配置 kubectl get oc -o yaml -n onecloud | less

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/de91e623-abb5-4eee-b07b-3034dd7d9862)
起了这么多，是不是不正常

**Comment by szz1113-1119** [comment]
另外，能否我重新搭建一个控制节点，然后吧数据库数据导出，然后迁移到另外一台控制节点服务器，其他宿主机如何迁移，需要大神指点

**Comment by szz1113-1119** [comment]
> > ![image](https://user-images.githubusercontent.com/58723494/269130575-b31e7140-a623-4897-a480-bd4f9590760a.png) 执行命令会报访问6443拒绝，更别说执行其他命令了，上面有对应的pod的日志
> 
> 6443是 k8s apiserver没起来，具体要看相应的容器日志。docker ps -a | grep apiserver，然后 docker logs。可能是你这个集群的 etcd 没有起来。

刚才看了一下apiserver的日志，报2379，redis无法连接

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/f0111ea8-630d-4d3b-90c2-3d60c7319722)

**Comment by wanyaoqi** [comment]
> > > ![image](https://user-images.githubusercontent.com/58723494/269130575-b31e7140-a623-4897-a480-bd4f9590760a.png) 执行命令会报访问6443拒绝，更别说执行其他命令了，上面有对应的pod的日志
> > 
> > 
> > 6443是 k8s apiserver没起来，具体要看相应的容器日志。docker ps -a | grep apiserver，然后 docker logs。可能是你这个集群的 etcd 没有起来。
> 
> 刚才看了一下apiserver的日志，报2379，redis无法连接

k8s 应该是没有使用 redis的 🤔

**Comment by wanyaoqi** [comment]
> ![image](https://user-images.githubusercontent.com/58723494/269202583-f0111ea8-630d-4d3b-90c2-3d60c7319722.png)

这个是没有连上 etcd 。得 看下etcd pod 日志
