### ISSUE TITLE
[求助/Help]纳管了京东云，但是平台上没有选项

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18052]
创建云主机时，无法选择京东云
![image](https://github.com/yunionio/cloudpods/assets/59357035/5a072e44-9959-4dce-bc7e-91d841ae6721)

**Comment by ioito** [comment]
@ninghongwu 京东云目前不支持新建

**Comment by ninghongwu** [comment]
@ioito 收到，谢谢
