### ISSUE TITLE
[求助/Help]资源未同步(状态显示正常)

### ISSUE THREAD

**Issue by shixin66** [yunionio/cloudpods#18060]
有两个华为云账号    国际站的账号能正常同步资源
![image](https://github.com/yunionio/cloudpods/assets/19245023/728ba577-44f3-4d98-95d6-b959d63dcdc3)
![image](https://github.com/yunionio/cloudpods/assets/19245023/7f1ee12b-3703-4544-944e-54e6bf13f8da)
当前产品
Cloudpods
软件版本
v3.10.5

中国站的账号 状态显示正常 能获取到余额  未提示缺少权限 但是 资源未同步 如下图
![image](https://github.com/yunionio/cloudpods/assets/19245023/52eda426-adc7-4e13-abf9-783a56b6cca8)
![image](https://github.com/yunionio/cloudpods/assets/19245023/96a4ce05-5a4f-41d9-86d2-ba457a5c47f0)

**Comment by ioito** [comment]
1. 登录下国际站华为云到这个地址 https://console.huaweicloud.com/apiexplorer/#/openapi/BSS/doc?api=ShowCustomerAccountBalances 点击下调试，看下是否有余额信息
2. 提取下华为云中国区同步时的region日志
@shixin66

**Comment by shixin66** [comment]
国际站账号  是后付费  账上没有余额 资源同步正常   没有问题的

**Comment by shixin66** [comment]
[同步日志.xlsx](https://github.com/yunionio/cloudpods/files/12667942/default.xlsx)
以上是同步日志

**Comment by ioito** [comment]
@shixin66 这个问题遇到过，近期会修复 https://github.com/yunionio/cloudmux/pull/441

**Comment by ioito** [comment]
@shixin66 registry.cn-beijing.aliyuncs.com/yunionio/region:master-20230920-solo 使用这个镜像试下

**Comment by shixin66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/19245023/50548178-689e-4026-adaf-577c021e6d12)
使用这个镜像    资源同步正常了

**Comment by shixin66** [comment]
目前我单独搭建了一个测试环境   资源同步正常               请问一下   正式版本  什么时候更新      我等发布正式版本       还是我单独更新使用这个镜像即可

**Comment by ioito** [comment]
> 目前我单独搭建了一个测试环境 资源同步正常 请问一下 正式版本 什么时候更新 我等发布正式版本 还是我单独更新使用这个镜像即可

单独更新这个镜像即可，后面的版本将包含这个更新

**Comment by shixin66** [comment]
已更新   资源同步正常  问题已解决  谢谢
