### ISSUE TITLE
[求助/Help]宿主机 host pod报错

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#18069]
一台宿主机在发生服务器重启后服务离线，我们尝试删除host pod 重启服务，host pod在运行状态下，日志频繁报错，并且发现该宿主机上的8885端口没有启动，求助。
![image](https://github.com/yunionio/cloudpods/assets/17080656/79f3a941-6c8d-4e6e-bd29-8bcc62fa2403)

**Comment by hoganlxj** [comment]
@tianchao001 看着宿主机的mac地址变了，可以参考
https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/#%E5%AE%BF%E4%B8%BB%E6%9C%BAmac%E6%94%B9%E5%8F%98%E4%BC%9A%E5%AF%BC%E8%87%B4host%E6%9C%8D%E5%8A%A1%E7%A6%BB%E7%BA%BF%E9%9C%80%E8%A6%81%E6%9B%B4%E6%94%B9%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%9C%A8%E5%B9%B3%E5%8F%B0%E6%B3%A8%E5%86%8C%E7%9A%84mac%E5%9C%B0%E5%9D%80%E5%85%B7%E4%BD%93%E6%AD%A5%E9%AA%A4%E5%A6%82%E4%B8%8B

**Comment by tianchao001** [comment]
根据大佬提供的文档，问题已经解决，多谢。
