### ISSUE TITLE
控制节点的服务器无法启动k8s，能否重新搭建一个控制节点，然后把数据库数据导出，然后迁移到另外一台控制节点服务器，其他宿主机同步迁移过去

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#18071]
控制节点的服务器无法启动k8s，能否重新搭建一个控制节点，然后把数据库数据导出，然后迁移到另外一台控制节点服务器，其他宿主机同步迁移过去

**Comment by hoganlxj** [comment]
@szz1113-1119 这种情况不支持。 可以先看控制节点上k8s集群无法启动报什么错？

**Comment by szz1113-1119** [comment]
问一下，控制节点能搭建一个主备，保证可用？还是说只能是搭建负载高可用，如果搭建，是否可以手动配置搭建，不使用你们提供的一键化安装

**Comment by zexi** [comment]
@szz1113-1119 参考文档可以进行高可用部署：https://www.cloudpods.org/zh/docs/setup/ha-ce/
