### ISSUE TITLE
[求助/Help] 编译 host-image需要设置$LIBQEMUIO_PATH

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#18094]
Start to build component: host-image
Need set $LIBQEMUIO_PATH env to build host-image

请问这个$LIBQEMUIO_PATH应该设置成哪个地址？

**Comment by wanyaoqi** [comment]
这个路径是编译qemu中 libqemuio 后静态库的路径，编译方法可以参考 https://github.com/yunionio/qemu

**Comment by flowlsj** [comment]
> 这个路径是编译qemu中 libqemuio 后静态库的路径，编译方法可以参考 https://github.com/yunionio/qemu

![image](https://github.com/yunionio/cloudpods/assets/7510377/7c3c2014-3c78-469e-8610-cdfa6ea5dfd8)
好像也不对哦

**Comment by nyl1001** [comment]
这问题没有人跟吗？

**Comment by zexi** [comment]
@flowlsj  @nyl1001 参考这个 PR 的文档步骤试试能否编译出来？https://github.com/yunionio/website/pull/69
