### ISSUE TITLE
[求助/Help] VNC 到虚拟机失败

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#18095]
在前端界面 vnc 到虚拟机，发现 webconsole 报错：
[info 2023-09-21 02:21:54 appsrv.(*Application).ServeHTTP(appsrv.go:286)] 7on5t_ZVDh9yfA31gVxP9FoWBgM= 200 e8faef-c0de79 POST /webconsole/server/f03b557f-189b-4c27-88a0-f6d9505892f7 (10.100.201.72:43046:apigateway) 27.36ms
webconsole
[error 2023-09-21 02:21:56 httperrors.HTTPError(httperrors.go:110)] Send error Invalid remote port: 0
webconsole
goroutine 2408 [running]:
webconsole
runtime/debug.Stack()
webconsole
    /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
webconsole
runtime/debug.PrintStack()
webconsole
    /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
webconsole
yunion.io/x/onecloud/pkg/httperrors.HTTPError({0x15a0158?, 0xc0009643c0?}, {0x159ecd0?, 0xc0003cc0e0?}, {0xc0005d6180, 0x16}, 0x1f4, {0x13b948d, 0x11}, {{0xc0005d6180, ...}, ...})
webconsole
    /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:112 +0x405
webconsole
yunion.io/x/onecloud/pkg/httperrors.JsonClientError(...)
webconsole
    /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:117
webconsole
yunion.io/x/onecloud/pkg/httperrors.GeneralServerError({0x15a0158, 0xc0009643c0}, {0x159ecd0, 0xc0003cc0e0}, {0x1595e60?, 0xc000077f60?})
webconsole
    /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:122 +0xdd
webconsole
yunion.io/x/onecloud/pkg/webconsole/server.(*ConnectionServer).ServeHTTP(0xc0003b8300?, {0x159ecd0, 0xc0003cc0e0}, 0xc0003b8400)
webconsole
    /root/go/src/yunion.io/x/onecloud/pkg/webconsole/server/server.go:74 +0x3cd
webconsole
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003ea600, {0x159ecd0, 0xc0003cc0e0}, 0xc0003b8200)
webconsole
    /root/go/src/yunion.io/x/onecloud/vendor/github.com/gorilla/mux/mux.go:212 +0x202
webconsole
net/http.serverHandler.ServeHTTP({0xc0009641b0?}, {0x159ecd0, 0xc0003cc0e0}, 0xc0003b8200)
webconsole
    /usr/lib/go/src/net/http/server.go:2916 +0x43b
webconsole
net/http.(*conn).serve(0xc0008e55e0, {0x15a0158, 0xc00036c360})
webconsole
    /usr/lib/go/src/net/http/server.go:1966 +0x5d7
webconsole
created by net/http.(*Server).Serve
webconsole
    /usr/lib/go/src/net/http/server.go:3071 +0x4db

**Comment by hoganlxj** [comment]
@flowlsj 这个问题是 宿主机列表中 access_ip 为空导致的。 可以重启host 服务
kubectl rollout restart ds -n onecloud default-host

**Comment by ioito** [comment]
#18102 优化下错误提示
