### ISSUE TITLE
[Feature]添加计算节点的时候无法使用--offline-data-path选项

### ISSUE THREAD

**Issue by weiwhy** [yunionio/cloudpods#18105]
**添加计算节点的时候无法使用--offline-data-path选项**:
```
ocboot.py add-node --offline-data-path /rpm/ add-node 10.168.26.216 10.168.222.140
```

**安装主节点的时候无法使用--enable-host-on-vm**
导致如果在虚拟机环境下安装主节点，安装完成后无法找到宿主机

**Comment by zhasm** [comment]
@weiwhy 您好~ 开源版不支持离线部署。离线部署属于商业版支持的 feature。如有商业需求，请留言，我们的商务工作人员会与您联系~

**Comment by zexi** [comment]
@weiwhy 另一个问题，--enable-host-on-vm 应该是可以在虚拟机里面部署计算节点服务，可以看下 default-host-xxx 这个 pod 有没有创建，如果创建了但没有注册进来，就无法找到宿主机，需要按照下面的文档排查原因：

https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/

**Comment by weiwhy** [comment]
> @weiwhy 另一个问题，--enable-host-on-vm 应该是可以在虚拟机里面部署计算节点服务，可以看下 default-host-xxx 这个 pod 有没有创建，如果创建了但没有注册进来，就无法找到宿主机，需要按照下面的文档排查原因：
> 
> https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/

就是按照官网提供的allinone的安装方法执行安装
```
python3 run.py --stack fullstack x.x.x.x
之后生成的config-allinone-current.yml文件中的--enable-host-on-vm是没有启用的，处于注释的状态
导致随后的pod里面和host相关的pod只有一个，然后clicm host-list显示没有宿主机，我的意思就是
python3 run.py --enable-host-on-vm --stack fullstack x.x.x.x这样就好了
我为什么要这么说呢，因为我发现
python3 ocboot.py 是可以添加--enable-host-on-vm选项的
```

**Comment by zexi** [comment]
> > @weiwhy 另一个问题，--enable-host-on-vm 应该是可以在虚拟机里面部署计算节点服务，可以看下 default-host-xxx 这个 pod 有没有创建，如果创建了但没有注册进来，就无法找到宿主机，需要按照下面的文档排查原因：
> > https://www.cloudpods.org/zh/docs/function_principle/onpremise/host/troubleshooting/
> 
> 就是按照官网提供的allinone的安装方法执行安装
> 
> ```
> python3 run.py --stack fullstack x.x.x.x
> 之后生成的config-allinone-current.yml文件中的--enable-host-on-vm是没有启用的，处于注释的状态
> 导致随后的pod里面和host相关的pod只有一个，然后clicm host-list显示没有宿主机，我的意思就是
> python3 run.py --enable-host-on-vm --stack fullstack x.x.x.x这样就好了
> 我为什么要这么说呢，因为我发现
> python3 ocboot.py 是可以添加--enable-host-on-vm选项的
> ```

@weiwhy 哦，理解你的意思了，那我们给 run.py 添加一个 --enable-host-on-vm 参数吧。

run.py 目前就是拿来做一个调用 ocboot.py 的封装。

**Comment by zexi** [comment]
https://github.com/yunionio/ocboot/pull/975
@weiwhy 已给 run.py 添加 '--enable-host-on-vm' 参数
