### ISSUE TITLE
[BUG]调整配置报错

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18106]
v3.10.2
阿里云主机调整配置报错，已经是v3.10.2版本的，麻烦看看

![image](https://github.com/yunionio/cloudpods/assets/59357035/a64e387a-36a6-4520-bc72-a5272da8d6dc)
![image](https://github.com/yunionio/cloudpods/assets/59357035/6f38bc28-4d5a-48b2-87b7-8e70d504fcbe)
![image](https://github.com/yunionio/cloudpods/assets/59357035/ee16f26c-805e-434c-a9ba-c4618dedac21)

**Comment by ninghongwu** [comment]
@ioito 请问需要升级修复吗

**Comment by ioito** [comment]
> @ioito 请问需要升级修复吗

是的，合并pr之后，可以自己打个镜像试下，或者根据关联的pr改下代码打个镜像替换

**Comment by ninghongwu** [comment]
@ioito 升级到最新的3.10.5可以了，谢谢
