### ISSUE TITLE
[求助/Help] 裸金属部署安装问题

### ISSUE THREAD

**Issue by 522623905** [yunionio/cloudpods#18128]
参考文档：
https://www.cloudpods.org/zh/docs/function_principle/onpremise/baremetal/principle/

请问：
1、**裸金属注册阶段**时，会通过PXE启动yunios的ramdisk。然后在**部署安装操作系统阶段**时，是直接在这个ramdisk上下载镜像，然后将镜像注入磁盘，再创建分区吗？还是说，在**部署安装操作系统阶段**时，是重新PXE启动，然后加载用户的kernel、initrd，去走类似于kickstart的自动部署安装流程呢？
2、裸金属安装部署时，网络配置是怎么做的呢？是系统安装好后，再ssh进去配置IP吗？还是说在安装阶段时就可有什么方式去做呢？

这块原理上没有理解，可否帮忙解答一下呢？

**Comment by zexi** [comment]
@522623905 
1. 是直接在这个ramdisk上下载镜像，然后将镜像注入磁盘，再创建分区。
2. 网络等配置是分区完成后，找到对应 rootfs 分区，然后挂载起来，修改 /etc 里面的配置。比如 rootfs 在 /dev/sda1 ，然后 yunionos 会把 /dev/sda1 挂到 /tmp/rootfs_dir ，然后 baremetal-agent 服务远程 ssh 修改 /tmp/rootfs_dir 里面的配置

**Comment by 522623905** [comment]
> @522623905
> 
> 1. 是直接在这个ramdisk上下载镜像，然后将镜像注入磁盘，再创建分区。
> 2. 网络等配置是分区完成后，找到对应 rootfs 分区，然后挂载起来，修改 /etc 里面的配置。比如 rootfs 在 /dev/sda1 ，然后 yunionos 会把 /dev/sda1 挂到 /tmp/rootfs_dir ，然后 baremetal-agent 服务远程 ssh 修改 /tmp/rootfs_dir 里面的配置

多谢。我确认下代码实现。
