### ISSUE TITLE
[求助/Help] Host Raid监控失效

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#18135]
一个整列降级，重建中，megacli 输出：
```
Storage

       Virtual Drives
                Virtual drive      : Target Id 0 ,VD name
                Size               : 3.637 TB
                State              : Degraded
                RAID Level         : 5

                Virtual drive      : Target Id 1 ,VD name
                Size               : 118.625 GB
                State              : Optimal
                RAID Level         : 0
```
host_raid.adapter 状态正常，
<img width="1424" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/37df8416-ddc7-4f12-9c7d-fb6242b7e22f">

但是未产生报警。请问该如何进一步排查，谢谢。

**Comment by zexi** [comment]
@fangpsh 这个需要打开 raid plugin ，用下面的命令：

```bash
kubectl edit oc -n onecloud default
```

<img width="758" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/b366fff6-f3d3-4443-b7d2-ffecec15bc0f">

把 enableRaidPlugin 改成 true ，这个插件会用 megacli 获取磁盘状态，但之前我们发现有一定概率会导致部分型号机器 raid 驱动报错，导致系统卡住，所以就默认关闭了。

**Comment by fangpsh** [comment]
补个文档： https://github.com/yunionio/docs/pull/1745
