### ISSUE TITLE
[求助/Help]好像是一个bug，帮忙看一下 from hewenxiang

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/cloudpods#18134]
<img width="730" alt="image" src="https://github.com/yunionio/cloudpods/assets/11387540/88ac0514-556e-41d9-b6c3-522830f06428">
from @hewenxiang

**Comment by ioito** [comment]
ref: https://github.com/yunionio/ansible-telegraf/blob/master/defaults/main.yml

**Comment by swordqiu** [comment]
这个报什么错呢？

**Comment by hewenxiang** [comment]
@swordqiu  与文件名不匹配
