### ISSUE TITLE
[求助/Help]安装完毕，两个节点都是初始化中

### ISSUE THREAD

**Issue by yuyc** [yunionio/cloudpods#18131]
#kubectl logs default-host-95fkz -n onecloud -c host
![image](https://github.com/yunionio/cloudpods/assets/15811147/7ef69c0f-8351-4bd2-b7f6-9ca50e96df61)

**Comment by zexi** [comment]
@yuyc 这个错误看起来是 default-host 这个 pod 访问 k8s 内部的 coredns 都失效了

```bash
kubectl get pods -n kube-system -o wide | grep coredns
```

看下 coredns pod 是否正常？

<img width="884" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/b5e1ee28-24c2-44e1-ae40-56f6eb2736c9">
这个错误还第一次见，这个 host 节点是多网卡的吗？

**Comment by zexi** [comment]
@yuyc 等待你的反馈，另外要看下有没有设置防火墙，selinux 之类的安全策略
