### ISSUE TITLE
创建磁盘快照提示磁盘快照的配额不足！

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#18140]
{
  "class": "BadRequestError",
  "code": 400,
  "details": "ValidateCreateData: driver.ValidateCreateSnapshotData: {\"error\":{\"class\":\"BadRequestError\",\"code\":400,\"data\":{\"fields\":[\"25692aa6-69de-401b-8076-925521e8d30f\"],\"id\":\"Disk %!s(MISSING) snapshot full, cannot take any more\"},\"details\":\"Disk 25692aa6-69de-401b-8076-925521e8d30f snapshot full, cannot take any more\"}}",
  "time": "2023-09-25T13:40:57+08:00"
}
实际磁盘空间还有

**Comment by hoganlxj** [comment]
@zhongyong  这个是是默认磁盘快照数量配额不足，调整配额数量步骤如下
登陆部署cloudpods的机器
climc service-config-edit region2  
修改default_max_manual_snapshot_count值 ，然后重启region
 kubectl rollout restart deployment -n onecloud default-region

**Comment by zexi** [comment]
> @zhongyong 这个是是默认磁盘快照数量配额不足，调整配额数量步骤如下 登陆部署cloudpods的机器 climc service-config-edit region2 修改default_max_manual_snapshot_count值 ，然后重启region kubectl rollout restart deployment -n onecloud default-region

@zhongyong 按照上面方法设置后，是否还有问题？
