### ISSUE TITLE
[BUG]默认的ntp服务器无法更新时区

### ISSUE THREAD

**Issue by yuyc** [yunionio/cloudpods#18149]
**问题描述/What happened**:
默认的ntp服务器配置无法更新时区，需要根据服务器所在时区进行修改。
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
你是如何更新时区的，这个跟cloudpods有什么关联 @yuyc

**Comment by zexi** [comment]
> 默认会把第一个控制节点设置为ntpserver，上有为utc0时区，如果中国采用东八区，那么就会失败，需要手工处理。 另外安装计算节点时候，会把计算节点单独设置成一个ntpserver服务器，应该让其同步第一个控制节点。

<img width="761" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/480e3f73-081f-43a0-8939-53e080109528">

@yuyc 我看了下计算节点的代码，确实有设置 ntp 的逻辑，在没有设置平台 ntp endpoint 的情况下，会默认同步 cn 的时间。
