### ISSUE TITLE
[BUG]  all in one  升级到 3.10.5  纳管 vmware， 创建 虚拟机 磁盘 分配失败

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#18152]
**问题描述/What happened**:

![6d7b9ca3c1b8e4c3d754442ecba52ed](https://github.com/yunionio/cloudpods/assets/48039439/4043938d-3e3e-4446-8102-5c8822a44abf)

{
    "__reason__": {
        "reason": {
            "image_id": "88fb2fd2-9918-475c-8ea4-b066e9e16700",
            "reason": {
                "__reason__": "{\"error\":{\"class\":\"ClientError\",\"code\":499,\"details\":\"Post \\\"https://10.40.175.243:30883/disks/image_cache\\\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\",\"request\":{\"body\":\"{\\\"disk\\\":{\\\"datastore\\\":{\\\"account\\\":\\\"administrator@cloud.local\\\",\\\"host\\\":\\\"10.158.158.12\\\",\\\"password\\\":\\\"/Gxig...47e3-8cbc-89b7bb9791af\\\"}}\",\"headers\":{\"Content-Length\":\"525\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Region-Version\":\"v2\",\"X-Request-Id\":\"e2d7f1-3edb74\",\"X-Task-Id\":\"2022249c-fbf6-4416-885a-cf642e2c2917\",\"X-Task-Notify-Url\":\"https://default-region:30888/tasks/2022249c-fbf6-4416-885a-cf642e2c2917\",\"X-Yunion-Parent-Id\":\"0.0\",\"X-Yunion-Peer-Service-Name\":\"compute_v2\",\"X-Yunion-Remote-Addr\":\"10.40.175.243:30883\",\"X-Yunion-Span-Id\":\"0.0.0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"f8b1c288\"},\"method\":\"POST\",\"url\":\"https://10.40.175.243:30883/disks/image_cache\"}}}",
                "__status__": "ERROR"
            }
        },
        "stage": "OnImageCacheComplete"
    },
    "__stage__": "OnDiskPrepared",
    "__status__": "error",
    "__task_name__": "StorageCacheImageTask"
}

**环境/Environment**:

- OS 
centos 7.9

cloudpods: 3.10.4--->升级 3.10.5

-->

**Comment by ioito** [comment]
可以看下那段时间计算节点10.40.175.243的host pod日志 @sun3book

**Comment by zexi** [comment]
@sun3book @ioito 30883 是 esxi-agent 服务的端口，需要看下 esxi-agent 那个 pod 的状态和日志。

**Comment by sun3book** [comment]
> @sun3book @ioito 30883 是 esxi-agent 服务的端口，需要看下 esxi-agent 那个 pod 的状态和日志。

[error 2023-09-26 07:55:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"1993b22c"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:55:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"bf38368e"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:56:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"1dc3ddd8"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:56:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"fbc0a400"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:57:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"d2ce41c6"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:57:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"bc735243"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:58:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"087c1ac1"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:58:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"c6a5624a"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:59:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"88959ae0"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 07:59:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"06fbc6b3"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:00:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"aa3436d9"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:00:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"945217d2"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:01:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"57f34a3e"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:01:45 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"35f3d822"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:02:15 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"50c0c1e4"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:02:46 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"4b227c15"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:03:16 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"12378dc3"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
[error 2023-09-26 08:03:46 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"ConflictError","code":409,"details":"ValidateUpdateData: {\"error\":{\"class\":\"ConflictError\",\"code\":409,\"data\":{\"fields\":[\"https://10.40.175.206:30883\"],\"id\":\"Conflict manager_uri %!s(MISSING)\"},\"details\":\"Conflict manager_uri https://10.40.175.206:30883\"}}","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.40.175.206\",\"agent_type\":\"esxiagent\",\"manager_uri\":\"https://10.40...405c-85a6-d4d41dc386c2\"}}","headers":{"Content-Length":"244","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"esxiagent","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"09cff367"},"method":"PUT","url":"https://default-region:30888/baremetalagents/baee42a2-f615-41e4-82dd-a54cfc66353f"}}}, retry after 30s...
![image](https://github.com/yunionio/cloudpods/assets/48039439/0df4bbc1-b516-4fe3-9032-02d24523a456)

**Comment by sun3book** [comment]
> @sun3book esxi-agent 启动失败了，你执行一下 climc agent-list 看看

[root@zhcx-cloudpods01 images]#  climc agent-list 
+--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+
|                  ID                  |          Name           |   Access_ip   |         Manager_URI         | Status  | agent_type |             version              |               zone_id                |
+--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+
| 98178d9b-1817-421c-8d95-bb5dd45c7d38 | esxiagent-10.40.175.206 | 10.40.175.206 | https://10.40.175.206:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | 66992e31-fa5e-4b42-87f0-aed2c890eecd |
| fa3ca757-d220-4054-884d-0a9071767558 | esxiagent-10.40.175.254 | 10.40.175.254 | https://10.40.175.254:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | 1308a5d7-eb5d-413f-8d11-f3aad9a14df0 |
| dfeb1dc2-760d-4447-8c8c-b895973615a3 | esxiagent-10.40.175.246 | 10.40.175.246 | https://10.40.175.246:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | c1d4a794-45df-47fa-80a9-d475886e3c21 |
| f87186a1-b32a-4d5d-822c-1db1ca6e6ee1 | esxiagent-10.40.175.241 | 10.40.175.241 | https://10.40.175.241:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | 55de5f36-dc92-481f-85b8-ad627bb32145 |
| 59a46069-810b-4792-848a-e1f20b5a585e | esxiagent-10.40.175.240 | 10.40.175.240 | https://10.40.175.240:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | e11e2175-c24e-46b0-8a98-6bfd7e15fcba |
| baee42a2-f615-41e4-82dd-a54cfc66353f | esxiagent-10.40.175.243 | 10.40.175.243 | https://10.40.175.243:30883 | disable | esxiagent  | release/3.10(3b4258809123080100) | bd03e629-8ef0-405c-85a6-d4d41dc386c2 |
+--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+
***  Total: 6 Pages: 1 Limit: 20 Offset: 0 Page: 1  ***

状态全部变成了 disable

**Comment by wanyaoqi** [comment]
> > @sun3book esxi-agent 启动失败了，你执行一下 climc agent-list 看看
> 
> [root@zhcx-cloudpods01 images]# climc agent-list +--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+ | ID | Name | Access_ip | Manager_URI | Status | agent_type | version | zone_id | +--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+ | 98178d9b-1817-421c-8d95-bb5dd45c7d38 | esxiagent-10.40.175.206 | 10.40.175.206 | https://10.40.175.206:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | 66992e31-fa5e-4b42-87f0-aed2c890eecd | | fa3ca757-d220-4054-884d-0a9071767558 | esxiagent-10.40.175.254 | 10.40.175.254 | https://10.40.175.254:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | 1308a5d7-eb5d-413f-8d11-f3aad9a14df0 | | dfeb1dc2-760d-4447-8c8c-b895973615a3 | esxiagent-10.40.175.246 | 10.40.175.246 | https://10.40.175.246:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | c1d4a794-45df-47fa-80a9-d475886e3c21 | | f87186a1-b32a-4d5d-822c-1db1ca6e6ee1 | esxiagent-10.40.175.241 | 10.40.175.241 | https://10.40.175.241:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | 55de5f36-dc92-481f-85b8-ad627bb32145 | | 59a46069-810b-4792-848a-e1f20b5a585e | esxiagent-10.40.175.240 | 10.40.175.240 | https://10.40.175.240:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | e11e2175-c24e-46b0-8a98-6bfd7e15fcba | | baee42a2-f615-41e4-82dd-a54cfc66353f | esxiagent-10.40.175.243 | 10.40.175.243 | https://10.40.175.243:30883 | disable | esxiagent | release/3.10(3b4258809123080100) | bd03e629-8ef0-405c-85a6-d4d41dc386c2 | +--------------------------------------+-------------------------+---------------+-----------------------------+---------+------------+----------------------------------+--------------------------------------+ *** Total: 6 Pages: 1 Limit: 20 Offset: 0 Page: 1 ***
> 
> 状态全部变成了 disable

结合这两个日志看，注册的 esxi-agent zone id是 bd03e629-8ef0-405c-85a6-d4d41dc386c2。但是这个地址是被注册过的 zone 66992e31-fa5e-4b42-87f0-aed2c890eecd

**Comment by wanyaoqi** [comment]
@sun3book 这个disable 状态可以忽略

**Comment by sun3book** [comment]
> @sun3book 这个disable 状态可以忽略

这种情况是不是升级导致的。如何修复呢？

**Comment by wanyaoqi** [comment]
> > @sun3book 这个disable 状态可以忽略
> 
> 这种情况是不是升级导致的。如何修复呢？

问题是你的 esxi-agent 注册过很多次，配置的不同的 zone 。可能是这次升级重启了 esxi-agent 触发的。你可以使用 climc agent-delete 把多余的 agent先清理了

**Comment by sun3book** [comment]
> climc agent-delete

zone 要不要也删除多余的

**Comment by sun3book** [comment]
> > > @sun3book 这个disable 状态可以忽略
> > 
> > 
> > 这种情况是不是升级导致的。如何修复呢？
> 
> @sun3book 问题是你的 esxi-agent 注册过很多次，配置的不同的 zone 。可能是这次升级重启了 esxi-agent 触发的。你可以使用 climc agent-delete 把多余的 agent先清理了

不太看的出来那个是多余的。 没有对应zone的信息

**Comment by sun3book** [comment]
我从zone id 反查一下

**Comment by wanyaoqi** [comment]
@sun3book 可以使用 climc agent-list --details

**Comment by sun3book** [comment]
> @sun3book 可以使用 climc agent-list --details

![image](https://github.com/yunionio/cloudpods/assets/48039439/b1d60aaa-20fb-47df-9b3e-8cf693e557f3)
![image](https://github.com/yunionio/cloudpods/assets/48039439/0133e346-6abb-4a81-820f-565ab02a2bab)
kong控制台已经删掉了，只保留了默认的 zone0,  命令查出来还有，如何处理

**Comment by sun3book** [comment]
> @sun3book 可以使用 climc agent-list --details
删除掉多余的 zone 一切恢复正常
