### ISSUE TITLE
[Feature] 能否支持 ubuntu20.04 作为宿主机

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#18160]
**What would you like to be added**:
目前只能在 centos7 和 debian 11 上安装云联系统。能不能支持 ubuntu20.04

**Comment by ioito** [comment]
#17543 即将支持

**Comment by zexi** [comment]
@flowlsj ubuntu 22.04 做为宿主机的正在测试中，还有些小问题，解决后就可以支持了

**Comment by flowlsj** [comment]
@zexi 请问有大概的时间节点吗？

**Comment by zexi** [comment]
> @zexi 请问有大概的时间节点吗？

估计要1个月左右，下次发布版本的时候

**Comment by zexi** [comment]
> > @zexi 请问有大概的时间节点吗？
> 
> 估计要1个月左右，下次发布版本的时候 @flowlsj

@flowlsj 我说的应该有歧义，我说的发版本是大版本 v3.11 的时候，不是目前的 v3.10.6

**Comment by zexi** [comment]
该问题和 https://github.com/yunionio/cloudpods/issues/18313 重复了，关闭此问题。
