### ISSUE TITLE
[求助/Help] 定位后端代码找不到/parameters/LIST_PhysicalmachineList

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#18178]
api/v1/parameters/LIST_PhysicalmachineList
这个定位代码找了2天也没找到。。求哪个大佬指点下 谢谢

**Comment by zexi** [comment]
@vincentiss 这个是在哪里发送的请求？前端代码吗？

**Comment by swordqiu** [comment]
这个报错没有关系的，是获取列表的前端配置信息，没有更改，则没有这个配置信息

**Comment by ioito** [comment]
@vincentiss https://github.com/yunionio/cloudpods/blob/master/pkg/yunionconf/models/parameters.go
