### ISSUE TITLE
[求助/Help]rook+ceph后端存储，启动虚拟机提示GetStoragesByPath: rbd:HWCloud: NotFoundError"

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18197]
1、启动虚拟机提示：
`
{
    "__reason__": "Async start server failed: generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError",
    "__stage__": "OnStartComplete",
    "__status__": "error"
}
`

2、操作一台在node1的虚拟机迁移到node5(刚才无法启动虚拟机电脑计算节点)，也是迁移失败，日志：
`
"{\"error\":{\"code\":400,\"details\":\"Error #01: genericScheduler.Schedule: No resource are avaliable that match all of the following predicates: filter by host_migrate(-1), session_id=\\\"1696333777352\\\"\\n\",\"request\":{\"body\":\"{\\\"backup\\\":false,\\\"best_effort\\\":false,\\\"change_config\\\":false,\\\"count\\\":1,\\\"cpu_desc\\\":\\\"Intel(R) Xeon(R) CPU...ount\\\":2,\\\"vmem_size\\\":2048}\",\"headers\":{\"Content-Length\":\"1769\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Request-Id\":\"7e1fb8-cb011e\",\"X-Yunion-Lang\":\"zh-CN\",\"X-Yunion-Parent-Id\":\"0.0\",\"X-Yunion-Peer-Service-Name\":\"compute_v2\",\"X-Yunion-Remote-Addr\":\"default-scheduler:30887\",\"X-Yunion-Span-Id\":\"0.0.0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"019a5f40\"},\"method\":\"POST\",\"url\":\"https://default-scheduler:30887/scheduler\"}}}"
`

4、node5(刚才无法启动虚拟机电脑计算节点)的日志
`
[info 2023-10-03 11:27:18 appsrv.(*Application).ServeHTTP(appsrv.go:286)] jciGOzHLSUJocIUoFvKV0aQS_bw= 200 61275c-b14d14-798993 POST /servers/c87b367c-3c68-48d9-89ee-7fbf00ebb100/start (172.16.1.7:58984:compute_v2) 1.51ms
[info 2023-10-03 11:27:18 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:548)] Use vnc port 4
[error 2023-10-03 11:27:18 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:570)] Start VM failed 测试Centos7(c87b367c-3c68-48d9-89ee-7fbf00ebb100): generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError
[info 2023-10-03 11:27:19 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:548)] Use vnc port 5
[error 2023-10-03 11:27:19 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:570)] Start VM failed 测试Centos7(c87b367c-3c68-48d9-89ee-7fbf00ebb100): generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError
[info 2023-10-03 11:27:21 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:548)] Use vnc port 6
[error 2023-10-03 11:27:21 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:570)] Start VM failed 测试Centos7(c87b367c-3c68-48d9-89ee-7fbf00ebb100): generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError
[error 2023-10-03 11:27:25 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:583)] Async start server 测试Centos7(c87b367c-3c68-48d9-89ee-7fbf00ebb100) failed: generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError!!!
[info 2023-10-03 11:27:25 modules.TaskComplete(task.go:34)] Sync task d5c878a6-063e-434a-8a49-ec5a6d109958 complete succ
[error 2023-10-03 11:27:25 guestman.(*guestStartTask).Run(qemu-kvm.go:1537)] failed asyncScriptStart c87b367c-3c68-48d9-89ee-7fbf00ebb100: generateDiskSetupScripts: GetDiskByPath(rbd:HWCloud/a5b2cb54-3b2b-490f-882f-e9a5c28e083d): GetStoragesByPath: rbd:HWCloud: NotFoundError
`

5、Ceph的磁盘：
<img width="553" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/24ef427e-5b37-45ef-80b3-37597829fe67">

6、Cloudpods版本
v3.10.5
rook+ceph：https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/

**Comment by chenjacken** [comment]
host node5节点pod完整日志：
[host_node5.log](https://github.com/yunionio/cloudpods/files/12793153/host_node5.log)

**Comment by chenjacken** [comment]
> 看到有下面报错，感觉是缺少 prettytable 这个python包，导致调用 ceph 客户端失败了。
> 
> 可以在宿主机执行 ceph -s，看是否有缺少包的报错，把缺少的python包安装一下。
> 
> [error 2023-10-03 11:43:43 hostinfo.(*SHostInfo).PutHostOnline(hostinfo.go:1541)] Host sys error: map[isolated_devices:[{isolated_devices GPU 05:00.0 use kernel driver ast, skip it 2023-10-03 11:43:42.994314942 +0000 UTC m=+4.704237455}] storages:[{storages 5a312f0f-2ffb-4f04-80bb-226e41fd45e0 HWCloud-ceph check storage accessible failed: output: stderr "Traceback (most recent call last):\n File "/usr/bin/ceph", line 136, in \n from ceph_daemon import admin_socket, DaemonWatcher, Termsize\n File "/usr/lib/python2.7/site-packages/ceph_daemon.py", line 21, in \n from prettytable import PrettyTable, HEADER\nImportError: No module named prettytable\n": exit status 1 2023-10-03 11:43:43.170621912 +0000 UTC m=+4.880544456}]]

[root@node5 ~]# ceph -s
Traceback (most recent call last):
  File "/usr/bin/ceph", line 136, in <module>
    from ceph_daemon import admin_socket, DaemonWatcher, Termsize
  File "/usr/lib/python2.7/site-packages/ceph_daemon.py", line 21, in <module>
    from prettytable import PrettyTable, HEADER
ImportError: No module named prettytable
[root@node5 ~]# cat /etc/os-release 
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"

[root@node5 ~]# 
+++++++
是呢，是缺少了这个包。是因为麒麟的系统，之前的步骤导致出错吗？centos都没问题。

**Comment by swordqiu** [comment]
收到，请按这个思路排查。

我们也看下是不是麒麟的安装步骤把这个包省略了。

**Comment by swordqiu** [comment]
@zhasm 验证一下是不是麒麟的安装步骤会把 prettytable 忽略安装

**Comment by chenjacken** [comment]
> 收到，请按这个思路排查。
> 
> 我们也看下是不是麒麟的安装步骤把这个包省略了。

安装上prettytable模块，所在节点的虚拟机能启动成功了。
host重启过程看到有一个error信息：
`[error 2023-10-03 14:43:02 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest c87b367c-3c68-48d9-89ee-7fbf00ebb100 start monitor failed, can't get qmp monitor port or monitor path`
