### ISSUE TITLE
[求助/Help]创建虚拟机磁盘分配失败

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18202]
1，cloudpods版本
v3.10.5
rook+ceph

2，界面显示：
`{
    "__reason__": {
        "reason": {
            "__reason__": {
                "reason": "{\"__reason__\":{\"reason\":\"{\\\"__reason__\\\":{\\\"reason\\\":{\\\"image_id\\\":\\\"fc1b1846-ddfc-4476-829d-4364d41ca367\\\",\\\"reason\\\":{\\\"__reason__\\\":\\\"POST https://172.16.1.8:8885/disks/image_cache: {\\\\\\\"error\\\\\\\":{\\\\\\\"class\\\\\\\":\\\\\\\"NotFoundError\\\\\\\",\\\\\\\"code\\\\\\\":404,\\\\\\\"details\\\\\\\":\\\\\\\"Storagecache 77a880d6-2d53-48b4-80f8-6e66e5c609b7 not found\\\\\\\",\\\\\\\"request\\\\\\\":{\\\\\\\"body\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"disk\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"format\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"qcow2\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"image\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"fc1b1846-ddfc-4476-829d-4364d41ca367\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"image_id\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"fc1b1846-ddfc-4...48b4-80f8-6e66e5c609b7\\\\\\\\\\\\\\\"}}\\\\\\\",\\\\\\\"headers\\\\\\\":{\\\\\\\"Content-Length\\\\\\\":\\\\\\\"418\\\\\\\",\\\\\\\"Content-Type\\\\\\\":\\\\\\\"application/json\\\\\\\",\\\\\\\"User-Agent\\\\\\\":\\\\\\\"yunioncloud-go/201708\\\\\\\",\\\\\\\"X-Auth-Token\\\\\\\":\\\\\\\"*\\\\\\\",\\\\\\\"X-Region-Version\\\\\\\":\\\\\\\"v2\\\\\\\",\\\\\\\"X-Request-Id\\\\\\\":\\\\\\\"214d46-8cb7d5\\\\\\\",\\\\\\\"X-Task-Id\\\\\\\":\\\\\\\"2bbe7bc7-776b-410e-8f9b-167efbd3dcad\\\\\\\",\\\\\\\"X-Task-Notify-Url\\\\\\\":\\\\\\\"https://default-region:30888/tasks/2bbe7bc7-776b-410e-8f9b-167efbd3dcad\\\\\\\",\\\\\\\"X-Yunion-Parent-Id\\\\\\\":\\\\\\\"0.0\\\\\\\",\\\\\\\"X-Yunion-Peer-Service-Name\\\\\\\":\\\\\\\"compute_v2\\\\\\\",\\\\\\\"X-Yunion-Remote-Addr\\\\\\\":\\\\\\\"172.16.1.8:8885\\\\\\\",\\\\\\\"X-Yunion-Span-Id\\\\\\\":\\\\\\\"0.0.0\\\\\\\",\\\\\\\"X-Yunion-Span-Name\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"X-Yunion-Strace-Debug\\\\\\\":\\\\\\\"true\\\\\\\",\\\\\\\"X-Yunion-Strace-Id\\\\\\\":\\\\\\\"7da058d4\\\\\\\"},\\\\\\\"method\\\\\\\":\\\\\\\"POST\\\\\\\",\\\\\\\"url\\\\\\\":\\\\\\\"https://172.16.1.8:8885/disks/image_cache\\\\\\\"}}}\\\",\\\"__status__\\\":\\\"ERROR\\\"}},\\\"stage\\\":\\\"OnImageCacheComplete\\\"},\\\"__stage__\\\":\\\"OnStorageCacheImageComplete\\\",\\\"__status__\\\":\\\"error\\\",\\\"__task_name__\\\":\\\"StorageCacheImageTask\\\"}\",\"stage\":\"OnStorageCacheImageComplete\"},\"__stage__\":\"on_kvm_disk_prepared\",\"__status__\":\"error\",\"__task_name__\":\"DiskCreateTask\"}",
                "stage": "on_kvm_disk_prepared"
            },
            "__stage__": "on_disk_prepared",
            "__status__": "error",
            "__task_name__": "KVMGuestCreateDiskTask"
        },
        "stage": "on_disk_prepared"
    },
    "__stage__": "OnDiskPrepared",
    "__status__": "error",
    "__task_name__": "GuestCreateDiskTask"
}`

3，所在节点log:
[host.log](https://github.com/yunionio/cloudpods/files/12811184/host.log)

**Comment by swordqiu** [comment]
@chenjacken 请提供  172.16.1.8 这台宿主机的 host.log

**Comment by chenjacken** [comment]
> @chenjacken 请提供 172.16.1.8 这台宿主机的 host.log

@swordqiu 
[host_172.16.1.8.log](https://github.com/yunionio/cloudpods/files/12811257/host_172.16.1.8.log)

**Comment by chenjacken** [comment]
`[error 2023-10-05 01:17:54 httperrors.HTTPError(httperrors.go:110)] Send error Storagecache 77a880d6-2d53-48b4-80f8-6e66e5c609b7 not found
[info 2023-10-05 01:17:54 appsrv.(*Application).ServeHTTP(appsrv.go:286)] 5BWX32sB5eKN5WDLxFgwC28vpxk= 404 ac7cdd-38ebf9-139ba7 POST /disks/image_cache (172.16.1.7:8751:compute_v2) 0.40ms
[error 2023-10-05 01:19:07 httperrors.HTTPError(httperrors.go:110)] Send error Storagecache 77a880d6-2d53-48b4-80f8-6e66e5c609b7 not found
[info 2023-10-05 01:19:07 appsrv.(*Application).ServeHTTP(appsrv.go:286)] 5BWX32sB5eKN5WDLxFgwC28vpxk= 404 5fd43c-5ae828-4e3af9 POST /disks/image_cache (172.16.1.7:14220:compute_v2) 0.44ms`


对应改镜像的缓存，如何排查缓存失败的原因？：
<img width="1035" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/a79879c5-a6d2-4669-b30a-c961fa385453">

**Comment by chenjacken** [comment]
Connecting to root(root)@172.16.1.9  0.1
Last login: Thu Oct  5 06:33:55 2023 from 172.16.1.30
[root@node2 ~]# ceph -s
no monitors specified to connect to.
Error connecting to cluster: ObjectNotFound
[root@node2 ~]# 


Connecting to root(root)@172.16.1.8  0.1
Last login: Thu Oct  5 06:33:37 2023 from 172.16.1.30
[root@node1 ~]# ceph -s
Error initializing cluster client: Error('error calling conf_read_file: error code 22',)
[root@node1 ~]# 

不一样的信息

**Comment by chenjacken** [comment]
奇怪了，没操作过这台服务器

**Comment by chenjacken** [comment]
那我重新安装该节点解决哈
