### ISSUE TITLE
[求助/Help]VPC模式下，虚拟机无法获取DHCP地址

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18203]
1，版本
v3.10.5

2，日志：
`[root@master01 ~]# kubectl logs default-vpcagent-7cd789bc4c-xfbqd -n onecloud | grep error
[error 2023-10-04 22:32:42 apihelper.GetModels(reflect.go:155)] vpcs: list failed with updated_at.gt('0001-01-01 00:00:00.000000001 +0000 UTC'): {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:32:42 apihelper.(*APIHelper).run(apihelper.go:140)] doSync error: SyncModelSets: syncModelSets: GetModels: vpcs list failed with params: admin=true&cloud_env=onpremise&details=false&filter.0=updated_at.ge%28%270001-01-01+00%3A00%3A00%27%29&filter.1=manager_id.isnullorempty%28%29&filter.2=external_id.isnullorempty%28%29&limit=1024&offset=0&order=asc&order_by.0=updated_at&scope=system&show_emulated=false&system=true: {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:32:53 apihelper.GetModels(reflect.go:155)] vpcs: list failed with updated_at.gt('0001-01-01 00:00:00.000000001 +0000 UTC'): {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:32:53 apihelper.(*APIHelper).run(apihelper.go:140)] doSync error: SyncModelSets: syncModelSets: GetModels: vpcs list failed with params: admin=true&cloud_env=onpremise&details=false&filter.0=updated_at.ge%28%270001-01-01+00%3A00%3A00%27%29&filter.1=manager_id.isnullorempty%28%29&filter.2=external_id.isnullorempty%28%29&limit=1024&offset=0&order=asc&order_by.0=updated_at&scope=system&show_emulated=false&system=true: {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:04 apihelper.GetModels(reflect.go:155)] vpcs: list failed with updated_at.gt('0001-01-01 00:00:00.000000001 +0000 UTC'): {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:04 apihelper.(*APIHelper).run(apihelper.go:140)] doSync error: SyncModelSets: syncModelSets: GetModels: vpcs list failed with params: admin=true&cloud_env=onpremise&details=false&filter.0=updated_at.ge%28%270001-01-01+00%3A00%3A00%27%29&filter.1=manager_id.isnullorempty%28%29&filter.2=external_id.isnullorempty%28%29&limit=1024&offset=0&order=asc&order_by.0=updated_at&scope=system&show_emulated=false&system=true: {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:14 apihelper.GetModels(reflect.go:155)] vpcs: list failed with updated_at.gt('0001-01-01 00:00:00.000000001 +0000 UTC'): {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:14 apihelper.(*APIHelper).run(apihelper.go:140)] doSync error: SyncModelSets: syncModelSets: GetModels: vpcs list failed with params: admin=true&cloud_env=onpremise&details=false&filter.0=updated_at.ge%28%270001-01-01+00%3A00%3A00%27%29&filter.1=manager_id.isnullorempty%28%29&filter.2=external_id.isnullorempty%28%29&limit=1024&offset=0&order=asc&order_by.0=updated_at&scope=system&show_emulated=false&system=true: {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:25 apihelper.GetModels(reflect.go:155)] vpcs: list failed with updated_at.gt('0001-01-01 00:00:00.000000001 +0000 UTC'): {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 22:33:25 apihelper.(*APIHelper).run(apihelper.go:140)] doSync error: SyncModelSets: syncModelSets: GetModels: vpcs list failed with params: admin=true&cloud_env=onpremise&details=false&filter.0=updated_at.ge%28%270001-01-01+00%3A00%3A00%27%29&filter.1=manager_id.isnullorempty%28%29&filter.2=external_id.isnullorempty%28%29&limit=1024&offset=0&order=asc&order_by.0=updated_at&scope=system&show_emulated=false&system=true: {"error":{"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}
[error 2023-10-04 23:35:43 procutils.WaitZombieLoop(zombie_others.go:68)] read /proc/2260/stat: open /proc/2260/stat: no such file or directory
[error 2023-10-04 23:50:42 procutils.WaitZombieLoop(zombie_others.go:68)] read /proc/2947/stat: open /proc/2947/stat: no such file or directory`

3，截图：
<img width="610" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/4e32c286-5006-4b8f-9291-d2a329302c90">

<img width="991" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/de2e0cff-92fb-488d-9923-eee2c5364aa6">

**Comment by zexi** [comment]
@chenjacken 

应该是这个地方导致的

> {"class":"ServiceAbnormal","code":499,"data":{"fields":["compute"],"id":"%s service is abnormal, please check service status"},"details":"compute service is abnormal, please check service status"}}

vpcagent 连接 default-region-xxx 这个服务失败了，需要看下 default-region 相关的 pod 的状态：

```bash
$ kubectl get pods -n onecloud -o wide | grep default-region | grep -v dns
```

如果状态是 Running 的话，还要实际看下这个 pod 的日志

**Comment by zexi** [comment]
@chenjacken 我看 region 日志里面有访问 `dial tcp 172.16.1.11:8885: connect: connection refused` 链接拒绝的日志，是不是网络有问题？这个是从 region pod 所在节点访问 172.16.1.11 这个计算节点的请求。
<img width="781" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/6285b090-850f-47a8-bdbb-d246687fd16c">

**Comment by chenjacken** [comment]
> 172.16.1.11

这虚拟机DHCP不能获取IP的问题还在，我晚一点继续看看，排查下问题。

**Comment by chenjacken** [comment]
> @chenjacken 我看 region 日志里面有访问 `dial tcp 172.16.1.11:8885: connect: connection refused` 链接拒绝的日志，是不是网络有问题？这个是从 region pod 所在节点访问 172.16.1.11 这个计算节点的请求。 <img alt="image" width="781" src="https://user-images.githubusercontent.com/10767027/273226343-6285b090-850f-47a8-bdbb-d246687fd16c.png">


`[root@master01 ~]# kubectl get pods -n onecloud -o wide | grep default-region | grep -v dns
default-region-5dc486685c-qrx62                      1/1     Running       2          4d22h   10.40.241.137   master01               <none>           <none>
[root@master01 ~]# curl -k https://172.16.1.11:8885
{"class":"NotFoundError","code":404,"details":"Handler not found","time":"2023-10-11T15:42:31Z"}
[root@master01 ~]# 
[root@master01 ~]# ping 172.16.1.11
PING 172.16.1.11 (172.16.1.11) 56(84) bytes of data.
64 bytes from 172.16.1.11: icmp_seq=1 ttl=64 time=0.185 ms
64 bytes from 172.16.1.11: icmp_seq=2 ttl=64 time=0.123 ms
64 bytes from 172.16.1.11: icmp_seq=3 ttl=64 time=0.131 ms
64 bytes from 172.16.1.11: icmp_seq=4 ttl=64 time=0.128 ms
64 bytes from 172.16.1.11: icmp_seq=5 ttl=64 time=0.151 ms
^C
--- 172.16.1.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 0.123/0.143/0.185/0.022 ms`

**Comment by chenjacken** [comment]
[root@master01 ~]# kubectl exec -ti -n onecloud $(kubectl get pods -n onecloud | grep default-region | awk '{print $1}') /bin/bash

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "default-region-dns-fxcrp": executable file not found in $PATH: unknown
command terminated with exit code 126

**Comment by chenjacken** [comment]
```
[root@master01 ~]# kubectl exec -ti -n onecloud default-region-5dc486685c-qrx62 -- sh
/ # curl -k https://172.16.1.11:8885
{"class":"NotFoundError","code":404,"details":"Handler not found","time":"2023-10-11T16:06:52Z"}/ # 
/ # ping 172.16.1.11
PING 172.16.1.11 (172.16.1.11): 56 data bytes
64 bytes from 172.16.1.11: seq=0 ttl=63 time=0.243 ms
64 bytes from 172.16.1.11: seq=1 ttl=63 time=0.202 ms
64 bytes from 172.16.1.11: seq=2 ttl=63 time=0.160 ms
64 bytes from 172.16.1.11: seq=3 ttl=63 time=0.192 ms
64 bytes from 172.16.1.11: seq=4 ttl=63 time=0.220 ms
^C
--- 172.16.1.11 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.160/0.203/0.243 ms
/ # 
```

default-region内访问是通的

**Comment by zexi** [comment]
> ```
> [root@master01 ~]# kubectl exec -ti -n onecloud default-region-5dc486685c-qrx62 -- sh
> / # curl -k https://172.16.1.11:8885
> {"class":"NotFoundError","code":404,"details":"Handler not found","time":"2023-10-11T16:06:52Z"}/ # 
> / # ping 172.16.1.11
> PING 172.16.1.11 (172.16.1.11): 56 data bytes
> 64 bytes from 172.16.1.11: seq=0 ttl=63 time=0.243 ms
> 64 bytes from 172.16.1.11: seq=1 ttl=63 time=0.202 ms
> 64 bytes from 172.16.1.11: seq=2 ttl=63 time=0.160 ms
> 64 bytes from 172.16.1.11: seq=3 ttl=63 time=0.192 ms
> 64 bytes from 172.16.1.11: seq=4 ttl=63 time=0.220 ms
> ^C
> --- 172.16.1.11 ping statistics ---
> 5 packets transmitted, 5 packets received, 0% packet loss
> round-trip min/avg/max = 0.160/0.203/0.243 ms
> / # 
> ```
> 
> default-region内访问是通的

@chenjacken 试下访问 172.16.1.11:8885 加端口是否能通？

**Comment by chenjacken** [comment]
> > ```
> > [root@master01 ~]# kubectl exec -ti -n onecloud default-region-5dc486685c-qrx62 -- sh
> > / # curl -k https://172.16.1.11:8885
> > {"class":"NotFoundError","code":404,"details":"Handler not found","time":"2023-10-11T16:06:52Z"}/ # 
> > / # ping 172.16.1.11
> > PING 172.16.1.11 (172.16.1.11): 56 data bytes
> > 64 bytes from 172.16.1.11: seq=0 ttl=63 time=0.243 ms
> > 64 bytes from 172.16.1.11: seq=1 ttl=63 time=0.202 ms
> > 64 bytes from 172.16.1.11: seq=2 ttl=63 time=0.160 ms
> > 64 bytes from 172.16.1.11: seq=3 ttl=63 time=0.192 ms
> > 64 bytes from 172.16.1.11: seq=4 ttl=63 time=0.220 ms
> > ^C
> > --- 172.16.1.11 ping statistics ---
> > 5 packets transmitted, 5 packets received, 0% packet loss
> > round-trip min/avg/max = 0.160/0.203/0.243 ms
> > / # 
> > ```
> > 
> > 
> > default-region内访问是通的
> 
> @chenjacken 试下访问 172.16.1.11:8885 加端口是否能通？

谢谢。
这个环境已经清理了，没有继续跟踪这个问题。
