### ISSUE TITLE
[BUG]容器云新建定时任务前端报错

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#18215]
**问题描述/What happened**:
容器云新建定时任务前端报错
**环境/Environment**:
v3.10.4

![image](https://github.com/yunionio/cloudpods/assets/29140975/a213cfa5-c9cc-41d6-a444-a0df2e3d8faa)
![image](https://github.com/yunionio/cloudpods/assets/29140975/20200993-3bf4-475a-80eb-5cf4d3460c91)

**Comment by zexi** [comment]
@hewenxiang 感谢反馈，我们处理下 /keep-state
