### ISSUE TITLE
[求助/Help]根分区块满了可以清除对应的日志吗

### ISSUE THREAD

**Issue by xiaoluoge11** [yunionio/cloudpods#18213]
我当前使用的版本是cloudpods3.8.8  根分区还剩2.6G,pod被驱除。

4.9G	keystone
15G	kubeserver
1.8G	monitor
1016K	mysql
0	mysql.sock
721M	notify
212K	performance_schema
0	test
2.4M	yunionansible
5.0G	yunioncloud
18M	yunioncloudevent
20M	yunioncloudid
1.5M	yunioncloudnet
2.0M	yunioncloudproxy
2.8M	yunionconf
13G	yunionlogger

最大文件是这几个库，请问这个日志库可以清楚吗

**Comment by zexi** [comment]
@xiaoluoge11 可以先清理掉 yunionlogger 这个日志库，这里面记录的是操作日志，清理完后建议升级到最新的 v3.9.5，这个版本对 kubeserver 和操作日志的大小做了优化，不会记录非必要的日志。
