### ISSUE TITLE
[Docs] All in One 融合云安装

### ISSUE THREAD

**Issue by hu0215** [yunionio/cloudpods#18225]
我所用的uos1060d+ocboot3.6服务器是arm64架构，报错如下
TASK [common : install packages via loop] **************************************
ok: [192.168.10.213] => (item=apt-transport-https)
ok: [192.168.10.213] => (item=bash-completion)
ok: [192.168.10.213] => (item=bridge-utils)
ok: [192.168.10.213] => (item=ca-certificates)
ok: [192.168.10.213] => (item=ceph-common)
ok: [192.168.10.213] => (item=chntpw)
ok: [192.168.10.213] => (item=conntrack)
ok: [192.168.10.213] => (item=conntrackd)
ok: [192.168.10.213] => (item=curl)
ok: [192.168.10.213] => (item=dkms)
failed: [192.168.10.213] (item=docker-ce) => {"ansible_loop_var": "item", "changed": false, "item": "docker-ce", "msg": "No package matching 'docker-ce' is available"}
ok: [192.168.10.213] => (item=git)
ok: [192.168.10.213] => (item=glusterfs-common)
ok: [192.168.10.213] => (item=gnupg-agent)
ok: [192.168.10.213] => (item=gnupg2)
ok: [192.168.10.213] => (item=ipset)
ok: [192.168.10.213] => (item=ipvsadm)
ok: [192.168.10.213] => (item=jq)
failed: [192.168.10.213] (item=kubeadm=1.15.8-00) => {"ansible_loop_var": "item", "changed": false, "item": "kubeadm=1.15.8-00", "msg": "No package matching 'kubeadm' is available"}
failed: [192.168.10.213] (item=kubectl=1.15.8-00) => {"ansible_loop_var": "item", "changed": false, "item": "kubectl=1.15.8-00", "msg": "No package matching 'kubectl' is available"}
failed: [192.168.10.213] (item=kubelet=1.15.8-00) => {"ansible_loop_var": "item", "changed": false, "item": "kubelet=1.15.8-00", "msg": "No package matching 'kubelet' is available"}
ok: [192.168.10.213] => (item=libusb-1.0-0)
ok: [192.168.10.213] => (item=libusbredirparser1)
ok: [192.168.10.213] => (item=librbd1)
ok: [192.168.10.213] => (item=libspice-server1)
ok: [192.168.10.213] => (item=ntp)
ok: [192.168.10.213] => (item=python-pymysql)
ok: [192.168.10.213] => (item=python-selinux)
ok: [192.168.10.213] => (item=python-yaml)
ok: [192.168.10.213] => (item=python3-pip)
ok: [192.168.10.213] => (item=software-properties-common)
ok: [192.168.10.213] => (item=wget)
ok: [192.168.10.213] => (item=ovmf)
ok: [192.168.10.213] => (item=openvswitch-switch)
failed: [192.168.10.213] (item=yunion-climc) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-climc", "msg": "No package matching 'yunion-climc' is available"}
failed: [192.168.10.213] (item=yunion-executor) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-executor", "msg": "No package matching 'yunion-executor' is available"}
failed: [192.168.10.213] (item=yunion-ocadm) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-ocadm", "msg": "No package matching 'yunion-ocadm' is available"}
failed: [192.168.10.213] (item=yunion-qemu-2.12.1) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-qemu-2.12.1", "msg": "No package matching 'yunion-qemu-2.12.1' is available"}
failed: [192.168.10.213] (item=yunion-fetcherfs) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-fetcherfs", "msg": "No package matching 'yunion-fetcherfs' is available"}

docker和k8s我还可以自己安装，，注释掉对应检测，但yunion这个怎么解决，，对应服务器update的报错如下
错误:7 [https://iso.yunion.cn/uos/buster/arm64/3.6](javascript:;) ./ Packages
404 Not Found [IP: 47.75.19.130 443]
忽略:8 [https://iso.yunion.cn/uos/buster/arm64/3.6](javascript:;) ./ Translation-zh
忽略:9 [https://iso.yunion.cn/uos/buster/arm64/3.6](javascript:;) ./ Translation-zh_CN
忽略:10 [https://iso.yunion.cn/uos/buster/arm64/3.6](javascript:;) ./ Translation-en

现在是其他安装好了，，就是yunion这儿卡住了
TASK [common : Enable yunion systemd services] *********************************
failed: [192.168.10.213] (item=yunion-executor) => {"ansible_loop_var": "item", "changed": false, "item": "yunion-executor", "msg": "Could not find the requested service yunion-executor: host"}

**Comment by zhasm** [comment]
@hu0215 3.6 是好几年前的历史版本了，许多包已经过时，repo 也不再维护。
如果没有特殊需求，建议使用最新的稳定版：`v3.10.5`.

**Comment by hu0215** [comment]
@zhasm 但是uos arm架构的支持我看了下好像3.10的不行，，我应该用的3.7的，，是写错了

**Comment by hu0215** [comment]
> @hu02153.6 是好几年前的历史版本了，很多包已经过时，repo 也不再维护。 如果没有特殊需求，建议使用最新的稳定版本：`v3.10.5`.

不过arm架构的支持我看了下好像3.10的不行，，我应该用3.7的，，是写错了

**Comment by zhasm** [comment]
@hu0215 是否依然有问题？如有，请重开issue~
