### ISSUE TITLE
[求助/Help]看错主机，误在控制节点操作rm -fr /etc/openvswitch/*，如何恢复下面的配置文件？

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18221]
很不幸，把主机看错了，直接在控制节点是宿主机上操作了：rm -fr /etc/openvswitch/*
ls   /etc/openvswitch发现目录下的文件已经被删除。还可以通过如何操作补救吗？default.conf和system-id.conf可手工编辑回去，但是conf.db文件如何恢复？
谢谢！

**Comment by chenjacken** [comment]
恢复了default.conf和system-id.conf文件
systemctl start  openvswitch

然后reboot，控制节点起来后，貌似恢复了。

**Comment by swordqiu** [comment]
@chenjacken 

对的，只需要保留 system-id.conf即可恢复一个节点的ovs

**Comment by chenjacken** [comment]
> @chenjacken
> 
> 对的，只需要保留 system-id.conf即可恢复一个节点的ovs

手动创建了这个system-id.conf文件，会恢复回来。谢谢。
