### ISSUE TITLE
[BUG] v3.10.6 格式化磁盘，挂载分区失败

### ISSUE THREAD

**Issue by wanyaoqi** [yunionio/cloudpods#18270]
**问题描述/What happened**:
v3.10.6 host-deployer base镜像中缺少 parted fdisk gdisk 等命令，导致创建虚机时指定新增的磁盘文件系统和挂载点失效
**环境/Environment**:
cloudpods v3.10.6

**解决办法/Solution**:
更新 host-deployer 镜像为： `registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:v3.10.6-1`
```bash
kubectl patch oc -n onecloud default --type='json' \
   -p='[{op: replace, path: /spec/hostdeployer/image, value: registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:v3.10.6-1},{op: replace, path: /spec/hostdeployer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/hostdeployer/tag, value: v3.10.6-1}]'
```

**Comment by zexi** [comment]
@wanyaoqi 需要再验证下 v3.10.6 host-deployer 镜像有没有被覆盖，没问题再关闭该问题。

**Comment by zexi** [comment]
验证后没有问题
