### ISSUE TITLE
[求助/Help]GPU透传虚拟机找不到显卡设备

### ISSUE THREAD

**Issue by OSCAR2766** [yunionio/cloudpods#18291]
宿主机Centos直通Centos虚拟机，uefi和bios启动模式都试过，设备类型hpc和vga都测过，来回折腾虚拟机里lspci就是没有RTX3090的pci设备出现，都是只有这个默认的vga。目前不清楚是我宿主机配置问题还是虚拟机的配置属性有要求。官网的文档基本都看了，找不到其他有用信息，请问大家有没成功的案例可以让我参考一下。如有相关问题沟通，也可邮件联系2134313485@qq.com。
![3](https://github.com/yunionio/cloudpods/assets/48045800/7b9932f2-1f02-49fc-b4dd-9d61ef3dafc8)
![c19d66a6ec2d4d301246abae78a157f](https://github.com/yunionio/cloudpods/assets/48045800/150281f4-807d-42a3-9bd1-17404e8d6035)
![7799a9027dde4576c4425246f16e605](https://github.com/yunionio/cloudpods/assets/48045800/447230b3-307f-43b4-9d5c-781d3284477c)

下面附上宿主机的一些信息

1. 已验证Intel VT-d 或 AMD IOMMU 在系统的 BIOS 中启用。
![1](https://github.com/yunionio/cloudpods/assets/48045800/c33c510e-a7d7-4c18-93c4-3e283d48347d)

2. 已验证 grub 设置的内核参数已经生效
![2](https://github.com/yunionio/cloudpods/assets/48045800/2afe9edb-f44d-4ddf-b46a-eec98d38a6ed)

3. 已验证 vfio 内核模块正确加载
![da58edf17f5825329252cb55bc8f2d2](https://github.com/yunionio/cloudpods/assets/48045800/e96164ac-08a7-4824-b91e-662386ef8616)

4. 已验证宿主机上待透传的PCI/PCIe设备被vfio-pci接管
![93550e6e63dae87f5d86d4df58839b4](https://github.com/yunionio/cloudpods/assets/48045800/36900dff-5f8c-47f8-a92a-b6482f30c6d5)

5. 宿主机的一些其他配置展示
![b211c1fd0aa04c1fcf97798a7b60d3b](https://github.com/yunionio/cloudpods/assets/48045800/f221d108-c8e3-492c-a675-0e835588f3fb)

**Comment by wanyaoqi** [comment]
@OSCAR2766 虚机内核是什么版本的，宿主机内核是什么版本的

**Comment by OSCAR2766** [comment]
> @OSCAR2766 虚机内核是什么版本的

宿主机：Linux node6 5.4.130-1.yn20221208.el7.x86_64 #1 SMP Thu Dec 8 12:09:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
虚拟机：Linux Test-Uefi.cloud.onecloud.io 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wanyaoqi** [comment]
@OSCAR2766 换个高版本内核的虚机镜像试试
