### ISSUE TITLE
[BUG]区域名称为空后就不能操作改名了

### ISSUE THREAD

**Issue by MJings** [yunionio/cloudpods#18307]
<img width="960" alt="1697114719844" src="https://github.com/yunionio/cloudpods/assets/51787309/93b09c38-8e7c-409c-9927-9cd4d6de0699">
修改区域名称的时候，没有输入任何字符后，名称编辑就没了，只剩下一个备注

**Comment by zexi** [comment]
@MJings 请问部署的版本是哪个？v3.10.5 还是其它版本？

**Comment by MJings** [comment]
3.10.5

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/5495 已修复

**Comment by MJings** [comment]
升级了最新版本，并没有修复此问题

> [yunionio/dashboard#5495](https://github.com/yunionio/dashboard/pull/5495)已修复

**Comment by MJings** [comment]
升级了最新版本，并没有修复此问题

**Comment by dengju2020** [comment]
> yunionio/dashboard#5495

@MJings 等我们月底发版更新下。现在还没有发。

如果现在需要修改区域名称信息，可以使用climc工具。参考：https://www.cloudpods.org/zh/docs/ops/climc/usage/
