### ISSUE TITLE
[BUG] 在 ubuntu22.04 上安装 3.10.6 报错

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#18313]
**问题描述/What happened**:
ubuntu22.04 上安装 3.10.6, region-dns 启动失败，报错：

[debug 231013 09:04:50 db.newTableSpec(tablespec.go:73)] table opslog_tbl maxDuration 720 hour maxSegements 6
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize cloudproviderregions
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtagcloudproviders
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtagcloudregions
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize dbinstance_secgroups
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize dbinstancenetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize dns_zonevpcs
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize elasticcachesecgroups
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize groupguests
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize groupnetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize guestdisks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize guestnetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize guestsecgroups
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize baremetalnetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtaghosts
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize hoststorages
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize hostwires
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize instancebackupjoints
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize instancesnapshotjoints
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize inter_vpc_network_vpcs
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize loadbalancernetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize networkinterfacenetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtagnetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize scalinggroupguests
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize scalinggroupnetworks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize snapshotpolicydisks
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize storagecachedimages
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtagstorages
[debug 231013 09:04:50 db.NewJointResourceBaseManager(jointbase.go:48)] Initialize schedtagzones
listen tcp :53: bind: address already in use

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):  22.04.3 LTS (Jammy Jellyfish)
- Kernel (e.g. `uname -a`): Linux ubuntu-22-04-01 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`): 
        Manufacturer: innotek GmbH
	Manufacturer: Oracle Corporation
	Product Name: VirtualBox
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): 没装上

**Comment by zexi** [comment]
@flowlsj 是用的 ocboot 最新的代码部署的吗？

**Comment by flowlsj** [comment]
是最新的 ocboot，拉的 master 的。
![image](https://github.com/yunionio/cloudpods/assets/7510377/a9b4f79c-05a4-44b0-b9bf-4c6cd3461caf)
卡在zhe这里。看 master 就是 region-dns 起不来

**Comment by zexi** [comment]
> 是最新的 ocboot，拉的 master 的。 ![image](https://user-images.githubusercontent.com/7510377/274856083-a9b4f79c-05a4-44b0-b9bf-4c6cd3461caf.png) 卡在zhe这里。看 master 就是 region-dns 起不来

@flowlsj 执行下面的命令看下其他服务的状态：

```bash
kubectl get pods -A
```

**Comment by flowlsj** [comment]
@zexi 
![image](https://github.com/yunionio/cloudpods/assets/7510377/a8b1a3ac-5f36-4747-bee6-6762dda1e42a)
那个错误过了，我再看看

**Comment by zexi** [comment]
> @zexi ![image](https://user-images.githubusercontent.com/7510377/274857410-a8b1a3ac-5f36-4747-bee6-6762dda1e42a.png) 那个错误过了，我再看看

@flowlsj 这个镜像拉取不下来的问题，感觉是 dns 的关系，应该是 region-dns 和系统里面的 systemd dns 服务冲突了，可能会导致域名解析失效，你试下手动 docker pull 镜像能否拉取下来？

**Comment by flowlsj** [comment]
@zexi 手动 pull 也失败了，都是用的阿里云的，怎么一部分拉取成功了呢？

**Comment by flowlsj** [comment]
![image](https://github.com/yunionio/cloudpods/assets/7510377/7f1504ee-e0f4-4af6-9924-d5a1188a10a4)
这些do'sh都是安装的时候拉到的

**Comment by flowlsj** [comment]
“应该是 region-dns 和系统里面的 systemd dns 服务冲突了”  我觉得你是对的，这台机器现在都解析不了域名了

**Comment by zexi** [comment]
> “应该是 region-dns 和系统里面的 systemd dns 服务冲突了” 我觉得你是对的，这台机器现在都解析不了域名了

@flowlsj 先手动修改下 /etc/resolv.conf ，把 nameserver 改成 114.114.114.114 试试能否解决？

**Comment by flowlsj** [comment]
@zexi 手动改nameserver 可以 pull image。但是在这个过程中 region-dns 好像会去一直去改动/etc/resolv.conf。然后改完/etc/resolv.conf 之后 region-dns 服务就会失败。
![image](https://github.com/yunionio/cloudpods/assets/7510377/7d3232b1-c8a5-40f8-8d35-a419e5b65701)

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/issues/18160

**Comment by flowlsj** [comment]
@zexi 还有一个问题，host-image 无法正常工作。
![image](https://github.com/yunionio/cloudpods/assets/7510377/18dd3245-9c87-41e8-9585-83b11ac71cdf)

**Comment by wanyaoqi** [comment]
@flowlsj 贴一下错误日志

**Comment by flowlsj** [comment]
![image](https://github.com/yunionio/cloudpods/assets/7510377/a55889e1-3ffd-4702-a4a9-8e0e64ac630f)
 就这一行

**Comment by zexi** [comment]
> ![image](https://user-images.githubusercontent.com/7510377/275728176-a55889e1-3ffd-4702-a4a9-8e0e64ac630f.png) 就这一行

@flowlsj 这个问题我应该修复过，看下 onecloud-operator 这个 pod 的版本是不是 v3.10.6 的？

**Comment by flowlsj** [comment]
哦，那我换到 3.10.6 试试

**Comment by zexi** [comment]
> @zexi 手动改nameserver 可以 pull image。但是在这个过程中 region-dns 好像会去一直去改动/etc/resolv.conf。然后改完/etc/resolv.conf 之后 region-dns 服务就会失败。 ![image](https://user-images.githubusercontent.com/7510377/274870373-7d3232b1-c8a5-40f8-8d35-a419e5b65701.png)

@flowlsj https://github.com/yunionio/ocboot/pull/978 这个 PR 解决 DNS 启动不了的问题

**Comment by zexi** [comment]
@flowlsj ubuntu 22.04 的部署问题已经都解决了，可以拉取最新的 ocboot 代码，再部署测试下

<img width="1955" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/3a1e82be-aef4-461b-b179-8d611084235b">

我本地测试 ubuntu 22.04 作为2个节点，已经搞定了。

**Comment by zexi** [comment]
@flowlsj 是的，要用 ocboot 最新的代码安装就行了
