### ISSUE TITLE
[求助/Help] 龙蜥8.8的镜像不能被cloudpods识别

### ISSUE THREAD

**Issue by Misswjy** [yunionio/cloudpods#18319]
龙蜥8.8的镜像目前可以使用吗，我上传的官方的龙蜥8.8的镜像不被cloudpods识别，且创建虚拟机后磁盘不会自动扩充

**Comment by Misswjy** [comment]
[root@test ~]# hostnamectl 
   Static hostname: localhost.localdomain
Transient hostname: test.cloud.onecloud.io
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b00b1714933e44ef9a3a79b80397bdbf
           Boot ID: 1010ab6dd04c4ecbbaad40636fdfd5d4
    Virtualization: kvm
  Operating System: Anolis OS 8.8
            Kernel: Linux 5.10.134-13.an8.x86_64
      Architecture: x86-64
[root@test ~]# 
[root@test ~]# 
[root@test ~]# 
[root@test ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   50G  0 disk 
└─sda1   8:1    0   20G  0 part /
sr0     11:0    1 1024M  0 rom  
[root@test ~]#

**Comment by Misswjy** [comment]
![1d6411ec6fcf6eb57fbc98b5e05aabf](https://github.com/yunionio/cloudpods/assets/102505378/30fed437-4de5-416e-b72e-f57c5930bf5b)

**Comment by zexi** [comment]
@Misswjy 感谢反馈，这个我们需要测试下 /keep-state

**Comment by swordqiu** [comment]
@Misswjy 

已经修复，请等待3.10.7发版
https://github.com/yunionio/cloudpods/pull/18342

**Comment by xxiang188** [comment]
可以给个联系方式 深入了解云计算吗??

**Comment by zexi** [comment]
> 可以给个联系方式 深入了解云计算吗??

@xxiang188 这里有联系方式：https://www.cloudpods.org/zh/docs/contact/
