### ISSUE TITLE
[求助/Help] Docker build 拉取镜像失败

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#18328]
Docker build/docker/Dockerfile.baremetal-agent时候会先FROM registry.cn-beijing.aliyuncs.com/yunionio/baremetal-base:v0.3.9-20230812.0
然后拉取到sha256:d08d4463ff3585d6aeba2449318c361ae182872105da5f5334611ddf27a3dee2 0B / 84.18kB的时候就会失败报403错误。。
我是用的macOS，请问该怎么办啊

**Comment by zexi** [comment]
@vincentiss 是用的 `make image baremetal-agent` 打包镜像的吗？

**Comment by vincentiss** [comment]
> @vincentiss 是用的 `make image baremetal-agent` 打包镜像的吗？

不是
是Docker build的时候出错的 用的build/docker/Dockerfile.baremetal-agent这个文件

**Comment by zexi** [comment]
@vincentiss 直接用 docker build 是不行的，请参考文档：https://www.cloudpods.org/zh/docs/development/dev-env/

设置好 docker buildx 后，使用`make image baremetal-agent` 编译打包。

> > @vincentiss 是用的 `make image baremetal-agent` 打包镜像的吗？
> 
> 不是 是Docker build的时候出错的 用的build/docker/Dockerfile.baremetal-agent这个文件

**Comment by vincentiss** [comment]
可能公司内网有限制拉不下来 虚拟机可以。。
