### ISSUE TITLE
[求助/Help] 请问PCI透传功能支持直接指定PCI地址吗

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#18336]
想把网卡的某个口直通到虚拟机内，原来在pve的做法是新增pci设备，指定hostpci 地址。
cloudpods 下似乎只能把网卡透传。

再相关issue 中未找到答案，也和这个issue 遇到的情况不同：https://github.com/yunionio/cloudpods/issues/17538
所以另外发帖求问，谢谢。

**Comment by wanyaoqi** [comment]
@fangpsh 可以参考一下这个文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/

**Comment by fangpsh** [comment]
> @fangpsh 可以参考一下这个文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/

感谢回复。这个文档阅读过，文档中指明的是直接把整个设备透传，无法将整个网卡这么操作。

想请教的是如何将特定pci 地址的设备透传，例如一个网卡设备有4个口，4个地址，透传特定某一个。
类似pve 的做法：
```
qm set VMID -hostpci0 02:00,device-id=0x10f6,sub-vendor-id=0x0000
```

**Comment by wanyaoqi** [comment]
> > @fangpsh 可以参考一下这个文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/
> 
> 感谢回复。这个文档阅读过，文档中指明的是直接把整个设备透传，无法将整个网卡这么操作。

这里不是整个设备，文档也没有写整个设备。文档中是注册一种设备类型（通过 device_id 和 vendor_id）。
4个口4个地址当然是4个设备，只不过在cloudpods你需要先将设备注册上来，然后再分配给虚机。
或许你可以先尝试一下？

> 
> 想请教的是如何将特定pci 地址的设备透传，例如一个网卡设备有4个口，4个地址，透传特定某一个。 类似pve 的做法：
> 
> ```
> qm set VMID -hostpci0 02:00,device-id=0x10f6,sub-vendor-id=0x0000
> ```

**Comment by fangpsh** [comment]
> > > @fangpsh 可以参考一下这个文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/
> > 
> > 
> > 感谢回复。这个文档阅读过，文档中指明的是直接把整个设备透传，无法将整个网卡这么操作。
> 
> 这里不是整个设备，文档也没有写整个设备。文档中是注册一种设备类型（通过 device_id 和 vendor_id）。 4个口4个地址注册上来是4个设备，只不过在cloudpods你需要先将设备注册上来，然后再分配给虚机。 或许你可以先尝试一下？
> 
> > 想请教的是如何将特定pci 地址的设备透传，例如一个网卡设备有4个口，4个地址，透传特定某一个。 类似pve 的做法：
> > ```
> > qm set VMID -hostpci0 02:00,device-id=0x10f6,sub-vendor-id=0x0000
> > ```

刚刚尝试了下，添加 SR-IOV NIC，添加完之后，宿主机失联了😭，修复中。

**Comment by fangpsh** [comment]
```
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
02:00.1 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
03:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
03:00.1 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
```

```
# lspci -n -s '02:00.1'
02:00.1 0200: 14e4:165f
```
添加了vendor_id ：14e4，device_id：165f。
操作完成之后，对应宿主机及关联虚拟机资源直接失联。重启后可恢复。

**Comment by wanyaoqi** [comment]
> > > > @fangpsh 可以参考一下这个文档 https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices/
> > > 
> > > 
> > > 感谢回复。这个文档阅读过，文档中指明的是直接把整个设备透传，无法将整个网卡这么操作。
> > 
> > 
> > 这里不是整个设备，文档也没有写整个设备。文档中是注册一种设备类型（通过 device_id 和 vendor_id）。 4个口4个地址注册上来是4个设备，只不过在cloudpods你需要先将设备注册上来，然后再分配给虚机。 或许你可以先尝试一下？
> > > 想请教的是如何将特定pci 地址的设备透传，例如一个网卡设备有4个口，4个地址，透传特定某一个。 类似pve 的做法：
> > > ```
> > > qm set VMID -hostpci0 02:00,device-id=0x10f6,sub-vendor-id=0x0000
> > > ```
> 
> 刚刚尝试了下，添加 SR-IOV NIC，添加完之后，宿主机失联了😭，修复中。

@fangpsh 开启 SR-IOV 参考这个文档
https://www.cloudpods.org/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov/#%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%BC%80%E5%90%AF-sr-iov

**Comment by fangpsh** [comment]
感谢，待我腾挪一台机器出来，单独测试下，然后补充下文档。

**Comment by fangpsh** [comment]
更新一下：
 添加SR-IOV NIC 设备，会如wanyaoqi 老师所说，采集后有多个设备，都会在平台出现，如下图
<img width="799" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/e5ee2cce-db80-49c8-b58f-00a6c7ae0a2f">
可以点进去，根据PCI_BUS_ID 区分每个设备，再关联到虚拟机即可。

要添加透传网卡设备，必须是双网卡，添加非宿主机IP在的网卡设备。如果是只有一个网卡，添加之后，会导致宿主机直接离线。
