### ISSUE TITLE
[求助/Help] 多云纳管平台无法在线重置密码及迁移

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#18332]
# 环境说明
创建了一套3个节点的高可用cloudpods私有云A（v3.10.6）。
然后用docker-compose启用了一套cloudpods平台B（v3.10.6），并通过多云管理功能纳管了集群A。

#18113 
# 问题说明
## 问题1：纳管平台未同步私有云的基础监控
私有云的监控截图
![image](https://github.com/yunionio/cloudpods/assets/46590985/786293d8-47f5-4ed2-b5f1-7dc17248479d)

纳管平台的监控截图（都是一周的监控截图，各种指标均类似）
![image](https://github.com/yunionio/cloudpods/assets/46590985/3083b089-22cf-4aa5-8bf8-2821a64ac5bc)

## 问题2：VM无法在线重置密码
纳管平台B上，VM需先关机，才可重置密码
![image](https://github.com/yunionio/cloudpods/assets/46590985/fc3bf8b4-cf85-483a-ab03-1819f87a4f11)

## 问题3：纳管平台无法迁移虚拟机
纳管平台无法迁移虚拟机，私有云上可以正常执行。
```
{
  "class": "NotAcceptableError",
  "code": 406,
  "details": "hypervisor cloudpods不允许此操作",
  "time": "2023-10-17T14:32:34+08:00"
}
```

**Comment by ioito** [comment]
2和3并未实现，1需要我验证下

**Comment by SlyChen** [comment]
多云纳管问题太多，不测了，关了。

**Comment by dengju2020** [comment]
> 多云纳管问题太多，不测了，关了。

不好意思给你带来不好的体验，目前我们新版在进行回归测试。等待新版发布后再试试🙏

**Comment by dengju2020** [comment]
@SlyChen 第一个问题，监控看着俩个监控的时间范围不一样。建议修改为一样试试

**Comment by SlyChen** [comment]
> @SlyChen 第一个问题，监控看着俩个监控的时间范围不一样。建议修改为一样试试

选择的时间范围是一样的，显示的异常。

除了纳管异常，私有云本身的监控就有点问题，#18406 一部分基础监控不显示，另外经典网络的agent监控无数据，问题 #16433 跟这个一样。

**Comment by dengju2020** [comment]
> > @SlyChen 第一个问题，监控看着俩个监控的时间范围不一样。建议修改为一样试试
> 
> 选择的时间范围是一样的，显示的异常。
> 
> 除了纳管异常，私有云本身的监控就有点问题，#18406 一部分基础监控不显示，另外经典网络的agent监控无数据，问题 #16433 跟这个一样。

好的。我们重新回归下
