### ISSUE TITLE
[求助/Help] v3.10.6私有云集群虚拟机无法在线扩容

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#18334]
v3.10.6私有云集群，虚拟机硬盘扩容时，lsblk查看硬盘已扩容成功。而part部分还是未扩容前的容量，需手动growpart再xfs_growfs才能实现真正的扩容。

**Comment by zexi** [comment]
> v3.10.6私有云集群，虚拟机硬盘扩容时，lsblk查看硬盘已扩容成功。而part部分还是未扩容前的容量，需手动growpart再xfs_growfs才能实现真正的扩容。

@SlyChen 这个是这样的，如果要自动给文件系统扩容，需要关机进行。在开机情况下扩容，平台只能在宿主机上把虚拟机的磁盘 resize ，无法进入虚拟机里面调用文件系统命令扩容，需要用户手动操作下。

**Comment by SlyChen** [comment]
有道理，我的问题。
