### ISSUE TITLE
[求助/Help] v3.10.6私有云windows2012无法修改启动顺序

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#18347]
虚拟机windows2012无法修改启动顺序。
![image](https://github.com/yunionio/cloudpods/assets/46590985/07a03e16-01ba-4842-aaf3-6465d76a14c5)

**Comment by wanyaoqi** [comment]
@SlyChen 你的意思是设置启动顺序后没生效？还是从光盘引导吗

**Comment by SlyChen** [comment]
无法变更顺序，比如把光驱改成第一引导。

**Comment by dengju2020** [comment]
可以鼠标拖动顺序 @SlyChen

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/5556

**Comment by dengju2020** [comment]
@SlyChen 本地已复现并修复，可以等待下个版本发布或者拉取最新的代码更新
