### ISSUE TITLE
[求助/Help] 主机-虚拟机列表页面性能问题

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#18370]
主机->虚拟机 列表 页面，肉眼可见，加载缓慢。

接口地址：/api/v2/servers?scope=system&show_fail_reason=true&details=false&with_meta=true&filter=hypervisor.notin%28baremetal%2Ccontainer%29&cloud_env=onpremise&limit=100

<img width="1388" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/bbbce5fc-d233-479e-87f7-7a053ad00628">

/api/v2/servers?scope=system&show_fail_reason=true&details=true&with_meta=true&filter=hypervisor.notin%28baremetal%2Ccontainer%29&cloud_env=onpremise&limit=100

<img width="1362" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/abce60f6-d78e-4328-8a57-047e8cd834a4">

版本：v3.10.6

**Comment by fangpsh** [comment]
共 133 个主机，控制节点，没看到性能异常。其他页面均还正常。
请问，如何进一步找到性能点，例如可以给下这个接口的对应sql，我explain一下不。
谢谢。

**Comment by fangpsh** [comment]
Queued at 2.43s
更多时间是在前端的队列中排队，前端的处理耗时？

**Comment by easy-mj** [comment]
列表字段只保留当前9列信息，试试效果如何
![image](https://github.com/yunionio/cloudpods/assets/11886313/0250359d-762d-4bec-9168-503e6a9f2abd)

**Comment by fangpsh** [comment]
<img width="765" alt="image" src="https://github.com/yunionio/cloudpods/assets/1650540/bedca7cf-5313-4fbc-bb67-33b8e4f0075c">
这样尝试了，现象依然。

**Comment by fangpsh** [comment]
升级到3.10.7 之后，进入虚拟机页面感觉更快一点，会先获取其他信息，再更新IP和宿主机列信息，体验好一些了。
这个issue 我先关闭了。
