### ISSUE TITLE
[求助/Help]3.10.6不支持h3c私有云吗？

### ISSUE THREAD

**Issue by dengni-10000** [yunionio/cloudpods#18375]
我看功能介绍上看已经支持，但是feature-config里面又没有呀
![image](https://github.com/yunionio/cloudpods/assets/128779102/d9e38328-f2cd-4661-a5a0-48940812ad1e)

**Comment by dengju2020** [comment]
开源版不支持，只有企业版支持 @dengni-10000

**Comment by dengju2020** [comment]
我们稍晚更新下文档，标记下企业版支持的云平台
