### ISSUE TITLE
[求助/Help]磁盘分配失败

### ISSUE THREAD

**Issue by daixh302** [yunionio/cloudpods#18399]
esxi6.5环境下，几台主机接入了vcenter，在多云管理账号中接入的是vcenter和相应的账号。
磁盘分配失败，日志如下：

{
    "__reason__": {
        "reason": {
            "image_id": "a82eca16-6c1d-41bd-89a6-378e4cba78d5",
            "reason": {
                "__reason__": "AcquireImage: remoteFile.Fetch: download: Remote file fetch GET https://default-cloudpods-glance:30292/v1/images/a82eca16-6c1d-41bd-89a6-378e4cba78d5?format=vmdk&scope=system error 404",
                "__stage__": "OnImageCacheComplete",
                "__status__": "error"
            }
        },
        "stage": "OnImageCacheComplete"
    },

测试glance到vcenter主机 TCP 902端口不通，到vcenter主机上进行了检查，发现并没有TCP 902的监听，UDP 902端口倒有监听，glance到其他接入vcenter被管理主机的TCP 902是通的。

**Comment by zexi** [comment]
@daixh302 目前用 helm 部署的不支持 esxi 的管理，如果要管理，请先使用 allinone 的方式部署

**Comment by daixh302** [comment]
docker compose部署的支持吗

**Comment by zexi** [comment]
> docker compose部署的支持吗

@daixh302 目前 docker compose 和 helm 部署的都还不支持，因为目前 esxi 的管理还依赖一些内核模块，所以需要用 ocboot 部署完整的一套系统才行，这个问题我们还在改进中。

**Comment by daixh302** [comment]
我需要管理esxi，同时还要阿里云和天翼云等这样云平台的资源，我该以allinone的方式安装哪个版本？

**Comment by zexi** [comment]
> 我需要管理esxi，同时还要管理阿里云和天翼云等这样云平台的资源，我该以allinone的方式安装哪个版本？

@daixh302 https://www.cloudpods.org/zh/docs/quickstart/allinone-converge/ 安装融合云版本

**Comment by daixh302** [comment]
已经安装了allinone融合云版本，我们的每台ESXI有两个物理网卡，每个网卡分别绑了一个端口组，这样可以给虚拟机按需分配两个不同的子网IP。那在融合云版本控制台，怎么绑定这两个物理网卡的两个子网，我看文档也很抽象。

**Comment by swordqiu** [comment]
@daixh302 这是我们最近更新的vmware网络原理介绍，应该比之前要清晰一些。 https://www.cloudpods.org/zh/docs/function_principle/multicloud/vmware/vmware_net/

简单说，3.10版本之前（含），二层网络和虚拟交换机对应，IP子网通过VLAN_ID和虚拟交换机的端口组对应。如果用3.10，可以在这台宿主机所在的二层网络上创建两个IP子网，其VLAN_ID和这两个端口组的VLAN_ID一一对应。

3.11版本后（含），端口组和二层网络，接入一个端口组的虚拟机可以从对应二层网络的IP子网分配IP。所以如果用3.11，可以在这两个端口组上分别创建两个子网即可。
