### ISSUE TITLE
[求助/Help]一次性创建多台虚拟机 有几率部分虚拟机获取不到ip地址

### ISSUE THREAD

**Issue by Misswjy** [yunionio/cloudpods#18398]
[root@k8s-master-primary ~]# kubectl logs default-host-7tjwm -n onecloud -c host | grep error
[error 2023-10-20 10:15:42 hostinfo.(*SHostInfo).PutHostOnline(hostinfo.go:1553)] Host sys error: map[isolated_devices:[{isolated_devices    GPU 03:00.0 use kernel driver ast, skip it 2023-10-20 10:15:42.416298942 +0000 UTC m=+5.471518676}]]
[error 2023-10-20 11:32:44 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 4f36a307-23bf-48e4-8f27-34ecd7cffcd5 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-20 11:32:44 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:785)] Guest test(4f36a307-23bf-48e4-8f27-34ecd7cffcd5) qmp monitor connect failed Connect to tcp 127.0.0.1:56101 failed dial tcp 127.0.0.1:56101: connect: connection refused, something wrong
[error 2023-10-20 11:32:45 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_4f36a307-23bf-48e4-8f27-34ecd7cffcd5_10021: no such file or directory
[error 2023-10-20 11:46:05 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1222)] Guest 4f36a307-23bf-48e4-8f27-34ecd7cffcd5 on Monitor Disconnect reason: <nil>
[error 2023-10-20 11:46:49 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 4f36a307-23bf-48e4-8f27-34ecd7cffcd5 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-20 11:46:50 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_4f36a307-23bf-48e4-8f27-34ecd7cffcd5_24477: no such file or directory
[error 2023-10-21 08:01:23 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:263)] Remove task path failed remove /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_4f36a307-23bf-48e4-8f27-34ecd7cffcd5_24477: device or resource busy
[error 2023-10-21 08:20:59 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 74547b6f-bced-4949-893f-7dfd812127c8 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-21 08:20:59 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:785)] Guest test-1(74547b6f-bced-4949-893f-7dfd812127c8) qmp monitor connect failed Connect to tcp 127.0.0.1:56103 failed dial tcp 127.0.0.1:56103: connect: connection refused, something wrong
[error 2023-10-21 08:21:00 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_74547b6f-bced-4949-893f-7dfd812127c8_37554: no such file or directory
[error 2023-10-21 10:15:20 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:263)] Remove task path failed remove /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_74547b6f-bced-4949-893f-7dfd812127c8_37554: device or resource busy
[error 2023-10-21 10:16:39 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest d5f1c537-e8b3-4a16-8dc8-12ea07fadb04 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-21 10:16:40 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_d5f1c537-e8b3-4a16-8dc8-12ea07fadb04_28367: no such file or directory
[error 2023-10-21 10:58:15 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 9c548a35-9fd6-4e3c-86cf-d2e98bfb0762 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-21 10:58:16 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_9c548a35-9fd6-4e3c-86cf-d2e98bfb0762_28454: no such file or directory
[error 2023-10-21 11:03:42 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:263)] Remove task path failed remove /sys/fs/cgroup/cpu/cloudpods.hostagent/server_9c548a35-9fd6-4e3c-86cf-d2e98bfb0762_28454: device or resource busy
[error 2023-10-21 11:03:42 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:263)] Remove task path failed remove /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_d5f1c537-e8b3-4a16-8dc8-12ea07fadb04_28367: device or resource busy
[error 2023-10-21 11:07:13 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 2cada9f6-fb5f-4fb3-801a-a7c6ac664e6d start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-21 11:07:13 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_2cada9f6-fb5f-4fb3-801a-a7c6ac664e6d_37548: no such file or directory
[error 2023-10-21 11:30:49 httperrors.HTTPError(httperrors.go:110)] Send error Guest 86e4c4b7-cd5b-49ad-8e4e-c4ed371c9441 not found
[error 2023-10-21 11:30:50 httperrors.HTTPError(httperrors.go:110)] Send error Guest 86e4c4b7-cd5b-49ad-8e4e-c4ed371c9441 not found
[error 2023-10-21 11:31:27 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 86e4c4b7-cd5b-49ad-8e4e-c4ed371c9441 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-21 11:31:28 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_86e4c4b7-cd5b-49ad-8e4e-c4ed371c9441_20614: no such file or directory
[error 2023-10-22 04:55:20 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest ec37649a-f041-43e6-8772-64db33216e6c start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 04:55:21 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_ec37649a-f041-43e6-8772-64db33216e6c_17832: no such file or directory
[error 2023-10-22 05:04:36 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest ec37649a-f041-43e6-8772-64db33216e6c start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 05:04:36 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_ec37649a-f041-43e6-8772-64db33216e6c_27167: no such file or directory
[error 2023-10-22 05:16:05 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1222)] Guest ec37649a-f041-43e6-8772-64db33216e6c on Monitor Disconnect reason: <nil>
[error 2023-10-22 05:16:57 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest ec37649a-f041-43e6-8772-64db33216e6c start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 05:16:58 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_ec37649a-f041-43e6-8772-64db33216e6c_39279: no such file or directory
[error 2023-10-22 05:28:20 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 8dc776ac-1677-4ced-804b-e457403beb64 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 05:28:20 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_8dc776ac-1677-4ced-804b-e457403beb64_10264: no such file or directory
[error 2023-10-22 05:58:03 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 112d72ec-d23c-4008-89d8-900425af8d86 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 05:58:04 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_112d72ec-d23c-4008-89d8-900425af8d86_40323: no such file or directory
[error 2023-10-22 06:22:09 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1222)] Guest 112d72ec-d23c-4008-89d8-900425af8d86 on Monitor Disconnect reason: <nil>
[error 2023-10-22 06:23:12 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 112d72ec-d23c-4008-89d8-900425af8d86 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 06:23:13 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_112d72ec-d23c-4008-89d8-900425af8d86_24688: no such file or directory
[error 2023-10-22 06:50:29 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest bee130b1-de64-4b10-8e99-279c467c8cde start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 06:50:29 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_bee130b1-de64-4b10-8e99-279c467c8cde_10854: no such file or directory
[error 2023-10-22 08:00:06 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest df798774-566c-4d1f-85dc-21b95b63dee9 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 08:00:07 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_df798774-566c-4d1f-85dc-21b95b63dee9_39336: no such file or directory
[error 2023-10-22 08:05:44 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 6dba927f-bbe0-44e9-825b-74428e8dfd11 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 08:05:44 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 6dba927f-bbe0-44e9-825b-74428e8dfd11 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 08:05:45 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_6dba927f-bbe0-44e9-825b-74428e8dfd11_4520: no such file or directory
[error 2023-10-22 08:08:32 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1222)] Guest 6dba927f-bbe0-44e9-825b-74428e8dfd11 on Monitor Disconnect reason: <nil>
[error 2023-10-22 08:09:06 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 6dba927f-bbe0-44e9-825b-74428e8dfd11 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-22 08:09:06 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_6dba927f-bbe0-44e9-825b-74428e8dfd11_8296: no such file or directory
[error 2023-10-23 01:37:28 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 70853073-341c-47d7-8abd-3c8184c039dc start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 01:37:28 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:785)] Guest node-2(70853073-341c-47d7-8abd-3c8184c039dc) qmp monitor connect failed Connect to tcp 127.0.0.1:56118 failed dial tcp 127.0.0.1:56118: connect: connection refused, something wrong
[error 2023-10-23 01:37:29 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_70853073-341c-47d7-8abd-3c8184c039dc_36216: no such file or directory
[error 2023-10-23 03:09:36 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest a67282ba-45b3-4fe9-823a-92def5eede59 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 03:09:36 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_a67282ba-45b3-4fe9-823a-92def5eede59_2987: no such file or directory
[error 2023-10-23 03:43:10 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1222)] Guest a67282ba-45b3-4fe9-823a-92def5eede59 on Monitor Disconnect reason: <nil>
[error 2023-10-23 03:44:05 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest a67282ba-45b3-4fe9-823a-92def5eede59 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 03:44:06 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_a67282ba-45b3-4fe9-823a-92def5eede59_37336: no such file or directory
[error 2023-10-23 04:52:08 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_8f4286ff-d22a-4430-88c7-b8b33c3493dc_22778: no such file or directory
[error 2023-10-23 04:56:08 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:263)] Remove task path failed remove /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_a67282ba-45b3-4fe9-823a-92def5eede59_37336: device or resource busy
[error 2023-10-23 04:59:36 httperrors.HTTPError(httperrors.go:110)] Send error Guest 99cb2243-0285-468a-8185-d52cb2d646e5 not found
[error 2023-10-23 04:59:36 httperrors.HTTPError(httperrors.go:110)] Send error Guest 99cb2243-0285-468a-8185-d52cb2d646e5 not found
[error 2023-10-23 05:00:00 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 99cb2243-0285-468a-8185-d52cb2d646e5 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 05:00:01 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_99cb2243-0285-468a-8185-d52cb2d646e5_30625: no such file or directory
[error 2023-10-23 05:28:15 httperrors.HTTPError(httperrors.go:110)] Send error Guest 5e4baa92-f265-46ef-8227-7b799afa876e not found
[error 2023-10-23 05:28:15 httperrors.HTTPError(httperrors.go:110)] Send error Guest 5e4baa92-f265-46ef-8227-7b799afa876e not found
[info 2023-10-23 05:28:32 workmanager.(*workerTask).Run(manager.go:92)] DelayTask failed: Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab sh: 1: crontab: not found
[error 2023-10-23 05:30:22 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[info 2023-10-23 05:31:06 workmanager.(*workerTask).Run(manager.go:92)] DelayTask failed: Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab sh: 1: crontab: not found
[error 2023-10-23 05:38:31 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[info 2023-10-23 05:49:23 workmanager.(*workerTask).Run(manager.go:92)] DelayTask failed: Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab sh: 1: crontab: not found
[info 2023-10-23 06:28:07 workmanager.(*workerTask).Run(manager.go:92)] DelayTask failed: Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab sh: 1: crontab: not found
[error 2023-10-23 06:34:01 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[error 2023-10-23 06:34:01 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[error 2023-10-23 07:44:19 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[error 2023-10-23 07:44:19 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[error 2023-10-23 07:44:19 guestman.(*SKVMGuestInstance).scriptStop(qemu-kvm.go:1791)] exit status 127
[error 2023-10-23 07:52:43 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest eb9c4b99-c386-4b94-8bd1-7aded2bf6ef7 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 07:52:43 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_eb9c4b99-c386-4b94-8bd1-7aded2bf6ef7_35451: no such file or directory
[error 2023-10-23 07:56:05 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest 4f102d41-1d8f-47ea-8cf7-066568e1a44c start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 07:56:06 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_4f102d41-1d8f-47ea-8cf7-066568e1a44c_39219: no such file or directory
[error 2023-10-23 09:38:36 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest ded95ccc-012d-44f5-8800-09da5dba0ff1 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 09:38:36 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_ded95ccc-012d-44f5-8800-09da5dba0ff1_17769: no such file or directory
[error 2023-10-23 09:42:23 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:792)] Guest eefdec59-c049-4e9c-8bde-d31004c04b64 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-10-23 09:42:23 cgrouputils.(*CGroupTask).createTask(cgrouputils.go:236)] mkdir /sys/fs/cgroup/memory/cloudpods.hostagent/server_eefdec59-c049-4e9c-8bde-d31004c04b64_21755: no such file or directory

**Comment by Misswjy** [comment]
[root@k8s-master-primary ~]# kubectl logs default-host-deployer-wqxhg -n onecloud | grep error
[error 2023-10-23 01:37:20 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd13p1: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 01:37:20 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd13p2: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 01:37:21 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd13p3: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 01:37:26 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd3p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 01:37:26 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd3p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 03:44:05 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd1p1: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 03:44:05 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd1p2: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 03:44:05 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd1p3: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:28:23 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd0p1: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:28:24 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd0p2: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:28:24 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd0p3: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:28:31 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd0p3/usr/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd0p3/usr/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 05:28:31 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd0p3/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd0p3/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 05:31:05 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd2p3/usr/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd2p3/usr/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 05:31:05 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd2p3/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd2p3/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 05:49:15 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p1: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:49:15 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p2: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:49:15 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p3: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 05:49:22 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd0p3/usr/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd0p3/usr/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 05:49:22 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd0p3/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd0p3/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 06:27:58 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p1: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 06:27:58 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p2: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 06:27:58 nbd.(*NBDDriver).setupLVMS(driver.go:160)] unable to find vg from /dev/nbd3p3: unable to find vg, output is "  No volume groups found.\n"
[error 2023-10-23 06:28:06 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd3p3/usr/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd3p3/usr/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 06:28:06 fsdriver.(*sLinuxRootFs).GetArch(linux.go:467)] stat file /tmp/_dev_nbd3p3/lib64/ld-linux-x86-64.so.2: stat /tmp/_dev_nbd3p3/lib64/ld-linux-x86-64.so.2: no such file or directory
[error 2023-10-23 07:52:40 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd0p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 07:52:40 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd0p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 07:56:02 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd7p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 07:56:02 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd7p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 09:38:24 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd4p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 09:38:24 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd4p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 09:42:11 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd5p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[error 2023-10-23 09:42:11 fsdriver.(*sLinuxRootFs).DeployNetworkingScripts(linux.go:426)] rootFs.GenerateSshHostKeys fail GenerateSshHostKeys /tmp/_dev_nbd5p3 /usr/bin/ssh-keygen -A cannot read from /dev/urandom, No such file or directory
[root@k8s-master-primary ~]#

**Comment by wanyaoqi** [comment]
@Misswjy 虚机什么操作系统

**Comment by wanyaoqi** [comment]
> DelayTask failed: Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab sh: 1: crontab: not found

@Misswjy  看报错是虚机镜像里面没有crontab 命令。这镜像是哪里下载的

**Comment by Misswjy** [comment]
@wanyaoqi 自己用centos的官方镜像做的

**Comment by wanyaoqi** [comment]
@Misswjy 这个 crontab 命令貌似都是默认有的，这样看应该是镜像的问题

**Comment by Misswjy** [comment]
@wanyaoqi 应该不是镜像的问题，没有获取到ip是概率性的

**Comment by wanyaoqi** [comment]
@Misswjy 全都是这个镜像吗，密码是否部署成功

**Comment by Misswjy** [comment]
@wanyaoqi 是这个镜像 密码部署是成功的 只是没获取到ip

**Comment by wanyaoqi** [comment]
@Misswjy 看下虚机里面 networkmanager 是否有什么报错
