### ISSUE TITLE
[求助/Help]怎么强制改IP啊。

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18422]
参数错误
IP 10.16.10.33不可达：IP 10.16.10.33 not reachable on this host

机器是正常可以ping通的

**Comment by dengju2020** [comment]
@shengxianli 可以在虚拟机详情页-网络，修改IP

**Comment by shengxianli** [comment]
@shengxianli 就是在这里修改的，部分主机正常运行，但是不知道为什么修改不了
![image](https://github.com/yunionio/cloudpods/assets/32296103/88195b06-dd97-4a13-bfe4-ae10e6b3fc36)

**Comment by zexi** [comment]
@shengxianli 关机修改试试？

**Comment by shengxianli** [comment]
@zexi 关机也不行。有的能改 有的就改不了，很奇怪

**Comment by zexi** [comment]
> @zexi 关机也不行。有的能改 有的就改不了，很奇怪

@shengxianli 关机改不了的报错是什么？还是 'not reachable on this host' 吗？

**Comment by shengxianli** [comment]
@zexi IP不可达：IP not reachable on this host

**Comment by shengxianli** [comment]
@zexi 有没有通过shell修改配置的方式

**Comment by zexi** [comment]
> @zexi IP不可达：IP not reachable on this host

@shengxianli 这个错误是应该是因为虚拟机所在的宿主机的二层网络里面的子网，没有包含这个要修改的 ip 地址，就算手动修改后，应该也是不通的。

看下平台里面有没有包含这个要修改 ip 的子网，没有的话，需要基于宿主机所在的二层网络新建一个。

**Comment by shengxianli** [comment]
@zexi 确实可以了谢谢
