### ISSUE TITLE
[求助/Help] 新增的计算节点上创建虚拟机无法DHCP获取IP

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#18463]
版本：v3.10.6
问题描述：3台物理节点组建高可用私有云，并做计算节点使用，节点上新建虚拟机均可正常获取IP。现新增了一台计算节点，创建centos|ubuntu虚拟机后均无法DHCP获取IP。

1. 计算节点default-host-xxx日志
![image](https://github.com/yunionio/cloudpods/assets/46590985/46698588-927e-4e1e-b817-dd7e99a81df5)

2. 虚拟机网卡配置文件
![image](https://github.com/yunionio/cloudpods/assets/46590985/9ba2a358-a1dc-49ef-b4a2-d3d5a43e0776)

**Comment by hoganlxj** [comment]
@SlyChen  虚拟机的IP子网是 经典网络下（vpc的名称为Default）的吗？

**Comment by SlyChen** [comment]
> @SlyChen 虚拟机的IP子网是 经典网络下（vpc的名称为Default）的吗？
对，是经典网络，三台控制节点上开的同子网虚拟机是能正常获取的。

**Comment by hoganlxj** [comment]
@SlyChen 发下default-region-xxx的日志

**Comment by SlyChen** [comment]
@hoganlxj  不知道是不是跟这个有关，为了更直观，我重启了defalut-region-xxx。新建了2台测试机。
* 一台是test3，用的是私网，DHCP获取成功了。
* 一台是test4, 用的是公网，DHCP失败了。
![image](https://github.com/yunionio/cloudpods/assets/46590985/2449e0fa-f442-46c9-848c-da54f4be6be2)

日志详见附件：
[default-region.log](https://github.com/yunionio/cloudpods/files/13187135/default-region.log)

私网和公网均在system项目下，并全局共享，无任何不同。

**Comment by wanyaoqi** [comment]
> 版本：v3.10.6 问题描述：3台物理节点组建高可用私有云，并做计算节点使用，节点上新建虚拟机均可正常获取IP。现新增了一台计算节点，创建centos|ubuntu虚拟机后均无法DHCP获取IP。
> 
> 1. 计算节点default-host-xxx日志
>    ![image](https://user-images.githubusercontent.com/46590985/278562848-46698588-927e-4e1e-b817-dd7e99a81df5.png)
> 2. 虚拟机网卡配置文件
>    ![image](https://user-images.githubusercontent.com/46590985/278563093-9ba2a358-a1dc-49ef-b4a2-d3d5a43e0776.png)

@SlyChen 看起来是host-agent 是有dhcp reply的，手动执行 dhclient 也不行吗。
在虚机里面抓包是否能抓到 dhcp reply ? 看下虚机里面的 networkmanager 服务是什么报错

**Comment by SlyChen** [comment]
1. dhclient 没用，持续到超时。
2. 虚拟机抓不到任何dhcp reply相关报文。
![image](https://github.com/yunionio/cloudpods/assets/46590985/f6a48685-686b-4b6f-bbd6-e3e405fd1177)
3. centos&ubuntu（包含正常虚拟机）均无networkmanager服务。
![image](https://github.com/yunionio/cloudpods/assets/46590985/83790544-0119-4761-995e-6ecb8965013d)
4. 在新增的计算节点上开了一台私网的机器（此时正常获取），卸载网卡后，新增一块公网网卡，现象就成无法获取了。

**Comment by SlyChen** [comment]
异常的机器迁移到控制点立马正常，是不是新增的计算节点在DHCP或子网这块少了什么配置？

附件是新增计算节点的host.conf文件。
[host.json](https://github.com/yunionio/cloudpods/files/13200380/host.json)
