### ISSUE TITLE
[求助/Help] glance能否部署多个在不同机房（或者说可用区域）？

### ISSUE THREAD

**Issue by Guojing20210406** [yunionio/cloudpods#18496]
https://www.cloudpods.org/zh/docs/setup/multi-zone/
这个文档告诉了我如何使用多可用区域，我能否部署多个glance服务呢，我的希望是一个机房部署一个glance服务。感谢感谢

**Comment by swordqiu** [comment]
@Guojing20210406 
目前不支持这种部署方式

**Comment by swordqiu** [comment]
@Guojing20210406 平台支持这样的逻辑：

1. 镜像被下载到宿主机后会被缓存在宿主机上
2. 同一个可用区的其他宿主机拉取镜像时，如果同可用区的其他宿主机也缓存了该镜像，会优先从该宿主机拉取

**Comment by Guojing20210406** [comment]
@swordqiu 感谢～
