### ISSUE TITLE
[求助/Help] baremetal-agent正确的部署方式

### ISSUE THREAD

**Issue by Guojing20210406** [yunionio/cloudpods#18556]
文档上说 https://www.cloudpods.org/zh/docs/setup/baremetal/ 目前只能指定一个 node 来部署运行 baremetal-agent 服务，因为 baremetal-agent 服务是有状态的，不能多副本跨节点运行。
但是代码里获取baremetal-agent是通过zoneId获取的
<img width="693" alt="image" src="https://github.com/yunionio/cloudpods/assets/81560614/663434fe-27ab-467c-ae15-33b2904b44a6">
而可用区的文档上https://www.cloudpods.org/zh/docs/setup/multi-zone/ 说添加一个可用区以后会自动创建一个baremetal-agent。那么到底baremetal-agent是整个平台只能有一个baremetal-agent服务？还是一个可用区一个baremetal-agent服务呢？

**Comment by zexi** [comment]
@Guojing20210406 一个可用区可以部署一个 baremetal-agent 服务，一个平台可以部署多个 baremetal-agent 服务。

**Comment by Guojing20210406** [comment]
@zexi 了解～多谢

**Comment by Guojing20210406** [comment]
你好，关于这个问题。我想想问问实际怎么操作，我现在新增一个可用区以后，在第二个node上开放了baremetal-agent。（ocadm baremetal enable --node $node_name --listen-interface $listen_interface）但是，第二个node也还是找到第一个node去运行，导致一直报错。
请问下，是还需要给node加上什么label吗？
