### ISSUE TITLE
[求助/Help] 裸金属镜像安装问题请教

### ISSUE THREAD

**Issue by 522623905** [yunionio/cloudpods#18552]
想请问下，我在
**yunionos-master/src/lib/mos/rootcreate.sh**中看到有一处代码：
```
# clone image at the begining of disk drive
qemu-img convert -O raw /tmp/$IMGID /dev/$DISK
```

请问：
1、这里的镜像是qcow2镜像吗？
2、这里直接将2镜像转换成raw格式到磁盘，就表示系统已经安装到磁盘了吗？如果后面不做任何配置，bios设置启动项后，就可以直接启动这个系统了吗？

**Comment by zexi** [comment]
@522623905 是的，这里是 qcow2 格式的镜像，能否启动还是和 bios 引导有关系的。
比如 bios 设置的是 legacy 模式的引导，就要求 qcow2 镜像是 legacy 引导的；如果 bios 设置了 uefi 引导，就要求 convert 的镜像是 uefi 的。

**Comment by 522623905** [comment]
谢谢。
还有一些问题请教：
1）这些qcow2镜像是特殊制作的，还是一般的都可以这么支持呢？
2）那对于通用的ISO镜像是否支持呢？在这里找到个链接，意思是说上传ISO镜像时，会自动转换成qcow2格式，使得就可以支持了吗？
https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/upload/

**Comment by zexi** [comment]
> 谢谢。 还有一些问题请教： 1）这些qcow2镜像是特殊制作的，还是一般的都可以这么支持呢？ 2）那对于通用的ISO镜像是否支持呢？在这里找到个链接，意思是说上传ISO镜像时，会自动转换成qcow2格式，使得就可以支持了吗？ https://www.cloudpods.org/zh/docs/function_principle/onpremise/glance/sysimage/upload/

@522623905 这里有一些我们制作镜像的脚本，主要是依赖 pakcer 这个工具来自动化制作：https://github.com/yunionio/service-images，物理机镜像最关键的是要默认给 initramfs 里面添加 raid 和 nvme 之类的磁盘驱动：https://github.com/yunionio/service-images/blob/master/scripts/ubuntu/dracut-config.sh#L8-L23

通用的 ISO 需要虚拟机从 ISO 启动，然后装好系统后，执行保存虚拟机镜像，然后平台会自动把虚拟机的系统盘保存成 qcow2 格式的镜像文件。
