### ISSUE TITLE
[求助/Help]添加计算机节点,不显示

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18589]
添加计算机节点,不显示
![image](https://github.com/yunionio/cloudpods/assets/32296103/30e2bafd-52b1-4d93-930e-ac645c0b0e89)

**Comment by zexi** [comment]
@shengxianli 请按照这个步骤排查问题：https://www.cloudpods.org/zh/docs/quickstart/allinone-private/#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA

主要是看 default-host-xxx 这个 pod 有没有起来，起来的话就看下这个 pod 的日志，节点加入不进来的原因都会在日志里面。

**Comment by shengxianli** [comment]
@zexi 很奇怪,.没有日志,节点的IP也看不到
![image](https://github.com/yunionio/cloudpods/assets/32296103/c178ab6a-d048-434f-8e37-998f93054949)

**Comment by zexi** [comment]
> @zexi 很奇怪,.没有日志,节点的IP也看不到 ![image](https://user-images.githubusercontent.com/32296103/281008831-c178ab6a-d048-434f-8e37-998f93054949.png)

@shengxianli 添加进来的计算节点是虚拟机吗？

**Comment by shengxianli** [comment]
@zexi 是物理机

**Comment by zexi** [comment]
> @zexi 是物理机

@shengxianli `kubectl get nodes --show-labels -o wide` 有这个节点吗？

**Comment by shengxianli** [comment]
@zexi 
[root@IT-Cloudpods ocboot]# kubectl get nodes --show-labels -o wide
NAME           STATUS   ROLES    AGE    VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                    CONTAINER-RUNTIME   LABELS
it-cloudpods   Ready    master   110d   v1.15.12   10.0.254.17   <none>        CentOS Linux 7 (Core)   5.4.130-1.yn20221208.el7.x86_64   docker://20.10.5    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=it-cloudpods,kubernetes.io/os=linux,node-role.kubernetes.io/master=,onecloud.yunion.io/controller=enable
[root@IT-Cloudpods ocboot]#

**Comment by zexi** [comment]
> @zexi [root@IT-Cloudpods ocboot]# kubectl get nodes --show-labels -o wide NAME STATUS ROLES AGE VERSION INTERNAL-IP EXTERNAL-IP OS-IMAGE KERNEL-VERSION CONTAINER-RUNTIME LABELS it-cloudpods Ready master 110d v1.15.12 10.0.254.17 CentOS Linux 7 (Core) 5.4.130-1.yn20221208.el7.x86_64 docker://20.10.5 beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=it-cloudpods,kubernetes.io/os=linux,node-role.kubernetes.io/master=,onecloud.yunion.io/controller=enable [root@IT-Cloudpods ocboot]#

@shengxianli 添加的节点不在 k8s node 列表里面？
能发下添加节点的命令吗？

**Comment by shengxianli** [comment]
@zexi  ./ocboot.py add-node 10.0.254.17 10.1.18.2

**Comment by zexi** [comment]
@shengxianli 那看起来是 10.1.18.2 这个节点没有加入到 10.0.254.17 这个 k8s 集群中来，执行 ocboot.py add-node 没有报错吗？麻烦重新执行下看看

**Comment by shengxianli** [comment]
[log.txt](https://github.com/yunionio/cloudpods/files/13278975/log.txt)
@zexi 这个是日志

**Comment by zexi** [comment]
> [log.txt](https://github.com/yunionio/cloudpods/files/13278975/log.txt) @zexi 这个是日志

@shengxianli 不是这个日志，需要 `ocboot.py add-node 10.0.254.17 10.1.18.2` 这个命令的输出，因为现在的现象是这个节点没有出现在 k8s 集群里面

**Comment by shengxianli** [comment]
@zexi 发错了这个是
[log1.txt](https://github.com/yunionio/cloudpods/files/13278995/log1.txt)

**Comment by zexi** [comment]
@shengxianli 是不是这个 10.1.18.2 节点上面已经跑了 kubernetes 了？
登录到那个节点上面，执行 `systemctl status kubelet ` 看下？

**Comment by shengxianli** [comment]
@zexi 
[root@kvmc01 ~]# systemctl status kubelet 
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 二 2023-11-07 19:09:09 CST; 15h ago
     Docs: https://kubernetes.io/docs/
 Main PID: 28800 (kubelet)
    Tasks: 34
   Memory: 50.9M
   CGroup: /system.slice/kubelet.service
           └─28800 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --node-ip=10.1.18.2 --node-labels=onecloud.yunion.io/host=enable --pod-infra-container-image=re...

11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.465430   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.564706   28800 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "kvmc01" is forbidden: User "system:node:kvm01" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-...
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.565518   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.665628   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.765727   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.865829   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.965925   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.066014   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.166109   28800 kubelet.go:2252] node "kvmc01" not found
11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.266214   28800 kubelet.go:2252] node "kvmc01" not found

**Comment by zexi** [comment]
> @zexi [root@kvmc01 ~]# systemctl status kubelet ● kubelet.service - kubelet: The Kubernetes Node Agent Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled) Drop-In: /usr/lib/systemd/system/kubelet.service.d └─10-kubeadm.conf Active: active (running) since 二 2023-11-07 19:09:09 CST; 15h ago Docs: https://kubernetes.io/docs/ Main PID: 28800 (kubelet) Tasks: 34 Memory: 50.9M CGroup: /system.slice/kubelet.service └─28800 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --node-ip=10.1.18.2 --node-labels=onecloud.yunion.io/host=enable --pod-infra-container-image=re...
> 
> 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.465430 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.564706 28800 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "kvmc01" is forbidden: User "system:node:kvm01" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-... 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.565518 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.665628 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.765727 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.865829 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:11 kvmc01 kubelet[28800]: E1108 10:25:11.965925 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.066014 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.166109 28800 kubelet.go:2252] node "kvmc01" not found 11月 08 10:25:12 kvmc01 kubelet[28800]: E1108 10:25:12.266214 28800 kubelet.go:2252] node "kvmc01" not found

@shengxianli 看起来是第一次添加没有成功，可以 reset 重新添加下试试：

```bash
# 重置
kubeadm reset -f
```
然后看下两个节点的时间是否一致，确保系统时间是统一的，然后重新执行 ocboot.py add-node 命令

**Comment by shengxianli** [comment]
[root@IT-Cloudpods ~]# kubeadm reset -f
[preflight] Running pre-flight checks
W1108 10:35:50.628430   30619 removeetcdmember.go:79] [reset] No kubeadm config, using etcd pod spec to get data directory
[reset] No etcd config found. Assuming external etcd
[reset] Please, manually reset etcd to prevent further issues
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
[root@IT-Cloudpods ~]# cd ocboot/
[root@IT-Cloudpods ocboot]# ./ocboot.py add-node 10.0.254.17 10.1.18.2
INFO:lib.ssh:exec_command: [ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json
ssh -p 22 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -i /root/.ssh/id_rsa root@10.0.254.17 '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json'
Traceback (most recent call last):
  File "./ocboot.py", line 40, in <module>
    sys.exit(main())
  File "./ocboot.py", line 36, in main
    args.func(args)
  File "/root/ocboot/lib/service.py", line 100, in do_action
    args.ssh_port)
  File "/root/ocboot/lib/cluster.py", line 24, in construct_cluster
    cluster = OnecloudCluster(cli)
  File "/root/ocboot/lib/cluster.py", line 44, in __init__
    f'{sudo_exec} kubectl -n onecloud get onecloudclusters default -o json')
  File "/root/ocboot/lib/ssh.py", line 84, in exec_command
    raise StderrException(err)
lib.ssh.StderrException: The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by zexi** [comment]
> @zexi [root@IT-Cloudpods ~]# kubeadm reset -f [preflight] Running pre-flight checks W1108 10:35:50.628430 30619 removeetcdmember.go:79] [reset] No kubeadm config, using etcd pod spec to get data directory [reset] No etcd config found. Assuming external etcd [reset] Please, manually reset etcd to prevent further issues [reset] Stopping the kubelet service [reset] Unmounting mounted directories in "/var/lib/kubelet" [reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki] [reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf] [reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
> 
> The reset process does not reset or clean up iptables rules or IPVS tables. If you wish to reset iptables, you must do so manually. For example: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
> 
> If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar) to reset your system's IPVS tables.
> 
> The reset process does not clean your kubeconfig files and you must remove them manually. Please, check the contents of the $HOME/.kube/config file. [root@IT-Cloudpods ~]# cd ocboot/ [root@IT-Cloudpods ocboot]# ./ocboot.py add-node 10.0.254.17 10.1.18.2 INFO:lib.ssh:exec_command: [ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :; kubectl -n onecloud get onecloudclusters default -o json ssh -p 22 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -i /root/.ssh/id_rsa root@10.0.254.17 '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :; kubectl -n onecloud get onecloudclusters default -o json' Traceback (most recent call last): File "./ocboot.py", line 40, in sys.exit(main()) File "./ocboot.py", line 36, in main args.func(args) File "/root/ocboot/lib/service.py", line 100, in do_action args.ssh_port) File "/root/ocboot/lib/cluster.py", line 24, in construct_cluster cluster = OnecloudCluster(cli) File "/root/ocboot/lib/cluster.py", line 44, in **init** f'{sudo_exec} kubectl -n onecloud get onecloudclusters default -o json') File "/root/ocboot/lib/ssh.py", line 84, in exec_command raise StderrException(err) lib.ssh.StderrException: The connection to the server localhost:8080 was refused - did you specify the right host or port?
> 
> [root@IT-Cloudpods ocboot]# kubectl get pods -n onecloud The connection to the server localhost:8080 was refused - did you specify the right host or port?

@shengxianli 不是，我的意思是在 cloud_poc 那台节点上执行 reset ，不是在第一个控制节点执行。。。你现在把第一个控制节点 reset 了。

**Comment by shengxianli** [comment]
@zexi 好吧我恢复下快照

**Comment by zexi** [comment]
> @zexi 好吧我恢复下快照

@shengxianli 好的，还好有快照，可能我表达的不太清楚，流程是：**待加入的节点** `reset` 后，重新再**控制节点**上执行 `add-node` 。

**Comment by shengxianli** [comment]
@zexi 有点意思，还是不行

PLAY RECAP *********************************************************************
10.1.18.2                  : ok=91   changed=21   unreachable=0    failed=0    skipped=21   rescued=0    ignored=0

[root@IT-Cloudpods ocboot]# climc host-list
***  Total: 0  ***
[root@IT-Cloudpods ocboot]# climc host-list
***  Total: 0  ***
[root@IT-Cloudpods ocboot]# ssh root@10.1.18.2
Last login: Wed Nov  8 11:14:12 2023 from 10.0.254.17
[root@kvmc01 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 三 2023-11-08 11:13:20 CST; 8min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 17247 (kubelet)
    Tasks: 35
   Memory: 48.6M
   CGroup: /system.slice/kubelet.service
           └─17247 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --node-ip=10.1.18.2 --node-labels=onecloud.yunion.io/host=enable -...

11月 08 11:20:40 kvmc01 kubelet[17247]: E1108 11:20:40.076977   17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL...
11月 08 11:20:48 kvmc01 kubelet[17247]: E1108 11:20:48.077357   17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "...
11月 08 11:20:55 kvmc01 kubelet[17247]: E1108 11:20:55.077145   17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL...
11月 08 11:20:59 kvmc01 kubelet[17247]: E1108 11:20:59.077388   17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "...
11月 08 11:21:06 kvmc01 kubelet[17247]: E1108 11:21:06.077027   17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL...
11月 08 11:21:14 kvmc01 kubelet[17247]: E1108 11:21:14.077338   17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "...
11月 08 11:21:21 kvmc01 kubelet[17247]: E1108 11:21:21.078088   17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL...
11月 08 11:21:25 kvmc01 kubelet[17247]: E1108 11:21:25.077455   17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "...
11月 08 11:21:36 kvmc01 kubelet[17247]: E1108 11:21:36.077044   17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL...
11月 08 11:21:39 kvmc01 kubelet[17247]: E1108 11:21:39.077413   17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "...
Hint: Some lines were ellipsized, use -l to show in full.
[root@kvmc01 ~]#

**Comment by zexi** [comment]
> @zexi ，还是不行
> 
> PLAY RECAP ********************************************************************* 10.1.18.2 : ok=91 changed=21 unreachable=0 failed=0 skipped=21 rescued=0 ignored=0
> 
> [root@IT-Cloudpods ocboot]# climc host-list *** Total: 0 *** [root@IT-Cloudpods ocboot]# climc host-list *** Total: 0 *** [root@IT-Cloudpods ocboot]# ssh root@10.1.18.2 Last login: Wed Nov 8 11:14:12 2023 from 10.0.254.17 [root@kvmc01 ~]# systemctl status kubelet ● kubelet.service - kubelet: The Kubernetes Node Agent Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled) Drop-In: /usr/lib/systemd/system/kubelet.service.d └─10-kubeadm.conf Active: active (running) since 三 2023-11-08 11:13:20 CST; 8min ago Docs: https://kubernetes.io/docs/ Main PID: 17247 (kubelet) Tasks: 35 Memory: 48.6M CGroup: /system.slice/kubelet.service └─17247 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --node-ip=10.1.18.2 --node-labels=onecloud.yunion.io/host=enable -...
> 
> 11月 08 11:20:40 kvmc01 kubelet[17247]: E1108 11:20:40.076977 17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL... 11月 08 11:20:48 kvmc01 kubelet[17247]: E1108 11:20:48.077357 17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "... 11月 08 11:20:55 kvmc01 kubelet[17247]: E1108 11:20:55.077145 17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL... 11月 08 11:20:59 kvmc01 kubelet[17247]: E1108 11:20:59.077388 17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "... 11月 08 11:21:06 kvmc01 kubelet[17247]: E1108 11:21:06.077027 17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL... 11月 08 11:21:14 kvmc01 kubelet[17247]: E1108 11:21:14.077338 17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "... 11月 08 11:21:21 kvmc01 kubelet[17247]: E1108 11:21:21.078088 17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL... 11月 08 11:21:25 kvmc01 kubelet[17247]: E1108 11:21:25.077455 17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "... 11月 08 11:21:36 kvmc01 kubelet[17247]: E1108 11:21:36.077044 17247 pod_workers.go:190] Error syncing pod 643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8 ("default-telegraf-q66jh_onecloud(643abb88-b0b1-4cc6-a51e-cfd4a9dab7c8)"), skipping: failed to "StartContainer" for "telegraf-init" with CrashL... 11月 08 11:21:39 kvmc01 kubelet[17247]: E1108 11:21:39.077413 17247 pod_workers.go:190] Error syncing pod 3ba8372a-6bb2-4ec0-bb83-2cf052304ee9 ("default-host-xc7z6_onecloud(3ba8372a-6bb2-4ec0-bb83-2cf052304ee9)"), skipping: failed to "StartContainer" for "host" with CrashLoopBackOff: "... Hint: Some lines were ellipsized, use -l to show in full. [root@kvmc01 ~]#

@shengxianli `kubectl get nodes` 现在有这个添加的节点了吗？

**Comment by shengxianli** [comment]
@zexi 现在web控制台还是看不到机器。节点docker很多镜像没有启动，kubectl get nodes可以看到节点，climc host-list看不到计算机节点
![image](https://github.com/yunionio/cloudpods/assets/32296103/ca3a3cb7-55a2-43c2-92a7-b79a49c77328)

**Comment by shengxianli** [comment]
@zexi  哦，我又看了一下 Exited 好像和现在UP的都是一个容器，都是可以忽略的

**Comment by zexi** [comment]
> @zexi 哦，我又看了一下 Exited 好像和现在UP的都是一个容器，都是可以忽略的

执行这个命令把 host 服务日志打出来看下：
`kubectl get pods -n onecloud -o wide | grep host | grep kvmc01 | grep '/3' | awk '{print $1}' | xargs kubectl logs -n onecloud -c host`

**Comment by shengxianli** [comment]
@zexi 请查收
[log.zip](https://github.com/yunionio/cloudpods/files/13293502/log.zip)

**Comment by zexi** [comment]
> @zexi 请查收 [log.zip](https://github.com/yunionio/cloudpods/files/13293502/log.zip)

@shengxianli 这个就是文档里面说的问题了，创建一个包含这个宿主机 ip 的子网就行了：
https://www.cloudpods.org/zh/docs/quickstart/allinone-private/#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA

```
[error 2023-11-08 07:15:46 hostinfo.(*SHostInfo).GetMasterNicIpAndMask(hostinfo.go:988)] MasterNic (*netutils2.SNetInterface)(nil)
[error 2023-11-08 07:15:46 hostinfo.(*SHostInfo).onFail(hostinfo.go:1068)] register failed: try create network: find_matched == false
[error 2023-11-08 07:15:46 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...
goroutine 1485 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x59
panic({0x2848820, 0x34be9d0})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0xc00017d800, {0x2848820?, 0x34be9e0?})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1070 +0xeb
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).tryCreateNetworkOnWire(0x5476f00?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1095 +0x565
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).fetchAccessNetworkInfo(0xc00017d800)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1128 +0x4a5
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc001124001?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1055 +0x1e
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x5c
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x65
[root@IT-Cloudpods ~]# 
```

<img width="1221" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/78817805-2b29-4ab8-b96b-462bcdb6cf8d">

**Comment by shengxianli** [comment]
@zexi 我恢复快照忘记建子网了，我重新跑下流程

**Comment by shengxianli** [comment]
@zexi 可以拉 多谢大牛
