### ISSUE TITLE
[求助/Help]双网卡管理口和业务口及rook+ceph的配置求助

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18583]
一，求助内容：
宿主机是2个网口：一个千兆网口和一个万兆网口，想规划千兆网口是管理口，万兆网口是业务口。
求助cloudpod和ceph的万兆网口的配置，使用万兆提高内部网络性能。

目前部署的情况是：
千兆网卡IP段：172.16.1.x，eno1网口
万兆网卡IP段：10.0.1.x，ens4网口

目前通过官方文档（https://www.cloudpods.org/zh/docs/setup/ha-ce/ 和https://www.cloudpods.org/zh/docs/setup/db-ha/ ）进行高可用部署v3.10.6，控制节点VIP是：172.16.1.100，数据库双主VIP是：172.16.1.10。

三台控制节点部署配置的IP是：172.16.1.8；172.16.1.9；172.16.1.10。
同时搭配了ceph，通过官方文档部署(https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/ )。
在web端增加块存储CEPH，配置的Ceph Mon Host是:172.16.1.6,172.16.1.11,172.16.1.16，这样ceph也是使用了千兆的网络。
<img width="902" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/648739a0-f7a4-4d7d-811d-75215d9ca0a5">

二，目前配置情况
1、Cloudpods已经配置好了万兆网络，在宿主机上` /etc/yunion/host.conf`增加好了配置：
```
ovn_encap_ip: 10.0.1.8
networks:
- eno1/br0/172.16.1.8
- ens4/br1/10.0.1.8
```

<img width="1028" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/3afaf840-26fe-47f5-b63e-dd2cb9482d6b">

2、rook+ceph的部署根据https://www.cloudpods.org/zh/blog/2021/10/09/rook-ceph-with-cloudpods/ 指导来部署完成和配置到cloudpod上。
Ceph客户端的配置`/etc/ceph/ceph.conf`内容是：
```
[global]
mon_host = 172.16.1.6:6789,172.16.1.11:6789,172.16.1.16:6789

[client.admin]
keyring = /etc/ceph/keyring
```

rook的k8s编排文件yaml内容里，有一个配置项没找到案例是如何配置双网络的，就是对应ceph的`public-network`和`cluster-network`
```
  network:
    # enable host networking
    provider: host
    # enable the Multus network provider
    #provider: multus
    #selectors:
      # The selector keys are required to be `public` and `cluster`.
      # Based on the configuration, the operator will do the following:
      #   1. if only the `public` selector key is specified both public_network and cluster_network Ceph settings will listen on that interface
      #   2. if both `public` and `cluster` selector keys are specified the first one will point to 'public_network' flag and the second one to 'cluster_network'
      #
      # In order to work, each selector value must match a NetworkAttachmentDefinition object in Multus
      #
      #public: public-conf --> NetworkAttachmentDefinition object name in Multus
      #cluster: cluster-conf --> NetworkAttachmentDefinition object name in Multus
    # Provide internet protocol version. IPv6, IPv4 or empty string are valid options. Empty string would mean IPv4
    #ipFamily: "IPv6"
    # Ceph daemons to listen on both IPv4 and Ipv6 networks
    #dualStack: false
```

三，请教：
1、rook+ceph如何配置双网络，ceph的`public-network`和`cluster-network`
2、cloudpod如上的配置是已经双网络优化了吗？还存在哪方面的配置待完善？
3、cloudpod里已经添加了ceph的存储配置，但是地址是172.16.1.x的千兆网络，如何对该配置进行修改（web页面没修改地方），配置为ceph的万兆网络，走万兆业务口。

谢谢！！

**Comment by swordqiu** [comment]
@chenjacken 
rook ceph使用分离的cluster network可以参考如下文档：

https://rook.github.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#use-hostnetwork-in-the-cluster-configuration

1.7修改rook-config-override参考：

https://rook.github.io/docs/rook/v1.7/ceph-advanced-configuration.html#custom-cephconf-settings

**Comment by chenjacken** [comment]
![image](https://github.com/yunionio/cloudpods/assets/935084/51bad259-a165-49c8-bed8-421969f12751)

谢谢。
在平台上已经配置了的块存储，Ceph Mon Host是:172.16.1.6,172.16.1.11,172.16.1.16，如何修改IP ？

**Comment by ioito** [comment]
目前api不支持修改，若实在要改，需要到yunioncloud数据库中的storages表里面找到这条记录，然后手动更改
