### ISSUE TITLE
[求助/Help] 纳管vmware系统报错

### ISSUE THREAD

**Issue by wang1cheng** [yunionio/cloudpods#18588]
docker compose 安装好系统后，纳管vmware报错如图，可以被其他管理平台纳管，端口telnet没有问题。
![image2023-11-7_17-11-57](https://github.com/yunionio/cloudpods/assets/17242040/8175b427-b7a5-4e94-af06-b19d33a1b1ec)

**Comment by wang1cheng** [comment]
docker里ping vmware 的IP不通，这网络需要怎么打通？

**Comment by zexi** [comment]
> docker里ping vmware 的IP不通，这网络需要怎么打通？

@wang1cheng 理论上 docker 会在本地创建 iptables NAT 规则，本机能访问的话，容器里面应该也能访问。
