### ISSUE TITLE
[求助/Help] web页新建虚拟机时，一直获取不到套餐规格

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#18593]
![无标题](https://github.com/yunionio/cloudpods/assets/4537805/2207e81d-ab26-4251-ad2d-5f45813bb24c)
web页新建本地IDC虚拟机时，一直获取不到套餐规格,一直提示数据加载中，请稍候。最后超时失败，查看数据库 show full processlist,显示语句如下：
| 2971638 | yunioncloud      | 172.29.4.20:50728   | yunioncloud      | Execute     |       5 | Sending data                                                                | SELECT COUNT(*) AS `count` FROM (SELECT `t423248811`.`attached_disk_count`, `t423248811`.`attached_disk_size_gb`, `t423248811`.`attached_disk_type`, `t423248811`.`cloudregion_id`, `t423248811`.`cpu_arch`, `t423248811`.`cpu_core_count`, `t423248811`.`created_at`, `t423248811`.`data_disk_max_count`, `t423248811`.`data_disk_types`, `t423248811`.`deleted`, `t423248811`.`deleted_at`, `t423248811`.`description`, `t423248811`.`enabled`, `t423248811`.`external_id`, `t423248811`.`gpu_attachable`, `t423248811`.`gpu_count`, `t423248811`.`gpu_max_count`, `t423248811`.`gpu_spec`, `t423248811`.`id`, `t423248811`.`imported_at`, `t423248811`.`instance_type_category`, `t423248811`.`instance_type_family`, `t423248811`.`is_emulated`, `t423248811`.`local_category`, `t423248811`.`md5`, `t423248811`.`memory_size_mb`, `t423248811`.`name`, `t423248811`.`nic_max_count`, `t423248811`.`nic_type`, `t423248811`.`os_name`, `t423248811`.`postpaid_status`, `t423248811`.`prepaid_status`, `t423248811`.`progress`, `t423248811`.`provider`, `t423248811`.`source`, `t423248811`.`status`, `t423248811`.`sys_disk_max_size_gb`, `t423248811`.`sys_disk_min_size_gb`, `t423248811`.`sys_disk_resizable`, `t423248811`.`sys_disk_type`, `t423248811`.`update_version`, `t423248811`.`updated_at`, `t423248811`.`zone_id` FROM `serverskus_tbl` AS `t423248811` WHERE (`t423248811`.`deleted` = 0) AND (`t423248811`.`is_emulated` = 0) AND (`t423248811`.`provider` =  'OneCloud' ) AND (`t423248811`.`enabled` = 1) AND (`t423248811`.`cloudregion_id` =  'default' ) AND (`t423248811`.`postpaid_status` =  'available' ) AND (((`t423248811`.`memory_size_mb` >  3584 ) AND (`t423248811`.`memory_size_mb` <=  4608 ))) AND (`t423248811`.`cpu_core_count` =  4 ) GROUP BY `t423248811`.`name`) AS `t423248820` |    0.000 |
统计一下serverskus_tbl表的行数竟然有649216行，不知道是什么原因怎么这么多，查看表内容如下图：
![无标题1](https://github.com/yunionio/cloudpods/assets/4537805/55648759-3dba-4f8f-9704-c5f5a07d47d8)

**Comment by hoganlxj** [comment]
@xxhacker 要过滤掉deleted=1的套餐 ，再看下

**Comment by xxhacker** [comment]
> deleted=1

查询出来为6073行

**Comment by xxhacker** [comment]
> 先执行下 `delete from serverskus_tbl where deleted=1`
> 数据库和cloudpods是否分离部署，数据库所在的机器cpu，内存是多少

数据库和cloudpods没有分开部署， 数据库为物理机24核32G

**Comment by ioito** [comment]
删除掉无用的套餐之后还剩多少

**Comment by xxhacker** [comment]
> 删除掉无用的套餐之后还剩多少

6073，除去provider=Aliyun，只有39行

**Comment by ioito** [comment]
那现在应该正常了吧，https://github.com/yunionio/cloudpods/pull/18594/files 这个是自动清理无用套餐，之前不会delete, 只会标识套餐deleted=1, 导致数据累积了

**Comment by xxhacker** [comment]
> https://github.com/yunionio/cloudpods/pull/18594/files

这个是在什么版本修复的，我使用的是3.10.4

**Comment by ioito** [comment]
v3.10.7   这个版本这周会发布
