### ISSUE TITLE
SSH报错[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18646]
使用SSH的时候 在没有输入账号密码的时候就报错，输入正确的也不行
![image](https://github.com/yunionio/cloudpods/assets/32296103/da87641c-393b-44c6-aeb6-1fa462323f25)

**Comment by zexi** [comment]
@shengxianli 请问使用的版本是 v3.10.6 还是 v3.10.7 ？

**Comment by shengxianli** [comment]
@zexi v3.10.5

**Comment by zexi** [comment]
@shengxianli 这个问题修复过，需要升级到 v3.10.7 版本，参考这个文档升级：https://www.cloudpods.org/zh/docs/setup/upgrade/

**Comment by shengxianli** [comment]
@zexi 好的多谢
