### ISSUE TITLE
启用 baremetal-agent error[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18705]
[root@it-cloudpods-online ~]# ocadm baremetal enable --node it-cloudpods-online  --listen-interface eth0
I1116 11:49:08.968353   17683 baremetal.go:119] Enable baremetal for node it-cloudpods-online
I1116 11:49:08.975987   17683 baremetal.go:135] Enable baremetal agent phase finished ...
<img width="884" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/ad8b211e-ea5e-4252-8280-f18c99246deb">

**Comment by zexi** [comment]
@shengxianli 请用 kubectl log 把任意2个启动失败的 baremetal-agent 的日志放上来

**Comment by shengxianli** [comment]
@zexi 大牛请查收 
[root@it-cloudpods-online ~]# kubectl logs -n onecloud default-baremetal-agent-changshajm-75989dd5db-qnxp6  -f --since 5m
[info 231116 04:10:12 loader.init.0(loader.go:28)] Redfish drivers loaded!
[info 231116 04:10:12 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/baremetal-agent.conf
[info 231116 04:10:12 options.ParseOptions(options.go:340)] Set log level to "info"
[info 2023-11-16 04:10:12 service.(*BaremetalService).StartService(service.go:53)] No cachepath, use default /opt/cloud/workspace/bm_image_cache
[info 2023-11-16 04:10:12 service.(*BaremetalService).StartService(service.go:57)] No BootIsoPath, use default /opt/cloud/workspace/bm_boot_iso
[info 2023-11-16 04:10:12 service.(*BaremetalService).StartService.func1(service.go:69)] auth complete
[info 2023-11-16 04:10:12 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-11-16 04:10:12 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-11-16 04:10:12 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-11-16 04:10:12 appsrv.NewApplication(appsrv.go:118)] App hostId: HL6M7Bc7wVOXzRU468-2zSgYFQs= (baremetal-agent,it-cloudpods-online,10.0.254.10)
2023/11/16 04:10:12 Allow hosts []
[info 2023-11-16 04:10:12 appsrv.(*Application).SetDefaultTimeout(appsrv.go:134)] adjust application default timeout to 60.000000 seconds
[info 2023-11-16 04:10:12 options.StartOptionManagerWithSessionDriver(manager.go:63)] OptionManager start to fetch service configs ...
[info 2023-11-16 04:10:12 options.optionsEquals(manager.go:118)] Options added: {"api_server":"https://10.0.254.10"}
[fatal 2023-11-16 04:10:12 service.(*BaremetalService).startAgent(service.go:99)] Start agent error: WaitIfaceIps: net.InterfaceByName: route ip+net: no such network interface
[root@it-cloudpods-online ~]# kubectl logs -n onecloud default-baremetal-agent-jinangs-7679c7d7db-t5pwh     -f --since 5m
[info 231116 04:09:53 loader.init.0(loader.go:28)] Redfish drivers loaded!
[info 231116 04:09:53 options.ParseOptions(options.go:318)] Use configuration file: /etc/yunion/baremetal-agent.conf
[info 231116 04:09:53 options.ParseOptions(options.go:340)] Set log level to "info"
[info 2023-11-16 04:09:53 service.(*BaremetalService).StartService(service.go:53)] No cachepath, use default /opt/cloud/workspace/bm_image_cache
[info 2023-11-16 04:09:53 service.(*BaremetalService).StartService(service.go:57)] No BootIsoPath, use default /opt/cloud/workspace/bm_boot_iso
[info 2023-11-16 04:09:53 service.(*BaremetalService).StartService.func1(service.go:69)] auth complete
[info 2023-11-16 04:09:53 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
[info 2023-11-16 04:09:53 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2023-11-16 04:09:53 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2023-11-16 04:09:53 appsrv.NewApplication(appsrv.go:118)] App hostId: HL6M7Bc7wVOXzRU468-2zSgYFQs= (baremetal-agent,it-cloudpods-online,10.0.254.10)
2023/11/16 04:09:53 Allow hosts []
[info 2023-11-16 04:09:53 appsrv.(*Application).SetDefaultTimeout(appsrv.go:134)] adjust application default timeout to 60.000000 seconds
[info 2023-11-16 04:09:53 options.StartOptionManagerWithSessionDriver(manager.go:63)] OptionManager start to fetch service configs ...
[info 2023-11-16 04:09:53 options.optionsEquals(manager.go:118)] Options added: {"api_server":"https://10.0.254.10"}
[fatal 2023-11-16 04:09:53 service.(*BaremetalService).startAgent(service.go:99)] Start agent error: WaitIfaceIps: net.InterfaceByName: route ip+net: no such network interface

**Comment by zexi** [comment]
> Start agent error: WaitIfaceIps: net.InterfaceByName: route ip+net: no such network interface

@shengxianli 要给每个对应 baremetal 的 configmap 设置服务运行监听的网卡名称 listen_interface ，这个错误是运行 baremetal-agent pod 对应节点上没有找到监听的网卡。

**Comment by shengxianli** [comment]
@zexi 请问怎么设置，对这方面不太懂

**Comment by zexi** [comment]
> @zexi 请问怎么设置，对这方面不太懂

@shengxianli 比如要修改 default-baremetal-agent-changshajm 的 listen_interface

```bash
# 执行下面命令修改 configmap
kubectl edit configmap -n onecloud default-baremetal-agent-changshajm

# 找到 listen_interface 的设置，改成那个节点需要监听的网卡
# 比如 default-baremetal-agent-changshajm 节点上需要让服务监听到 eth0 的网卡
# 就设置 listen_interface: eth0
```

改完后重启 default-baremetal-agent-changshajm 这个 deployment

```bash
kubectl rollout restart deployment -n onecloud default-baremetal-agent-changshajm
```

**Comment by shengxianli** [comment]
@zexi 现在pod正常了，
添加IPMI报错
<img width="422" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/43104328-4ff2-4d71-b515-eb19c9e828ed">

{
    "__reason__": {
        "reason": "no valid baremetal",
        "stage": "OnSyncConfigComplete"
    },
    "__stage__": "OnIpmiProbeComplete",
    "__status__": "error",
    "__task_name__": "BaremetalIpmiProbeTask"
}

这个pod日志

[root@it-cloudpods-online ~]# kubectl logs -n onecloud default-baremetal-agent-changshajm-686747b784-tcgmw    -f --since 5m
[error 2023-11-16 04:51:00 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"853b89e9"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:51:30 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"9ca785f8"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:52:00 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"3ca3e822"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:52:30 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"58d4b750"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:53:00 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"838052d4"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:53:30 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"a18fc4c1"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:54:00 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"6c7f8df2"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:54:30 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"2d03f3c7"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:55:00 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"de30335d"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
[error 2023-11-16 04:55:30 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: {"error":{"class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri https://10.0.254.10:8879","request":{"body":"{\"baremetalagent\":{\"access_ip\":\"10.0.254.10\",\"agent_type\":\"baremetal\",\"manager_uri\":\"https://10.0.25...4823-856b-bec6689afa50\"}}","headers":{"Content-Length":"237","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"baremetal","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"42ebd4b3"},"method":"POST","url":"https://default-region:30888/baremetalagents"}}}, retry after 30s...
^C

**Comment by zexi** [comment]
> "class":"DuplicateResourceError","code":409,"details":"Duplicate manager_uri [https://10.0.254.10:8879",](https://10.0.254.10:8879","request":{"body":"{%5C"baremetalagent%5C":{%5C"access_ip%5C":%5C"10.0.254.10%5C",%5C"agent_type%5C":%5C"baremetal%5C",%5C"manager_uri%5C":%5C"https//10.0.25...4823-856b-bec6689afa50%5C%22%7D%7D%22,%22headers%22:%7B%22Content-Length%22:%22237%22,%22Content-Type%22:%22application/json%22,%22User-Agent%22:%22yunioncloud-go/201708%22,%22X-Auth-Token%22:%22*%22,%22X-Yunion-Parent-Id%22:%22%22,%22X-Yunion-Peer-Service-Name%22:%22baremetal%22,%22X-Yunion-Remote-Addr%22:%22default-region:30888%22,%22X-Yunion-Span-Id%22:%220%22,%22X-Yunion-Span-Name%22:%22%22,%22X-Yunion-Strace-Debug%22:%22true%22,%22X-Yunion-Strace-Id%22:%229ca785f8%22%7D,%22method%22:%22POST%22,%22url%22:%22https://default-region:30888/baremetalagents%22%7D%7D%7D)

@shengxianli 这个报错是说已经有 10.0.254.10 的 baremetal-agent 节点注册了，所以现在这个节点注册不上去。

一个节点只能运行一个 baremetal-agent ，你是把 baremetal-agent 部署到不同节点的吗？

**Comment by shengxianli** [comment]
@zexi 我有点不太明白。cloudpods 现在是all in one的一台，然后按照城市建了一些可用区

**Comment by zexi** [comment]
> @zexi 我有点不太明白。cloudpods 现在是all in one的一台，然后按照城市建了一些可用区

@shengxianli 现在的架构是每个可用区里面，只能有一个节点部署 baremetal-agent ，用来管理这些可用区下面的物理机。

你现在只有一个节点，只能运行一个 baremetal-agent 。

**Comment by zexi** [comment]
@shengxianli 我觉得你应该不需要部署这么多 baremetal-agent ，只保留一个就行了。

**Comment by shengxianli** [comment]
@zexi 我是按照这个文档部署的https://www.cloudpods.org/zh/docs/setup/baremetal/，其它的是默认生成的，也没做什么操作
我现在需要怎么处理一下，是不是只保留这一个就行default-baremetal-agent-6cf48fb454-6q96f  ，其它要删掉
<img width="873" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/1ae609bc-1043-432e-bead-4213d4bee0db">

**Comment by zexi** [comment]
@shengxianli 感觉是你在 oc 里面添加自定义 zone 了，`kubectl get oc -n onecloud default -o yaml` ，把内容贴上来看下

**Comment by shengxianli** [comment]
@zexi 是的 我添加了
customZones:
  - tianjin
  - xianzhongjing
  - shanghai
  - lixinghang
  - wuhanapp
  - wuhanxfz
  - shenyang
  - xiandaxia
  - xianrenbao
  - zhengzhouhg
  - changshajm
  - jinangs
  - qingdao
  - dongyawangjingzhongxin
  devtool:

**Comment by zexi** [comment]
> @zexi 是的 我添加了，这样装系统的时候方便一些 customZones:
> 
> * tianjin
> * xianzhongjing
> * shanghai
> * lixinghang
> * wuhanapp
> * wuhanxfz
> * shenyang
> * xiandaxia
> * xianrenbao
> * zhengzhouhg
> * changshajm
> * jinangs
> * qingdao
> * dongyawangjingzhongxin
>   devtool:
> 
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/32296103/283347977-fe213f94-6b7c-4892-aace-26637dd62c31.png">

@shengxianli 如果不是多可用区私有云部署，不要在 oc 里面设置这个参数，这会影响 baremetal-agent 和 host 服务的部署的，如果只是模拟的多可用区，直接在前端添加就行了。

把 oc 里面的 customZones: 去掉，再把其他的 baremetal-agent 删掉，就保留第一个就行了。

**Comment by shengxianli** [comment]
@zexi 哦哦 现在每个可用去下面都是esxi节点。kubectl -n onecloud delete pods 使用这个命令删除就行是吧

**Comment by zexi** [comment]
> @zexi 哦哦 现在每个可用去下面都是esxi节点。kubectl -n onecloud delete pods 使用这个命令删除就行是吧

@shengxianli 要把对应的  deployment 也删掉，`kubectl delete deployment -n onecloud`
