### ISSUE TITLE
allinone方式部署报错

### ISSUE THREAD

**Issue by wang1cheng** [yunionio/cloudpods#18708]
![image2023-11-16_16-44-24](https://github.com/yunionio/cloudpods/assets/17242040/6ceb0e5e-9fe7-470d-8a33-d22b7134cd9d)
请问上面报错咋回事？如何解决？

**Comment by zexi** [comment]
@wang1cheng 应该是 ansible 版本不兼容的问题，刚合并了一个 PR 修复此问题，更新 ocboot 的代码到最新的 release/3.10 分支，然后再重新执行 run.py 试试。

**Comment by wang1cheng** [comment]
我用的3.11版本，请问3.11版本也修复了吗

**Comment by zexi** [comment]
> 我用的3.11版本，请问3.11版本也修复了吗

@wang1cheng 3.11 还没有发布，我刚才把修复的 PR cherry pick 到 release/3.11 分支了，你更新一下试试。

不过还是建议使用 release/3.10 分支来部署，3.11 是正在开发的一个版本。

**Comment by wang1cheng** [comment]
请问现在是否有只安装云管系统的yaml安装包，对于已经有k8s环境的可以省去这些安装步骤，只安装管理平台。
目前我换回3.10版本安装，还是报同样的问题，要先创建coredns的deployment资源才能打patch吧，目前我是把k8s的相关pod创建起来了，没看到coredns和calico的资源

**Comment by wang1cheng** [comment]
docker-compose方式已部署过了，实际使用确实需要管理vmware。ocadm init流程是不是就是把k8s部署好，且把coredns和calico部署好？目前k8s的控制节点服务已安装好，好像重装到这步就跳过这个init这步了



---原始邮件---
发件人: "Zexi ***@***.***&gt;
发送时间: 2023年11月16日(周四) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] allinone方式部署报错 (Issue #18708)




  
请问现在是否有只安装云管系统的yaml安装包，对于已经有k8s环境的可以省去这些安装步骤，只安装管理平台。 目前我换回3.10版本安装，还是报同样的问题，要先创建coredns的deployment资源才能打patch吧，目前我是把k8s的相关pod创建起来了，没看到coredns和calico的资源
  
@wang1cheng 目前还有另外两种只安装云管的方式：
  
使用 helm 部署到已有 k8s: https://www.cloudpods.org/zh/docs/quickstart/cmp/k8s/
 
使用 docker compose 部署：https://www.cloudpods.org/zh/docs/quickstart/cmp/docker-compose/
  
但目前这两种方式都无法管理 VMware ，因为目前对 VMWare 的磁盘管理依赖依赖内核 nbd 模块，该模块无法在 docker compose 里面加载。如果是需要对 VMWare 管理，请使用 Ocboot 安装 的方式部署。如果是只管理其他云平台，可以用以上的方式部署。

**Comment by zexi** [comment]
> docker-compose方式已部署过了，实际使用确实需要管理vmware。ocadm init流程是不是就是把k8s部署好，且把coredns和calico部署好？目前k8s的控制节点服务已安装好，好像重装到这步就跳过这个init这步了
> […](#)
> ---原始邮件--- 发件人: "Zexi ***@***.***&gt; 发送时间: 2023年11月16日(周四) 晚上8:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yunionio/cloudpods] allinone方式部署报错 (Issue #18708) 请问现在是否有只安装云管系统的yaml安装包，对于已经有k8s环境的可以省去这些安装步骤，只安装管理平台。 目前我换回3.10版本安装，还是报同样的问题，要先创建coredns的deployment资源才能打patch吧，目前我是把k8s的相关pod创建起来了，没看到coredns和calico的资源 @wang1cheng 目前还有另外两种只安装云管的方式： 使用 helm 部署到已有 k8s: https://www.cloudpods.org/zh/docs/quickstart/cmp/k8s/ 使用 docker compose 部署：https://www.cloudpods.org/zh/docs/quickstart/cmp/docker-compose/ 但目前这两种方式都无法管理 VMware ，因为目前对 VMWare 的磁盘管理依赖依赖内核 nbd 模块，该模块无法在 docker compose 里面加载。如果是需要对 VMWare 管理，请使用 Ocboot 安装 的方式部署。如果是只管理其他云平台，可以用以上的方式部署。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

@wang1cheng 如果要管理 VMware 那就必须用 ocboot 部署了。

如果之前装过，就会跳过 init 的步骤，需要先执行 `kubeadm reset -f` 把节点重置后，然后重新运行 `run.py` 脚本重装下。

**Comment by wang1cheng** [comment]
嗯，重新安装，现在是coredns的pod处于pending状态，k8s的node状态为notready，日志看是cni配置未初始化，这里是应该先安装calico再安装coredns吗？没看到calico的pod

**Comment by zexi** [comment]
> 嗯，重新安装，现在是coredns的pod处于pending状态，k8s的node状态为notready，日志看是cni配置未初始化，这里是应该先安装calico再安装coredns吗？没看到calico的pod

@wang1cheng ocboot 脚本运行完了吗？calico 这些组件 ocboot 是会自动安装的。请问是在什么 linux 发行版上安装的？我这边也测试下，因为我们在 Centos 7 、Debian 10/11 和 Ubuntu 22.04 测试没有出现过这个问题。

**Comment by wang1cheng** [comment]
用的是centos7.6系统，是这样的：看安装的k8s版本比较老，我就把ocadm里关于k8s版本修改为1.20.5。ocboot脚本运行是报错信息看，应该是代码调用k8s的daemonset的接口版本"extensions/v1beta1"和使用的k8s版本不匹配导致的。这个是不是要下载匹配的vendor再编译下就可以了？

**Comment by zexi** [comment]
> 我就把ocadm里关于k8s版本修改为1.20.5。ocboot脚本运行是报错信息看，应该是代码调用k8s的daemonset的接口版本"extension

@wang1cheng 目前我们没有测试 1.20.5 的 k8s ，要改成这个版本要适配的地方还是比较多的，建议你先用我们提供的 1.15 的版本，这个是测试最多的。

如果你一定要使用高版本 k8s，也不建议改动 ocadm ，我建议基于 ubuntu 22.04 先把高版本 k8s 部署起来，因为 ubuntu 默认就有 nbd 的驱动，然后再使用 helm 参考这个文档 https://www.cloudpods.org/zh/docs/quickstart/cmp/k8s/ 把服务部署进去，这样应该就能管理  VMware  了。

但以上的操作我不能保证一定 work ，可能又其他想不到的问题。如果是想稳定使用不折腾，就直接用我们提供的版本就行了。

**Comment by wang1cheng** [comment]
有计划使用高版本的k8s吗？ 我申请个阿里云虚机的话，能连公网，使用你们的版本是不是安装就顺畅点

**Comment by zexi** [comment]
> 有计划使用高版本的k8s吗？ 我申请个阿里云虚机的话，能连公网，使用你们的版本是不是安装就顺畅点

@wang1cheng 有计划，现在正在做高版本的 k8s 支持，计划是用更轻量级的 k3s 替换掉底层的 k8s 。

开源版本需要连公网部署。
