### ISSUE TITLE
安装物理机报错[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18703]
大神们这个怎么解决啊
fatal: [10.1.18.40]: FAILED! => {"changed": false, "msg": "No package matching 'kernel-5.4.130-1.yn20221208.el7' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-5.4.130-1.yn20221208.el7' found available, installed or updated"

**Comment by swordqiu** [comment]
@shengxianli 这是在什么操作系统上安装哪个版本的Cloudpods？

**Comment by shengxianli** [comment]
@swordqiu centos7 虚拟机

**Comment by swordqiu** [comment]
@shengxianli  我看 iso.yunion.cn 上的rpm是 https://iso.yunion.cn/centos/7/3.10/aarch64/kernel-5.4.199-200.yn20221212.el7.aarch64.rpm ，感觉你的ocboot的版本不太对。请确保是最新的 release/3.10 分支。
