### ISSUE TITLE
[求助/Help]高可用部署报错，DB HA

### ISSUE THREAD

**Issue by labose** [yunionio/cloudpods#18717]
执行高可用部署出现错误，DB IP用的keepalived DB VIP
报错出现步骤：
TASK [primary-master-node/setup_cloud : Create essential services, wait for a fe         w minutes. You can open another terminal and execute `kubectl get pods -n oneclo         ud -w` to watch the process.] ***

报错内容：FAILED! => {"attempts": 6, "changed": true, "cmd": "/opt/yunion/bin/ocadm cluster create  --wait", "delta": "0:30:00.197236", "end": "2023-11-16 22:08:10.913197", "msg": "non-zero return code", "rc": 1, "start": "2023-11-16 21:38:10.715961", "stderr": "[info 231116 21:38:10 onecloud.WaitOnecloudDeploymentUpdated.func1(operator.go:155)] Wait: glance: current status is nil, maybe deployment not created\n

TASK [primary-master-node/setup_cloud : Create onecloud web login user admin] ***
fatal: [192.168.15.5]: FAILED! => {"changed": true, "cmd": "eval $(/opt/yunion/bin/ocadm cluster rcadmin)\n/opt/yunion/bin/climc user-create --password admin@123 --enabled admin\n", "delta": "0:00:00.987537", "end": "2023-11-16 22:08:26.032750", "msg": "non-zero return code", "rc": 1, "start": "2023-11-16 22:08:25.045213", "stderr": "{\"error\":{\"class\":\"WrongPassword\",\"code\":401,\"details\":\"Authenticate: usrExt.VerifyPassword: WrongPassword\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.15.12:30500/v3/auth/tokens\"}}}", "stderr_lines": ["{\"error\":{\"class\":\"WrongPassword\",\"code\":401,\"details\":\"Authenticate: usrExt.VerifyPassword: WrongPassword\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.15.12:30500/v3/auth/tokens\"}}}"], "stdout": "", "stdout_lines": []}

TASK [primary-master-node/setup_cloud : Update onecloud user admin password to admin@123] ***
fatal: [192.168.15.5]: FAILED! => {"changed": true, "cmd": "eval $(/opt/yunion/bin/ocadm cluster rcadmin)\n/opt/yunion/bin/climc user-update --password admin@123 --enabled --allow-web-console admin\n", "delta": "0:00:00.940747", "end": "2023-11-16 22:08:28.594690", "msg": "non-zero return code", "rc": 1, "start": "2023-11-16 22:08:27.653943", "stderr": "{\"error\":{\"class\":\"WrongPassword\",\"code\":401,\"details\":\"Authenticate: usrExt.VerifyPassword: WrongPassword\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.15.12:30500/v3/auth/tokens\"}}}", "stderr_lines": ["{\"error\":{\"class\":\"WrongPassword\",\"code\":401,\"details\":\"Authenticate: usrExt.VerifyPassword: WrongPassword\",\"request\":{\"body\":\"{\\\"auth\\\":{\\\"context\\\":{\\\"source\\\":\\\"cli\\\"},\\\"identity\\\":{\\\"methods\\\":[\\\"password\\\"],\\\"password\\\":{\\\"user\\\":{\\\"name\\\":\\\"s...ult\\\"},\\\"name\\\":\\\"system\\\"}}}}\",\"headers\":{\"Content-Length\":\"209\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\"},\"method\":\"POST\",\"url\":\"https://192.168.15.12:30500/v3/auth/tokens\"}}}"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
192.168.15.5              : ok=148  changed=67   unreachable=0    failed=1    skipped=34   rescued=0    ignored=2
192.168.15.6              : ok=196  changed=68   unreachable=0    failed=0    skipped=45   rescued=0    ignored=0
192.168.15.7              : ok=192  changed=67   unreachable=0    failed=0    skipped=45   rescued=0    ignored=0

[部署信息.txt](https://github.com/yunionio/cloudpods/files/13386919/default.txt)

**Comment by labose** [comment]
执行kubectl get pods -n onecloud -w出现以下报错
error: the server doesn't have a resource type "pods"

**Comment by zexi** [comment]
> 执行kubectl get pods -n onecloud -w出现以下报错 error: the server doesn't have a resource type "pods"

@labose 
```bash
export KUBECONFIG=/etc/kubernets/admin.conf
```
设置这个环境变量后，再执行看看。

这个环境是否重装过？我看现在的报错是密码不对

**Comment by labose** [comment]
我改过DBHA_KA_AUTH，忘了
