### ISSUE TITLE
[求助/Help]创建虚拟机 配置透传设备GPU,无法启动虚拟机

### ISSUE THREAD

**Issue by chaiBitch** [yunionio/cloudpods#18752]
os :  ubuntu 2204
version: v3.7.10

创建虚拟机时，配置了透传设备GPU
虚拟机在显示启动后，一会变成 关机 。 点击开机依然如此

如不配置透传设备， 则正常

启动日志
<html>
<body>

  | vm01- | 关机 | 192.168.30.220(私有) |   | Default | 按量付费 |   | system
-- | -- | -- | -- | -- | -- | -- | -- | --

<br class="Apple-interchange-newline">
</body>
</html>

![1700635260582](https://github.com/yunionio/cloudpods/assets/31441052/8cf2d4ae-ebe0-43cb-98e0-0431e682ef49)

![1700635353402](https://github.com/yunionio/cloudpods/assets/31441052/28a0814c-a01b-4cb0-8fe0-af2a0732e988)

**Comment by chaiBitch** [comment]
追加日志：

starting=>ready: monitor disconnect read tcp 127.0.0.1:39826->127.0.0.1:56118: read: connection reset by peer

**Comment by zexi** [comment]
@chaiBitch 麻烦把那个虚拟机所在的节点的 default-host-xxx pod 日志放上来，命令如下：

```bash
# 找到对应节点的 pod 
kubectl get pods -n onecloud -o wide | grep 'host' | egrep -v 'deployer|health|image|bastion'

# 查看日志
kubectl logs -n onecloud -c host default-host-xxx
```

**Comment by chaiBitch** [comment]
o 2023-11-22 07:35:07 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:583)] VM started vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) ...
[info 2023-11-22 07:35:07 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:589)] Async start server vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) success!
[info 2023-11-22 07:35:08 monitor.(*QmpMonitor).read(qmp.go:182)] QMP Read vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"QMP": {"version": {"qemu": {"micro": 0, "minor": 2, "major": 4}, "package": "2023-07-20_04:06:34@buildkitsandbox@"}, "capabilities": ["oob"]}}
[info 2023-11-22 07:35:08 guestman.(*SKVMGuestInstance).onMonitorConnected(qemu-kvm.go:994)] Monitor connected ...
[info 2023-11-22 07:35:08 monitor.(*QmpMonitor).write(qmp.go:260)] QMP Write vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"execute":"qmp_capabilities"}
[info 2023-11-22 07:35:08 monitor.(*QmpMonitor).write(qmp.go:260)] QMP Write vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"execute":"query-version"}
[info 2023-11-22 07:35:08 monitor.(*QmpMonitor).read(qmp.go:232)] Scan over vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) ...
[info 2023-11-22 07:35:08 monitor.(*QmpMonitor).read(qmp.go:235)] QMP Disconnected vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): read tcp 127.0.0.1:52740->127.0.0.1:56122: read: connection reset by peer
[error 2023-11-22 07:35:08 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1348)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 on Monitor Disconnect reason: read tcp 127.0.0.1:52740->127.0.0.1:56122: read: connection reset by peer
[info 2023-11-22 07:35:08 guestman.(*SKVMGuestInstance).CleanStartupTask(qemu-kvm.go:1499)]f2b125af-5199-47f9-8fc3-2a63dde3a8c6: Clean startup task ... no task
[info 2023-11-22 07:35:09 guestman.(*SKVMGuestInstance).clearCgroup(qemu-kvm.go:1450)] cgroup destroy 0
[info 2023-11-22 07:35:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 805f5c POST /write?db=telegraf (192.168.30.218:47882) 18.35ms
[info 2023-11-22 07:36:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 dd263a POST /write?db=telegraf (192.168.30.218:61844) 17.28ms
[info 2023-11-22 07:37:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 cd3416 POST /write?db=telegraf (192.168.30.218:54654) 16.04ms
[info 2023-11-22 07:38:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 b36383 POST /write?db=telegraf (192.168.30.218:13198) 17.41ms
[info 2023-11-22 07:39:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 18a6a9 POST /write?db=telegraf (192.168.30.218:48408) 14.13ms
[info 2023-11-22 07:40:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 86d482 POST /write?db=telegraf (192.168.30.218:20132) 17.87ms
[info 2023-11-22 07:41:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 5a0b76 POST /write?db=telegraf (192.168.30.218:39240) 16.80ms
[info 2023-11-22 07:42:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 b6d2fb POST /write?db=telegraf (192.168.30.218:13068) 18.14ms
[info 2023-11-22 07:43:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 de5564 POST /write?db=telegraf (192.168.30.218:12994) 16.32ms
[info 2023-11-22 07:43:40 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 200 130d32-ec462d-b1d4d1 POST /servers/f2b125af-5199-47f9-8fc3-2a63dde3a8c6/start (10.40.253.43:33408:compute_v2) 2.45ms
[info 2023-11-22 07:43:41 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:558)] Use vnc port 23
[error 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:802)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:802)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:802)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 start monitor failed, can't get qmp monitor port or monitor path
[error 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:802)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 start monitor failed, can't get qmp monitor port or monitor path
[info 2023-11-22 07:43:42 monitor.(*SBaseMonitor).connect(monitor.go:298)] Connect tcp 127.0.0.1:56123 success
[info 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:583)] VM started vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) ...
[info 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:589)] Async start server vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) success!
[info 2023-11-22 07:43:42 monitor.(*QmpMonitor).read(qmp.go:182)] QMP Read vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"QMP": {"version": {"qemu": {"micro": 0, "minor": 2, "major": 4}, "package": "2023-07-20_04:06:34@buildkitsandbox@"}, "capabilities": ["oob"]}}
[info 2023-11-22 07:43:42 guestman.(*SKVMGuestInstance).onMonitorConnected(qemu-kvm.go:994)] Monitor connected ...
[info 2023-11-22 07:43:42 monitor.(*QmpMonitor).write(qmp.go:260)] QMP Write vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"execute":"qmp_capabilities"}
[info 2023-11-22 07:43:42 monitor.(*QmpMonitor).write(qmp.go:260)] QMP Write vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): {"execute":"query-version"}
[info 2023-11-22 07:43:43 monitor.(*QmpMonitor).read(qmp.go:232)] Scan over vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6) ...
[info 2023-11-22 07:43:43 monitor.(*QmpMonitor).read(qmp.go:235)] QMP Disconnected vm01(f2b125af-5199-47f9-8fc3-2a63dde3a8c6): read tcp 127.0.0.1:56714->127.0.0.1:56123: read: connection reset by peer
[error 2023-11-22 07:43:43 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1348)] Guest f2b125af-5199-47f9-8fc3-2a63dde3a8c6 on Monitor Disconnect reason: read tcp 127.0.0.1:56714->127.0.0.1:56123: read: connection reset by peer
[info 2023-11-22 07:43:43 guestman.(*SKVMGuestInstance).CleanStartupTask(qemu-kvm.go:1499)]f2b125af-5199-47f9-8fc3-2a63dde3a8c6: Clean startup task ... no task
[info 2023-11-22 07:43:44 guestman.(*SKVMGuestInstance).clearCgroup(qemu-kvm.go:1450)] cgroup destroy 0
[info 2023-11-22 07:44:12 appsrv.(*Application).ServeHTTP(appsrv.go:288)] o_apV2K0M_WG27CkQJc0HgPp8T8= 204 1bca20 POST /write?db=telegraf (192.168.30.218:44626) 17.60ms

**Comment by zexi** [comment]
@chaiBitch 这个日志不全，需要全部导出来放上来看下，可以在执行 `kubectl logs .... > /tmp/host.log` 从定向到 /tmp/host.log ，然后把这个文件放上来看下

**Comment by chaiBitch** [comment]
[host.log](https://github.com/yunionio/cloudpods/files/13435596/host.log)

其中含有  gpu 绑定失败的错误日志

**Comment by wanyaoqi** [comment]
@chaiBitch 可以看下 /opt/cloud/workspace/servers/logs/<SERVER_ID> 这个文件的，这个是虚机qemu启动日志

**Comment by chaiBitch** [comment]
以下是配置了透传gpu的虚拟机启动的报错日志
请问按照常规方法配置 GPU-KVM 直通可以解决吗 ，cloudpods有没有内置什么机制



/d5408c57-55ce-47cd-89d2-c58ab928333f/pid', b'-chardev', b'socket,id=qga0,server,nowait,path=/opt/cloud/workspace/servers/d5408c57-55ce-47cd-89d2-c58ab928333f/qga.sock', b'-device', b'virtserialport,bus=virtio-serial0.0,chardev=qga0,name=org.qemu.guest_agent.0', b'-object', b'rng-random,id=rng0,filename=/dev/urandom', b'-device', b'virtio-rng-pci,id=random0,bus=pcie.0,addr=0x09,max-bytes=1024,period=1000,rng=rng0', b'-chardev', b'pty,id=charserial0', b'-device', b'isa-serial,chardev=charserial0,id=serial0', b'-device', b'pvpanic,id=pvpanic,ioport=0x505']
char device redirected to /dev/pts/3 (label charserial0)
qemu-system-x86_64: -device vfio-pci,id=dev_82_00.0,bus=pci.3,addr=0x00,multifunction=off,host=82:00.0: vfio 0000:82:00.0: failed to open /dev/vfio/102: No such file or directory

**Comment by wanyaoqi** [comment]
@chaiBitch 看起来是 gpu没有配置好 vfio驱动导致的，确认一下 gpu驱动是否是 vfio
