### ISSUE TITLE
[求助/Help]求没有bmc带外管理的裸机管理和装机流程方法

### ISSUE THREAD

**Issue by ccbutcc** [yunionio/cloudpods#18750]
机器含有 PXE ,不支持 带外管理， 寻求裸机管理和装机的方法

**Comment by zexi** [comment]
和管理有 BMC 的带外物理机流程差不多，区别在于创建物理机记录的时候不要填写 IPMI 信息，并且选择不要探测带外信息，大概流程如下：

1. 先用命令行在平台创建一条物理机的记录：

```bash
# 假设 pxe 网卡的 mac 地址是：2c:ea:7f:af:4c:87
# pxe 分配的地址是 10.2.128.1
# 要管理的物理机名称是：no-ipmi-host
climc host-create --access-ip 10.2.128.1 --no-probe no-ipmi-host 2c:ea:7f:af:4c:87
```

2. 设置物理机 uefi pxe 启动，平台的 baremetal-agent 服务发现来自 2c:ea:7f:af:4c:87 的 pxe 请求后，就会下发 pxe ramfs 系统回去，等待物理机进入 pxe 系统

3. 进入 pxe ramfs 系统后，物理机就会进入“准备中”的状态，此时会探测上报硬件信息，等状态变为“运行中”，就可以安装操作系统了，需要注意安装操作系统的镜像需要是  UEFI 的 qcow2 镜像。

**Comment by chaiBitch** [comment]
状态始终在准备中，是何原因 ，需要排查那个组件
baremetal-agent 日志
[info 2023-11-30 09:00:56 pxe.(*dhcpRequest).fetchConfig(dhcp.go:207)] DHCP relay from 192.168.30.43(0.0.0.0) for 00:10:e2:01:01:72, find matched networks: &types.SNetworkConfig{GuestDhcp:"", GuestGateway:"192.168.30.1", GuestIpStart:"192.168.30.43", GuestIpEnd:"192.168.30.43", GuestIpMask:21, Id:"4f1e4d80-bd3c-4c07-88c2-cd64b00822b8", IsEmulated:false, IsPublic:false, IsSystem:false, Name:"adm01", ServerType:"baremetal", Status:"available", ProjectId:"95645944bb51443d8878488245e1aad9", VlanId:1, WireId:"321a19b4-b351-4a97-88b2-b521cb91125a"}
[info 2023-11-30 09:00:56 appsrv.(*Application).ServeHTTP(appsrv.go:288)] tHgnVYTVlhZCs16Ukg2OXOOuMUQ= 200 a36e0b-70678a POST /baremetals/aca23e38-af9e-40f0-8ff4-93541f93f96c/sync-config (10.40.96.75:50056:compute_v2) 0.21ms
[info 2023-11-30 09:00:56 baremetal.(*SBaremetalManager).fetchBaremetal(manager.go:211)] Baremetal aca23e38-af9e-40f0-8ff4-93541f93f96c update success
[info 2023-11-30 09:00:56 modules.TaskComplete(task.go:34)] Sync task 935c7d78-c5c9-45b8-86d0-02b237fe904d complete succ
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-01-00-10-e2-01-01-72" error: stat /opt/cloud/yunion/baremetal/grub.cfg-01-00-10-e2-01-01-72: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81EDA" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81EDA: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81ED" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81ED: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81E" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81E: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A81" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A81: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A8" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A8: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0A" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0A: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C0" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C0: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg-C" error: stat /opt/cloud/yunion/baremetal/grub.cfg-C: no such file or directory
[error 2023-11-30 09:00:56 pxe.(*TFTPHandler).sendFile(tftp.go:110)] TFTP stat file "/opt/cloud/yunion/baremetal/grub.cfg" error: stat /opt/cloud/yunion/baremetal/grub.cfg: no such file or directory
[info 2023-11-30 09:00:56 baremetal.(*SBaremetalInstance).NeedPXEBoot(manager.go:971)] Check task BaremetalServerPrepareTask, server  NeedPXEBoot: true(Task BaremetalServerPrepareTask need PXE boot)
[info 2023-11-30 09:00:56 baremetal.(*SBaremetalInstance).NeedPXEBoot(manager.go:971)] Check task BaremetalServerPrepareTask, server  NeedPXEBoot: true(Task BaremetalServerPrepareTask need PXE boot)

**Comment by zexi** [comment]
@chaiBitch 看下机器启动界面，有没有进入 PXE 启动界面，如果进入后，看下有没有收到返回的 grub 配置，如果收到的话应该会进入一个 grub 的引导界面，然后就进入 pxe ramfs 系统了。
这个报错看起来是要管理的那台机器没有进入 pxe ramfs 系统导致的，这个要先看下要管理的那台机器现在处于什么状态。

**Comment by chaiBitch** [comment]
系统正常进入， 但状态似乎上报失败！  curL 错误， 请问这个步骤需要人干预吗，  这个系统的默认密码是多少

![1701409923572](https://github.com/yunionio/cloudpods/assets/31441052/bac5da98-859b-4398-a3bb-32b6f7eeae37)

**Comment by zexi** [comment]
@chaiBitch 如果 curl 失败的话，默认密码就是：mosbaremetal
可以登录进去看下网卡获取 ip 情况，有可能是网卡没有驱动之类的问题导致的，还有可能是 dhcp 没有配置到正确的网络，导致 curl baremetal-agent 的地址导致的。

需要按上面的方向排查下问题。

**Comment by zexi** [comment]
@chaiBitch yunionos 里面应该没有这个网卡的驱动，用 `lspci -v` 看下这个网卡用的什么驱动？我查了下好像是  r8168 ，麻烦你那边确认下

**Comment by zexi** [comment]
@chaiBitch 用下面命令升级 baremetal-agent deployment，然后重新 pxe 启动服务器试试：

```bash
kubectl set image -n onecloud deployment/default-baremetal-agent *=registry.cn-beijing.aliyuncs.com/yunionio/baremetal-agent:v3.10-lzx-r8169
```

**Comment by chaiBitch** [comment]
启动后状态仍然一直是准备中，    可以用默认密码进入 ramfs系统，  检查网络只有 lo 网卡，  应该还是缺少网卡驱动


在ubuntu 下， 该机器对应的网卡信息： 
```
root@30-46:~# ethtool -i  enp8s0
driver: r8169
version: 5.15.0-89-generic
firmware-version: rtl8168h-2_0.0.2 02/26/15
expansion-rom-version: 
bus-info: 0000:08:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

**Comment by zexi** [comment]
@chaiBitch 进入 ramfs 系统后，看下 dmesg 有没有报错？

**Comment by zexi** [comment]
@chaiBitch 另外进入 ramfs 系统后，手动加载内核驱动后，再看下 dmesg 有没有报错？

```
modprobe r8169

dmesg
```

**Comment by chaiBitch** [comment]
你好，没有明显的报错。

```4.6280031hid-generic0003:C0F4:09F0 0002:unknown mainitemtam oxt4.6280091hid-generic0003:COF4:09F0.0002:tag Ox0unknownmainitem4.6280141hid-generictag 0x00003:COF4:09F0.0002itemunknoummain4.6280201hid-generic0003:COF4:09F0.0002:mainitem0x0tagunknoun6280261hid-genericunknown0003:COF4:09F00002:tag0x0mainitem4.6280311hid-generic0003:COF4:09FO0x0002:unknownmainitemtag4.6280371hid-generic0003:COF4:09F00002mainitemtag0xunknow4.6609661hid-genericitemtag0003:COF4:09F0.0002Oxunknowmain4.6609721hid-generic0x00003:COF4:09F0.0002:unknownmainitemtag4.6609771hid-generic0x0003:COF4:09F0.0002unknownmainitemtaghid-generic4.66098310x00003:COF4:09F0.0002:maintagunknownitem46609891hid-generic0003:COF4:09F0.0002unknownmaintagOxitem4.6609941hid-generic0003:COF4:09F0.0002:0x0unknown mainitemtag4.6610001hid-generic 0003:COF4:09F0.0002: unbalanced collection at end of report descriptionhid-generic:4.66109?1probe of0003:COF4:09F0.0002 failed with error -224.6793961IPMI messagehandler: uersion 39 .24.691112]ipmidevice interface4.709164]ipmi si:IPMI System Interface driver4.711439]ipmi si:Unable to find any System Interface(s)4.7642721ipmi si:IPMI System Interface driver47667271Unable to find any Sustem interfacets)ipmi si:4.9769961registeredrface driver usbserial genericusbcore!4.9825861wshscrialeru8 Sar1n00o0'oot inegdsregisteredfor generic5.06291915.1132171Fusion MPT base driver3.0420omittostone aly rtts ot 20mptctl:Registered with Fusion MPT base drivermptetl :nkdevsmptetletefme oramanou10n3?0lgmored100102hpsa: unknown parctibata iuars inp.3.00loadedini.c'weic im DIABLE MINBL is disabled. uplicate in neasurenc5 5839051fuse:17.37)doutceamaoo6.2061981wi18 2080601deuice-mapper :"ouent4,27saonott!·22022-07-28) initialised: dm-deueleredhat.cor```

**Comment by chaiBitch** [comment]
没有明显报错：


`4.628003] hid-generic0003:COF4:09F0.0002:unknoun mainitem tagox04.6280091hid-generic0003:COF4:09F0.0002:unknownmainitem taq 0x0.628014] hid-generic0003:COF4:09F00002item tag0x0unknownmain.6280201hid-generic0003:COF4:09FO0002tag0x0unknown main item4.6280261hid-generic0003:COF4:09FO0002maintag 0x0unknownitem4.628031]hid-generic0003:COF4:09FO0002tag ox0unknownmainitemhid-generic4.62803710003:COF4:09F00002tag Ox0unknoumainitem46609661hid-generic0003:COF4:9FO.0002mainitemtag 0x0uknown4.6609721hid-generic0003:COF4:09FOmain0x00002itemtagunknoun4.6609771hid-generic0003:COF4:09FOitem0x00002:unknownmaintag4.6609831hid-generic0003:COF4:09F0.0002:item0xounknownmaintag46609891hid-generic0003:COF4:09FOtag0x0000z:mainitemunknown4.6609941hid-generic0003:COF4:09F0.0002:Ox0unknown mainitemtag0003:COF4:09F0.0002: unbalanced collection at end of report description4.6610001hid-generic4.6610971hid-generic:probe of 0003:COF4:09FO .0002 failed with error-22IPMI message4.6793961handler :uersion 39.24.691112]ipmideviceinterface4.7091641ipmi si:IPMISustem Interface driver4.7114391ipmi si:Unable to find any System Interface(s)ipmi si:4.7642721IPMI Sustem Interface driver4.7667271ipmi si:Unable to find anu Sustem Interface(s)4.9769961usbcore:registered new interface driver usbserial generic4.9825861usbserial: USB Serial support registered for genericmpt3sas uersion 43.100 .0000 loaded5.06291915.1132171Fusion MPT base driver 3.04.205Copyright (c)1999-2008 LSI Corporation.1189951Fusion MPT misc device (ioctl) driuer 3.04.205.12667515.1326191mptctl: Registered with Fusion MPT base driver5.1385191mptctl: /deu/mptctl e (major,minor=10,220)eter shpsa allow any’ ignoredhpsa : unknown paramlibata version 3.00 loadedfuse: init(API version ?.37)6.2061981core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurementrdcuracamanrchetoro0 willnotbe6.218060]device-mapper:(2022-07-28) initialised: dm-develeredhat.con`

**Comment by zexi** [comment]
@chaiBitch `modprobe r8169` 和 lsmod 看下有这个驱动吗？
