### ISSUE TITLE
[BUG]terraform-provider-cloudpods 已经不适合当前的cloudpods了

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#18759]
**问题描述/What happened**:
terraform-provider-cloudpods 已经不适合当前的cloudpods了
**环境/Environment**:
cloudpodsv3.10.7

**Comment by zexi** [comment]
@hewenxiang 目前这个代码很久没有维护了，如果需要，可以手动修改下代码测试。

**Comment by zackzhangkai** [comment]
terraform已经不维护了吗？
