### ISSUE TITLE
[BUG]前端javascript 漏洞

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#18758]
**问题描述/What happened**:
经我们漏扫发现的
**环境/Environment**:
v3.10.4
 
![image](https://github.com/yunionio/cloudpods/assets/29140975/4f808cfa-6b3c-4f34-8d70-c13925b4a8c5)

**Comment by swordqiu** [comment]
@hewenxiang 有更详细的信息吗？没看出来是哪个框架库

**Comment by hewenxiang** [comment]
@swordqiu 
给的解决方案是将版本号给去掉
![image](https://github.com/yunionio/cloudpods/assets/29140975/0777aa82-d68e-4a18-84a6-14907ee57622)

**Comment by swordqiu** [comment]
@hewenxiang 我们在3.10.6集中进行了一次修复，用3.10.6或者3.10.7验证一下？
