### ISSUE TITLE
[求助/Help] 纳管VMware vSAN，上传qcow2镜像后，使用镜像创建虚拟机报错“磁盘分配失败”

### ISSUE THREAD

**Issue by dominickcjh** [yunionio/cloudpods#18774]
虚拟机页面报错
![image](https://github.com/yunionio/cloudpods/assets/144430202/3eff5104-1f8e-4de0-a671-83f162074c13)

镜像缓存报错
![image](https://github.com/yunionio/cloudpods/assets/144430202/a87203ab-d850-41f3-99d9-e8f7f011595f)
![image](https://github.com/yunionio/cloudpods/assets/144430202/738efb3c-c8cf-4508-8ec6-df6a2731d072)

查看glance pod日志报错
![image](https://github.com/yunionio/cloudpods/assets/144430202/d739b11d-cfe7-494e-84d5-a09b648caa91)

登录到glance pod，找到对应持久化目录下只有xxx.qcow2，没有对应.vmdk文件。
![image](https://github.com/yunionio/cloudpods/assets/144430202/d156e8da-dda5-44b2-9f9f-fc912ebe2d13)

将报错接口中的vmdk改成qcow2，可以正确请求接口
![image](https://github.com/yunionio/cloudpods/assets/144430202/2b9b013f-c16d-47b2-981d-1f5baf3e3f7d)

**Comment by zexi** [comment]
@dominickcjh 感觉是 glance 默认配置没有转换 vmdk 格式的镜像导致的，用下面的命令看下 target_image_formats 配置：

```bash
climc service-config-edit glance
```
<img width="412" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/c8f7e10d-36f4-4e36-afea-b7a6a65735ac">

如果只有 qcow2 的话，按照上面的设置把 vmdk 也加上，然后使用 `kubectl rollout restart deployment -n onecloud default-glance` 重启下 glance 镜像服务，再重新上传一个镜像应该就有 vmdk 的了。

**Comment by dominickcjh** [comment]
> @dominickcjh 感觉是 glance 默认配置没有转换 vmdk 格式的镜像导致的，用下面的命令看下 target_image_formats 配置：
> 
> ```shell
> climc service-config-edit glance
> ```
> 
> <img alt="image" width="412" src="https://user-images.githubusercontent.com/10767027/285421228-c8f7e10d-36f4-4e36-afea-b7a6a65735ac.png">
> 如果只有 qcow2 的话，按照上面的设置把 vmdk 也加上，然后使用 `kubectl rollout restart deployment -n onecloud default-glance` 重启下 glance 镜像服务，再重新上传一个镜像应该就有 vmdk 的了。

确实是这个问题，刚好也看到文档中有相应内容。调整并重启pod后，上传镜像后会创建vmdk了。非常感谢。也希望文档中能够增加重启glance服务的描述。
![image](https://github.com/yunionio/cloudpods/assets/144430202/cd2805d1-e8b1-4149-8302-87536a8e6a33)
