### ISSUE TITLE
v3.10.7 Cloudpods 原生计算机节点上的虚拟机不通[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18771]
cloudpods版本v3.10.7
计算机节点 为虚拟机（进行测试）
在 Cloudpods 私有云计算机节点下创建的虚拟机不通
![image](https://github.com/yunionio/cloudpods/assets/32296103/9492ae5e-b6bf-4a3b-a382-f1e4561a28ce)
![image](https://github.com/yunionio/cloudpods/assets/32296103/5417ed32-700b-4433-b8ae-4312d0e4cd03)

**Comment by zexi** [comment]
@shengxianli 02 那台虚拟机挂了一个子网的2个 ip ，这样会导致虚拟机里面的 linux 路由不对称，导致网络不通。
比如从 eth0 进来的包可能会从 eth1 出去。
建议不要给一台虚拟机添加多个属于一个子网的 ip ，如果一定要这么用，需要手动给虚拟机里面配置路由优先级顺序。

**Comment by shengxianli** [comment]
@zexi 01那个也不通。
