### ISSUE TITLE
无法识别zstack的san存储

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18773]
最近zstack增加了本地存储，能识别到宿主机的本地存储，但是SAN存储识别不到，region log上传了麻烦看下，谢谢 [region.log](https://github.com/yunionio/cloudpods/files/13455441/region.log)
![image](https://github.com/yunionio/cloudpods/assets/59357035/e469459d-b3fd-487f-80bb-05d7de2fa062)

![image](https://github.com/yunionio/cloudpods/assets/59357035/d4cab6f7-9d5c-47c8-a90e-a69247cb0ac3)

**Comment by ioito** [comment]
确实没加这种存储的逻辑，我加下

**Comment by ninghongwu** [comment]
@ioito 👍加好了我再试试，谢谢

**Comment by ioito** [comment]
yunionio/cloudmux#591

**Comment by ninghongwu** [comment]
@ioito 这个要等后面升级版本吗

**Comment by ioito** [comment]
> @ioito 这个要等后面升级版本吗

是的，有开发能力的可以自己下载源码打镜像替换更新

**Comment by ninghongwu** [comment]
@ioito 下个版本预计什么时候呢，坐等😄

**Comment by dengju2020** [comment]
> @ioito 下个版本预计什么时候呢，坐等😄

预计12月初发布

**Comment by ninghongwu** [comment]
@dengju2020 更新到3.10.10了，可以识别到SAN存储，但是创建还是有问题
![image](https://github.com/yunionio/cloudpods/assets/59357035/2bd0a4f1-2ffb-4557-bae0-f16ab05e0c1a)

本地存储和san存储空间都是足够的，麻烦看下，谢谢
![image](https://github.com/yunionio/cloudpods/assets/59357035/6005fa60-da79-4e62-a96d-ac849cd8c7a8)

**Comment by ioito** [comment]
@ninghongwu 分别截图看下zstack上面宿主机底下关联的存储列表，及cloudpods同步下来的zstack关联的存储列表

**Comment by ninghongwu** [comment]
@ioito 请看下这个截图可以么
![image](https://github.com/yunionio/cloudpods/assets/59357035/f2cc6a3e-0eaf-4b6b-b6b6-f154d2cea113)
![image](https://github.com/yunionio/cloudpods/assets/59357035/1d12579e-e777-4e55-99ba-d17c2bbf8405)

**Comment by ioito** [comment]
不行，需要看宿主机底下的存储，选择一个宿主机

**Comment by ninghongwu** [comment]
@ioito 两种存储
![image](https://github.com/yunionio/cloudpods/assets/59357035/2c19ad93-6acb-4120-9617-f93ab1afd7f4)

![image](https://github.com/yunionio/cloudpods/assets/59357035/50ea4096-459b-4379-ae12-bf7b8e8f281e)

**Comment by ninghongwu** [comment]
zstack上
![image](https://github.com/yunionio/cloudpods/assets/59357035/afb9500f-53a8-457e-ac17-64b73f041ebc)

**Comment by ioito** [comment]
> zstack上 ![image](https://private-user-images.githubusercontent.com/59357035/293322074-afb9500f-53a8-457e-ac17-64b73f041ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzMzNDksIm5iZiI6MTcwMzgzMzA0OSwicGF0aCI6Ii81OTM1NzAzNS8yOTMzMjIwNzQtYWZiOTUwMGYtNTNhOC00NTdlLWFjMTctNjRiNzNmMDQxZWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA2NTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZGZhYWE1ZWU4ZTljMTA0OWM1OGVhZWJkNTFmMzM3ZDJlNDQ1NGM2M2U3OWVkM2E5ODdkYzRmNDY0MGUyNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8QVJplUeVxoDlArOmGJbzVKJ10vQSpzbfYOOWtzqv3Q)

这个应该是磁盘，不是存储

**Comment by ninghongwu** [comment]
@ioito zstack上宿主机里看不到存储，只能去存储下面看
![image](https://github.com/yunionio/cloudpods/assets/59357035/a1cd2e43-d84b-4851-bf35-cbe5a9a058a4)

![image](https://github.com/yunionio/cloudpods/assets/59357035/b96795a4-e025-4232-9e2e-bcdb6a45977e)

**Comment by FlywinNing** [comment]
@ioito zstack还不行呢，麻烦看下
![image](https://github.com/yunionio/cloudpods/assets/158119314/345eff32-b96a-4ce9-81c1-e3021e806ae2)

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/20224

**Comment by FlywinNing** [comment]
@ioito 是等后面更新scheduler版本吗
现在是 image: registry.cn-beijing.aliyuncs.com/yunion/scheduler:v3.10.13

**Comment by ioito** [comment]
是的，或者你拉代码自己编译下镜像

**Comment by FlywinNing** [comment]
@ioito 等合并了我再改image，可以更新了回复个消息哈，非常感谢👍

**Comment by ioito** [comment]
registry.cn-beijing.aliyuncs.com/yunionio/scheduler:v3.10-2024050916-solo 已合并，我打了个镜像，可以试下

**Comment by FlywinNing** [comment]
@ioito 现在报400，麻烦再看下
![image](https://github.com/yunionio/cloudpods/assets/158119314/132da350-bccb-4168-88e1-c243b821ed3d)

**Comment by ioito** [comment]
climc scheduler-history-list 看下最近调度的历史
再贴下 climc scheduler-history-show --raw --log <id> 的输出结果， <id> 换成失败的session_id

**Comment by FlywinNing** [comment]
@ioito 今天早上来试了一下可以创建成功了，可能scheduler升级后，要等和zstack同步一次？
