### ISSUE TITLE
[求助/Help]vcenter6.5&7.0对接Cloudpods v3.10.2，同步数据异常问题

### ISSUE THREAD

**Issue by ives-66** [yunionio/cloudpods#18772]
![禁用后也无法删除](https://github.com/yunionio/cloudpods/assets/74636037/02df550b-a347-452a-8b92-4e56d609888f)![上传连接测试报错.j![同步数据报错信息](https://github.com/yunionio/cloudpods/assets/74636037/5414190f-7a70-41e5-be13-3285394e1479)pg...]()

![image](https://github.com/yunionio/cloudpods/assets/10767027/4ddb6290-fb32-4d54-8881-cb3439325d0b)

**Comment by ives-66** [comment]
问题现象：
原vcenter6.5&7.0自动同步数据正常，因版本升级将原vcenter6.5中的4台ESXI6.5格式化安装了ESXI7.0加入了vcenter7.0（前后ESXI的IP没有改变）。之后同步数据出现异常现象

**Comment by ives-66** [comment]
问题现象2，现在尝试禁用云账号（vcenter6.5&7.0），想删除也没法进行删除（删除为灰色状态）

**Comment by zexi** [comment]
@ives-66 请先升级到最新的 v3.10.7 版本后再试试，https://www.cloudpods.org/zh/docs/setup/upgrade/ 这个是升级文档。

**Comment by ives-66** [comment]
根据提供的文档，已升级为 v3.10.7 版本，上诉的2个问题依旧。可以帮看看还有啥原因会导致这种情况出现吗？

**Comment by ives-66** [comment]
![Uploading image.png…]()

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/57d287a6-5716-47d5-8eb8-deddfb103826)

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/fece596a-b181-4c15-89ac-1fc8a5aa7e51)

**Comment by dengju2020** [comment]
> ![image](https://user-images.githubusercontent.com/74636037/285382979-57d287a6-5716-47d5-8eb8-deddfb103826.png)

@ives-66 鼠标hover上去是否有提示信息？可以试试单个操作，看看是否可用。另外一个问题我们再看看

**Comment by swordqiu** [comment]
@ives-66 ESXI宿主机是一IP地址为全局ID标识的，所以把升级后和升级前的宿主机混在一起了。

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/8ba47baf-fc48-47a9-9c0f-6f066f814534)

**Comment by ives-66** [comment]
这种情况，有啥解决方案吗？

**Comment by swordqiu** [comment]
请尝试删除这三台宿主机的所有网络接口：
climc host-wire-list --host <host_id>
找到该宿主机的所有网卡的mac，然后执行下面命令删除
climc host-remove-netif <host_id> <mac>

**Comment by ives-66** [comment]
这个是在Cloudpods平台机器上操作吗？还是在哪里操作的？

**Comment by ives-66** [comment]
> > ![图像](https://user-images.githubusercontent.com/74636037/285382979-57d287a6-5716-47d5-8eb8-deddfb103826.png)
> 
> @ives-66鼠标hover上去是否有提示信息？可以试试单个操作，看看是否可用。另外一个问题我们再看看

提示“账户不空闲”

**Comment by ives-66** [comment]
> 请尝试删除这三台宿主机的所有网络接口：climc host-wire-list --host <host_id>找到该宿主机的所有网卡的mac，然后执行下面命令删除climc host-remove-netif <host_id>

这个是在Cloudpods平台机器上操作吗？还是在哪里操作的？

**Comment by ives-66** [comment]
> > 请尝试删除这三台宿主机的所有网络接口：climc host-wire-list --host <host_id>找到该宿主机的所有网卡的mac，然后执行下面命令删除climc host-remove-netif <host_id>
> 
> 这个是在Cloudpods平台机器上操作吗？还是在哪里操作的？

![image](https://github.com/yunionio/cloudpods/assets/74636037/558b8722-e343-4569-a10f-b2a5c63b7a9a)
要怎么区分哪个才是升级的4台ESXI？

**Comment by swordqiu** [comment]
@ives-66 可以在web控制台查看被升级的三台宿主机的ID

**Comment by ives-66** [comment]
> @ives-66 可以在web控制台查看被升级的三台宿主机的ID

vcenter的控制台吗？方便提供一下更详细的操作方法吗？

**Comment by ives-66** [comment]
> > @ives-66 可以在web控制台查看被升级的三台宿主机的ID
> 
> vcenter的控制台吗？方便提供一下更详细的操作方法吗？

cloudpods平台上，看不到升级4台ESXI的数据，因为没法同步过来

**Comment by ives-66** [comment]
> > > @ives-66 可以在web控制台查看被升级的三台宿主机的ID
> > 
> > 
> > vcenter的控制台吗？方便提供一下更详细的操作方法吗？
> 
> cloudpods平台上，看不到升级4台ESXI的数据，因为没法同步过来

中午出现“探测网络失败”，我将vcenter6.5删除了，然后单独同步vcenter7.0问题依旧，紧接着我又把vcenter6.5连接信息重新添加的，之后就没法删除了

**Comment by ives-66** [comment]
> 单个
![image](https://github.com/yunionio/cloudpods/assets/74636037/7c8696d8-20ad-48b8-8d6d-ecf73abf9c9b)
现在删除按钮看着是可以操作了，我现在要怎么操作比较合适？

**Comment by swordqiu** [comment]
@ives-66 可以删除云账号试试

**Comment by ives-66** [comment]
你们这个云账号删除后，会把同步过来的历史信息删除掉的吗？

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/e02514ca-ac3e-49ea-848d-64bee546e58c)
vcenter6.5跟vcenter7.0都删除了，IP子网信息怎么还在的，这个要怎么清理掉？

**Comment by dengju2020** [comment]
> ![image](https://user-images.githubusercontent.com/74636037/285404784-e02514ca-ac3e-49ea-848d-64bee546e58c.png) vcenter6.5跟vcenter7.0都删除了，IP子网信息怎么还在的，这个要怎么清理掉？

@ives-66 vmware的网络是使用云管平台的。不会随云账号删除而删除。下次导入云账号会自动匹配。如果不再使用可以手动在云管删除。

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/ee92da34-9455-4802-a3a5-7c2c9bc1efa7)
vcenter6.5&7.0删除云账号+子网信息后，目前看vcenter7.0正在同步数据了，vcenter6.5还是报“探测网络失败”，这种要怎么处理会比较好？

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/4dfe63fb-7181-4a0e-9b65-f7a7f418a145)
![image](https://github.com/yunionio/cloudpods/assets/74636037/38d0250c-4bb5-48f7-bd54-c503d57270ff)
升级到V3.10.7版本后，云账号这个位置，原来有个“本地IDC”没有了，这属于正常的吧？

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/6b6f9c25-1079-4294-abda-6e6c39feb006)
![image](https://github.com/yunionio/cloudpods/assets/74636037/93383628-2783-4f7f-b77d-371cd7436de3)
升级V3.10.7版本后，云账号这里没有了“本地IDC”选项是正常的吗？

**Comment by swordqiu** [comment]
@ives-66 日志有探测网络失败的失败信息吗？

> ![image](https://user-images.githubusercontent.com/74636037/285409849-ee92da34-9455-4802-a3a5-7c2c9bc1efa7.png) vcenter6.5&7.0删除云账号+子网信息后，目前看vcenter7.0正在同步数据了，vcenter6.5还是报“探测网络失败”，这种要怎么处理会比较好？

**Comment by ives-66** [comment]
![image](https://github.com/yunionio/cloudpods/assets/74636037/eec9a5cf-7678-428f-b395-773006226dbd)
有的

**Comment by ives-66** [comment]
目前vcenter7.0同步正常了，升级为ESXI7.0的机器信息也同步过来了，就剩下vcenter6.5没法同步

**Comment by ives-66** [comment]
这个报错还是跟之前差不多，提示冲突之类的。宿主机确实是属于不同的网段，刚开始都是正常的，就是6.5升级为7.0后用原ip就异常了，有没有办法清掉冲突的网络信息？

**Comment by swordqiu** [comment]
> vcenter7.0的二层网络比vcenter6.5更多，但是目前vcenter7.0同步正常了，二层网络调整不了为一个啊（分布不同地区地域的）

@ives-66 建议把vcenter 6.5云账号删除，然后把可能是vcenter6.5的IP子网全部删除，然后再纳管一遍vcenter6.5

**Comment by ives-66** [comment]
vcenter6.5&vcenter7.0全部删除后，重新添加后问题解决，感谢大佬
