### ISSUE TITLE
负载均衡lbagent节点建立[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18799]
3.10（含）之后版本部署Lbagent
自3.10(含）版本之后，负载均衡开始支持VPC内虚拟机的负载均衡，并可以挂载EIP。同时，部署流程更新为：

1、采用ocboot将已有虚拟机或物理机部署为lbagent节点 2、创建lbcluster 3、将一对lbagent节点和一个lbcluster关联，实现lbagent的自动化配置

lbagent节点的部署
采用ocboot，采用如下命令将地址为<ip_of_lbagent_node>的经典网络虚拟机或物理机部署为一台lbagent：

./ocboot add-lbagent <ip_of_master_node> <ip_of_lbagent_node>
部署成功的lbagent节点是k8s集群的一个节点，并且带有如下label：

onecloud.yunion.io/lbagent=enable

大神好，关于这个负载均衡数据转发的节点的部署没有看的太懂，比如我创建了2台虚拟机，IP为192.168.1.2和192.168.1.3 那是不是ip_of_lbagent_node就是这2个地址，我在选个一个IP比如是192.168.1.10作为<ip_of_master_node>这个节点的IP

**Comment by zexi** [comment]
> 比如我创建了2台虚拟机，IP为192.168.1.2和192.168.1.3 那是不是ip_of_lbagent_node就是这2个地址，我在选个一个IP比如是192.168.1.10作为<ip_of_master_node>这个节点的IP 。

@shengxianli 是的，就是这样部署的。

**Comment by shengxianli** [comment]
@zexi <ip_of_master_node>这个节点不能是虚拟IP是吧。也需要一台虚拟机
INFO:lib.ssh:exec_command: [ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json
ssh -p 22 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -i /root/.ssh/id_rsa root@10.1.18.50 '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json'
Traceback (most recent call last):
  File "./ocboot.py", line 40, in <module>
    sys.exit(main())
  File "./ocboot.py", line 36, in main
    args.func(args)
  File "/ocboot/lib/service.py", line 126, in do_action
    args.ssh_port)
  File "/ocboot/lib/cluster.py", line 24, in construct_cluster
    cluster = OnecloudCluster(cli)
  File "/ocboot/lib/cluster.py", line 44, in __init__
    f'{sudo_exec} kubectl -n onecloud get onecloudclusters default -o json')
  File "/ocboot/lib/ssh.py", line 84, in exec_command
    raise StderrException(err)
lib.ssh.StderrException: ssh: connect to host 10.1.18.50 port 22: Connection timed out

**Comment by swordqiu** [comment]
@shengxianli 看报错是kubectl未安装？
