### ISSUE TITLE
[求助/Help]服务: identity异常

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18810]
收到一些告警，麻烦看下是组件有异常吗，pod都正常running的，svc也没发现这个identity服务，谢谢
服务: identity 异常。
方法: GET
路径: 504 /v3/endpoints?interface=internal&region_id=region0&service_id=333973e2b4d3413c8af885850141de52 (xxxxxxxxx:36074:operator) 60001.39ms
错误: {"class":"TimeoutError","code":504,"details":"request process timeout","time":"2023-11-25T09:43:26+08:00"}

![image](https://github.com/yunionio/cloudpods/assets/59357035/885200a2-afb2-4d71-9949-54aa1c823a14)

**Comment by ninghongwu** [comment]
@swordqiu 系统负载不高，是不是default-keystone里的limit设置太小了，我调大点观察一段时间看看

**Comment by swordqiu** [comment]
@ninghongwu 是否有进一步信息？keystone服务比较轻量，很少发生timeout，可以从数据库连接是否阻塞以及负载是否太高来排查。

**Comment by ninghongwu** [comment]
@swordqiu identity 服务最近没出现告警了，compute又出现了

服务: compute 异常。 方法: GET 路径: 504 /cloudaccounts/43b8e38c-5658-48cd-8ad8-d84c817304cd?scope=system (xxxxxx:47170:cloudmon) 60000.59ms 错误: {"class":"TimeoutError","code":504,"details":"request process timeout","time":"2023-12-09T02:45:44+08:00"}
