### ISSUE TITLE
[求助/Help] 统信UOS桌面专业版AMD64安装监控agent报错，Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab /var/spool/cron: No such file or directory /var/spool/cron: mkdir: No such file or directory

### ISSUE THREAD

**Issue by baiweiyll** [yunionio/cloudpods#18824]
cloudpods版本：3.9.12
宿主机 ：X86架构 Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
虚拟机镜像 ：统信UOS桌面专业版AMD64  https://www.chinauos.com/resource/download-professional

错误信息如下：
{
    "__reason__": "Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = deploy telegraf: add crontab /var/spool/cron: No such file or directory\n/var/spool/cron: mkdir: No such file or directory\n: exit status 1",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}

**Comment by zexi** [comment]
<img width="1384" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/d571d94f-0013-4558-ac41-0965081a02c7">

[root@office-controller ~]# ls -alh debian-12-generic-amd64-20230802-1460.qcow2
-rw-r--r-- 1 root root 395M Sep  4 11:11 debian-12-generic-amd64-20230802-1460.qcow2

使用 debian-12 的镜像遇到了类似的问题，会导致部署后没有用户密码。使用的是 v3.10.8 的版本。
@wanyaoqi

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/19088
该 PR 修复此问题。

**Comment by zexi** [comment]
@baiweiyll 下个版本 v3.10.9 会包含修复此问题的代码
