### ISSUE TITLE
[求助/Help]  Ubuntu22.04添加计算节点失败

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#18830]
![image](https://github.com/yunionio/cloudpods/assets/7510377/4ba8fe56-b095-4f17-8a21-8e51b3bfd114)

**Comment by zexi** [comment]
@flowlsj 这个看起来是 k8s 网络的问题，请参考文档排查添加节点到控制节点的网络情况：https://www.cloudpods.org/zh/docs/ops/k8s/dnserror/  。
