### ISSUE TITLE
[BUG] 初始化script_tbl表时候执行的InitializeData函数 查询数据库字段不对

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#18851]
**问题描述/What happened**:
script_tbl 这个表中没有  playbook_reference 这个字段，然后会导致每次启动都会添加一条数据 
代码位置  pkg/devtool/models/script.go:63
![image](https://github.com/yunionio/cloudpods/assets/70850653/e1e14eee-9e71-43a3-8b6b-8dd5d2d3c957)

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@xzzdhq 感谢反馈，我修复下。

/keep-state

**Comment by zexi** [comment]
@xzzdhq 我看了下代码，这个  ScriptManager.InitializeData() 函数应该不会被调用，因为没有在 pkg/devtool/models/initdb.go 里面注册，应该是可以删除的代码。
我测试不断重启 devtool 服务，并没有出现重复插入的情况。
