### ISSUE TITLE
虚拟机是否可以支持英特尔sgx？

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#18885]
当前我们的cloudpods 宿主机内核版本为5.4.130-1.yn20221208.el7.x86_64 ，想问下 ：
1  咱们这个内核版本是否支持英特尔 sgx模块？（我们已经在bios开启了该功能，在当前宿主机系统内通过cpuid|grep SGX 看到SGX supported  为true，但加载该模块仍然需要额外安装驱动）。 
2  如果想让vm也能够使用英特尔sgx，我们需要一些额外的虚拟化配置吗？

**Comment by swordqiu** [comment]
@tianchao001 感觉不需要特殊配置，因为默认cpu是透传到虚拟机的，只要宿主机能看到这个flag，虚拟机也能看到。

**Comment by tianchao001** [comment]
> @tianchao001 感觉不需要特殊配置，因为默认cpu是透传到虚拟机的，只要宿主机能看到这个flag，虚拟机也能看到。

咱们这个内核版本是支持sgx的对吗？ 5.4.130-1.yn20221208.el7.x86_64

**Comment by swordqiu** [comment]
@tianchao001 不太确定5.4内核是否支持SGX。但是即使宿主机内核不支持，也不妨碍虚拟机使用这个特性，因为虚拟机的指令是在CPU上直接执行的，并不通过宿主机内核代理。

**Comment by tianchao001** [comment]
> @tianchao001 不太确定5.4内核是否支持SGX。但是即使宿主机内核不支持，也不妨碍虚拟机使用这个特性，因为虚拟机的指令是在CPU上直接执行的，并不通过宿主机内核代理。

我测试了一下，在宿主机上执行cpuid 显示sgx为true的情况下，装了虚拟机后，虚拟机内显示false

**Comment by wanyaoqi** [comment]
@tianchao001 https://www.intel.com/content/www/us/en/developer/articles/technical/virtualizing-intel-software-guard-extensions-with-kvm-and-qemu.html 看这个 intel 的文档来说目前是不支持的
