### ISSUE TITLE
[求助/Help]从管理后台进入普通项目下偶发性出现403

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#18886]
从管理后台进入普通项目下偶发性出现403，然后等自动返回又正常，请问这是哪块的问题呢
![image](https://github.com/yunionio/cloudpods/assets/59357035/3f831a2c-11ab-4b9a-b109-8ad90a733511)
![image](https://github.com/yunionio/cloudpods/assets/59357035/fb5b0fc5-fe18-4c4e-8a7c-4a969c4234ce)

**Comment by ninghongwu** [comment]
admin用户，也给了角色和权限都有的
![image](https://github.com/yunionio/cloudpods/assets/59357035/deee8da7-9818-44c6-b860-3edd80f52d70)

**Comment by swordqiu** [comment]
@ninghongwu 可以打开浏览器debug模式，看下返回403的是哪些API请求，这样才好定位问题。

**Comment by ninghongwu** [comment]
@swordqiu 页面403了 但是没发现api请求有403

![image](https://github.com/yunionio/cloudpods/assets/59357035/61c6da20-8bbb-412c-b135-7ecade7f58eb)

**Comment by ninghongwu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/59357035/6618bd32-6556-4fb1-9fa2-f7b10d721268)

**Comment by ninghongwu** [comment]
@ioito 出现403的时候就只有这些请求，等它几秒的自动跳转就又正常访问了
