### ISSUE TITLE
[求助/Help] 物理机--添加--导入Excel表报错 找不到可用IP地址

### ISSUE THREAD

**Issue by ChaoHsin-fang** [yunionio/cloudpods#18894]
InsufficientResourceError
找不到可用IP地址
错误源信息:
{
  "class": "InsufficientResourceError",
  "code": 400,
  "details": "找不到可用IP地址",
  "request": {
    "body": "{\"host\":{\"access_ip\":\"10.5.1.1\",\"access_mac\":\"14:23:f2:c0:b6:00\",\"host_type\":\"baremetal\",\"ipmi_ip_...oject_domain\":\"default\"}}",
    "headers": {
      "Content-Length": "247",
      "Content-Type": "application/json",
      "User-Agent": "yunioncloud-go/201708",
      "X-Auth-Token": "*",
      "X-Request-Id": "915c18",
      "X-Yunion-Lang": "zh-CN",
      "X-Yunion-Parent-Id": "0",
      "X-Yunion-Peer-Service-Name": "apigateway",
      "X-Yunion-Remote-Addr": "default-region:30888",
      "X-Yunion-Span-Id": "0.0",
      "X-Yunion-Span-Name": "",
      "X-Yunion-Strace-Debug": "true",
      "X-Yunion-Strace-Id": "d8ce7be1"
    },
    "method": "POST",
    "url": "https://default-region:30888/hosts"
  },
  "time": "2023-12-05T14:22:06+08:00"
} 

{
  "method": "post",
  "url": "/v1/uploads",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "x-yunion-lang": "zh-CN"
  },
  "data": {}
}

**Comment by zexi** [comment]
感谢反馈，我们测试下。/keep-state

**Comment by zexi** [comment]
https://github.com/yunionio/cloudpods/pull/19353
解决此问题
