### ISSUE TITLE
[求助/Help] host服务和dns服务CrashLoopBackOff

### ISSUE THREAD

**Issue by zhuhedong** [yunionio/cloudpods#18945]
![image](https://github.com/yunionio/cloudpods/assets/44915307/f5e7e534-49e9-45f0-9b05-dc185ec9dafd)
![image](https://github.com/yunionio/cloudpods/assets/44915307/be6e92b8-0353-461b-b33f-4d5559747b2e)

默默问一句，这个是什么问题

**Comment by zhuhedong** [comment]
![image](https://github.com/yunionio/cloudpods/assets/44915307/2b154b1d-32ec-4fa9-9bd0-67556476df42)

**Comment by zhuhedong** [comment]
也是你们的服务， 我出现了控制台一直打不开的问题， 我现在重装了， 就遇到了这个问题

**Comment by zhuhedong** [comment]
我现在环境没有了， 我怎么新装一个节点，如何弄过去， 系统数据镜像还在

**Comment by zexi** [comment]
和此问题相关：https://github.com/yunionio/cloudpods/issues/18954，该问题就关闭了。
@zhuhedong 后续有问题，可以重新提交新的 issue 。
