### ISSUE TITLE
[求助/Help]物理机IPMI托管后，少部分机器获取不到硬件信息

### ISSUE THREAD

**Issue by ives-66** [yunionio/cloudpods#18942]
机器品牌型号：浪潮NF5270M5
![模版导入物理机](https://github.com/yunionio/cloudpods/assets/74636037/46783176-3256-41b1-b4e3-0af36629691a)
![物理机带外管理口用户配置信息](https://github.com/yunionio/cloudpods/assets/74636037/33631235-81dc-4db8-885c-8306e23eb83f)
![硬件信息同步无数据显示](https://github.com/yunionio/cloudpods/assets/74636037/668b6cfa-e6bb-41a4-b339-1c587d5c7e81)
![多云管理平台IPMI报错信息](https://github.com/yunionio/cloudpods/assets/74636037/26fdc372-5c27-4f14-a18b-4c8e9b63bf38)

麻烦大佬帮忙看看，看看问题出在哪里？万分感谢

**Comment by zexi** [comment]
@ives-66 ISO 引导注册要求物理机必须支持 redfish api 才行，那些没有获取到信息的机器应该不支持这个，需要用 pxe 引导注册。

**Comment by ives-66** [comment]
好的，感谢你。
