### ISSUE TITLE
[BUG]谷歌云的虚拟机重装系统上传新的密钥信息，重装成功后无法使用新密钥连接虚拟机

### ISSUE THREAD

**Issue by xiezhihuan** [yunionio/cloudpods#18958]
**问题描述/What happened**:
谷歌云的虚拟机重装系统上传新的密钥信息，重装成功后无法使用新密钥连接虚拟机。密钥未写入到操作系统中

**Comment by ioito** [comment]
我这边测试是正常的，你那边确认重装完成后 /root/.ssh/authorized_keys 里面没有任何公钥信息么

**Comment by xiezhihuan** [comment]
> 我这边测试是正常的，你那边确认重装完成后 /root/.ssh/authorized_keys 里面没有任何公钥信息么

我再尝试复现一次看看
