### ISSUE TITLE
[BUG]谷歌云虚拟机重装ubuntu-minimal-2004-focal-v20230818镜像后磁盘由原来20G变成10G

### ISSUE THREAD

**Issue by xiezhihuan** [yunionio/cloudpods#18957]
**问题描述/What happened**:
我使用cloudpods网页客户端创建了一台centos-7-v20230809镜像的20G磁盘的虚拟机，创建成功后关机进行重装ubuntu-minimal-2004-focal-v20230818镜像。待重装完成后，发现磁盘由20G变成了10G
**环境/Environment**:

![image](https://github.com/yunionio/cloudpods/assets/34810084/6e7adaab-632d-47fc-93fc-e78778e42777)

**Comment by ioito** [comment]
https://github.com/yunionio/cloudmux/pull/637 修复
