### ISSUE TITLE
[BUG] 纳管vmware，原来一直正常使用，升级3.10.8 发现有 新添加进 vmware集群的 宿主机信息 没同步进来 cloudpods ，点击云账号全量同步 ，几个小时了还是一直显示在同步中的状态，没结束

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#18959]
**问题描述/What happened**:

**环境/Environment**:

OS
centos 7.9
cloudpods: 3.10.7--->升级 3.10.8n (e.g. `climc version-list`):

-->

新添加进 vmware集群的 宿主机信息 没同步进来 cloudpods ，点击云账号全量同步 ，几个小时了还是一直显示在同步中的状态，没结束

![bff0d8956db2e6c9d484bd02774792d](https://github.com/yunionio/cloudpods/assets/48039439/01efd9fc-a864-4bf7-80dd-f3caa0c0cbff)

**Comment by swordqiu** [comment]
@sun3book 请看下云账号的操作日志是否有异常？如果没有，请看下default-region这个deployment的pod日志是否有异常。

**Comment by zexi** [comment]
@sun3book 我在 3.10.8 没有复现出来这个问题，请把 default-region 这个服务重启下，然后再同步一次，如果还是有问题，请把 region 服务的日志导出来贴到这里。
