### ISSUE TITLE
[BUG]重装系统之后无法进行密码登录

### ISSUE THREAD

**Issue by xiezhihuan** [yunionio/cloudpods#18963]
**问题描述/What happened**:
虚拟机镜像: ubuntu-minimal-2004-focal-v20230818
虚拟机重装系统时选择密码，但重装完成之后无法使用密码登录
**环境/Environment**:

关机，绑定公钥之后登录查看ssh配置，发现未允许使用密码登录
```bash 
cat /etc/ssh/sshd_config | grep Password
PasswordAuthentication no
#PermitEmptyPasswords no
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication, then enable this but set PasswordAuthentication
```

期望: 重装系统选择密码的情况下，重装完成之后可使用密码登录

**Comment by zexi** [comment]
@xiezhihuan 这个是镜像里面的默认配置，平台这边部署不会去改这个地方。

可以你自己基于这个镜像创建虚拟机修改后，然后把这个虚拟机系统盘保存成系统镜像，之后再用这个镜像创建虚拟机，默认的 sshd 密码登录就打开了。

**Comment by xiezhihuan** [comment]
> 不能像新装的虚拟机那样帮设置PasswordAuthentication yes吗

同一个镜像新建的虚拟机ssh是运行密码登录的
```bash
cat /etc/ssh/sshd_config | grep Password
PasswordAuthentication yes
#PermitEmptyPasswords no
PasswordAuthentication yes
PasswordAuthentication yes
```

**Comment by ioito** [comment]
![Pasted Graphic](https://github.com/yunionio/cloudpods/assets/13750250/8bcb9267-7573-40c7-ae1b-e4fb6d04db10)
![image](https://github.com/yunionio/cloudpods/assets/13750250/2fd1478d-3402-4873-8a85-a60d49bce64e)
看了下重装系统是启动脚本是正常设置的，gcp的日志也正常记录启动脚本是执行了的，这个我再查下

**Comment by xiezhihuan** [comment]
> ![Pasted Graphic](https://private-user-images.githubusercontent.com/13750250/289724692-8bcb9267-7573-40c7-ae1b-e4fb6d04db10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDgwMjMsIm5iZiI6MTcwMjM0NzcyMywicGF0aCI6Ii8xMzc1MDI1MC8yODk3MjQ2OTItOGJjYjkyNjctNzU3My00MGM3LWFlMWItZTRmYjZkMDRkYjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNmIxOTZkNDY0NDVmZjM3ZTgyYWU2MmZjMDM0Y2QyNDY2MjY2ODc4ODA0YTNiMDQ2MzIzZTg2ZjA4YTAyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8IWg9S_1WOrCKBLB-v5TNRq5cMWNQjYWXwlLXgh8PU) ![image](https://private-user-images.githubusercontent.com/13750250/289724815-2fd1478d-3402-4873-8a85-a60d49bce64e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDgwMjMsIm5iZiI6MTcwMjM0NzcyMywicGF0aCI6Ii8xMzc1MDI1MC8yODk3MjQ4MTUtMmZkMTQ3OGQtMzQwMi00ODczLThhODUtYTYwZDQ5YmNlNjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMmM4NWU3YThlYjIxOWU1ZjllN2E0MjU0YzU4NTFlNWM2ZmM1YWM2ZjVkZGIzNjlmZjJjMWY2YTkwNGM2NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rThvu842r04dKCHCaTZo-_6kQRBEPjNzRKu7buLQgmg) 看了下重装系统是启动脚本是正常设置的，gcp的日志也正常记录启动脚本是执行了的，这个我再查下

是的，看到有自定义脚本去修改sshd配置。但好像没有修改生效

**Comment by ioito** [comment]
https://github.com/yunionio/cloudmux/pull/634 
@xiezhihuan  找到原因了，没有设置允许password登录

**Comment by xiezhihuan** [comment]
我应该怎么重新部署呢，用[ocboot](https://github.com/yunionio/ocboot) 工具？

> [yunionio/cloudmux#634](https://github.com/yunionio/cloudmux/pull/634) @xiezhihuan 找到原因了，没有设置允许password登录

**Comment by zexi** [comment]
@xiezhihuan 这个 https://github.com/yunionio/cloudmux/pull/634 PR 昨天才合并到主仓库：https://github.com/yunionio/cloudpods/pull/18969。

需要手动打 region 服务的镜像 ，然后更新服务，可以参考这个文档自己做镜像：https://v2.cloudpods.org/docs/development/dev-env

不然就只有等下次我们发布版本再统一更新了。
