### ISSUE TITLE
[求助/Help]创建rds实例失败，提华为云工单说是 套餐规格不对，但是页面就这一个套餐可以选择

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#18962]
一开始创建一个rds实例在这一步报错
![image](https://github.com/yunionio/cloudpods/assets/70850653/e07d08f8-8772-4d4f-8ce6-3e78e24a9f0f)

然后点击同步状态，发现错误如下，
![image](https://github.com/yunionio/cloudpods/assets/70850653/1c38482f-e859-4570-926e-c27aeb92679e)

查看数据库 external_id 为空 
![image](https://github.com/yunionio/cloudpods/assets/70850653/96936657-f82e-44d9-b7d6-d71f7addbb2f)

**Comment by xzzdhq** [comment]
查看 region日志 ，然后重新新建一个 rds实例，得到日志如下 
看到 华为云返回错误码为  DBS.280241 ，含义为 卷类型错误，但是不知道 cloudpods 这边的卷类型参数是在哪里传过去的，以及本次api 传的卷类型是什么
调用华为云的出入参 
[error 2023-12-11 09:24:16 modules.(*SBaseManager).jsonRequest(manager_base.go:232)]POST: https://rds.cn-east-3.myhuaweicloud.com/v3/2e4265e2e96b460690a5d19366ba9452/instances body: {"availability_zone":"cn-east-3a","datastore":{"type":"MySQL","version":"5.6"},"flavor_ref":"rds.mysql.n1.medium.2","name":"rds2","password":"y7cX+52mU6C-","region":"cn-east-3","security_group_id":"2db951c6-b0c8-463b-b71c-d3c5614ea841","subnet_id":"27a4e84c-ba03-4302-afe7-458b0a737330","volume":{"size":40,"type":"LOCALSSD"},"vpc_id":"04362e26-e600-4e6a-a23a-1aa3c2a1a39f"} error: {"code":400,"details":"{\"error_code\":\"DBS.280241\",\"error_msg\":\"Invalid storage type.\"}","error_code":"DBS.280241"}




所有日志
error 2023-12-11 09:23:10 httperrors.HTTPError(httperrors.go:110)] Send error 找不到dbinstance资源rds2
[info 2023-12-11 09:23:10 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 404 fda149-e2d976 GET /dbinstances/rds2?filter=name.contains%28%27rds2%27%29&name=rds2&scope=system (10.0.88.2:56692:apigateway) 2.67ms
[info 2023-12-11 09:23:10 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 fda149-697a09 GET /dbinstances?filter=name.contains%28%27rds2%27%29&name=rds2&scope=system (10.0.88.2:56692:apigateway) 1.23ms
[info 2023-12-11 09:23:15 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 1e0208-96f7b9 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:56866:apigateway) 12.13ms
[info 2023-12-11 09:23:26 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 564933-211ee5 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:56942:apigateway) 23.15ms
[info 2023-12-11 09:23:37 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 a0b290-1c9ad6 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:57036:apigateway) 11.27ms
[warning 2023-12-11 09:23:40 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager cloudAccountProbeWorkerManager has been busy for 1843 cycles...
[info 2023-12-11 09:23:41 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 876c74 GET /schedtags/same_project (10.0.88.2:46408:operator) 94.71ms
[info 2023-12-11 09:23:41 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 8b2a9e GET /dynamicschedtags/same_cloudprovider_project (10.0.88.2:46408:operator) 3.69ms
[info 2023-12-11 09:23:45 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 b7ebde-578ce7 GET /vpcs?cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&limit=0&project_domain&scope=system&usable=true&zone_id=2270a350-dc46-4515-8613-f236598b5efd (10.0.88.2:57114:apigateway) 14.84ms
[info 2023-12-11 09:23:45 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 949438-1f06f2 GET /dbinstance_skus?category=single&cloudregion=7d2be344-03de-425f-87f8-8c2fb98b9c2a&cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&engine=MySQL&engine_version=5.6&project_domain&scope=system&storage_type=LOCALSSD&vcpu_count=1&vmem_size_mb=2048&zone1=2270a350-dc46-4515-8613-f236598b5efd (10.0.88.2:57112:apigateway) 14.83ms
[info 2023-12-11 09:23:45 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 89b04f GET /hosts?details=true&enabled=1&host_type=hypervisor&limit=1024&offset=0&scope=system (10.3.0.1:53590:monitor) 1.61ms
[info 2023-12-11 09:23:45 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 1a869f-facbd3 GET /networks?cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&limit=0&project_domain&scope=system&usable=true&vpc=e697593f-8e25-42cd-8e3a-770159be5b37&zones.0=2270a350-dc46-4515-8613-f236598b5efd (10.0.88.2:57112:apigateway) 17.80ms
[info 2023-12-11 09:23:47 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 a016e9-7b8a25 GET /vpcs?cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&limit=0&project_domain&scope=system&usable=true&zone_id=1aad8fdb-ed26-4ab2-8ad8-0ce5a16d4460 (10.0.88.2:57114:apigateway) 20.33ms
[info 2023-12-11 09:23:47 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 c36b8f-7b73f5 GET /dbinstance_skus?category=single&cloudregion=7d2be344-03de-425f-87f8-8c2fb98b9c2a&cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&engine=MySQL&engine_version=5.6&project_domain&scope=system&storage_type=LOCALSSD&vcpu_count=1&vmem_size_mb=2048&zone1=1aad8fdb-ed26-4ab2-8ad8-0ce5a16d4460 (10.0.88.2:57112:apigateway) 20.58ms
[info 2023-12-11 09:23:48 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 3b4361-3b1fb1 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:57112:apigateway) 11.22ms
[info 2023-12-11 09:23:48 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 285c91-34cc6a GET /networks?cloudregion_id=7d2be344-03de-425f-87f8-8c2fb98b9c2a&limit=0&project_domain&scope=system&usable=true&vpc=e697593f-8e25-42cd-8e3a-770159be5b37&zones.0=1aad8fdb-ed26-4ab2-8ad8-0ce5a16d4460 (10.0.88.2:57112:apigateway) 23.09ms
[info 2023-12-11 09:23:58 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 bec36e-694935 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:57252:apigateway) 40.93ms
[info 2023-12-11 09:23:59 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 d1999e-9f9d20 POST /dbinstances (10.0.88.2:57252:apigateway) 204.71ms
[info 2023-12-11 09:23:59 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 2e5a46-2ab41e GET /dbinstances?details=false&limit=20&scope=system&show_fail_reason=true (10.0.88.2:57252:apigateway) 2.64ms
[info 2023-12-11 09:23:59 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 13c381-4ac36c GET /dbinstances?details=true&limit=20&scope=system&show_fail_reason=true (10.0.88.2:57252:apigateway) 11.11ms
[info 2023-12-11 09:24:01 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 9f5c96-79cff6 GET /dbinstances/statistics?details=true&limit=20&scope=system&show_fail_reason=true (10.0.88.2:57252:apigateway) 1.20ms
[error 2023-12-11 09:24:02 modules.(*SBaseManager).jsonRequest(manager_base.go:232)]POST: https://eps.myhuaweicloud.com/v1.0/enterprise-projects body: {"name":"system"} error: {"code":403,"details":"{\"error\":{\"error_code\":\"EPS.0004\",\"error_msg\":\"Permission error.\"}}"}



[info 2023-12-11 09:24:09 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 716f72-1cdf75 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:57336:apigateway) 11.00ms
[info 2023-12-11 09:24:09 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 721511-a30f34 GET /dbinstances/3dd4e8b0-b494-4e1b-8b3b-49def53d6963?details=true&scope=system&show_fail_reason=true (10.0.88.2:57336:apigateway) 10.78ms
[warning 2023-12-11 09:24:10 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager cloudAccountProbeWorkerManager has been busy for 1844 cycles...
[error 2023-12-11 09:24:16 modules.(*SBaseManager).jsonRequest(manager_base.go:232)]POST: https://rds.cn-east-3.myhuaweicloud.com/v3/2e4265e2e96b460690a5d19366ba9452/instances body: {"availability_zone":"cn-east-3a","datastore":{"type":"MySQL","version":"5.6"},"flavor_ref":"rds.mysql.n1.medium.2","name":"rds2","password":"y7cX+52mU6C-","region":"cn-east-3","security_group_id":"2db951c6-b0c8-463b-b71c-d3c5614ea841","subnet_id":"27a4e84c-ba03-4302-afe7-458b0a737330","volume":{"size":40,"type":"LOCALSSD"},"vpc_id":"04362e26-e600-4e6a-a23a-1aa3c2a1a39f"} error: {"code":400,"details":"{\"error_code\":\"DBS.280241\",\"error_msg\":\"Invalid storage type.\"}","error_code":"DBS.280241"}
[info 2023-12-11 09:24:16 taskman.(*STask).SetStageFailed(tasks.go:695)] XXX TASK DBInstanceCreateTask failed: "{\"__reason__\":\"create: Create: {\\\"code\\\":400,\\\"details\\\":\\\"{\\\\\\\"error_code\\\\\\\":\\\\\\\"DBS.280241\\\\\\\",\\\\\\\"error_msg\\\\\\\":\\\\\\\"Invalid storage type.\\\\\\\"}\\\",\\\"error_code\\\":\\\"DBS.280241\\\"}\",\"__stage__\":\"OnCreateDBInstanceComplete\",\"__status__\":\"ERROR\"}" on stage OnCreateDBInstanceComplete
[info 2023-12-11 09:24:16 taskman.(*STask).NotifyParentTaskComplete(tasks.go:719)] notify_parent_task_complete: DBInstanceCreateTask params {"__failed_reason":{"reason":"{\"__reason__\":\"create: Create: {\\\"code\\\":400,\\\"details\\\":\\\"{\\\\\\\"error_code\\\\\\\":\\\\\\\"DBS.280241\\\\\\\",\\\\\\\"error_msg\\\\\\\":\\\\\\\"Invalid storage type.\\\\\\\"}\\\",\\\"error_code\\\":\\\"DBS.280241\\\"}\",\"__stage__\":\"OnCreateDBInstanceComplete\",\"__status__\":\"ERROR\"}","stage":"OnCreateDBInstanceComplete"},"__request_context":{"lang":"zh-CN","request_id":"d1999e-9f9d20","service_name":"compute_v2","trace":{"debug":true,"duration":0,"id":"0.0","kind":"SERVER","local_endpoint":{"addr":"default-cloudpods-region","port":30888,"service_name":"compute_v2"},"name":"create","parent_id":"0","remote_endpoint":{"addr":"10.0.88.2","port":57252,"service_name":"apigateway"},"shared":false,"tags":{"resource":"dbinstances"},"timestamp":"2023-12-11T09:23:59.296108Z","trace_id":"6a216192"}},"__stages":[{"complete_at":"2023-12-11T09:23:59Z","name":"on_init"},{"complete_at":"2023-12-11T09:24:16Z","name":"OnCreateDBInstanceComplete"}],"auto_renew":false,"billing_cycle":"1H","billing_type":"postpaid","category":"single","cloudregion_id":"7d2be344-03de-425f-87f8-8c2fb98b9c2a","description":"rds2","disk_size_gb":40,"dry_run":false,"duration":"1h","engine":"MySQL","engine_version":"5.6","expired_at":"2023-12-11T10:23:59.303361Z","instance_type":"rds.mysql.n1.medium.2","manager_id":"a51085e3-ffc1-4b8a-8e86-1f7fc89af51a","multi_az":false,"name":"rds2","network":"c4b2da8b-9288-4bc7-807d-340228884a3b","network_id":"c4b2da8b-9288-4bc7-807d-340228884a3b","port":0,"project":"b38035d42eea478b8b48a90e3c459529","project_id":"b38035d42eea478b8b48a90e3c459529","reset_password":true,"secgroup":["default"],"secgroup_ids":["default"],"storage_type":"LOCALSSD","tenant":"b38035d42eea478b8b48a90e3c459529","tenant_id":"b38035d42eea478b8b48a90e3c459529","vcpu_count":1,"vmem_size_mb":2048,"vpc_id":"e697593f-8e25-42cd-8e3a-770159be5b37","zone1":"1aad8fdb-ed26-4ab2-8ad8-0ce5a16d4460"}
[info 2023-12-11 09:24:19 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 a257d6-3d6f35 GET /dbinstances/76345bd9-0aa8-403b-81e0-932b1b3d1fce?details=true&scope=system&show_fail_reason=true (10.0.88.2:57408:apigateway) 10.96ms
[info 2023-12-11 09:24:19 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 048772-4e8586 GET /dbinstances/3dd4e8b0-b494-4e1b-8b3b-49def53d6963?details=true&scope=system&show_fail_reason=true (10.0.88.2:57408:apigateway) 10.95ms
[info 2023-12-11 09:24:20 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 1991b5 GET /schedtags/same_project (10.0.88.2:46738:operator) 98.74ms
[info 2023-12-11 09:24:20 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 28add6 GET /dynamicschedtags/same_cloudprovider_project (10.0.88.2:46738:operator) 3.57ms

**Comment by xzzdhq** [comment]
图一是cloudpods的创建页面，图二图三是 华为云工单返回的信息
![image](https://github.com/yunionio/cloudpods/assets/70850653/e2f984bb-d9a7-451c-86d9-e1f50c4d796f)
![image](https://github.com/yunionio/cloudpods/assets/70850653/c6e43a50-ded5-4478-8ef4-f8a3cea9bc72)
![image](https://github.com/yunionio/cloudpods/assets/70850653/fe81b04a-7b3e-4ca5-83c9-ef62777dc81b)

**Comment by ioito** [comment]
这个我改进下，华为云的rds套餐列表没有太考虑实例类型和存储类型的关系

**Comment by xzzdhq** [comment]
ok，改好了麻烦issue回复下

**Comment by ioito** [comment]
> ok，改好了麻烦issue回复下

收集套餐程序已经更新，近两天会推送最新套餐

**Comment by ioito** [comment]
@xzzdhq 套餐数据已更新
![image](https://github.com/yunionio/cloudpods/assets/13750250/00efc492-a8a1-40fa-8e7c-1c43df8a2076)
