### ISSUE TITLE
[求助/Help] 创建弹性公网IP，状态显示可用，但是进去IP详情查看操作日志，在sync_cloud_project 项有报错

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#18968]
日志如下 
创建弹性公网ip也失败，华为云的错误码文档 https://support.huaweicloud.com/api-em/ErrorCode.html  ，含义为为权限不足
错误日志如下 
[error 2023-12-12 02:09:15 modules.(*SBaseManager).jsonRequest(manager_base.go:232)]POST: https://eps.myhuaweicloud.com/v1.0/enterprise-projects body: {"name":"system"} error: {"code":403,"details":"{\"error\":{\"error_code\":\"EPS.0004\",\"error_msg\":\"Permission error.\"}}"}<br/>[

但是查看代码，没有找到这个路由 https://eps.myhuaweicloud.com/v1.0/enterprise-projects 
然后在华为云里面也没有找到这个接口，想问一下，这个权限是什么权限呢，

当时的region服务日志如下：

 [info 2023-12-12 02:09:07 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 2e52e2-acb672 POST /eips (10.0.88.2:53304:apigateway) 35.88ms<br/>[info 2023-12-12 02:09:07 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 ca2f56-be6d55 GET /eips?details=false&limit=20&scope=system&show_fail_reason=true (10.0.88.2:53304:apigateway) 2.76ms<br/>[info 2023-12-12 02:09:07 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 9ab630-a4cbbe GET /eips?details=true&limit=20&scope=system&show_fail_reason=true (10.0.88.2:53304:apigateway) 10.77ms<br/>[info 2023-12-12 02:09:09 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 56477a-875d77 GET /eips/statistics?details=true&limit=20&scope=system&show_fail_reason=true (10.0.88.2:53304:apigateway) 1.20ms<br/><br/><br/>[warning 2023-12-12 02:09:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager cloudAccountProbeWorkerManager has been busy for 975 cycles...<br/>[error 2023-12-12 02:09:15 modules.(*SBaseManager).jsonRequest(manager_base.go:232)]POST: https://eps.myhuaweicloud.com/v1.0/enterprise-projects body: {"name":"system"} error: {"code":403,"details":"{\"error\":{\"error_code\":\"EPS.0004\",\"error_msg\":\"Permission error.\"}}"}<br/>[info 2023-12-12 02:09:17 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 6899d7-ba5954 GET /eips/c0a7f8dd-bc7f-47e2-8af6-8815687a290e?details=true&scope=system&show_fail_reason=true (10.0.88.2:53398:apigateway) 8.71ms<br/>[info 2023-12-12 02:09:17 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 8882de-f36ff6 GET /eips/6c76959a-bd31-4699-862a-c0dbea1c2fa2?details=true&scope=system&show_fail_reason=true (10.0.88.2:53400:apigateway) 9.44ms<br/>[info 2023-12-12 02:09:20 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 07b7ca GET /schedtags/same_project (10.0.88.2:42740:operator) 111.94ms<br/>[info 2023-12-12 02:09:20 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 8460ce GET /dynamicschedtags/same_cloudprovider_project (10.0.88.2:42740:operator) 3.55ms<br/>[info 2023-12-12 02:09:23 appsrv.(*Application).ServeHTTP(appsrv.go:288)] 8wkyuYQTK40H4vHtu6LZHD2YwbA= 200 2da694 GET /hosts?details=true&enabled=1&host_type=hypervisor&limit=1024&offset=0&scope=system (10.3.0.1:35372:monitor) 1.79ms<br/>[info 2023-12-12 02:09:25 cloudprovider.WaitStatus(waitstatus.go:31)] xutest2 status allocate expect ready

![image](https://github.com/yunionio/cloudpods/assets/70850653/a604061e-2ac1-470d-9c73-167ab639a9a4)

**Comment by ioito** [comment]
报权限错误的是尝试创建企业项目https://console.huaweicloud.com/apiexplorer/#/openapi/EPS/doc?api=CreateEnterpriseProject失败，这个不影响资源的创建，只是会记录一个日志，这个本意是想把创建的eip放置到对应的企业项目里面

**Comment by xzzdhq** [comment]
感谢大佬，
