### ISSUE TITLE
[求助/Help] 创建NAT网关没有平台和区域可以选

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#18960]
![image](https://github.com/yunionio/cloudpods/assets/70850653/87e22bf5-b987-4c22-a869-8a249f22e0b9)

**Comment by ioito** [comment]
查看下录入的云账号底下是否有vpc及ip子网 @xzzdhq

**Comment by xzzdhq** [comment]
看了，vpc以及ip子网都是有的，是不是最后一张图的权限不足问题导致的呢
![image](https://github.com/yunionio/cloudpods/assets/70850653/706d05ee-ee02-461b-9180-e8e9a95433af)
![image](https://github.com/yunionio/cloudpods/assets/70850653/3f93a824-15c1-42f6-bf7c-d4416db7c1e9)
![image](https://github.com/yunionio/cloudpods/assets/70850653/41b19180-bc0a-48ae-bf92-1fa95453a374)
![image](https://github.com/yunionio/cloudpods/assets/70850653/e76be4e7-7ebf-4851-9ebe-20440d4513f2)

![image](https://github.com/yunionio/cloudpods/assets/70850653/f921f910-e292-4712-b444-c250daeb8974)

**Comment by ioito** [comment]
<img width="804" alt="image" src="https://github.com/yunionio/cloudpods/assets/13750250/1a18df02-c9e8-4a61-8c7d-7db2031ac842">
是你选择的域底下没有可用的子网及vpc，切到default域应该就可以

**Comment by xzzdhq** [comment]
default域下也是空的，然后查看 vpc以及子网都在 default 域下面，
![image](https://github.com/yunionio/cloudpods/assets/70850653/f12fb21e-bd1f-4565-a67d-dc37871ddaa2)

![image](https://github.com/yunionio/cloudpods/assets/70850653/58629a27-59d7-4e85-a2b3-3e8fd744e6b8)

**Comment by GuoLiBin6** [comment]
前端过滤平台时错误导致未正确显示，已修复：https://github.com/yunionio/dashboard/pull/5763
