### ISSUE TITLE
[求助/Help]cloupods3.10.8版本切换 Influxdb 到 VictoriaMetrics遇到问题

### ISSUE THREAD

**Issue by ives-66** [yunionio/cloudpods#18964]
![8941702360463_ pic](https://github.com/yunionio/cloudpods/assets/74636037/5ccf6753-4e43-42ee-b67d-bb7bb0f7838e)

**Comment by zexi** [comment]
@ives-66 是第一次执行 patch 的命令吗？这个看起来已经 disable influxdb 了，patch 完后不会删除 influxdb pod 的，需要参考[这个文档](https://v2.cloudpods.org/docs/operations/monitoring/migrating-to-vm#%E5%88%A0%E9%99%A4-influxdb-%E6%9C%8D%E5%8A%A1)手动删除。

**Comment by ives-66** [comment]
我还想问下，删除切换不会有其他影响的吧？

**Comment by zexi** [comment]
> 我还想问下，删除切换不会有其他影响的吧？

@ives-66 相关内容都写到这个文档里面了，可以先看下：https://v2.cloudpods.org/docs/operations/monitoring/migrating-to-vm

切换默认不会迁移原来的 influxdb 的监控数据，如果需要迁移监控数据，可以参考文档里面的方法迁移。其他的影响应该没有了。

**Comment by ives-66** [comment]
好的，感谢你
