### ISSUE TITLE
检测IPMI配置失败[求助/Help]

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#18972]
检测IPMI配置失败
probing=>probe_fail: {"__reason__":"self.sendIpmiNicInfo: SendNicInfo: {\"error\":{\"class\":\"BadRequestError\",\"code\":400,\"details\":\"IP 0.0.0.0 not attach to any wire\",\"request\":{\"body\":\"{\\\"host\\\":{\\\"ip_addr\\\":\\\"0.0.0.0\\\",\\\"link_up\\\":true,\\\"mac\\\":\\\"b4:05:5d:04:a5:b6\\\",\\\"mtu\\\":1500,\\\"nic_type\\\":\\\"ipmi\\\",\\\"...erve\\\":true,\\\"reset\\\":true}}\",\"headers\":{\"Content-Length\":\"168\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Yunion-Parent-Id\":\"\",\"X-Yunion-Peer-Service-Name\":\"baremetal\",\"X-Yunion-Remote-Addr\":\"default-region:30888\",\"X-Yunion-Span-Id\":\"0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"d09cbb85\"},\"method\":\"POST\",\"url\":\"https://default-region:30888/hosts/5b219f43-2ca6-4422-8577-28693fd27eb2/add-netif\"}}}","__stage__":"OnSyncConfigComplete","__status__":"error"}

<img width="562" alt="image" src="https://github.com/yunionio/cloudpods/assets/32296103/eb2d4f9a-caee-4466-bc93-02ee3d98e9ee">

**Comment by zexi** [comment]
@shengxianli 登录到物理机上，执行 `ipmitool lan print` 看下输出的是什么？
