### ISSUE TITLE
[求助/Help] ocboot add-node 宿主机的host.conf文件是怎么获取的？

### ISSUE THREAD

**Issue by enhellowhy** [yunionio/cloudpods#18994]
ocboot add-node 宿主机的host.conf文件是怎么获取的？想修改下这个host.conf的模板配置。

**Comment by zexi** [comment]
@enhellowhy 这个目前是通过 ocadm join 的时候自动生成的，代码在这个地方：https://github.com/yunionio/ocadm/blob/master/pkg/util/onecloud/onecloud.go#L376-L435

建议你可以通过修改 ocboot 里面的 ansible task ，去变更 host.conf ，然后再重启下上面的 host 容器就行了。

**Comment by enhellowhy** [comment]
收到，感谢~~
