### ISSUE TITLE
dhcp不回包[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19026]
纳管物理机过程中，有一台gpu机器是双网卡，我们在纳管过程中发现，这台机器的dhcp的请求发到了server端，但dhcp server报错 没有回包：
这台物理机网关是129, 地址是167，所在地址池 GuestIpStart:"10.60.36.165", GuestIpEnd:"10.60.36.174"  也完全匹配。
![image](https://github.com/yunionio/cloudpods/assets/17080656/70986f93-6cd3-4e1a-a2bd-f25e9b911786)
tcpdump抓包结果：
![image](https://github.com/yunionio/cloudpods/assets/17080656/800c374f-1eaf-4160-bbd5-1bdada396321)

**Comment by zexi** [comment]
@tianchao001 错误的原因是因为没有在平台找到 `e8:eb:d3:12:b3:d6` mac 地址的物理机记录。
创建物理机的时候有没有指定这个 mac 地址？

**Comment by tianchao001** [comment]
> @tianchao001 错误的原因是因为没有在平台找到 `e8:eb:d3:12:b3:d6` mac 地址的物理机记录。 创建物理机的时候有没有指定这个 mac 地址？

创建物理机的时候 并没有指定mac地址，但问题是 如果我们指定了这个mac地址，后续转裸金属时 启用bond0 会影响吗？因为我们在上次创建这台物理机时指定了这个mac地址，转裸金属时会报
  - 'Failed: p-hbhl-a800-7003:44137715-a739-44a4-8c64-2838079bcea7 [net_bonding] net_bonding:
    Not enough netifs for bonding, require 2 netifs, max count 1'

**Comment by zexi** [comment]
> > @tianchao001 错误的原因是因为没有在平台找到 `e8:eb:d3:12:b3:d6` mac 地址的物理机记录。 创建物理机的时候有没有指定这个 mac 地址？
> 
> 创建物理机的时候 并没有指定mac地址，但问题是 如果我们指定了这个mac地址，后续转裸金属时 启用bond0 会影响吗？因为我们在上次创建这台物理机时指定了这个mac地址，转裸金属时会报
> 
> * 'Failed: p-hbhl-a800-7003:44137715-a739-44a4-8c64-2838079bcea7 [net_bonding] net_bonding:
>   Not enough netifs for bonding, require 2 netifs, max count 1'

@tianchao001 看这个情况是需要指定 mac 地址才行，如果有两张网卡都查了网线，应该不会影响做 bond0 。

**Comment by tianchao001** [comment]
> > > @tianchao001 错误的原因是因为没有在平台找到 `e8:eb:d3:12:b3:d6` mac 地址的物理机记录。 创建物理机的时候有没有指定这个 mac 地址？
> > 
> > 
> > 创建物理机的时候 并没有指定mac地址，但问题是 如果我们指定了这个mac地址，后续转裸金属时 启用bond0 会影响吗？因为我们在上次创建这台物理机时指定了这个mac地址，转裸金属时会报
> > 
> > * 'Failed: p-hbhl-a800-7003:44137715-a739-44a4-8c64-2838079bcea7 [net_bonding] net_bonding:
> >   Not enough netifs for bonding, require 2 netifs, max count 1'
> 
> @tianchao001 看这个情况是需要指定 mac 地址才行，如果有两张网卡都查了网线，应该不会影响做 bond0 。

那我指定mac地址，然后再测试一下转裸金属，有问题我再来求助，多谢老哥回复。
