### ISSUE TITLE
[求助/Help]ubuntu 2022.04 编译host image编译报错

### ISSUE THREAD

**Issue by nyl1001** [yunionio/cloudpods#19024]
报错信息如下：make image host-image VERSION=v3.10.8
mkdir -p /root/cloudpods/_output

Start to build component: host-image
make[1]: Entering directory '/root/cloudpods'
go build -mod vendor -ldflags "-w -X yunion.io/x/pkg/util/version.gitVersion=master-20230911.0-497-g4cb021916520a5 -X yunion.io/x/pkg/util/version.gitCommit=4cb0219165 -X yunion.io/x/pkg/util/version.gitBranch=master -X yunion.io/x/pkg/util/version.buildDate=2023-12-18T02:09:41Z -X yunion.io/x/pkg/util/version.gitTreeState=dirty -X yunion.io/x/pkg/util/version.gitMajor=0 -X yunion.io/x/pkg/util/version.gitMinor=0" -o /root/cloudpods/_output/bin/host-image yunion.io/x/onecloud/cmd/host-image
# runtime/cgo
/usr/bin/ld: cannot find -lqemuio: No such file or directory
/usr/bin/ld: cannot find -lgnutls: No such file or directory
/usr/bin/ld: cannot find -lqemuio: No such file or directory
/usr/bin/ld: cannot find -lgnutls: No such file or directory

本人参照https://github.com/yunionio/qemu 编译了qemu，LIBQEMUIO_PATH也指向了qemu根目录，但是编译依然报上述错误，尝试安装了各种依赖包，依然不能解决问题。

**Comment by nyl1001** [comment]
感觉贵司开源给人犹抱琵琶半遮面的感觉，回答issue遮遮掩掩的，关于host image编译的那两个issue 都没有给出完整的解决方法，这是啥原因呢

**Comment by swordqiu** [comment]
@nyl1001 多谢反馈。我们自己根据文档验证一下，如果有文档不够清晰的地方，我们尽快修正。

**Comment by zexi** [comment]
类似的问题还有 https://github.com/yunionio/cloudpods/issues/18094 ，编译出 libqemuaio.a 后，再制作 host-image 容器镜像会遇到下面的问题。

![img_v3_0268_084bcfcb-1384-43dd-afd3-e465c4ca263g](https://github.com/yunionio/cloudpods/assets/10767027/c37b5776-bcd6-4856-a767-4c78f60baed3)

**Comment by wanyaoqi** [comment]
@nyl1001 @zexi @swordqiu  https://github.com/yunionio/qemu/tree/stable-2.12  请使用这个分支，这个功能是基于 qemu 2.12 开发的

**Comment by zexi** [comment]
建议专门写2篇如何编译 qemu 和 libqemuaio 的文档到开发手册里面。
qemu 编译是 4.2 的版本，libqemuaio 又是基于 2.12 的版本，看这个 https://github.com/yunionio/qemu/blob/main/README.md 不清楚。

**Comment by nyl1001** [comment]
> @nyl1001 @zexi @swordqiu https://github.com/yunionio/qemu/tree/stable-2.12 请使用这个分支，这个功能是基于 qemu 2.12 开发的

一样报错，请问LIBQEMUIO_PATH到底设置多少，你们都没有回答

**Comment by zexi** [comment]
@nyl1001 参考这个 PR 的文档步骤试试能否编译出来？https://github.com/yunionio/website/pull/69
