### ISSUE TITLE
[求助/Help]  裸金属/物理机/回收站  无法删除，命令行也无法删除

### ISSUE THREAD

**Issue by ccbutcc** [yunionio/cloudpods#19025]
1. 物理机正常进入 ramfs 后，正常注册
2. 新建裸金属 ，进入裸金属创建过程
3. 裸金属创建过程过长 ，超过半个小时，遂删除
4. 重建无法成功找不到存储选项， 发现需要清理回收站， 在回收站内发现刚删除的裸金属
5. 遂删除回收站内的裸金属， 状态始终处于删除中
6. 尝试删除物理机， 命令行方式，提示非空无法删除

请问怎么样让这台物理机恢复到最初状态，重新进入ramfs系统引导 , 然后重新创建裸金属

感谢！

**Comment by zexi** [comment]
> 3. 裸金属创建过程过长 ，超过半个小时，遂删除
这个可以用 `climc host-ssh $物理机名称或id` 进入到  ramfs 里面，再执行 `ps faux` 看下有什么进程在跑，一般时间都会花在 `wget 下载镜像上`，如果装机的镜像太大，就会比较耗时，根据网络环境决定的。

> 请问怎么样让这台物理机恢复到最初状态，重新进入ramfs系统引导 , 然后重新创建裸金属
执行下面的命令强制清理数据库记录，然后重启 baremetal-agent 服务：
```bash
# 找到回收站里面的裸金属，并删除掉
climc server-list --pending-delete
climc server-purge $裸金属id

# 删除物理机记录
climc host-disable $物理机id
climc host-purge $物理机id

# 重启 baremetal-agent 服务
kubectl rollout restart deployment -n onecloud default-baremetal-agent
```

等待 baremetal-agent pod 重启后，重新 pxe 引导物理机创建裸金属。@ccbutcc

**Comment by ccbutcc** [comment]
好的。感谢。已解决该问题。 裸金属始终处于 `部署中`， 这又该看哪个组件日志呢， 此时观察我的物理机，仍处于 ·yunoinos· 没有出现装系统的相关变化

**Comment by zexi** [comment]
> 好的。感谢。已解决该问题。 裸金属始终处于 `部署中`， 这又该看哪个组件日志呢， 此时观察我的物理机，仍处于 ·yunoinos· 没有出现装系统的相关变化

@ccbutcc 用 `climc host-ssh $物理机id` 登录到 ramfs 里面，然后用 `ps faux` 看下，应该有 `wget` 进程在下载镜像。
如果要看部署日志，就用 `kubectl logs` 看 default-baremetal-agent  pod 的日志。

**Comment by ccbutcc** [comment]
裸金属长时间维护中又是什么引起的， raid 存储一直在 初始化中， 是否和存储的raid 有关

**Comment by ccbutcc** [comment]
装机不选择raid ， 裸金属创建不会卡住， 但是会循环安装 YunionOS , 安装时选择的系统镜像没有效果，请问是什么原因

**Comment by zexi** [comment]
> 装机不选择raid ， 裸金属创建不会卡住， 但是会循环安装 YunionOS , 安装时选择的系统镜像没有效果，请问是什么原因

@ccbutcc 裸金属现在什么状态？只有裸金属状态为“运行中”的状态，才会从磁盘引导启动。

**Comment by ccbutcc** [comment]
处于运行中状态， 不知道啥原因安装完成后 自动重启的 进入了PXE， 我手动阻断PXE,再在页面点击裸金属重启 成功的进入了我安装的系统。

**Comment by zexi** [comment]
> 处于运行中状态， 不知道啥原因安装完成后 自动重启的 进入了PXE， 我手动阻断PXE,再在页面点击裸金属重启 成功的进入了我安装的系统。

装完系统后，自动重启进入 pxe 应该也没问题，平台这边会返回一个从磁盘引导的 grub 配置文件。可以重启下 baremetal-agent ，然后再 pxe 启动一次，应该会看到一个 grub 的配置界面，然后会自动查找磁盘上的系统启动。

**Comment by ccbutcc** [comment]
1.  请问 由于通过 cloudpods 创建 raid会卡住， 换用其它平台创建RAID并提前做好， 再在cloudpods 创建裸金属选择 不做RAID 。 发现创建后 RAID 被删除

2.  在对网卡进行 bond 时， 如何自定义 bond 类型



谢谢！

**Comment by zexi** [comment]
> 1. 请问 由于通过 cloudpods 创建 raid会卡住， 换用其它平台创建RAID并提前做好， 再在cloudpods 创建裸金属选择 不做RAID 。 发现创建后 RAID 被删除，  请问这个情况如何处理

@ccbutcc 现在的流程是必须通过我们做 RAID 盘，不支持提前做好拿来用。可以用 `climc host-ssh $物理机id` 登录到 yunionos 系统里面，调用 /opt 下面的 raid 制作工具看下是哪个地方卡住了。

> 2. 在对网卡进行 bond 时， 如何自定义 bond 类型

现在 bond 默认就是 mode4 ，不支持其他类型。
