### ISSUE TITLE
转裸金属网卡bond失败[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19030]
一台物理机是双网卡，在纳管时需要绑定其中一张网卡的mac地址才可以纳管成功，但纳管成功后在转裸金属时启用网卡bond0会报错：
'Failed: p-hbhl-a800-7003:36402f89-4a5d-4f5d-86cf-57b1822fffcc [net_bonding] net_bonding:
    Not enough netifs for bonding, require 2 netifs, max count 1
    
![image](https://github.com/yunionio/cloudpods/assets/17080656/3a96c96a-df42-4090-b279-6448de61b6f8)

   我们确认了两张网卡都是通的，因为在纳管时，如果不绑定mac地址 两张网卡都能发dhcp请求到dhcp server端。

**Comment by zexi** [comment]
@tianchao001 我记得好像修复过类似的问题，你们用的哪个版本？

**Comment by tianchao001** [comment]
> @tianchao001 我记得好像修复过类似的问题，你们用的哪个版本？

现在升级到3.9.13了
补充一下这台服务器的网卡物理信息
![image](https://github.com/yunionio/cloudpods/assets/17080656/ba5f2d87-a105-46e0-8c6a-7b63320d439a)

**Comment by zexi** [comment]
@tianchao001 另外你可以在物理机二层网络，那里手动给一张网卡关联二层网络，手动设置关联后，就可以做 bonding 了。

**Comment by tianchao001** [comment]
> @tianchao001 另外你可以在物理机二层网络，那里手动给一张网卡关联二层网络，手动设置关联后，就可以做 bonding 了。

是关联那张没有指定mac地址的网卡对吗？ 另外 如果要彻底解决这个问题，建议升级到哪个版本呀？

**Comment by zexi** [comment]
<img width="1346" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/51adf761-e157-4479-b858-ce162fdfc103">
@tianchao001 在前端这个位置，先手动给另外一张网卡设置二层网络后，再试试 bonding 。

**Comment by tianchao001** [comment]
> <img alt="image" width="1346" src="https://private-user-images.githubusercontent.com/10767027/291188257-51adf761-e157-4479-b858-ce162fdfc103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODY1ODgsIm5iZiI6MTcwMjg4NjI4OCwicGF0aCI6Ii8xMDc2NzAyNy8yOTExODgyNTctNTFhZGY3NjEtZTE1Ny00NDc5LWI4NTgtY2UxNjJmZGZjMTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZWEyY2ZlZTE2NTg3OGI5ZGYyOWU3MjkyODBjMzE2YTQ2YTFhN2Q1YzkzMDY5MjI1NTk1Mjc2ZWUzYTA0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VcWlIPcHmqcWA9BWG2Y95awRLzbzg8cech2KjwkugJw"> @tianchao001 在前端这个位置，先手动给另外一张网卡设置二层网络后，再试试 bonding 。

好的，我试试。
