### ISSUE TITLE
[求助/Help] 容器下新建集群, 控制节点创建失败

### ISSUE THREAD

**Issue by guinanlin** [yunionio/cloudpods#19045]
操作文档:
https://www.cloudpods.org/v3.9/zh/docs/web_ui/docker/cluster/k8s-cluster/

我这边的版本是 3.9.4

操作路径:
![image](https://github.com/yunionio/cloudpods/assets/44794953/18d239d3-45f7-401d-bfe2-c8ef4fb2d812)

虚拟机没有创建起来:
![image](https://github.com/yunionio/cloudpods/assets/44794953/39e4991e-b50c-484a-938e-72a1239dadf1)

日志内容: 没有看懂, 帮忙分析一下可能原因是什么?
{
    "__reason__": {
        "reason": "{\"__reason__\":{\"reason\":{\"__reason__\":{\"reason\":\"{\\\"__reason__\\\":{\\\"reason\\\":\\\"{\\\\\\\"__reason__\\\\\\\":\\\\\\\"prepare resource: Wait server 50168d88-a8c5-4ad3-88b8-dd5c8360370c running error: Object server: 50168d88-a8c5-4ad3-88b8-dd5c8360370c/d01-controlplane-m27z-0 status is \\\\\\\\\\\\\\\"sched_fail\\\\\\\\\\\\\\\", can't wait\\\\\\\",\\\\\\\"__stage__\\\\\\\":\\\\\\\"OnPrepared\\\\\\\",\\\\\\\"__status__\\\\\\\":\\\\\\\"ERROR\\\\\\\"}\\\",\\\"stage\\\":\\\"OnPrepared\\\"},\\\"__stage__\\\":\\\"OnMachinePrepared\\\",\\\"__status__\\\":\\\"error\\\",\\\"__task_name__\\\":\\\"MachinePrepareTask\\\"}\",\"stage\":\"OnMachinePrepared\"},\"__stage__\":\"OnMachinesCreated\",\"__status__\":\"error\",\"__task_name__\":\"MachineCreateTask\"},\"stage\":\"OnMachinesCreated\"},\"__stage__\":\"OnMachinesCreated\",\"__status__\":\"error\",\"__task_name__\":\"MachineBatchCreateTask\"}",
        "stage": "OnMachinesCreated"
    },
    "__stage__": "OnMachinesCreated",
    "__status__": "error",
    "__task_name__": "ClusterCreateMachinesTask"
}`
`

**Comment by zexi** [comment]
@guinanlin 到虚拟机界面，看下 d01-controlplane-m27z-0 这台虚拟机的操作日志

**Comment by guinanlin** [comment]
> @guinanlin 到虚拟机界面，看下 d01-controlplane-m27z-0 这台虚拟机的操作日志

这台的日志:
`[
    "No matching resources",
    "{\"error\":{\"code\":400,\"details\":\"Error #01: genericScheduler.Schedule: No resource are avaliable that match all of the following predicates: filter by host_storage(-1), session_id=\\\"1702952755037\\\"\\n\",\"request\":{\"body\":\"{\\\"backup\\\":false,\\\"best_effort\\\":false,\\\"change_config\\\":false,\\\"count\\\":1,\\\"details\\\":false,\\\"disks\\\":[{\\\"backe...ount\\\":2,\\\"vmem_size\\\":4096}\",\"headers\":{\"Content-Length\":\"2082\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Request-Id\":\"0bba70\",\"X-Yunion-Lang\":\"en\",\"X-Yunion-Parent-Id\":\"0\",\"X-Yunion-Peer-Service-Name\":\"compute_v2\",\"X-Yunion-Remote-Addr\":\"default-scheduler:30887\",\"X-Yunion-Span-Id\":\"0.0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"fee73493\"},\"method\":\"POST\",\"url\":\"https://default-scheduler:30887/scheduler\"}}}"
]`

**Comment by zexi** [comment]
@guinanlin 看起来是存储不够了，可以用下面的命令看下详细的调度日志：
```bash
climc scheduler-history-show --log --raw 1702952755037
```

**Comment by guinanlin** [comment]
> @guinanlin 看起来是存储不够了，可以用下面的命令看下详细的调度日志：
> 
> ```shell
> climc scheduler-history-show --log --raw 1702952755037
> ```

调整了一下存储, 虚拟机那边的确创建起来了. 但是创建集群的时候还是报错. 
这次倒是显示证书过期了.

`{
    "__reason__": {
        "reason": "{\"__reason__\":{\"reason\":{\"__reason__\":{\"reason\":\"{\\\"__reason__\\\":\\\"Get \\\\\\\"https://192.168.8.97:6443/version?timeout=30s\\\\\\\": x509: certificate has expired or is not yet valid: current time 2023-12-19T04:54:10Z is before 2023-12-19T05:18:40Z\\\",\\\"__stage__\\\":\\\"OnSyncStatus\\\",\\\"__status__\\\":\\\"ERROR\\\"}\",\"stage\":\"OnSyncStatus\"},\"__stage__\":\"OnSyncStatusComplete\",\"__status__\":\"error\",\"__task_name__\":\"ClusterSyncstatusTask\"},\"stage\":\"OnSyncStatusComplete\"},\"__stage__\":\"OnMachinesDeployed\",\"__status__\":\"error\",\"__task_name__\":\"ClusterDeployMachinesTask\"}",
        "stage": "OnMachinesDeployed"
    },
    "__stage__": "OnMachinesCreated",
    "__status__": "error",
    "__task_name__": "ClusterCreateMachinesTask"
}`

**Comment by guinanlin** [comment]
> > @guinanlin 看起来是存储不够了，可以用下面的命令看下详细的调度日志：
> > ```shell
> > climc scheduler-history-show --log --raw 1702952755037
> > ```
> 
> 调整了一下存储, 虚拟机那边的确创建起来了. 但是创建集群的时候还是报错. 这次倒是显示证书过期了.
> 
> `{ "__reason__": { "reason": "{\"__reason__\":{\"reason\":{\"__reason__\":{\"reason\":\"{\\\"__reason__\\\":\\\"Get \\\\\\\"https://192.168.8.97:6443/version?timeout=30s\\\\\\\": x509: certificate has expired or is not yet valid: current time 2023-12-19T04:54:10Z is before 2023-12-19T05:18:40Z\\\",\\\"__stage__\\\":\\\"OnSyncStatus\\\",\\\"__status__\\\":\\\"ERROR\\\"}\",\"stage\":\"OnSyncStatus\"},\"__stage__\":\"OnSyncStatusComplete\",\"__status__\":\"error\",\"__task_name__\":\"ClusterSyncstatusTask\"},\"stage\":\"OnSyncStatusComplete\"},\"__stage__\":\"OnMachinesDeployed\",\"__status__\":\"error\",\"__task_name__\":\"ClusterDeployMachinesTask\"}", "stage": "OnMachinesDeployed" }, "__stage__": "OnMachinesCreated", "__status__": "error", "__task_name__": "ClusterCreateMachinesTask" }`

后来倒腾了一下, 这个 x509 是因为 控制节点的时间 与 宿主机的时间不一致导致的. 
调整了一下, 已经能正常跑了. 感谢.
