### ISSUE TITLE
[求助/Help]请问一下LIBQEMUIO_PATH这个环境变量该如何设置

### ISSUE THREAD

**Issue by nyl1001** [yunionio/cloudpods#19058]
按照你们的操作文档 https://github.com/yunionio/qemu编译得到了libqemuio.a，但是一直没有告诉我们如何设置LIBQEMUIO_PATH。
麻烦贵司撰写操作文档走点儿心可以吗？

**Comment by swordqiu** [comment]
@nyl1001 没人有义务走心，请给开源贡献的人以必要的尊重。

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/blob/3f10e5adad8438affbb00aa776179f17fc781f22/Makefile#L50-L53
@nyl1001 你在问 LIBQEMUIO_PATH 应该阅读过 Makefile
如果你阅读过 Makefile的话就应该知道 LIBQEMUIO_PATH 设置的是静态链接库的路径。
所以你需要了解一下静态链接库的路径如何设置，其实就是你编译的 qemu 目录的路径。如果还不知道就搜索一下C语言静态链接库 。

然后友情提示 qemu 编译的时候我们是放在 src 目录下，所以你也需要把 qemu 源码放在 src 目录下，或者你可以修改 Makefile 去掉 LIBQEMUIO_PATH 后面跟着的 src。

或者你等几天，我们正在写如何编译 host-image 的文档，到时候可以跟着一步一步操作。

**Comment by nyl1001** [comment]
> https://github.com/yunionio/cloudpods/blob/3f10e5adad8438affbb00aa776179f17fc781f22/Makefile#L50-L53
> 
> 
> @nyl1001 你在问 LIBQEMUIO_PATH 应该阅读过 Makefile
> 如果你阅读过 Makefile的话就应该知道 LIBQEMUIO_PATH 设置的是静态链接库的路径。
> 所以你需要了解一下静态链接库的路径如何设置，其实就是你编译的 qemu 目录的路径。如果还不知道就搜索一下C语言静态链接库 。
> 然后友情提示 qemu 编译的时候我们是放在 src 目录下，所以你也需要把 qemu 源码放在 src 目录下，或者你可以修改 Makefile 去掉 LIBQEMUIO_PATH 后面跟着的 src。
> 
> 或者你等几天，我们正在写如何编译 host-image 的文档，到时候可以跟着一步一步操作。

设置为qemu目录的路径，这个我都试过，编译一样报错，能试的肯定都试过，不然不会跑这里来求助

**Comment by nyl1001** [comment]
> @nyl1001 没人有义务走心，请给开源贡献的人以必要的尊重。

你真牛，老6

**Comment by nyl1001** [comment]
> > https://github.com/yunionio/cloudpods/blob/3f10e5adad8438affbb00aa776179f17fc781f22/Makefile#L50-L53
> > 
> > @nyl1001 你在问 LIBQEMUIO_PATH 应该阅读过 Makefile
> > 如果你阅读过 Makefile的话就应该知道 LIBQEMUIO_PATH 设置的是静态链接库的路径。
> > 所以你需要了解一下静态链接库的路径如何设置，其实就是你编译的 qemu 目录的路径。如果还不知道就搜索一下C语言静态链接库 。
> > 然后友情提示 qemu 编译的时候我们是放在 src 目录下，所以你也需要把 qemu 源码放在 src 目录下，或者你可以修改 Makefile 去掉 LIBQEMUIO_PATH 后面跟着的 src。
> > 或者你等几天，我们正在写如何编译 host-image 的文档，到时候可以跟着一步一步操作。
> 
> 设置为qemu目录的路径，这个我都试过，编译一样报错，能试的肯定都试过，不然不会跑这里来求助

我编译的时候，确实也用src目录包了一层，还是报错

**Comment by nyl1001** [comment]
这是操作的截图：
<img width="1264" alt="image" src="https://github.com/yunionio/cloudpods/assets/5603342/82e23de6-0156-4c0b-aa2b-e7c6e628ce65">

**Comment by zexi** [comment]
和 https://github.com/yunionio/cloudpods/issues/19024 是相同问题，此问题先关闭。
