### ISSUE TITLE
版本升级过程中遇到问题[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19055]
在3.9.13升级到3.10.7过程中，我们有一台主机在TASK [upgrade/common : Upgrade common packages 步骤出现失败，失败原因是域名解析失败，这台失败的机器是我们3台k8s 底座 master之一，但并不是升级时指定的master ，请问有影响吗？
另外， 有什么办法重试吗？
![image](https://github.com/yunionio/cloudpods/assets/17080656/48fd02c4-fac7-4302-a82a-4d68b7c2526d)

**Comment by zhasm** [comment]
@tianchao001 
以centos为例，试试执行以下命令：
```bash
yum update -y yunion-ocadm yunion-climc yunion-climc-ee yunion-executor yunion-qemu-4.2.0 openvswitch
```

**Comment by tianchao001** [comment]
> @tianchao001 以centos为例，试试执行以下命令,看看有什么报错：
> 
> ```shell
> yum install -y yunion-ocadm yunion-climc yunion-climc-ee yunion-executor yunion-qemu-4.2.0 openvswitch
> ```
> 
> 另外,如果mirrors.tencentyun.com 的源已经无法使用，可以将其禁用。

OK  我试下，多谢大佬

**Comment by tianchao001** [comment]
> @tianchao001 以centos为例，试试执行以下命令,看看有什么报错：
> 
> ```shell
> yum install -y yunion-ocadm yunion-climc yunion-climc-ee yunion-executor yunion-qemu-4.2.0 openvswitch
> ```
> 
> 另外,如果mirrors.tencentyun.com 的源已经无法使用，可以将其禁用。

我看了下 有两个节点的成功任务数比较低，我如果再执行一遍ocboot 是不是可行的？

**Comment by tianchao001** [comment]
> @tianchao001 以centos为例，试试执行以下命令,看看有什么报错：
> 
> ```shell
> yum install -y yunion-ocadm yunion-climc yunion-climc-ee yunion-executor yunion-qemu-4.2.0 openvswitch
> ```
> 
> 另外,如果mirrors.tencentyun.com 的源已经无法使用，可以将其禁用。

我看了下 有两个节点的成功任务数比较低，我如果再执行一遍ocboot 是不是可行的？

**Comment by zhasm** [comment]
@tianchao001 
可以的, ocboot 的升级命令可以反复执行, 无副作用.

**Comment by tianchao001** [comment]
好的， 谢谢。

**Comment by zhasm** [comment]
@tianchao001 不客气, 无论解决与否, 都期望得到您的反馈~
