### ISSUE TITLE
[BUG]如果纳管的云平台宿主机存储过大，则无法写入数据库，导致无法同步宿主机

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#19060]
**问题描述/What happened**:
不能同步宿主机的原因是 hosts 表的storage_size 类型太小了。导致同步时报错。解决方法是将类型改为int64,需要改动的地方很多
**环境/Environment**:
v3.10.7 8 
<img width="1006" alt="e4178299b27c7e54bbd133889b54043" src="https://github.com/yunionio/cloudpods/assets/29140975/cc36c01a-57d0-4244-a835-1f8b33554faf">

**Comment by ioito** [comment]
fixed #19085 64位系统下go的int可以储存64位大小的数字，默认的mysql int(11)会越界

**Comment by zexi** [comment]
@hewenxiang 已修复，下周会发布 v3.10.9 版本，到时候升级就可以了。
