### ISSUE TITLE
[求助/Help]关于外部访问虚拟机的网络问题

### ISSUE THREAD

**Issue by TracyBin** [yunionio/cloudpods#19066]
场景：使用场景为公司内部私有云，通过cloudpods管理公司内部的物理机资源。公司网络管理员给我们分配了多个与物理机同网段的IP地址，供虚拟化使用，之前一直使用EXSI虚拟化，是可以正常访问虚拟机

问题描述：cloudpods环境下，将公司分配的与物理机同网段的多个IP地址，作为经典网络的IP子网网段作弹性公网IP池使用。根据文档描述，需要在物理机接入三层交换机增加路由，配置EIP网关为弹性公网IP地址段的下一条地址。因公司三层交换机没有权限进行更改，在这种情况下，有没有网络方案可以实现外部网络访问虚拟机

**Comment by TracyBin** [comment]
换了一台宿主机后 ，虚拟机能够在外部访问了。具体解决方案为将宿主机和虚拟机放到同一个二层子网中。
但另外一台宿主机为EXSI虚拟机(启用了嵌套虚拟化)，其上的虚拟机与宿主机同一个二层子网，但无法与宿主机通信，外部也无法访问，问题原因还在排查中

**Comment by TracyBin** [comment]
确认是嵌套虚拟化问题

**Comment by swordqiu** [comment]
1. 如果虚拟机使用VPC网络，则需要外部需要通过EIP访问虚拟机。如果不能在路由器上设置路由，并且要访问EIP的节点和EIP网关在一个二层网络的话，可以在节点上配置一个静态路由，也能实现。只是这种配置方式只能对该节点有效。
2. 你说的第二种情况是虚拟机使用经典网络，这种自然能够实现外部访问虚拟机。

**Comment by TracyBin** [comment]
> 1. 如果虚拟机使用VPC网络，则需要外部需要通过EIP访问虚拟机。如果不能在路由器上设置路由，并且要访问EIP的节点和EIP网关在一个二层网络的话，可以在节点上配置一个静态路由，也能实现。只是这种配置方式只能对该节点有效。
> 2. 你说的第二种情况是虚拟机使用经典网络，这种自然能够实现外部访问虚拟机。

是的，qiu老师，宿主机是物理机的场景下使用经典网络没问题，但有宿主机是EXSI虚拟机的场景下，经典网络似乎失效了，嵌套创建出来的虚拟机无法从外部访问
