### ISSUE TITLE
[BUG]调度数据库编码问题

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#19097]
**问题描述/What happened**:
v3.10.8
如果创建的标签是中文，那么在修改动态调度标签时报错
**环境/Environment**:
![image](https://github.com/yunionio/cloudpods/assets/29140975/6feb8b65-b216-46d5-91bf-bdfcb9e627f8)

**Comment by swordqiu** [comment]
@hewenxiang 

这个PR修复
https://github.com/yunionio/sqlchemy/pull/176

等待合并后 cloudpods更新vendor
