### ISSUE TITLE
如何提升虚拟机网卡速率？[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19092]
我们遇到一个虚拟机网卡速率无法提升的问题，虽然我们在cloudpods控制台将虚拟机带宽修改为0(不限制)，但实际使用iperf压测发现 虚拟机带宽仍然无法超过8Gb/s，更多时间只能到6.5Gb/s。我们查看了网卡队列数，发现最高只能设置到16，哪怕机器配置提升到64C，网卡队列数也无法进一步提升，请问还有其他办法提升虚拟机网卡速率吗？
截图：
![image](https://github.com/yunionio/cloudpods/assets/17080656/db694445-136b-46c6-9a5b-403b060a1553)
![image](https://github.com/yunionio/cloudpods/assets/17080656/791782ae-0aec-46c7-bed0-df07194e697a)

**Comment by swordqiu** [comment]
@tianchao001 可以考虑用SR-IOV网卡: https://v2.cloudpods.org/docs/guides/onpremise/vminstance/passthrough/sriov
