### ISSUE TITLE
裸金属重装系统不成功[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19101]
我们有一台裸金属服务器，在控制台关机后点击重装系统，由centos 改为ubuntu系统，通过观察 重装完成后，控制台的系统图标确实改为ubuntu了。
并且整个重装过程也确实有通过ipmi操作 pxe启动 与进入yun os等步骤，同时 baremetal-agent 日志也输出了通过ssh pxe ip yum os进行主机命名、网卡配置等信息，通过BMC 远程查看，服务器也确实是在yun os下 在执行一系列的配置动作。

但是再次触发重启后，裸金属服务器仍然实际还是centos老系统，系统环境一点也没改变。
而在执行 delete baremetal-agent  pod 后，再次重装系统，重装完成后，却能成功进入新ubuntu系统，请问这是什么原因导致的？

**Comment by zexi** [comment]
@tianchao001 没有遇到过这种情况，看下每块盘上面有没有旧的 centos 系统？

**Comment by tianchao001** [comment]
> @tianchao001 没有遇到过这种情况，看下每块盘上面有没有旧的 centos 系统？

我检查了一下，因为我们的ssd是两块盘 一块sda  一块sdb，我发现 这次新系统是装在sda3上的，但是sdb盘也被分区了，我尝试挂载sdb的盘到目录下 进入看了下 发现 有一个 一模一样的系统目录（也是新系统目录结构），因为这台机器我们重装了好几次，所以我推测  是不是以前的系统重装都被装到了sdb上，唯独在我重启baremetal-agent pod后，系统被安装到了sda盘上？

**Comment by zexi** [comment]
> > @tianchao001 没有遇到过这种情况，看下每块盘上面有没有旧的 centos 系统？
> 
> 我检查了一下，因为我们的ssd是两块盘 一块sda 一块sdb，我发现 这次新系统是装在sda3上的，但是sdb盘也被分区了，我尝试挂载sdb的盘到目录下 进入看了下 发现 有一个 一模一样的系统目录（也是新系统目录结构），因为这台机器我们重装了好几次，所以我推测 是不是以前的系统重装都被装到了sdb上，唯独在我重启baremetal-agent pod后，系统被安装到了sda盘上？

@tianchao001 有没有手动换过 ssd 盘？系统一般只会装到 sda 或者是根据创建时选择的规格的盘上，不会随机安装。

**Comment by tianchao001** [comment]
> > > @tianchao001 没有遇到过这种情况，看下每块盘上面有没有旧的 centos 系统？
> > 
> > 
> > 我检查了一下，因为我们的ssd是两块盘 一块sda 一块sdb，我发现 这次新系统是装在sda3上的，但是sdb盘也被分区了，我尝试挂载sdb的盘到目录下 进入看了下 发现 有一个 一模一样的系统目录（也是新系统目录结构），因为这台机器我们重装了好几次，所以我推测 是不是以前的系统重装都被装到了sdb上，唯独在我重启baremetal-agent pod后，系统被安装到了sda盘上？
> 
> @tianchao001 有没有手动换过 ssd 盘？系统一般只会装到 sda 或者是根据创建时选择的规格的盘上，不会随机安装。

这个并没有手动换过，我们有个raid卡，实际也是通过raid卡识别ssd的，只不过 我们没有装raid，直接用的单盘方式。在创建裸金属时，实际每次也只能看到一块ssd盘的容量信息，每次选择也只能选ssd 并不能选定是哪块ssd。

**Comment by zexi** [comment]
> 这个并没有手动换过，我们有个raid卡，实际也是通过raid卡识别ssd的，只不过 我们没有装raid，直接用的单盘方式。在创建裸金属时，实际每次也只能看到一块ssd盘的容量信息，每次选择也只能选ssd 并不能选定是哪块ssd。

@tianchao001 这种情况就是默认选择装到  /dev/sda 上面了，不过你说 sdb 上也有系统，确实有可能在引导的时候出现引导到 sdb 上启动，这种情况可以先清理掉 sdb 上的系统，保证只有一块盘上有系统，就不会出现引导的问题了。

**Comment by tianchao001** [comment]
> > 这个并没有手动换过，我们有个raid卡，实际也是通过raid卡识别ssd的，只不过 我们没有装raid，直接用的单盘方式。在创建裸金属时，实际每次也只能看到一块ssd盘的容量信息，每次选择也只能选ssd 并不能选定是哪块ssd。
> 
> @tianchao001 这种情况就是默认选择装到 /dev/sda 上面了，不过你说 sdb 上也有系统，确实有可能在引导的时候出现引导到 sdb 上启动，这种情况可以先清理掉 sdb 上的系统，保证只有一块盘上有系统，就不会出现引导的问题了。

后续如果还是两块ssd的机器 在重装系统时，有办法避免装错盘吗？比如有没有命令行重装系统 可以指定到盘符的方式~

**Comment by zexi** [comment]
> 后续如果还是两块ssd的机器 在重装系统时，有办法避免装错盘吗？比如有没有命令行重装系统 可以指定到盘符的方式~
目前是当时选择根据盘的型号，还有 raid 驱动来辨别的，如果两块盘一模一样，就会选择当时在 yunionos 系统中的 sda 盘作为系统盘，现在不支持选择装到指定的 sdX 这种方式。
