### ISSUE TITLE
VMware迁移到KVM平台失败

### ISSUE THREAD

**Issue by CloudCourierStation** [yunionio/cloudpods#19115]
![image](https://github.com/yunionio/cloudpods/assets/33771248/92f24bf1-1226-41b4-9195-8808cf037ef7)
![image](https://github.com/yunionio/cloudpods/assets/33771248/06c357c2-4439-4d4f-919b-54d07cd97373)
{
    "__reason__": "create disk 10b8eac6-c1f7-4b1e-8450-3d192e6b7a93 failed: create_raw: Fail to create disk: create image failed: qemu-img: /opt/cloud/workspace/disks/10b8eac6-c1f7-4b1e-8450-3d192e6b7a93: Backing file specified without backing format\nDetected format of raw.\n: exit status 1",
    "__stage__": "OnHostCreateGuest",
    "__status__": "error"
}

这是缺少了什么条件吗？

**Comment by wanyaoqi** [comment]
@CloudCourierStation 你使用的是哪个版本的 cloudpods，环境信息可以描述一下。
如果是3.10.8 可以更新一下 host-deployer 
```bash
$ kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/hostdeployer/imageName, value: host-deployer},{op: replace, path: /spec/hostdeployer/repository, value: [registry.cn-beijing.aliyuncs.com/yunionio](http://registry.cn-beijing.aliyuncs.com/yunionio)},{op: add, path: /spec/hostdeployer/tag, value: v3.11-20231226181054-solo}]'
```

**Comment by CloudCourierStation** [comment]
@wanyaoqi 换上v3.11-20231226181054-solo这个之后，host-deployer报错sh: line 1: virtlogd: command not found
![image](https://github.com/yunionio/cloudpods/assets/33771248/8a470e5b-90b6-4d55-8c08-7e9b6941f77a)

**Comment by wanyaoqi** [comment]
@CloudCourierStation 你需要提供一下你的 cloudpods 版本信息

**Comment by CloudCourierStation** [comment]
@wanyaoqi v3.10.3-20230614.0

**Comment by wanyaoqi** [comment]
> @wanyaoqi v3.10.3-20230614.0

@CloudCourierStation 哦那需要同时更新一下 onecloud-operator
```
kubectl -n onecloud set image deployment/onecloud-operator onecloud-operator=registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.10-20231227162536-solo
```

问一下宿主机上的 qemu 是什么版本，之前遇到过类似的问题是高版本的 qemu-img 需要指定 backing-file 的格式。


如果需要还原host-deployer:
```bash
$ kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/hostdeployer/imageName, value: host-deployer},{op: replace, path: /spec/hostdeployer/repository, value: [registry.cn-beijing.aliyuncs.com/yunionio](http://registry.cn-beijing.aliyuncs.com/yunionio)},{op: add, path: /spec/hostdeployer/tag, value: v3.10.3-20230614.0}]'
```

**Comment by CloudCourierStation** [comment]
@wanyaoqi  我更新了operator之后还是会报sh: line 1: virtlogd: command not found这个错误

**Comment by wanyaoqi** [comment]
@CloudCourierStation 更新 operator 后host-deployer 会重建，已经重建了吗

**Comment by CloudCourierStation** [comment]
@wanyaoqi 更新operator之后host-deployer有重启过了，但是错误跟之前的错误依然是一样的，还有一行错误报错是：
[debug 2023-12-28 07:27:05 procutils.(*Command).Output(procutils.go:98)] Execute command "stat -c {\"file_size\":%s,\"file_name\":\"%n\",\"file_type\":\"%F\"} /opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc" , error: exit status 1 , output: stat: cannot statx '/opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc': No such file or directory

**Comment by wanyaoqi** [comment]
> @wanyaoqi 更新operator之后host-deployer有重启过了，但是错误跟之前的错误依然是一样的，还有一行错误报错是： [debug 2023-12-28 07:27:05 procutils.(*Command).Output(procutils.go:98)] Execute command "stat -c {"file_size":%s,"file_name":"%n","file_type":"%F"} /opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc" , error: exit status 1 , output: stat: cannot statx '/opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc': No such file or directory

@CloudCourierStation 我们本地验证一下

**Comment by CloudCourierStation** [comment]
> @wanyaoqi 更新operator之后host-deployer有重启过了，但是错误跟之前的错误依然是一样的，还有一行错误报错是： [debug 2023-12-28 07:27:05 procutils.(*Command).Output(procutils.go:98)] Execute command "stat -c {"file_size":%s,"file_name":"%n","file_type":"%F"} /opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc" , error: exit status 1 , output: stat: cannot statx '/opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc': No such file or directory

@wanyaoqi 这一行日志是host报的，我还需要更新一下host测试一下吗？

**Comment by wanyaoqi** [comment]
> > @wanyaoqi 更新operator之后host-deployer有重启过了，但是错误跟之前的错误依然是一样的，还有一行错误报错是： [debug 2023-12-28 07:27:05 procutils.(*Command).Output(procutils.go:98)] Execute command "stat -c {"file_size":%s,"file_name":"%n","file_type":"%F"} /opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc" , error: exit status 1 , output: stat: cannot statx '/opt/cloud/workspace/disks/dc536cbc-8b04-4dec-826c-86af68fd55cc': No such file or directory
> 
> @wanyaoqi 这一行日志是host报的，我还需要更新一下host测试一下吗？

@CloudCourierStation 我们在本地环境测试没有复现这个问题，需要打开 debug 日志排查一下
开启 debug 日志：
```bash
$ kubectl edit cm -n onecloud default-host
log_level: debug # 日志级别改成 debug
# 重启 host
$ kubectl rollout restart ds -n onecloud default-host
$ 重启 host-deployer
$ kubectl rollout restart ds -n onecloud default-host-deployer
```
再试一下，如果还不行的话再导出日志看下
`kubectl logs -n onecloud -c host <HOST_POD>  > host.log`
`kubectl logs -n onecloud <HOST+DEPLOYER_POD>  > host-deployer.log`
