### ISSUE TITLE
[求助/Help]host-image编译依旧报错，按照你们最新提供的编译指导文档操作依然无法成功编译

### ISSUE THREAD

**Issue by nyl1001** [yunionio/cloudpods#19121]
这是报错信息：
<img width="1407" alt="image" src="https://github.com/yunionio/cloudpods/assets/5603342/d211c17d-64b5-40d8-8b62-b94c61a114c4">
 这是你们的指导文档，文档中存在明显错误：
<img width="1768" alt="image" src="https://github.com/yunionio/cloudpods/assets/5603342/4e59c00d-a12f-4cfa-95d8-2b3e93cb3c4f">

**Comment by wanyaoqi** [comment]
fixed: https://github.com/yunionio/website/pull/84/files

**Comment by nyl1001** [comment]
文档依然有错误，另外ubuntu下编译依然失败

**Comment by zexi** [comment]
@nyl1001 编译报什么错误，麻烦把相关错误信息截图或者文字贴上来。

**Comment by wanyaoqi** [comment]
> fixed: https://github.com/yunionio/website/pull/84/files

我验证没有问题

**Comment by wanyaoqi** [comment]
> > fixed: https://github.com/yunionio/website/pull/84/files
> 
> 我验证没有问题

<img width="896" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/0b4bfa8c-b546-4470-a11f-c48b5e467e6d">

这部分都是在容器里面执行

**Comment by nyl1001** [comment]
试了很多次，压根儿就没有编译成功过，麻烦帮忙看下这是什么原因：
<img width="1327" alt="image" src="https://github.com/yunionio/cloudpods/assets/5603342/16a848ed-16e8-4895-b891-0ce8ffb2bf87">

**Comment by wanyaoqi** [comment]
@nyl1001 贴一下你的详细操作步骤？我这边测试没有问题

**Comment by nyl1001** [comment]
> @nyl1001 贴一下你的详细操作步骤？我这边测试没有问题

![image](https://github.com/yunionio/cloudpods/assets/5603342/453c76a1-2919-4b15-8323-3c10b8419418)

**Comment by nyl1001** [comment]
git clone -b stable-2.12 https://gitlab.com/qemu-project/qemu.git
wget https://raw.githubusercontent.com/yunionio/qemu/stable-2.12/0001-patch-for-2.12.patch
cd qemu && mkdir src && mv ./* src/
cd src && git apply ../../0001-patch-for-2.12.patch
cd ../

# 这里 /root/cloudpods 为本地 cloudpods 路径，需替换成本地相应的 cloudpods 路径
docker run --network host -v $(pwd):/root/qemu -v /root/cloudpods:/go/src/yunion.io/x/cloudpods -it golang:1.18.10-buster

# 容器内：
sed -i 's|http://deb.debian.org|http://mirrors.aliyun.com|g' /etc/apt/sources.list
apt-get update
apt-get install -y gcc make git vim python pkg-config flex bison libpixman-1-dev libudev-dev libaio-dev libcurl4-openssl-dev zlib1g-dev libglib2.0-dev libusb-1.0-0-dev libusbredirparser-dev libusbredirhost-dev libcapstone-dev libcephfs-dev librbd-dev librados-dev libspice-server-dev libspice-protocol-dev
cd /root/qemu/src
./configure --target-list=$(uname -m)-softmmu --enable-libusb --extra-ldflags=-lrt --enable-spice --enable-rbd
# 编译 libqemuio.a
make libqemuio.a
# 继续在容器内部执行
apt install -y file gnutls-bin libgnutls30 libgnutls28-dev
cd /go/src/yunion.io/x/cloudpods
# 编译 host-image
# LIBQEMUIO_PATH=/root/qemu make cmd/host-image
# ./scripts/bundle_libraries.sh _output/bin/bundles/host-image _output/bin/host-image
LIBQEMUIO_PATH=/root/qemu make image host-image VERSION=v3.10.8

**Comment by nyl1001** [comment]
git clone -b stable-2.12 https://gitlab.com/qemu-project/qemu.git
wget https://raw.githubusercontent.com/yunionio/qemu/stable-2.12/0001-patch-for-2.12.patch
cd qemu && mkdir src && mv ./* src/
cd src && git apply ../../0001-patch-for-2.12.patch
cd ../

# 这里 /root/cloudpods 为本地 cloudpods 路径，需替换成本地相应的 cloudpods 路径
docker run --network host -v $(pwd):/root/qemu -v /root/cloudpods:/go/src/yunion.io/x/cloudpods -it golang:1.18.10-buster

# 容器内：
sed -i 's|http://deb.debian.org|http://mirrors.aliyun.com|g' /etc/apt/sources.list
apt-get update
apt-get install -y gcc make git vim python pkg-config flex bison libpixman-1-dev libudev-dev libaio-dev libcurl4-openssl-dev zlib1g-dev libglib2.0-dev libusb-1.0-0-dev libusbredirparser-dev libusbredirhost-dev libcapstone-dev libcephfs-dev librbd-dev librados-dev libspice-server-dev libspice-protocol-dev
cd /root/qemu/src
./configure --target-list=$(uname -m)-softmmu --enable-libusb --extra-ldflags=-lrt --enable-spice --enable-rbd
# 编译 libqemuio.a
make libqemuio.a
# 继续在容器内部执行
apt install -y file gnutls-bin libgnutls30 libgnutls28-dev
cd /go/src/yunion.io/x/cloudpods
# 编译 host-image
# LIBQEMUIO_PATH=/root/qemu make cmd/host-image
# ./scripts/bundle_libraries.sh _output/bin/bundles/host-image _output/bin/host-image
LIBQEMUIO_PATH=/root/qemu make image host-image VERSION=v3.10.8

**Comment by wanyaoqi** [comment]
<img width="801" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/2ebb27c0-fa2e-4dbf-88a0-e277cef10f83">
首先你确认libqemuio.a是否编译成功。
然后这个是我的编译记录：
<img width="1920" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/3f72e765-0d0d-48f8-a2cc-09e38333b372">
