### ISSUE TITLE
[求助/Help]想请教一下，创建vmware虚拟机失败，报错分配磁盘报错

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19123]
创建vmware 虚拟机，报错 fail to find valid ESXi agent 
查看之前一样报错的issue  https://github.com/yunionio/cloudpods/issues/18152 
但是看见 esxi-agent 是没有日志的
![image](https://github.com/yunionio/cloudpods/assets/70850653/80943b3c-2275-4b21-9cf7-937dcde08fb9)
![企业微信截图_17036684359326](https://github.com/yunionio/cloudpods/assets/70850653/b51ff5dc-c3f0-4a9d-a278-5493e6d6c8cf)
![image](https://github.com/yunionio/cloudpods/assets/70850653/53640a22-f3e1-492a-9d1f-1e586a399d4f)

**Comment by xzzdhq** [comment]
想问一下，和我zone的 可用宿主机/物理机有关嘛
![image](https://github.com/yunionio/cloudpods/assets/70850653/74267477-3e8e-4616-bd81-c26acfa645ba)

**Comment by ioito** [comment]
是和zone有关

**Comment by xzzdhq** [comment]
请教一下，看了一下代码，是判断状态，为enable才不会报错，esxi-agent在数据库中的状态是为disable，请问下，esxi-agent 只能创建一个嘛，以及只会和zone0进行绑定吗、

我其实已经创建了可用的zone 本地AZ1，但是 essxi-agent 还是只有一个 ，不知道什么情况，以及我是docker compose安装情况下，按照下面文档进行zone的安装，是否就能解决问题呢

![image](https://github.com/yunionio/cloudpods/assets/70850653/1a902d72-1026-42a8-ac72-c9e09d0b5783)

https://v2.cloudpods.org/docs/operations/multi-zone-config#%E7%89%A9%E7%90%86%E6%9C%BA%E7%AE%A1%E7%90%86%E6%9C%8D%E5%8A%A1baremetal-agent-%E5%92%8Cvmware%E7%AE%A1%E7%90%86%E6%9C%8D%E5%8A%A1esxi-agent

![image](https://github.com/yunionio/cloudpods/assets/70850653/897e096d-03c0-4a80-b1df-1aeb12f8a48f)

**Comment by zexi** [comment]
@xzzdhq docker-compse 部署的目前只支持一个 zone ，最新的 v3.10.10 版本 docker-compse 已经可以运行 esxi-agent 管理 vmware 了。
另外 esxi agent 可用区这个问题我测试下，可能是有问题，建议先使用 zone0 可用区的 esxi-agent ，前端可以对 zone0 进行改名，但不要删除这个默认 zone0 ，很多服务的 endpoint 是默认关联到这个 zone0 的。
