### ISSUE TITLE
[求助/Help]误删了宿主机上面某个虚拟机文件目录

### ISSUE THREAD

**Issue by enhellowhy** [yunionio/cloudpods#19132]
请问如果误删了宿主机上面的虚拟机文件目录，有没有什么办法恢复？虚拟机状态显示未知，进程也不在了。

**Comment by swordqiu** [comment]
@enhellowhy 如果只是删除了 /opt/cloud/workspace/servers/<sid> 这个目录，那可以尝试恢复。首先创建该目录，在目录下新建一个名称为desc的文件，重启host服务，然后尝试开机试试。

**Comment by enhellowhy** [comment]
已恢复，非常感谢~
