### ISSUE TITLE
[求助/Help]创建zstack虚拟机失败

### ISSUE THREAD

**Issue by ninghongwu** [yunionio/cloudpods#19136]
更新到3.10.10，可以识别出sharedblock了。选择本地云盘创建是成功的，但是选择sharedblock创建不了

问题背景麻烦看下这个issue，谢谢

https://github.com/yunionio/cloudpods/issues/18773

**Comment by ioito** [comment]
https://www.zstack.io/help/product_manuals/cli_manual/v4/4.2.html#chapter-4-2-4-3-2-%E6%9F%A5%E8%AF%A2%E4%B8%BB%E5%AD%98%E5%82%A8-QueryPrimaryStorage
通过官方的命令行查询主存储的列表，参数需要传下 zone.cluster.uuid 及 zone.uuid 截图看下返回结果 @ninghongwu
