### ISSUE TITLE
[求助/Help]虚拟机无法访问外网

### ISSUE THREAD

**Issue by hf43hf** [yunionio/cloudpods#19142]
求助。。。。
ocboot部署all in one
局域网主路由网段：192.168.0.0/16，网关：192.168.50.1
宿主机ip：192.168.50.107
创建了一个vpc网络：172.16.0.0/24
经典网络创建了一个弹性ip池：192.168.51.1-192.168.51.254 网关：192.168.50.1
经过上面的配置后，创建的虚拟机无法访问外网，弹性ip也无法访问

**Comment by swordqiu** [comment]
@hf43hf 首先确保 宿主机 192.168.50.107 可以访问外网，新建一台VPC虚拟机，不挂EIP，是否可以访问外网？

**Comment by hf43hf** [comment]
> 新建一台VPC虚拟机，不挂EIP，是否可以访问外网？

你好，宿主机可以访问外网，新建的vpc虚拟机不挂弹性ip也不能访问外网。这是我的vpc网络和虚拟机：
![2231703936596_ pic](https://github.com/yunionio/cloudpods/assets/39023384/9fd606d4-4aaf-4e7a-a412-1a29e17992c1)

![2251703936705_ pic](https://github.com/yunionio/cloudpods/assets/39023384/be9673e8-333e-4754-be75-4ad8bdfb5bbb)
![2241703936673_ pic](https://github.com/yunionio/cloudpods/assets/39023384/c5b2f7c4-5203-44ca-86a6-0091ea818cac)

**Comment by hf43hf** [comment]
> > 新建一台VPC虚拟机，不挂EIP，是否可以访问外网？
> 
> 你好，宿主机可以访问外网，新建的vpc虚拟机不挂弹性ip也不能访问外网。这是我的vpc网络和虚拟机： ![2231703936596_ pic](https://private-user-images.githubusercontent.com/39023384/293458600-9fd606d4-4aaf-4e7a-a412-1a29e17992c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzcxMDMsIm5iZiI6MTcwMzkzNjgwMywicGF0aCI6Ii8zOTAyMzM4NC8yOTM0NTg2MDAtOWZkNjA2ZDQtNGFhZi00ZTdhLWE0MTItMWEyOWUxNzk5MmMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGQ0OTY0NThmOGZlZWFkY2JjNTBlMDYyNzM0Y2I2ZWJhNjQwNmM3MTEzMzAyM2FmODI1ZDJiMGMzMzVkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQkrdxi4L392oLYdpNJpx7XeU_1ASxJW30-FBgxGFWI)
> 
> ![2251703936705_ pic](https://private-user-images.githubusercontent.com/39023384/293458622-be9673e8-333e-4754-be75-4ad8bdfb5bbb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzcxMDMsIm5iZiI6MTcwMzkzNjgwMywicGF0aCI6Ii8zOTAyMzM4NC8yOTM0NTg2MjItYmU5NjczZTgtMzMzZS00NzU0LWJlNzUtNGFkOGJkZmI1YmJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3M2QyMjVmZDU5ZDY1NWRjODNiOWY2ZTMzZjNhYjBlYWI2Zjc5MzJmZWUyOGZmNmFlZDZiMGQ4ZjA5MGI2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4fjtpyFCJm3kuhKxNH1lEeF4-F5t4nhIusW1Wq7Cn8) ![2241703936673_ pic](https://private-user-images.githubusercontent.com/39023384/293458628-c5b2f7c4-5203-44ca-86a6-0091ea818cac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzcxMDMsIm5iZiI6MTcwMzkzNjgwMywicGF0aCI6Ii8zOTAyMzM4NC8yOTM0NTg2MjgtYzViMmY3YzQtNTIwMy00NGNhLTg2YTYtMDA5MWVhODE4Y2FjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZjRhMzIxN2FkZTI4MDAzMzA2OGU0ZDY4MDIyZWJlZDhiZDg2ZmU5NjNlMjI0MDU4OGY4MTUyNjAyYzhiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_uxVyERWlD0CnZl7QVdwXIYT-x8oOoQbb4yKkf0jXM)

![2261703936846_ pic](https://github.com/yunionio/cloudpods/assets/39023384/1c3aefe5-ea50-4395-8ef1-2d7589b60984)

**Comment by hf43hf** [comment]
<img width="835" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/45fb8634-f9fe-4051-a0ee-02c507228ef7">
vpc网段使用172.16.0.0/12，虚拟机无法获取到vpc ip

**Comment by swordqiu** [comment]
@hf43hf 这是vpcagent有问题，可以看下vpcagent的日志是否有报错。

**Comment by hf43hf** [comment]
> @hf43hf 这是vpcagent有问题，可以看下vpcagent的日志是否有报错。

<img width="1278" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/6c8202c2-840b-4aaf-8b24-b64919fae80f">
这是vpcagentde的日志，麻烦老师看一看

**Comment by swordqiu** [comment]
@hf43hf 这个报错是说 名称为 vpc-vpc 的二层网络的 vpc (id 为 2b9c8203-4f9b-4532-87aa-bb449c13bb39 )不存在，是数据库数据不一致了。尝试删除这个 二次网络：

```
# 先 wire-list 找到这个 vpc-vpc 二次网络的id
climc wire-list --scope system --search vpc-vpc --show-emulated
# 删除这个二层网络
climc wire-delete <wire_id>
```

**Comment by hf43hf** [comment]
> @hf43hf 这个报错是说 名称为 vpc-vpc 的二层网络的 vpc (id 为 2b9c8203-4f9b-4532-87aa-bb449c13bb39 )不存在，是数据库数据不一致了。尝试删除这个 二次网络：
> 
> ```
> # 先 wire-list 找到这个 vpc-vpc 二次网络的id
> climc wire-list --scope system --search vpc-vpc --show-emulated
> # 删除这个二层网络
> climc wire-delete <wire_id>
> ```

vpc-vpc这个网络之前从管理台删除过了，climc wire-list --scope system --show-emulated中看不到这个vpc。
<img width="1459" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/21b4a359-a9f1-4b6d-afcf-c335c267fb94">

**Comment by swordqiu** [comment]
@hf43hf 请先重启vpcagent解决

**Comment by hf43hf** [comment]
> @hf43hf 请先重启vpcagent解决

重启后vpc可以正常分配ip了，但是虚拟机还是无法访问外网。
<img width="1060" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/c127bff4-0c5e-4fe8-b771-89f1e8ac5c73">
<img width="1464" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/0e2a01a5-a11b-42d0-976e-55117bd724ed">

**Comment by swordqiu** [comment]
@hf43hf 这是因为域名解析有问题，请看下虚拟机内 /etc/resolve.conf 查看分配的dns服务器地址，验证从虚拟机内是否可以访问这个dns服务器。

**Comment by hf43hf** [comment]
> /etc/resolve.conf

虚拟机内没有这个目录。
<img width="1103" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/3b1be230-4a40-44d1-89f2-027e0531f353">

**Comment by swordqiu** [comment]
@hf43hf 请参考这个文档 https://www.cloudpods.org/docs/guides/onpremise/network/dns 是否改了dns的设置？

**Comment by hf43hf** [comment]
> https://www.cloudpods.org/docs/guides/onpremise/network/dns

请问是这个地方的配置吗？
<img width="1565" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/ef0668aa-ef3e-4966-910f-5505058d7305">

**Comment by hf43hf** [comment]
> > https://www.cloudpods.org/docs/guides/onpremise/network/dns
> 
> 请问是这个地方的配置吗？ <img alt="image" width="1565" src="https://private-user-images.githubusercontent.com/39023384/293533777-ef0668aa-ef3e-4966-910f-5505058d7305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODEwMzMsIm5iZiI6MTcwNDA4MDczMywicGF0aCI6Ii8zOTAyMzM4NC8yOTM1MzM3NzctZWYwNjY4YWEtZWYzZS00OTY2LTkxMGYtNTUwNTA1OGQ3MzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDAzNDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MzE5NjE2NTY4NGU2MTA2ZWVhMjFlNzIwMDJlNzk4YjVjYzg4OWE2YWFlNmEyMTg0YzBlYTI5ZmJlZTFhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t7xydQw8h5_6M1nx6moy-0fNFBdb7DChR7UdCYxs3rs">

老师，我在vpc子网中设置了域名服务器ip后，虚拟机内可以访问外网了，但是绑定浮动ip后就无法访问外网了，浮动ip子网的域名服务器ip与vpc的域名服务器ip设置的同一个ip

**Comment by hf43hf** [comment]
<img width="1284" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/2a60ff2c-76a6-4b7e-a3f6-aa7bb25a78d0">
这是我的浮动ip配置

**Comment by swordqiu** [comment]
@hf43hf 绑定浮动IP对浮动IP在物理网络的路由有要求，请参考 https://www.cloudpods.org/docs/guides/onpremise/network/vpc/eipgwhowto

**Comment by hf43hf** [comment]
> @hf43hf 绑定浮动IP对浮动IP在物理网络的路由有要求，请参考 https://www.cloudpods.org/docs/guides/onpremise/network/vpc/eipgwhowto

按照文档将浮动ip设置为跟主路由不同的网段并在主路由添加了静态路由，浮动ip可以被ping通了，但是局域网环境无法通过浮动ip登录到虚拟机，宿主机上可以通过浮动ip登录到虚拟机，麻烦看下是哪里的问题呢？

**Comment by swordqiu** [comment]
@hf43hf 应该是局域网跟宿主机不在一个网段，你配置的静态路由只在宿主机所在网段生效了。路由需要全局一致，一般需要网络管理员全局统一设置。

**Comment by hf43hf** [comment]
> @hf43hf 应该是局域网跟宿主机不在一个网段，你配置的静态路由只在宿主机所在网段生效了。路由需要全局一致，一般需要网络管理员全局统一设置。

我是在主路由上添加的全局静态路由，应该是全局生效的吧，局域网是能ping通浮动ip，但是无法通过浮动ip ssh登录虚拟机。这是我的配置：
<img width="1081" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/06ae3e97-c3b5-4189-add3-e97eac29aa42">
<img width="1019" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/29b1ffb4-865e-484b-8d29-7cb1997f0f76">
<img width="1522" alt="image" src="https://github.com/yunionio/cloudpods/assets/39023384/501b467b-28ba-4bd0-a7f9-54a1c0163f2c">

**Comment by DSYZayn** [comment]
我也遇到虚拟机无法访问外网的问题，宿主机可以访问外网，虚拟机（使用Ubuntu-jammy-server-cloudimg-amd64）使用vpc网络,相关信息如下：
![image](https://github.com/yunionio/cloudpods/assets/98650340/894ab9ee-d832-48c9-b36e-fc2aa799333a)
![image](https://github.com/yunionio/cloudpods/assets/98650340/6c4ad521-ac08-436f-8962-3f4929a0b444)
![image](https://github.com/yunionio/cloudpods/assets/98650340/561d4368-aa03-4108-a39c-4f8f3b382c70)
另外，在多云管理这里报了一个域名配置错误如下，不知道是否相关：
![image](https://github.com/yunionio/cloudpods/assets/98650340/d65ae769-62ef-4ac8-8a3b-d60cc54d5f78)

已知没有更改过虚拟机的`/etc/resolv.conf`, 宿主机的`/etc/resolv.conf`更改如下：
![image](https://github.com/yunionio/cloudpods/assets/98650340/2f5db611-5631-456d-b11a-2b3461dc3c8b)

**Comment by DSYZayn** [comment]
在多次尝试重启，关机虚拟机，绑定解绑EIP之后，发现解绑EIP可以访问外网了，参考了这个问题#16466
