### ISSUE TITLE
[求助/Help] centos7.6安装内核重启后网卡无法启动

### ISSUE THREAD

**Issue by hf43hf** [yunionio/cloudpods#19141]
通过./run.py -m https://mirrors.aliyun.com/pypi/simple/ full命令安装完内核重启后网卡不工作

**Comment by swordqiu** [comment]
@hf43hf 请执行 lspci | grep -i Ethernet 看下具体网卡型号

**Comment by hf43hf** [comment]
> @hf43hf 请执行 lspci | grep -i Ethernet 看下具体网卡型号

![Uploading 2221703856471_.pic.jpg…]()

**Comment by hf43hf** [comment]
> @hf43hf 请执行 lspci | grep -i Ethernet 看下具体网卡型号
这是我的网卡型号
![2221703856471_ pic](https://github.com/yunionio/cloudpods/assets/39023384/084b18fe-db44-49db-810b-4d382266a1e3)

**Comment by swordqiu** [comment]
@hf43hf 你要不切回原装的内核，如果是Cloudpods 3.10.8之后的版本，用原装内核也是可以正常运行的

**Comment by hf43hf** [comment]
> @hf43hf 你要不切回原装的内核，如果是Cloudpods 3.10.8之后的版本，用原装内核也是可以正常运行的

好的，我试下

**Comment by hf43hf** [comment]
> @hf43hf 你要不切回原装的内核，如果是Cloudpods 3.10.8之后的版本，用原装内核也是可以正常运行的

你好3.10.8之后的版本安装方式是不一样了吗？我从标签3.10.11中没有看到run.py文件呢？官网中有没有看到对应的文档

**Comment by swordqiu** [comment]
@hf43hf 按这样步骤：1. 重启切换内核到原生内核，网络已经就可以使用。2. 在线升级到3.10.10，参考：https://www.cloudpods.org/docs/operations/upgrading/ocboot-upgrade
