### ISSUE TITLE
[求助/Help] Can't deploy on Ubuntu22.04.3LTS bare metal.

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#19149]
# Issue
I try to deploy cloudpods with `all in one` on a bare metal(Ubuntu 22.04.3 LTS),and it reports erros as follows:
![image](https://github.com/yunionio/cloudpods/assets/98650340/e626ed63-d262-4228-b5e4-d75be103fb70)

I cloned release/3.10 ocboot tools for deploy.

# Machine version
![image](https://github.com/yunionio/cloudpods/assets/98650340/7eadd67f-ba48-4842-a94b-54671fa037fd)

I note that the latest ocboot tools support Ubuntu 22.04 LTS, but I used to encountered many errors like `can't found python3-pyyaml` and `can't find ansible` etc. Every practice was followed wtth the official doc:
![image](https://github.com/yunionio/cloudpods/assets/98650340/c034ea35-4492-417e-a5e5-989ae8dbabfd)

**Comment by DSYZayn** [comment]
I successfully deploy an `all in one` cloudpods, but I failed to add compute nodes, it reports errors as follows:
![image](https://github.com/yunionio/cloudpods/assets/98650340/1aea69e6-a39c-405b-83a0-455a4cef3c11)

**Comment by DSYZayn** [comment]
After edit /etc/yunion/host.conf with #18796 on the compute node and delete related pods,I met errors as follows:
![image](https://github.com/yunionio/cloudpods/assets/98650340/5bc2be0f-ae76-4b54-9400-78024f8c9274)

**Comment by zexi** [comment]
> After edit /etc/yunion/host.conf with #18796 on the compute node and delete related pods,I met errors as follows: ![image](https://private-user-images.githubusercontent.com/98650340/293579738-5bc2be0f-ae76-4b54-9400-78024f8c9274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDQyNzYsIm5iZiI6MTcwNDEwMzk3NiwicGF0aCI6Ii85ODY1MDM0MC8yOTM1Nzk3MzgtNWJjMmJlMGYtYWU3Ni00YjU0LTk0MDAtNzgwMjRmOGM5Mjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEwMTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczODJiNTBiOTAxNGI4MTYzODIzZmE4MGFhZmYyYTczY2E1YjBkZDU3ZjFkYWQ1YjI2ZTNkZjgzOTBmOTZlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKDb0ftT3k6MY2_lZrjf7C4RiRFiO74MNSJQP0t2SqU)

Please make sure the host.conf is a valid YAML format, for example the wrong space or tab indentation can lead to this error.

**Comment by DSYZayn** [comment]
Thanks! After several times reboot host pods,it worked!



---- Replied Message ----
| From | Zexi ***@***.***> |
| Date | 01/01/2024 18:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [yunionio/cloudpods] [求助/Help] Can't deploy on Ubuntu22.04.3LTS bare metal. (Issue #19149) |

After edit /etc/yunion/host.conf with #18796 on the compute node and delete related pods,I met errors as follows:

Please make sure the host.conf is a valid YAML format, for example the wrong space or tab indentation can lead to this error.
