### ISSUE TITLE
[求助/Help]3.10.8版本更新VMware虚拟机密码不生效

### ISSUE THREAD

**Issue by wang1cheng** [yunionio/cloudpods#19158]
对VMware虚机设置密码不生效，查看esxi-agent的日志如下，帮看下是什么原因？

**Comment by wang1cheng** [comment]
![esxi](https://github.com/yunionio/cloudpods/assets/17242040/1c1ad82c-fd62-4d7f-801a-2807bc997f0f)

**Comment by swordqiu** [comment]
@wang1cheng 是不是docker compose部署的？请升级到3.10.10试下

**Comment by wang1cheng** [comment]
是用的helm方式部署的



---原始邮件---
发件人: "Jian ***@***.***&gt;
发送时间: 2024年1月2日(周二) 下午4:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.10.8版本更新VMware虚拟机密码不生效 (Issue #19158)




 
@wang1cheng 是不是docker compose部署的？请升级到3.10.10试下

**Comment by swordqiu** [comment]
@wang1cheng 请升级到 3.10.10 试试

**Comment by wang1cheng** [comment]
好的，这块的处理流程大概是怎样的？可以大致说下吗



---原始邮件---
发件人: "Jian ***@***.***&gt;
发送时间: 2024年1月2日(周二) 下午4:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.10.8版本更新VMware虚拟机密码不生效 (Issue #19158)




 
@wang1cheng 请升级到 3.10.10 试试

**Comment by swordqiu** [comment]
@wang1cheng 是通过host-deployer服务实现密码重置，具体原理参见：https://www.cloudpods.org/docs/guides/onpremise/host/host-deployer

**Comment by sun3book** [comment]
![92b4ae222fd54c4c8ad0ed742eb6d0a](https://github.com/yunionio/cloudpods/assets/48039439/2d73f6d8-b8c3-42f0-9e21-7df37bebaa7e)

升级 3.10.10 也存在同样的问题， ip 和 密码 没有生效进 系统里边。 虚拟机 用的是 windows 2019
在 3.10.6的时候是好用的

**Comment by sun3book** [comment]
重置密码功能，测试了，是可以用的，能生效， 但 ip 还是生效不了

**Comment by wanyaoqi** [comment]
@sun3book @wang1cheng  这个问题修复了,  https://github.com/yunionio/cloudpods/pull/19215
可以先更新一下 host-deployer 镜像： registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:0119-1

**Comment by sun3book** [comment]
> registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:0119-1
换这个镜像可以了，ip 和密码 都生效了。

**Comment by wang1cheng** [comment]
好的，感谢！我试下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.10.8版本更新VMware虚拟机密码不生效 (Issue #19158)




  
registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:0119-1
 换这个镜像可以了，ip 和密码 都生效了。
