### ISSUE TITLE
[求助/Help] cloudid，cloudproxy服务域名解析异常

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#19156]
涉及SSH代理节点，多云管理的模块报错如下：
![image](https://github.com/yunionio/cloudpods/assets/98650340/62099930-dd4c-417c-948c-19964c666f87)
![image](https://github.com/yunionio/cloudpods/assets/98650340/f87abbb4-a182-4069-a196-0143d5b9fe5e)

如何排查这个问题并修复？

**Comment by swordqiu** [comment]
@DSYZayn 先确认服务状态是否正常：

```
kubectl -n onecloud get pods -l app=cloudid
kubectl -n onecloud get pods -l app=cloudproxy
```

**Comment by DSYZayn** [comment]
@swordqiu 执行了这些命令，`No resources found`，这该如何解决？开启多云管理除了参考[隐藏功能配置](https://www.cloudpods.org/docs/operations/hidden-feature-config)还要做什么配置吗？我只执行了`climc feature-config-qcloud --switch on`
![image](https://github.com/yunionio/cloudpods/assets/98650340/2bc86ecc-a244-498f-8441-04ca2acd131a)

**Comment by swordqiu** [comment]
@DSYZayn 理论上应该自动部署上。

请查看一下部署模式：

```
kubectl -n onecloud get oc -o yaml | grep -w productVersion
```

请查看 onecloud-operator 的pod是否有报错：

```
kubectl -n onecloud logs <name_of_onecloud_operator_pod>
```

**Comment by DSYZayn** [comment]
@swordqiu Version:Edge, pod报错如下：
![image](https://github.com/yunionio/cloudpods/assets/98650340/bbcab7c1-64d3-417d-8c2d-3b163a0d42e0)

**Comment by DSYZayn** [comment]
@swordqiu 我刚刚在[私有云-高可用安装-编写部署配置](https://www.cloudpods.org/docs/getting-started/onpremise/ha-ce#%E7%BC%96%E5%86%99%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE)这里看到了关于部署版本的配置选项，我的宿主机是按照[私有云-Ocboot快速安装](https://www.cloudpods.org/docs/getting-started/onpremise/quickstart-virt)一节安装的，现在想在私有云的基础上增加多云管理模块，我想应该属于融合云。该如何增量部署？

**Comment by dengju2020** [comment]
> @swordqiu 我刚刚在[私有云-高可用安装-编写部署配置](https://www.cloudpods.org/docs/getting-started/onpremise/ha-ce#%E7%BC%96%E5%86%99%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE)这里看到了关于部署版本的配置选项，我的宿主机是按照[私有云-Ocboot快速安装](https://www.cloudpods.org/docs/getting-started/onpremise/quickstart-virt)一节安装的，现在想在私有云的基础上增加多云管理模块，我想应该属于融合云。该如何增量部署？ 另外，文档中三个cloudpods版本的Ocboot安装步骤没有区别，版本选项应该在哪里配置？

@DSYZayn 建议重新安装。

**Comment by DSYZayn** [comment]
@dengju2020 很好的建议，具体来说，我通过在控制节点重新执行安装脚本`$ ./run.py -m https://mirrors.aliyun.com/pypi/simple/ full <host_ip>`部署了融合云版本。并且原有的集群仍可用（镜像、虚拟机均未丢失），可以建议作为增量部署的方案之一写入文档，当然这可能需要更多的测试案例来佐证。
据此关闭此问题。
