### ISSUE TITLE
[求助/Help] EIP 绑定 在有些宿主机可以正常访问，有些则不行

### ISSUE THREAD

**Issue by ccbutcc** [yunionio/cloudpods#19159]
> v3.10.8 采用 octboot 高可用部署， 创建两台虚拟机， 分配一个 vpc 私有IP, 同时 绑定一个 弹性IP 到 虚拟机上

   现象：
   
    在部分宿主机上 ， 可以使用弹性IP 访问， 能ping通，正常ssh登录， 可以判断弹性Ip 绑定成功
    在另外一部分宿主机上面， 能 ping通， 但无法 ssh 通，初步判断是在这些机器上  弹性Ip 与虚拟机 没有建立对应关系

  求教 要排查哪些组件， 感谢！

**Comment by ioito** [comment]
host组件里面的sdnagent https://github.com/yunionio/sdnagent 这是sdn的代码仓库
