### ISSUE TITLE
[BUG] win 虚拟机无法登录

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#19161]
**问题描述/What happened**:
使用文档[常用镜像百度网盘提取链接及提取码](https://www.cloudpods.org/docs/guides/onpremise/glance/common-image-url#%E5%B8%B8%E7%94%A8%E9%95%9C%E5%83%8F%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E6%8F%90%E5%8F%96%E9%93%BE%E6%8E%A5%E5%8F%8A%E6%8F%90%E5%8F%96%E7%A0%81)中的windows server 2016镜像创建虚拟机，随机生成密码，用户名为Administrator,输入密码显示不正确（使用VNC发送文字+回车操作）。确认输入密码无误。
此问题如何排查并解决？
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): 宿主机Ubuntu22.04.3
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):cloudpods 3.10.10

**Comment by DSYZayn** [comment]
测试发现在Web界面手动关机并更改密码后，密码正确可以登录。不太明白是哪里的问题

**Comment by swordqiu** [comment]
@DSYZayn 感觉是虚拟机刚创建时刻更改密码失败了，可以提供一下这台虚拟机所在宿主机的 host-deployer 容器的日志，我们分析一下

**Comment by DSYZayn** [comment]
@swordqiu 
host-deployer日志：[host_deployer-mqrgq.txt](https://github.com/yunionio/cloudpods/files/13816866/host_deployer-mqrgq.txt)
虚拟机信息：![image](https://github.com/yunionio/cloudpods/assets/98650340/c4a5b25c-81ac-4664-93c1-a7ec5df4d97f)

**Comment by swordqiu** [comment]
@DSYZayn 日志看上去没有问题，Windows修改密码的原理是植入一个脚本，脚本在windows启动后自动执行，修改密码。植入的操作是成功的。感觉是windows启动后执行脚本有问题。执行脚本的日志在windows的目录是：C:\Windows\mdbg_*  其中*是随机的字符串。可以帮忙把这个脚本日志找出来分析一下脚本未执行成功的原因。

**Comment by DSYZayn** [comment]
@swordqiu 没有找到这个目录，c盘搜索mdbg也没有。尝试销毁后重新起一台随机密码的win虚机，仍然无法使用随机密码登录，关机并手动输入密码后成功登录。是否有其他日志文件可以定位这个问题？win的qcow2镜像资源较少，没有更多的测试资源。

**Comment by ioito** [comment]
改下 /etc/yunion/host.conf 配置文件中的 log_level 变为debug，再创建，发下日志 @DSYZayn

**Comment by DSYZayn** [comment]
@ioito 在其他宿主机创建了一台，仍然有此问题，另外无法访问外网（同子网的其他linux虚拟机可以，宿主机也可以）：
[default-host-deployer-tnrgz.txt](https://github.com/yunionio/cloudpods/files/13868388/default-host-deployer-tnrgz.txt)
![image](https://github.com/yunionio/cloudpods/assets/98650340/6129d6ee-ee02-463d-b707-834c921c4430)

**Comment by wanyaoqi** [comment]
@DSYZayn  这个问题我们环境复现了，应该是个bug，有进展会在这里通知

**Comment by wanyaoqi** [comment]
> 好的，另外这个镜像安装系统后，无法访问外网确认是dns问题，表现为可以访问外网IP但无法正确解析域名，修改dns为10.10.10.10后正常访问。无法确认是镜像问题还是我这里部署的cloudpods平台问题。
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 01/09/2024 19:39 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [yunionio/cloudpods] [BUG] win 虚拟机无法登录 (Issue #19161) | @DSYZayn 这个问题我们环境复现了，应该是个bug，有进展会在这里通知 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@DSYZayn climc network-update --dns <DNS> 可以更新 dns ，新建的虚机有效。
