### ISSUE TITLE
[bug] 系统镜像修改名称，最小磁盘大小，磁盘驱动等属性，使用ImageManager中Update方法

### ISSUE THREAD

**Issue by hidonkey** [yunionio/cloudpods#19166]
[bug] 系统镜像修改名称，最小磁盘大小，磁盘驱动等属性，使用ImageManager中Update方法报错

代码如下：

ImageManager manager = new ImageManager(EndpointType.PublicURL)
JSONObject param = ObjectConvertUtils.objectConvertToJSONObject(boncloudImageUpdate);
 报错行： JSONObject  jsonObject = manager.Update(cloudPodsSessionConfig.getSession(),id, param);

报错问题
com.yunionyun.mcp.mcclient.JSONClientException: {"code":400,"details":"ValidateUpdateData: {\"error\":{\"class\":\"InvalidStatusError\",\"code\":400,\"data\":{\"fields\":[\"active\"],\"id\":\"cannot upload in status %!s(MISSING)\"},\"details\":\"cannot upload in status active\"}}","time":"2024-01-04T15:21:55+08:00","class":"InvalidStatusError"}(400/Bad Request)

**Comment by ioito** [comment]
fixed https://github.com/yunionio/mcclient_java/pull/58
