### ISSUE TITLE
apigateway和web相关组件之间是什么关系？[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19160]
apigateway 和  webconsole与web之间是什么关系？如果我要登录平台，请求是先到哪个组件，最终由哪个组件处理并返回呀?

**Comment by swordqiu** [comment]
@tianchao001 web是一个nginx的容器，托管前端静态资源，apigateway为web提供API服务。apigateway把后端服务的API汇聚起来，给web提供统一的AP入口，统一通过 /api 的路径访问。

**Comment by tianchao001** [comment]
> 

那如果一个用户登录控制台，请求链路应该是 ingress--> web->apigateway->后端服务模块？ 对吗

**Comment by swordqiu** [comment]
@tianchao001 对的

**Comment by tianchao001** [comment]
> @tianchao001 对的

apigateway访问后端服务模块时，是不是也需要携带认证token？，就是说 apigateway需要先访问default-keystone  获取token，然后携带token请求后端服务API？

**Comment by swordqiu** [comment]
@tianchao001 对的。apigateway启动后，会向keystone注册获得一个admin token，后面会以这个token访问后端服务。
default-web是托管前端静态资源的nginx。default-webconsole是提供主机的H5远程终端的后端服务。

**Comment by tianchao001** [comment]
> @tianchao001 对的。apigateway启动后，会向keystone注册获得一个admin token，后面会以这个token访问后端服务。 default-web是托管前端静态资源的nginx。default-webconsole是提供主机的H5远程终端的后端服务。

@swordqiu  那就是说 apigateway的这个admin token 其实是不存在过期时间的，也只会请求一次获取token，后续就会一直用这个admin token 访问后端服务对吗？
那后端服务验证这个token 是每次接受请求apigateway时都去keystone认证吗？ 还是直接自己解码认证了呀？

**Comment by swordqiu** [comment]
@tianchao001 admin token也有时效性，需要定期到keystone更新。用户访问apigateway时，会携带自己的token，apigateway会向keystone验证这个token，验证成功才会继续转发用户请求到指定服务。token验证必须到keystone，但是服务都会缓存验证后的结果，避免频繁向keystone验证同一个token。

**Comment by tianchao001** [comment]
> @tianchao001 admin token也有时效性，需要定期到keystone更新。用户访问apigateway时，会携带自己的token，apigateway会向keystone验证这个token，验证成功才会继续转发用户请求到指定服务。token验证必须到keystone，但是服务都会缓存验证后的结果，避免频繁向keystone验证同一个token。

@swordqiu   就是说  
用户请求到达 apigateway 后 apigateway验证token后，再转发请求到后端指定服务时，那后端指定服务也会验证一遍吗？还是说直接响应？我的困惑点在于 来自apigateway的请求到达后端指定服务时，后端这个服务是不是也会验证来自apigateway的token？
用户请求---->apigateway--->keystone验证token--->apigateway--->后端服务--->响应？
用户请求---->apigateway--->keystone验证token--->apigateway--->后端服务---->keystone验证token--->后端服务--->响应？

**Comment by swordqiu** [comment]
@tianchao001 是的，token在每个服务都要被验证一遍
