### ISSUE TITLE
疑似虚拟机分区BUG[BUG]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19162]
虚拟机系统 centos 7.9 内核 5.4
宿主机内核也是5.4
控制台上创建虚拟机时，分配磁盘容量为300G
但虚拟机系统里 根分区实际只有30G，fdisk -l 看了下，看起来分区盘符也异常，只有 1  2  3  没有设备名称。
并且 分区实际确实有300G，但df -h 只有30G
![image](https://github.com/yunionio/cloudpods/assets/17080656/72845717-0d8b-4b07-8e6c-cab7ba2aaaa7)
![image](https://github.com/yunionio/cloudpods/assets/17080656/fc8d1f29-1b43-41b6-b8b4-115cf6961c56)

**Comment by hoganlxj** [comment]
@tianchao001 cloudpods是那个版本， 换个系统镜像试下

**Comment by tianchao001** [comment]
> @tianchao001 cloudpods是那个版本， 换个系统镜像试下

cloudpods 是3.10.7,系统镜像应该没问题，因为同批创建了12台 只有其中两台出了这个问题

**Comment by tianchao001** [comment]
@hoganlxj

**Comment by hoganlxj** [comment]
@tianchao001 找到有问题虚拟机所在的宿主机，导出宿主机的host-deployer日志

**Comment by tianchao001** [comment]
[test.log](https://github.com/yunionio/cloudpods/files/13828108/test.log)
@hoganlxj

**Comment by wanyaoqi** [comment]
@tianchao001 看日志没有什么报错，磁盘 id 是什么？都有问题还是只有这一台有问题

**Comment by tianchao001** [comment]
> @tianchao001 看日志没有什么报错，磁盘 id 是什么？都有问题还是只有这一台有问题

@wanyaoqi   磁盘id d2b5fa7f-817b-42a7-8956-796360fdada9，这台宿主机上一共新建了5台虚拟机，同样的系统镜像，同样的磁盘容量，其中两台有这个问题，我尝试再其他宿主机上重建，但发现 也会概率出现这种问题。

**Comment by wanyaoqi** [comment]
@tianchao001 可以试试使用最新的 host-deployer，需要单独更新 onecloud-operator 和 host-dployer
registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.10.10
registry.cn-beijing.aliyuncs.com/yunionio/host-deployer:v3.10.10
