### ISSUE TITLE
关于ocboot的问题[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19178]
roles/utils/gpu-init   这个ansible roles是3.10.10新版本升级时新增的吗，这次升级 貌似经常卡在这个环节。 name: cp gpu related files  这里。
自行测试ssh和网络均正常，但每次跑都会有其中一台卡在上述环节，然后杀死进程重新跑 就能跑过去，但又会卡在其他机器那。
卡住的现象大概是这样的：
![image](https://github.com/yunionio/cloudpods/assets/17080656/1f968f0e-cad5-42ab-97dc-933edc446ea1)

也不会有任何报错，就是一直跑不到下一台机器。感觉是ansible底层的问题。

**Comment by zhasm** [comment]
我看一下

**Comment by tianchao001** [comment]
> @tianchao001
> 
> 1. 请问，是新部署时出现这个问题，还是升级时触发的？
> 2. 出现这个问题的机器的环境是 (centos7 2009 x86，还是其他具体型号）？

@zhasm 升级时触发的，机器环境是centos7 2009  x86，从3.10.7升级到3.10.10

**Comment by zhasm** [comment]
@tianchao001 收到，我测试一下。

**Comment by zhasm** [comment]
duplicated topic. Please refer to https://github.com/yunionio/cloudpods/issues/19190
