### ISSUE TITLE
虚拟机创建后没有IP地址

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19173]
我们创建了一批虚拟机，发现全部没有IP地址，网卡是up状态，但网卡配置文件是空的，ifconfig 看 eth0也没ip 请问是什么问题导致的？

**Comment by hoganlxj** [comment]
@tianchao001 虚拟机IP是用的经典网络 还是vpc？

**Comment by tianchao001** [comment]
> @tianchao001 虚拟机IP是用的经典网络 还是vpc？

@hoganlxj   配置是这样的：
![image](https://github.com/yunionio/cloudpods/assets/17080656/8e830fcd-9c03-479f-bc17-439de15bfb35)

这个问题已经通过和我们网络同事沟通解决了，但我有个困惑，想请教下。
场景介绍：
首先，我们的网络交换机端口先是做了trunk，端口下有两个网段，分别是vlan 1和vlan 1000，宿主机在vlan 1 网段中，出问题的虚拟机在vlan 1000 网段中。
相对应我们在cloudpods创建了两个子网，分别写入了vlan 1和 vlan 1000 给宿主机和虚拟机用。
同时 两个子网的网关不同，宿主机的网关是60.65   虚拟机的网关是93.1，均开启了dhcp 中继 指向了我们的cloudpods dhcp server。
在上述模式下，虚拟机创建后，没有地址。
而后，网络同学 修改了模式，取消了trunk，将vlan 1000也取消，而虚拟机的网段以sub的形式加入到宿主机的默认vlan 1 中。
这时，再创建虚拟机，地址就通了。

问题：
1  我们ip子网那里配置的vlan 是对应的 网络中的trunk模式吗？
2  虚拟机的地址也是虚拟机启动时走dhcp协议 请求 cloudpods server 分配的吗？ host-deployer 这个组件并不配置网络相关信息是吗？

**Comment by wanyaoqi** [comment]
> > @tianchao001 虚拟机IP是用的经典网络 还是vpc？
> 
> @hoganlxj 配置是这样的： ![image](https://private-user-images.githubusercontent.com/17080656/294428876-8e830fcd-9c03-479f-bc17-439de15bfb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDI1NzcsIm5iZiI6MTcwNDQ0MjI3NywicGF0aCI6Ii8xNzA4MDY1Ni8yOTQ0Mjg4NzYtOGU4MzBmY2QtOWMwMy00NzlmLWJjMTctNDM5ZGUxNWJmYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTA2NmRmNTcxMzU0MTZjYmQzNjQ2Yjk4MGVhODAyMjEzN2E3ODVhMTU4MjExYTA1ZjA5OTQ2YzRhNzM2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku027B2v8Yoo0D8hWHTFNtVSnOekW7lJGoeHuzblAOk)
> 
> 这个问题已经通过和我们网络同事沟通解决了，但我有个困惑，想请教下。 场景介绍： 首先，我们的网络交换机端口先是做了trunk，端口下有两个网段，分别是vlan 1和vlan 1000，宿主机在vlan 1 网段中，出问题的虚拟机在vlan 1000 网段中。 相对应我们在cloudpods创建了两个子网，分别写入了vlan 1和 vlan 1000 给宿主机和虚拟机用。 同时 两个子网的网关不同，宿主机的网关是60.65 虚拟机的网关是93.1，均开启了dhcp 中继 指向了我们的cloudpods dhcp server。 在上述模式下，虚拟机创建后，没有地址。 而后，网络同学 修改了模式，取消了trunk，将vlan 1000也取消，而虚拟机的网段以sub的形式加入到宿主机的默认vlan 1 中。 这时，再创建虚拟机，地址就通了。
> 
> 问题： 1 我们ip子网那里配置的vlan 是对应的 网络中的trunk模式吗？
是的，access 模式使用默认vlan 1

> 2 虚拟机的地址也是虚拟机启动时走dhcp协议 请求 cloudpods server 分配的吗？ host-deployer 这个组件并不配置网络相关信息是吗？
启动时是 dhcp，但是配置启动脚本，ifcfg文件是 host-deployer 配置的

**Comment by tianchao001** [comment]
> > > @tianchao001 虚拟机IP是用的经典网络 还是vpc？
> > 
> > 
> > @hoganlxj 配置是这样的： ![image](https://private-user-images.githubusercontent.com/17080656/294428876-8e830fcd-9c03-479f-bc17-439de15bfb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDI1NzcsIm5iZiI6MTcwNDQ0MjI3NywicGF0aCI6Ii8xNzA4MDY1Ni8yOTQ0Mjg4NzYtOGU4MzBmY2QtOWMwMy00NzlmLWJjMTctNDM5ZGUxNWJmYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTA2NmRmNTcxMzU0MTZjYmQzNjQ2Yjk4MGVhODAyMjEzN2E3ODVhMTU4MjExYTA1ZjA5OTQ2YzRhNzM2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku027B2v8Yoo0D8hWHTFNtVSnOekW7lJGoeHuzblAOk)
> > 这个问题已经通过和我们网络同事沟通解决了，但我有个困惑，想请教下。 场景介绍： 首先，我们的网络交换机端口先是做了trunk，端口下有两个网段，分别是vlan 1和vlan 1000，宿主机在vlan 1 网段中，出问题的虚拟机在vlan 1000 网段中。 相对应我们在cloudpods创建了两个子网，分别写入了vlan 1和 vlan 1000 给宿主机和虚拟机用。 同时 两个子网的网关不同，宿主机的网关是60.65 虚拟机的网关是93.1，均开启了dhcp 中继 指向了我们的cloudpods dhcp server。 在上述模式下，虚拟机创建后，没有地址。 而后，网络同学 修改了模式，取消了trunk，将vlan 1000也取消，而虚拟机的网段以sub的形式加入到宿主机的默认vlan 1 中。 这时，再创建虚拟机，地址就通了。
> > 问题： 1 我们ip子网那里配置的vlan 是对应的 网络中的trunk模式吗？
> 
> 是的，access 模式使用默认vlan 1，trunk 模式才需要配置 vlan
> 
> > 2 虚拟机的地址也是虚拟机启动时走dhcp协议 请求 cloudpods server 分配的吗？ host-deployer 这个组件并不配置网络相关信息是吗？
> 
> 启动时是 dhcp，但是配置启动脚本，ifcfg文件是 host-deployer 配置的

@wanyaoqi 
那我们cloudpods 需要识别当前是trunk模式 还是acces模式吗？ 如果需要，是在IP子网配置那修改吗？

**Comment by wanyaoqi** [comment]
> > > > @tianchao001 虚拟机IP是用的经典网络 还是vpc？
> > > 
> > > 
> > > @hoganlxj 配置是这样的： ![image](https://private-user-images.githubusercontent.com/17080656/294428876-8e830fcd-9c03-479f-bc17-439de15bfb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDI1NzcsIm5iZiI6MTcwNDQ0MjI3NywicGF0aCI6Ii8xNzA4MDY1Ni8yOTQ0Mjg4NzYtOGU4MzBmY2QtOWMwMy00NzlmLWJjMTctNDM5ZGUxNWJmYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTA2NmRmNTcxMzU0MTZjYmQzNjQ2Yjk4MGVhODAyMjEzN2E3ODVhMTU4MjExYTA1ZjA5OTQ2YzRhNzM2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku027B2v8Yoo0D8hWHTFNtVSnOekW7lJGoeHuzblAOk)
> > > 这个问题已经通过和我们网络同事沟通解决了，但我有个困惑，想请教下。 场景介绍： 首先，我们的网络交换机端口先是做了trunk，端口下有两个网段，分别是vlan 1和vlan 1000，宿主机在vlan 1 网段中，出问题的虚拟机在vlan 1000 网段中。 相对应我们在cloudpods创建了两个子网，分别写入了vlan 1和 vlan 1000 给宿主机和虚拟机用。 同时 两个子网的网关不同，宿主机的网关是60.65 虚拟机的网关是93.1，均开启了dhcp 中继 指向了我们的cloudpods dhcp server。 在上述模式下，虚拟机创建后，没有地址。 而后，网络同学 修改了模式，取消了trunk，将vlan 1000也取消，而虚拟机的网段以sub的形式加入到宿主机的默认vlan 1 中。 这时，再创建虚拟机，地址就通了。
> > > 问题： 1 我们ip子网那里配置的vlan 是对应的 网络中的trunk模式吗？
> > 
> > 
> > 是的，access 模式使用默认vlan 1，trunk 模式才需要配置 vlan
> > > 2 虚拟机的地址也是虚拟机启动时走dhcp协议 请求 cloudpods server 分配的吗？ host-deployer 这个组件并不配置网络相关信息是吗？
> > 
> > 
> > 启动时是 dhcp，但是配置启动脚本，ifcfg文件是 host-deployer 配置的
> 
> @wanyaoqi 那我们cloudpods 需要识别当前是trunk模式 还是acces模式吗？ 如果需要，是在IP子网配置那修改吗？

不需要，建一个看下这个文档 https://v1.cloudpods.org/zh/docs/function_principle/onpremise/network/host/

**Comment by tianchao001** [comment]
好嘞，谢谢。
