### ISSUE TITLE
物理机纳管-物理机托管[求助/Help]

### ISSUE THREAD

**Issue by strivorll** [yunionio/cloudpods#19176]
![image](https://github.com/yunionio/cloudpods/assets/49850950/d7f01cce-6d28-4d7e-a08b-1dcdd45a03b3)

物理纳管模块，针对已有系统的物理机进行托管，报错。我理解应该填这个物理的BMC IP、用户名、密码信息，但脚本只有用户名和密码信息，官方文档也没有详细说明。帮忙看看应该怎么操作哈。

**Comment by hoganlxj** [comment]
@strivorll   要在平台 ipmi类型的IP子网  ，该子网范围包含 托管物理机ipmi地址，具体参考https://www.cloudpods.org/docs/guides/onpremise/baremetal/create-register#%E9%85%8D%E7%BD%AE%E7%BD%91%E7%BB%9C

**Comment by strivorll** [comment]
> @strivorll 要在平台 ipmi类型的IP子网 ，该子网范围包含 托管物理机ipmi地址，具体参考https://www.cloudpods.org/docs/guides/onpremise/baremetal/create-register#%E9%85%8D%E7%BD%AE%E7%BD%91%E7%BB%9C

我在平台新建了IPMI的子网，报错依旧。
我理解在OS层执行脚本注册应该有地方要我输入这个服务器的IPMI地址，但从脚本的提示上没有输出的地方。是有单独的配置文件需要配置吗？

**Comment by hoganlxj** [comment]
@strivorll 是要在被托管的物理机上执行 托管的脚本
