### ISSUE TITLE
升级过程中疑似报错是否需要重试？[求助/Help]

### ISSUE THREAD

**Issue by tianchao001** [yunionio/cloudpods#19190]
我们在使用ocboot从3.10.7升级到3.10.10过程中，在ansible执行任务的init gpu环节遇到几台机器异常，但并没有具体错误，请问可以忽略吗？
![image](https://github.com/yunionio/cloudpods/assets/17080656/712e915b-db47-4160-b70e-409d531bb919)

**Comment by zhasm** [comment]
解决中。

**Comment by zexi** [comment]
@tianchao001 这个 UNREACHABLE 应该是网络不可达了，从控制节点能 ssh 登录这几个计算节点吗？

**Comment by zhasm** [comment]
@zexi 一个用户反馈，直接执行gpu init里的/usr/local/gpu-init/gpu_setup.sh  脚本，卡在这里了：
![img_v3_026u_cd8833e7-43f1-4f66-9854-89e1d5668e9g](https://github.com/yunionio/cloudpods/assets/133000/60a91827-9e6b-498c-803f-623b5acc1a80)

**Comment by tianchao001** [comment]
> @tianchao001 这个 UNREACHABLE 应该是网络不可达了，从控制节点能 ssh 登录这几个计算节点吗？

@zexi  ssh是没问题的，整个ansible流程，只卡在了 gpu init环节。

**Comment by zexi** [comment]
> @zexi 一个用户反馈，直接执行gpu init里的/usr/local/gpu-init/gpu_setup.sh 脚本，卡在这里了： ![img_v3_026u_cd8833e7-43f1-4f66-9854-89e1d5668e9g](https://private-user-images.githubusercontent.com/133000/295082023-60a91827-9e6b-498c-803f-623b5acc1a80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzA2NDQsIm5iZiI6MTcwNDc3MDM0NCwicGF0aCI6Ii8xMzMwMDAvMjk1MDgyMDIzLTYwYTkxODI3LTllNmItNDk4Yy04MDNmLTYyM2I1YWNjMWE4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMzE5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDllY2Q1NWRhMGEzMzQxYWU3NzhlYTgwNWRhMzBjMGJlYzRhMGQ4ZDNjMDZlOTg0YjYyYjEyMjc4ZThmYjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ti9l_hWg-D052z4ScH3WpF2Uu7aCbpAq0rRJSgi_XY4)

@zhasm 执行 `bash -x /usr/local/gpu-init/gpu_setup.sh` 看下具体卡在哪个命令了？

**Comment by zexi** [comment]
> > @tianchao001 这个 UNREACHABLE 应该是网络不可达了，从控制节点能 ssh 登录这几个计算节点吗？
> 
> @zexi ssh是没问题的，整个ansible流程，只卡在了 gpu init环节。

@tianchao001 先把这个文件里面的 gpu-init 注释掉，再执行 upgrade 试试。

https://github.com/yunionio/ocboot/blob/master/onecloud/upgrade-cluster.yml#L19-L21

**Comment by tianchao001** [comment]
> > > @tianchao001 这个 UNREACHABLE 应该是网络不可达了，从控制节点能 ssh 登录这几个计算节点吗？
> > 
> > 
> > @zexi ssh是没问题的，整个ansible流程，只卡在了 gpu init环节。
> 
> @tianchao001 先把这个文件里面的 gpu-init 注释掉，再执行 upgrade 试试。
> 
> https://github.com/yunionio/ocboot/blob/master/onecloud/upgrade-cluster.yml#L19-L21

@zexi  嗯，已经使用这个临时办法升级成功了，这个环节卡住的概率较大，后面再升级感觉还是会遇到类似问题。

**Comment by zexi** [comment]
@zhasm 升级过程中可以不执行 gpu-init ，可以给 ocboot upgrade 加个参数来控制是否要在升级过程中执行 gpu-init 这个 role ，可以默认不执行。

**Comment by zexi** [comment]
> @zhasm 升级过程中可以不执行 gpu-init ，可以给 ocboot upgrade 加个参数来控制是否要在升级过程中执行 gpu-init 这个 role ，可以默认不执行。

https://github.com/yunionio/ocboot/pull/1110 实现这个机制。

**Comment by zhasm** [comment]
@tianchao001 

大概率是 `/usr/local/gpu-init/gpu_setup.sh` 脚本的 323 行附近的 `dracut -f --kver ...` 语句卡住。
这一句跟内核、gpu等硬件有关，不需联网。

请按照如下方式，协助定位：

1. 保存备份；
```bash
cp /usr/local/gpu-init/gpu_setup.sh /usr/local/gpu-init/g.sh 
```

2. 插入如下调试标志 （效果如图）
在`/usr/local/gpu-init/g.sh` 的开头位置，增加一行：
```
set -ex ;export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
```
<img width="688" alt="image" src="https://github.com/yunionio/cloudpods/assets/133000/003119fe-87da-4b6b-801f-48fcf28f0fd0">

3. 增加计时  （效果如图）
在 `/usr/local/gpu-init/g.sh`的 323  行左右，在`dracut`前增加`time`。

<img width="839" alt="image" src="https://github.com/yunionio/cloudpods/assets/133000/9aaef318-ce63-498e-923f-c49afc073dc9">

4. 执行
```sh
/usr/local/gpu-init/g.sh
```
<img width="1367" alt="image" src="https://github.com/yunionio/cloudpods/assets/133000/063a87b7-910d-4692-8650-e47a5ffbfbf3">

请对这个步骤截图。我的环境本步骤执行需要 30s 以内。

**Comment by tianchao001** [comment]
@zhasm 
已经卡在这个界面两个多小时了。
![image](https://github.com/yunionio/cloudpods/assets/17080656/bd2b2208-6b44-4b31-a1fd-d4e23000e031)

**Comment by zhasm** [comment]
@tianchao001 收到，多谢反馈，我们看一下。

**Comment by wanyaoqi** [comment]
> @zhasm 已经卡在这个界面两个多小时了。 ![image](https://private-user-images.githubusercontent.com/17080656/295465635-bd2b2208-6b44-4b31-a1fd-d4e23000e031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjgzMDcsIm5iZiI6MTcwNDg2ODAwNywicGF0aCI6Ii8xNzA4MDY1Ni8yOTU0NjU2MzUtYmQyYjIyMDgtNmI0NC00YjMxLWExZmQtZDRlMjMwMDBlMDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2MjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMzFhYTFkOTNmZDYxNjI3ZTQ0MjNiMjNkZjAzMWE1MDk3MmQ5MmE2ZTAyZWJkMTEwOGM0ZDgwNWU3ZmEwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I-axvmUTS6g8vGCInooEe1HxTJJtKaQDMllSmbrw4uc)

@tianchao001 你可以手动执行一下最后一条 dracut 命令，加上 --debug 看下卡在哪里

**Comment by tianchao001** [comment]
@wanyaoqi  @zhasm 
![image](https://github.com/yunionio/cloudpods/assets/17080656/443b9b5c-edc7-4b83-9cf0-414fd5037f5e)

**Comment by wanyaoqi** [comment]
> @wanyaoqi @zhasm ![image](https://private-user-images.githubusercontent.com/17080656/295517958-443b9b5c-edc7-4b83-9cf0-414fd5037f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTQwNTAsIm5iZiI6MTcwNDg5Mzc1MCwicGF0aCI6Ii8xNzA4MDY1Ni8yOTU1MTc5NTgtNDQzYjliNWMtZWRjNy00YjgzLTljZjAtNDE0ZmQ1MDM3ZjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEzMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNWIwNjdjOWM5MTc2MmU4NzcyZGU1ZDRkMjc2ZTc5YzVkYjJkNDI2OGIwMzNhMTA4ZGYyMTIyZWRlMmJkNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vYzmGU6nvVdzom1yEf9V6uRMeWHD79y32hvxhQl1W4A)

@tianchao001  搜到一个类似的问题但是看不到 solution https://access.redhat.com/solutions/5186351。
需要定位一下，你可以 strace 一下这个进程看一下具体卡在什么地方了，看下 dmesg 有什么信息么？看下 iostat 看下 /boot分区 ioutils。
