### ISSUE TITLE
[BUG] Win 虚拟机创建失败

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#19202]
**问题描述/What happened**:
使用cloudpods提供的windows 2012 server ,windows10,cloudbase.it 的windows 2012镜像均创建失败，显示`booting from hard [disk`,日志文件：]
[default-host-deployer-hszxv.txt](https://github.com/yunionio/cloudpods/files/13868201/default-host-deployer-hszxv.txt)

**环境/Environment**:
cloudpods full v3.10.10 
宿主机 Ubuntu22.04.3LTS，此前使用windows 2016server (cloudpods提供）镜像创建成功，但存在初始密码错误、无法访问外网的问题 #19161。
可以正常创建linux虚拟机，初始密码正确，虚拟机可以访问外网。
确认宿主机可以访问外网。
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
@DSYZayn 
<img width="932" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/36a67414-bfa9-46a1-857e-b8a458525c66">
windows 2012 这个看起来是没有找到系统，上传的镜像是否是完整的？

windows2016以上部署的问题这个 pr 已经修复了，https://github.com/yunionio/cloudpods/pull/19215

**Comment by DSYZayn** [comment]
和其他镜像上传方式步骤一致，应当是完整的，且不只2012这个镜像部署失败。前天测试了从ISO安装Win10没问题。

**Comment by wanyaoqi** [comment]
> @wanyaoqi 和其他镜像上传方式步骤一致，应当是完整的，且不只2012这个镜像部署失败。前天测试了从ISO安装Win10没问题。

`disk.MountRootfs not found partition, not init, quit` 看报错是没有找到系统盘分区。你试试打开 debug 日志在试一试
```bash
$ kubectl edit cm -n onecloud default-host 
log_level: debug # 改成 debug

# 重启 host-deployer
$ kubectl rollout restart ds -n onecloud default-host-deployer
```
