### ISSUE TITLE
[求助/Help] 多云管理Docker Compose安装，time out

### ISSUE THREAD

**Issue by lucaroot** [yunionio/cloudpods#19218]
我在海外主机Docker Compose安装时候报错，Error response from daemon: Head "https://registry.cn-beijing.aliyuncs.com/v2/yunionio/compose-service-init/manifests/v3.10-20231222.3": Get "https://dockerauth.cn-hangzhou.aliyuncs.com/auth?scope=repository%3Ayunionio%2Fcompose-service-init%3Apull&service=registry.aliyuncs.com%3Acn-beijing%3A26842": net/http: TLS handshake timeout

请问我该怎么替换或者指定docker官方镜像呢

**Comment by zhasm** [comment]
对于稳定镜像，例如 registry.cn-beijing.aliyuncs.com/yunion/host:v3.10.10 ，都会存在 docker.io/yunion/host:v3.10.10 的海外同步镜像。请尝试替换一下脚本里的 registry 试试？

**Comment by lucaroot** [comment]
因为原配置文件是yunionio

但是刚刚给的解决方案中是因为原配置文件是yunion
1、所以我分别进行了替换，替换成docker.io/yunionio后，提示如下：

Error response from daemon: pull access denied for yunionio/yunionconf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied


2、替换成docker.io/yunion后

Error response from daemon: manifest for yunion/host-deployer:v3.10-20231222.2 not found: manifest unknown: manifest unknown


单独将host-deployer:v3.10-20231222.2替换为registry.cn-beijing.aliyuncs.com/yunionio后

Error response from daemon: pull access denied for yunion/mariadb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by lucaroot** [comment]
追加操作：
我将配置文件中registry.cn-beijing.aliyuncs.com/yunion/host:v3.10.10替换成docker.io
host:v3.10-20231222.3中cn-beijing替换成cn-hangzhou、cn-shenzhen、cn-hongkong均报错net/http: TLS handshake timeout

**Comment by zexi** [comment]
@lucaroot 或者你用 ocboot 部署吧，这个可以指定 dockerhub 的镜像：https://www.cloudpods.org/docs/getting-started/cmp/quickstart-ocboot
<img width="887" alt="image" src="https://github.com/yunionio/cloudpods/assets/10767027/00f22d09-d8e8-4964-b898-f1a4a85127b7">

**Comment by lucaroot** [comment]
这个问题是我安装好后，连接不上云，一直会加载中。都不知道怎么排查

**Comment by zexi** [comment]
> 这个问题是我安装好后，连接不上云，一直会加载中。都不知道怎么排查

@lucaroot 前端界面加载不出来？

**Comment by lucaroot** [comment]
@zexi 前端是可以的，就是云账户连接不上。重启后未登录状态下，机器shell一堆报错，都是连接ip错误的信息，ip查了下是阿里云之类的ip

**Comment by zexi** [comment]
> @zexi 前端是可以的，就是云账户连接不上。重启后未登录状态下，机器shell一堆报错，都是连接ip错误的信息，ip查了下是阿里云之类的ip

@lucaroot 麻烦贴下具体的错误信息。

**Comment by lucaroot** [comment]
@zexi 
![111](https://github.com/yunionio/cloudpods/assets/17341289/b5d50201-c200-4b7d-9bb4-cab2b4847d47)如图

**Comment by lucaroot** [comment]
@zexi 我分别用centos7和debian10都进行Ocboot安装多云管理版本后，web界面正常，也可以正常进行登录修改密码等操作，但是只要一连接云账户，shell就会疯狂报错，如图。
![222](https://github.com/yunionio/cloudpods/assets/17341289/a8e0221d-9db2-4c24-a002-cec32cfb1a8c)

**Comment by zexi** [comment]
> @zexi 我分别用centos7和debian10都进行Ocboot安装多云管理版本后，web界面正常，也可以正常进行登录修改密码等操作，但是只要一连接云账户，shell就会疯狂报错，如图。 ![222](https://private-user-images.githubusercontent.com/17341289/296021015-a8e0221d-9db2-4c24-a002-cec32cfb1a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NDEsIm5iZiI6MTcwNTAyNDY0MSwicGF0aCI6Ii8xNzM0MTI4OS8yOTYwMjEwMTUtYThlMDIyMWQtOWRiMi00YzI0LWEwMDItY2VjMzJjZmIxYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAxNTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MTMzMjYxODRiYjVlYzhiMWJiNjk2ZTFmYTA1NTUyNDMwOGNjNzhiODRlZWY0OWI1MWJhOWNkMzI2M2Y4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dySZ5ATyX8UEswNWt39OsLAmefEXUg995NPrWOzVkpg)

@lucaroot 这个报错应该是还有一些 pod 没有启动，用下面的命令看下整个 k8s 集群 pod 的状态：

```bash
kubectl get pods -A -o wide
```

**Comment by lucaroot** [comment]
@zexi 所有pod都是running状态。

**Comment by zexi** [comment]
@lucaroot 连接云账号这个那个 ipvs 的报错应该没有关系，连接云账号报错的话，前端界面应该有报错，另外也可以把 default-region-xxx 这个 pod 的日志导出来看下，里面应该也有报错日志。

**Comment by lucaroot** [comment]
我测试阿里云云账号时候，填入ak后就会一直卡住，我看了下发的包，请求网址:
https://cloud.99ai.world/api/v2/cloudaccounts
请求方法:
POST
状态代码:
504 Gateway Timeout

当我测试aws账号时候，就会正常，我随便填写aws-ak就会报ak错误

**Comment by zexi** [comment]
> 我测试阿里云云账号时候，填入ak后就会一直卡住，我看了下发的包，请求网址: https://cloud.99ai.world/api/v2/cloudaccounts 请求方法: POST 状态代码: 504 Gateway Timeout
> 
> 当我测试aws账号时候，就会正常，我随便填写aws-ak就会报ak错误

@lucaroot 这个会不会是你那边网络环境的问题，aliyun 的 api 地址应该不是 cloud.99ai.world 这个域名。

**Comment by lucaroot** [comment]
因为我的应用是在内网，外部访问域名有nginx做转发到内部的，应该是无影响的。另外麻烦帮我把那个域名打个码，thx

**Comment by zexi** [comment]
> 因为我的应用是在内网，外部访问域名有nginx做转发到内部的，应该是无影响的。另外麻烦帮我把那个域名打个码，thx

@lucaroot 我不确定用 nginx 转发是否 ok ，看代码里面 https://github.com/yunionio/cloudmux/blob/master/pkg/multicloud/aliyun/aliyun.go#L396 是直接请求到 xxx.aliyuncs.com 这些 endpoint 的。

**Comment by lucaroot** [comment]
@zexi 从nginx转发应该是ok的，因为我直接在vm内部用内网ip的形式访问还是同样的报错，现在的状态是我连接aws正常，我连接aliyun等待超时，大概率可能是我的网络问题，虽然我本地ping阿里云都是ok的，不确定具体原因。

**Comment by lucaroot** [comment]
感谢支持，是网络原因，我换环境重新安装后一切功能正常
