### ISSUE TITLE
[Feature] vnc发送文字添加强制终止功能

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#19225]
**What would you like to be added**:
目前VNC**发送文字**功能不知道怎么实现的，是一个一个字蹦的效果，希望能做成复制粘贴的效果，或者添加一个强制终止的功能。复制了一大段发现错了，还得等它字蹦完。有点无语的feature。😅
# 测试环境
虚拟机 win10,记事本，发送大段文字。

**Comment by swordqiu** [comment]
@DSYZayn vnc发送文字的实现是将用户输入文字框的字母，模拟键盘按键，逐个顺次输入，每个字符间隔100ms，因此输入大段文字就会时间很长，并且无法打断。因vnc是一个简单的图形终端协议，图形显示效率和输入效率都比较低。建议仅在需要虚拟机无网络连接时使用。对于Linux，日常使用建议通过web ssh。对于Windows，日常时间建议用RDP（web RDP在3.11已支持）

**Comment by DSYZayn** [comment]
@swordqiu 请问现在cloudpods v3.11是否作为生产版本？合适的话近期升级一下。
