### ISSUE TITLE
[求助/Help]在本地搭建cloudpods环境的过程中,想要使用三方认证源,目前本地搭建只支持LDAP协议吗?

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19227]
![image](https://github.com/yunionio/cloudpods/assets/19704134/8b26d481-3d95-402a-8428-83d94b8decd5)
这个我本地请求的接口报错,其他认证源不能使用吗请问?

**Comment by ioito** [comment]
麻烦点下网络请求，看报什么错 @ilovedumplings
