### ISSUE TITLE
[求助/Help] 物理机安装系统，新建裸金属 No resource are avaliable

### ISSUE THREAD

**Issue by ChaoHsin-fang** [yunionio/cloudpods#19226]
物理机--安装系统-新建裸金属时报错如下 物理机直接有系统

web界面报错：
[
    "No matching resources",
    "{\"error\":{\"code\":400,\"details\":\"Error #01: genericScheduler.Schedule: No resource are avaliable that match all of the following predicates: filter by baremetal_storage(-1), session_id=\\\"1704945871575\\\"\\n\",\"request\":{\"body\":\"{\\\"backup\\\":false,\\\"baremetal_disk_configs\\\":[{\\\"adapter\\\":0,\\\"conf\\\":\\\"none\\\",\\\"count\\\":1,\\\"driver\\\":\\\"MegaRaid\\\",\\\"...t\\\":96,\\\"vmem_size\\\":524288}\",\"headers\":{\"Content-Length\":\"2325\",\"Content-Type\":\"application/json\",\"User-Agent\":\"yunioncloud-go/201708\",\"X-Auth-Token\":\"*\",\"X-Request-Id\":\"4d62d7-3efb21\",\"X-Yunion-Lang\":\"zh-CN\",\"X-Yunion-Parent-Id\":\"0.0\",\"X-Yunion-Peer-Service-Name\":\"compute_v2\",\"X-Yunion-Remote-Addr\":\"default-scheduler:30887\",\"X-Yunion-Span-Id\":\"0.0.0\",\"X-Yunion-Span-Name\":\"\",\"X-Yunion-Strace-Debug\":\"true\",\"X-Yunion-Strace-Id\":\"02fc7233\"},\"method\":\"POST\",\"url\":\"https://default-scheduler:30887/scheduler\"}}}"
]
命令行工具调度历史报错如下：
climc  scheduler-history-show --log --raw 1704945871575
consuming: 0s
error: 'genericScheduler.Schedule: No resource are avaliable that match all of the
  following predicates: filter by baremetal_storage(-1), session_id="1704945871575"'
input: '{"backup":false,"baremetal_disk_configs":[{"adapter":0,"conf":"none","count":1,"driver":"MegaRaid","range":[0],"type":"rotate"}],"best_effort":false,"change_config":false,"count":1,"details":false,"disks":[{"backend":"local","driver":"scsi","image_id":"6ea5b15d-e009-4984-860b-1d4c38ef3bab","image_properties":{"arch":"x86_64","disk_format":"qcow2","distro":"Ubuntu","installed_cloud_init":"true","is_lvm_partition":"false","is_readonly":"false","os_arch":"x86_64","os_distribution":"Ubuntu","os_language":"","os_type":"Linux","os_version":"20.04","partition_type":"gpt","uefi_support":"true","version":"20.04"},"index":0,"os_arch":"x86_64","size":15697920},{"backend":"local","driver":"scsi","index":0,"mountpoint":"/","size":-1}],"domain_id":"default","has_isolated_device":false,"host_mem_page_size":0,"hypervisor":"baremetal","live_migrate":false,"name":"test-131","nets":[{"bw_limit":1000,"domain_id":"default","driver":"virtio","exit":false,"index":0,"network":"ad5f3f8b-9675-4c37-8da9-95215648d1e7","num_queues":0,"private":false,"project_id":"bb7dc551694e467b8c1d5a4959cc7f8e","require_designated_ip":false,"require_teaming":false,"reserved":false,"rx_traffic_limit":0,"standby_addr_count":0,"standby_port_count":0,"try_teaming":false,"tx_traffic_limit":0,"vip":false}],"pending_usages":[{"brand":"OneCloud","cloud_env":"onpremise","count":1,"cpu":96,"deleted":false,"domain_id":"default","group":0,"hypervisor":"baremetal","isolated_device":0,"memory":524288,"provider":"OneCloud","region_id":"default","storage":15697919,"tenant_id":"bb7dc551694e467b8c1d5a4959cc7f8e","update_version":0,"zone_id":"2d80c45f-2110-48be-8fb7-54660d2edd5e"},{"brand":"OneCloud","bucket":0,"cache":0,"cloud_env":"onpremise","deleted":false,"domain_id":"default","eip":0,"eport":0,"instance_snapshot":0,"loadbalancer":0,"mongodb":0,"object_cnt":0,"object_gb":0,"port":1,"provider":"OneCloud","rds":0,"region_id":"default","snapshot":0,"tenant_id":"bb7dc551694e467b8c1d5a4959cc7f8e","update_version":0}],"prefer_host_id":"c5bf75a4-3abe-4f39-880c-2632a0508187","prefer_region_id":"default","prefer_zone_id":"2d80c45f-2110-48be-8fb7-54660d2edd5e","project_id":"bb7dc551694e467b8c1d5a4959cc7f8e","record_to_history":false,"resource_type":"shared","reuse_network":false,"suggestion":false,"suggestion_all":false,"suggestion_limit":100,"vcpu_count":96,"vmem_size":524288}'
output: ""
session_id: "1704945871575"
tasks:
- capacity_map:
    c5bf75a4-3abe-4f39-880c-2632a0508187:
      MinValue: -1
      Values:
        baremetal_cpu:
          Value: 1
        baremetal_memory:
          Value: 1
        baremetal_status:
          Value: 1
        baremetal_storage:
          Value: 0
  consuming: 3.207487ms
  data:
    __meta__: null
    ChangeConfig: false
    HasIsolatedDevice: false
    InstanceGroupsDetail: null
    PendingUsages:
    - {}
    - {}
    Raw: '{"backup":false,"baremetal_disk_configs":[{"adapter":0,"conf":"none","count":1,"driver":"MegaRaid","range":[0],"type":"rotate"}],"best_effort":false,"change_config":false,"count":1,"details":false,"disks":[{"backend":"local","driver":"scsi","image_id":"6ea5b15d-e009-4984-860b-1d4c38ef3bab","image_properties":{"arch":"x86_64","disk_format":"qcow2","distro":"Ubuntu","installed_cloud_init":"true","is_lvm_partition":"false","is_readonly":"false","os_arch":"x86_64","os_distribution":"Ubuntu","os_language":"","os_type":"Linux","os_version":"20.04","partition_type":"gpt","uefi_support":"true","version":"20.04"},"index":0,"os_arch":"x86_64","size":15697920},{"backend":"local","driver":"scsi","index":0,"mountpoint":"/","size":-1}],"domain_id":"default","has_isolated_device":false,"host_mem_page_size":0,"hypervisor":"baremetal","live_migrate":false,"name":"test-131","nets":[{"bw_limit":1000,"domain_id":"default","driver":"virtio","exit":false,"index":0,"network":"ad5f3f8b-9675-4c37-8da9-95215648d1e7","num_queues":0,"private":false,"project_id":"bb7dc551694e467b8c1d5a4959cc7f8e","require_designated_ip":false,"require_teaming":false,"reserved":false,"rx_traffic_limit":0,"standby_addr_count":0,"standby_port_count":0,"try_teaming":false,"tx_traffic_limit":0,"vip":false}],"pending_usages":[{"brand":"OneCloud","cloud_env":"onpremise","count":1,"cpu":96,"deleted":false,"domain_id":"default","group":0,"hypervisor":"baremetal","isolated_device":0,"memory":524288,"provider":"OneCloud","region_id":"default","storage":15697919,"tenant_id":"bb7dc551694e467b8c1d5a4959cc7f8e","update_version":0,"zone_id":"2d80c45f-2110-48be-8fb7-54660d2edd5e"},{"brand":"OneCloud","bucket":0,"cache":0,"cloud_env":"onpremise","deleted":false,"domain_id":"default","eip":0,"eport":0,"instance_snapshot":0,"loadbalancer":0,"mongodb":0,"object_cnt":0,"object_gb":0,"port":1,"provider":"OneCloud","rds":0,"region_id":"default","snapshot":0,"tenant_id":"bb7dc551694e467b8c1d5a4959cc7f8e","update_version":0}],"prefer_host_id":"c5bf75a4-3abe-4f39-880c-2632a0508187","prefer_region_id":"default","prefer_zone_id":"2d80c45f-2110-48be-8fb7-54660d2edd5e","project_id":"bb7dc551694e467b8c1d5a4959cc7f8e","record_to_history":false,"resource_type":"shared","reuse_network":false,"suggestion":false,"suggestion_all":false,"suggestion_limit":100,"vcpu_count":96,"vmem_size":524288}'
    UserCred:
      TokenCredential:
        Context:
          ip: 172.31.1.114
          source: web
        Domain: Default
        DomainId: default
        Expires: "2024-01-12T04:02:44Z"
        ProjectDomain: Default
        ProjectDomainId: default
        RoleIds: a8b061b7e06b4c52851ea35cc02fb5ba
        Roles: admin
        Token: 5e995853a91f8db6c29f6c2a0645e19b095441f0b3cddcf84c1e620544a7b930
        User: admin
        UserId: a9dc45667b3844018b4f40933a23a3b3
        tenant: system
        tenant_id: bb7dc551694e467b8c1d5a4959cc7f8e
    backup: false
    baremetal_disk_configs:
    - adapter: 0
      conf: none
      count: 1
      driver: MegaRaid
      range:
      - 0
      size: null
      splits: ""
      type: rotate
    best_effort: false
    candidates:
    - c5bf75a4-3abe-4f39-880c-2632a0508187
    cdrom: ""
    count: 1
    cpu_desc: ""
    cpu_microcode: ""
    cpu_mode: ""
    details: false
    disks:
    - backend: local
      backup_id: ""
      boot_index: null
      cache: ""
      disk_id: ""
      disk_type: ""
      driver: scsi
      existing_path: ""
      format: ""
      fs: ""
      image_encrypt_key_id: ""
      image_id: 6ea5b15d-e009-4984-860b-1d4c38ef3bab
      image_properties:
        arch: x86_64
        disk_format: qcow2
        distro: Ubuntu
        installed_cloud_init: "true"
        is_lvm_partition: "false"
        is_readonly: "false"
        os_arch: x86_64
        os_distribution: Ubuntu
        os_language: ""
        os_type: Linux
        os_version: "20.04"
        partition_type: gpt
        uefi_support: "true"
        version: "20.04"
      index: 0
      medium: ""
      mountpoint: ""
      nvme_device: null
      os_arch: x86_64
      schedtags: []
      size: 15697920
      snapshot_id: ""
      storage_id: ""
    - backend: local
      backup_id: ""
      boot_index: null
      cache: ""
      disk_id: ""
      disk_type: ""
      driver: scsi
      existing_path: ""
      format: ""
      fs: ""
      image_encrypt_key_id: ""
      image_id: ""
      image_properties: null
      index: 0
      medium: ""
      mountpoint: /
      nvme_device: null
      os_arch: ""
      schedtags: []
      size: -1
      snapshot_id: ""
      storage_id: ""
    domain_id: default
    for_guests: null
    group_releations: null
    groups: null
    guest_status: ""
    host_id: ""
    host_mem_page_size: 0
    hypervisor: baremetal
    id: ""
    ignore_filters: {}
    instance_backup_id: ""
    instance_snapshot_id: ""
    instance_type: ""
    is_container: false
    is_daemon: null
    isolated_devices: null
    live_migrate: false
    name: test-131
    nets:
    - address: ""
      address6: ""
      bw_limit: 1000
      domain_id: default
      driver: virtio
      exit: false
      ifname: ""
      index: 0
      mac: ""
      net_type: ""
      network: ad5f3f8b-9675-4c37-8da9-95215648d1e7
      num_queues: 0
      private: false
      project_id: bb7dc551694e467b8c1d5a4959cc7f8e
      require_designated_ip: false
      require_teaming: false
      reserved: false
      rx_traffic_limit: 0
      schedtags: []
      sriov_device: null
      standby_addr_count: 0
      standby_port_count: 0
      try_teaming: false
      tx_traffic_limit: 0
      vip: false
      wire: ""
    os_arch: ""
    prefer_backup_host: ""
    prefer_host_id: c5bf75a4-3abe-4f39-880c-2632a0508187
    prefer_manager_id: ""
    prefer_region_id: default
    prefer_wire_id: ""
    prefer_zone_id: 2d80c45f-2110-48be-8fb7-54660d2edd5e
    project_id: bb7dc551694e467b8c1d5a4959cc7f8e
    record_to_history: false
    required_candidates: 1
    resource_type: shared
    reuse_network: false
    schedtags: []
    session_id: "1704945871575"
    skip_cpu_check: null
    skip_kernel_check: null
    sku: ""
    suggestion: false
    suggestion_all: false
    suggestion_details: false
    suggestion_limit: 100
    tag: ""
    target_host_kernel: ""
    type: ""
    vcpu_count: 96
    vmem_size: 524288
  error: 'genericScheduler.Schedule: No resource are avaliable that match all of the
    following predicates: filter by baremetal_storage(-1), session_id="1704945871575"'
  logs:
  - 'Success: CPU-131:c5bf75a4-3abe-4f39-880c-2632a0508187 [baremetal_cpu,baremetal_memory,baremetal_status,host_schedtag] '
  - 'Failed: CPU-131:c5bf75a4-3abe-4f39-880c-2632a0508187 [baremetal_storage] baremetal_storage:
    no enough storage err: <nil>'
  result: null
  status: failed
  time: "2024-01-11 04:04:31"
  type: baremetal
time: "2024-01-11 04:04:31"

**Comment by zexi** [comment]
@ChaoHsin-fang 我看传递的磁盘参数是2块，第1块肯定是到  / mountpoint 的，把第二块去掉试试。
```json
[
  {
    "backend": "local",
    "driver": "scsi",
    "image_id": "6ea5b15d-e009-4984-860b-1d4c38ef3bab",
    "image_properties": {
      "arch": "x86_64",
      "disk_format": "qcow2",
      "distro": "Ubuntu",
      "installed_cloud_init": "true",
      "is_lvm_partition": "false",
      "is_readonly": "false",
      "os_arch": "x86_64",
      "os_distribution": "Ubuntu",
      "os_language": "",
      "os_type": "Linux",
      "os_version": "20.04",
      "partition_type": "gpt",
      "uefi_support": "true",
      "version": "20.04"
    },
    "index": 0,
    "os_arch": "x86_64",
    "size": 15697920
  },
  {
    "backend": "local",
    "driver": "scsi",
    "index": 0,
    "mountpoint": "/",
    "size": -1
  }
]
```

**Comment by ChaoHsin-fang** [comment]
目前只选了一块 3.5T的SSD 不做raid 创建裸金属报错如下 
/opt/MegaRAID/MegaCli/MegaCli64 -CfgLdAdd -r0 [134:0] WT NORA Direct NoCachedBadBBU -a0 
  我理解这个命令里面 -r0 是raid0 吧 服务器只有一块SSD ，做raid0 至少需要两块磁盘吧 
  

{
    "__reason__": "Do deploy: Build MegaRaid raid failed: Driver MegaRaid, adapter 0 build raid: Build raw disks: [\"/opt/MegaRAID/MegaCli/MegaCli64 -CfgLdAdd -r0 
    [134:0] WT NORA Direct NoCachedBadBBU -a0\" error: Process exited with status 38, cmd error:  \r                                     \nThe specified physical disk does not have the appropriate attributes to complete \nthe requested command.\n\nExit Code: 0x26\n, \"/opt/MegaRAID/storcli/storcli64 /c0 add vd each type=raid0 drives=134:0,134:1,134:2,134:3,134:4,134:5,134:6,134:7 wt nora direct\" error: Process exited with status 255, cmd error:  CLI Version = 007.2612.0000.0000 June 13, 2023\nOperating system = Linux 6.0.0-6-amd64\nController = 0\nStatus = Failure\nDescription = Configuration not allowed\n\n\n]",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}

**Comment by zexi** [comment]
@ChaoHsin-fang 根据这个代码来看：https://github.com/yunionio/cloudpods/blob/master/pkg/baremetal/utils/raid/megactl/megactl.go#L833-L847 ，应该是先会做 jbod ，如果 jbod 失败，才会用 raid0 再试一遍，megactl 做 raid0 应该可以只用一块盘。
试试用 `climc host-ssh 物理机名称` 登录到物理机里面，然后手动执行这些 MegaCli64 命令试试，如果还是报错，试试执行 `"/opt/MegaRAID/MegaCli/MegaCli64 -CfgForeign -Scan -Clear`

**Comment by ChaoHsin-fang** [comment]
请教一下目前物理机进小系统了，yunionos的默认密码是多少

**Comment by zexi** [comment]
> 请教一下目前物理机进小系统了，yunionos的默认密码是多少

@ChaoHsin-fang 这个密码是随机生成的，可以用 `climc host-logininfo 物理机名称` 获取到

**Comment by ChaoHsin-fang** [comment]
climc> host-logininfo CPU-131物理机名称
{"error":{"class":"ActionNotFoundError","code":404,"details":"Action login_info not found, please check service version, current version: release/3.10(7d8b4cd9b523101015)","request":{"body":{},"headers":{"Content-Length":"2","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"POST","url":"https://IP:30888/hosts/CPU-131/login_info"}}}

**Comment by zexi** [comment]
> climc> host-logininfo CPU-131物理机名称 {"error":{"class":"ActionNotFoundError","code":404,"details":"Action login_info not found, please check service version, current version: release/3.10(7d8b4cd9b523101015)","request":{"body":{},"headers":{"Content-Length":"2","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"POST","url":"[https://IP:30888/hosts/CPU-131/login_info"}}}](https://IP:30888/hosts/CPU-131/login_info%22%7D%7D%7D)

@ChaoHsin-fang 从前端访问物理机列面，应该有获取物理机登录密码的按钮

**Comment by ChaoHsin-fang** [comment]
进入小系统手动执行如下 ：
# /opt/MegaRAID/MegaCli/MegaCli64 -CfgLdAdd -r0 [134:0] WT NORA Direct NoCachedBadBBU -a0

The specified physical disk does not have the appropriate attributes to complete
the requested command.

Exit Code: 0x26

**Comment by zexi** [comment]
> 进入小系统手动执行如下 ： /opt/MegaRAID/MegaCli/MegaCli64 -CfgLdAdd -r0 [134:0] WT NORA Direct NoCachedBadBBU -a0
> 
> The specified physical disk does not have the appropriate attributes to complete the requested command.
> 
> Exit Code: 0x26

@ChaoHsin-fang 按照这个步骤排查下：https://serverfault.com/questions/331807/megacli-is-killing-me-any-help-appreciated

**Comment by ChaoHsin-fang** [comment]
/opt/MegaRAID/MegaCli/MegaCli64 -CfgForeign -Clear -aALL

There is no foreign configuration on controller 0.

Exit Code: `0x00`

没有外部配置

**Comment by zexi** [comment]
@ChaoHsin-fang 后来解决了吗？
