### ISSUE TITLE
[求助/Help]裸金属的硬盘可以使用外部存储而不是本地磁盘吗，如根目录挂到ceph, nfs 上等

### ISSUE THREAD

**Issue by ccbutcc** [yunionio/cloudpods#19234]
求助： 由于平台无法对我们的服务器做raid, 裸金属遂放弃使用本地硬盘

裸金属的硬盘可以使用外部存储而不是本地磁盘吗，如根目录挂到ceph, nfs 上等

**Comment by swordqiu** [comment]
@ccbutcc 裸金属只支持使用物理机本地挂载的硬盘作为存储。不支持外部存储。
