### ISSUE TITLE
[求助/Help]Edge版本(3.10.11)web报错：cloudproxy服务域名解析异常, 请检查域名解析配置

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#19245]
如同：[求助/Help] cloudid，cloudproxy服务域名解析异常 #19156

1，版本
3.10.11的Edge版本高可用部署。
web页面报错：`cloudproxy服务域名解析异常, 请检查域名解析配置`

2，检查信息：
onecloud-operator的log：
```
[info 240113 17:16:33 controller.recordResourceEvent(utils.go:162)] update Ingress default-web in OnecloudCluster default successful
[error 240113 17:16:33 component.(*ComponentManager).syncDeployment(component.go:471)] get old deployment error for component esxi-agent: deployment.apps "default-esxi-agent" not found
I0113 17:16:34.387070       1 sync.go:110] component "cloudmux" is disable, skip sync
[error 240113 17:16:34 component.(*ComponentManager).syncDeployment(component.go:471)] get old deployment error for component cloudproxy: deployment.apps "default-cloudproxy" not found
[error 240113 17:16:34 component.(*ComponentManager).syncDeployment(component.go:471)] get old deployment error for component cloudid: deployment.apps "default-cloudid" not found
[error 240113 17:16:34 component.(*ComponentManager).syncDeployment(component.go:471)] get old deployment error for component cloudevent: deployment.apps "default-cloudevent" not found
I0113 17:16:34.508832       1 baremetal.go:103] List nodes by baremetal selector, node count 0
[info 240113 17:16:35 onecloud.EnsureAgentAnsiblePlaybookRef(onecloud.go:845)] start to EnsureAgentAnsiblePlaybookRef
```
```
[root@master1 ~]# kubectl -n onecloud get oc -o yaml | grep -w productVersion
    productVersion: Edge
```

**Comment by chenjacken** [comment]
请问：Edge版本是默认不安装cloudproxy、cloudid和cloudevent吗？
但是网页会提示有这个错误，pod日志也出现error

**Comment by swordqiu** [comment]
@chenjacken 收到，我们验证一下这个问题

**Comment by chenjacken** [comment]
> @chenjacken 收到，我们验证一下这个问题

好的，谢谢！🌹

**Comment by zexi** [comment]
@chenjacken 请问是访问前端哪些页面，出现了 `cloudproxy服务域名解析异常, 请检查域名解析配置` 的错误？

**Comment by chenjacken** [comment]
> @chenjacken 请问是访问前端哪些页面，出现了 `cloudproxy，cloudid 服务域名解析异常, 请检查域名解析配置` 的错误？

部署后没出现，然后我开启了k8s的功能`feature-config-k8s`，在SSH代理的页面会报错。

**Comment by zexi** [comment]
> > @chenjacken 请问是访问前端哪些页面，出现了 `cloudproxy，cloudid 服务域名解析异常, 请检查域名解析配置` 的错误？
> 
> 部署后没出现，然后我开启了k8s的功能`feature-config-k8s`，在SSH代理的页面会报错。

@chenjacken cloudproxy 的问题已经通过PR https://github.com/yunionio/cloudpods-operator/pull/1034 修复了，cloudid 的问题是在哪个前端页面出现的？

**Comment by chenjacken** [comment]
> cloudproxy服务域名解析异常, 请检查域名解析配置

页面只是提示`cloudproxy服务域名解析异常, 请检查域名解析配置`，没有cloudid，但是在onecloud-operator的log有出现cloudproxy、cloudid和cloudevent，not found。

**Comment by chenjacken** [comment]
已经通过PR https://github.com/yunionio/cloudpods-operator/pull/1034 修复了，我部署的环境如何做调整？

**Comment by zexi** [comment]
> 已经通过PR [yunionio/cloudpods-operator#1034](https://github.com/yunionio/cloudpods-operator/pull/1034) 修复了，我部署的环境如何做调整？

@chenjacken 要等待下一次版本发布升级。

我手动做了一个 onecloud-operator 的镜像，可以先手动更新：registry.cn-beijing.aliyuncs.com/zexi/onecloud-operator:v3.10-20240115.0

**Comment by chenjacken** [comment]
谢谢哈】🌹
