### ISSUE TITLE
[BUG] 云账号禁用新建虚拟机未生效

### ISSUE THREAD

**Issue by wuwish** [yunionio/cloudpods#19269]
**问题描述/What happened**:
云账号禁用后，新建虚拟机时没有过滤掉相应禁用的云订阅

**环境/Environment**:
cloudpods v3.10.7

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/5922

**Comment by hoganlxj** [comment]
@wuwish 更新前端镜像，命令如下
``` shell
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/web/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/web/tag, value: v3.10.12-20240122.0}]'
```
