### ISSUE TITLE
[BUG] 同一个云厂商多个云账号新建虚拟机时云订阅选中改变无效

### ISSUE THREAD

**Issue by wuwish** [yunionio/cloudpods#19268]
**问题描述/What happened**:
同一个云厂商录入了多个账号时，新建虚拟机时选中了不同的云订阅不生效，查看传递给后端的参数发现也是一致的

**环境/Environment**:
3.10.7 版本

- OS (e.g. `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/5917

**Comment by hoganlxj** [comment]
@wuwish 更新前端镜像
``` shell
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/web/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/web/tag, value: v3.10.12-20240122.0}]'
```
