### ISSUE TITLE
[BUG] 资源权限隔离问题

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19282]
**问题描述/What happened**:

新建了一个项目 mango5gDemain_project1， 属于域 Default
然后可以把子域  测试域1 下面的 用户 group1_user1 以及用户组 group2 给加到这个项目里面去 
不是说域之前资源，用户全部是隔离的嘛
![image](https://github.com/yunionio/cloudpods/assets/70850653/cbcc149e-524b-4f22-8a36-0aee84cc3138)
![image](https://github.com/yunionio/cloudpods/assets/70850653/af58e578-13d6-4a7e-b515-65eb2539712d)
![image](https://github.com/yunionio/cloudpods/assets/70850653/8d437b56-50f3-49b3-8368-5d639c0fd1a2)

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by dengju2020** [comment]
用户是可以跨域加入项目的。由管理员设置
