### ISSUE TITLE
[求助/Help]在云账户接入界面移动云账号没有接入选项

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19304]
看到之前有一样的issue https://github.com/yunionio/cloudpods/issues/17268
但是里面的文档打开不了，然后翻了新的文档，找不到，

**Comment by jackgao2015** [comment]
@zexi  帮忙看一下这个问题

**Comment by hoganlxj** [comment]
@xzzdhq 这是 新建移动云的文档
https://www.cloudpods.org/docs/guides/cmp/cloudaccounts/cloudaccount#%E6%96%B0%E5%BB%BA%E7%A7%BB%E5%8A%A8%E4%BA%91%E8%B4%A6%E5%8F%B7

**Comment by zexi** [comment]
> 看到之前有一样的issue #17268 但是里面的文档打开不了，然后翻了新的文档，找不到，

@xzzdhq https://www.cloudpods.org/docs/operations/hidden-feature-config#%E5%8A%9F%E8%83%BD%E5%8F%82%E7%85%A7%E8%A1%A8 这里是 feature-config 的文档。

**Comment by xzzdhq** [comment]
感谢
