### ISSUE TITLE
[求助/Help]想请教一下，现在想对接移动云的资源，但是发现移动云的虚拟机只能只读

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19309]
查看移动云的api、其实是有创建接口go版本存在的，但是这边看虚拟机资源功能是只读同步的支持情况
![image](https://github.com/yunionio/cloudpods/assets/70850653/da38ea85-8ddd-42ce-8c86-c1c42632299e)

**Comment by ioito** [comment]
移动云目前并未支持写操作，用的人比较少

**Comment by xzzdhq** [comment]
意思是现有的移动云接口 可以接入进来在cloudpods这边做部分资源的创建嘛

**Comment by ioito** [comment]
可以加，也欢迎开源贡献 https://www.cloudpods.org/docs/development/resource_sync/add-cloud 这个是对接文档
