### ISSUE TITLE
[BUG]在计算节点上执行kubuctl提示错误

### ISSUE THREAD

**Issue by dengni-10000** [yunionio/cloudpods#19317]
**问题描述/What happened**:
使用ocboot安装私有云，添加了一台计算节点，在计算节点执行kubectl有问题，但安装节点上没有问题
kubectl logs -n onecloud default-telegraf-XXX -c telegraf
The connection to the server localhost:8080 was refused - did you specify the right host or port?
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):centos7.9
- Kernel (e.g. `uname -a`):5.4.130-1.yn20230805.el7.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@dengni-10000 计算节点上的 kubectl 不会配置认证信息，是故意这样的，要访问 k8s 请到第一个控制节点执行。
如果实在要在计算节点上执行 kubectl 访问集群，可以把控制节点的 /etc/kubernetes/admin.conf 拷贝到计算节点的 ~/.kube/config ，就可以了。
