### ISSUE TITLE
[Feature]IP地址修改

### ISSUE THREAD

**Issue by shengxianli** [yunionio/cloudpods#19318]
IP地址变了，不会自动更新，好像不能手动修改地址
![image](https://github.com/yunionio/cloudpods/assets/32296103/dde33053-9a99-4a0d-8759-a56386489e2e)

**Comment by wanyaoqi** [comment]
@shengxianli 运行中修改ip需要虚机内安装QGA

**Comment by shengxianli** [comment]
@wanyaoqi 
关机也不行是不是VMware不支持
![image](https://github.com/yunionio/cloudpods/assets/32296103/6ad47665-763b-4034-964a-57169c4bda9f)

**Comment by wanyaoqi** [comment]
@shengxianli 哦你是vmware的机器，下次可以先说明一下
vmware关机重置密码应该可以，需要关机修改密码后部署一下机器。
```bash
climc server-deploy <ID>
```

目前产品上好像没有支持这个操作，需要手动执行一下。
