### ISSUE TITLE
[求助/Help] how to delete a server IP once a VM is deleted

### ISSUE THREAD

**Issue by eddiewang** [yunionio/cloudpods#19313]
Hello!

I'm currently evaluating Cloudpods all in one, and was able to provision a QEMU VM with no issues. However, once I deleted the VM, it seems like the IP on the VNIC doesn't get cleaned up.

This leads me to have a network on my VPC that I cannot delete. I tried looking for an option in climc but the closest command only lists the network ips.

**Comment by swordqiu** [comment]
@eddiewang the server might be in pending delete state, please check with command line:

```
climc server-list --pending-delete
```

You may clean up the server permanently by:

```
climc server-delete -f <sid>
```

**Comment by eddiewang** [comment]
thank you @swordqiu - that worked great. do you know why the server would be in pending delete state?

**Comment by swordqiu** [comment]
@eddiewang this is a feature by design, to give user a chance to recover deleted VM. If a VM was pending deleted for  curtain period (three days by default), the VM will be finally cleaned up.
