### ISSUE TITLE
[求助/Help] cloudpods配置通用oidc登陆成功之后报错

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19340]
![1f9e47cf0725258b151af6bc9fa5662](https://github.com/yunionio/cloudpods/assets/19704134/6aa55705-28df-4953-82a1-1ae3a9bb4f4e)

如图所示，我正常配置了一个通用oidc的登录配置，用户名密码接口已经正常通过，但是到了cloudpods之后，报错无效的用户名密码，我当时没有配置自动创建用户，请问和这个配置有关系吗??

**Comment by ioito** [comment]
是的，因为没有github用户和本地用户的关联关系，找不到本地对应的用户登录

**Comment by dengju2020** [comment]
@ilovedumplings 这个功能需要到已有个人中心先关联下（目前仅私有云支持）。不然登陆会失败。
