### ISSUE TITLE
[求助/Help] cloudpods通用OIDC logout配置

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19341]
看通用oidc配置相关endpoint的时候,并没有配置登出协议,然后在cloudpods页面点击登出,重新通过三方oidc协议登陆的时候,cookie并没有删除,还会直接跳转到登出账号的页面

**Comment by zhasm** [comment]
duplicated: https://github.com/yunionio/cloudpods/issues/19340
