### ISSUE TITLE
[BUG] 云账号改为只读模式后新建公有云虚拟机依然可以选中

### ISSUE THREAD

**Issue by wuwish** [yunionio/cloudpods#19462]
**问题描述/What happened**:
云账号改为只读模式后新建公有云虚拟机依然可以选中

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/19468/files
@easy-mj
GET /cloudproviders?read-only=false 可过滤非只读模式订阅列表
GET /cloudaccounts?read-only=false 可过滤非只读模式云账号列表

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/6065
