### ISSUE TITLE
[求助/Help] 删除虚拟机，宿主机目录/opt/cloud/workspace/disks/snapshots/下快照无法删除

### ISSUE THREAD

**Issue by baiweiyll** [yunionio/cloudpods#19522]
环境/Environment:

OS
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
Kernel
4.19.90-24.4.v2101.ky10.aarch64
Host
Manufacturer: HiSilicon
Manufacturer: Huawei
Manufacturer: NO DIMM
Manufacturer: Samsung
Memory Subsystem Controller Manufacturer ID: Unknown
Memory Subsystem Controller Product ID: Unknown
Module Manufacturer ID: Unknown
Module Product ID: Unknown
Product Name: BC82AMDD
Product Name: TaiShan 2280 V2
Service
3.9.14
使用麒麟v10桌面系统作为虚拟机镜像启动后，对磁盘（本地存储）手动进行创建磁盘快照，创建2个快照后，手动删除快照，观察宿主机目录/opt/cloud/workspace/disks/snapshots/下还存在快照文件，接着手动删除虚拟机，并勾选“同时删除快照”，最后在回收站将虚拟机彻底清除后，发现宿主机对应目录下还是存在已经删掉虚拟机的快照文件

**Comment by wanyaoqi** [comment]
这个是由于快照删除不是同步删除的，后续已经改成同步删除了 https://github.com/yunionio/cloudpods/pull/19844
