### ISSUE TITLE
[BUG] 创建阿里云虚拟机，选中的实例规格无法创建

### ISSUE THREAD

**Issue by wuwish** [yunionio/cloudpods#19536]
**问题描述/What happened**:
创建阿里云虚拟机时，选中了实例规格ecs.n1.tiny，无法创建出虚拟机，报错如下
![ef947a39afd0dd910d5bd1ea3940030](https://github.com/yunionio/cloudpods/assets/41946192/f54f1b4f-607a-4c72-a7cc-860efab3cb92)。
查询了https://yunionmeta.oss-cn-beijing.aliyuncs.com/serversku/Aliyun/cn-hangzhou.status.json，ecs.n1.tiny实例仅有可用区h、j、k可用，此处是否有问题？

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wuwish** [comment]
@ioito 我使用的云账号没有这三个可用区的交换机，因此创建会失败，但是为什么oss套餐中ecs.n1.tiny之和h、j、k三个可用区做了关联呢，此处的逻辑是怎么样的

**Comment by ioito** [comment]
region(区域) zone(可用区) 是每个阿里云账号公用的(大家都有，不用创建)，因此套餐是能直接和region zone绑定的，子网是各自账号需要单独创建的资源， 实际创建过程中需要判断对应账号底下对应的可用区底下是否有可用的子网资源

**Comment by wuwish** [comment]
那上述ecs.n1.tiny实例规格为什么只有h、j、k三个可用区可用，其它可用区应该也要有这个实例规格

**Comment by ioito** [comment]
![image](https://github.com/yunionio/cloudpods/assets/13750250/8af4fb11-2192-4f07-b486-572b97d87122)

**Comment by wuwish** [comment]
我的账号支持的可用区好像更多
![image](https://github.com/yunionio/cloudpods/assets/41946192/b9ec08cf-16b2-4b31-b7fb-a331034b712c)
方便问一下，上述实例规格与可用区关联关系可以通过哪个接口查询吗

**Comment by ioito** [comment]
好吧，你的账号YYDS
https://api.aliyun.com/api/Ecs/2014-05-26/DescribeAvailableResource?params={%22RegionId%22:%22cn-hangzhou%22,%22InstanceChargeType%22:%22PostPaid%22,%22InstanceType%22:%22ecs.n1.tiny%22,%22DestinationResource%22:%22InstanceType%22}&tab=DEBUG

**Comment by wuwish** [comment]
可能因为我的是企业账号，那我目前有什么好的方法解决这个问题吗

**Comment by ioito** [comment]
可以手动创建套餐，目前前端还不支持，需要用climc操作 climc server-sku-create  -xxx -xxx -xxx 参数很多，且参数跟你的环境有关

**Comment by wuwish** [comment]
明白，感谢大佬~

**Comment by wuwish** [comment]
> 明白，感谢大佬~

对了，我手动改库后，下一次同步会不会刷掉

**Comment by ioito** [comment]
只有external_id不为空才会同步更新删除，所以清除掉external_id之后，这些记录就不会变更

**Comment by wuwish** [comment]
好的，感谢感谢~
