### ISSUE TITLE
[BUG]代码key为空

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19557]
**问题描述/What happened**:
![image](https://github.com/yunionio/cloudpods/assets/70850653/a87ff10c-6b67-4e1c-9487-cd5dba1c1516)
代码位置pkg/scheduler/manager/task_queue.go:229
这里的key 是一个恒久为空的情况，是否是逻辑有问题呢
**环境/Environment**:
v3.0.10
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@xzzdhq 是有代码上的逻辑问题，但因为一个队列也能调度，所以从结果上来说没有出问题。
感谢反馈，已经提 PR 修复，这样在同一时刻不同 hypervisor 类型调度的时候，能提高性能。
