### ISSUE TITLE
从 v3.10.10 升级到 v3.11.0 创建虚拟机， 部署环节报错[BUG]

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#19565]
**问题描述/What happened**:
从 v3.10.10 升级到 v3.11.0 创建虚拟机， 部署环节报错
**环境/Environment**:
<img width="588" alt="1d405967b5925eb59154b7fa42816fc" src="https://github.com/yunionio/cloudpods/assets/35864027/ca216f7e-7538-42de-8cd6-9f86095df98c">

{
    "__reason__": "Async start server failed: init guest networks: generateNicScripts for nic: &{{{vpctest 4e4e8ec4-aea1-4432-825f-225c7b28d81f 00:22:06:dc:7a:46 false 172.168.11.95 172.168.11.1 192.168.1.150 cloud.onecloud.io  <nil> vpctest-95 24 1 1000 1500 0 0 0    0 true  95e2013e-9dfd-4313-858c-540785ae418b  {  } <nil> []} virtio 1 <nil>   <nil>   0  false} <nil>}: Can't find bridge ",
    "__stage__": "OnStartComplete",
    "__status__": "error"
}

- OS (e.g. `cat /etc/os-release`):
[root@centosbase ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
[root@centosbase ~]# uname -a
Linux centosbase 5.4.130-1.yn20230805.el7.x86_64 #1 SMP Wed Oct 11 03:26:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
[root@centosbase ~]# dmidecode | egrep -i 'manufacturer|product' |sort -u
        Manufacturer: QEMU
        Product Name: Standard PC (i440FX + PIIX, 1996)
[root@centosbase ~]#

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

![image](https://github.com/yunionio/cloudpods/assets/35864027/486f1ba2-5192-4af4-b4c9-81d4f35943c8)

**Comment by wanyaoqi** [comment]
@khw934 执行一下 climc server-desc <ID> 看下

**Comment by khw934** [comment]
> @khw934 执行一下 climc server-desc 看下

bash-5.1# climc server-desc 01cd4bca-2b98-4f59-8c8a-78a77c15a3e1
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      Field       |                                                                                       Value                                                                                        |
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| bios             | BIOS                                                                                                                                                                               |
| boot_order       | cdn                                                                                                                                                                                |
| cpu              | 2                                                                                                                                                                                  |
| cpu_sockets      | 1                                                                                                                                                                                  |
| disks            | [{"aio_mode":"native","boot_index":-1,"bps":0,"cache_mode":"none","disk_id":"e330c0f7-5270-4f83-85b1-a4899347b09e","driver":"scsi","format":"qcow2","image_path":"/opt/cloud/works |
|                  | pace/disks/image_cache/26b39ceb-794c-4a70-8ade-4a97f6aea436","index":0,"iops":0,"is_ssd":false,"merge_snapshot":false,"migrating":false,"num_queues":0,"path":"/opt/cloud/workspac |
|                  | e/disks/e330c0f7-5270-4f83-85b1-a4899347b09e","size":30720,"storage_id":"7196524e-1ae9-410f-8f3b-da67a5a66eda","storage_type":"local","template_id":"26b39ceb-794c-4a70-8ade-4a97f |
|                  | 6aea436","throughput":0}]                                                                                                                                                          |
| domain           | cloud.onecloud.io                                                                                                                                                                  |
| domain_id        | default                                                                                                                                                                            |
| host_id          | 0cb08d19-3f09-4b23-8cd4-f17f980efd8e                                                                                                                                               |
| hostname         | khw934                                                                                                                                                                             |
| is_daemon        | false                                                                                                                                                                              |
| is_volatile_host | false                                                                                                                                                                              |
| light_mode       | false                                                                                                                                                                              |
| machine          | pc                                                                                                                                                                                 |
| mem              | 2048                                                                                                                                                                               |
| metadata         | {"__cpu_mode":"host","__enable_cgroup_cpuset":"true","__os_profile__":"{\"disk_driver\":\"scsi\",\"fs_format\":\"ext4\",\"hypervisor\":\"kvm\",\"net_driver\":\"virtio\",\"os_type |
|                  | \":\"Linux\"}","__qemu_cmdline":"$QEMU_CMD $QEMU_CMD_KVM_ARG -S -cpu host,kvm_pv_eoi=on,vendor=GenuineIntel -chardev socket,id=hmqmondev,port=55902,host=127.0.0.1,nodelay,server, |
|                  | nowait -mon chardev=hmqmondev,id=hmqmon,mode=readline -chardev socket,id=qmqmondev,port=56102,host=127.0.0.1,nodelay,server,nowait -mon chardev=qmqmondev,id=qmqmon,mode=control - |
|                  | rtc base=utc,clock=host,driftfix=none -nodefaults -no-user-config -global kvm-pit.lost_tick_policy=discard -machine pc,accel=kvm -k en-us -smp cpus=2,sockets=2,cores=120,maxcpus= |
|                  | 240 -name 'khw934',debug-threads=on -uuid 01cd4bca-2b98-4f59-8c8a-78a77c15a3e1 -m 2048M,slots=4,maxmem=524288M -object memory-backend-ram,id=mem,size=2048M -numa node,memdev=mem  |
|                  | -boot cdn -device VGA,id=video0,bus=pci.0,addr=0x02 -vnc :2,password -object iothread,id=iothread0 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x03 -device virtio- |
|                  | scsi-pci,id=scsi,bus=pci.0,addr=0x04 -drive file=$DISK_0,if=none,id=drive_0,cache=none,aio=native,file.locking=off -device scsi-hd,serial=e330c0f752704f8385b1a4899347b09e,drive=d |
|                  | rive_0,bus=scsi.0,id=drive_0 -drive id=ide0-cd0,if=none,media=cdrom -device ide-cd,drive=ide0-cd0,bus=ide.1 -netdev type=tap,id=vpctest-94,ifname=vpctest-94,vhost=on,vhostforce=o |
|                  | ff,script=/opt/cloud/workspace/servers/01cd4bca-2b98-4f59-8c8a-78a77c15a3e1/if-up-br0-vpctest-94.sh,downscript=/opt/cloud/workspace/servers/01cd4bca-2b98-4f59-8c8a-78a77c15a3e1/i |
|                  | f-down-br0-vpctest-94.sh -device virtio-net-pci,id=netdev-vpctest-94,bus=pci.0,addr=0x05,netdev=vpctest-94,mac=00:22:2a:9a:1e:8e$(nic_speed 1000) -usb -device usb-kbd -device usb |
|                  | -tablet -device qemu-xhci,id=usb,bus=pci.0,addr=0x06 -pidfile /opt/cloud/workspace/servers/01cd4bca-2b98-4f59-8c8a-78a77c15a3e1/pid   -chardev socket,id=qga0,server,nowait,path=/ |
|                  | opt/cloud/workspace/servers/01cd4bca-2b98-4f59-8c8a-78a77c15a3e1/qga.sock -device virtserialport,bus=virtio-serial0.0,chardev=qga0,name=org.qemu.guest_agent.0 -object rng-random, |
|                  | id=rng0,filename=/dev/urandom -device virtio-rng-pci,id=random0,bus=pci.0,addr=0x07,max-bytes=1024,period=1000,rng=rng0 -chardev pty,id=charserial0 -device isa-serial,chardev=cha |
|                  | rserial0,id=serial0 -device pvpanic,id=pvpanic,ioport=0x505","__qemu_version":"4.2.0","__vnc_password":"q2GtYcW3","__vnc_port":"2","create_params":"{\"__count__\":1,\"__os_profil |
|                  | e__\":{\"disk_driver\":\"scsi\",\"fs_format\":\"ext4\",\"hypervisor\":\"kvm\",\"net_driver\":\"virtio\",\"os_type\":\"Linux\"},\"auto_start\":true,\"count\":1,\"deploy_telegraf\" |
|                  | :true,\"description\":\"\",\"disks\":[{\"backend\":\"local\",\"disk_type\":\"sys\",\"driver\":\"scsi\",\"image_id\":\"26b39ceb-794c-4a70-8ade-4a97f6aea436\",\"image_properties\": |
|                  | {\"arch\":\"x86_64\",\"disk_format\":\"qcow2\",\"distro\":\"CentOS\",\"installed_cloud_init\":\"false\",\"is_lvm_partition\":\"false\",\"is_readonly\":\"false\",\"os_arch\":\"x86 |
|                  | _64\",\"os_distribution\":\"CentOS\",\"os_language\":\"\",\"os_type\":\"Linux\",\"os_version\":\"7.6.1810\",\"partition_type\":\"\",\"uefi_support\":\"false\",\"version\":\"7.6.1 |
|                  | 810\"},\"index\":0,\"medium\":\"rotate\",\"os_arch\":\"x86_64\",\"size\":30720}],\"domain\":\"default\",\"domain_id\":\"default\",\"hostname\":\"khw934\",\"hypervisor\":\"kvm\",\ |
|                  | "instance_type\":\"ecs.g1.c2m2\",\"name\":\"khw934\",\"nets\":[{\"bw_limit\":1000,\"domain_id\":\"default\",\"driver\":\"virtio\",\"exit\":true,\"index\":0,\"network\":\"4e4e8ec4 |
|                  | -aea1-4432-825f-225c7b28d81f\",\"num_queues\":0,\"private\":false,\"project_id\":\"b8682393d759479886125db40f5f7b90\",\"require_designated_ip\":false,\"require_teaming\":false,\" |
|                  | reserved\":false,\"rx_traffic_limit\":0,\"standby_addr_count\":0,\"standby_port_count\":0,\"try_teaming\":false,\"tx_traffic_limit\":0,\"vip\":false}],\"os_arch\":\"x86\",\"os_ty |
|                  | pe\":\"Linux\",\"policy_domain_tags\":[],\"policy_object_tags\":[],\"policy_project_tags\":[],\"prefer_region\":\"default\",\"prefer_region_id\":\"default\",\"prefer_zone\":\"94f |
|                  | 25464-30bb-42b7-8ee4-b88a7e57f4f0\",\"prefer_zone_id\":\"94f25464-30bb-42b7-8ee4-b88a7e57f4f0\",\"project\":\"b8682393d759479886125db40f5f7b90\",\"project_domain\":\"default\",\" |
|                  | project_domain_id\":\"default\",\"project_id\":\"b8682393d759479886125db40f5f7b90\",\"secgrp_id\":\"default\",\"sku\":\"ecs.g1.c2m2\",\"tenant\":\"b8682393d759479886125db40f5f7b9 |
|                  | 0\",\"tenant_id\":\"b8682393d759479886125db40f5f7b90\",\"vcpu_count\":2,\"vmem_size\":2048}","generate_name":"khw934","hot_remove_nic":"enable","hotplug_cpu_mem":"enable","last_l |
|                  | ogin_key":"+v/SLlwdZh8X+BKYNM3I48EypMsgERTg/wH8bA==","login_account":"root","login_key":"+v/SLlwdZh8X+BKYNM3I48EypMsgERTg/wH8bA==","login_key_timestamp":"2024-02-28T07:12:18.4749 |
|                  | 84Z","os_arch":"x86_64","os_distribution":"CentOS","os_name":"Linux","os_version":"7.6.1810","start_vcpu_count":"2","start_vmem_mb":"2048","telegraf_deployed":"true"}             |
| name             | khw934                                                                                                                                                                             |
| nics             | [{"bw":1000,"dns":"192.168.1.150","domain":"cloud.onecloud.io","driver":"virtio","gateway":"172.168.11.1","ifname":"vpctest-94","index":0,"interface":"enp0s25","ip":"172.168.11.9 |
|                  | 4","is_default":false,"link_up":false,"mac":"00:22:2a:9a:1e:8e","masklen":24,"masklen6":0,"mtu":1500,"net":"vpctest","net_id":"4e4e8ec4-aea1-4432-825f-225c7b28d81f","num_queues": |
|                  | 1,"rate":0,"rx_traffic_limit":0,"tx_traffic_limit":0,"virtual":false,"vlan":1,"wire_id":"95e2013e-9dfd-4313-858c-540785ae418b"}]                                                   |
| os_name          | Linux                                                                                                                                                                              |
| pending_deleted  | false                                                                                                                                                                              |
| project_domain   | Default                                                                                                                                                                            |
| secgroups        | [{"id":"default","name":"Default"}]                                                                                                                                                |
| security_rules   | in:allow 0.0.0.0/0 any                                                                                                                                                             |
| src_ip_check     | true                                                                                                                                                                               |
| src_mac_check    | true                                                                                                                                                                               |
| tenant           | system                                                                                                                                                                             |
| tenant_id        | b8682393d759479886125db40f5f7b90                                                                                                                                                   |
| uuid             | 01cd4bca-2b98-4f59-8c8a-78a77c15a3e1                                                                                                                                               |
| vdi              | vnc                                                                                                                                                                                |
| vga              | std                                                                                                                                                                                |
| zone             | zone0                                                                                                                                                                              |
| zone_id          | 94f25464-30bb-42b7-8ee4-b88a7e57f4f0                                                                                                                                               |
+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
bash-5.1#

**Comment by wanyaoqi** [comment]
@khw934  确认一下虚机使用的网络 `vpc2` 是 vpc子网吧
<img width="792" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/d333102a-26d3-4394-ae48-d2bd45ff8326">
看虚机网络详情中并没有拿到 vpc 相关的信息
你可以执行一些 climc network-show vpc2 给我看下。

**Comment by khw934** [comment]
> climc network-show vpc2

是使用  vpc2 , 如果版本回退就可以

![image](https://github.com/yunionio/cloudpods/assets/35864027/936930c5-87c7-4250-8953-f5a7efc79023)

**Comment by wanyaoqi** [comment]
@khw934 这个是经典网络的，我们排查一下，看起来是有问题，升级到3.11后虚机网卡 desc 中缺少 bridge 字段

**Comment by wanyaoqi** [comment]
@khw934 执行一下看下climc host-network-list --details

**Comment by khw934** [comment]
> climc host-network-list --details

![image](https://github.com/yunionio/cloudpods/assets/35864027/f2cd1a40-8056-484e-961d-565fb9459ce6)

**Comment by wanyaoqi** [comment]
@khw934 我们环境没有复现这个问题，感觉可能升级到 3.11 然后 region 回滚到 3.10引起的。

**Comment by khw934** [comment]
> @khw934 我们环境没有复现这个问题，感觉可能升级到 3.11 然后 region 回滚到 3.10引起的。

这个问题怎么解决？

**Comment by hoganlxj** [comment]
这个问题修复了，升级到v3.11后，需要再升级region，命令如下
```bash
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/regionServer/tag, value: v3.11.2-20240314.2}]'
```

**Comment by fangpsh** [comment]
昨天重启虚拟机，遇到类似错误日志：
```
{
    "__reason__": "Async start server failed: init guest networks: generateNicScripts for nic: &{{{sz-vlan200 6e04b4a8-ad33-4e06-8ce3-71510b03af1b 00:22:88:00:7d:24 false 192.168.200.222 192.168.200.253 192.168.100.80,192.168.100.81 zego.cloud  <nil> szvlan200-222 24 200 1000 1500 0 0 0    0 true  1dc3c180-fcb3-4343-8908-8f6d88048540  {  } <nil> []} virtio 1 <nil>   <nil>   0  false} <nil>}: Can't find bridge ",
    "__stage__": "OnStartComplete",
    "__status__": "error"
}
```

升级到了[v3.11.2](https://github.com/yunionio/cloudpods/releases/tag/v3.11.2)   好了。
