### ISSUE TITLE
[文档/Docs]啥时候发新版本？

### ISSUE THREAD

**Issue by rekazer0** [yunionio/cloudpods#19587]
Releases的旧版本看了一下删除了，是要发新版本的吗？昨天clone源码发现按照部署文档部署会出现一些问题。
因为现在不能部署旧版本的，问下新的Release大概啥时候发布呢？

**Comment by swordqiu** [comment]
@rekazer0 已经发布release v3.11.0 了，可以部署 v3.11.0

**Comment by rekazer0** [comment]
好的，非常感谢

**Comment by rekazer0** [comment]
@zexi @swordqiu 好的，非常感谢
