### ISSUE TITLE
[文档/Docs]框架的方法映射求助

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19592]
**What part of the document needs to be added**:
想问一下，这里的接口和框架的方法映射应该是有更新的，想问一下文档这块有更新计划嘛
https://www.cloudpods.org/docs/development/backend-framework#%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E6%A1%86%E6%9E%B6-1

![image](https://github.com/yunionio/cloudpods/assets/70850653/f6acf651-58c4-410e-af84-99b3768e251f)

**Comment by ioito** [comment]
https://github.com/yunionio/docs/pull/1895/files 目前仅 FetchCustomizeColumns 有变更，其他保持不变

**Comment by xzzdhq** [comment]
感谢，屈轩大佬yyds！
