### ISSUE TITLE
[求助/Help]在部署TASK [primary-master-node/setup_k8s : Wait 500 seconds for primary master to response:过程中遇到问题

### ISSUE THREAD

**Issue by rekazer0** [yunionio/cloudpods#19614]
部署版本：3.11
环境：Ubuntu 22.04.4 LTS X86（基于EXSI 8.0）
使用命令 ./run.py virt 10.112.9.60进行部署

TASK [primary-master-node/setup_k8s : show init args] **************************
ok: [10.112.9.60] => {
    "msg": "/opt/yunion/bin/ocadm init --control-plane-endpoint 10.112.9.60:6443 --mysql-host 10.112.9.60 --mysql-user root --mysql-password rDZAjyC2a9fh --mysql-port 3306 --image-repository registry.cn-beijing.aliyuncs.com/yunion --apiserver-advertise-address 10.112.9.60  --node-ip 10.112.9.60 --host-networks ens192/br0/10.112.9.60  --enable-hugepage --onecloud-version v3.11.0 --operator-version v3.11.0 --pod-network-cidr 10.40.0.0/16 --service-cidr 10.96.0.0/12 --service-dns-domain cluster.local --addon-calico-ip-autodetection-method 'can-reach=10.112.9.60' --enable-host-agent"
}

TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ********
skipping: [10.112.9.60]

TASK [primary-master-node/setup_k8s : Wait 500 seconds for primary master to response: 10.112.9.60:6443] ***
fatal: [10.112.9.60]: FAILED! => {"changed": false, "elapsed": 500, "msg": "Timeout when waiting for 10.112.9.60:6443"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
10.112.9.60                : ok=123  changed=17   unreachable=0    failed=1    skipped=38   rescued=0    ignored=0

**kubelet 日志：**
I0304 12:04:19.590203   51715 server.go:425] Version: v1.15.12
I0304 12:04:19.590810   51715 plugins.go:103] No cloud provider specified.
W0304 12:04:19.590905   51715 server.go:564] standalone mode, no API client
W0304 12:04:19.591090   51715 server.go:628] failed to get the kubelet's cgroup: mountpoint for cpu not found.  Kubelet system container metrics may be missing.
W0304 12:04:19.591334   51715 server.go:635] failed to get the container runtime's cgroup: failed to get container name for docker process: mountpoint for cpu not found. Runtime system container metrics may be missing.
F0304 12:04:19.591719   51715 server.go:273] failed to run Kubelet: mountpoint for cpu not found

### 系统版本：
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by rekazer0** [comment]
此问题为

**Comment by zhasm** [comment]
拉一下最新代码，看看能否复现。如果能复现，看一下输出：
```bash
cat /proc/cmdline
```

**Comment by rekazer0** [comment]
> @rekazer0
> 
> 拉一下最新代码，看看能否复现。如果能复现，看一下输出：
> 
> ```shell
> cat /proc/cmdline
> ```
> 
> 预期会有 `systemd.unified_cgroup_hierarchy=0` 这个字符串。
是的
```shell
root@cloudpods:~# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-5.15.0-107-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro systemd.unified_cgroup_hierarchy=0 nouveau.modeset=0 iommu=pt rdblacklist=nouveau mgag200.modeset=0 intel_iommu=on crashkernel=auto vfio_iommu_type1.allow_unsafe_interrupts=1
```
