### ISSUE TITLE
[BUG]post接口入参key不对

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19616]
**问题描述/What happened**:
代码位置 pkg/appsrv/dispatcher/dispatcher.go:318 
![image](https://github.com/yunionio/cloudpods/assets/70850653/cc3b7863-b4b3-4124-8199-d5ed8b20ac62)

现在代码位置 判断是创建一个还是多个是取字段 count 
但是 调用ecs 创建公有云资源 
接口为 https://dev.cloud.mg.xyz/api/v2/servers 
入参 字段只有一个    "__count__": 1,

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
没太懂什么意思，能说下预期及目前有什么问题？

**Comment by xzzdhq** [comment]
意思是 后端代码这里是通过取 入参query中 key为 count的值来判断是走单个还是批量，然后现在看 创建ecs单个资源的前端请求，没有 key=count的这个入参字段，只有__count__

**Comment by ioito** [comment]
创建路径是 用户 -> web(nginx) -> apigateway(网关) -> region
__count__ 参数在apigateway(网关) https://github.com/yunionio/cloudpods/blob/master/pkg/apigateway/handler/resource.go 做了处理
