### ISSUE TITLE
[求助/Help] 虚拟机在线快照报错Reload blkdev error: onReloadBlkdevFail：GenericError: Could not open backing fle：Failed to get shared \"write\" lock"

### ISSUE THREAD

**Issue by baiweiyll** [yunionio/cloudpods#19623]
1、按照https://github.com/yunionio/qemu/tree/main步骤编译qemu，
2、编译完后替换/usr/local/qemu-4.2.0/bin/qemu-system-aarch64文件
3、在虚拟机开机状态下对磁盘创建快照报错，错误信息为：Reload blkdev error: onReloadBlkdevFail：GenericError: Could not open backing fle：Failed to get shared \"write\" lock"

虚拟机使用的本地存储

环境/Environment:

OS
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
Kernel
4.19.90-24.4.v2101.ky10.aarch64
Host
Manufacturer: HiSilicon
Manufacturer: Huawei
Manufacturer: NO DIMM
Manufacturer: Samsung
Memory Subsystem Controller Manufacturer ID: Unknown
Memory Subsystem Controller Product ID: Unknown
Module Manufacturer ID: Unknown
Module Product ID: Unknown
Product Name: BC82AMDD
Product Name: TaiShan 2280 V2
Service
3.9.14

**Comment by swordqiu** [comment]
@baiweiyll 因内核头文件申明 F_OFD_SETLK 导致，已在 README 补充说明避免方法：https://github.com/yunionio/qemu/pull/10/files
