### ISSUE TITLE
[求助/Help]openstack监控数据无法获取

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#19649]
cloudpods ----
version: v3.10.8
openstack ----
vesion: 2.23.2

我在cloudpods上面纳管了一个openstack ,纳管完成之后，openstack的nova计算节点被cloudpods作为宿主机进行纳管。但是我在cloudpods上点击该宿主机的监控的时候，发现数据都是空的。我看了官网的介绍，cloudmon不支持从Openstack上采集监控数据。我想求证一下，纳管openstack有什么方式可以采集到监控数据吗？

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/operations/agent/ 可以手动安装监控agent试下，需要网络和cloudpods打通

**Comment by huhaiqwer** [comment]
> https://www.cloudpods.org/docs/operations/agent/ 可以手动安装监控agent试下，需要网络和cloudpods打通

请问是在nova结算节点上面手动安装agent吗？ cloudpods本身是不支持监控openstack的吗？

**Comment by ioito** [comment]
要看虚拟机监控，需要到openstack各个虚拟机中装agent, cloudpods本身是不支持openstack监控
