### ISSUE TITLE
[BUG]我用api文档中的compute(计算服务)/server的创建虚拟机实例Post请求，总是报500错误，怎么解决？

### ISSUE THREAD

**Issue by AuZn-wjx** [yunionio/cloudpods#19660]
**问题描述/What happened**:
因为本身创建虚拟机的请求中参数很多，我根据网页端新建虚拟机的关键信息来进行创建还是报500的错误
![image](https://github.com/yunionio/cloudpods/assets/65400797/343eaebd-3a1b-4b30-9518-0cd81e54be36)
请求方式是:POST
请求的url是：{{url}}/servers
以下是我的请求Body
```json
{
    "auto_start": true,
    "generate_name": "wjx_host2",
    "name": "wjx_host2",
    "description": "test create network",
    "hypervisor": "aliyun",
    "count": 1,
    "disks": [
        {
            "disk_type": "sys",
            "index": 0,
            "backend": "cloud_essd_pl3",
            "size": 25600,
            "image_id": "ba4f0037-00b0-4bbc-8f54-9a38affb5351",
            "medium": "rotate"
        }
    ],
    "nets": [
        {
            "network": "3030648a-195d-45d1-8253-c4641b09c41d"
        }
    ],
    "prefer_region_id": "7f75db7e-6d2a-44f4-818d-bc29baca0d3d",
    "vcpu_count": 2,
    "vmem_size": 2048,
    "project_id": "c5f7db1b78e345008dfe60d70c9780e8",
    "prefer_zone_id": "9c60386d-693e-49b3-8454-8f63c10bb6b1",
    "prefer_manager_id": "06d147b9-30bf-477b-80b7-46e383b0eaf8",
    "dry_run": true
}
有大佬知道是什么原因引起的么？
``` 
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by AuZn-wjx** [comment]
请求头也加入进去了
![image](https://github.com/yunionio/cloudpods/assets/65400797/2dee04ec-f61f-4acc-8aee-e47a4fee4eb7)

**Comment by hoganlxj** [comment]
> 请求头也加入进去了 ![image](https://private-user-images.githubusercontent.com/65400797/310433107-2dee04ec-f61f-4acc-8aee-e47a4fee4eb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTY4MjcsIm5iZiI6MTcwOTcxNjUyNywicGF0aCI6Ii82NTQwMDc5Ny8zMTA0MzMxMDctMmRlZTA0ZWMtZjYxZi00YWNjLThhZWUtZTQ3YTRmZWU0ZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA5MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZTdhNzUyMjBlYmY5NDk5NzU5NTlkOTRiOWZiZTI5NmM2NjA4MWVhNTIxNTk2MjlhNDcwNWNkNmJjNmYzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c8FwVMzxuY0wyYS7nlIGOUImMrn5A557IKPgL5IKXhM)
看着是Headers有问题，把X-Auth-Token换成Cookie

**Comment by ioito** [comment]
<img width="660" alt="image" src="https://github.com/yunionio/cloudpods/assets/13750250/b52d48ef-5099-458d-87fe-125e1e6f7bf3">
size单位默认是M, 大于500G

**Comment by AuZn-wjx** [comment]
> <img alt="图像" width="660" src="https://private-user-images.githubusercontent.com/13750250/310446835-b52d48ef-5099-458d-87fe-125e1e6f7bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjE4NDIsIm5iZiI6MTcwOTg2MTU0MiwicGF0aCI6Ii8xMzc1MDI1MC8zMTA0NDY4MzUtYjUyZDQ4ZWYtNTA5OS00NThkLTg3ZmUtMTI1ZTFlNmY3YmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAxMzIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YWNmMTQ3YmI0NWY2MzUzMmU1ZDIyM2IwYjUyNDM5Nzg4MjkxN2IwMjc4YzNkNDUyYTJlNmExMjBmN2RmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kk2xMSJj1yRD_CGMmvq-3ZkvKyMoe7gamWZDBwiKc9Y">size单位默认是M， 大于500G

这个我是故意不调成20GB~500GB内来获取这个错误的请求，目的是拿到创建虚拟机的关键信息在这里框框标出的信息：
![image](https://github.com/yunionio/cloudpods/assets/65400797/5dabeb08-44ac-40c3-8132-e3216b15f3a2)
获取到该主要信息后，我再根据api文档内的全部属性来筛选出填写Post请求Body的关键信息信息：
api文档信息如下：
![image](https://github.com/yunionio/cloudpods/assets/65400797/6fad59b8-5634-458c-a001-1f21b1c02b57)
这里是我参考网页中错误信息的关键信息+api文档内的字段在Postman中填写成Post请求的Body部分
![image](https://github.com/yunionio/cloudpods/assets/65400797/6f82c805-f099-4f7c-bb55-3047f1397766)
在Postman中的Body即url信息
发送过去之后就会报Post请求500错误这怎么解决？
![image](https://github.com/yunionio/cloudpods/assets/65400797/34d2b75d-1c2b-4426-a5e6-fd1ddd752310)

**Comment by AuZn-wjx** [comment]
> 贡献

这个我试着把X-Auth-Token换成了网页端的cookie也还是报500错误

**Comment by AuZn-wjx** [comment]
换成了这个网页端的请求头中的cookie：
![image](https://github.com/yunionio/cloudpods/assets/65400797/9314304a-1d25-48ae-87a9-da22d3adffa3)

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/development/apisdk/api 可以仔细看下这个文档, 用climc --debug server-create xxxx 看下传参

**Comment by AuZn-wjx** [comment]
> 网页端
大佬你好，我根据climc --debug server-create去查看传参，基本上和api文档内一致，我看到只有<name>是必选项，但直接用
climc --debug server-create wjx_host2会报缺少disk
![image](https://github.com/yunionio/cloudpods/assets/65400797/73d3ef8b-60d8-42a4-9fc7-6eb62f92d953)
![image](https://github.com/yunionio/cloudpods/assets/65400797/67f42a48-015a-4218-ad03-081fe2ba65f7)

那我怎么知道哪些是我创建虚拟机必须要传输的参数呢？主要创建虚拟机需要传递的参数很多，但这里显示除了name其他又都是可选，还望大佬指点

**Comment by ioito** [comment]
随便传个，主要是让你看api请求的地址，header和body

**Comment by AuZn-wjx** [comment]
> climc --debug server-create

这个api请求的地址header都是由用Go的sdk程序运行得到的，根据endpoint返回的响应中的url来请求的，header的参数则是看GoSDK运行之后得到的参数来确定的具体如下：
![image](https://github.com/yunionio/cloudpods/assets/65400797/27bca2ba-245d-46f8-b2b2-4aa56b94fc1b)
目前的困难点就是body中的请求参数的问题，因为根据此方法我对server的获取云主机列表、获取详情等Get请求都是可以获取到的，我想url和header应该是没问题的
获取云主机列表的Get请求
![image](https://github.com/yunionio/cloudpods/assets/65400797/fcf1e4fd-541f-4713-a97e-c2211b6ef207)
关键问题就是如何获取创建云主机的关键信息即Body信息

**Comment by AuZn-wjx** [comment]
> 随便传个，主要是让你看api请求的地址，header和body

用climc --debug去看就是我输入了disk的内容又会说缺少啥参数
![image](https://github.com/yunionio/cloudpods/assets/65400797/c104d724-0702-46ed-8b3d-1bb14e06a886)

**Comment by AuZn-wjx** [comment]
> 随便传个，主要是让你看api请求的地址，header和body
输入以下信息：
climc --debug server-create wjx_host2 --disk 1
根据大佬指点这里是返回的api请求的地址，header和body：
![image](https://github.com/yunionio/cloudpods/assets/65400797/8113faac-7afb-4f97-acac-e7bf23279aac)
不知道怎么确定我的Body关键参数

**Comment by AuZn-wjx** [comment]
> 随便传个，主要是让你看api请求的地址，header和body

我根据大佬描述：
输入：climc --debug server-create wjx_host2 --disk 1
获取以下请求的地址，header和body的信息
![image](https://github.com/yunionio/cloudpods/assets/65400797/e93cb35e-31ec-4476-afd6-005beccca975)
并根据此信息中的curl中的信息确定关键信息：
![image](https://github.com/yunionio/cloudpods/assets/65400797/532a328b-e9dc-4ad2-9bfa-ead1e4a2f3fa)
再根据之前网页端报错获取的一些新建虚拟机时需要的具体字段值来填写body
![image](https://github.com/yunionio/cloudpods/assets/65400797/8ee05e0e-5379-461e-8e71-5ee00f96a38f)
然后在postman中请求还是报错怎么回事？
![image](https://github.com/yunionio/cloudpods/assets/65400797/cc50f044-8e8f-4aed-a2c5-6924454b4a0c)
![image](https://github.com/yunionio/cloudpods/assets/65400797/df444ec1-4102-48de-8519-f27c6d06791f)

**Comment by ioito** [comment]
我感觉你的postman json body并没有传入到后端，你先用curl 试下，如果可以，那就是你使用postman的问题

**Comment by AuZn-wjx** [comment]
以下是我用curl来请求的也是报了同样的错误
![image](https://github.com/yunionio/cloudpods/assets/65400797/600e7883-157d-4085-8f6c-c2ba6ba55cf8)
不知道是什么问题

**Comment by AuZn-wjx** [comment]
我用curl去请求也是出现同样的错误：
![image](https://github.com/yunionio/cloudpods/assets/65400797/a73e44dc-08e1-495b-a696-173658c6a170)
不知道怎么解决？

**Comment by ioito** [comment]
![image](https://github.com/yunionio/cloudpods/assets/13750250/b3388012-23ca-43f2-a601-4cd9607eee18)
这个header去掉再试

**Comment by AuZn-wjx** [comment]
我把Content-Length去掉之后可以顺利发送了！！！感谢大佬~~
![image](https://github.com/yunionio/cloudpods/assets/65400797/f89e300f-c928-43e2-bb1d-df91d6835080)
不过我还有一个疑问就是Post发送过去了有返回200ok但是在查询云主机实例的时候却找不到新创建的虚拟机是怎么回事？
![image](https://github.com/yunionio/cloudpods/assets/65400797/5ecbf99d-aa6b-4ee3-9d1a-dc000254a54e)
只能看到我之间用网页端创建的一个虚拟机

**Comment by AuZn-wjx** [comment]
> ![image](https://private-user-images.githubusercontent.com/13750250/311154871-b3388012-23ca-43f2-a601-4cd9607eee18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTE1MTYsIm5iZiI6MTcwOTg5MTIxNiwicGF0aCI6Ii8xMzc1MDI1MC8zMTExNTQ4NzEtYjMzODgwMTItMjNjYS00M2YyLWE2MDEtNGNkOTYwN2VlZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA5NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYmY3OTNkMzJjODhhOWY3Y2MyMTEzZGI3YTg4MTQ5YmMxMTkxNGEyNDcyMTcxMTY4NmU3ZGI1YjA5ZDNlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulBZczXKQJBMS3MKI2d7CfrTcbyeCj39RlBqKZLzBp8) 这个header去掉再试

大佬你好，我虽然请求成功了，但是使用GET请求去查看虚拟机找不到创建的虚拟机如下：
![image](https://github.com/yunionio/cloudpods/assets/65400797/debbb933-f747-4298-9cf5-2f2323f22cc5)
下面是我的POST请求是成功返回200了
![image](https://github.com/yunionio/cloudpods/assets/65400797/43b77b56-e42f-4de2-b4b1-84a587fe41cf)

**Comment by ioito** [comment]
成功创建后，会返回创建的虚拟机id， 查这个虚拟机的请求应该是 /servers/<id> 你的地址少写了 /<id>

**Comment by AuZn-wjx** [comment]
> 成功创建后，会返回创建的虚拟机id， 查这个虚拟机的请求应该是 /servers/<id> 你的地址少写了 /<id>
![image](https://github.com/yunionio/cloudpods/assets/65400797/a7598fba-4877-4f15-a08d-cc30db4fcfbd)
没有加id是POST请求虽然返回了200OK但是返回的参数里面没有虚拟机id，这就表示没有创建成功对么？是创建请求中还差什么重要参数对吧
这是我的Post请求Body
![image](https://github.com/yunionio/cloudpods/assets/65400797/7ebd0f5c-957c-4085-a05f-b1a7bd06b74b)

**Comment by ioito** [comment]
dry_run=false

**Comment by AuZn-wjx** [comment]
> dry_run=false

谢谢大佬ozn!!!已成功创建！！！万分感谢！！！
