### ISSUE TITLE
[求助/Help]在关联查询的时候，有panic

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19704]
![1710214269869](https://github.com/yunionio/cloudpods/assets/70850653/0c06ea24-56f0-4a1a-94b3-7977ddde163c)
![1710214269879](https://github.com/yunionio/cloudpods/assets/70850653/f8f62858-3bd7-43fb-a427-80b380edfc13)
![image](https://github.com/yunionio/cloudpods/assets/70850653/3bcb065f-9478-41a5-a5b8-4f765aae22de)

**Comment by ioito** [comment]
贴下 EcsPrice 的结构体定义

**Comment by xzzdhq** [comment]
> 贴下 EcsPrice 的结构体定义

// SEcsPriceManager ecs价格表
type SEcsPriceManager struct {
	db.SVirtualResourceBaseManager
}

var EcsPriceManager *SEcsPriceManager

func init() {
	EcsPriceManager = &SEcsPriceManager{
		SVirtualResourceBaseManager: db.NewVirtualResourceBaseManager(
			SEcsPrice{},
			"yunion_billing_price_ecs",
			"price_ecs",
			"price_ecs",
		),
	}
}

type SEcsPrice struct {
	db.SResourceBase
	//主键id，自增

	Id    string  `json:"id" gorm:"column:id"`       //这里的数据为唯一id，是一个存在一致的情况，
	Price float64 `json:"price" gorm:"column:price"` //价格

	//云平台对应的映射,这个字段可以存着
	CloutType int `json:"column:cloud_type" gorm:"column:cloud_type"`
	// 云平台，原来的表是有平台信息的， 原来的业务就按照原来的格式来 ，
	Provider string `width:"32" charset:"ascii" nullable:"false" primary:"true" list:"user" json:"provider"`
	// 计费类型, 按量、包年包月
	// example: postpaid
	BillingType string `width:"36" charset:"ascii" nullable:"true" default:"postpaid" list:"user" create:"optional" json:"billing_type"`

	//资源id
	FlavorsId string `json:"column:flavors_id" gorm:"column:flavors_id"`
}

**Comment by xzzdhq** [comment]
![image](https://github.com/yunionio/cloudpods/assets/70850653/39de02d7-b5c0-4093-b337-548085f87958)

**Comment by ioito** [comment]
到数据库中查下 show create table yunion_billing_price_ecs, 另外 json定义时不要有 "column:" 前缀

**Comment by xzzdhq** [comment]
> 到数据库中查下 show create table yunion_billing_price_ecs, 另外 json定义时不要有 "column:" 前缀

我现在把行定义和 数据库多余的列删除之后，代码可以走完查询构建，但是报错，这里的关联表定义请问该怎么配置呢
CREATE TABLE `yunion_billing_price_ecs` (
  `id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `flavors_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `billing_type` varchar(36) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT 'postpaid',
  `provider` varchar(32) NOT NULL COMMENT '云平台',
  `price` double DEFAULT NULL,
  `cloud_type` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL COMMENT '创建日期',
  `updated_at` datetime NOT NULL COMMENT '更新日期',
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime DEFAULT NULL,
  `update_version` int(11) NOT NULL DEFAULT 0,
  KEY `ix_yunion_billing_price_ecs_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ecs资源价格表'

![image](https://github.com/yunionio/cloudpods/assets/70850653/ae1aa77c-5746-44b7-9414-92d11848be87)
![image](https://github.com/yunionio/cloudpods/assets/70850653/f7b93442-c5fc-44df-b8d6-39ebd9f21fd1)

**Comment by ioito** [comment]
你可以在 ListItemFilter 方法末尾 调用 q.DebugQuery()，打印下sql语句, 然后网络上查询mysql这个报错的含义
region服务的日志级别要调为debug
kubectl edit cm -n onecloud default-region

**Comment by ioito** [comment]
改下 FetchCustomizeColumns 返回值里面加上你要返回的属性

**Comment by xzzdhq** [comment]
感谢屈轩大神，
