### ISSUE TITLE
[求助/Help]新建了一个 资源，然后调用list 方法的时候，db_dispatch.go 里面，统计文档数量报错了 ，query里面有nil

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19735]
报错bug
![image](https://github.com/yunionio/cloudpods/assets/70850653/ce1d2c78-8147-4e5f-956f-ffefe11964c0)

**Comment by ioito** [comment]
需要贴下有关你改了的任何sql查询的代码，上面的截图并没有什么有效的信息

**Comment by xzzdhq** [comment]
> 需要贴下有关你改了的任何sql查询的代码，上面的截图并没有什么有效的信息
这是开始的
![image](https://github.com/yunionio/cloudpods/assets/70850653/54031ad0-5417-4816-9289-75729bc3aebf)
然后改成返回 manager.Query() 就可以了

**Comment by ioito** [comment]
第二个参数q就是可以认为就是manager.Query()， 这里不能AppendField，只能加过滤条件
