### ISSUE TITLE
 v3.10.10版本，VPC 挂安全组，不生效[BUG]

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#19734]
**问题描述/What happened**:
虚拟机使用 vpc-ideal-sx-01 ， 在虚拟机上挂安全组， 安全组配置各种策略都不生效。
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- 
![image](https://github.com/yunionio/cloudpods/assets/35864027/5ae23225-3cc1-426c-b263-d1d50e6b1c2b)

- Kernel (e.g. `uname -a`):
-
![image](https://github.com/yunionio/cloudpods/assets/35864027/98a8bdfa-89b6-49fc-a0ae-e34e53e4e6a6)

- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
![image](https://github.com/yunionio/cloudpods/assets/35864027/cf10b155-2057-43a5-94d7-1ff18eec4065)

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
![image](https://github.com/yunionio/cloudpods/assets/35864027/3d0409a4-b5e4-4a8e-9c49-23bf289bfe29)

v3.10.10

![image](https://github.com/yunionio/cloudpods/assets/35864027/ecceb5b4-49aa-4c22-97ec-a26e0d0b1efa)

配置了限制了， 其他主机还能访问过来

**Comment by wanyaoqi** [comment]
@khw934 查看一下 vpcagent 日志是否有报错 
kubectl get pods -n onecloud -lapp=vpcagent 获取 pods
kubectl logs -n onecloud <POD_NAME>

**Comment by wanyaoqi** [comment]
可以试试重启一下 vpcagent。kubectl rollout restart deploy default-vpcagent -n onecloud

**Comment by khw934** [comment]
> 可以试试重启一下 vpcagent。kubectl rollout restart deploy default-vpcagent -n onecloud

感谢了， 重新启动后，就可以了， 一般是什么问题， 重启就好了

**Comment by khw934** [comment]
还有个问题， 我增加了一 个EIP 但是，在 EIP网关部署的机器访问过去， 经常掉线， ssh 几次才有一次成功。
![image](https://github.com/yunionio/cloudpods/assets/35864027/81fb9bcd-8e73-417b-8b59-77067c301cf0)

**Comment by swordqiu** [comment]
> 还有个问题， 我增加了一 个EIP 但是，在 EIP网关部署的机器访问过去， 经常掉线， ssh 几次才有一次成功。 ![image](https://private-user-images.githubusercontent.com/35864027/313293988-81fb9bcd-8e73-417b-8b59-77067c301cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2MTMsIm5iZiI6MTcxMDU1NDMxMywicGF0aCI6Ii8zNTg2NDAyNy8zMTMyOTM5ODgtODFmYjliY2QtOGU3My00MTdiLThiNTktNzcwNjdjMzAxY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAxNTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzRlZDQ3OTRhMWYzZmUyM2QzZDY3MDBkYWQ1OTdjZTk1NGI4OTVjMGJhYjk3OWViZTU0MmQ4N2ZjNTkwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcn-ruHKtvEFN4ScM0XyxII3GajQxmy3JFGDxOGHb90)

@khw934  AllInOne部署的时候，会默认打开该节点的EIP网关选项。感觉像是你新增的EIP网关和默认开启的EIP网关冲突了。可以采用如下方式将默认开启的EIP网关下线：
* 修改 /etc/yunion/host.conf, 设置 sdn_enable_eip_man: false (如果已经是false，则不是这个情况，请另找原因），并重启该节点的host服务
* 在该节点运行如下脚本清理eip网关生成的bridge和端口：
```
ovs-vsctl del-br breip
ovs-vsctl list-ports brvpc | grep ^ev- | awk '{print "ovs-vsctl del-port brvpc " $1}' | sh
```

**Comment by khw934** [comment]
> > 还有个问题， 我增加了一 个EIP 但是，在 EIP网关部署的机器访问过去， 经常掉线， ssh 几次才有一次成功。 ![image](https://private-user-images.githubusercontent.com/35864027/313293988-81fb9bcd-8e73-417b-8b59-77067c301cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2MTMsIm5iZiI6MTcxMDU1NDMxMywicGF0aCI6Ii8zNTg2NDAyNy8zMTMyOTM5ODgtODFmYjliY2QtOGU3My00MTdiLThiNTktNzcwNjdjMzAxY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAxNTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzRlZDQ3OTRhMWYzZmUyM2QzZDY3MDBkYWQ1OTdjZTk1NGI4OTVjMGJhYjk3OWViZTU0MmQ4N2ZjNTkwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcn-ruHKtvEFN4ScM0XyxII3GajQxmy3JFGDxOGHb90)
> 
> @khw934 AllInOne部署的时候，会默认打开该节点的EIP网关选项。感觉像是你新增的EIP网关和默认开启的EIP网关冲突了。可以采用如下方式将默认开启的EIP网关下线：
> 
> * 修改AllInOne部署节点的 /etc/yunion/host.conf, 设置 sdn_enable_eip_man: false (如果已经是false，则不是这个情况，请另找原因），并重启该节点的host服务
> * 在该节点运行如下脚本清理eip网关生成的bridge和端口：
> 
> ```
> ovs-vsctl del-br breip
> ovs-vsctl list-ports brvpc | grep ^ev- | awk '{print "ovs-vsctl del-port brvpc " $1}' | sh
> ```

我自己没有再开一个EIP 网关， 用就是部署节点的EIP 网关

**Comment by swordqiu** [comment]
> > > 还有个问题， 我增加了一 个EIP 但是，在 EIP网关部署的机器访问过去， 经常掉线， ssh 几次才有一次成功。 ![image](https://private-user-images.githubusercontent.com/35864027/313293988-81fb9bcd-8e73-417b-8b59-77067c301cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2MTMsIm5iZiI6MTcxMDU1NDMxMywicGF0aCI6Ii8zNTg2NDAyNy8zMTMyOTM5ODgtODFmYjliY2QtOGU3My00MTdiLThiNTktNzcwNjdjMzAxY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAxNTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzRlZDQ3OTRhMWYzZmUyM2QzZDY3MDBkYWQ1OTdjZTk1NGI4OTVjMGJhYjk3OWViZTU0MmQ4N2ZjNTkwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcn-ruHKtvEFN4ScM0XyxII3GajQxmy3JFGDxOGHb90)
> > 
> > 
> > @khw934 AllInOne部署的时候，会默认打开该节点的EIP网关选项。感觉像是你新增的EIP网关和默认开启的EIP网关冲突了。可以采用如下方式将默认开启的EIP网关下线：
> > 
> > * 修改AllInOne部署节点的 /etc/yunion/host.conf, 设置 sdn_enable_eip_man: false (如果已经是false，则不是这个情况，请另找原因），并重启该节点的host服务
> > * 在该节点运行如下脚本清理eip网关生成的bridge和端口：
> > 
> > ```
> > ovs-vsctl del-br breip
> > ovs-vsctl list-ports brvpc | grep ^ev- | awk '{print "ovs-vsctl del-port brvpc " $1}' | sh
> > ```
> 
> 我自己没有再开一个EIP 网关， 用就是部署节点的EIP 网关

可以检查一下其他节点的 /etc/yunion/host.conf 的 sdn_enable_eip_man，如果有为 true 则需要按上述方法下线

**Comment by khw934** [comment]
> > > > 还有个问题， 我增加了一 个EIP 但是，在 EIP网关部署的机器访问过去， 经常掉线， ssh 几次才有一次成功。 ![image](https://private-user-images.githubusercontent.com/35864027/313293988-81fb9bcd-8e73-417b-8b59-77067c301cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2MTMsIm5iZiI6MTcxMDU1NDMxMywicGF0aCI6Ii8zNTg2NDAyNy8zMTMyOTM5ODgtODFmYjliY2QtOGU3My00MTdiLThiNTktNzcwNjdjMzAxY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDAxNTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzRlZDQ3OTRhMWYzZmUyM2QzZDY3MDBkYWQ1OTdjZTk1NGI4OTVjMGJhYjk3OWViZTU0MmQ4N2ZjNTkwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcn-ruHKtvEFN4ScM0XyxII3GajQxmy3JFGDxOGHb90)
> > > 
> > > 
> > > @khw934 AllInOne部署的时候，会默认打开该节点的EIP网关选项。感觉像是你新增的EIP网关和默认开启的EIP网关冲突了。可以采用如下方式将默认开启的EIP网关下线：
> > > 
> > > * 修改AllInOne部署节点的 /etc/yunion/host.conf, 设置 sdn_enable_eip_man: false (如果已经是false，则不是这个情况，请另找原因），并重启该节点的host服务
> > > * 在该节点运行如下脚本清理eip网关生成的bridge和端口：
> > > 
> > > ```
> > > ovs-vsctl del-br breip
> > > ovs-vsctl list-ports brvpc | grep ^ev- | awk '{print "ovs-vsctl del-port brvpc " $1}' | sh
> > > ```
> > 
> > 
> > 我自己没有再开一个EIP 网关， 用就是部署节点的EIP 网关
> 
> 可以检查一下其他节点的 /etc/yunion/host.conf 的 sdn_enable_eip_man，如果有为 true 则需要按上述方法下线

我检查了都没有配置

**Comment by swordqiu** [comment]
至少有一台配置了吧？

**Comment by khw934** [comment]
> 至少有一台配置了吧？
只有一台部署节点 ， 192.168.1.150 开了EIP 网关

**Comment by khw934** [comment]
非常感谢，问题已经解决
