### ISSUE TITLE
[求助/Help]关于baremetal-agent在多可用区部署的问题

### ISSUE THREAD

**Issue by Guojing20210406** [yunionio/cloudpods#19745]
参考问题 #18556。目前的情况在这里回复了，我这里在复述一下。
我现在在多个可用区部署baremetal-agent。由于我此前已经部署了一个，现在部署第二个的时候，第二个baremetal-agent仍然会找到第一个node运行（我看日志上ip发现的）。我想知道实际操作多可用区baremetal-agent应该怎么做？

**Comment by zexi** [comment]
@Guojing20210406  https://www.cloudpods.org/docs/operations/multi-zone-config
这里有文档可以参考。

**Comment by Guojing20210406** [comment]
我就是参考这个文档做的。但是修改完onecloudcluster之后。确实有2个baremetal-agent起来了，但是他们是冲突的，他们zone是一样的，所以就会冲突了。

**Comment by zexi** [comment]
> https://www.cloudpods.org/docs/operations/multi-zone-config

@Guojing20210406 执行 `climc agent-list` 看下，另外可以看下另外一个 baremetal-agent 对应的 configmap 里面设置的 zone 是什么

**Comment by Guojing20210406** [comment]
他们configmap的zone都是一样，是第一个zoneid。意思直接修改configmap的zone就可以？

**Comment by Guojing20210406** [comment]
好的，我试试
