### ISSUE TITLE
[BUG] 虚拟机关机，获取ak/sk的 代码处，ak/sk没有接受

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#19742]
**问题描述/What happened**:
可以看见，ret没有被接收，
![image](https://github.com/yunionio/cloudpods/assets/70850653/c26b8b2f-338a-4294-86e3-c02ec624a0bc)
![image](https://github.com/yunionio/cloudpods/assets/70850653/bf624ec2-884f-4233-a9ab-8b6a31f643b0)

**环境/Environment**:
v3.0.10
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by xzzdhq** [comment]
但是看 SGuest 的方法名为 Validate，那是不是在后面关机的方法中还会去获取ak/sk呢

**Comment by ioito** [comment]
这是校验虚拟机加密信息是否存在，有没有使用秘钥并没有影响

**Comment by xzzdhq** [comment]
ok，感谢
