### ISSUE TITLE
[求助/Help] host服务增加存储盘问题

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#19758]
cloudpods  3.10.8
os: centos 7.9

创建本地idc虚拟机报错
deploying=>deploy_fail: {"__reason__":"Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = Connect: failed start guest qemu-kvm: -drive file=/home/kvmtmp/cloudpods/block-storage/cdb98e18-e43d-41e9-8d8a-073b0db635e6,if=none,id=drive_0,cache=none: Could not open '/home/kvmtmp/cloudpods/block-storage/cdb98e18-e43d-41e9-8d8a-073b0db635e6': No such file or directory\n: exit status 1","__stage__":"OnDeployGuestComplete","__status__":"error"}

报错完成之后  点击虚拟机状态同步 ->状态变成已关机->点击开机可以正常开机。但是流程串不起来，host.conf 的配置如下
![image](https://github.com/yunionio/cloudpods/assets/54271145/5c4ffef9-1fc8-4255-b4ca-873ed19c3361)

因为 /home/kvmtmp/cloudpods/block-storage 这个挂载点 挂在了大硬盘， -/opt/cloud/workspace/disks所处的文件系统比较小
请问这个问题有上面解决方案吗？
我尝试了再host demoset 添加了如下配置 。还是不行
![Uploading image.png…]()

**Comment by huhaiqwer** [comment]
![Uploading image.png…]()

**Comment by huhaiqwer** [comment]
图片上传不去 daemonset 挂在如下
    - mountPath: /home/kvmtmp/cloudpods/block-storage
      mountPropagation: Bidirectional
      name: kvmtmp

     - hostPath:
         path: /home/kvmtmp/cloudpods/block-storage
         type: Directory
       name: kvmtmp

**Comment by huhaiqwer** [comment]
对应的目录 存在 对应的文件
![image](https://github.com/yunionio/cloudpods/assets/54271145/f1b479cf-e68f-4299-9d71-87a2b9906a0c)

**Comment by huhaiqwer** [comment]
确定目录已经挂载到了host服务的docker里面 
![image](https://github.com/yunionio/cloudpods/assets/54271145/951b1a8b-d0ca-4493-afc6-4015b6477421)

**Comment by zexi** [comment]
@huhaiqwer 请按照这个文档添加存储 https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage#%E6%B7%BB%E5%8A%A0%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8 ，要求是一定要把本地存储挂载到放在 /opt/cloud/workspace 目录下面的子目录，如果是其他路径，可以用 bind mount 的方式挂到 opt 下面

**Comment by huhaiqwer** [comment]
> @huhaiqwer 请按照这个文档添加存储 https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage#%E6%B7%BB%E5%8A%A0%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8 ，要求是一定要把本地存储挂载到放在 /opt/cloud/workspace 目录下面的子目录，如果是其他路径，可以用 bind mount 的方式挂到 opt 下面
@zexi 请问李老师 我把 /home/kvmtmp/cloudpods/block-storage 挂到host服务里面了，为什么不行，按照常理来说，应该可以正常访问/home/kvmtmp/cloudpods/block-storage了呀。能麻烦解释一下吗

**Comment by huhaiqwer** [comment]
> @huhaiqwer 请按照这个文档添加存储 https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage#%E6%B7%BB%E5%8A%A0%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8 ，要求是一定要把本地存储挂载到放在 /opt/cloud/workspace 目录下面的子目录，如果是其他路径，可以用 bind mount 的方式挂到 opt 下面
@zexi 请问李老师 我把 /home/kvmtmp/cloudpods/block-storage 挂到host服务里面了，为什么不行，按照常理来说，应该可以正常访问/home/kvmtmp/cloudpods/block-storage了呀。能麻烦解释一下吗

**Comment by zexi** [comment]
> > @huhaiqwer 请按照这个文档添加存储 https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage#%E6%B7%BB%E5%8A%A0%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8 ，要求是一定要把本地存储挂载到放在 /opt/cloud/workspace 目录下面的子目录，如果是其他路径，可以用 bind mount 的方式挂到 opt 下面
> 
> @zexi 请问李老师 我把 /home/kvmtmp/cloudpods/block-storage 挂到host服务里面了，为什么不行，按照常理来说，应该可以正常访问/home/kvmtmp/cloudpods/block-storage了呀。能麻烦解释一下吗

@huhaiqwer 这个原因是 host pod 作为 daemonset 运行在 k8s 里面，默认的 volumeMount 只挂了 /opt 进去，如果把 /home/kvmtmp 挂给 host 容器，应该也可以，不过这样不太通用，所以我们这边默认设计要求使用 /opt 目录，如果是其他目录，也可以 mount --bind 映射到  /opt 目录下
