### ISSUE TITLE
[求助/Help]禁用宿主机之后无法重启虚拟机的逻辑修改建议

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#19757]
平台版本：v3.11.2

![b1decd40-0ef4-4079-9eaa-b24bffa465a9](https://github.com/yunionio/cloudpods/assets/1650540/952020cb-1727-4a46-8d64-62ac35abdb24)

```
{
  "class": "InvalidStatusError",
  "code": 400,
  "details": "宿主机状态为online，启用状态为%!s(bool=false)，无法对虚机执行start操作",
  "time": "2024-03-21T10:54:32+08:00"
}
```

我们的场景是发现资源超卖之后，禁止自动分配新机器，所以设置了禁用。
这样会导致虚拟机无法重启。
按这个逻辑，如果宿主机宕机重启的话，虚拟机也无法被自动拉起？可能会导致不符合预期的故障。

宿主禁用是否可以改成只对新资源分配做限制，例如扩容、升配、新建，而不对启停做限制？

**Comment by wanyaoqi** [comment]
@fangpsh 你的需求应该使用调度标签来实现，可以给宿主机关联到禁止调度的策略上

**Comment by fangpsh** [comment]
> 如果宿主机宕机重启的话，虚拟机也无法被自动拉起

 明白。目前这个设计，如果禁用了的宿主机，意外重启的话，之前在这个宿主上运行的虚拟机也是无法被自动拉起的吧？

**Comment by wanyaoqi** [comment]
> > 如果宿主机宕机重启的话，虚拟机也无法被自动拉起
> 
> 明白。请教下，目前这个设计，如果禁用了的宿主机，意外重启的话，之前在这个宿主上运行的虚拟机（配置了自动重启）也是无法被自动拉起的吧？

@fangpsh 意外重启会自动拉起
