### ISSUE TITLE
[BUG] Keep restarting during the ocboot installation

### ISSUE THREAD

**Issue by cnjack** [yunionio/cloudpods#19783]
**问题描述/What happened**:
在使用ocboot run.py的时候一直重启
![image](https://github.com/yunionio/cloudpods/assets/2562093/f9d97985-cd40-45da-bbf7-43b355a4d19c)

感觉和这个有关 https://github.com/yunionio/ocboot/blob/master/onecloud/roles/utils/kernel-check/tasks/unified_cgroup_hierarchy.yml

![image](https://github.com/yunionio/cloudpods/assets/2562093/9d8cb00c-3bd6-40a1-8703-2b653597a775)
![image](https://github.com/yunionio/cloudpods/assets/2562093/98aa61a6-394d-460e-8ea0-04177bf17273)

另外我也遇到这个问题 https://github.com/yunionio/cloudpods/issues/19700

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-101-generic
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`): 3.11

**Comment by zhasm** [comment]
收到，定位中。

**Comment by cnjack** [comment]
有我可以帮忙的吗?

**Comment by zhasm** [comment]
@cnjack 

我这里没能重现您的问题，安装过程，只重启一次，来更新grub配置，然后再次安装，就一键到底了。

**Comment by zhasm** [comment]
如有问题，请重新打开本issue，继续留言。或新开主题。
