### ISSUE TITLE
[求助/Help] java sdk 是否支持aksk方式的认证？api v3认证接口，认证方式为aksk时，入参的access_key_secret该怎么填呢？

### ISSUE THREAD

**Issue by caojingwen17** [yunionio/cloudpods#19793]
java sdk是不是只支持用户名密码方式认证？目前只看到这种认证方式

<img width="770" alt="微信图片_20240326101348" src="https://github.com/yunionio/cloudpods/assets/50550304/51fd389d-3f27-4e52-8ce1-06455eb7a979">

这里编码后的字符串该如何填写

**Comment by ioito** [comment]
是的，目前java只支持用户名密码认证，如果有能力可以提交pr支持下aksk认证，参考实现: https://github.com/yunionio/mcclient_python/blob/8436ac9835a22145dd3a3931089dbae1f079ae82/yunionclient/api/client.py#L918

**Comment by caojingwen17** [comment]
那么再请教一下，api的v3认证接口，aksk方式认证时，access_key_secret这个该怎么填？

**Comment by caojingwen17** [comment]
那么再请教一下，api的v3认证接口，aksk方式认证时，access_key_secret这个参数该怎么填？

**Comment by ioito** [comment]
curl -k -X 'POST' -d '{"auth":{"context":{"source":"cli"},"identity":{"access_key_secret":"{\"access_key\":\"355270364e0a46eb84429e5ffa043842\",\"algorithm\":\"AWS4-HMAC-SHA256\",\"location\":\"cn-beijing\",\"request\":\"AWS4-HMAC-SHA256\\n20240326T103944Z\\n20240326/cn-beijing/s3/aws4_request\\n81ca05d0e6f088a349d268ad81f5d43e0dcc82558c3a0f33507d46adbc1f1429\",\"sign_date\":\"2024-03-26T10:39:44.000000Z\",\"signature\":\"2534884f0726c54f01e805e3a5a40ec97331deb481b03ae6bb5ef77a5b9a60c2\",\"signed_headers\":[\"date\",\"host\",\"x-amz-content-sha256\",\"x-amz-date\"]}","methods":["aksk"]}}}' -H 'Accept: */*' -H 'Accept-Encoding: *' -H 'Content-Length: 573' -H 'Content-Type: application/json' -H 'User-Agent: yunioncloud-go/201708' 'https://example.com:5000/v3/auth/tokens'
这是一个curl举例，需要用到时间，header等参数进行签名编码

**Comment by caojingwen17** [comment]
大佬你好！现在就是不太清楚如何进行编码TAT

**Comment by ioito** [comment]
https://github.com/yunionio/mcclient_python/blob/8436ac9835a22145dd3a3931089dbae1f079ae82/yunionclient/api/client.py#L822 就是的python编码实现

**Comment by caojingwen17** [comment]
看了一下好复杂，如果要用api的aksk方式认证好艰难。TAT

**Comment by ioito** [comment]
https://help.aliyun.com/zh/sdk/product-overview/rpc-mechanism?spm=a2c4g.11186623.0.0.3da5fd04gC3PCm 公有云签名都类似，你能看懂这种文档就能自己实现签名认证
