### ISSUE TITLE
[求助/Help] cloudpods权限配置相关的问题，配置的资源权限在权限详情页无法展示?

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19790]
在权限配置页面分为资源权限和其他权限两类，然后看域管理员权限列表当中(查看详情)，没有发现资源权限的权限配置呢?请问是为什么?
我理解的资源权限的resource是servers，应该是在计算节点?但是为什么计算节点没有展示呢?请问将权限分为资源权限和其他权限的目的是什么呢?
![image](https://github.com/yunionio/cloudpods/assets/19704134/cfd44bfa-e7f7-46e0-a9e1-7ebf87fd556c)

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/6277
