### ISSUE TITLE
[BUG] 权限这块发现一个交互上的bug

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19792]
**问题描述/What happened**:
权限编辑页面，当权限的yaml配置为
policy:
  '*':
    '*':
      '*': allow
的时候
可视化视图下的计算节点的权限却不是全选，但是展开却都是选上了的，还是因为有一些隐藏的权限。
![image](https://github.com/yunionio/cloudpods/assets/19704134/2bbbc9ff-7d73-4d98-a5b3-f77bc8da3be8)

**环境/Environment**:
线上saas环境

**Comment by easy-mj** [comment]
https://github.com/yunionio/dashboard/pull/6278
