### ISSUE TITLE
[BUG] 裸金属重装系统会选错盘

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#19823]
**问题描述/What happened**:

当有多快磁盘的时候，直接重装系统，会出现不确定装到哪块盘的情况。

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ChaoHsin-fang** [comment]
请教一下重装的时候是怎么确保装的系统磁盘呢，而不是数据盘

**Comment by zexi** [comment]
@ChaoHsin-fang 现在命令行可以用这个方式选盘
https://github.com/yunionio/cloudpods/pull/20470
