### ISSUE TITLE
[求助/Help]请问ceph块存储可以做系统盘吗？

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#19825]
创建虚拟机选择ceph集群的块存储磁盘作为系统盘，然后一直状态处于缓存景象中，
请问ceph块存储可以做系统盘吗？

**Comment by wanyaoqi** [comment]
@vincentiss 可以，第一次缓存镜像可能有点慢，需要从glance 上传镜像到 ceph

**Comment by vincentiss** [comment]
果然 谢了
