### ISSUE TITLE
[文档/Docs] 权限使用过程中有一些问题，没有在文档上找到，想要请问一下权限的共享范围问题

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#19829]
**What part of the document needs to be added**:
权限的共享范围测试发下只有全局共享和私有这两种场景，经过测试，共享范围字段是通过policy表中的is_public和public_scope定义的，当is_public为0的时候,权限为私有，当is_public为0并且public_scope为domain的时候为本域共享(这个本域共享实际是没有测试出来，通过改数据库改出来的)，想请教一下私有和本域共享的含义是什么?当public_scope为system并且is_public为0的时候的(系统)私有和public_scope为domain并且is_public为0(域私有)这两个私有有什么区别么?谢谢

**Comment by qian788** [comment]
这个在项目视图看会比较明显，私有：只有选择的项目可以使用，本域共享：该域下所有项目都可以使用。
比如：安全组是私有，且项目选择的a，那么在项目视图下，只有a项目可以选择这个安全组。如果是本域共享，那么其他项目是都可以选择它的。

**Comment by ilovedumplings** [comment]
> 如果是本域共享

原来是这个意思啊..我去尝试下,谢谢

**Comment by ilovedumplings** [comment]
> 只有选择的项目可以使用

那再权限视图下，我测试出来只有私有(自己创建)和全局共享(系统创建)这两个权限，按照私有为选择的项目可以使用的话，那和实际使用是有出入的，因为私有的权限是不是那只能项目看到，但是cloudpods默认的项目权限是不具备认证体系菜单的，这样是不是有点歧义了呢?我不知道描述的对不对。

换种描述方式：

手动创建的权限为私有，但是私有只能项目使用，但是权限是域级别的资源，可不可以理解成私有就是域内部使用呢?那本域共享和私有在权限这块逻辑下就是一样的??

**Comment by qian788** [comment]
开源版本是只有私有和全局共享的。
我们本身是分项目级别（子网）和域级别（vpc）的，2种都是可以手动创建。项目级别的本域共享（开源叫全局共享）和域级别的私有（开源应该不显示共享范围）的使用范围是一样的。这样说会好理解些吗？
