### ISSUE TITLE
[求助/Help]ceph磁盘做系统盘，启动显示 No bootable device

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#19843]
你好。

我用ceph磁盘做位系统盘创建虚拟机
虚拟机显示创建成功了 运行中，
但无法获得密钥
远程控制看，启动没有找到设备，
镜像缓存里有一条缓存失败。

这是因为缓存景象失败的原因吗？谢谢
<img width="715" alt="1" src="https://github.com/yunionio/cloudpods/assets/4445479/03cdbebc-a931-48fa-b02d-8c649a8a69cf">

**Comment by wanyaoqi** [comment]
@vincentiss 这个镜像是BIOS引导的还是 UEFI引导的？如果是缓存失败应该会报错创建失败。
你也可以用本地存储验证一下这个镜像

**Comment by vincentiss** [comment]
> @vincentiss 这个镜像是BIOS引导的还是 UEFI引导的？如果是缓存失败应该会报错创建失败。 你也可以用本地存储验证一下这个镜像

谢谢

镜像本地创建没问题。

怎么看是bios或uefi引导啊？
我又重新建了一个虚拟机使用了另外一个镜像，比较慢，需要等等结果。

**Comment by wanyaoqi** [comment]
@vincentiss BIOS还是UEFI引导是镜像的属性，在虚机修改属性那里可以设置

如果本地盘创建没问题，那可能确实是镜像缓存有问题

**Comment by vincentiss** [comment]
请问存在这个表里的数据会有什么定时任务清理吗？
