### ISSUE TITLE
[求助/Help]Ceph做系统盘，找不到启动盘

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#19871]
<img width="1155" alt="image" src="https://github.com/yunionio/cloudpods/assets/4445479/ab23b13f-807f-4ef0-b330-8d3b8ca9a91e">

镜像没有问题，本地磁盘可以创建虚拟机并正常运行。

请问用ceph做系统盘创建虚拟机还有什么需要设置的吗？这个问题怎么排查？谢谢

**Comment by wanyaoqi** [comment]
@vincentiss 看起来还是没有识别到启动盘。你能否使用 rbd 命令把系统盘map到宿主机上，挂载起来确认一下这个盘是否包含操作系统。
如何使用rbd map 可以参考 https://docs.ceph.com/en/quincy/man/8/rbdmap/ 。或者搜索一下

**Comment by vincentiss** [comment]
> rbd map

我映射完，尝试mount的时候报错了。
mount: /mnt/rbddev0: wrong fs type, bad option, bad superblock on /dev/rbd0, missing codepage or helper program, or other error.

**Comment by vincentiss** [comment]
> 我映射完，尝试mount的时候报错了。
> mount: /mnt/rbddev0: wrong fs type, bad option, bad superblock on /dev/rbd0, missing codepage or helper program, or other error.



> @vincentiss 看起来还是没有识别到启动盘。你能否使用 rbd 命令把系统盘map到宿主机上，挂载起来确认一下这个盘是否包含操作系统。 如何使用rbd map 可以参考 https://docs.ceph.com/en/quincy/man/8/rbdmap/ 。或者搜索一下

我映射完，尝试mount的时候报错了。
mount: /mnt/rbddev0: wrong fs type, bad option, bad superblock on /dev/rbd0, missing codepage or helper program, or other error.

**Comment by vincentiss** [comment]
> @vincentiss 看起来还是没有识别到启动盘。你能否使用 rbd 命令把系统盘map到宿主机上，挂载起来确认一下这个盘是否包含操作系统。 如何使用rbd map 可以参考 https://docs.ceph.com/en/quincy/man/8/rbdmap/ 。或者搜索一下

我映射完，尝试mount的时候报错了。
mount: /mnt/rbddev0: wrong fs type, bad option, bad superblock on /dev/rbd0, missing codepage or helper program, or other error.

**Comment by wanyaoqi** [comment]
@vincentiss 如果没有文件系统和操作系统的话，那这个镜像缓存的是有问题的。
尝试吧镜像缓存删了，重新缓存一下

**Comment by vincentiss** [comment]
@wanyaoqi

**Comment by wanyaoqi** [comment]
@vincentiss 
<img width="1368" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/f1fc699f-3cc0-473a-860d-91f044c67b52">
块存储下面的镜像缓存，要释放的话先删除虚机。

**Comment by vincentiss** [comment]
哦 怪不得 我的这里都是0b， 我重试下 谢谢。
