### ISSUE TITLE
[求助/Help]如何将新增的菜单（模块）加入到权限管理中？

### ISSUE THREAD

**Issue by lanzhiming** [yunionio/cloudpods#19878]
主要问题：后端新增了一个菜单（门户管理模块），需要将此模块加入到权限管理中，如何添加？
问题诉求：
1.后端部分：后端新建了一个notice模块，需要怎么约定权限标识？是否需要插入数据库？
2.前端部分：前端除了在containers下新增一个Portal文件夹，还需要申明哪些文件？或者还需要在哪些文件中进行注册？如何与后端打通权限分配的功能？
期望的效果：
![image](https://github.com/yunionio/cloudpods/assets/10107052/5b0521e2-67d0-4f57-a877-c3fb075b14fc)

目前前端的定义如下：
containers/Portal/router/index.js
`
export default {
  index: 100,
  meta: {
    label: '门户管理',
    icon: 'menu-portal',
  },
  menus: [
    {
      meta: {
        label: '门户管理',
      },
      submenus: [
        {
          path: '/bidding-mng',
          meta: {
            label: '公告配置',
            permission: 'bidding-mng_list',
          },
          component: Layout,
          children: [
            {
              name: 'Portal',
              path: '',
              meta: {},
              component: Portal,
            },
            {
              name: 'PortalCreateOrUpdate',
              path: 'createOrUpdate',
              meta: {},
              component: PortalCreateOrUpdate,
            },
          ],
        },
      ],
    },
  ],
}
`
 感谢大佬们拨冗查看，是否有以上问题的整体操作手册？或者参考文档？麻烦提供一下，再次感谢！

**Comment by GuoLiBin6** [comment]
后端新增服务或api，前端对接权限步骤：
1. 增加定义：前端代码中，src/constants/permission.js 中包含所有权限定义，可在此文件中增加，格式为 权限名称:[服务名，资源名，操作]
2. 增加翻译：前端代码中，containers/IAM/views/policy/constants.js，定义了权限服务和各个资源的翻译映射，可在此处增加翻译
3. 使用：在对应路由或操作中使用，格式为 permission: 权限名称

**Comment by lanzhiming** [comment]
thanks
