### ISSUE TITLE
[求助/Help] KVM 虚拟机导入cloudpods失败

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#19870]
我有一台虚拟机，系统为windows 2008SP2,镜像大小为40G，是从libvirt创建虚拟机，因为是跨机房没有办法使用climc servers-import-from-libvirt 来进行导入，想直接拷贝系统镜像方式来进行迁移，镜像格式为QCOW2，然后通过镜像导入的方式导入到cloudpods里面 climc image-upload --format qcow2 --os-type Windows --os-arch x86_64 --standard  xx.qcow2, 系统镜像也导入成功，但启动的时候启不来，启动的时候直接进入了系统恢复模式，我发现它根本没有识别到原先系统，不知道是什么问题引起的？
![1712107097930](https://github.com/yunionio/cloudpods/assets/4537805/ce0cce5a-172e-4fe6-acc7-cc9ed43119e6)
![1712107180084](https://github.com/yunionio/cloudpods/assets/4537805/23603c63-869b-46d8-883d-a95c7d20970f)

**Comment by wanyaoqi** [comment]
@xxhacker 这种可能是原虚机内安装的驱动在新的宿主机上，新的qemu模拟的硬件配置不适用。
<img width="553" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/d50d8607-d180-419a-8204-e865d98c7340">

**Comment by xxhacker** [comment]
> @xxhacker 这种可能是原虚机内安装的驱动在新的宿主机上，新的qemu模拟的硬件配置不适用。 <img alt="image" width="553" src="https://private-user-images.githubusercontent.com/18528551/319014673-d50d8607-d180-419a-8204-e865d98c7340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTIyNDEsIm5iZiI6MTcxMjExMTk0MSwicGF0aCI6Ii8xODUyODU1MS8zMTkwMTQ2NzMtZDUwZDg2MDctZDE4MC00MTlhLTgyMDQtZTg2NWQ5OGM3MzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMzkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNmE0MGQ2NzU4ZjAxMjFjNzcxNWI2NmE0MWJjNWRmMTM2OWM4ZDdkMmM0M2Q5OGYxMWQ3MmY3YmU1OGJiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rfjh94EqS4gzX6U3tLxehx6a3VDyCMuYHVJrA9vKJNU">

那像这种情况不知道怎么解决

**Comment by wanyaoqi** [comment]
@xxhacker 这种就是对比一下源端和目的端起虚机的参数有什么不一样，这个会影响到硬件模拟。然后尝试调整目的端虚机参数。
cloudpods通常能够调整的有磁盘网卡驱动，vdi，vnc等这些，也可以看下 `climc server-set-qemu-params` 可以调整的参数

**Comment by xxhacker** [comment]
> climc server-set-qemu-params

非常感谢，我调整了磁盘的驱动问题解决了，还有一个问题我咨询一下，就是我这个系统之前有一个1T的数据盘，格式也是QCOW2的，我用文档中的 climc guest-image-create <name> --image xx.qcow2 --image xx.img ，结果报错了，这两个文件都是当下的目录中
![1712114662759](https://github.com/yunionio/cloudpods/assets/4537805/7b3378dd-f46f-4d77-a88b-5d5a220f2745)
我问一下，两个文件是不是都要上传到镜像文件后才能合并，不能本地直接合并？

**Comment by wanyaoqi** [comment]
@xxhacker  https://www.cloudpods.org/docs/guides/onpremise/glance/guestimage/create 参考一下这个，这两个文件需要分别上传到 glance，然后再组合成主机镜像

**Comment by xxhacker** [comment]
@wanyaoqi  明白，不好意思，系统起来后认不到网卡，提示网卡驱动有问题，我看以前libvirt的网卡信息如下：

**Comment by wanyaoqi** [comment]
@xxhacker 建议网卡使用virtio驱动，你先给你的windows打上virtio驱动

**Comment by xxhacker** [comment]
@wanyaoqi 已经解决了，安装了virtio驱动，太感谢了！
