### ISSUE TITLE
[求助/Help]Ceph做系统盘 缓存镜像总是0b 

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#19887]
请问，

ceph做系统盘，缓存镜像的时候总是0b，创建的虚拟机也找不到启动盘

请问我该如何查找这个问题啊？谢谢

**Comment by wanyaoqi** [comment]
@vincentiss 你看下host日志缓存镜像是否有报错。如果没有报错你手动上传一下镜像到ceph看能否成功。
镜像缓存到ceph是通过 qemu-img convert 做的，具体可以看
https://github.com/yunionio/cloudpods/blob/b7df3d6af09e8964178238f1f066c99166f288cc/pkg/hostman/storageman/imagecache_rbd.go#L87-L88

**Comment by vincentiss** [comment]
> @vincentiss 你看下host日志缓存镜像是否有报错。如果没有报错你手动上传一下镜像到ceph看能否成功。 镜像缓存到ceph是通过 qemu-img convert 做的，具体可以看：
> 
> https://github.com/yunionio/cloudpods/blob/b7df3d6af09e8964178238f1f066c99166f288cc/pkg/hostman/storageman/imagecache_rbd.go#L87-L88
> 
> 
> 你也可以打开host debug日志，重新缓存镜像，找到日志中的缓存镜像命令，然后手动执行 qemu-img convert命令

好的谢谢。我去试试。
我现在发现local 存储的镜像缓存也都是0b ， 这种是不是都没缓存成功，创建虚拟机的时候这种情况是不是应该报错创建不成功呢？

**Comment by wanyaoqi** [comment]
@vincentiss 0b看起来是本地盘的缓存就有问题了，或者是你的这个镜像有问题？

**Comment by vincentiss** [comment]
应该是网络问题，同机房的很快

**Comment by wanyaoqi** [comment]
@vincentiss 这里的缓存大小应该就是镜像的 size，插入 cachedimages 时就会同时保存镜像的信息
