### ISSUE TITLE
[求助/Help] 上传大容量镜像失败

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#19883]
我有一个大概1.2T的镜像文件要上传，每次都上传到750G的时候都提示失败，已经好多次了，如果下图所示：
<img width="893" alt="Snipaste_2024-04-04_18-25-35" src="https://github.com/yunionio/cloudpods/assets/4537805/b0bb109c-9b9a-43ce-b0ad-e93af16aba4d">
![Quicker_20240404_182647](https://github.com/yunionio/cloudpods/assets/4537805/af2d31b3-81bf-41b3-80cb-242623d48463)
我查看了glance所在的机器根分区大小为1.6T，我又查看了glance组件，查看配置文件 /etc/yunion/glance.conf好像也没有什么挂载大小或者容量的限制，但是看到s3fs挂载的时候只有256G不知道跟这个有没有关系，如果有关系的话怎么调大它
<img width="760" alt="Snipaste_2024-04-04_18-29-31" src="https://github.com/yunionio/cloudpods/assets/4537805/c653c50a-813f-4883-9fd9-dea9f78a3c3e">

**Comment by ioito** [comment]
same as #13425, 如果改nginx超时时间依然不行，那就只能用climc上传，这个不会经过nginx，一般不会失败

**Comment by xxhacker** [comment]
@ioito 我这个本来就是不通过网页方式传的，是直接执行命令climc image-upload方式上传的

**Comment by ioito** [comment]
哦，目前框架内超时时间最长是2小时，如果要上传这么大的镜像，需要改如下代码，https://github.com/yunionio/cloudpods/pull/19888

**Comment by xxhacker** [comment]
@ioito 我看日志是到2个小时时候中断了，如果我修改的话，怎么改了，我用的版本是3.10.4

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/19888 按这个改，然后重新打glance镜像，替换自己的环境

**Comment by xxhacker** [comment]
@ioito 有文档可以参考不

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/development/dev-env#docker-%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91%E4%B8%8A%E4%BC%A0

**Comment by ioito** [comment]
你的环境有没有开selinux权限之类的东西，这个报错是指你当前的这个root用户没有chown&stat文件的权限

**Comment by xxhacker** [comment]
@ioito 我查看了一下，是开了selinux，然后关掉后，重启机器后，报错更多了
![1712479095023](https://github.com/yunionio/cloudpods/assets/4537805/65af6de5-4428-404c-9bf8-5f1c1f5c6d2b)

**Comment by ioito** [comment]
依然是权限问题，这个需要你自己解决

**Comment by xxhacker** [comment]
@ioito 不好意思，权限问题我自己解决了，又碰到了这个问题，感觉好像少了个横杠
![1712480747427](https://github.com/yunionio/cloudpods/assets/4537805/df0fd34f-8738-4076-8b1f-750547fbadaf)

**Comment by ioito** [comment]
可能是docker版本不一致，你按整个文档，从头开始操作
