### ISSUE TITLE
[求助/Help]在代码中新加了报错信息，如何整合到locales.go中

### ISSUE THREAD

**Issue by meibin353** [yunionio/cloudpods#19884]
执行Makefile中的y18n-gen方法报错
/usr/bin/make -f /data/gowork/src/git.mg.xyz/mg-cloud/cloudpods/Makefile -C /data/gowork/src/git.mg.xyz/mg-cloud/cloudpods y18n-gen
make: 进入目录“/data/gowork/src/git.mg.xyz/mg-cloud/cloudpods”
export GO111MODULE=off; y18n -chdir /data/gowork/src/git.mg.xyz/mg-cloud/cloudpods -dir ./locales/ -out ./locales/locales.go -lang en-US,zh-CN yunion.io/x/onecloud/cmd/apigateway yunion.io/x/onecloud/cmd/keystone yunion.io/x/onecloud/cmd/monitor yunion.io/x/onecloud/cmd/region yunion.io/x/onecloud/cmd/yunionconf  ; cp ./locales/zh-CN/{out,messages}.gotext.json; 
panic: no concrete method: func (*sync/atomic.Pointer[net/http.response]).CompareAndSwap(old *net/http.response, new *net/http.response) (swapped bool)

goroutine 11103 [running]:
golang.org/x/tools/go/ssa.(*Program).declaredFunc(0x692973?, 0xc06fc716e0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:124 +0xdd
golang.org/x/tools/go/ssa.(*Program).addMethod(0xc03beb77c0, 0xc0438a25f0, 0xc0e1dfabe0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:86 +0x136
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913858, 0xc0438a25e0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:173 +0x6c6
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913740, 0xc05f2dfdc0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:215 +0x325
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913830, 0xc0695669f0}, 0x1)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:228 +0x5cf
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913740, 0xc05f2dfc00}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:221 +0x34a
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913858, 0xc068ab0ba0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:193 +0x4e5
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913880, 0xc06694ef48}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:233 +0x647
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913858, 0xc037b4d3a0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:182 +0x1d3
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913880, 0xc049a0df20}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:233 +0x647
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913858, 0xc0b48452a0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:182 +0x1d3
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913880, 0xc0305604b0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:233 +0x647
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc03beb77c0, {0x913740, 0xc0402fefc0}, 0x0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:181 +0x1b1
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc03beb77c0, {0x913740?, 0xc0402fefc0?})
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/methods.go:145 +0x70
golang.org/x/tools/go/ssa.(*Package).build(0xc0308b04e0)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/builder.go:2275 +0xf6
sync.(*Once).doSlow(0x0?, 0x0?)
	/home/meibin/.goenv/versions/1.22.1/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/home/meibin/.goenv/versions/1.22.1/src/sync/once.go:65
golang.org/x/tools/go/ssa.(*Package).Build(...)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/builder.go:2263
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x0?)
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/builder.go:2247 +0x46
created by golang.org/x/tools/go/ssa.(*Program).Build in goroutine 1
	/data/gowork/github.com/yousong/y18n/vendor/golang.org/x/tools/go/ssa/builder.go:2246 +0x18a
cp: 在'./locales/zh-CN/{out,messages}.gotext.json' 后缺少了要操作的目标文件
请尝试执行 "cp --help" 来获取更多信息。

**Comment by ioito** [comment]
https://github.com/yunionio/y18n/pull/1 按这个编译最新的y18n试下
