### ISSUE TITLE
default-host-image的pod没有正常启动

### ISSUE THREAD

**Issue by weiwhy** [yunionio/cloudpods#19899]
问题出现在添加节点后，
有个pod（default-host-image-zc7r4）没起来，提示的错误的/etc/resolv.conf 文件不存在，
但是实际上这个文件是存在的,如下图：

![be1ed58a6de6c1647f1a23a4d837933](https://github.com/yunionio/cloudpods/assets/25366558/44442ce5-bad2-4e91-9c8f-2da2abc21513)

最初我猜测可能是/etc/resolv.conf文件的内容和权限的问题，如下图是node0的可以正常启动这个pod的这个配置文件的截图

![image](https://github.com/yunionio/cloudpods/assets/25366558/5f4bc546-a672-4e3c-819f-a7b9fc4b6e08)

修改文件权限和文件内容一致之后，还是无法正常启动，报错的内容没有变化，还是提示/etc/resolv.conf 文件不存在

推测可能是镜像问题，

![image](https://github.com/yunionio/cloudpods/assets/25366558/8858a5e5-6dc9-4a19-9560-a19fd12d0752)

![image](https://github.com/yunionio/cloudpods/assets/25366558/19a023ab-042c-4ccb-998e-49c38a0dc48d)

但是镜像是一致的，现在不太确定是什么原因导致的，比较费解

**Comment by weiwhy** [comment]
新加的两个节点都是这个问题：
![image](https://github.com/yunionio/cloudpods/assets/25366558/70f1d96d-17b5-4352-badc-8942ff554b38)

操作系统是乌班图的22.04

**Comment by zexi** [comment]
@weiwhy 看下 `ls -alh /etc/resolv.conf` 是不是软链接？

**Comment by weiwhy** [comment]
![image](https://github.com/yunionio/cloudpods/assets/25366558/d1124fa0-9ae1-4887-acfa-63b8a1f1e298)
确实是个软链接

**Comment by weiwhy** [comment]
之前的节点确实不是软的，我改改试试

**Comment by weiwhy** [comment]
好了，都恢复正常了
![image](https://github.com/yunionio/cloudpods/assets/25366558/9cd3f7d9-4fc4-48cd-9a23-957feb7b634e)
多谢大佬

**Comment by weiwhy** [comment]
多谢大佬，大佬威武
