### ISSUE TITLE
[求助/Help]Host容器报错，-qmp: not found

### ISSUE THREAD

**Issue by weiwhy** [yunionio/cloudpods#19918]
Host Pod有报错，表现为前端显示异常，如下图：
![image](https://github.com/yunionio/cloudpods/assets/25366558/78ec74a5-2023-4180-9278-ff209da11207)
通过查看host的log，报错如下:
```
[info 2024-04-09 11:12:36 guestman.(*SGuestManager).OnLoadExistingGuestsComplete(guestman.go:311)] Load existing guests complete...
[error 2024-04-09 11:12:36 hostinfo.(*SHostInfo).PutHostOnline(hostinfo.go:1541)] Host sys error: map[hosts:[{hosts  node4- detect qemu version: unexpect qmp res sh: 3: -qmp: not found
 2024-04-09 11:12:32.511023264 +0000 UTC m=+0.609862057}] isolated_devices:[{isolated_devices    GPU 02:00.0 use kernel driver ast, skip it 2024-04-09 11:12:36.423168378 +0000 UTC m=+4.522007172}]]
```

**Comment by wanyaoqi** [comment]
@weiwhy 看起来是没有找到qemu，怎么安装的qemu ? rpm -qa | grep qemu 看看？

**Comment by weiwhy** [comment]
我查看了一下：
![image](https://github.com/yunionio/cloudpods/assets/25366558/ef1f84c3-940e-48b3-ba4c-4e1b63f98f3e)
是这样的

**Comment by weiwhy** [comment]
![image](https://github.com/yunionio/cloudpods/assets/25366558/2215061a-3fe7-4a4a-9288-3355714a14f9)
会不会是因为没有环境变量，我去试试

**Comment by weiwhy** [comment]
@wanyaoqi 好了，恢复了
加了一条这个
![image](https://github.com/yunionio/cloudpods/assets/25366558/18db252f-266b-4073-b5a7-e63a211bcf25)

**Comment by weiwhy** [comment]
@wanyaoqi 但是有个问题，其他节点的环境变量也没有这个qemu也是正常的

**Comment by wanyaoqi** [comment]
@weiwhy 应该不用加这个环境变量的，host代码会去找 /usr/local/qemu-下面的目录，感觉可能就是重启一下host就好了

**Comment by wanyaoqi** [comment]
可以把这个变量去了在看看，另外看下host configmap中 default_qemu_version 是多少？

**Comment by weiwhy** [comment]
@wanyaoqi  configmap里的版本是
![image](https://github.com/yunionio/cloudpods/assets/25366558/ab589dfb-a1b4-4b29-a0ff-fe67a519f907)
然后我刚刚把profile里后加的环境变量删了，然后重启，没报错，所以就是重启就能解决，难道当时没重启这个节点，应该是忘记重启了，尴尬

**Comment by weiwhy** [comment]
感谢大佬
