### ISSUE TITLE
[求助/Help] ubuntu22.04 Allinone部署时报错，no available installation candidate for yunion-climc=3.11[.-]*

### ISSUE THREAD

**Issue by zhangsj** [yunionio/cloudpods#19921]
os ubuntu 22.04

报错信息
TASK [common : Install latest packages via loop for debian-based system] *******
ok: [10.193.27.32] => (item=[01/37] ca-certificates)
failed: [10.193.27.32] (item=[02/37] yunion-climc=3.11[.-]*) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "cache_update_time": 1712728675, "cache_updated": false, "changed": false, "item_index": 1, "msg": "no available installation candidate for yunion-climc=3.11[.-]*", "package_item": "yunion-climc=3.11[.-]*"}
failed: [10.193.27.32] (item=[03/37] yunion-climc-ee=3.11[.-]*) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "cache_update_time": 1712728675, "cache_updated": false, "changed": false, "item_index": 2, "msg": "no available installation candidate for yunion-climc-ee=3.11[.-]*", "package_item": "yunion-climc-ee=3.11[.-]*"}
ok: [10.193.27.32] => (item=[04/37] yunion-executor)
ok: [10.193.27.32] => (item=[05/37] yunion-fetcherfs)
ok: [10.193.27.32] => (item=[06/37] yunion-ocadm=3.11[.-]*)

NO MORE HOSTS LEFT *************************************************************

**Comment by zhasm** [comment]
@zhangsj 收到，我验证一下

**Comment by zexi** [comment]
https://github.com/yunionio/ocboot/pull/1206

**Comment by zhasm** [comment]
如有问题，请重新打开本issue，继续留言。或新开主题。
