### ISSUE TITLE
[求助/Help] 安装过程能否简化？或者是readme提供一个在线DEMO？

### ISSUE THREAD

**Issue by 2775468731** [yunionio/cloudpods#19945]

**Comment by 2775468731** [comment]
为什么部署一个demo还需要执行ansible......这是什么操作

**Comment by 2775468731** [comment]
我想试用一下云管平台，为什么在我服务器上安装了一个k8s......

**Comment by rekazer0** [comment]
试用的话看看商业版的https://cloud.yunion.cn/auth/register

> 我想试用一下云管平台，为什么在我服务器上安装了一个k8s......
