### ISSUE TITLE
[BUG] 使用镜像创建虚拟机时一直在缓存镜像中，超过2个小时就直接失败？

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#19958]
我有一个虚拟机使用的镜像是从别的地方导入过来的大概1T左右，在创建的时候不管是系统盘还是数据盘都我都指定使用ceph,但一直卡在了缓存镜像中，我观察有几下现象如图：
![1712895557168](https://github.com/yunionio/cloudpods/assets/4537805/50e9e94a-9c4a-4529-be49-30d2402373d9)
不知道上面的缓存列表有什么作用？
![1712895628665(1)](https://github.com/yunionio/cloudpods/assets/4537805/297d2895-5e54-442c-bee8-57f212b5af78)
我明明指定创建虚拟机使用的空间在是ceph，不知道为何跑到了某一台计算节点上了（好像是随机指定的一台），且这个文件一直增加，感觉是缓存到这里来了

**Comment by hoganlxj** [comment]
@xxhacker 用新镜像第一次新建虚拟机，是先把镜像缓存宿主机上，后面再新建虚拟机就会用镜像存储。 1T的镜像镜像，上传到宿主机比较慢，可以再等等

**Comment by xxhacker** [comment]
@hoganlxj 今天上传了一天了，还是没有上传好，好像这个缓存到40%左右的时候，也就是这个tmp这个文件500多G的时候，又重新开始缓存了，今天已经第三次了从0到差不多40%，然后又再来一次，我看宿主机的磁盘是有空间的

**Comment by xxhacker** [comment]
能过几次查看我发现，如果缓存时候超过2个小时就失败了，是不是有什么超时设置？
![Quicker_20240413_091610](https://github.com/yunionio/cloudpods/assets/4537805/56a70310-6c52-4d75-80dc-e44877aff24c)
![Snipaste_2024-04-13_09-17-57](https://github.com/yunionio/cloudpods/assets/4537805/b7b7eb66-1f44-4299-95ba-e2e56e31b8ae)
![Snipaste_2024-04-13_09-19-33](https://github.com/yunionio/cloudpods/assets/4537805/333d3b27-779c-4f66-8346-ab9caec0c919)

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/19976 按这个改下，更新下glance服务

**Comment by xxhacker** [comment]
@ioito 按照#19976 代码更新了一下glance服务，把超时时间设置为8个小时，我看日志显示镜像缓存已经100%了，但查看虚拟机的状态还是在缓存镜像中且进度条一动也不动了好几个小时了，一直是83.33%，不知道什么原因，也没有日志报错或者不知道在哪里看日志了
![Snipaste_2024-04-15_23-18-17](https://github.com/yunionio/cloudpods/assets/4537805/6c887c8d-5841-447f-9883-3724665fc54c)
![Snipaste_2024-04-15_23-19-20](https://github.com/yunionio/cloudpods/assets/4537805/01fc4ac6-99e8-4a21-9d10-c1e75982e5f9)

**Comment by ioito** [comment]
是否创建时选了共享存储，例如ceph，如果是，83.33%之后需要把镜像导入到ceph中

**Comment by xxhacker** [comment]
@ioito 后端是ceph,就是这个镜像比较大缓存比较久，现在的状态是在分配磁盘中，由于这个镜像比较大，所以分配磁盘时间也相当久，不知道能在哪里可以查看分配磁盘的进度，已经分配了快24小时了

**Comment by ioito** [comment]
目前没有地方展示导入镜像到ceph的进度
