### ISSUE TITLE
[BUG]虚拟机自定义数据失败

### ISSUE THREAD

**Issue by dominickcjh** [yunionio/cloudpods#19983]
**问题描述/What happened**:
通过cloudpods纳管vmware，创建虚拟机并自定义数据，自定义数据内容未执行成功

**环境/Environment**:
- OS: CentOS 7.9
- Kernel: Linux CloudPods 5.4.130-1.yn20230805.el7.x86_64
- Service Version: 3.11

**问题分析**:
创建的虚拟机使用镜像CentOS-7-x86_64-GenericCloud-2009.qcow2，随机生成root密码，虚拟机创建完成后，登录虚拟机使用journalctl命令查看发现报错Failed at step EXEC spawning /etc/userdata.sh: Permission denied，查看/etc/userdata.sh内容，发现其包含创建虚拟机时高级设置-自定义数据中填写的内容，判断虚拟机需要执行该脚本来实现自定义数据中填写的内容。但通过ls -l /etc/userdata.sh发现该脚本文件权限为600，没有可执行权限。不知道是否为代码问题。

**Comment by dominickcjh** [comment]
镜像中的umask 0022

**Comment by swordqiu** [comment]
收到，的确可能是umask的问题

**Comment by swordqiu** [comment]
https://github.com/yunionio/cloudpods/pull/19987 这个PR在 release/3.11 修复，请等待下次升级
