### ISSUE TITLE
[BUG] 删除云账号的时候没有级联删除对应的serversku

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#20011]
**问题描述/What happened**:
删除云账号的时候没有级联删除对应的serversku，删除云账号的task，没有涉及相关serversku的删除应该
**环境/Environment**:
master分支
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
哪个云，这个云是否有其他云账号

**Comment by ilovedumplings** [comment]
> 哪个云，这个云是否有其他云账号

私有云和公有云都有这个问题,私有云使用openstack,公有云使用的是阿里云

**Comment by ilovedumplings** [comment]
https://github.com/yunionio/cloudpods/issues/20011#issuecomment-2058174990  不知道这样改合适么

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/blob/35b58e7d837cf5913ebe030338a9a581a79f4506/pkg/compute/models/purge.go#L93 这里会清除sku，需要region没有被其他账号引用后才会删

**Comment by ilovedumplings** [comment]
> https://github.com/yunionio/cloudpods/blob/35b58e7d837cf5913ebe030338a9a581a79f4506/pkg/compute/models/purge.go#L93
> 
> 这里会清除sku，需要region没有被其他账号引用后才会删

为什么region还被引用就允许云账号被删除呢?

**Comment by ilovedumplings** [comment]
> https://github.com/yunionio/cloudpods/blob/35b58e7d837cf5913ebe030338a9a581a79f4506/pkg/compute/models/purge.go#L93
> 
> 这里会清除sku，需要region没有被其他账号引用后才会删



> > https://github.com/yunionio/cloudpods/blob/35b58e7d837cf5913ebe030338a9a581a79f4506/pkg/compute/models/purge.go#L93
> > 
> > 这里会清除sku，需要region没有被其他账号引用后才会删
> 
> 为什么region还被引用就允许云账号被删除呢?

而且云账号被删除之后,虚拟机就应该不存在了吧?那其region为什么还会被引用呢?

**Comment by ioito** [comment]
公有云region是共用，最后一个云账号删除才会删除对应的region

**Comment by ilovedumplings** [comment]
> 公有云region是共用，最后一个云账号删除才会删除对应的region

那私有云账号被删除了，我理解对应的私有云的region以后也就用不到了，而且私有云对应的虚拟机其实在平台应该都不可见了吧?那其实region应该也会被删除吧?但我私有云的region是没有被删除呢，这块是有什么考虑吗?

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/pull/20020  试下这个改动
