### ISSUE TITLE
[求助/Help]Allinone 模式下EIP外部无法访问

### ISSUE THREAD

**Issue by 20162430117** [yunionio/cloudpods#20053]
![1713408157927](https://github.com/yunionio/cloudpods/assets/43359848/735a5d77-a0ab-4fd5-98ee-a9c65fcefac0)
![1713408185138](https://github.com/yunionio/cloudpods/assets/43359848/3b69411f-5358-40b3-9717-bcaab54e887b)

**Comment by hoganlxj** [comment]
@20162430117 参考下面文章，是不是没有添加eip网段的静态路由
https://www.cloudpods.org/docs/guides/onpremise/network/vpc/eiphowto
