### ISSUE TITLE
[求助/Help]关于裸金属客户机无法获取DCHP

### ISSUE THREAD

**Issue by Enddyone** [yunionio/cloudpods#20080]
http://docs-os.yunion.cn/docs/getting-started/onpremise/baremetal
您好我是按照官网的教程，配置了dhcp relay 客户机器无法获取DHCP，一直在dhcp那转圈圈。所有的机器都在一个lan 下 面，查看dhcp 端口监听也是正常的，请问这个是什么问题，应该从那方排查，另外我单独假设的dhcp 是可以获取IP的。

**Comment by hoganlxj** [comment]
@Enddyone 配置dhcp relay 没？

**Comment by Enddyone** [comment]
配置了，还是不行。取消relay 后， 配置host的也是无法获取ip，一直都在请求。

**Comment by zexi** [comment]
> 配置了，还是不行。取消relay 后， 配置host的也是无法获取ip，一直都在请求。

@Enddyone 可以通过查看 baremetal-agent 这个 pod 的日志，看下有没有收到来自 dhcp relay 的请求。或者使用 tcpdump 抓包看下 dhcp 请求有没有到 baremetal-agent 服务所在的节点。

**Comment by Enddyone** [comment]
您好，我进行了抓包，显示dhcp请求是可以到 服务器的，就是无法分配ip地址。配置的是/etc/yunion/host.conf
![a](https://github.com/yunionio/cloudpods/assets/167519465/c642aae8-f3fe-48d6-a439-7cd7a830e5d3)

[root@master ~]#  tcpdump  -i enp1s0f0 udp port 67 or port 68 -vvv
tcpdump: listening on enp1s0f0, link-type EN10MB (Ethernet), capture size 262144 bytes
22:48:01.033005 IP (tos 0x0, ttl 20, id 1, offset 0, flags [none], proto UDP (17), length 396)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 00:25:90:ca:80:22 (oui Unknown), length 368, xid 0x90ca8022, secs 6, Flags [Broadcast] (0x8000)
          Client-Ethernet-Address 00:25:90:ca:80:22 (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 36: 
              Subnet-Mask, Time-Zone, Default-Gateway, Time-Server
              IEN-Name-Server, Domain-Name-Server, RL, Hostname
              BS, Domain-Name, SS, RP
              EP, RSZ, TTL, BR
              YD, YS, NTP, Vendor-Option
              Requested-IP, Lease-Time, Server-ID, RN
              RB, Vendor-Class, TFTP, BF
              Option 128, Option 129, Option 130, Option 131
              Option 132, Option 133, Option 134, Option 135
            MSZ Option 57, length 2: 1260
            GUID Option 97, length 17: 0.0.0.0.0.0.0.0.0.0.0.0.37.144.202.128.34
            ARCH Option 93, length 2: 0
            NDI Option 94, length 3: 1.2.1
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
            Agent-Information Option 82, length 18: 
              Circuit-ID SubOption 1, length 6: ^@^D^@^A^A^C
              Remote-ID SubOption 2, length 8: ^@^FpM-^A^EM-6M-c@
            END Option 255, length 0
22:48:05.039012 IP (tos 0x0, ttl 20, id 2, offset 0, flags [none], proto UDP (17), length 396)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 00:25:90:ca:80:22 (oui Unknown), length 368, xid 0x90ca8022, secs 10, Flags [Broadcast] (0x8000)
          Client-Ethernet-Address 00:25:90:ca:80:22 (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 36: 
              Subnet-Mask, Time-Zone, Default-Gateway, Time-Server
              IEN-Name-Server, Domain-Name-Server, RL, Hostname
              BS, Domain-Name, SS, RP
              EP, RSZ, TTL, BR
              YD, YS, NTP, Vendor-Option
              Requested-IP, Lease-Time, Server-ID, RN
              RB, Vendor-Class, TFTP, BF
              Option 128, Option 129, Option 130, Option 131
              Option 132, Option 133, Option 134, Option 135
            MSZ Option 57, length 2: 1260
            GUID Option 97, length 17: 0.0.0.0.0.0.0.0.0.0.0.0.37.144.202.128.34
            ARCH Option 93, length 2: 0
            NDI Option 94, length 3: 1.2.1
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
            Agent-Information Option 82, length 18: 
              Circuit-ID SubOption 1, length 6: ^@^D^@^A^A^C
              Remote-ID SubOption 2, length 8: ^@^FpM-^A^EM-6M-c@
            END Option 255, length 0
22:48:13.058065 IP (tos 0x0, ttl 20, id 3, offset 0, flags [none], proto UDP (17), length 396)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 00:25:90:ca:80:22 (oui Unknown), length 368, xid 0x90ca8022, secs 18, Flags [Broadcast] (0x8000)
          Client-Ethernet-Address 00:25:90:ca:80:22 (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 36: 
              Subnet-Mask, Time-Zone, Default-Gateway, Time-Server
              IEN-Name-Server, Domain-Name-Server, RL, Hostname
              BS, Domain-Name, SS, RP
              EP, RSZ, TTL, BR
              YD, YS, NTP, Vendor-Option
              Requested-IP, Lease-Time, Server-ID, RN
              RB, Vendor-Class, TFTP, BF
              Option 128, Option 129, Option 130, Option 131
              Option 132, Option 133, Option 134, Option 135
            MSZ Option 57, length 2: 1260
            GUID Option 97, length 17: 0.0.0.0.0.0.0.0.0.0.0.0.37.144.202.128.34
            ARCH Option 93, length 2: 0
            NDI Option 94, length 3: 1.2.1
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
            Agent-Information Option 82, length 18: 
              Circuit-ID SubOption 1, length 6: ^@^D^@^A^A^C
              Remote-ID SubOption 2, length 8: ^@^FpM-^A^EM-6M-c@
            END Option 255, length 0

**Comment by Enddyone** [comment]
私有云创建的时候是可以从pxe 地址池里面正常获取IP 地址的 。

**Comment by Enddyone** [comment]
<html>
<body>

2024/04/24 09:44:09 Allow hosts []
--
  |   | [info 2024-04-24 09:44:09 appsrv.NewApplication(appsrv.go:121)] App hostId: cY8tXZguAyYnUlH-IAoWnpTeN_0= (baremetal-agent,master,107.x.x.138)
  |   | [info 2024-04-24 09:44:09 app.InitApp(app.go:32)] RequestWorkerCount: 8
  |   | [info 2024-04-24 09:44:09 watcher.(*SInformerSyncManager).startWatcher(watcher.go:83)]EndpointChangeManager: Start resource informer watcher for endpoint
  |   | [info 2024-04-24 09:44:09 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
  |   | [info 2024-04-24 09:44:09 policy.(*SPolicyManager).init(policy.go:136)] policy fetch worker count 1
  |   | [info 2024-04-24 09:44:09 service.(*BaremetalService).StartService.func1(service.go:69)] auth complete
  |   | [error 2024-04-24 09:44:09 auth.(*authManager).startRefreshRevokeTokens(auth.go:179)] refreshRevokeTokens: No valid admin token credential
  |   | [info 2024-04-24 09:44:09 service.(*BaremetalService).StartService(service.go:57)] No BootIsoPath, use default /opt/cloud/workspace/bm_boot_iso
  |   | [info 2024-04-24 09:44:09 service.(*BaremetalService).StartService(service.go:53)] No cachepath, use default /opt/cloud/workspace/bm_image_cache
  |   | [info 240424 09:44:09 options.parseOptions(options.go:354)] Set log level to "info"
  |   | [warning 240424 09:44:09 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument enable-rbac
  |   | [info 240424 09:44:09 options.parseOptions(options.go:331)] Use configuration file: /etc/yunion/baremetal-agent.conf
  |   | [info 240424 09:44:09 loader.init.0(loader.go:28)] Redfish drivers loaded!
  |   | [info 2024-04-24 09:44:06 appsrv.(*Application).waitCleanShutdown(appsrv.go:545)] Service stopped.
  |   | [info 2024-04-24 09:44:06 baremetal.Stop(agent.go:231)] baremetalAgent stop ...
  |   | [info 2024-04-24 09:44:06 appsrv.(*Application).registerCleanShutdown.func1(appsrv.go:521)] Quit signal received!!! do cleanup...
  |   | [info 2024-04-24 09:42:12 options.optionsEquals(manager.go:116)] Options changed: {"auto_register_baremetal":[false,true]}
  |   | [OLD]: {"config_version":1,"created_at":"2024-04-21T03:24:45.000000Z","deleted":false,"enabled":true,"id":"9f0e0db609b747568ab0273db65dbe22","is_emulated":false,"name":"baremetal","type":"baremetal","update_version":1,"updated_at":"2024-04-21T04:00:54.000000Z"}
  |   | [NEW]: {"config_version":2,"created_at":"2024-04-21T03:24:45.000000Z","deleted":false,"enabled":true,"id":"9f0e0db609b747568ab0273db65dbe22","is_emulated":false,"name":"baremetal","type":"baremetal","update_version":2,"updated_at":"2024-04-24T09:42:12.000000Z"}
  |   | [info 2024-04-24 09:42:12 watcher.(*SInformerSyncManager).OnUpdate(watcher.go:47)]UPDATED: :


</body>
</html>


好像是dhcp relay 没有生效，配置了，启用了，hosts 也没生效。

**Comment by zexi** [comment]
> ![1](https://private-user-images.githubusercontent.com/167519465/325180152-5ade4783-683c-4141-899e-87ac7c34e5e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTEyMTYsIm5iZiI6MTcxNDAxMDkxNiwicGF0aCI6Ii8xNjc1MTk0NjUvMzI1MTgwMTUyLTVhZGU0NzgzLTY4M2MtNDE0MS04OTllLTg3YWM3YzM0ZTVlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMjA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDFhODk2NThkNjk1MGRlMGNjYjY5ODI4MzQzZDZhODhhNWY5M2NhNDg1YmMxYWUyNGE2MGFiNTA2NTcwZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0onYZYg6dUhcIxPBdVynArPPBMqB02DiuEPBGV4FiVo) 配置的e host dhcp relay 好像都没生效。

@Enddyone /etc/yunion/host.conf 里面的 dhcp_relay 怎么配置的？

**Comment by Enddyone** [comment]
![20240426082516](https://github.com/yunionio/cloudpods/assets/167519465/f3239f2e-4823-4a72-b6cf-3775b6467444)
您好，就是按照你们官网的教程配置的。

**Comment by zexi** [comment]
@Enddyone 这个要结合你们的网络环境排查了，大概思路就是：
- 确保这个二层网络下，只有一个 dhcp server ，如果交换机上配了 dhcp ，就在交换机上设置 relay
- 或者禁用交换机的 dhcp 服务，只让这个 host 服务做 dhcp relay
