### ISSUE TITLE
[求助/Help] centos9安装出现Host name can not contain 'localhost' 该怎么处理

### ISSUE THREAD

**Issue by Circlefork** [yunionio/cloudpods#20095]
TASK [utils/misc-check : print hostname msg] ***********************************
fatal: [192.168.110.228]: FAILED! => {"changed": false, "msg": "Host name can not contain 'localhost'!"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.110.228            : ok=3    changed=0    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0

**Comment by zhasm** [comment]
1. centos9 从没适配过。极大大大大大概率跑不通。目前适配到了 centos 8。完整的适配列表请见： https://www.cloudpods.org/docs/getting-started/cmp/quickstart-ocboot 
2. 请看报错。`hostname` 里不得含有 `localhost` 字样。请更新`hostname`。

**Comment by Circlefork** [comment]
是centos7 我打错了 只需要修改hostname吗 在哪修改

**Comment by zhasm** [comment]
`hostnamectl set-hostname <new-hostname>`
