### ISSUE TITLE
创建ESXI硬盘失败

### ISSUE THREAD

**Issue by TracyBin** [yunionio/cloudpods#20106]
- 版本：cloudpods 3.10.8，部署方式是ocboot 融合云
- vCenter: 8.0
- 问题描述：创建ESXI硬盘失败，创建出来的硬盘格式为qcow2，应该是vmdk格式

![image](https://github.com/yunionio/cloudpods/assets/16395897/a0b00b69-e786-4681-96c5-ade9c6148950)

- 问题复现：在硬盘页面创建云硬盘失败，报错信息如下
![image](https://github.com/yunionio/cloudpods/assets/16395897/5acae2d0-77e8-4c7e-9450-dafdeb06cef7)
- F12查看接口传参，发现hypervisor参数值是kvm，且创建硬盘页面的宿主机和虚拟机下拉框均是空值
![e75791f0be2429ec514ec50cf50b5fe](https://github.com/yunionio/cloudpods/assets/16395897/79120441-511f-4e6a-937d-ac14a6142176)
- 宿主机下拉框调用的 URL为：https://10.19.xx.xx/api/v2/hosts?scope=system&show_fail_reason=true&details=false&baremetal=false&limit=0&brand=OneCloud&storage_type=rotate

**Comment by ioito** [comment]
宿主机下拉框是少了一个参数，不过vmware的磁盘目前不支持单独创建。

**Comment by TracyBin** [comment]
1. vCenter确实没有单独创建磁盘的功能和接口，应该通过虚拟机关机后，在配置修改页面增加数据磁盘来解决
2. 硬盘创建页面是否应该屏蔽掉单独创建磁盘的入口

**Comment by dengju2020** [comment]
> 1. vCenter确实没有单独创建磁盘的功能和接口，应该通过虚拟机关机后，在配置修改页面增加数据磁盘来解决
> 2. 硬盘创建页面是否应该屏蔽掉单独创建vmware磁盘的入口

我们优化下磁盘新建的限制
