### ISSUE TITLE
yum源进行缓存提示错误[14] HTTPS Error 404 - Not Found 安装脚本给的网页https://iso.yunion.cn/altarch/7/3.11/aarch64/repodata/repomd.xml: 

### ISSUE THREAD

**Issue by fszw** [yunionio/cloudpods#20108]
- OS (e.g. `CentOS Linux release 7.9.2009 (AltArch)`):
- Kernel (e.g. `Linux cloudpods4 4.18.0-193.28.1.el7.aarch64 #1 SMP Wed Oct 21 16:25:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`):
- Host: (e.g. `    Manufacturer: HiSilicon
        Manufacturer: Huawei
        Manufacturer: HUAWEI
        Manufacturer: Hynix
        Manufacturer: NO DIMM
        Product Name: BC82AMDDIA
        Product Name: S920X00K`)
- Service Version (e.g. `---+
| ansible       | release/3.11(3eed5b59c424031912)           |
| apimap        | release/3.11(3eed5b59c424031913)           |
| cloudmon      | release/3.11(3eed5b59c424031912)           |
| cloudproxy    | release/3.11(3eed5b59c424031913)           |
| compute_v2    | release/3.11(3eed5b59c424031913)           |
| devtool       | release/3.11(3eed5b59c424031913)           |
| identity      | release/3.11(3eed5b59c424031913)           |
| image         | release/3.11(3eed5b59c424031913)           |
| k8s           | heads/v3.11.2-20240318.1(e6c3e48724031912) |
| log           | release/3.11(3eed5b59c424031913)           |
| monitor       | release/3.11(3eed5b59c424031913)           |
| notify        | release/3.11(3eed5b59c424031913)           |
| scheduledtask | release/3.11(3eed5b59c424031912)           |
| scheduler     | release/3.11(3eed5b59c424031912)           |
| vpcagent      | release/3.11(3eed5b59c424031913)           |
| webconsole    | release/3.11(3eed5b59c424031912)           |
| yunionconf    | release/3.11(3eed5b59c424031913)  `):

**Comment by fszw** [comment]
![image](https://github.com/yunionio/cloudpods/assets/149599367/6af98562-6f87-447b-a31d-c4776a5261ba)

**Comment by zhasm** [comment]
您的安装方式是ocboot 对吗？用的哪个分支？是否是最新commit? 安装命令是？

**Comment by fszw** [comment]
> 您的安装方式是ocboot 对吗？用的哪个分支？是否是最新commit? 安装命令是？

对 完全按照手册来的

**Comment by zhasm** [comment]
好的，我再试一下本地能否复现

**Comment by zhasm** [comment]
@fszw 麻烦您再发一下  `cat /etc/*os-release` 的命令结果。**以及您的安装命令**。（是使用python3 run.py xxx，还是使用了 buildash ）

```sh
cat /etc/*os-release
CentOS Linux release 7.9.2009 (AltArch)
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by fszw** [comment]
> 麻烦您再发一下 的命令结果。**以及您的安装命令**。（是使用python3 run.py xxx，还是使用了 buildash ）`cat /etc/*os-release`
> 
> ```shell
> cat /etc/*os-release
> CentOS Linux release 7.9.2009 (AltArch)
> NAME="CentOS Linux"
> VERSION="7 (AltArch)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (AltArch)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7:server"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"
> ```

 ./ocboot.py add-node 10.10.10.7 10.10.50.4

**Comment by fszw** [comment]
> 麻烦您再发一下 的命令结果。**以及您的安装命令**。（是使用python3 run.py xxx，还是使用了 buildash ）`cat /etc/*os-release`
> 
> ```shell
> cat /etc/*os-release
> CentOS Linux release 7.9.2009 (AltArch)
> NAME="CentOS Linux"
> VERSION="7 (AltArch)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (AltArch)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7:server"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"
> ```

![image](https://github.com/yunionio/cloudpods/assets/149599367/fc561763-ba3f-4a6c-ae5b-72ded77ca9ba)

**Comment by zhasm** [comment]
感谢反馈，可以复现了。我更新代码，今天之内测试、提交代码。

**Comment by zhasm** [comment]
@fszw 
已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。
有进展之后，请反馈，多谢。

**Comment by fszw** [comment]
> @fszw 已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。 有进展之后，请反馈，多谢。 如果报错，请 执行如下代码，看一下结果。
> 
> ```shell
> curl  curl https://iso.yunion.cn/centos/7/3.11/aarch64/yunion.repo
> cat /etc/yum.repos.d/yunion.repo
> ```

好的

**Comment by fszw** [comment]
> > @fszw 已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。 有进展之后，请反馈，多谢。 如果报错，请 执行如下代码，看一下结果。
> > ```shell
> > curl  curl https://iso.yunion.cn/centos/7/3.11/aarch64/yunion.repo
> > cat /etc/yum.repos.d/yunion.repo
> > ```
> 
> 好的

问题已经解决了 这边可以安装了

**Comment by fszw** [comment]
> @fszw 已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。 有进展之后，请反馈，多谢。 如果报错，请 执行如下代码，看一下结果。
> 
> ```shell
> curl https://iso.yunion.cn/centos/7/3.11/aarch64/yunion.repo
> cat /etc/yum.repos.d/yunion.repo
> ```

但是 部署上后 虚拟机启动不起来 
![image](https://github.com/yunionio/cloudpods/assets/149599367/1b74ffe4-ffbc-4614-8e17-d727c6c3bba0)

**Comment by zhasm** [comment]
@fszw 好的，我请同事看一下虚机起不来的问题

**Comment by wanyaoqi** [comment]
> > @fszw 已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。 有进展之后，请反馈，多谢。 如果报错，请 执行如下代码，看一下结果。
> > ```shell
> > curl https://iso.yunion.cn/centos/7/3.11/aarch64/yunion.repo
> > cat /etc/yum.repos.d/yunion.repo
> > ```
> 
> 但是 部署上后 虚拟机启动不起来 ![image](https://private-user-images.githubusercontent.com/149599367/324800937-1b74ffe4-ffbc-4614-8e17-d727c6c3bba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzEzMjEsIm5iZiI6MTcxMzg3MTAyMSwicGF0aCI6Ii8xNDk1OTkzNjcvMzI0ODAwOTM3LTFiNzRmZmU0LWZmYmMtNDYxNC04ZTE3LWQ3MjdjNmMzYmJhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMTE3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA2NjIzMGI0ZWI2ZGQyZDc3MGNiYWI4NTA2ZTYwYmNmMDU5ODIzYTNlNTM5NjU5NTViNjMxNzIxZmVmMmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JPsbYmNAIVFrZHpuuurdUwqMQKUMsT3epwh9kZoXqTQ)

@fszw 这个是个已知问题，已经修复过了，可以更新一下 host-deployer 镜像
```
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/hostdeployer/imageName, value: host-deployer},{op: replace, path: /spec/hostdeployer/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/hostdeployer/tag, value: v3.11.3-20240423.0}]'

更新到这个版本：
registry.cn-beijing.aliyuncs.com/yunionio/host-deployer:v3.11.3-20240423.0
```

**Comment by fszw** [comment]
> > > @fszw 已经更新了配置，请重新执行您之前的命令。（不需要更新ocboot代码）。 有进展之后，请反馈，多谢。 如果报错，请 执行如下代码，看一下结果。
> > > ```shell
> > > curl https://iso.yunion.cn/centos/7/3.11/aarch64/yunion.repo
> > > cat /etc/yum.repos.d/yunion.repo
> > > ```
> > 
> > 
> > 但是 部署上后 虚拟机启动不起来 ![image](https://private-user-images.githubusercontent.com/149599367/324800937-1b74ffe4-ffbc-4614-8e17-d727c6c3bba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzEzMjEsIm5iZiI6MTcxMzg3MTAyMSwicGF0aCI6Ii8xNDk1OTkzNjcvMzI0ODAwOTM3LTFiNzRmZmU0LWZmYmMtNDYxNC04ZTE3LWQ3MjdjNmMzYmJhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMTE3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA2NjIzMGI0ZWI2ZGQyZDc3MGNiYWI4NTA2ZTYwYmNmMDU5ODIzYTNlNTM5NjU5NTViNjMxNzIxZmVmMmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JPsbYmNAIVFrZHpuuurdUwqMQKUMsT3epwh9kZoXqTQ)
> 
> @fszw 这个是个已知问题，已经修复过了，可以更新一下 host-deployer 镜像
> 
> ```
> kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/hostdeployer/imageName, value: host-deployer},{op: replace, path: /spec/hostdeployer/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/hostdeployer/tag, value: v3.11.3-20240422.2}]'
> 
> 更新到这个版本：
> registry.cn-beijing.aliyuncs.com/yunionio/host-deployer:v3.11.3-20240422.2
> ```

还是不行 
![image](https://github.com/yunionio/cloudpods/assets/149599367/b3f8be95-a39f-4b7f-ad3f-a1e48bcf67e6)
{
    "__reason__": {
        "reason": {
            "__reason__": {
                "reason": "{\"__reason__\":{\"reason\":{\"__reason__\":\"create_raw: Fail to create disk: create image failed: qemu-img: /opt/nfs_share/9b233556-533f-49e6-8fd8-356d440ecce2: Failed to lock byte 101\\nFormatting '/opt/nfs_share/9b233556-533f-49e6-8fd8-356d440ecce2', fmt=qcow2 size=32212254720 cluster_size=2097152 preallocation=metadata lazy_refcounts=off refcount_bits=16\\n: exit status 1\",\"__stage__\":\"OnDiskReady\",\"__status__\":\"error\"},\"stage\":\"OnDiskReady\"},\"__stage__\":\"OnKvmDiskPrepared\",\"__status__\":\"error\",\"__task_name__\":\"DiskCreateTask\"}",
                "stage": "OnKvmDiskPrepared"
            },
            "__stage__": "OnDiskPrepared",
            "__status__": "error",
            "__task_name__": "KVMGuestCreateDiskTask"
        },
        "stage": "OnDiskPrepared"
    },
    "__stage__": "OnDiskPrepared",
    "__status__": "error",
    "__task_name__": "GuestCreateDiskTask"
}
但是 这个再同步一下状态 后点击开机,虚拟机就运行了  这个只出现在部署arm架构的虚拟机时出现 会不会是因为我用的cpu是鲲鹏920的原因

**Comment by zhasm** [comment]
@fszw 更新镜像之后，问题是否得到解决？
