### ISSUE TITLE
[求助/Help] 如何使用java的sdk或者官方Api上传镜像文件

### ISSUE THREAD

**Issue by WjtMatch** [yunionio/cloudpods#20101]
sdk和api文档都没找到和文件上传相关的内容，查询页面看到web端是用/images/upload的地址上传的，这个地址在api和sdk也没找到

**Comment by ioito** [comment]
目前java sdk确实不支持上传，后续会支持，若能看懂golang代码，可以参考 https://github.com/yunionio/cloudpods/blob/15bd94a0b6cb525e77a04b417253856eff43d25c/pkg/mcclient/modules/image/mod_images.go#L439 实现
