### ISSUE TITLE
私有云， 虚拟机创建成功后，VPC 网络 一直获取不到正确获取IP [BUG]

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#20145]
问题描述/What happened:
私有云， 虚拟机创建成功后，一直获取不到正确获取IP
环境/Environment:
centos7

OS (e.g. cat /etc/os-release):
[root@centosbase ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Kernel (e.g. uname -a):
[root@centosbase ~]# uname -a
Linux centosbase 5.4.130-1.yn20230805.el7.x86_64 https://github.com/yunionio/cloudpods/pull/1 SMP Wed Oct 11 03:26:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@centosbase ~]#

Host: (e.g. dmidecode | egrep -i 'manufacturer|product' |sort -u)
[root@centosbase ~]# dmidecode | egrep -i 'manufacturer|product' |sort -u
Manufacturer: QEMU
Product Name: Standard PC (i440FX + PIIX, 1996)
[root@centosbase ~]#

Service Version (e.g. kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list):
[root@centosbase ~]# climc version-list
Get "192.168.1.1/version": unsupported protocol scheme ""
Get "https://192.168.1.150:30898/version": dial tcp 192.168.1.150:30898: connect: connection refused
Get "https://192.168.1.150:30443/version": dial tcp 192.168.1.150:30443: connect: connection refused
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field | Value |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ansible | release/3.11(3eed5b59c424031912) |
| apimap | release/3.11(3eed5b59c424031913) |
| cloudevent | release/3.11(3eed5b59c424031913) |
| cloudid | release/3.11(3eed5b59c424031913) |
| cloudmon | release/3.11(3eed5b59c424031912) |
| cloudproxy | release/3.11(3eed5b59c424031913) |
| compute_v2 | release/3.11(3eed5b59c424031913) |
| devtool | release/3.11(3eed5b59c424031913) |
| dns | {"error":{"class":"ClientError","code":499,"details":"Get "192.168.1.1/version": unsupported protocol scheme ""","request":{"headers":{"User-Agent":"yunioncloud-go/201708","X-Aut |
| | h-Token":"*"},"method":"GET","url":"192.168.1.1/version"}}} |
| identity | release/3.11(3eed5b59c424031913) |
| image | release/3.11(3eed5b59c424031913) |
| k8s | heads/v3.11.2-20240318.1(e6c3e48724031912) |
| log | release/3.11(3eed5b59c424031913) |
| monitor | release/3.11(3eed5b59c424031913) |
| notify | release/3.11(3eed5b59c424031913) |
| scheduledtask | release/3.11(3eed5b59c424031912) |
| scheduler | release/3.11(3eed5b59c424031912) |
| vpcagent | release/3.11(3eed5b59c424031913) |
| webconsole | release/3.11(3eed5b59c424031912) |
| yunionconf | release/3.11(3eed5b59c424031913) |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[root@centosbase ~]#

私有云，使用的是 VPC 网络， 虚拟机创建成功后，一直获取不到正确获取IP
虚拟机创建成功后， 这个界面等待时间毕竟长
![image](https://github.com/yunionio/cloudpods/assets/35864027/ead7da56-9150-475b-962b-7c42ac1df4ae)

系统成功进入后， 获取到的ip 不对
![image](https://github.com/yunionio/cloudpods/assets/35864027/19406c38-0532-4f4e-b41b-d5f07bdcf34b)

![image](https://github.com/yunionio/cloudpods/assets/35864027/1834db48-800e-441a-a60f-995b001d9600)

**Comment by zexi** [comment]
@khw934 麻烦把 vpcagent 这个 pod 的日志导出来看下

**Comment by khw934** [comment]
> @khw934 麻烦把 vpcagent 这个 pod 的日志导出来看下

隔离很长时间， 才正确获取了IP
![image](https://github.com/yunionio/cloudpods/assets/35864027/55afaf18-44da-4cdb-9ddf-32b928904d4e)

[vpcagent-240426.log.tar.gz](https://github.com/yunionio/cloudpods/files/15124786/vpcagent-240426.log.tar.gz)

**Comment by ioito** [comment]
将vpcagent升级到3.11.3试下

**Comment by khw934** [comment]
[root@centosbase ~]# kubectl get pods -A | grep 'vpcagent'
onecloud              default-vpcagent-7b7fbb6cb4-jzbvr                   1/1     Running   0          2d1h
[root@centosbase ~]#

怎么升级   default-vpcagent-7b7fbb6cb4-jzbvr  镜像版本

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/operations/upgrading/ocboot-upgrade

**Comment by khw934** [comment]
> 将vpcagent升级到3.11.3试下
升级后，一样的 问题


![image](https://github.com/yunionio/cloudpods/assets/35864027/0fbbf915-fdc1-443e-8f76-26e3fb69e24e)
[vpcagent-24-04-26-2.log](https://github.com/yunionio/cloudpods/files/15124964/vpcagent-24-04-26-2.log)

**Comment by ioito** [comment]
你稍等一段时间后再重启下vpcagent试下，我看日志里面清理了不少无用的信息

**Comment by khw934** [comment]
> 你稍等一段时间后再重启下vpcagent试下，我看日志里面清理了不少无用的信息

过段时间， 就才能获取到正确的ip ， 
![image](https://github.com/yunionio/cloudpods/assets/35864027/1109f8d4-751d-43e0-8144-e6e2c5414db0)
[vpcagent-24-04-26-3.log](https://github.com/yunionio/cloudpods/files/15125055/vpcagent-24-04-26-3.log)

**Comment by khw934** [comment]
整体升级到 3.11.3 ， 问题解决。
