### ISSUE TITLE
[文档/Docs]查询系统镜像详情状态枚举值

### ISSUE THREAD

**Issue by WjtMatch** [yunionio/cloudpods#20161]
文档中镜像状态的枚举值

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/blob/430e85ae012d37c2dd1dcd0cc8f070b3f8333776/pkg/apis/image/consts.go#L27-L42
https://github.com/yunionio/dashboard/blob/22ff5e4276737856a728c7eafd38742b49032468/src/locales/zh-CN.json#L242-L257
