### ISSUE TITLE
[求助/Help]虚拟机的“远程控制”中的“ssh xxx”功能在权限哪个地方配置？

### ISSUE THREAD

**Issue by lanzhiming** [yunionio/cloudpods#20171]
主要问题：虚拟机的“远程控制”中的“ssh xxx”功能在权限哪个地方配置？
补充说明：我在权限那里勾选了“远程控制”，但是远程控制下面对应的下拉菜单中的权限在哪分配？我看到前端代码中对应的**权限为server_perform_list_forward,server_perform_open_forward。但是不清楚是在哪里分配**？这是默认就有？

功能截图：
<img width="1684" alt="image" src="https://github.com/yunionio/cloudpods/assets/10107052/438c7b1a-6808-423d-a706-1919bf544717">

代码截图：
<img width="839" alt="image" src="https://github.com/yunionio/cloudpods/assets/10107052/d3182d48-9829-42d4-82d6-4a1de1dde10b">

权限页面：
![image](https://github.com/yunionio/cloudpods/assets/10107052/98f12aa9-f4cf-4c82-8186-82fcce77af00)
![image](https://github.com/yunionio/cloudpods/assets/10107052/a6585299-a10e-4a1f-8580-1ad328b36df6)

**Comment by dengju2020** [comment]
@lanzhiming 鼠标hover上有提示信息么？
