### ISSUE TITLE
[求助/Help] SSH代理节点显示为空，且无法进行下一步

### ISSUE THREAD

**Issue by bigdata-user** [yunionio/cloudpods#20180]
SSH代理节点显示为空，区域只有云联壹云，无法进行下一步
![abc](https://github.com/yunionio/cloudpods/assets/20829283/cd935e47-9e78-454a-9169-8211182970bc)

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/6763
