### ISSUE TITLE
[求助/Help] 我在阿里云上找了两个云主机部署了 cloudpods  私有云， 通过内网IP 可以访问门户， 但是通过 公网IP 无法访问

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#20181]
我在阿里云上找了两个云主机部署了 cloudpods  私有云， 通过内网IP 可以访问门户， 但是通过 公网IP 无法访问 ， 请问 ingress 需要配置什么？

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/operations/fe/config-ssl-certs#%E6%9B%B4%E6%94%B9%E5%89%8D%E7%AB%AFhttps-443%E7%AB%AF%E5%8F%A3%E4%B8%BA%E5%85%B6%E5%AE%83%E7%AB%AF%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95%E6%AD%A5%E9%AA%A4 试下这个

**Comment by khw934** [comment]
不行， 但是如果把  default-web  的svc ClusterIP 改成  NodePort 就可以 。

**Comment by khw934** [comment]
问题已解决
