### ISSUE TITLE
[求助/Help]服务器断电后，重启后，发现k8s启动有问题，6443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#20200]
你好，服务器断电后，重启后，发现k8s启动有问题，6443 was refused - did you specify the right host or port?
然后在网上查询了一下https://blog.csdn.net/gotheon/article/details/133700695
在控制节点服务器上执行journalctl -xeu kubelet
[root@cloudpods-46 ~]# journalctl -xeu kubelet
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.223397     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.247216     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.347427     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.423403     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.447661     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.547873     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.624083     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.648037     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.748252     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.824173     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.848453     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.948676     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.026934     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.048851     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.149032     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: I0506 17:17:01.201011     901 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.223827     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224951     901 remote_image.go:94] ImageStatus failed: Id or size of image "registry.cn-beijing.aliyuncs.com/yunion/kube-schedule
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224982     901 kuberuntime_image.go:87] ImageStatus for image {"registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8"} 
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225041     901 kuberuntime_manager.go:779] container start failed: ImageInspectError: Failed to inspect image "registry.cn-beijin
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225075     901 pod_workers.go:190] Error syncing pod 140b609d9657a1c71c951f1d02f62324 ("kube-scheduler-cloudpods-46_kube-system(1
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.249219     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.349379     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.423966     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.449528     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.549697     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.624647     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.649886     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.682171     901 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "cloudpods-4
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.750115     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.824685     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.850282     901 kubelet.go:2252] node "cloudpods-46" not found
...skipping...
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.223397     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.247216     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.347427     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.423403     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.447661     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.547873     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.624083     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.648037     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.748252     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.824173     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.848453     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.948676     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.026934     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.048851     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.149032     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: I0506 17:17:01.201011     901 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.223827     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224951     901 remote_image.go:94] ImageStatus failed: Id or size of image "registry.cn-beijing.aliyuncs.com/yunion/kube-schedule
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224982     901 kuberuntime_image.go:87] ImageStatus for image {"registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8"} 
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225041     901 kuberuntime_manager.go:779] container start failed: ImageInspectError: Failed to inspect image "registry.cn-beijin
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225075     901 pod_workers.go:190] Error syncing pod 140b609d9657a1c71c951f1d02f62324 ("kube-scheduler-cloudpods-46_kube-system(1
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.249219     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.349379     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.423966     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.449528     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.549697     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.624647     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.649886     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.682171     901 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "cloudpods-4
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.750115     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.824685     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.850282     901 kubelet.go:2252] node "cloudpods-46" not found
...skipping...
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.223397     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.247216     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.347427     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.423403     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.447661     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.547873     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.624083     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.648037     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.748252     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.824173     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.848453     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.948676     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.026934     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.048851     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.149032     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: I0506 17:17:01.201011     901 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.223827     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224951     901 remote_image.go:94] ImageStatus failed: Id or size of image "registry.cn-beijing.aliyuncs.com/yunion/kube-schedule
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224982     901 kuberuntime_image.go:87] ImageStatus for image {"registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8"} 
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225041     901 kuberuntime_manager.go:779] container start failed: ImageInspectError: Failed to inspect image "registry.cn-beijin
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225075     901 pod_workers.go:190] Error syncing pod 140b609d9657a1c71c951f1d02f62324 ("kube-scheduler-cloudpods-46_kube-system(1
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.249219     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.349379     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.423966     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.449528     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.549697     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.624647     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.649886     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.682171     901 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "cloudpods-4
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.750115     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.824685     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.850282     901 kubelet.go:2252] node "cloudpods-46" not found
...skipping...
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.223397     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.247216     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.347427     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.423403     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.447661     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.547873     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.624083     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.648037     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.748252     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.824173     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.848453     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:00 cloudpods-46 kubelet[901]: E0506 17:17:00.948676     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.026934     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.048851     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.149032     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: I0506 17:17:01.201011     901 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.223827     901 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224951     901 remote_image.go:94] ImageStatus failed: Id or size of image "registry.cn-beijing.aliyuncs.com/yunion/kube-schedule
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.224982     901 kuberuntime_image.go:87] ImageStatus for image {"registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8"} 
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225041     901 kuberuntime_manager.go:779] container start failed: ImageInspectError: Failed to inspect image "registry.cn-beijin
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.225075     901 pod_workers.go:190] Error syncing pod 140b609d9657a1c71c951f1d02f62324 ("kube-scheduler-cloudpods-46_kube-system(1
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.249219     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.349379     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.423966     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.166.62
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.449528     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.549697     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.624647     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.16
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.649886     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.682171     901 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "cloudpods-4
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.750115     901 kubelet.go:2252] node "cloudpods-46" not found
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.824685     901 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.166.62.46
5月 06 17:17:01 cloudpods-46 kubelet[901]: E0506 17:17:01.850282     901 kubelet.go:2252] node "cloudpods-46" not found

按照查询的是否需要重新加载一下API的镜像docker load -i kube-apiserver-amd64_v1.9.0.tar
然后重启docker和k8s

![image](https://github.com/yunionio/cloudpods/assets/58723494/c796fa0f-1626-4228-89a1-410fd1acfb7f)

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/3f4b1a54-b239-4b2d-a720-1b2cff8bd833)

**Comment by szz1113-1119** [comment]
另外，问一下，如果控制节点如果起不起来，是否可以把镜像保留住，重新搭建控制节点，然后把镜像迁移过去

**Comment by hoganlxj** [comment]
@szz1113-1119 看下etcd的容器是否正常，若有异常看下日志
```bash
docker ps -a |grep etcd
```

**Comment by hoganlxj** [comment]
> 另外，问一下，如果控制节点如果起不起来，是否可以把镜像保留住，重新搭建控制节点，然后把镜像迁移过去

/opt/docker目录在，cloudpods组件的镜像是可以用的

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/df7acb63-76e2-4a56-831c-936bad7c564a)
看到是在的
我如何使用

**Comment by szz1113-1119** [comment]
主要是控制节点k8s的apiserver坏了，但里面还有有用的虚拟机，所有想看看有没有办法能恢复

**Comment by szz1113-1119** [comment]
我的控制节点的k8s启动不了，我是否可以重新安装一台控制节点，直接连接坏了的那台控制节点的数据库，使用我原有的虚拟机？

**Comment by szz1113-1119** [comment]
这几个镜像是比较重要的，希望能协助给个方法让我能恢复，我重新安装了一台控制节点，是否可以把那个坏掉的节点，文件或数据库拷贝过来，或者是直接连接坏掉的服务器上的mysql

**Comment by hoganlxj** [comment]
> 我的控制节点的k8s启动不了，我是否可以重新安装一台控制节点，直接连接坏了的那台控制节点的数据库，使用我原有的虚拟机？

@szz1113-1119 参考https://www.cloudpods.org/docs/operations/change-node-ip

**Comment by szz1113-1119** [comment]
多谢，我已经按照您给的方法成功恢复了，多谢

**Comment by rekazer0** [comment]
> [@szz1113-1119](https://github.com/szz1113-1119) 看着是服务器断电后，etcd损坏，导致集群起不来，后面做下自动备份，参考 https://www.cloudpods.org/docs/operations/ha/auto-backup/

请问在k3s的环境中，遇到同样的问题。我应该如何在mysql服务起不来的情况下备份数据库呢？
