### ISSUE TITLE
[求助/Help] 计算节点服务器无法启动，如何删除控制节点页面中的宿主机记录

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#20207]
求助：
前提条件：
1，由于断电，我的控制节点服务器k8s无法启动，然后重新搭建了一台控制节点服务，数据库使用的是旧控制节点服务器的数据库。
2，由于断电，部分计算节点的服务器，无法启动服务器，此服务器已经重装系统。
问题：
1，新的控制节点，web访问后，
![image](https://github.com/yunionio/cloudpods/assets/58723494/41458b87-a5d5-46ac-96ce-48a173d8bf60)
请教如何删除截图中的记录，在页面上无法点击删除按钮，如图所示：
![image](https://github.com/yunionio/cloudpods/assets/58723494/35fefea6-297b-4c37-a4b1-73471a22bce6)

**Comment by hoganlxj** [comment]
@szz1113-1119 参考这个
https://www.cloudpods.org/docs/operations/remove-host

**Comment by szz1113-1119** [comment]
@hoganlxj 按照这个执行了，还是不行，因为那个宿主已经断电连接不上了，我认为应该是直接到数据库把这个数据删掉。
![image](https://github.com/yunionio/cloudpods/assets/58723494/953e6cfc-427b-4cf6-9000-8907a1590060)
![image](https://github.com/yunionio/cloudpods/assets/58723494/45f13f4b-120a-4433-9098-2180bd6f03b4)
![image](https://github.com/yunionio/cloudpods/assets/58723494/1ffda6c8-e1b2-4c82-9399-a1d95b595731)

**Comment by szz1113-1119** [comment]
![image](https://github.com/yunionio/cloudpods/assets/58723494/d6cdc6ab-4d69-4305-9c47-ac979bf47b31)

**Comment by szz1113-1119** [comment]
所以我觉的应该直接删除数据库表中的数据

**Comment by hoganlxj** [comment]
> @hoganlxj 按照这个执行了，还是不行，因为那个宿主已经断电连接不上了，我认为应该是直接到数据库把这个数据删掉。 ![image](https://private-user-images.githubusercontent.com/58723494/328836221-953e6cfc-427b-4cf6-9000-8907a1590060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE4ODAsIm5iZiI6MTcxNTE2MTU4MCwicGF0aCI6Ii81ODcyMzQ5NC8zMjg4MzYyMjEtOTUzZTZjZmMtNDI3Yi00Y2Y2LTkwMDAtODkwN2ExNTkwMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOTIzMjdiNDQ2Y2Y0NTA0NzJmMGQ5ZmJhYWU4M2U3MGE2YzlkMmVkYzFjNjMzM2JlYjM2ZDFiY2E2NDUxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9krKOKhM80-AmlVruItCUWFuB-qJqaWVVuzask9dbI) ![image](https://private-user-images.githubusercontent.com/58723494/328836715-45f13f4b-120a-4433-9098-2180bd6f03b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE4ODAsIm5iZiI6MTcxNTE2MTU4MCwicGF0aCI6Ii81ODcyMzQ5NC8zMjg4MzY3MTUtNDVmMTNmNGItMTIwYS00NDMzLTkwOTgtMjE4MGJkNmYwM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZjU4NjE5OTFhZjFmYjQ0ZDRmNzYzMWQyNWFmZDIzNjBmYTZkNTRlMWZkMjZhNDFhZGExMDY0MmI5YjU4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZI43vUybgs3vNxuP_Gy_mFsZ0S6akJAqPRqrjzbmws) ![image](https://private-user-images.githubusercontent.com/58723494/328836865-1ffda6c8-e1b2-4c82-9399-a1d95b595731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE4ODAsIm5iZiI6MTcxNTE2MTU4MCwicGF0aCI6Ii81ODcyMzQ5NC8zMjg4MzY4NjUtMWZmZGE2YzgtZTFiMi00YzgyLTkzOTktYTFkOTViNTk1NzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTlkYjNmMmJlYmRjZDkxZGFlZTgyZTBlYmY4NWQ3ODk4MzhlMmZmYjBhMjk1N2M1ZGMyODZiOGZiZmJhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9yVHl6AgA_Aa34-XE5lZ2bQ1Q4yOdDOR3nZzp461aD8)

执行删除宿主机的命令报错了，用下面的命令试下
```bash
climc host-purge $host_id
```

**Comment by szz1113-1119** [comment]
这个命令可以，已经删除了，多谢
