### ISSUE TITLE
[求助/Help]配置aksk后，SDK, climc和api接口问题

### ISSUE THREAD

**Issue by FlywinNing** [yunionio/cloudpods#20241]
参考的文档：https://github.com/yunionio/mcclient_python

请问这里的5000端口是固定的吗，我配置后执行 connect: connection refused

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/guides/climc/auth#%E6%8E%A7%E5%88%B6%E8%8A%82%E7%82%B9%E8%AE%A4%E8%AF%81%E9%85%8D%E7%BD%AE
看下自己的环境的环境变量

**Comment by FlywinNing** [comment]
![image](https://github.com/yunionio/cloudpods/assets/158119314/e611064a-6a90-42e3-bfb2-34b3c4a53b82)
@ioito server list是空的，是跟环境变量里的export OS_PROJECT_NAME=system有关系吗

**Comment by ioito** [comment]
climc server-list --scope system

**Comment by FlywinNing** [comment]
@ioito 可以了，谢谢，倒腾半天不如大佬的一个指点👍
