### ISSUE TITLE
[求助/Help]  开出的 虚拟机可以访问 宿主机的网络， 请问有什么办法可以让虚拟机无法访问宿主机的网络？

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#20244]
开出的 虚拟机可以访问 宿主机的网络， 请问有什么办法可以让虚拟机无法访问宿主机的网络？

**Comment by fangpsh** [comment]
自定义一个安全组。

**Comment by DSYZayn** [comment]
@fangpsh 请教一下具体该怎么设置。我希望vpc内的虚拟机(172.16.0.0/24)不能访问宿主机所在的网段(192.168.1.0/24)，尝试自定义安全组把出口流量的192.168.1.0/24网段禁止，导致虚拟机无法上网了。

**Comment by fangpsh** [comment]
> @fangpsh 请教一下具体该怎么设置。我希望vpc内的虚拟机(172.16.0.0/24)不能访问宿主机所在的网段(192.168.1.0/24)，尝试自定义安全组把出口流量的192.168.1.0/24网段禁止，导致虚拟机无法上网了。

主动出，默认放行，drop 宿主机段，我这一切测试正常，符合预期。
主动入，默认拒绝，需要显式放行。

不过我的网络是经典网络（二层），非 VPC 网络，不知是否这里有差异。

https://www.cloudpods.org/docs/guides/onpremise/network/examples#%E4%BA%8C%E5%B1%82%E7%BD%91%E7%BB%9C%E9%85%8D%E7%BD%AE

**Comment by DSYZayn** [comment]
单网口的vpc网络，如何实现虚拟机禁止访问宿主机所在网段？
