### ISSUE TITLE
[BUG]公有云镜像未同步更新

### ISSUE THREAD

**Issue by FlywinNing** [yunionio/cloudpods#20256]
https://github.com/yunionio/cloudpods/issues/18044
你好，参考这个issue，之前遇到的一个问题，公有云镜像更新了，cloudpods这边未同步更新

现在又出现了，麻烦看下，谢谢

![image](https://github.com/yunionio/cloudpods/assets/158119314/28a29bdd-9fa5-4c8d-8dfd-8a2614494e02)
![image](https://github.com/yunionio/cloudpods/assets/158119314/b742f15f-a01f-4289-b8b6-df420d027ba4)

**Comment by ioito** [comment]
是指CentOS 7.9 64位应该没有对吧，是不是之前用这个镜像创建过实例，这个是有bug，最近已经修复。

**Comment by ioito** [comment]
最近上传套餐服务有bug，我恢复下

**Comment by FlywinNing** [comment]
之前是用这个centos7.9创建过
Windows有些也不一致
明天我再试试，谢谢
