### ISSUE TITLE
[BUG] 不确实是不是一个BUG：在用户登陆的时候，token_cache_tbl会生成6个不同token_id

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#20253]
**问题描述/What happened**:
在用户登陆的时候，token_cache_tbl会生成6个不同token_id，不确定是不是bug，因为method是token的时候,除了id不一样,其余的参数都一样，感觉是没有必要的处理。
如下图:
![image](https://github.com/yunionio/cloudpods/assets/19704134/0d77446a-4d73-452c-8f3b-0d13f5e94ea4)
还有个问题是：method=password的作用是什么?

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ilovedumplings** [comment]
> **问题描述/What happened**: 在用户登陆的时候，token_cache_tbl会生成6个不同token_id，不确定是不是bug，因为method是token的时候,除了id不一样,其余的参数都一样，感觉是没有必要的处理。 如下图: ![image](https://private-user-images.githubusercontent.com/19704134/330000214-0d77446a-4d73-452c-8f3b-0d13f5e94ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTMwMzEsIm5iZiI6MTcxNTU5MjczMSwicGF0aCI6Ii8xOTcwNDEzNC8zMzAwMDAyMTQtMGQ3NzQ0NmEtNGQ3My00NTJjLThmM2ItMGQxM2Y1ZTk0ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5MzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzk3M2U3MjZmN2U5OTYxOWEwOTBhNzVjMjFhYWM5MTQ4Njc1ZDVkOGE0ZmMxOWNlNDE2M2Y3MWI2MTZkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1abQMpcu2BO1AcQeVSGmLqVL4N6U3-fDYx5-D45AW8) 还有个问题是：method=password的作用是什么?
> 
> **环境/Environment**:
> 
> * OS (e.g. `cat /etc/os-release`):
> * Kernel (e.g. `uname -a`):
> * Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
> * Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

但是好像每个token的id对应的权限不一致,请问是不是个bug,如果不是bug,这样的逻辑是什么?我没太有排查思路,所以直接问一下了

**Comment by ioito** [comment]
认证通过后，用户在请求资源时，会将token透传到各个服务，由各个服务去验证token是否有效，因此会产生多个token，要验证这个，可以先停掉log服务，再重新登陆，你就会发现登录后是有5个token_id，因为少了透传到log服务验证token

**Comment by ilovedumplings** [comment]
> token
不知道是我理解的问题还是啥?想问下为什么会透传token呢?请求哪里的资源把token带到对应服务不就可以了吗?

**Comment by ioito** [comment]
网关携带token去请求各个服务，其他服务也需要验证这个token正确性，因此也会拿这个token到keystone验证一次，验证过程中会生成新的token(因为服务由网关变成其他服务了)

**Comment by ilovedumplings** [comment]
> 网关携带token去请求各个服务，其他服务也需要验证这个token正确性，因此也会拿这个token到keystone验证一次，验证过程中会生成新的token(因为服务由网关变成其他服务了)

我是不是可以理解成接口从网关进来携带token去请求服务,如果这个接口涉及到了region/keystone/log的业务,那么就会产生3个token

**Comment by ioito** [comment]
是这个意思，不过keystone应该不算，因为它本身就是认证服务

**Comment by ilovedumplings** [comment]
> 是这个意思，不过keystone应该不算，因为它本身就是认证服务

嗯嗯

**Comment by ilovedumplings** [comment]
> 是这个意思，不过keystone应该不算，因为它本身就是认证服务

谢谢
