### ISSUE TITLE
[求助/Help]default-region-dns pod出现问题

### ISSUE THREAD

**Issue by FlywinNing** [yunionio/cloudpods#20250]
从 3.10.13 升级到 3.11，回滚后 default-region-dns 一直CrashLoopBackOff，
麻烦帮忙看下，谢谢

![1715589022149](https://github.com/yunionio/cloudpods/assets/158119314/c672fb2f-4d15-4a2c-b280-54420221579c)

**Comment by hoganlxj** [comment]
@FlywinNing  可以检查下region-dns的镜像版本，如果是3.11的，改为v3.10.13

> 从 3.10.13 升级到 3.11，回滚后 default-region-dns 一直CrashLoopBackOff， 麻烦帮忙看下，谢谢
> 
> ![1715589022149](https://private-user-images.githubusercontent.com/158119314/329980405-c672fb2f-4d15-4a2c-b280-54420221579c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODk1MjcsIm5iZiI6MTcxNTU4OTIyNywicGF0aCI6Ii8xNTgxMTkzMTQvMzI5OTgwNDA1LWM2NzJmYjJmLTRkMTUtNGEyYy1iMjgwLTU0NDIwMjIxNTc5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwODMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGJiNTY2NjBiOWJlNjIxZjRkYzJmNzdhZTQ0ZjM5ZDNlMzk1MWZjODQwYWUyNjJjNjZhYjBmMzE5ZjQ0YTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hT7SRtNGOPMuX80iF_ldH0W_T80m64KGJyrE6c5sQzE)

**Comment by FlywinNing** [comment]
@hoganlxj 是3.10.13  ，看着是报这个错 plugin/yunion: /etc/yunion/region-dns.conf:9 - Error during parsing: unknown property "admin_domain"
![image](https://github.com/yunionio/cloudpods/assets/158119314/5531e5be-4cfa-4d7b-9e88-9e0bec7f6c4a)

**Comment by FlywinNing** [comment]
![image](https://github.com/yunionio/cloudpods/assets/158119314/a6d1bb62-d44a-4a73-9542-3a7a8d9478ee)
![image](https://github.com/yunionio/cloudpods/assets/158119314/70abf373-b05f-4746-aada-91400abcc7b1)

**Comment by hoganlxj** [comment]
@FlywinNing 可以这样操作看下
```bash
kubectl delete cm -n onecloud default-region-dns
kubectl rollout restart ds -n onecloud default-region-dns
```

**Comment by FlywinNing** [comment]
@hoganlxj 我把这个镜像改成v3.11.3的了，倒是正常了，后面再观察看看，谢谢

**Comment by dengju2020** [comment]
@FlywinNing 为什么要降级，是遇到问题了么？

**Comment by FlywinNing** [comment]
@dengju2020 升级后和华为云同步一直超时，不清楚啥原因

**Comment by ioito** [comment]
region-dns并不会影响华为云同步，超时是指点云账号同步时报的超时么
