### ISSUE TITLE
[求助/Help] 对接vmware原来3.10.7正常，升级 3.11.2 后，创建虚拟机无法选择子网

### ISSUE THREAD

**Issue by sun3book** [yunionio/cloudpods#20295]
![image](https://github.com/yunionio/cloudpods/assets/48039439/23bf99cf-9722-4942-9ddb-ee5f27207150)

**Comment by hoganlxj** [comment]
@sun3book 3.11版本后，vmware网络做过调整，需要先手工新建IP子网
具体参考 https://www.cloudpods.org/docs/guides/cmp/vmware/vmware_net
