### ISSUE TITLE
[求助/Help] v3.11.3版本/forecast接口 java sdk验证失败

### ISSUE THREAD

**Issue by WjtMatch** [yunionio/cloudpods#20301]
之前版本是v3.11.2 对应javaSdk是3.2.15 /forecast接口验证没问题，现在升级到v3.11.3 javaSdk升级到3.2.16在平台可以验证通过但是JavaSdk一直返回"can_create": false,同样的参数验证了一下用平台的api可以，用sdk则失败
![1715841516418](https://github.com/yunionio/cloudpods/assets/46695957/3e036840-bc14-4e7b-a3dd-ba883d72bb9c)
![1715841561235](https://github.com/yunionio/cloudpods/assets/46695957/754599bb-0fac-4f38-a590-01ab8c2de3fc)

**Comment by zexi** [comment]
@WjtMatch java sdk 并没有修改这个逻辑，后端调度器那里也没有什么变化，麻烦提供下前端传的 forecast 和 java sdk 的 json ，对比下是否完全一样。
