### ISSUE TITLE
[BUG] 使用lvmlockd模式扩容关机的虚拟机磁盘报错

### ISSUE THREAD

**Issue by CloudCourierStation** [yunionio/cloudpods#20323]
报错信息：
 "__reason__": "lvactive shared: lvchange -aye /dev/cluster-vg/73bd7f2a-9779-46d6-885d-92783ac4f6b9 failed   LV locked by other host: cluster-vg/73bd7f2a-9779-46d6-885d-92783ac4f6b9\n  Failed to lock logical volume cluster-vg/73bd7f2a-9779-46d6-885d-92783ac4f6b9.\n: exit status 5",

**Comment by wanyaoqi** [comment]
@CloudCourierStation 这个问题最近正在修复

**Comment by CloudCourierStation** [comment]
@wanyaoqi 请问一下，主机备份也是报这个错，也是还在修复吗？

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/pull/20380 这个问题应该修复了
