### ISSUE TITLE
[求助/Help]baremetal物理机管理服务组件DHCP服务的配置文件在哪里？

### ISSUE THREAD

**Issue by NeckC** [yunionio/cloudpods#20332]
物理机注册过程中，dhcp无法分配，找不到物理机的DHCP服务在哪个镜像中。
需要查看baremetal对应镜像的配置文件中DHCP是如何进行分配的，以及需要查看DHCP分配的日志和服务状态。
在基础资源-》物理机-》添加物理机，的界面中，选择的是PXE引导注册。其中，指定了ipmi地址、用户名和密码、管理口IP选择的是dhcp子网的静态IP，并且也填充了物理机的eth0的mac地址。
网络确定互相通畅，配置确定没有问题按照官方文档进行配置的。

**Comment by zexi** [comment]
@NeckC dhcp 服务是随着 baremetal-agent 这个服务启动的，需要配置好 dhcp relay ，可以用 tcpdump 抓包看下请求有没有到 baremetal-agent 所在的节点。

**Comment by NeckC** [comment]
> @NeckC dhcp 服务是随着 baremetal-agent 这个服务启动的，需要配置好 dhcp relay ，可以用 tcpdump 抓包看下请求有没有到 baremetal-agent 所在的节点。
@zexi 
抓包看了有收到DHCP的请求 但是没有回复报文，所以现在就想看下 baremetal-agent 这个服务的DHCP配置文件在哪，服务里面的日志报文也要看下具体的信息。

**Comment by zexi** [comment]
@NeckC 可以在物理机 pxe dhcp 启动的时候，看下 baremetal-agent 的日志，里面应该有报错。
baremetal-agent 会根据 dhcp relay 的来源选择网络，还有 dhcp 请求的 mac 地址来选择对应的物理机。

**Comment by zexi** [comment]
> @zexi 问一下这个DHCP的配置文件信息 在cloudpod的哪个容器里面 ![image](https://private-user-images.githubusercontent.com/112455646/334366477-02019fb8-4556-4310-afab-30d14cfe84eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTU4NjYsIm5iZiI6MTcxNjg5NTU2NiwicGF0aCI6Ii8xMTI0NTU2NDYvMzM0MzY2NDc3LTAyMDE5ZmI4LTQ1NTYtNDMxMC1hZmFiLTMwZDE0Y2ZlODRlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMTI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDA0OTkxNmEwZTllOTNkNzQyNDg2NTUyYzE5MDliMzI5ZDEzMjJkNzQzMWMwMmNjYjQyY2EwYzYxY2FiNTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pVTVK3y0j5-dzzBrJsV7QzjfsCO_uZGip51aJ4Vt_fo)
> 
> # NOTE: "boot_file FILE" and "opt bootfile FILE" are conceptually the same,
> # but "boot_file" goes into BOOTP-defined fixed-size field in the packet,
> # whereas "opt bootfile" goes into DHCP option 0x43.
> # Same for "sname HOST" and "opt tftp HOST".
> # Static leases map
> #static_lease 00:60:08:11:CE:4E 192.168.0.54 #static_lease 00:60:08:11:CE:3E 192.168.0.44 optional_hostname
> 
> # The remainder of options are DHCP options and can be specified with the
> # keyword 'opt' or 'option'. If an option can take multiple items, such
> # as the dns option, they can be listed on the same line, or multiple
> # lines.
> # Examples:
> opt dns 192.168.10.2 192.168.10.10 option subnet 255.255.255.0 opt router 192.168.10.2 opt wins 192.168.10.10 option dns 129.219.13.81 # appended to above DNS servers for a total of 3 option domain local option lease 864000 # default: 10 days option msstaticroutes 10.0.0.0/8 10.127.0.1 # single static route option staticroutes 10.0.0.0/8 10.127.0.1, 10.11.12.0/24 10.11.12.1

这个应该不是我们的 dhcp 服务设置

**Comment by NeckC** [comment]
@zexi 你好那你们cloudpodS的DHCP服务配置在哪里的文件里看呢？

**Comment by NeckC** [comment]
@zexi 然后还想看下你们cloudpods正常的DHCP日志是啥样的，我看的日志里没有回应
![image](https://github.com/yunionio/cloudpods/assets/112455646/d277b5fb-9e87-4102-8862-99a82a56b552)

**Comment by zexi** [comment]
> @zexi 然后还想看下你们cloudpods正常的DHCP日志是啥样的，我看的日志里没有回应 ![image](https://private-user-images.githubusercontent.com/112455646/334710154-d277b5fb-9e87-4102-8862-99a82a56b552.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjM5MjgsIm5iZiI6MTcxNzA2MzYyOCwicGF0aCI6Ii8xMTI0NTU2NDYvMzM0NzEwMTU0LWQyNzdiNWZiLTllODctNDEwMi04ODYyLTk5YTgyYTU2YjU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMDA3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjMzNDQ2MjQxMzNiODljNjIwODM3YWRkOWQwNDkwODI0MDQ0MmZhZjFiMDFhZDFlMTY5NDFlYmM1MzExNWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HbnDGAPcZtqtFrT8T3l_tAYdbIk2tKHoq7K5iN5FDUw)

@NeckC 这里有 warning 的日志，说的是收到从 10.123.123.252 这个 dhcp_relay 过来的 a4:ae:12:65:18:75 mac 地址的 dhcp 请求，但是没有找到 match 的 network 。
需要到平台创建一个子网，gateway 为 10.123.123.252 。
如果实际环境中 10.123.123.252 不是网关，可以用命令行更新对应子网的 dhcp 属性，用 `--dhcp` 的参数：`climc network-update --dhcp 10.123.123.252 $子网名称`。

**Comment by NeckC** [comment]
@zexi 你好这个是什么原因
![image](https://github.com/yunionio/cloudpods/assets/112455646/2ad3109b-71df-4555-804b-005b3a04098a)

prepare=>prepare_fail: {"__reason__":"Do deploy: run /lib/mos/sysinit.sh: \"/lib/mos/sysinit.sh\" error: Process exited with status 255, cmd error: Huawei system initialization\nERROR:Can't get hole memory!!\n time 0.08 (ms).\nERROR:Can't get hole memory!!\n time 0.07 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\n","__stage__":"OnSyncConfigComplete","__status__":"error"} run /lib/mos/sysinit.sh: "/lib/mos/sysinit.sh" error: Process exited with status 255, cmd error: Huawei system initialization ERROR:Can't get hole memory!! time 0.08 (ms). ERROR:Can't get hole memory!! time 0.07 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). { "__reason__": { "reason": { "__reason__": "Do deploy: run /lib/mos/sysinit.sh: \"/lib/mos/sysinit.sh\" error: Process exited with status 255, cmd error: Huawei system initialization\nERROR:Can't get hole memory!!\n time 0.08 (ms).\nERROR:Can't get hole memory!!\n time 0.07 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\n", "__stage__": "OnSyncConfigComplete", "__status__": "error" }, "stage": "OnSyncConfigComplete" }, "__stage__": "OnPrepareComplete", "__status__": "error", "__task_name__": "BaremetalPrepareTask" } 


三段报错都指向内存（空间）分配遇到问题，/lib/mos/sysinit.sh初始化脚本执行失败

**Comment by zexi** [comment]
> @zexi 你好这个是什么原因 ![image](https://private-user-images.githubusercontent.com/112455646/335533789-2ad3109b-71df-4555-804b-005b3a04098a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA5MDIsIm5iZiI6MTcxNzE1MDYwMiwicGF0aCI6Ii8xMTI0NTU2NDYvMzM1NTMzNzg5LTJhZDMxMDliLTcxZGYtNDU1NS04MDRiLTAwNWIzYTA0MDk4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTJiMDU1YmI3NjA5OTAwMmFhZTE0MmNlMWEzOWJiYTU3YzEyZmJhYmNjZTYyNDNlOTlmOGJiY2E1YTE5ZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iGZ9uSp5qzNHzvroBV645_m18nc3DolZvgq4RJMHpVI)
> 
> prepare=>prepare_fail: {"**reason**":"Do deploy: run /lib/mos/sysinit.sh: "/lib/mos/sysinit.sh" error: Process exited with status 255, cmd error: Huawei system initialization\nERROR:Can't get hole memory!!\n time 0.08 (ms).\nERROR:Can't get hole memory!!\n time 0.07 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\n","**stage**":"OnSyncConfigComplete","**status**":"error"} run /lib/mos/sysinit.sh: "/lib/mos/sysinit.sh" error: Process exited with status 255, cmd error: Huawei system initialization ERROR:Can't get hole memory!! time 0.08 (ms). ERROR:Can't get hole memory!! time 0.07 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). ERROR:Can't get hole memory!! time 0.06 (ms). { "**reason**": { "reason": { "**reason**": "Do deploy: run /lib/mos/sysinit.sh: "/lib/mos/sysinit.sh" error: Process exited with status 255, cmd error: Huawei system initialization\nERROR:Can't get hole memory!!\n time 0.08 (ms).\nERROR:Can't get hole memory!!\n time 0.07 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\nERROR:Can't get hole memory!!\n time 0.06 (ms).\n", "**stage**": "OnSyncConfigComplete", "**status**": "error" }, "stage": "OnSyncConfigComplete" }, "**stage**": "OnPrepareComplete", "**status**": "error", "**task_name**": "BaremetalPrepareTask" }
> 
> 三段报错都指向内存（空间）分配遇到问题，/lib/mos/sysinit.sh初始化脚本执行失败

@NeckC 没有遇到过这个问题，感觉和你的服务器硬件有关系。
可以执行下面的命令登录到机器里面：
```bash
climc host-ssh $物理机id
```

然后执行下面的命令看下是在哪个命令报错？
```bash
sh -x /lib/mos/sysinit.sh
```

**Comment by NeckC** [comment]
@zexi 
![image](https://github.com/yunionio/cloudpods/assets/112455646/abf86713-042c-42ab-b6be-0e5b318a69d5)

已在目标主机上执行sysinit.sh，发现里面包含的6条命令结果都是can't get hole memory，应该是虚拟系统本身没获取到内存空间或是没权限导致的执行命令失败，在出入free -g 可以看到我的足额内存（64G），在df -h也是正常显示32G空间；请问接下来该怎么排查这个问题

**Comment by zexi** [comment]
> @zexi ![image](https://private-user-images.githubusercontent.com/112455646/336025447-abf86713-042c-42ab-b6be-0e5b318a69d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDQzMzUsIm5iZiI6MTcxNzc0NDAzNSwicGF0aCI6Ii8xMTI0NTU2NDYvMzM2MDI1NDQ3LWFiZjg2NzEzLTA0MmMtNDJhYi1iNmJlLTBlNWIzMThhNjlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwNzA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjE4YmQzYmEwMDU3Y2VhYTUwMzc4ZjQzMDNhOGFjMWZiYWU3ZTRhNDJlOGVkMzBjZmVmOTFmMjhhMmNiYzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKPWNYsexIzVQOIb4m4r9xxmdGGl4DO2LFEUuoQ9ZUs)
> 
> 已在目标主机上执行sysinit.sh，发现里面包含的6条命令结果都是can't get hole memory，应该是虚拟系统本身没获取到内存空间或是没权限导致的执行命令失败，在出入free -g 可以看到我的足额内存（64G），在df -h也是正常显示32G空间；请问接下来该怎么排查这个问题

@NeckC `sh -x /lib/mos/oem/huawei.sh` 看下是调用哪个命令报错失败了？
