### ISSUE TITLE
[求助/Help] 虚拟机重启后无法进入

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#20341]
![image](https://github.com/yunionio/cloudpods/assets/98650340/0ec37f98-2a99-4357-8a5d-1fe249b7a30e)
如图，这台虚拟机直通了三张gpu，开始是能进去的，重启一下虚拟机就这样了。

**Comment by wanyaoqi** [comment]
@DSYZayn 透传设备设置成 GPU-VGA 设备了吗? ip 地址能通吗

**Comment by DSYZayn** [comment]
@wanyaoqi 是GPU-HPC设备状态，ip地址通不了。解绑透传设备后重启可以正常进入。

**Comment by DSYZayn** [comment]
@wanyaoqi 这个问题仍然存在
![image](https://github.com/user-attachments/assets/a0ddc161-3061-4c34-8d20-fefde03c34ac)
![image](https://github.com/user-attachments/assets/cabbc3de-cd5f-496d-9df6-aff010479a01)

**Comment by wanyaoqi** [comment]
@DSYZayn 可以看下虚机的启动日志，文件路径：/opt/cloud/workspace/servers/logs/<GUEST_ID>
猜测可能是qemu 的 BIOS 无法引导你的GPU设备，可以试试换个 UEFI 引导的镜像。
或者到宿主机上dump 一份 gpu rom 并且修改启动虚机脚本（需要对虚机如何启动有一定了解），如何dump gpu rom 可以参考https://clayfreeman.github.io/gpu-passthrough/#imaging-the-gpu-rom

**Comment by DSYZayn** [comment]
@wanyaoqi 换成debian10后可以进入并安装gpu驱动及cuda。不准备折腾ubuntu22.04平台了，谢谢回复😊。

**Comment by wanyaoqi** [comment]
@DSYZayn 哦是换了宿主机操作系统还是虚机镜像？

**Comment by DSYZayn** [comment]
换了虚拟机镜像，另外宿主机尝试过Ubuntu22.04，感觉体验也是很不友好，总有意想不到的异常，现在几台宿主机都使用debian10。



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/22/2024 16:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [yunionio/cloudpods] [求助/Help] 虚拟机重启后无法进入 (Issue #20341) |

@DSYZayn 哦是换了宿主机操作系统还是虚机镜像？
