### ISSUE TITLE
[求助/Help] 如何更方便的从硬盘备份中恢复出新虚机

### ISSUE THREAD

**Issue by fangpsh** [yunionio/cloudpods#20350]
1. 从硬盘备份中，恢复出一个硬盘，但是无法挂载为 vm 的系统盘使用。
2. 又尝试了，直接下载硬盘备份文件，再将硬盘备份导入到系统镜像中，进行创建虚拟机可以成功。但是这样的链条有点长，不太方便。
3. 目前在创建 vm 页面中，只能从主机备份中创建vm，可否支持直接从硬盘备份中创建？

**Comment by wanyaoqi** [comment]
@fangpsh 这个目前是不支持的，平台是需要镜像和镜像缓存的，方便做后续操作
