### ISSUE TITLE
[求助/Help]控制节点的服务器，在宿主机列表中，存储显示N/A，如何解决

### ISSUE THREAD

**Issue by szz1113-1119** [yunionio/cloudpods#20360]
![image](https://github.com/yunionio/cloudpods/assets/58723494/f6c65401-0a60-446c-a347-60874d395521)

**Comment by zexi** [comment]
@szz1113-1119 请参考这个文档：https://www.cloudpods.org/docs/guides/onpremise/host/troubleshooting
看下对应计算节点的日志，日志里面应该有存储上报失败的原因。
