### ISSUE TITLE
[Feature] 选择zstack集群功能

### ISSUE THREAD

**Issue by FlywinNing** [yunionio/cloudpods#20371]
**What would you like to be added**:
当zstack有多个集群时，cloudpods创建主机无法选择想要的集群，只能创建到默认的集群
请问这个后续版本会支持吗

![image](https://github.com/yunionio/cloudpods/assets/158119314/fd1af0bf-a4ce-4cf5-9faa-a4f57509bfa3)

**Comment by ioito** [comment]
cloudpods没有集群这个概念，暂时不会单独为zstack添加这种模型，后续会根据多数用户反馈做调整。
