### ISSUE TITLE
使用云桌面主机开腾讯会议麦克风声音问题

### ISSUE THREAD

**Issue by zhongyong** [yunionio/cloudpods#20482]
spice的客户端链接cloudpod创建的麒麟的虚拟机开启腾讯会议

3.9.14

1、cloudpod平台由x86和arm的服务器搭建，创建的arm的麒麟云桌面使用spice客户端链接后开启腾讯会议麦克风1-10分钟就无法声音输入。x86麒麟云桌面没有此问题，怀疑是qemu参数问题需要优化。
2、后面尝试uos的的x86和arm的版本，也是arm的版本麦克风输入有问题。

**Comment by swordqiu** [comment]
@zhongyong 经验证qemu 5.0无此现象，我们近期计划升级qemu
