### ISSUE TITLE
[BUG] 在执行qga-command '{"execute":"guest-exec", "arguments":{"path":"ls","capture-output":true}}' 错误。

### ISSUE THREAD

**Issue by Marahann** [yunionio/cloudpods#20491]
**问题描述/What happened**:
在执行qga-command '{"execute":"guest-exec", "arguments":{"path":"ls","capture-output":true}}' 错误。
**环境/Environment**:
centos7.9 cloudpods3.11

**错误定位**:
pkg/hostman/guestman/guesthandlers/guesthandler.go:912

```
func qgaCommand(ctx context.Context, userCred mcclient.TokenCredential, sid string, body jsonutils.JSONObject) (interface{}, error) {
	gm := guestman.GetGuestManager()
	input := computeapi.ServerQgaCommandInput{}
	err := body.Unmarshal(&input)
	if err != nil {
		return nil, httperrors.NewInputParameterError("unmarshal input to ServerQgaCommandInput: %s", err.Error())
	}
	cmdJson, err := jsonutils.ParseString(input.Command)
	if err != nil {
		return nil, httperrors.NewInputParameterError("failed parse qga command")
	}
	qgaCmd := &monitor.Command{}
	err = cmdJson.Unmarshal(qgaCmd)
	if err != nil {
		return nil, httperrors.NewInputParameterError("failed unmarshal qga command")
	}

	return gm.QgaCommand(qgaCmd, sid, input.Timeout)
}
```
***原因***
type Command struct {
	Execute string      `json:"execute"`
	Args    interface{} `json:"arguments,omitempty"`
}
 struct 字段Args  类型是interface{}  在字符串中arguments是对象时，```{xxxx, "arguments":{"path":"ls","capture-output":true}}``` 无法Unmarshal

***建议***
 interface{} => map[string]interface{}

**Comment by wanyaoqi** [comment]
@Marahann 这个问题我们看下

**Comment by wanyaoqi** [comment]
> @Marahann 这个问题我们看下

fixed: https://github.com/yunionio/cloudpods/pull/20505
