### ISSUE TITLE
[求助/Help]VPC和NAT怎么配置才能使虚机能够联网？

### ISSUE THREAD

**Issue by mwqlight** [yunionio/cloudpods#20529]
我的配置如下：
主机是192.168.1.77  vpc 172.16.0.0/16  ip 子网 172.16.1.0-172.16.2.0  怎么操作才能让虚机能够联网  
主机是联网的  我这样配置以后 虚机不能联网 文档里说nat自动开启 
目前联网只能使用和主机共享的网段，也就是二层网络，这就使得虚机只能有253个以下的数量。

**Comment by zexi** [comment]
@mwqlight 宿主机能连外网吗？
