### ISSUE TITLE
高可用部署问题[求助/Help]

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#20527]
OS: openeuler 22.03 sp3 x86
cloudpods： v3.10.8
ocboot版本： v3.10.14
节点安排
controlplane_host:   xxx.xxx.xxx.249 vip
primart_master_node: xxx.xxx.xxx.250
master_nodes:  
                      host1: xxx.xxx.xxx.251
                      host2: xxx.xxx.xx.x252
报错步骤

![image](https://github.com/yunionio/cloudpods/assets/54271145/9f55da93-5a18-4536-9f67-1d52ddc5494c)

现在部署报错，研究半天了发现时etcd 没起来，但是很奇怪 
配置文件我写的是三个master节点 
但是只有 250、251上拉起了etcd
250的etcd报错如下 ，连不上251的etcd
 
![image](https://github.com/yunionio/cloudpods/assets/54271145/dcf89e0e-2bdc-427f-b4c6-5e94b5dc48af)

进入251机器查看etcd 日志，如图下报错，完全没有可用的信息。不知道怎么排查

![image](https://github.com/yunionio/cloudpods/assets/54271145/1fa73c07-14ed-473e-8d6b-ccf82a19ceec)

我理解的是 250作为master的第一个节点，vip首选250，但是 keepalive里面有个 `check_kube` 脚本，检查失败，因为 master1节点的apiserver连不上etcd。 麻烦老师帮忙解惑，这个问题应该如何排查和解决

**Comment by huhaiqwer** [comment]
在执行部署步骤 `Use ocadm join master node` 的时候，master 1 节点上的 `keepalive`服务直接挂了，因为 执行 `check_kube` 脚本的时候，宿主机的apiserver服务无法启动 。

**Comment by huhaiqwer** [comment]
config.yml配置如下
![image](https://github.com/yunionio/cloudpods/assets/54271145/f388a7f8-a8e7-459d-9ffe-ac415d677566)

**Comment by hoganlxj** [comment]
> OS: openeuler 22.03 sp3 x86 cloudpods： v3.10.8 ocboot版本： v3.10.14 节点安排 controlplane_host: xxx.xxx.xxx.249 vip primart_master_node: xxx.xxx.xxx.250 master_nodes: host1: xxx.xxx.xxx.251 host2: xxx.xxx.xx.x252 报错步骤
> 
> ![image](https://private-user-images.githubusercontent.com/54271145/339620685-9f55da93-5a18-4536-9f67-1d52ddc5494c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjA2ODUtOWY1NWRhOTMtNWExOC00NTM2LTlmNjctMWQ1MmRkYzU0OTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjYyMzJmZDU2ZjVjYjkwZjVkM2I4NDllMGFmYWM0MGY5OWViYWQ5NmI3ZmY0M2ZlMGQ0MzlkYjRjODc3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ND_LtMG75XUb-n-eMaw_Odixpw4F6dgWKkyGf1SCAak)
> 
> 现在部署报错，研究半天了发现时etcd 没起来，但是很奇怪 配置文件我写的是三个master节点 但是只有 250、251上拉起了etcd 250的etcd报错如下 ，连不上251的etcd
> 
> ![image](https://private-user-images.githubusercontent.com/54271145/339620212-dcf89e0e-2bdc-427f-b4c6-5e94b5dc48af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjAyMTItZGNmODllMGUtMmJkYy00MjdmLWI0YzYtNWU5NGI1ZGM0OGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDZkNTZkNDYxYTFkNGE1ZDBmNTc4MDhkZTc0MjgwZTcyMTMyNTAxMDZlMzA3MGI1OTVjYjc1YjBhODhhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-pxFBVXuYESu_81cveF1fpwIsjp0Kk7n1k2CbmJvrH0)
> 
> 进入251机器查看etcd 日志，如图下报错，完全没有可用的信息。不知道怎么排查
> 
> ![image](https://private-user-images.githubusercontent.com/54271145/339620353-1fa73c07-14ed-473e-8d6b-ccf82a19ceec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjAzNTMtMWZhNzNjMDctMTRlZC00NzNlLThkNmItY2NmODJhMTljZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOTIyYmVlYWEzZjRkMzVjZjcyNzAzZDNkN2Y1MDRiZGUwMGM3YmM5NDliZjI3ODJkMDAyOWRkZjVkOGI4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZEd0VQX4lKXbPiKV13JtIxoagNPAnFmwIhsZJEVdex0)
> 
> 我理解的是 250作为master的第一个节点，vip首选250，但是 keepalive里面有个 `check_kube` 脚本，检查失败，因为 master1节点的apiserver连不上etcd。 麻烦老师帮忙解惑，这个问题应该如何排查和解决

看着是hostname 有问题，可以修改下，重新部署
卸载命令如下，3台节点都要执行
```bash
kubeadm reset -f
/opt/yunion/bin/ocadm reset -f
rm -rf /etc/kubernetes/ \
        /var/lib/etcd/ \
        /root/.kube \
        /etc/yunion/
reboot
```

**Comment by huhaiqwer** [comment]
> > OS: openeuler 22.03 sp3 x86 cloudpods： v3.10.8 ocboot版本： v3.10.14 节点安排 controlplane_host: xxx.xxx.xxx.249 vip primart_master_node: xxx.xxx.xxx.250 master_nodes: host1: xxx.xxx.xxx.251 host2: xxx.xxx.xx.x252 报错步骤
> > ![image](https://private-user-images.githubusercontent.com/54271145/339620685-9f55da93-5a18-4536-9f67-1d52ddc5494c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjA2ODUtOWY1NWRhOTMtNWExOC00NTM2LTlmNjctMWQ1MmRkYzU0OTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjYyMzJmZDU2ZjVjYjkwZjVkM2I4NDllMGFmYWM0MGY5OWViYWQ5NmI3ZmY0M2ZlMGQ0MzlkYjRjODc3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ND_LtMG75XUb-n-eMaw_Odixpw4F6dgWKkyGf1SCAak)
> > 现在部署报错，研究半天了发现时etcd 没起来，但是很奇怪 配置文件我写的是三个master节点 但是只有 250、251上拉起了etcd 250的etcd报错如下 ，连不上251的etcd
> > ![image](https://private-user-images.githubusercontent.com/54271145/339620212-dcf89e0e-2bdc-427f-b4c6-5e94b5dc48af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjAyMTItZGNmODllMGUtMmJkYy00MjdmLWI0YzYtNWU5NGI1ZGM0OGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDZkNTZkNDYxYTFkNGE1ZDBmNTc4MDhkZTc0MjgwZTcyMTMyNTAxMDZlMzA3MGI1OTVjYjc1YjBhODhhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-pxFBVXuYESu_81cveF1fpwIsjp0Kk7n1k2CbmJvrH0)
> > 进入251机器查看etcd 日志，如图下报错，完全没有可用的信息。不知道怎么排查
> > ![image](https://private-user-images.githubusercontent.com/54271145/339620353-1fa73c07-14ed-473e-8d6b-ccf82a19ceec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwMDQsIm5iZiI6MTcxODM1NzcwNCwicGF0aCI6Ii81NDI3MTE0NS8zMzk2MjAzNTMtMWZhNzNjMDctMTRlZC00NzNlLThkNmItY2NmODJhMTljZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOTIyYmVlYWEzZjRkMzVjZjcyNzAzZDNkN2Y1MDRiZGUwMGM3YmM5NDliZjI3ODJkMDAyOWRkZjVkOGI4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZEd0VQX4lKXbPiKV13JtIxoagNPAnFmwIhsZJEVdex0)
> > 我理解的是 250作为master的第一个节点，vip首选250，但是 keepalive里面有个 `check_kube` 脚本，检查失败，因为 master1节点的apiserver连不上etcd。 麻烦老师帮忙解惑，这个问题应该如何排查和解决
> > ![image](https://private-user-images.githubusercontent.com/32036395/339722622-36b01b08-4645-4f37-866b-bed1681affad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDc5MjQsIm5iZiI6MTcxODYwNzYyNCwicGF0aCI6Ii8zMjAzNjM5NS8zMzk3MjI2MjItMzZiMDFiMDgtNDY0NS00ZjM3LTg2NmItYmVkMTY4MWFmZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA3MDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OGYwMjY0NDIyM2EzMTdiZjk2YWZlMzkyOGEwMWI1ODU4NTUwMTU1MTcyMmZlNzBkYjYxMGEzODhkZDBiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ahmde5oaPjo42T7bh-33VicD2EcQ7zEfbWtsRm9ZqrU)
> 
> 看着是hostname 有问题，可以修改下，重新部署 卸载命令如下，3台节点都要执行
> 
> ```shell
> kubeadm reset -f
> /opt/yunion/bin/ocadm reset -f
> rm -rf /etc/kubernetes/ \
>         /var/lib/etcd/ \
>         /root/.kube \
>         /etc/yunion/
> reboot
> ```

接上次的问题 三个几点 有一个几点一直加不进集群 这边看 好像是kubelet.conf文件没有写入到节点中，部署流程一直卡在这里 
![image](https://github.com/yunionio/cloudpods/assets/54271145/78ebee6e-b7e3-45a3-8611-d0356460c25e)

252那台机器无法加入到集群，我可以手动尝试一下 手动创建config.yaml文件


![image](https://github.com/yunionio/cloudpods/assets/54271145/700599e4-40c6-4304-ba98-4c62f584e1bc)

**Comment by huhaiqwer** [comment]
删除 所有节点/var/lib/kubelet 后  清除环境 可以部署了 感谢大佬的支持
