### ISSUE TITLE
[求助/Help] 关于宿主机 NAT功能的请教

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#20545]
你好,
最新版是否有可关闭宿主机 NAT 功能, 使得vpc网络完全隔离, 只能通过 EIP 链接外网的功能?

**Comment by swordqiu** [comment]
@saltfishh 可以修改vpc的 external_access_mode 属性为eip实现这个效果

```bash
climc vpc-update --external-access-mode eip <vpc_id>
```

**Comment by saltfishh** [comment]
感谢回复

**Comment by saltfishh** [comment]
诶, 能否全局配置这个功能? 上面提供的命令貌似要创建vm后才可以执行.

**Comment by swordqiu** [comment]
@saltfishh 

```
climc service-config-edit region2
```
有一个参数 

default_vpc_external_access_mode: "eip"

可以设置新建的vpc的默认 external_access_mode

不知道是否可以解决你的问题？

**Comment by saltfishh** [comment]
感谢!
