### ISSUE TITLE
[Feature] 火山引擎 ECS 云主机 ”节省停机“ 功能支持

### ISSUE THREAD

**Issue by zhenrong-wang** [yunionio/cloudpods#20579]
**What would you like to be added**:

火山引擎 ECS 云主机支持 ”节省停机“ 功能，即 ”关机不收费“ 功能。但是目前在 Cloudpods 页面的主机关机时暂无这个选项。如下图所示：

![96219ff5124eba64a5fd163c6861425](https://github.com/yunionio/cloudpods/assets/59274212/15ee016e-a374-4002-9d96-5b621887aef6)

希望能支持该功能。

API 参考文档： https://www.volcengine.com/docs/6396/70468

**Comment by ioito** [comment]
刚看了下，后端本身是支持的，前端需要合并 https://github.com/yunionio/dashboard/pull/6733 后支持

**Comment by zhenrong-wang** [comment]
好的，感谢回复！期待这个 Feature 上线。

**Comment by zhenrong-wang** [comment]
@ioito  我看这个 PR 已经 merge 了，请问如何更新到我们的部署上呢？ 是我们要自己 build dashboard 吗？ 还是说等新版本发布之后一并更新？

**Comment by ioito** [comment]
> @ioito 我看这个 PR 已经 merge 了，请问如何更新到我们的部署上呢？ 是我们要自己 build dashboard 吗？ 还是说等新版本发布之后一并更新？

都可以

**Comment by zhenrong-wang** [comment]
> > @ioito 我看这个 PR 已经 merge 了，请问如何更新到我们的部署上呢？ 是我们要自己 build dashboard 吗？ 还是说等新版本发布之后一并更新？
> 
> 都可以

好的，预计该功能会包含在 3.11.4 版本中吗？

**Comment by dengju2020** [comment]
会。月底前发布 @zhenrong-wang

**Comment by zhenrong-wang** [comment]
> 会。月底前发布 @zhenrong-wang 
> 

好的，非常感谢！
