### ISSUE TITLE
[求助/Help]纳管VMware 虚拟机

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20604]
我遇到了一个 纳管vware 虚拟机的 问题， 是通过 手动搭建平台环境的 部署在centos上，目前部署了apigateway ,  keystone,  region，  scheduledtask ， scheduler，  yunionconf
![image](https://github.com/yunionio/cloudpods/assets/20590260/3a54e27c-ea49-4235-96e1-f582458e84f8)
但是 同步 vmware 不成功，
请问还要部署哪些服务
后台报错日志如下：
[E 2024-06-20 15:09:53 logclient.(*logTask).Run(logclient.go:250)] create action log {"action":"update_status","domain":"Default","domain_id":"default","ip":"10.0.53.235","is_system_account":false,"notes":"sync_network=>sync_net_failed: sync network failed","obj_id":"d22e5956-fe80-4dcf-8a7f-17ad53a7fd5f","obj_name":"iit_vmware_test","obj_type":"cloudaccount","owner_domain_id":"default","project_domain":"Default","project_domain_id":"default","roles":"admin","service":"compute","severity":"ERROR","success":false,"tenant":"system","tenant_id":"4d018b26d11c4dfa8a5a2faf6b35c682","user":"admin","user_id":"e6df17fa1368427e84769ac578623fba"} failed GetServiceVersionURLs: catalog.GetServiceURLs: No such service log: NotFoundError
[E 2024-06-20 15:09:53 logclient.(*logTask).Run(logclient.go:250)] create action log {"action":"sync_network","domain":"Default","domain_id":"default","ip":"10.0.53.235","is_system_account":false,"notes":"{\"error\":\"fail to find zone of esxi: no valid on-premise zone: NotFoundError\"}","obj_id":"d22e5956-fe80-4dcf-8a7f-17ad53a7fd5f","obj_name":"iit_vmware_test","obj_type":"cloudaccount","owner_domain_id":"default","project_domain":"Default","project_domain_id":"default","roles":"admin","service":"compute","severity":"ERROR","start_time":"2024-06-20T07:09:53.000000Z","success":false,"tenant":"system","tenant_id":"4d018b26d11c4dfa8a5a2faf6b35c682","user":"admin","user_id":"e6df17fa1368427e84769ac578623fba"} failed GetServiceVersionURLs: catalog.GetServiceURLs: No such service log: NotFoundError

**Comment by ioito** [comment]
climc zone-list 看下，如果没有zone, 需要climc zone-create 创建一个

**Comment by ollylu** [comment]
[root@localhost cloudpods]# climc zone-list
***  Total: 0  ***

**Comment by ollylu** [comment]
[root@localhost cloudpods]# climc zone-create esxi
+--------------------+--------------------------------------+
|       Field        |                Value                 |
+--------------------+--------------------------------------+
| baremetals         | 0                                    |
| baremetals_enabled | 0                                    |
| can_delete         | true                                 |
| can_update         | true                                 |
| cloudregion        | Default                              |
| cloudregion_id     | default                              |
| created_at         | 2024-06-20T07:25:25.000000Z          |
| deleted            | false                                |
| hosts              | 0                                    |
| hosts_enabled      | 0                                    |
| id                 | 7a21b9e1-848e-407d-803d-321dc95e8d44 |
| imported_at        | 2024-06-20T07:25:25.000000Z          |
| is_emulated        | false                                |
| name               | esxi                                 |
| networks           | 0                                    |
| progress           | 100                                  |
| provider           | OneCloud                             |
| region             | Default                              |
| region_id          | default                              |
| source             | local                                |
| status             | enable                               |
| storages           | 0                                    |
| update_version     | 0                                    |
| updated_at         | 2024-06-20T07:25:25.000000Z          |
| wires              | 0                                    |
+--------------------+--------------------------------------+

**Comment by ioito** [comment]
esxi-agent

**Comment by ollylu** [comment]
我启动 esxi-agent  后它一直报错 br0网络接口找不到，请问这个agent是需要部署到 vmware 服务所在的机器吗，还是 cloudpods 集群内一台机器即可
[I 2024-06-20 14:46:49 appsrv.(*Application).SetDefaultTimeout(appsrv.go:137)] adjust application default timeout to 60.000000 seconds
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/log.Fatalf({0x1afb502, 0x15}, {0xc000961e18, 0x1, 0x1})
	/data/coding-build/tools/jenkins_home/workspace/8647-cci-1502875-434266/vendor/yunion.io/x/log/log.go:138 +0x32
yunion.io/x/onecloud/pkg/esxi/service.(*SExsiAgentService).startAgent(0x0?, 0x1bc04d8?)
	/data/coding-build/tools/jenkins_home/workspace/8647-cci-1502875-434266/pkg/esxi/service/esxi_agent_service.go:93 +0x59
yunion.io/x/onecloud/pkg/esxi/service.(*SExsiAgentService).StartService(0xc000571f70?)
	/data/coding-build/tools/jenkins_home/workspace/8647-cci-1502875-434266/pkg/esxi/service/esxi_agent_service.go:83 +0x497
main.main()
	/data/coding-build/tools/jenkins_home/workspace/8647-cci-1502875-434266/cmd/esxi-agent/main.go:30 +0xb6
[F 2024-06-20 14:46:49 service.(*SExsiAgentService).startAgent(esxi_agent_service.go:93)] Start agent error: WaitIfaceIps: net.InterfaceByName br0: route ip+net: no such network interface

**Comment by ioito** [comment]
只要和region及vmware环境网络相通就行，配置文件中网口br0改成你的网卡名

**Comment by ollylu** [comment]
我该为本机的网卡后，可以启动了，单一直报错如下，请问这个什么原因
[E 2024-06-20 15:43:12 agent.(*SBaseAgent).startRegister(agent.go:121)] Register error: Not found networks by agent listen ip: 172.16.18.242, retry after 30s...
![image](https://github.com/yunionio/cloudpods/assets/20590260/e35e30f8-b60a-42ea-aef2-fa3e96c48465)

**Comment by ioito** [comment]
需要在平台上创建子网，子网范围要包含 172.16.18.242

**Comment by ollylu** [comment]
谢谢解答！ 麻烦大致解释下原因可以吗，然后 “在平台上创建子网” 有步骤吗

**Comment by ollylu** [comment]
请问是在这里创建吗
![image](https://github.com/yunionio/cloudpods/assets/20590260/c41f65f0-1c8d-4bf9-9272-e55c013b07bf)

**Comment by ioito** [comment]
注册要平台认可，也好管理，是的

**Comment by ollylu** [comment]
按你的说明我设置了，您看下我理解的对吗，它不会调度VM虚拟机到我的集群地址上吧
![image](https://github.com/yunionio/cloudpods/assets/20590260/f5cc0626-6a03-4a3b-95f9-5359a092ad5c)

**Comment by ioito** [comment]
你要创建个 172.16.18.242/32的 物理机 类型的子网，它就单独注册到这个子网底下

**Comment by ollylu** [comment]
好的，谢谢！
假如我的平台有多个域，需要为每个域 都设置  172.16.18.242/32的 物理机 类型的子网 吗？
另外可以是一个网段吗，例如172.16.18.1 ---- 172.16.18.242？

**Comment by ioito** [comment]
只设置一个子网就行，可以是网段

**Comment by ollylu** [comment]
好的 谢谢 问题解决

**Comment by jackgao2015** [comment]
> 好的 谢谢 问题解决

你好，如果问题已经解决，可以把issue关闭哈
