### ISSUE TITLE
[求助/Help]同步AWS 云用户账号不成功

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20612]
如下图 同步 AWS的云用户不成功
![image](https://github.com/yunionio/cloudpods/assets/20590260/3fdfa0a5-2eeb-4932-b11c-1ff20e4ef19b)

我已经给云账号加了这些权限
![image](https://github.com/yunionio/cloudpods/assets/20590260/d1efcc50-dac7-4ca0-ab57-eb6b2786c7b8)

请问是什么原因

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/63c0d3f0-d313-4bf8-9991-b2203eed20f1)

**Comment by ollylu** [comment]
我的环境是手动部署的，加了 keystone, region, apigateway，yunconf 这些模块，是有什么功能缺失吗，基于3.11版本编译的

**Comment by ioito** [comment]
云用户是cloudid服务

**Comment by ollylu** [comment]
好的 我先部署下，配置和其他服务类似吧

**Comment by ollylu** [comment]
你好。我启动 cloudid 报错了 似乎是需要证书吗，这个如何配置
[E 2024-06-21 12:44:36 service.StartService(service.go:72)] SAML initialization fail initSAMLInstance: Missing ssl-certfile: InputParameterError

这是我的启动命令
./cloudid --conf /etc/yunion/cloudid.conf

配置如下
region = 'Yunion'
address = '127.0.0.1'
port = 8690
auth_uri = 'http://127.0.0.1:35357/v3'
admin_user = 'cloudidadmin'
admin_password = 'cloudid@admin'
admin_tenant_name = 'system'
sql_connection = 'mysql+pymysql://cloudid:cloudpods-cloudid@127.0.0.1:3306/cloudid?charset=utf8'
log_level = 'debug'
auto_sync_table = true

**Comment by ollylu** [comment]
从代码来看 这个要加证书吗，如何配置

![image](https://github.com/yunionio/cloudpods/assets/20590260/15154368-c183-4646-8d38-fd5c7c86d229)

**Comment by ioito** [comment]
enable_ssl = true
ssl_certfile = '/xxxx/xxxx/xxxxservice.crt'
ssl_keyfile = '/xxx/xxx/xxx/service.key'
ssl_ca_certs = '/xxx/xxx/xxxca.crt'
配置这几个参数，证书需要自己生成，另外创建cloudid的endpoint要用到https

**Comment by ollylu** [comment]
按 您的建议我配置了自签名证书，然后重新启动，报错了，麻烦帮看下什么原因
[E 2024-06-21 14:33:56 service.StartService(service.go:72)] SAML initialization fail initSAMLIdp: read file /opt/yunion/share/saml/sp-metadata/gcp.xml fail: open /opt/yunion/share/saml/sp-metadata/gcp.xml: no such file or directory

**Comment by ollylu** [comment]
似乎是这段代码报错，难道要配置 ：options.Options.CloudSAMLMetadataPath, driver.GetMetadataFilename() 吗
![image](https://github.com/yunionio/cloudpods/assets/20590260/7b5ce087-98bc-40dd-9f57-8d311435e799)

**Comment by ollylu** [comment]
gcp.xml 似乎是google用的？ 我的是 AWS

**Comment by ioito** [comment]
需要创建 /opt/yunion/share/saml/sp-metadata/ 目录

**Comment by ollylu** [comment]
我创建这个目录后看到 有文件下载下来了
但似乎没有下载gcp.xml 还是报错
gcp.xml
![Uploading image.png…]()

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/3144aa51-d75b-4492-a0b6-f87db7a3f4de)

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/a0daea3a-4608-483f-99fe-6f591d01ccca)

**Comment by ollylu** [comment]
google的下载地址没有提供吗 。。。

**Comment by ollylu** [comment]
这是一个BUG吗

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/dd232fc0-460e-4609-a7d5-64176c27e227)
 我把 这个注册地址去掉后似乎OK了，尽然跑起来了，这样OK吗

**Comment by ioito** [comment]
不算，我们正常打包镜像时，会自动加入这个xml

**Comment by ollylu** [comment]
但是 还是没有同步到云用户，请问是什么原因
![image](https://github.com/yunionio/cloudpods/assets/20590260/859d244d-096d-4743-a7be-3f909aa80be5)
![image](https://github.com/yunionio/cloudpods/assets/20590260/93d7eb9c-bab0-4fd5-871b-e302adbae5f0)

**Comment by ollylu** [comment]
这条报错只是界面查询请求报错吧，其他的报错我没看到，请问什么原因导致还是没同步成功，还是缺少了模块，配置吗
[E 2024-06-21 14:56:54 httperrors.HTTPError(httperrors.go:110)] Send error ListItems: listItemQueryFiltersRaw: ListItemFilter: {"error":{"class":"ResourceNotFoundError","code":404,"data":{"fields":["cloudaccount","de7cadd5-deb0-4a1b-89fd-22c094fc2e28"],"id":"%!s(MISSING) %!s(MISSING) not found"},"details":"cloudaccount de7cadd5-deb0-4a1b-89fd-22c094fc2e28 not found"}}

**Comment by ollylu** [comment]
按我理解： cloudid 服务，调用scheduledtask服务启用云账号同步任务是吗， 需要使用etcd 吗，我自己搭建的集群没有部署 etcd应该不会影响 云用户同步吧

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/ec44f2fe-82eb-4181-8011-435390eef16c)
 这张表是空的没有同步到account 信息 ，所以导致没有同步，如何把信息导入呢

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/8d2b3360-f04b-449c-b58e-48bc7d0d5344)
看这段代码要先到这张表那账户信息来同步？

**Comment by ioito** [comment]
同步账号信息依赖etcd

**Comment by ollylu** [comment]
好的 etcd 有 配置，接入指导吗 ，我尝试配置下

**Comment by ioito** [comment]
没有配置，安装好，别加密，设好endpoint就行

**Comment by ollylu** [comment]
就是 默认2379端口是吧

**Comment by ioito** [comment]
任意指定都行，endpoint创建能对应起来就行

**Comment by ollylu** [comment]
按您的建议 我已经部署ETCD了 但m目前这几张表还是没有同步到用户信息，请问还有缺失的模块吗
![image](https://github.com/yunionio/cloudpods/assets/20590260/90ed2c98-5c71-4bc6-9b93-e29bfa08b93e)

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/356e654b-373c-43ee-943e-c0e4e23b05d1)
 此外我的Tab页没有用户 页面

**Comment by ollylu** [comment]
是否还有由于少了模块，目前我部署了 ：keystone, apigatway, region, cloudid, scheduledtask , schedule, etcd, yunconf

**Comment by ioito** [comment]
启用禁用一次云账号试试

**Comment by ollylu** [comment]
嗯。用户数据同步了 ！谢谢
多问一个问题，region 模块，与cloudid 模块之间的交互逻辑是怎样的，能简短描述下吗
这是我的理解，请问正确吗：
region同步云资源/账户数据到 ETCD， 然后 cloudid从ETCD读取这部分数据，保存到数据库，然后cloudid负责具体用户操作？
