### ISSUE TITLE
[求助/Help] ecs如何调用到cloudmux的CreateVm方法

### ISSUE THREAD

**Issue by xzzdhq** [yunionio/cloudpods#20611]
现在是看到了cloudmux项目里面， 理解 创建ecs的方法是  ICloudHost.CreateVM 这个方法，

然后追调用链路，应该是 
SManagedVirtualizedGuestDriver.RequestDeployGuestOnHost  ->
SManagedVirtualizedGuestDriver.RemoteDeployGuestForCreate ->
 ICloudHost.CreateVM 

但是，实在是找不到 从  ecs的页面新建接口的   SGuestManager.OnCreateComplete 方法 
进入到  GuestBatchCreateTask 这个task 里面， 
然后这个task 最后是怎么调用到   ICloudHost.CreateVM  这个方法的，有了解的大佬 可以写下代码的调用链路嘛，非常感谢

![image](https://github.com/yunionio/cloudpods/assets/70850653/eaa4f063-f567-49bd-81a4-d68607aaf962)

![image](https://github.com/yunionio/cloudpods/assets/70850653/dac845a4-52ac-48f7-9185-8c8a1eb4133f)
![image](https://github.com/yunionio/cloudpods/assets/70850653/72161982-bbbb-49e3-a973-a2a980dff3a5)

**Comment by ioito** [comment]
pkg/compute/tasks/guest_batch_create_task.go  guest.StartGuestCreateTask -> 
pkg/compute/tasks/guest_create_task.go guest.StartGuestDeployTask -> 
pkg/compute/tasks/guest_deploy_task.go drv.RequestDeployGuestOnHost -> 
ICloudHost.CreateVM

**Comment by xzzdhq** [comment]
感谢屈神
