### ISSUE TITLE
对接多个vmware,每个项目管理一个vmware,项目管理员创建虚拟机的时候，可以选择其他项目下面云账号的系统镜像，而且选择其他项目镜像，可以直接在其他项目管理的资源下面创建虚拟机

### ISSUE THREAD

**Issue by jinteng123** [yunionio/cloudpods#20628]
版本 3.11
![image](https://github.com/yunionio/cloudpods/assets/22409094/87ee077e-913f-4ecd-897a-166039fa90e8)

**Comment by ioito** [comment]
麻烦截图下项目管理员的权限信息

**Comment by jinteng123** [comment]
> 麻烦截图下项目管理员的权限信息

![图片](https://github.com/yunionio/cloudpods/assets/22409094/b9ffe9b8-e1f6-4f55-90bb-ab046f7ed247)

**Comment by ioito** [comment]
目前服务会默认添加云订阅及镜像的权限，可以移除以下代码重新编译region镜像替换服务试下
https://github.com/yunionio/cloudpods/blob/dd49b1e5a65e712f42297c6883adb550c743c2d6/pkg/compute/policy/defaults.go#L64-L75
https://github.com/yunionio/cloudpods/blob/dd49b1e5a65e712f42297c6883adb550c743c2d6/pkg/compute/policy/defaults.go#L215-L238
