### ISSUE TITLE
[求助/Help] 关于同时纳管公有云资源 & vmware虚拟机资源的部署方案

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20654]
你好，我们在使用开源社区版cloudpod 测试部署时遇到一个问题
我们需要同时 纳管公有云资源 & vmware虚拟机资源，我们希望一套平台，分布式部署，将“云上数据”，保存在云上数据库， vmware虚拟机资保存在私有内网，请问能否实现，部署方案时怎样的

**Comment by ollylu** [comment]
是否可以启动2个region服务，一个在公有云，一个在内网 分别纳管 公有云，和 vmware虚拟资源数据？

**Comment by ollylu** [comment]
我希望云上的资源数据保存在云上，内网的资源数据保存在内网，有什么部署方案吗

**Comment by hoganlxj** [comment]
> 你好，我们在使用开源社区版cloudpod 测试部署时遇到一个问题 我们需要同时 纳管公有云资源 & vmware虚拟机资源，我们希望一套平台，分布式部署，将“云上数据”，保存在云上数据库， vmware虚拟机资保存在私有内网，请问能否实现，部署方案时怎样的
这个云上数据，能具体说下？
vmware虚拟机资保存在私有内网 -- 这个是指？

**Comment by ollylu** [comment]
例如 我们云上的EC2资源，需要纳管到平台
我们公司内部 虚拟机资源也要纳管
我们希望有2个数据库独立保存这2部分资源信息

**Comment by ollylu** [comment]
简单说我们希望用2个数据库 
一个保存 云上资源信息（EC2，RDS....用户，，，等等）
一个保存 vmware虚拟机 资源信息（虚拟机，磁盘，等等）

**Comment by hoganlxj** [comment]
> 简单说我们希望用2个数据库 一个保存 云上资源信息（EC2，RDS....用户，，，等等） 一个保存 vmware虚拟机 资源信息（虚拟机，磁盘，等等）

目前不支持这种场景 部署
