### ISSUE TITLE
[求助/Help]使用Docker Compose部署Cloudpods多云版本报错

### ISSUE THREAD

**Issue by wangdepeng** [yunionio/cloudpods#20657]
使用Docker Compose部署Cloudpods多云版本时，执行docker compose up报错：
yaml: line 50: could not find expected ':'

环境：
操作系统：CentOS Linux release 7.9.2009 (Core)
Docker版本：
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:32:04 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:31:02 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by hoganlxj** [comment]
> 使用Docker Compose部署Cloudpods多云版本时，执行docker compose up报错： yaml: line 50: could not find expected ':'
> 
> 环境： 操作系统：CentOS Linux release 7.9.2009 (Core) Docker版本： Client: Docker Engine - Community Version: 26.1.4 API version: 1.45 Go version: go1.21.11 Git commit: 5650f9b Built: Wed Jun 5 11:32:04 2024 OS/Arch: linux/amd64 Context: default
> 
> Server: Docker Engine - Community Engine: Version: 26.1.4 API version: 1.45 (minimum version 1.24) Go version: go1.21.11 Git commit: de5c9cf Built: Wed Jun 5 11:31:02 2024 OS/Arch: linux/amd64 Experimental: false containerd: Version: 1.6.33 GitCommit: d2d58213f83a351ca8f528a95fbd145f5654e957 runc: Version: 1.1.12 GitCommit: v1.1.12-0-g51d5e94 docker-init: Version: 0.19.0 GitCommit: de40ad0

提示yaml文件格式有问题，看下docker-compose.yml 文件 50行是什么？

**Comment by wangdepeng** [comment]
按照 https://www.cloudpods.org/docs/getting-started/cmp/quickstart-docker-compose 这个文档操作的。
第50行的内容：
<<<<<<< HEAD:compose/docker-compose.yml

**Comment by zexi** [comment]
> 按照 https://www.cloudpods.org/docs/getting-started/cmp/quickstart-docker-compose 这个文档操作的。 第50行的内容： <<<<<<< HEAD:compose/docker-compose.yml

@wangdepeng 修复了，拉取最新代码试试。

**Comment by wangdepeng** [comment]
可以执行了。但是执行完之后，打不开页面。日志：
monitor-1                  | [error 2024-06-26 12:31:09 httperrors.HTTPError(httperrors.go:110)] Send error Handler not found
monitor-1                  | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] dxRd4Xtz9IpogGy0bM9Q7tZuY2M= 404 7ff7ab GET /process_stats (172.18.0.8:44872:cloudmon/cron-service) 0.13ms
cloudmon-1                 | [error 2024-06-26 12:31:09 misc.CollectServiceMetrics.func1(system.go:100)] collect service monitor metric error: request: {"error":{"class":"NotFoundError","code":404,"details":"Handler not found","request":{"headers":{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"cloudmon/cron-service","X-Yunion-Remote-Addr":"monitor:30093","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"77a33fa6"},"method":"GET","url":"https://monitor:30093/process_stats"}}}
kubeserver-1               | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] u5PFmq5VSbDQ5-lqTfpGgY9yPxI= 200 f9dd8f GET /api/version (172.18.0.8:45052:cloudmon/cron-service) 0.15ms
kubeserver-1               | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] u5PFmq5VSbDQ5-lqTfpGgY9yPxI= 200 d888f3 GET /api/stats (172.18.0.8:45054:cloudmon/cron-service) 3.19ms
kubeserver-1               | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] u5PFmq5VSbDQ5-lqTfpGgY9yPxI= 200 7c2f47 GET /api/worker_stats (172.18.0.8:45056:cloudmon/cron-service) 0.50ms
kubeserver-1               | [error 2024-06-26 12:31:09 httperrors.HTTPError(httperrors.go:110)] Send error Handler not found
kubeserver-1               | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] u5PFmq5VSbDQ5-lqTfpGgY9yPxI= 404 145264 GET /api/db_stats (172.18.0.8:45058:cloudmon/cron-service) 0.18ms
kubeserver-1               | [error 2024-06-26 12:31:09 httperrors.HTTPError(httperrors.go:110)] Send error Handler not found
kubeserver-1               | [info 2024-06-26 12:31:09 appsrv.(*Application).ServeHTTP(appsrv.go:289)] u5PFmq5VSbDQ5-lqTfpGgY9yPxI= 404 de2dd9 GET /api/process_stats (172.18.0.8:45060:cloudmon/cron-service) 0.13ms
cloudmon-1                 | [error 2024-06-26 12:31:09 misc.CollectServiceMetrics.func1(system.go:100)] collect service k8s metric error: [request: {"error":{"class":"NotFoundError","code":404,"details":"Handler not found","request":{"headers":{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"cloudmon/cron-service","X-Yunion-Remote-Addr":"kubeserver:30442","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"4dbfcf92"},"method":"GET","url":"https://kubeserver:30442/api/db_stats"}}}, request: {"error":{"class":"NotFoundError","code":404,"details":"Handler not found","request":{"headers":{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"cloudmon/cron-service","X-Yunion-Remote-Addr":"kubeserver:30442","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"6db58858"},"method":"GET","url":"https://kubeserver:30442/api/process_stats"}}}]
influxdb-1                 | ts=2024-06-26T12:31:09.699125Z lvl=info msg="Executing query" log_id=0q180EFW000 service=query query="SHOW DATABASES"
influxdb-1                 | [httpd] 172.18.0.8 - - [26/Jun/2024:12:31:09 +0000] "GET /query?db=&epoch=ms&q=SHOW+DATABASES HTTP/1.1" 200 122 "-" "yunioncloud-go/201708" f78c8d3e-33b7-11ef-801d-0242ac120006 249
influxdb-1                 | ts=2024-06-26T12:31:09.699608Z lvl=info msg="Executing query" log_id=0q180EFW000 service=query query="CREATE DATABASE system"
cloudmon-1                 | [error 2024-06-26 12:31:09 misc.CollectServiceMetrics(system.go:111)] collect service metric error: db.Write: Status: 400 Message: {"error":"database is required"}
cloudmon-1                 |
influxdb-1                 | [httpd] 172.18.0.8 - - [26/Jun/2024:12:31:09 +0000] "GET /query?db=&epoch=ms&q=CREATE+DATABASE+system HTTP/1.1" 200 176 "-" "yunioncloud-go/201708" f78ca118-33b7-11ef-801e-0242ac120006 1799
influxdb-1                 | [httpd] 172.18.0.8 - - [26/Jun/2024:12:31:09 +0000] "POST /write?db=&precision=ms HTTP/1.1" 400 33 "-" "yunioncloud-go/201708" f78cf0bb-33b7-11ef-801f-0242ac120006 23
notify-1                   | [info 2024-06-26 12:31:11 models.(*SNotificationManager).ReSend(notification.go:801)] need to resend total 0 notifications
keystone-1                 | [info 2024-06-26 12:31:25 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 3aca3b GET /v3/auth/tokens/invalid (172.18.0.22:40174:scheduler) 4.24ms
keystone-1                 | [info 2024-06-26 12:31:25 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 84ee8c GET /v3/auth/tokens/invalid (172.18.0.20:59906:scheduledtask) 3.97ms
keystone-1                 | [info 2024-06-26 12:31:26 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 7e5952 GET /v3/auth/tokens/invalid (172.18.0.21:52376:esxiagent) 4.41ms
keystone-1                 | [info 2024-06-26 12:31:26 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 aa2e61 GET /v3/auth/tokens/invalid (172.18.0.16:56806:cloudid) 3.90ms
keystone-1                 | [info 2024-06-26 12:31:27 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 5bc502 GET /v3/auth/tokens/invalid (172.18.0.17:59278:monitor) 3.92ms
keystone-1                 | [info 2024-06-26 12:31:27 appsrv.(*Application).ServeHTTP(appsrv.go:289)] jtF8HQ5TySSGuDOYIy0hdpfCuok= 200 4f0e99 GET /v3/auth/tokens/invalid (172.18.0.18:58800:yunionapi) 3.54ms
scheduledtask-1            | [info 2024-06-26 12:31:27 models.(*SScheduledTaskManager).Timer(scheduled_tasks.go:548)] queueSize: 100
scheduler-1                | [info 2024-06-26 12:31:29 schedtag.(*dataManager).syncOnce(sync.go:132)] Schedtag data start sync
scheduler-1                | [info 2024-06-26 12:31:29 schedtag.(*dataManager).syncOnce(sync.go:149)] Schedtag finish sync, elapsed 2.341112ms
scheduler-1                | [info 2024-06-26 12:31:59 schedtag.(*dataManager).syncOnce(sync.go:132)] Schedtag data start sync
scheduler-1                | [info 2024-06-26 12:31:59 schedtag.(*dataManager).syncOnce(sync.go:149)] Schedtag finish sync, elapsed 2.380413ms
notify-1                   | [info 2024-06-26 12:32:11 models.(*SNotificationManager).ReSend(notification.go:801)] need to resend total 0 notifications
scheduledtask-1            | [info 2024-06-26 12:32:27 models.(*SScheduledTaskManager).Timer(scheduled_tasks.go:548)] queueSize: 100
scheduler-1                | [info 2024-06-26 12:32:29 schedtag.(*dataManager).syncOnce(sync.go:132)] Schedtag data start sync
scheduler-1                | [info 2024-06-26 12:32:29 schedtag.(*dataManager).syncOnce(sync.go:149)] Schedtag finish sync, elapsed 6.477822ms
scheduler-1                | [info 2024-06-26 12:32:59 schedtag.(*dataManager).syncOnce(sync.go:132)] Schedtag data start sync
scheduler-1                | [info 2024-06-26 12:32:59 schedtag.(*dataManager).syncOnce(sync.go:149)] Schedtag finish sync, elapsed 2.155149ms

**Comment by zexi** [comment]
@wangdepeng 我这边测试没有问题，浏览器输入 `https://ip` 就能访问前端。如果不行的话，看下 `docker logs compose-web-1` 的日志，或者看看这个容器有没有启动。

**Comment by wangdepeng** [comment]
可以了 是因为网络策略的原因导致的。
