### ISSUE TITLE
[BUG] 负载均衡TCP端口映射通信异常

### ISSUE THREAD

**Issue by yulongz** [yunionio/cloudpods#20661]
**问题描述/What happened**:

通过负载均衡映射了云主机端口到公网IP，在使用的过程中发现不同网络环境下导致云主机连接异常。目前映射的端口为TCP方式，内网端口为22或80端口，都出现了如下问题。
目前已发现并测试的情况如下：
1、客户终端(手机/笔记本/台式机)在手机或手机热点环境下，通过负载均衡地址及端口可正常连接到云主机；
2、客户终端(手机/笔记本/台式机)在宽带环境下 ，通过负载均衡地址及端口无法正常连接到云主机，云主机IP及端口能通但数据不能正常返回。

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): cento7.9
- Kernel (e.g. `uname -a`):5.4.130-1.yn20230805.el7.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
        Manufacturer: Hynix
        Manufacturer: Inspur
        Manufacturer: Intel(R) Corporation
        Manufacturer: LITEON
        Product Name: NF5280M5
        Product Name: YZMB-00882-104
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|     Field     |                                                                                              Value                                                                                              |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ansible       | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| apimap        | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| cloudevent    | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-cloudevent:30892/version\": dial tcp: lookup default-cloudevent on 10.96.0.10:53: no such host","request":{"headers":{ |
|               | "User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-cloudevent:30892/version"}}}                                                                     |
| cloudid       | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-cloudid:30893/version\": dial tcp: lookup default-cloudid on 10.96.0.10:53: no such host","request":{"headers":{"User- |
|               | Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-cloudid:30893/version"}}}                                                                              |
| cloudmon      | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| cloudproxy    | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| compute_v2    | release/3.10(abc4558b2424052209)                                                                                                                                                                |
| devtool       | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| identity      | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| image         | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| k8s           | heads/v3.10.13-20240228.4(5cbfdf9624022900)                                                                                                                                                     |
| log           | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| monitor       | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| notify        | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| scheduledtask | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| scheduler     | release/3.10(abc4558b2424052209)                                                                                                                                                                |
| vpcagent      | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| webconsole    | release/3.10(abc4558b2424022900)                                                                                                                                                                |
| yunionagent   | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-yunionagent:30898/version\": dial tcp: lookup default-yunionagent on 10.96.0.10:53: no such host","request":{"headers" |
|               | :{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-yunionagent:30898/version"}}}                                                                  |
| yunionconf    | release/3.10(abc4558b2424022900)                                                                                                                                                                |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by yulongz** [comment]
> @yulongz 从现象描述看，感觉是本地网络配置问题。可以对比一下宽带（本地以太网）和热点以及WIFI的路由的差异。

不是某一个宽带的问题，是从多个宽带地址访问公网地址都出现此问题，经过多个家用宽带以及办公用宽带都是此问题。

**Comment by yulongz** [comment]
> > @yulongz 从现象描述看，感觉是本地网络配置问题。可以对比一下宽带（本地以太网）和热点以及WIFI的路由的差异。
> 
> 不是某一个宽带的问题，是从多个宽带地址访问公网地址都出现此问题，经过多个家用宽带以及办公用宽带都是此问题。

目前看到的情况是基本从所有宽带方式访问都是此问题。

**Comment by swordqiu** [comment]
@yulongz 
"云主机IP及端口能通但数据不能正常返回"
这个现象比较常见的原因是MTU的设置不一致，这里虚拟机用的是vpc网络吗？

**Comment by yulongz** [comment]
> @yulongz "云主机IP及端口能通但数据不能正常返回" 这个现象比较常见的原因是MTU的设置不一致，这里虚拟机用的是vpc网络吗？

目前云主机时在VPC网络里，然后负载均衡做的公网IP到虚机的监听映射。MTU我们先实验一下

**Comment by yulongz** [comment]
https://www.cloudpods.org/docs/guides/onpremise/network/vpc/mtu
我已经按照官网文档调整了MTU，即ovn_underlay_mtu增加到1560，但是出现了如下情况。
1、云主机设置MTU在1443及以上时，宽带访问仍然有问题。
2、云主机设置MTU在1442及以下时，宽带访问TCP监听的网站是正常的。还在测试。

**Comment by yulongz** [comment]
> https://www.cloudpods.org/docs/guides/onpremise/network/vpc/mtu 我已经按照官网文档调整了MTU，即ovn_underlay_mtu增加到1560，但是出现了如下情况。 1、云主机设置MTU在1443及以上时，宽带访问仍然有问题。 2、云主机设置MTU在1442及以下时，宽带访问TCP监听的网站是正常的。还在测试。

还有个一情况是测试环境下，lb agent部署在云主机里了。

**Comment by swordqiu** [comment]
可以在lbagent所在云主机里设置试试：

```
iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmt
```

**Comment by yulongz** [comment]
> https://www.cloudpods.org/docs/guides/onpremise/network/vpc/mtu 我已经按照官网文档调整了MTU，即ovn_underlay_mtu增加到1560，但是出现了如下情况。 1、云主机设置MTU在1443及以上时，宽带访问仍然有问题。 2、云主机设置MTU在1442及以下时，宽带访问TCP监听的网站是正常的。还在测试。

测试环境上满足以下条件服务端口监听转发才能正常：
1、我把ovn_underlay_mtu改成了1560。
2、lbagent所在云主机上MTU设置为1560(小于1558不行)。
3、创建虚机MTU改成1440(大约1443不行)。

iptable的规则我再看看。

**Comment by yulongz** [comment]
> > https://www.cloudpods.org/docs/guides/onpremise/network/vpc/mtu 我已经按照官网文档调整了MTU，即ovn_underlay_mtu增加到1560，但是出现了如下情况。 1、云主机设置MTU在1443及以上时，宽带访问仍然有问题。 2、云主机设置MTU在1442及以下时，宽带访问TCP监听的网站是正常的。还在测试。
> 
> 测试环境上满足以下条件服务端口监听转发才能正常： 1、我把ovn_underlay_mtu改成了1560。 2、lbagent所在云主机上MTU设置为1560(小于1558不行)。 3、创建虚机MTU改成1440(大约1443不行)。
> 
> iptable的规则我再看看。

我现在加了iptables规则，还是要满足上面的MTU条件才能访问。

**Comment by yulongz** [comment]
在ovn_underlay_mtu不调整默认1500的情况下，虚拟机的MTU是1440。

**测试1**
测试抓包访问web地址有个现象：
宽带：客户端发送MTU：1500；收到服务器返回的MTU：1452 ,   访问不正常。（1452>1440，是不是有点奇怪？!）
手机流量：客户端发送MTU：1500  ；收到服务器返回的MTU：1400 ， 访问正常。

**测试2**
如果将客户端的WLAN的MTU直接改成1400，访问正常。
Windows客户端修改MTU命令：netsh interface ipv4 set subinterface "WLAN" mtu=1400 store=persistent

**Comment by 66545shiwo** [comment]
@swordqiu 我整理下测试结果：
1.在cloudpods都是默认参数，当前客户端和服务器端MTU都为1500，虚拟机MTU默认为1440，访问虚拟机web服务异常
![image](https://github.com/yunionio/cloudpods/assets/39178471/de2037a2-a90c-47dc-a317-c2cbd151324c)
2.调整本地MTU由`1500`调整为`1440`，当前客户端为1440，服务器端MTU为1500，虚拟机MTU默认1440，访问虚拟机web服务正常
3.调整cloudpods参数`ovn_underlay_mtu`为1560，虚拟机默认MTU为1500，访问虚拟机web服务异常
4.调整cloudpods参数`ovn_underlay_mtu`为1560，调整虚拟机MTU由1500改为1440，访问虚拟机web服务正常

**Comment by swordqiu** [comment]
多谢反馈，我们产品上统一设置一下MTU

**Comment by yulongz** [comment]
> @swordqiu 我整理下测试结果： 1.当cloudpods都是默认参数，当前客户端和服务器端MTU都为1500，虚拟机MTU默认为1440，访问虚拟机web服务异常 ![image](https://private-user-images.githubusercontent.com/39178471/344851698-de2037a2-a90c-47dc-a317-c2cbd151324c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTM5NjAsIm5iZiI6MTcxOTk5MzY2MCwicGF0aCI6Ii8zOTE3ODQ3MS8zNDQ4NTE2OTgtZGUyMDM3YTItYTkwYy00N2RjLWEzMTctYzJjYmQxNTEzMjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA4MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDlhYjZkZGYwZmI2N2NkYTU2ZDg4Y2M3NDJhOTI5YzkwYzBkNzYxN2VlMDUyODcwMzZhMjVhMjU2MTkxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9KXLK-Bikh70CyYWmyY884LV3Cf4D-oMTHf_E7wDGg) 2.调整本地MTU由`1500`调整为`1440`，当前客户端为1440，服务器端MTU为1500，虚拟机MTU默认1440，访问虚拟机web服务正常 3.调整cloudpods参数`ovn_underlay_mtu`为1560，当前客户端和服务器端MTU都为1500，虚拟机默认MTU为1500，访问虚拟机web服务异常 4.调整cloudpods参数`ovn_underlay_mtu`为1560，当前客户端和服务器端MTU都为1500，调整虚拟机MTU由1500改为1440，访问虚拟机web服务正常

通过抓包发现，即使将ovn_underlay_mtu调整到1560，还是有大量的丢包，服务访问并不正常。

**Comment by zexi** [comment]
@swordqiu 可以把这些内核参数加到 lbagent 启动代码里面。
