### ISSUE TITLE
[求助/Help]请问支持做软raid吗？

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#20704]
请问支持做软raid吗？
谢谢

**Comment by zexi** [comment]
@vincentiss 不支持

**Comment by vincentiss** [comment]
如果想用mdadm做软raid 是不是需要修改定制的小系统啊？

**Comment by zexi** [comment]
> @zexi 谢谢 如果想用mdadm做软raid 是不是需要修改定制的小系统啊？

@vincentiss 应该是的，估计装系统的镜像里面也要支持

**Comment by vincentiss** [comment]
@zexi 好点谢谢

**Comment by vincentiss** [comment]
@zexi 
大佬 
我在这里加了mdadm [](https://github.com/yunionio/yunionos/blob/master/Dockerfile.buildroot#40)
编译出来的initramfs还是找不到该命令,
是不是我理解有问题啊？想把mdadm打包进去该改哪里啊？
谢谢
