### ISSUE TITLE
[求助/Help] Ubuntu22.04 安装高可用集群找不到deployment coredns

### ISSUE THREAD

**Issue by flowlsj** [yunionio/cloudpods#20707]
![image](https://github.com/yunionio/cloudpods/assets/7510377/c9b585cd-13f7-443c-91c4-3ec521671b6b)

**Comment by flowlsj** [comment]
3.10.6版本

**Comment by zexi** [comment]
@flowlsj 登录到第一个控制节点，执行 kubectl get pods -n kube-system 看下有没有 coredns ?

**Comment by flowlsj** [comment]
![image](https://github.com/yunionio/cloudpods/assets/7510377/bbdf99f9-8efe-45cd-b426-c816b7ea76c3)
没有哦

**Comment by zexi** [comment]
@flowlsj `kubectl get deployment -n kube-system` 看下有没有 coredns ，如果没有，感觉是安装部署的流程没有跑完，或者是 cni 没有初始化导致的。

`kubectl get nodes` 看下节点是不是 Ready 状态。

**Comment by flowlsj** [comment]
我重装了下又可以了
