### ISSUE TITLE
[求助/Help]cloudpod 安装monitor服务，influxDB后，看不到虚拟机监控指标

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20713]
如下图，我已经启动了monitor服务 但没有查看到指标，以下是我看到的后台日志，请问我是少装了什么服务吗
[D 2024-07-03 17:52:22 influxdb.(*InfluxdbExecutor).createRequest(influxdb.go:204)] Influxdb raw query: "SELECT mean(\"write_bps\") AS \"磁盘写速率\" FROM \"vm_diskio\" WHERE (\"vm_id\" = 'fce7d22a-65fa-4629-82f8-8ffe6dcf511a' and \"domain_id\" = 'dae546a017fc41dd8d8be07c13e4fd7d') AND time > now() - 1h GROUP BY \"vm_id\", time(1m) fill(none)" from db telegraf, curl: curl -X 'POST' -d 'q=SELECT+mean%28%22write_bps%22%29+AS+%22%E7%A3%81%E7%9B%98%E5%86%99%E9%80%9F%E7%8E%87%22+FROM+%22vm_diskio%22+WHERE+%28%22vm_id%22+%3D+%27fce7d22a-65fa-4629-82f8-8ffe6dcf511a%27+and+%22domain_id%22+%3D+%27dae546a017fc41dd8d8be07c13e4fd7d%27%29+AND+time+%3E+now%28%29+-+1h+GROUP+BY+%22vm_id%22%2C+time%281m%29+fill%28none%29' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: OneCloud Monitor' 'http://172.16.18.242:8086/query?db=telegraf&epoch=ms'
[D 2024-07-03 17:52:22 conditions.(*MetricQueryCondition).ExecuteQuery.func1(metricquery.go:102)] query metrics from TSDB "influxdb" elapsed: 1.14755ms
[I 2024-07-03 17:52:22 appsrv.(*Application).ServeHTTP(appsrv.go:289)] wV0qtRvRb91goYoSI8K3EZWoVfc= 200 393f03-f743b0 POST /unifiedmonitors/query (172.16.18.242:37850:apigateway) 1.70ms
[D 2024-07-03 17:52:25 alerting.(*schedulerImpl).Update(scheduler.go:37)] Scheduling update, rule count 0
[D 2024-07-03 17:52:35 alerting.(*schedulerImpl).Update(scheduler.go:37)] Scheduling update, rule count 0
[D 2024-07-03 17:52:45 alerting.(*schedulerImpl).Update(scheduler.go:37)] Scheduling update, rule count 0
![image](https://github.com/yunionio/cloudpods/assets/20590260/3c40ab72-2414-4baf-b124-9e6cf426efb6)

**Comment by ioito** [comment]
如果是公有云，需要再装下cloudmon，cloudmon会周期性通过api拉取公有云的监控

**Comment by wanyaoqi** [comment]
确认一下虚机内监控agent telegraf是否正常运行

**Comment by ollylu** [comment]
是AWS云机器

**Comment by ollylu** [comment]
好的 cloudmon 安装有什么特殊的配置地方吗

**Comment by ioito** [comment]
没有特殊地方，跟其他服务一样

**Comment by ollylu** [comment]
这是启动日志，请问哪里还需要配置吗
![image](https://github.com/yunionio/cloudpods/assets/20590260/854f0f01-47b9-4323-912d-577a3f00587c)

**Comment by ioito** [comment]
默认是6分钟拉一次监控信息，等一段时间后再看监控

**Comment by ollylu** [comment]
我看到连接9994 这个端口失败了 请问这个有影响吗
![image](https://github.com/yunionio/cloudpods/assets/20590260/97ae42a5-7ebf-4f49-90c1-3056d6fee32f)

**Comment by ioito** [comment]
没有影响
