### ISSUE TITLE
[求助/Help] web登录报错：头部中没有token：fetchAuthInfo: No token in header: InvalidCredentialError"

### ISSUE THREAD

**Issue by ChaoHsin-fang** [yunionio/cloudpods#20737]
/ # /opt/yunion/bin/keystone -v
Yunion cloud version:
{
  "major": "0",
  "minor": "0",
  "gitVersion": "v3.11.3",
  "gitBranch": "release/3.11",
  "gitCommit": "3ffea07d31",
  "gitTreeState": "dirty",
  "buildDate": "2024-04-24T02:53:47Z",
  "goVersion": "go1.18.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}/ #

kill -s SIGUSR1 1  调用堆栈信息如下
[keystone 调用栈日志.txt](https://github.com/user-attachments/files/16104630/keystone.txt)

 辛苦帮忙排查一下

**Comment by ioito** [comment]
看起来是都卡在数据库操作了，需要看下数据库是否正常，登录数据库show full processlist看下有没有异常的sql

**Comment by ChaoHsin-fang** [comment]
![image](https://github.com/yunionio/cloudpods/assets/48585560/1803aafa-88ea-4a72-b5ff-bbf3508c5210)

确实有异常 好多是sleep状态

**Comment by ioito** [comment]
sleep 是正常的，看非sleep的有没有异常

**Comment by hjoisajdoijsaid** [comment]
![Uploading 图片.png…]()

**Comment by ioito** [comment]
`climc worker-list --service identity`
再看下keystone的worker队列数量

**Comment by hjoisajdoijsaid** [comment]
[
<img width="692" alt="Snipaste_2024-07-05_14-16-47" src="https://github.com/yunionio/cloudpods/assets/172370742/c8b3130a-58d4-4def-b0b9-ba9081d1c1dc">
<img width="692" alt="Snipaste_2024-07-05_14-17-09" src="https://github.com/yunionio/cloudpods/assets/172370742/496d28dc-91eb-4e4e-87f9-b19bffa019f4">
<img width="692" alt="Snipaste_2024-07-05_14-17-28" src="https://github.com/yunionio/cloudpods/assets/172370742/1ba6c340-039e-4878-b6d1-21c81b27327e">
<img width="692" alt="Snipaste_2024-07-05_14-17-41" src="https://github.com/yunionio/cloudpods/assets/172370742/02dca20b-8cef-4ba7-9fea-5265aa9f2d1f">
<img width="692" alt="Snipaste_2024-07-05_14-17-52" src="https://github.com/yunionio/cloudpods/assets/172370742/c5c6ec36-741f-4b55-938a-f8e8f28be121">
](url)

**Comment by hjoisajdoijsaid** [comment]
[root@cloudpod-test-1 ~]# climc worker-list --service identity


{"error":{"class":"TimeoutError","code":504,"details":"request process timeout","request":{"body":"{\"auth\":{\"context\":{\"source\":\"cli\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"name\":\"s...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"209","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708"},"method":"POST","url":"https://10.64.25.154:30500/v3/auth/tokens"}}}

**Comment by ioito** [comment]
看起来就是keystone的sql有问题，可以先重启下keystone恢复，我查下出现大量COMMIT的原因

**Comment by ChaoHsin-fang** [comment]
在issue里面搜到类似的问题https://github.com/yunionio/dashboard/pull/4411  这个issue 应该在3.11版本里解决了吧

**Comment by ioito** [comment]
跟这个没关系，这个得后端解决处理

**Comment by ChaoHsin-fang** [comment]
重启keystone卡在这里了 default-keystone-5bc444cd8f-vtm8p                    0/1     Init:0/1           0          28m

**Comment by ioito** [comment]
到数据库中把所有keystone的COMMIT的请求kill掉

**Comment by ChaoHsin-fang** [comment]
找到原因了，数据库存储不够了，需要扩一下，感谢解答

**Comment by ilovedumplings** [comment]
> 找到原因了，数据库存储不够了，需要扩一下，感谢解答

磁盘不足?

**Comment by ChaoHsin-fang** [comment]
是的 ，binlog 30天自动清理一次 ，没到30天就把/var/lib/mysql/目录空间占满了，扩容之后，keystone能正常写数据了，就正常登录了
