### ISSUE TITLE
[求助/Help] pxe启动会申请两次IP吗？

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#20734]
你好，
我们碰到一个情况，一台物理机重启后，会申请2次IP，
第一次正常，
加载小系统后会第二次申请IP，agent发了offer包，客户机收不到。
请问申请2次IP是对的吗？为什么会失败呢 是交换机拦了么？不知道怎么排查了。
还有这种情况卡在小系统登录，ssh密码会通知失败，会设置成默认密码，默认密码是什么啊 在哪里找啊？尝试了yunion@123不对

**Comment by zexi** [comment]
@vincentiss 这个是正常的，因为启动到 YunionOS 后，里面会有脚本 https://github.com/yunionio/yunionos/blob/master/src_pxe/etc/init.d/S80eth0#L38 让每张网卡发送 dhcp 请求分配 ip 。

可以通过在后端执行 climc host-ssh 登录到 yunionos 里面：
```bash
climc host-ssh $物理机id 
```
通过 climc host-logininfo 查询登录信息

```bash
climc host-logininfo $物理机id
```

**Comment by vincentiss** [comment]
@zexi

**Comment by vincentiss** [comment]
@zexi 
客户机现在网络不通，看屏幕显示通知agent失败改成默认密码了。
climc查看的密码不对。
谢谢

**Comment by zexi** [comment]
> @zexi 客户机现在网络不通，看屏幕显示通知agent失败改成默认密码了。 climc查看的密码不对。 谢谢

@vincentiss 这个是默认密码：https://github.com/yunionio/yunionos/blob/master/src_pxe/etc/init.d/S99notify#L16，如果网络不通导致没有通知到 baremetal-agent ，会把默认密码设置成：mosbaremetal

**Comment by vincentiss** [comment]
@zexi 感谢感谢
大佬 能给分析下第二次IP分配失败的原因吗

**Comment by zexi** [comment]
> @zexi 感谢。 也就是说第二次分配IP失败的情况 是要找找交换机的问题么？
> 
> 日志上看 第二次一直是 discover 和offer，客户机收不到offer。 谢谢

@vincentiss 是的，这个得到交换机上看下，一般的排查流程是：
1. 现在  barematal-agent 所在的节点抓包，看有没有收到 client 发过来的 dhcp 请求
```bash
# 用这个命令观察请求和返回
tcpdump -i any -nn -vvv udp and port 67 or port 68
```
2. 如果没有收到物理机发来的 dhcp 请求，或者有 dhcp 响应但物理机那边没有收到，*就需要排查交换机的配置*
3. 如果没有响应，就需要排查  baremetal-agent 的日志，里面会有为什么没有分配 dhcp ip 的原因

**Comment by vincentiss** [comment]
@zexi 
有收到dhcp请求，第一次分配的时候dhcp过程是成功的，
第二次的时候agent收到了客户机的discover请求，也给他发了offer，但客户机收不到，就一直发discover请求。
奇怪的是如果是交换机的配置问题，为什么第一次会成功呢？

感谢大佬。 我先去查查交换机的配置
