### ISSUE TITLE
[BUG] 关于keystone又又死了的问题

### ISSUE THREAD

**Issue by ilovedumplings** [yunionio/cloudpods#20741]
![微信图片_20240705104403](https://github.com/yunionio/cloudpods/assets/19704134/46da0198-2365-40d3-82ac-f2f3a70e0f94)
![1720164528996](https://github.com/yunionio/cloudpods/assets/19704134/ed49c19a-eae3-4e5d-9e4c-c38d87c1ec7d)
结了两个图,分析不出来问题原因,猜测还是keystone自己内部的问题,版本是3.10.8 准备把issues的 19488和 19688 这两个代码合并上去
第二个图,感觉数据库也连不上了,但是直接访问数据库没问题，第一张图还报错了queue full,task dropped,猜测还是keystone内部问题

**Comment by ilovedumplings** [comment]
@ioito 老师有啥排查思路没?

**Comment by ioito** [comment]
这个应该把keystone到数据库网络搞好，应该就正常了

**Comment by ilovedumplings** [comment]
> 这个应该把keystone到数据库网络搞好，应该就正常了，其他服务连数据库正常么

当时没注意，当时的现象是所有服务去调用keystone全部超时，然后单独访问数据库是没问题的。这么一说,可能真是数据库的原因
