### ISSUE TITLE
[求助/Help] 查询虚拟机数量，过去7天趋势，无返回任何结果

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20783]
![image](https://github.com/yunionio/cloudpods/assets/20590260/04195d8c-86b2-46f5-bf3d-5af9a47d3aca)

我的集群是开源社区版， 搭建了 monitor服务，部署的是 influxdb，我希望查询 过去 20天 domain.servers数量趋势，接口请求如下：
但缺没有返回任何信息

curl 'https://cloudadmin.XXXXXXXX.com/api/v1/unifiedmonitors/query' \
  --data-raw '{"metric_query":[{"model":{"database":"influxdb","measurement":"usage","select":[[{"type":"field","params":["domain.servers"]},{"type":"last"}]]}}],"scope":"domain","show_meta":true,"from":"504h","interval":"24h","unit":true,"signature":"36f90ac896fdde1d20530ff1e10e45e96845ca470adf1afe097ad2bb1483a89e"}'

返回：
{"metas":[{"raw_query":"SELECT last(\"domain.servers\") FROM \"usage\" WHERE \"domain_id\" = 'a0d7703dd26a430d8b1333648d179d24' AND time > now() - 504h GROUP BY time(1d) fill(none)"}],"series_total":0}

请问是不是因为 domain.servers 这个指标有采集吗，如何配置让监控采集这个指标？ 我装了 region 服务，是不是缺少案安装了什么服务？

**Comment by ioito** [comment]
看下 a0d7703dd26a430d8b1333648d179d24 这个域底下有没有虚拟机，没有虚拟机就是正常的

**Comment by ollylu** [comment]
是不是需要在region服务那边设置同步指标？

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/5701c46b-6728-4ff9-8906-84db2948ef9f)
you有的

**Comment by ioito** [comment]
不需要，这个是cloudmon服务自动收集的

**Comment by ollylu** [comment]
如上图还有虚拟机使用率

**Comment by ioito** [comment]
到influxdb里面查usage表里面的数据

**Comment by ollylu** [comment]
![image](https://github.com/yunionio/cloudpods/assets/20590260/30909bbc-6352-4881-ba84-d33f62e97bac)

没有找到那张表

**Comment by ollylu** [comment]
是不是我少了什么配置

**Comment by ollylu** [comment]
需要安装telegraf 服务吗，我理解应该不需要吧

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/blob/b66d955fe9f6a4aadfeccbfcc57ec70c595310f4/pkg/cloudmon/misc/usageservice.go#L190-L229
你调试下这段代码吧，这个收集虚拟机数量的逻辑

**Comment by ollylu** [comment]
好的

**Comment by ollylu** [comment]
[E 2024-07-10 17:57:12 misc.UsegReport(usageservice.go:100)] report usage error: getImageUsageFields: GetServiceVersionURLs: catalog.GetServiceURLs: No such service image: NotFoundError -----是缺少这个服务 导致这个函数在一开始就退出了，请问Image服务 什么作用 是提供镜像管理吗

**Comment by ollylu** [comment]
glance服务没装，是缺少这个服务 导致这个函数在一开始就退出了，请问glance服务 什么作用 是提供镜像管理吗

**Comment by ollylu** [comment]
部署这个服务有特殊配置吗，还是与部署 cloudmon类似

**Comment by ioito** [comment]
部署类似region服务

**Comment by ollylu** [comment]
ok 感谢
