### ISSUE TITLE
iso.yunion.cn:443地址解析异常

### ISSUE THREAD

**Issue by hjoisajdoijsaid** [yunionio/cloudpods#20790]
纳管ubuntu计算节点时报错：
TASK [common : init apt cache for Ubuntu] **************************************
fatal: [10.64.25.94]: FAILED! => {"changed": false, "dest": "/tmp/yunion.gpg-key.asc", "elapsed": 10, "msg": "Request failed: <urlopen error timed out>", "url": "https://iso.yunion.cn/ubuntu/22/base/x86_64/yunion.gpg-key.asc"}

尝试跳过该步骤
在给计算节点安装k8s软件包时报错，仓库源内无镜像
尝试在计算节点 apt update
 apt update 
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease       
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease     
Hit:4 http://archive.ubuntu.com/ubuntu jammy-security InRelease      
Ign:5 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ InRelease       
Ign:6 https://iso.yunion.cn/deb-updates/x86_64 ./ InRelease
Ign:5 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ InRelease
Ign:6 https://iso.yunion.cn/deb-updates/x86_64 ./ InRelease
Ign:5 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ InRelease
Ign:6 https://iso.yunion.cn/deb-updates/x86_64 ./ InRelease
Err:5 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ InRelease
  Could not connect to iso.yunion.cn:443 (47.79.64.188), connection timed out
Err:6 https://iso.yunion.cn/deb-updates/x86_64 ./ InRelease
  Unable to connect to iso.yunion.cn:https:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
176 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://iso.yunion.cn/ubuntu/22/base/x86_64/./InRelease  Could not connect to iso.yunion.cn:443 (47.79.64.188), connection timed out
W: Failed to fetch https://iso.yunion.cn/deb-updates/x86_64/./InRelease  Unable to connect to iso.yunion.cn:https:
W: Some index files failed to download. They have been ignored, or old ones used instead.

同样是访问该地址异常，之前纳管的时候都没遇到，最近才遇到

**Comment by fangpsh** [comment]
iso.yunion.cn ->yunionrpm.oss-cn-hongkong.aliyuncs.com. ->47.79.64.188  阿里云香港。
挂个代理试一试。

**Comment by hjoisajdoijsaid** [comment]
之前都没挂代理就可以用，这个地址是有啥变动么

**Comment by swordqiu** [comment]
这个域名一直在阿里云香港的OSS托管。感觉是大陆到香港的G防火墙策略有调整。之前是没问题。

**Comment by hjoisajdoijsaid** [comment]
好的，感谢解答：）
