### ISSUE TITLE
[Feature] 3.12版本默认展示普通公网IP

### ISSUE THREAD

**Issue by ioito** [yunionio/cloudpods#20805]
**What would you like to be added**:

前端传入 show_emulated=true， 同时展示 类型(mode)
public_ip: 公网IP
elastic_ip: 弹性公网IP

@GuoLiBin6

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/6976

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/6978
