### ISSUE TITLE
[求助/Help]ocboot 增加node 镜像拉取不到了，是不是换仓库了

### ISSUE THREAD

**Issue by enhellowhy** [yunionio/cloudpods#20826]
![image](https://github.com/user-attachments/assets/3a8e0b45-da84-460e-9365-3236a1a7dd96)
ocboot 增加node 镜像拉取不到了，是不是换仓库了
当前版本3.9.6，目前有没有啥比较快速的解决方案？

**Comment by zexi** [comment]
<img width="704" alt="image" src="https://github.com/user-attachments/assets/c0c350be-4f98-44f1-9c4e-81b870fefd9a">

@enhellowhy 我这边拉取没有问题，请排查下是不是添加的 node 网络环境的问题？

**Comment by xmapst** [comment]
> ![image](https://private-user-images.githubusercontent.com/18282440/349339390-3a8e0b45-da84-460e-9365-3236a1a7dd96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTY0MDQsIm5iZiI6MTcyMTE5NjEwNCwicGF0aCI6Ii8xODI4MjQ0MC8zNDkzMzkzOTAtM2E4ZTBiNDUtZGE4NC00NjBlLTkzNjUtMzIzNmExYTdkZDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYmY4YmU4NDQ2Zjk5OWJjMmI1NjlhMzBmNjllZTdhMDk4YWVhY2FkY2E1NzAzOTRiOWYzODNiYzE5MDExZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DPfZHU57sK1etFhiI4Bd0V9RWhOaIJeAyo7_zqYfkUw) ocboot 增加node 镜像拉取不到了，是不是换仓库了 当前版本3.9.6，目前有没有啥比较快速的解决方案？

docker或者containerd版本太高导致的   降一下版本即可

**Comment by enhellowhy** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18282440/349339390-3a8e0b45-da84-460e-9365-3236a1a7dd96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTY0MDQsIm5iZiI6MTcyMTE5NjEwNCwicGF0aCI6Ii8xODI4MjQ0MC8zNDkzMzkzOTAtM2E4ZTBiNDUtZGE4NC00NjBlLTkzNjUtMzIzNmExYTdkZDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYmY4YmU4NDQ2Zjk5OWJjMmI1NjlhMzBmNjllZTdhMDk4YWVhY2FkY2E1NzAzOTRiOWYzODNiYzE5MDExZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DPfZHU57sK1etFhiI4Bd0V9RWhOaIJeAyo7_zqYfkUw) ocboot 增加node 镜像拉取不到了，是不是换仓库了 当前版本3.9.6，目前有没有啥比较快速的解决方案？
> 
> docker或者containerd版本太高导致的 降一下版本即可

对对对，是这个问题，我们也发现了，谢谢你们~
