### ISSUE TITLE
[求助/Help]加载kernel后dhcp失败

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#20845]
请教下
    启动机器主板请求dhcp正常拿到了启动文件，加载启动文件后，又去请求dhcp（临时文件系统内发的请求），然后碰到
```碰到no dhcpoffers received. no working leases in persistent database```,
<img width="387" alt="image" src="https://github.com/user-attachments/assets/034b74cd-3315-4db1-8894-3a15cdc3cfbf">

baremetal agent上tcpdump抓包看到发出的offer到了网关上，没有继续转发；it 的同事没发现什么线索，
请问为什么第二次dhcp会失败呢？有没有办法让第二次使用第一次获取到的IP呢？ 
谢谢。

**Comment by zexi** [comment]
@vincentiss 理论上如果能 pxe 启动成功，第二次 dhcp 也是走的同样路径。如果 agent 做了 dhcp response，应该还是网络原因，需要确保整个二层网络环境中没有其他的 dhcp 服务。

**Comment by vincentiss** [comment]
谢谢
两次间隔时间太短导致
