### ISSUE TITLE
主机偶发性启动失败，报错ssh问题[BUG]

### ISSUE THREAD

**Issue by WjtMatch** [yunionio/cloudpods#20844]
![image](https://github.com/user-attachments/assets/f09db28e-2795-4efb-b88c-a666ef5e3330)
[{"tenant_id":"b8682393d759479886125db40f5f7b90","notes":"{\"__reason__\":\"Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = Connect: new ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain\",\"__stage__\":\"OnDeployGuestComplete\",\"__status__\":\"error\"}","obj_name":"ecm-nyv1ys2ft1UUO6W","roles":"admin","owner_tenant_id":"b8682393d759479886125db40f5f7b90","is_system_account":false,"domain_id":"default","_i18n":{"service":"Compute","action":"Vm Deploy","obj_type":"Server"},"can_delete":false,"action":"vm_deploy","obj_type":"server","id":487204,"project_domain":"Default","owner_domain":"Default","can_update":true,"tenant":"system","severity":"ERROR","obj_id":"42c481b0-4c67-405b-83b8-86bca614c81a","kind":"NORMAL","ip":"10.100.117.172","ops_time":"2024-07-18T08:18:51.000000Z","start_time":"2024-07-18T08:17:33.000000Z","user_id":"881b11a50075450b8059d5c736936ec9","service":"compute","success":false,"domain":"Default","owner_domain_id":"default","owner_tenant":"system","project_domain_id":"default","user":"admin"},{"tenant_id":"b8682393d759479886125db40f5f7b90","notes":"deploying=>deploy_fail: {\"__reason__\":\"Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = Connect: new ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain\",\"__stage__\":\"OnDeployGuestComplete\",\"__status__\":\"error\"}","obj_name":"ecm-nyv1ys2ft1UUO6W","roles":"admin","owner_tenant_id":"b8682393d759479886125db40f5f7b90","is_system_account":false,"domain_id":"default","_i18n":{"service":"Compute","action":"Update Status","obj_type":"Server"},"can_delete":false,"action":"update_status","obj_type":"server","id":487203,"project_domain":"Default","owner_domain":"Default","can_update":true,"tenant":"system","severity":"ERROR","obj_id":"42c481b0-4c67-405b-83b8-86bca614c81a","kind":"NORMAL","ip":"10.100.117.172","ops_time":"2024-07-18T08:18:51.000000Z","start_time":"2024-07-18T08:18:51.000000Z","user_id":"881b11a50075450b8059d5c736936ec9","service":"compute","success":false,"domain":"Default","owner_domain_id":"default","owner_tenant":"system","project_domain_id":"default","user":"admin"}]
最近偶发性创建云主机时候会报这个ssh异常的问题

**Comment by zexi** [comment]
@WjtMatch 提供下整体部署的版本？另外看下 host-deployer 组件的版本。

**Comment by WjtMatch** [comment]
> @WjtMatch 这个镜像是什么镜像

![image](https://github.com/user-attachments/assets/9d823679-0f76-408e-9ca9-12655c429cc5)
zi'ding自定义的镜像

**Comment by WjtMatch** [comment]
> host-deployer

![Uploading 2f4e4d648fe7a1b6310be2b10ec77a2.png…]()
是这个信息吗

**Comment by WjtMatch** [comment]
> @WjtMatch 提供下整体部署的版本？另外看下 host-deployer 组件的版本。

<img width="1242" alt="2f4e4d648fe7a1b6310be2b10ec77a2" src="https://github.com/user-attachments/assets/aa85aa52-5529-4437-bc99-f8103331ebd2">
是这个信息吗

**Comment by wanyaoqi** [comment]
@WjtMatch 看起来需要排查一下，看一下当前宿主机的 host-deployer 服务日志

**Comment by WjtMatch** [comment]
> @WjtMatch 看起来需要排查一下，看一下当前宿主机的 host-deployer 服务日志

这个日志怎么看

**Comment by WjtMatch** [comment]
> @WjtMatch 看起来需要排查一下，看一下当前宿主机的 host-deployer 服务日志

![image](https://github.com/user-attachments/assets/749b52f7-8d32-43a8-8432-345c50c66ff5)

**Comment by wanyaoqi** [comment]
@WjtMatch 这个hostdeployer日志应该有个 qemu启动部署虚机的日志，你手动起一下看看是否能启动，然后看下 ssh能否连接

**Comment by WjtMatch** [comment]
> @WjtMatch 这个hostdeployer日志应该有个 qemu启动部署虚机的日志，你手动起一下看看是否能启动，然后看下 ssh能否连接

qemu这个怎么看啊

**Comment by wanyaoqi** [comment]
@WjtMatch 你看host-deployer 日志里面部署某个磁盘的时候会打印qemu 运行命令

**Comment by WjtMatch** [comment]
> @WjtMatch 你看host-deployer 日志里面部署某个磁盘的时候会打印qemu 运行命令

![image](https://github.com/user-attachments/assets/d24764d0-280c-4285-ad71-ec46953b314f)
这个吗

**Comment by wanyaoqi** [comment]
> > @WjtMatch 你看host-deployer 日志里面部署某个磁盘的时候会打印qemu 运行命令
> 
> ![image](https://private-user-images.githubusercontent.com/46695957/355039109-d24764d0-280c-4285-ad71-ec46953b314f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDgyOTUsIm5iZiI6MTcyMjg0Nzk5NSwicGF0aCI6Ii80NjY5NTk1Ny8zNTUwMzkxMDktZDI0NzY0ZDAtMjgwYy00Mjg1LWFkNzEtZWM0Njk1M2IzMTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4NTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NTdmMWQzY2Q3NzllMDIyODk0MWU4YjIzNjQ4YWRlMjI4OGE4YjU1ZDBjYjM3YjY1MDFkZWE4Nzg0NWM4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vs8O4krQzqJFIvXmGCbom994wEVtg71E3SGTLmFp62g) 这个吗

是的

**Comment by WjtMatch** [comment]
> > > @WjtMatch 你看host-deployer 日志里面部署某个磁盘的时候会打印qemu 运行命令
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/46695957/355039109-d24764d0-280c-4285-ad71-ec46953b314f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDgyOTUsIm5iZiI6MTcyMjg0Nzk5NSwicGF0aCI6Ii80NjY5NTk1Ny8zNTUwMzkxMDktZDI0NzY0ZDAtMjgwYy00Mjg1LWFkNzEtZWM0Njk1M2IzMTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4NTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NTdmMWQzY2Q3NzllMDIyODk0MWU4YjIzNjQ4YWRlMjI4OGE4YjU1ZDBjYjM3YjY1MDFkZWE4Nzg0NWM4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vs8O4krQzqJFIvXmGCbom994wEVtg71E3SGTLmFp62g) 这个吗
> 
> 是的

那我现在就直接在宿主机上执行这个命令然后看能不能创建出来主机是吧

**Comment by wanyaoqi** [comment]
> @WjtMatch 这个hostdeployer日志应该有个 qemu启动部署虚机的日志，你手动起一下看看是否能启动，然后看下 ssh能否连接

运行这个是用了来部署虚机的，你手动运行后尝试去 ssh 连接 这个端口看看能不能连上
