### ISSUE TITLE
[BUG] keystone数据中mobile不支持各种语言和文本布局

### ISSUE THREAD

**Issue by xmapst** [yunionio/cloudpods#20851]
**问题描述/What happened**:
mobile字段的字符集为`ascii_general_ci` 同步`LDAP`用户信息时提示
```
syncUsers: searchLDAP: process entry fail at 100-1-1901: syncUserDB: idp.SyncOrCreateUser: Update: saveUpdate: execUpdateSql: TxExec: Error 1366: Incorrect string value: '\xE2\x80\xAD137...' for column `keystone`.`user`.`mobile` at row 1
```
检查发现是`ascii_general_ci`字符集不支持  需要使用`utf8mb4_unicode_ci`

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
有手机号是非英文的情况么，能不能更正手机号后再同步

**Comment by ioito** [comment]
fixed #20898
