### ISSUE TITLE
[求助/Help] 新建虚拟机一直处于分配磁盘中

### ISSUE THREAD

**Issue by xxhacker** [yunionio/cloudpods#20870]
后端存储为ceph 14.2.X,已经在平台上跑的机器使用没有问题，就是新建虚拟机选择ceph做系统盘的时候，就一直处于分配磁盘中，也没有报错，还试了两种方式新建虚拟机也是可以的，一个是新建虚拟机的时候选择本地存储，或者是选择本地存储后再迁移至ceph也是可以的，不知道这种情况怎么解决
![微信截图_20240724092726](https://github.com/user-attachments/assets/696db75d-1a68-48da-8a41-a0179cd2099a)

**Comment by xxhacker** [comment]
这个是pod scheduler机器新建的时候的日志，看日志感觉都没有选到合适的节点
[b.txt](https://github.com/user-attachments/files/16356253/b.txt)

**Comment by zexi** [comment]
@xxhacker 调度器里面的报错应该不影响，你用下面的命令看下调度失败到哪一步了：
climc scheduler-history-list
找到失败的 session id
然后用下面的命令查看原因
climc scheduler-history-show --log --raw $session_id

**Comment by xxhacker** [comment]
@zexi 用上述命令查看，好像也没有发现有什么异常现象，以下是命令执行结果
[c.txt](https://github.com/user-attachments/files/16356456/c.txt)

**Comment by zexi** [comment]
> @zexi 用上述命令查看，好像也没有发现有什么异常现象，以下是命令执行结果 [c.txt](https://github.com/user-attachments/files/16356456/c.txt)

这个是调度成功的，返回的结果。这个问题应该和调度器没有关系，因为失败的话虚拟机状态会是调度失败，而不是处于分配磁盘中。

**Comment by zexi** [comment]
@xxhacker 要不你们升级到  v3.10.15 试试，这个是 3.10 最新的版本，3.10.4 太老了，有可能修复过这个问题。

**Comment by zexi** [comment]
这个是 3.10 各个版本相关的 changelog：https://www.cloudpods.org/docs/development/changelog/release-3_10/
