### ISSUE TITLE
[求助/Help]3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接

### ISSUE THREAD

**Issue by chensam678** [yunionio/cloudpods#20871]
3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接

**Comment by zexi** [comment]
> 3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接

@chensam678 看下 influxdb 这个 deployment 创建了吗？

**Comment by chensam678** [comment]
influxdeb的deployment没有创建，onecloud的operator版本时3.11.3

**Comment by chensam678** [comment]
influxdbdployment没有创建，onecloud operator版本是3.11.3



---原始邮件---
发件人: "Zexi ***@***.***&gt;
发送时间: 2024年7月24日(周三) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接 (Issue #20871)




  
3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接
  
@chensam678 看下 influxdb 这个 deployment 创建了吗？

**Comment by zexi** [comment]
> influxdeb的deployment没有创建，onecloud的operator版本时3.11.3

@chensam678 贴下 default-cloudpods-operator-xxxx 这个 pod 的日志，influxdb 是由这个 operator 创建的

**Comment by chensam678** [comment]
重启了operator，日志记录中似乎没有关于influxdb相关信息



---原始邮件---
发件人: "Zexi ***@***.***&gt;
发送时间: 2024年7月24日(周三) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接 (Issue #20871)




  
influxdeb的deployment没有创建，onecloud的operator版本时3.11.3
  
@chensam678 贴下 default-cloudpods-operator-xxxx 这个 pod 的日志，influxdb 是由这个 operator 创建的

**Comment by zexi** [comment]
@chensam678 更新下 ocboot 仓库的代码，最新的版本应该是 v3.11.5 的，已经默认用 victoria-metrics 替换 influxdb 了，我测试没有问题。

**Comment by chensam678** [comment]
好的，谢谢



---原始邮件---
发件人: "Zexi ***@***.***&gt;
发送时间: 2024年7月24日(周三) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]3.11版本使用helm部署时并未将influxdb部署，登录平台后会报influxdb服务无法连接 (Issue #20871)




 
@chensam678 更新下 ocboot 仓库的代码，最新的版本应该是 v3.11.5 的，已经默认用 victoria-metrics 替换 influxdb 了，重新部署下，我测试没有问题。
