### ISSUE TITLE
文档中注明[银河麒麟V10 SP2] 支持 x86_64 和 arm64，实际上却是只支持 x86_64

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#20888]
文档中注明[银河麒麟V10 SP2] 支持 x86_64 和 arm64，实际上却是只支持 x86_64
https://docs-os.yunion.cn/zh/docs/quickstart/allinone-full/ 
![image](https://github.com/user-attachments/assets/b4714d2f-161b-4305-8597-ef8fe0780b64)
![image](https://github.com/user-attachments/assets/228c36d5-2db1-4437-a9b9-0722c995d75b)

**Comment by zexi** [comment]
这个是老版本的文档了，请参考新版本文档部署：https://www.cloudpods.org/docs/getting-started/

另外现在开源版不再支持和维护对银河麒麟等商用Linux 发行版的部署。

**Comment by nashzosi** [comment]
好的已更换，openeuler

**Comment by yujianweilai** [comment]
> 好的已更换，openeuler

兄弟问一下，openeuler是银河麒麟的开源版吗？类似Centos和Redhat的关系？
