### ISSUE TITLE
[求助/Help]通过平台创建vmware虚拟机时，网卡中的PEERDNS,DNS1,DOMAIN如何进行更改或者不用添加

### ISSUE THREAD

**Issue by chensam678** [yunionio/cloudpods#20895]
通过平台上进行模板新建vmware虚拟机时，网卡中的PEERDNS,DNS1,DOMAIN如何进行更改或者不用添加，如果配置了这些参数模板原有的/etc/resolv.conf文件的内容会被清空。

**Comment by chensam678** [comment]
似乎改region应用的configmap相关参数也不生效

**Comment by ioito** [comment]
改对应ip子网的高级属性试下

**Comment by chensam678** [comment]
按照提供的方式处理后已解决，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 上午10:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunionio/cloudpods] [求助/Help]通过平台创建vmware虚拟机时，网卡中的PEERDNS,DNS1,DOMAIN如何进行更改或者不用添加 (Issue #20895)




 
改对应ip子网的高级属性试下
