### ISSUE TITLE
[求助/help]单网口的vpc网络，如何实现虚拟机禁止访问宿主机所在网段？

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#20902]
单网口的vpc网络，如何实现虚拟机禁止访问宿主机所在网段？

_Originally posted by @DSYZayn in https://github.com/yunionio/cloudpods/issues/20244#issuecomment-2254147230_

**Comment by swordqiu** [comment]
@DSYZayn 可以通过设置虚拟机的管理安全组，禁止虚拟机访问宿主机的网段。
管理安全组只能管理员设置

**Comment by DSYZayn** [comment]
@swordqiu 尝试了新建一个安全组，限制访问宿主机网段有效，但换绑安全组后虚拟机出现了无法访问外网的情况，手动修改/etc/resolv.conf中dns为10.10.10.10后正常。(ubuntu镜像)默认dns为127.0.0.53，这个是平台部署的时候没有注入dns成功吗？其他镜像部署的dns都是宿主机ip。另外我这里的Default安全组一直是未知状态，已经尝试重启了控制节点，还是没有获取到Default安全组状态，关联的实例只能解绑Default不能再绑定。怎么解决这个Default安全组未知的问题？
![image](https://github.com/user-attachments/assets/d212ca33-cc87-43a5-a15b-2158633ed796)
![image](https://github.com/user-attachments/assets/077c885b-48aa-4185-b4d3-041d319ca8c8)

**Comment by ioito** [comment]
你版本是多少，做了什么操作导致安全组状态未知

**Comment by DSYZayn** [comment]
@ioito v3.11.5,之前是多次添加删除了出入规则,然后有一次之后安全组状态就变成未知了，但新的虚拟机仍然会默认分配到这个安全组。如果是解绑后再绑定Default则显示安全组not ready.

**Comment by ioito** [comment]
fix: https://github.com/yunionio/cloudpods/pull/21016 合并后，重新打下region镜像，同步下安全组状态就好了

**Comment by zexi** [comment]
@DSYZayn region 镜像：
registry.cn-beijing.aliyuncs.com/yunionio/region:v3.11.6-20240814.0

**Comment by DSYZayn** [comment]
@zexi @ioito 谢谢两位，该镜像有效。
