### ISSUE TITLE
[BUG] 批量创建虚拟机失败

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#20922]
**问题描述/What happened**:

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):debian 10
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):3.11.5

使用占位符批量创建虚拟机失败, 如图配置，只创建了host01
![image](https://github.com/user-attachments/assets/d00d1937-8b4b-4005-b840-3260c1397087)

**Comment by zexi** [comment]
@DSYZayn 数量填的几个？

**Comment by DSYZayn** [comment]
> @DSYZayn 数量填的几个？

Sorry, 现在才看到要填数量，看那段提示文字我还以为占位符是自动映射数量🥲
