### ISSUE TITLE
[求助/Help] 华为云国际站无法同步状态

### ISSUE THREAD

**Issue by zhangsj** [yunionio/cloudpods#20945]
cloudpods多云管理 版本 v3.11.5
部署方式daocker-compose 
华为云国际站key已给admin权限 及bss administrator
仍然提示 
GetBalance: {"error":{"class":"CBC.0150","code":403,"details":"Access denied. The customer does not belong to the website you are now at.","request":{"headers":{"Authorization":"*","Host":"bss.myhuaweicloud.com","User-Agent":"yunioncloud-go/201708","X-Sdk-Date":"20240801T094302Z"},"method":"GET","url":"https://bss.myhuaweicloud.com/v2/accounts/customer-accounts/balances"}}}

![image](https://github.com/user-attachments/assets/d61a59e0-5b68-439b-a46f-9e4db073bfb4)

**Comment by zhangsj** [comment]
国际站是这个链接
https://bss-intl.myhuaweicloud.com/v2/accounts/customer-accounts/balances

![image](https://github.com/user-attachments/assets/e1eb3eae-a865-456e-b415-50f3f2160198)

**Comment by ioito** [comment]
我兼容处理下

**Comment by ioito** [comment]
fixed: https://github.com/yunionio/cloudmux/pull/1030

**Comment by zhangsj** [comment]
谢谢 [ocboot](https://github.com/yunionio/ocboot) 拉哪个分支？

**Comment by ioito** [comment]
最新release没释放出来，需要自己打包镜像，或者先执行以下命令更新
`kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-beijing.aliyuncs.com/yunionio},{op: add, path: /spec/regionServer/tag, value: v3.11-20240807-solo}]'`

**Comment by zhangsj** [comment]
docker-compose 中对应更新哪个服务

**Comment by ioito** [comment]
region服务

**Comment by zhangsj** [comment]
有大概的步骤吗？拉哪个代码？

**Comment by zexi** [comment]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/3a107e8a-5109-4355-9ddb-a8f85beb88fc">
改 docker-compose.yaml 里面的这里

**Comment by zhangsj** [comment]
这个bug在ocboot最新的版本V3.11.6中没有修复吗

**Comment by ioito** [comment]
v3.11.6已修复，若依然有问题，麻烦贴下报错信息

**Comment by zhangsj** [comment]
![image](https://github.com/user-attachments/assets/f56a91d2-9076-484c-92b0-9123730c318b)
![image](https://github.com/user-attachments/assets/5bbc16a5-efc7-4778-9f7a-4a4178a6e178)

**Comment by ioito** [comment]
https://github.com/yunionio/cloudmux/pull/1050/files 将在下次发版修复，其中有次优化导致识别华为Error错误
