### ISSUE TITLE
[BUG] ocboot account create error

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#20969]
**问题描述/What happened**:
Using Ocboot quick install guide, but got account create error.

![image](https://github.com/user-attachments/assets/95dc40e3-9165-489b-b239-dd5c97923113)

but I tried using cURL, it can connect.

**环境/Environment**:
- OS (e.g. `cat /etc/os-release`):
NAME="openEuler"
VERSION="22.03 (LTS-SP3)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP3)"
ANSI_COLOR="0;31"

- Kernel (e.g. `uname -a`):
Linux ocm-01.xxx.local 5.10.0-221.0.0.124.oe2203sp3.x86_64 #1 SMP Wed Jul 31 21:00:14 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
	Manufacturer: QEMU
	Product Name: Standard PC (i440FX + PIIX, 1996)

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@elvizlai Please try to use [k3s installation way](https://www.cloudpods.org/docs/getting-started/onpremise/buildah-k3s) to deployment.

**Comment by elvizlai** [comment]
any docs about upgrade version deploy using k3s?
