### ISSUE TITLE
[Feature] proxmox GetOsArch should not be fixed

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#20960]
**What would you like to be added**:

for proxmox instance.go, the arch is fixed:
```
func (ins *SInstance) GetOsArch() string {
	return "x86_64"
}
```

But there has arm64 version https://github.com/jiangcuo/Proxmox-Port, and it works well.

We should conn to nodes to fetch that info correctly.

**Comment by ioito** [comment]
Thank you for the feedback, we will fix this issue.

**Comment by ioito** [comment]
fixed: https://github.com/yunionio/cloudmux/pull/1034/files
