### ISSUE TITLE
[求助/Help] k8s集群创建失败

### ISSUE THREAD

**Issue by DSYZayn** [yunionio/cloudpods#20971]
导入centos7.6和7.9都试了，虚拟机可以创建成功，但是k8s集群总是创建失败，查看kubeconfig显示空白，同时报错ca empty
- 宿主机:debian10
- cloudpods v3.11.5
- 虚拟机镜像：centos7.6(文档中给出的镜像) | centos7.9(社区镜像导入)

![image](https://github.com/user-attachments/assets/936622c8-ca63-4e7f-97e2-b07febea1b15)
![image](https://github.com/user-attachments/assets/a5ae530e-65f6-4fda-96dd-7533d1d802df)
![image](https://github.com/user-attachments/assets/a926fd0e-dff0-4c4d-afe3-d65d8d11f787)

操作日志：[export-actions.xlsx](https://github.com/user-attachments/files/16516969/export-actions.xlsx)
确认创建的虚拟机是可以联网的，虚拟机状态：
![image](https://github.com/user-attachments/assets/c35fa700-03aa-40f3-a31f-557ffd3e3e0c)

**Comment by zexi** [comment]
@DSYZayn 应该是 centos 7 源过期导致的，可以这样临时解决下，用文档中的镜像创建一台虚拟机，然后进入虚拟机替换源：
```bash
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
```
之后保存这个虚拟机的镜像，最后创建 k8s 集群的时候选择这个镜像。

**Comment by DSYZayn** [comment]
@zexi 确认是这个问题，感谢。
