### ISSUE TITLE
[求助/Help] 拉取源码 执行  go mod vendor   报错 unknown revision v2.0.0-rc.16

### ISSUE THREAD

**Issue by ollylu** [yunionio/cloudpods#20979]
go mod vendor        
    ------------
go: downloading github.com/tredoe/osutil/v2 v2.0.0-rc.16
go: yunion.io/x/onecloud/pkg/util/seclib2 imports
        github.com/tredoe/osutil/v2/userutil/crypt/sha512_crypt: reading github.com/tredoe/osutil/go.mod at revision v2.0.0-rc.16: unknown revision v2.0.0-rc.16

**Comment by am6737** [comment]
> go mod 供应商 ------------ go：下载 github.com/tredoe/osutil/v2 v2.0.0-rc.16 go：yunion.io/x/onecloud/pkg/util/seclib2 导入 github.com/tredoe/osutil/v2/userutil/crypt/sha512_crypt：读取 github.com/tredoe/osutil/go.mod 修订版 v2.0.0-rc.16：未知修订版 v2.0.0-rc.16

你可以使用下面的命令解决，我想可能是不同代理服务器的缓存机制导致的。
```
go env -w GOPROXY="https://goproxy.cn,direct"
go mod vendor
```

**Comment by ollylu** [comment]
问题解决 谢谢

**Comment by am6737** [comment]
@ioito 
我们需要将go.mod里`github.com/tredoe/osutil/v2 v2.0.0-rc.16`更新为`github.com/tredoe/osutil v1.5.0`吗，因为github.com/tredoe/osutil目前最新版本为v1.5.0，由于不同的代理服务器缓存机制可能会导致找不到对应的版本。

**Comment by ioito** [comment]
fix: https://github.com/yunionio/cloudpods/pull/20992/files
