### ISSUE TITLE
[BUG]本地块存储的磁盘（qcow2格式）修改驱动时侯，设置为writeback后，虚拟机无法启动！！

### ISSUE THREAD

**Issue by maguoweng** [yunionio/cloudpods#20981]
**问题描述/What happened**:
本地块存储的磁盘（qcow2格式）修改驱动时侯，设置为writeback后，虚拟机无法启动！！
**环境/Environment**:
高可用 的3.11.5版本
- OS (e.g. `cat /etc/os-release`): openEuler 22.03 (LTS-SP3)
- Kernel (e.g. `uname -a`):5.10.0-182.0.0.95.oe2203sp3.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
kubectl  logs  -n onecloud default-host-mj2x5   host
回显如下：
[info 2024-08-08 08:42:04 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 204 8049b1 POST /write?db=telegraf (192.168.1.250:40158) 3.35ms
[info 2024-08-08 08:43:04 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 204 7fc1a2 POST /write?db=telegraf (192.168.1.250:55436) 3.48ms
[info 2024-08-08 08:44:04 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 204 e99914 POST /write?db=telegraf (192.168.1.250:58844) 3.68ms
[info 2024-08-08 08:45:04 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 204 885abf POST /write?db=telegraf (192.168.1.250:37824) 4.04ms
[info 2024-08-08 08:45:44 monitor.(*QmpMonitor).write(qmp.go:260)] QMP Write openEuler(79a09c24-e431-4498-856e-abf88135e999): {"execute":"system_powerdown"}
[info 2024-08-08 08:45:44 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 200 c6e38c-d20ebc-2a326d POST /servers/79a09c24-e431-4498-856e-abf88135e999/stop (10.40.133.2:34194:compute_v2) 0.30ms
[info 2024-08-08 08:45:44 monitor.(*QmpMonitor).read(qmp.go:182)] QMP Read openEuler(79a09c24-e431-4498-856e-abf88135e999): {"return": {}}
[info 2024-08-08 08:45:44 monitor.(*QmpMonitor).read(qmp.go:182)] QMP Read openEuler(79a09c24-e431-4498-856e-abf88135e999): {"timestamp": {"seconds": 1723106744, "microseconds": 893882}, "event": "POWERDOWN"}
[info 2024-08-08 08:45:44 monitor.(*QmpMonitor).watchEvent(qmp.go:252)] QMP event openEuler(79a09c24-e431-4498-856e-abf88135e999): QMP Event result: &monitor.Event{Event:"\"POWERDOWN\"", Data:map[string]interface {}{}, Timestamp:(*monitor.Timestamp)(0xc0013fe100)}
[info 2024-08-08 08:45:45 monitor.(*QmpMonitor).read(qmp.go:182)] QMP Read openEuler(79a09c24-e431-4498-856e-abf88135e999): {"timestamp": {"seconds": 1723106745, "microseconds": 847816}, "event": "SHUTDOWN", "data": {"guest": true, "reason": "guest-shutdown"}}
[info 2024-08-08 08:45:45 monitor.(*QmpMonitor).watchEvent(qmp.go:252)] QMP event openEuler(79a09c24-e431-4498-856e-abf88135e999): QMP Event result: &monitor.Event{Event:"\"SHUTDOWN\"", Data:map[string]interface {}{"guest":true, "reason":"guest-shutdown"}, Timestamp:(*monitor.Timestamp)(0xc0013fe6f0)}
[info 2024-08-08 08:45:45 monitor.(*QmpMonitor).read(qmp.go:232)] Scan over openEuler(79a09c24-e431-4498-856e-abf88135e999) ...
[error 2024-08-08 08:45:45 guestman.(*SKVMGuestInstance).onMonitorDisConnect(qemu-kvm.go:1668)] Guest 79a09c24-e431-4498-856e-abf88135e999 on Monitor Disconnect reason: <nil>
[info 2024-08-08 08:45:45 guestman.(*SKVMGuestInstance).CleanStartupTask(qemu-kvm.go:1825)]79a09c24-e431-4498-856e-abf88135e999: Clean startup task ... no task
[info 2024-08-08 08:45:46 guestman.(*SKVMGuestInstance).clearCgroup(qemu-kvm.go:1775)] cgroup destroy 137746 cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746
[info 2024-08-08 08:45:46 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:300)] Remove task path /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746 cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746
[info 2024-08-08 08:45:46 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:300)] Remove task path /sys/fs/cgroup/cpu/cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746 cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746
[info 2024-08-08 08:45:46 cgrouputils.(*CGroupTask).RemoveTask(cgrouputils.go:300)] Remove task path /sys/fs/cgroup/blkio/cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746 cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746
[info 2024-08-08 08:45:47 guestman.(*SKVMGuestInstance).clearCgroup(qemu-kvm.go:1775)] cgroup destroy 137746 cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746
[warning 2024-08-08 08:45:47 guestman.(*SKVMGuestInstance).CleanupCpuset(qemu-kvm.go:2179)] failed read dir /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746: open /sys/fs/cgroup/cpuset/cloudpods.hostagent/server_79a09c24-e431-4498-856e-abf88135e999_137746: no such file or directory
[info 2024-08-08 08:45:47 modules.TaskComplete(task.go:34)] Sync task e3bdc48e-3190-449e-8c93-12871e357773 complete succ
[info 2024-08-08 08:45:48 appsrv.(*Application).ServeHTTP(appsrv.go:289)] yZXWOGED9kezfyCdq8rixw1QBEY= 200 c6e38c-d20ebc-5ad6cf POST /servers/79a09c24-e431-4498-856e-abf88135e999/start (10.40.133.2:34210:compute_v2) 0.88ms
[info 2024-08-08 08:45:48 guestman.(*SKVMGuestInstance).allocGuestNumaCpuset(qemu-kvm.go:2889)] alloc numa cpus map[0:{[0 1 2 3] 0 false}]
[info 2024-08-08 08:45:48 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:832)] Use vnc port 9
[warning 2024-08-08 08:45:49 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:1105)] Guest 79a09c24-e431-4498-856e-abf88135e999 start monitor failed, can't get qmp monitor port or monitor path
[warning 2024-08-08 08:45:49 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2340)] Guest openEuler(79a09c24-e431-4498-856e-abf88135e999) waiting monitor connect
[error 2024-08-08 08:45:49 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2334)] Guest 79a09c24-e431-4498-856e-abf88135e999 check qemu(159211) process failed: os: process already finished
[error 2024-08-08 08:45:50 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:861)] Start VM failed openEuler(79a09c24-e431-4498-856e-abf88135e999): fied, but it requires cache.direct=on, which was not specified.

[info 2024-08-08 08:45:51 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:832)] Use vnc port 10
[warning 2024-08-08 08:45:52 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:1105)] Guest 79a09c24-e431-4498-856e-abf88135e999 start monitor failed, can't get qmp monitor port or monitor path
[warning 2024-08-08 08:45:52 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2340)] Guest openEuler(79a09c24-e431-4498-856e-abf88135e999) waiting monitor connect
[error 2024-08-08 08:45:52 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2334)] Guest 79a09c24-e431-4498-856e-abf88135e999 check qemu(159365) process failed: os: process already finished
[error 2024-08-08 08:45:53 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:861)] Start VM failed openEuler(79a09c24-e431-4498-856e-abf88135e999): fied, but it requires cache.direct=on, which was not specified.

[info 2024-08-08 08:45:55 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:832)] Use vnc port 11
[warning 2024-08-08 08:45:56 guestman.(*SKVMGuestInstance).StartMonitor(qemu-kvm.go:1105)] Guest 79a09c24-e431-4498-856e-abf88135e999 start monitor failed, can't get qmp monitor port or monitor path
[warning 2024-08-08 08:45:56 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2340)] Guest openEuler(79a09c24-e431-4498-856e-abf88135e999) waiting monitor connect
[error 2024-08-08 08:45:56 guestman.(*SKVMGuestInstance).scriptStart(qemu-kvm.go:2334)] Guest 79a09c24-e431-4498-856e-abf88135e999 check qemu(159514) process failed: os: process already finished
[error 2024-08-08 08:45:57 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:861)] Start VM failed openEuler(79a09c24-e431-4498-856e-abf88135e999): fied, but it requires cache.direct=on, which was not specified.

[error 2024-08-08 08:46:01 guestman.(*SKVMGuestInstance).asyncScriptStart(qemu-kvm.go:884)] Async start server openEuler(79a09c24-e431-4498-856e-abf88135e999) failed: fied, but it requires cache.direct=on, which was not specified.
!!!
[info 2024-08-08 08:46:01 modules.TaskComplete(task.go:34)] Sync task 98a0fbb1-35fc-4126-8114-bbb8773b037c complete succ
[error 2024-08-08 08:46:01 guestman.(*guestStartTask).Run(qemu-kvm.go:2040)] failed asyncScriptStart 79a09c24-e431-4498-856e-abf88135e999: fied, but it requires cache.direct=on, which was not specified.
![111](https://github.com/user-attachments/assets/efcf1132-15fe-49f4-80d0-a98babb9928d)
![C2DB8663-3431-47fe-AB88-E87BEFC75525](https://github.com/user-attachments/assets/6a43285a-0890-494e-8492-8c27b5296d51)

- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by maguoweng** [comment]
解决方法是将aio_mode 手动由native修改成threads后便可以启动。
问题是在web上修改成writeback后，后端数据库不会同步更新：
![屏幕截图 2024-08-08 172735](https://github.com/user-attachments/assets/6c40cd15-f0c4-42af-8bc1-c9f5b70ec22b)

**Comment by wanyaoqi** [comment]
fixed: https://github.com/yunionio/cloudpods/pull/20983
3.11 可以更新这个镜像：
`kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240808-gd}]'`

**Comment by maguoweng** [comment]
感谢您的修复！
