### ISSUE TITLE
[文档/Docs] missing upgrade/downgrade guide using k3s

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#20982]
**What part of the document needs to be added**:
只找到了升级文档: https://www.cloudpods.org/docs/operations/upgrading/ocboot-upgrade

目前缺失通过 k3s 安装后的版本升级指南, 以及相关的安装说明: https://www.cloudpods.org/docs/getting-started/onpremise/buildah-k3s

**Comment by zexi** [comment]
@elvizlai 感谢反馈，接下来我们会默认使用 k3s 部署，相关文档会尽快添加和修改。
