### ISSUE TITLE
[BUG] ceph rbd上的镜像缓存删除后镜像缓存列表显示异常

### ISSUE THREAD

**Issue by yulongz** [yunionio/cloudpods#20997]
**问题描述/What happened**:

操作顺序
1、在ceph rbd上创建了一个虚机
2、删除了虚拟机
3、释放镜像对应的本地磁盘的缓存，能够正常删除。
4、释放镜像对应的ceph上的缓存，无法执行释放缓存，显示存在引用(但是虚机已经被删除)。
镜像对应的缓存列表显示异常，存在内部错误。

![image](https://github.com/user-attachments/assets/19c2674c-62f4-4ad7-bf61-9eebdc2398b2)
![image](https://github.com/user-attachments/assets/d3457fcf-baea-4f13-b916-1a35a23bafd4)
![image](https://github.com/user-attachments/assets/0eddfc6b-d082-4e96-9549-75f68eecd176)

**环境/Environment**:

cloudpods版本3.10

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|     Field     |                                                                                             Value                                                                                              |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ansible       | release/3.10(65e12adada24051613)                                                                                                                                                               |
| apimap        | release/3.10(65e12adada24051613)                                                                                                                                                               |
| cloudevent    | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-cloudevent:30892/version\": dial tcp: lookup default-cloudevent on 10.96.0.10:53: no such host","request":{"headers": |
|               | {"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-cloudevent:30892/version"}}}                                                                   |
| cloudid       | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-cloudid:30893/version\": dial tcp: lookup default-cloudid on 10.96.0.10:53: no such host","request":{"headers":{"User |
|               | -Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-cloudid:30893/version"}}}                                                                            |
| cloudmon      | release/3.10(65e12adada24051613)                                                                                                                                                               |
| cloudproxy    | release/3.10(65e12adada24051613)                                                                                                                                                               |
| compute_v2    | release/3.10(65e12adada24051613)                                                                                                                                                               |
| devtool       | release/3.10(65e12adada24051613)                                                                                                                                                               |
| identity      | release/3.10(65e12adada24051613)                                                                                                                                                               |
| image         | release/3.10(65e12adada24051613)                                                                                                                                                               |
| k8s           | heads/v3.10.15-20240516.0(5cbfdf9624051613)                                                                                                                                                    |
| log           | release/3.10(65e12adada24051613)                                                                                                                                                               |
| monitor       | release/3.10(65e12adada24051613)                                                                                                                                                               |
| notify        | release/3.10(65e12adada24051613)                                                                                                                                                               |
| scheduledtask | release/3.10(65e12adada24051613)                                                                                                                                                               |
| scheduler     | release/3.10(65e12adada24051613)                                                                                                                                                               |
| vpcagent      | release/3.10(65e12adada24051613)                                                                                                                                                               |
| webconsole    | release/3.10(65e12adada24051613)                                                                                                                                                               |
| yunionagent   | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-yunionagent:30898/version\": dial tcp: lookup default-yunionagent on 10.96.0.10:53: no such host","request":{"headers |
|               | ":{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"https://default-yunionagent:30898/version"}}}                                                                |
| yunionconf    | release/3.10(65e12adada24051613)                                                                                                                                                               |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by yulongz** [comment]
补充接口返回数据：
api/v2/storagecaches/5f8d57c9-e80e-4c11-8bad-a2427d42beaf/cachedimages?scope=system&show_fail_reason=true&storage=03dbba1a-b5e2-48df-865e-6a0c7d793518&details=false&limit=20
```
            "account_read_only": false,
            "brand": "OneCloud",
            "cachedimage": "centos-stream-8-zyltest.qcow2",
            "cachedimage_id": "6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "can_delete": false,
            "can_update": true,
            "cdrom_reference": 0,
            "cloud_env": "onpremise",
            "created_at": "2024-08-12T01:57:16.000000Z",
            "delete_fail_reason": {
                "class": "NotEmptyError",
                "code": 406,
                "details": "镜像正使用中"
            },
            "deleted": false,
            "disk_reference": 1,
            "external_id": "6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "image": "centos-stream-8-zyltest.qcow2",
            "imported_at": "2024-08-12T01:57:16.000000Z",
            "provider": "OneCloud",
            "reference": 1,
            "row_id": 59,
            "size": 1149301760,
            "source": "local",
            "status": "active",
            "storage_info": [
                {
                    "id": "03dbba1a-b5e2-48df-865e-6a0c7d793518",
                    "medium_type": "ssd",
                    "name": "ceph-storage",
                    "storage_type": "rbd",
                    "zone": "zone0",
                    "zone_id": "35c32588-c481-4004-8bb9-69c976a53d2e"
                }
            ]
```


api/v2/storagecachedimages?scope=system&show_fail_reason=true&cachedimage_id=6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae&details=false&limit=20
```
{
    "data": [
        {
            "cachedimage_id": "6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "created_at": "2024-08-12T02:04:25.000000Z",
            "deleted": false,
            "imported_at": "2024-08-12T02:04:25.000000Z",
            "path": "/opt/cloud/workspace/disks/image_cache/6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "row_id": 63,
            "source": "local",
            "status": "active",
            "storagecache_id": "934cbc71-7f2a-4a86-804d-0bfdc6f82ec0",
            "update_version": 0,
            "updated_at": "2024-08-12T02:04:25.000000Z"
        },
        {
            "cachedimage_id": "6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "created_at": "2024-08-12T01:57:16.000000Z",
            "deleted": false,
            "external_id": "6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae",
            "imported_at": "2024-08-12T01:57:16.000000Z",
            "row_id": 59,
            "source": "local",
            "status": "active",
            "storagecache_id": "5f8d57c9-e80e-4c11-8bad-a2427d42beaf",
            "update_version": 3,
            "updated_at": "2024-08-12T01:57:34.000000Z"
        }
    ],
    "limit": 20,
    "total": 2
}
```


api/v2/storagecachedimages?scope=system&show_fail_reason=true&cachedimage_id=6efbc9a2-7565-4f91-8b0d-2e8dd8a8d4ae&details=true&limit=20

参数details=true出现异常
```
{
    "class": "InternalServerError",
    "code": 500,
    "details": "服务器内部错误：runtime error: index out of range [2] with length 2",
    "time": "2024-08-12T10:54:05+08:00"
}
```

**Comment by wanyaoqi** [comment]
> 65e12adada24051613

@yulongz 这个 500的问题应该修复过，你可以更新一下 region 镜像。
虚机是否在回收站内？

**Comment by yulongz** [comment]
> @yulongz 这个 500的问题应该修复过，你可以更新一下 region 镜像。 虚机是否在回收站内？

多谢提醒，确实回收站有对应虚机。

我删除了回收站的虚机，ceph上的镜像缓存能正常删除了。但是镜像的缓存列表还是有一条空记录，报错500.

![image](https://github.com/user-attachments/assets/5064cda3-85d1-4250-91d5-94a6ebb0d5a8)

![image](https://github.com/user-attachments/assets/373cb0bf-3fc0-4b76-828b-920ce4657ca7)

**Comment by wanyaoqi** [comment]
> Member

@yulongz 更新一下region镜像试试

**Comment by wanyaoqi** [comment]
> @yulongz 这个 500的问题应该修复过，你可以更新一下 region 镜像。 虚机是否在回收站内？

@yulongz 更新一下region镜像试试

**Comment by yulongz** [comment]
合并这个PR，已解决
[Automated cherry pick of #20425: fix(region): storagecacheresource panic on FetchCustomizeColumns #20426
](https://github.com/yunionio/cloudpods/pull/20426/files)
