### ISSUE TITLE
[求助/Help] vsphere 识别出来的镜像，windows镜像会被归类到linux

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21005]
vsphere  识别出来的镜像，windows镜像会被归类到linux，如图
![image](https://github.com/user-attachments/assets/6c4fd6c6-3970-4566-942a-ff20ff9e4f1c)

**Comment by ioito** [comment]
需要将模板名加上windows关键字

**Comment by zexi** [comment]
@ioito 可以通过 win.*\d 之类的正则表达式来判断下

**Comment by ioito** [comment]
https://github.com/yunionio/pkg/pull/135/files
