### ISSUE TITLE
[求助/Help] Ocboot 安装，climc 激活公有云后，列表中不显示

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#21014]
通过 https://www.cloudpods.org/docs/getting-started/onpremise/buildah-k3s 修改 VERSION 安装 v3.11.6-20240813.1

通过指令开启公有云支持
、、、
climc feature-config-qcloud --switch on
climc feature-config-aliyun --switch on
、、、

问题1：公有云列表未展示
问题2：由于问题1的存在，多个公有云无法选中切换

<img width="967" alt="image" src="https://github.com/user-attachments/assets/3a233f2e-2517-4479-9ac7-04d9d7302a03">

**Comment by zexi** [comment]
@elvizlai k3s 部署的默认是私有云，没有公有云支持，要改的话需要用下面的方式：

```bash
kubectl edit oc -n onecloud default
```

把 productVersion 改成 FullStask 
<img width="481" alt="image" src="https://github.com/user-attachments/assets/52f8a0ec-763a-486f-baf9-c9c3a32e0e20">

**Comment by elvizlai** [comment]
it works.
