### ISSUE TITLE
[求助/Help] 通过alb访问webconsole失败

### ISSUE THREAD

**Issue by zhangsj** [yunionio/cloudpods#21020]
版本 
v3.11.5

alb-->tg-->ec2(docker-compose部署)

访问webconsole后会自动在域名的url中添加了一次域名（https://cdp-test.abcxxxxx.com/cdp-test.abcxxxxx.com/web-console/ws?data=YWNjZXNzX3Rva2VuPURidnhJS2RaUnQxQk8wb0NGaVN5b2JRRkhTRUN2MTZtVzRWdFdzVERHMWt0UFNqODNaTXVpQ3R2eVpyZllmNmV4bE1tTmclM0QlM0QmYXBpX3NlcnZlcj0lM0ElMkYlMkYlMkZjZHAtdGVzdC5jb21wdXRlc2Vhcy5jb20maHlwZXJ2aXNvcj1xY2xvdWQmaW5zdGFuY2VfbmFtZT1OVklESUElQzIlQUUrVGVzbGElQzIlQUUrVDQrJTJBKzErJTQwK1NpbmdhcG9yZS02Jmlwcz0xMC4wLjEuMTUmaXNfbmVlZF9sb2dpbj1mYWxzZSZvc19kaXN0cmlidXRpb249VWJ1bnR1Jm9zX25hbWU9TGludXgmb3NfdHlwZT1MaW51eCZwcm90b2NvbD13ZWJzb2NrZXQ%3D&session_id=aeceec72-ec8c-4537-8ec2-610f4da11666）
手动去掉域名后提示 链接断开

请问如何处理

测试环境直接通过ip可以正常访问webconsole

**Comment by zexi** [comment]
@zhangsj exec 到 climc 容器里面，执行：
```bash
climc service-config-edit common
```
看下 api_server 设置的是什么值？

**Comment by zhangsj** [comment]
也是域名

**Comment by zhangsj** [comment]
抱歉，找到问题了。api-server 那里要加上https
另外，可以给webconsole单独配置一个域名吗

**Comment by zexi** [comment]
> 另外，可以给webconsole单独配置一个域名吗
@zhangsj 目前不支持，是和全局统一的。

**Comment by zhangsj** [comment]
好的 谢谢
