### ISSUE TITLE
[BUG] 上传系统镜像不能自定义os_version

### ISSUE THREAD

**Issue by 66545shiwo** [yunionio/cloudpods#21037]
**问题描述/What happened**:
上传一个windows镜像，发现os_version为空，没有发现任何地方可以设置os_version
**环境/Environment**:
v3.10.14

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
@66545shiwo 可以使用 `climc image-update` 命令更新镜像信息

**Comment by 66545shiwo** [comment]
@wanyaoqi 3q
