### ISSUE TITLE
[BUG] 批量创建虚拟在同一个宿主机上，虚机串行启动

### ISSUE THREAD

**Issue by 66545shiwo** [yunionio/cloudpods#21050]
**问题描述/What happened**:
创建虚机指定虚机个数为8个，指定在同一个宿主机上，发现虚机串行启动。
期望并行启动。
**环境/Environment**:
v3.10.14
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
虚机部署目前使用的是 nbd worker，这个 woker 数量是1，应该改成可配置的
<img width="766" alt="image" src="https://github.com/user-attachments/assets/a7ef47a5-e76a-4f90-beb5-28c2e85a596a">

**Comment by 66545shiwo** [comment]
@wanyaoqi 我说下现象：
8个虚机是差不多同时处于“部署中状态”，但“启动中”状态是一个一个执行的：
一个变成“运行中”，下一个虚机才会从“部署中”变为“启动中”
这种现象是改nbd_worker吗？

**Comment by 66545shiwo** [comment]
![dc47c413c51d796be66c243f1ce0d62](https://github.com/user-attachments/assets/8d373b0d-4944-495d-98f5-a69e21a0a93e)
虚机启动过程日志间隔大概这样

**Comment by wanyaoqi** [comment]
@66545shiwo 你这个是在部署阶段排队所以导致启动排队，所以是要改 nbd worker，目前这个work 应该是可以增大的，最好是和部署并发数一样大

**Comment by 66545shiwo** [comment]
的确可以了 ，已测试通过 ，感谢大佬 @wanyaoqi

**Comment by 66545shiwo** [comment]
建议大佬把这个参数可配置
