### ISSUE TITLE
[BUG]hsot-deployer 在修改win10（关机状态）虚拟机密码时候报错，提示：Failed to mount '/dev/sda1': Operation not permitted

### ISSUE THREAD

**Issue by maguoweng** [yunionio/cloudpods#21060]
**问题描述/What happened**:
我在创建win10专业版的虚拟机后，想通过重置密钥功能重置Administrator密码，但是失败了。
**环境/Environment**:  3.11.5
- OS (e.g. `cat /etc/os-release`):
openEuler release 22.03 (LTS-SP3)
- Kernel (e.g. `uname -a`):
-Linux kvm01 5.10.0-182.0.0.95.oe2203sp3.x86_64
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
[root@kvm01 ~]# dmidecode | egrep -i 'manufacturer|product' |sort -u
        Manufacturer: GenuineIntel
        Manufacturer: Intel Corporation
        Manufacturer Name: Intel
        Manufacturer: No Enclosure
        Manufacturer: Not Specified
        Manufacturer: VMware, Inc.
        Product Name: 440BX Desktop Reference Platform
        Product Name: VMware Virtual Platform
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

日志：kubectl  logs  default-host-deployer-vhwm6   -f
[info 2024-08-20 06:23:01 monitor.(*HmpMonitor).read(hmp.go:91)] Scan over  ...
[error 2024-08-20 06:23:01 qemu_kvm.(*QemuX86Driver).StartGuest.func2(driver.go:695)] monitor disconnect %!s(<nil>)
[info 2024-08-20 06:52:02 deployserver.(*DeployerServer).DeployGuestFs(deployserver.go:91)] ********* Deploy guest fs on qemuimg.SImageInfo{Path:"/opt/cloud/workspace/disks/63f0e489-f284-4914-8a16-1cadec420b8b", Format:"", IoLevel:0, Password:"", EncryptFormat:"", EncryptAlg:"", secId:""}
[info 2024-08-20 06:52:02 qemu_kvm.(*QemuDeployManager).Acquire(driver.go:121)] acquire QemuDeployManager
[info 2024-08-20 06:52:02 qemu_kvm.(*QemuX86Driver).StartGuest(driver.go:682)] start guest /usr/local/qemu-4.2.0/bin/qemu-system-x86_64 -enable-kvm -cpu host -M pc -nodefaults -daemonize -monitor unix:/opt/cloud/host-deployer/hmp_762fe90c-df7e-4b30-821a-474f24408878.socket,server,nowait -pidfile /opt/cloud/host-deployer/762fe90c-df7e-4b30-821a-474f24408878.pid -vnc none -smp 2 -m 320M -initrd /opt/cloud/host-deployer/yunionos/x86_64/initramfs -kernel /opt/cloud/host-deployer/yunionos/x86_64/kernel -append rootfstype=ramfs -append vsyscall=emulate -device virtio-serial-pci -netdev user,id=hostnet0,hostfwd=tcp:127.0.0.1:28002-:22 -device virtio-net-pci,netdev=hostnet0 -device virtio-scsi-pci,id=scsi -drive file=/opt/cloud/workspace/disks/63f0e489-f284-4914-8a16-1cadec420b8b,if=none,id=drive_0,cache=none -device scsi-hd,drive=drive_0,bus=scsi.0,id=drive_0 -drive id=cd0,if=none,media=cdrom,file=/opt/cloud/host-deployer/host_deployer_v1.iso -device ide-cd,drive=cd0,bus=ide.1
[info 2024-08-20 06:52:02 monitor.(*SBaseMonitor).connect(monitor.go:298)] Connect unix /opt/cloud/host-deployer/hmp_762fe90c-df7e-4b30-821a-474f24408878.socket success
[info 2024-08-20 06:52:02 monitor.(*HmpMonitor).read(hmp.go:79)] HMP Read : QEMU 4.2.0 monitor - type 'help' for more information

[info 2024-08-20 06:52:02 qemu_kvm.(*QemuX86Driver).StartGuest.func1(driver.go:691)] monitor connected
[info 2024-08-20 06:52:02 qemu_kvm.(*QemuKvmDriver).connect(driver.go:312)] guest started ....
[info 2024-08-20 06:52:09 qemu_kvm.(*QemuKvmDriver).connect(driver.go:327)] guest ssh connected
[info 2024-08-20 06:52:09 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command mount /dev/sr0 /opt
[info 2024-08-20 06:52:09 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command cat << EOF > /deploy_params
{"deploy_info":{"default_root_user":true,"enable_cloud_init":false,"enable_tty":false,"is_init":false,"login_account":"Administrator","password":"Changeme_123","public_key":{"admin_public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxY61DOscDxKmLVV7rwWq8kzd0oElwthpDuT4oQRbRuXPNuOhe495G9Dt3D+YrhoWDc6WfD20dxgv5LDW/aQRTxaC1SO3qVpLBThg+1zE7Z8m2SokXwkD5GT7I2JpVWxxK+maS2E0WlnTkJa6qzV265MZZu7GDAfsk3GfFvYm0Bacg8AKui1uRUSb301XBg4AdguE9jSw6joUMsj2CEuWw5sfsMMQaZ5eHrbhVln9NtFFaEWmR/tvd22jK1N8gUs1TG8WPP85tPTgS3V2v2FIAwA46GyrjeHDY3+UkPaaMc2zjmtzbFLpU962famK4alIazAc2N0bmiJD5spkGYnXZ\n","project_public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAkv9ATCQ4I/yXO77Jj9utFxvBrvC3THLh4DMX29MXpD5wRYKw4JD9IEEBg4cKb7tedkZAb6L/zyh/NKVqBwjkAEFvCkU2kASN1//++vuHcXxhH0gxMRhyYJd9pf2D2x6jtXSm1krXLLO+Ug43S4e7D1eIsCLlYoUoW+H5IVdOcA1nnZliZgzTeZdZhUhZWiFuYjSKRawza3fzRoK5QIvxfs1rsTcEYwIhNSCRlG1KE23X+Pnbh02rGaznIJ4QgZqN26X4XKdaBT03yVEFdnQ1/742ukBfONWJTg3gq6NTPif6m1yXVEhWK88978J3fCjvT1xgBIxyzeYBKjkkdqoz\n"},"windows_default_admin_user":true},"disk_info":{"path":"/opt/cloud/workspace/disks/63f0e489-f284-4914-8a16-1cadec420b8b"},"guest_desc":{"Hypervisor":"kvm","disks":[{"aio_mode":"native","cache_mode":"none","disk_id":"63f0e489-f284-4914-8a16-1cadec420b8b","driver":"ide","format":"qcow2","index":0,"merge_snapshot":false,"migrating":false,"path":"/opt/cloud/workspace/disks/63f0e489-f284-4914-8a16-1cadec420b8b","size":30720,"storage_id":"ce3cf2b6-186f-43e1-883e-d338924b2229"}],"domain":"bici.com","hostname":"win10-01","name":"win10-01","nics":[{"bridge":"br0","bw":1000,"dns":"114.114.114.114","domain":"bici.com","driver":"virtio","gateway":"192.168.1.1","ifname":"dasd-176","index":0,"interface":"ens224","ip":"192.168.1.176","is_default":true,"link_up":false,"mac":"00:22:8a:96:37:29","manual":false,"masklen":24,"masklen6":0,"mtu":1500,"net":"dasd","net_id":"eb063aa6-b63d-4eae-8af6-7c42e37fc243","virtual":false,"vlan":1,"wire_id":"a5f5fa67-a70c-4ac3-84c0-a91d88107c62"}],"uuid":"59d9f9c8-38d2-45e4-87ca-ac12a03d392d"}}
EOF
[info 2024-08-20 06:52:09 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command /opt/yunion/bin/host-deployer --config /opt/yunion/host.conf --deploy-action deploy_guest_fs --deploy-params-file /deploy_params
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).DeployGuestfs(driver.go:414)] DeployGuestfs log: 
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command test -f /error && cat /error || true
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).DeployGuestfs(driver.go:420)] deploy error str [[DetectRootFs with partition /dev/sda1 no root fs found, DetectRootFs with partition /dev/sda2 no root fs found]: NotFoundError]
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command test -f /response && cat /response || true
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).DeployGuestfs(driver.go:430)] deploy response str [null]
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).sshRun(driver.go:381)] QemuKvmDriver start command test -f /log && cat /log
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuKvmDriver).DeployGuestfs.func1(driver.go:401)] DeployGuestfs log: [info 2024-08-20 06:52:09 qemu_kvm.(*LocalDiskDriver).Connect(local_driver.go:62)] found part dev /dev/sda
[info 2024-08-20 06:52:09 qemu_kvm.(*LocalDiskDriver).Connect(local_driver.go:62)] found part dev /dev/sda1
[info 2024-08-20 06:52:09 qemu_kvm.(*LocalDiskDriver).Connect(local_driver.go:62)] found part dev /dev/sda2
[info 2024-08-20 06:52:09 fsutils.MountRootfs(fsutils.go:468)] detect partition /dev/sda
[error 2024-08-20 06:52:09 kvmpart.(*SKVMGuestDiskPartition).Mount(kvmpart.go:119)] Mount fs failed: unsupport fs  on /dev/sda
[info 2024-08-20 06:52:09 fsutils.MountRootfs(fsutils.go:468)] detect partition /dev/sda1
[error 2024-08-20 06:52:09 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda1': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:10 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda1': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:12 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda1': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:13 kvmpart.(*SKVMGuestDiskPartition).Mount(kvmpart.go:129)] SKVMGuestDiskPartition mount error: mount failed: tried 3 times, exceeding 3, last err exit status 14
[info 2024-08-20 06:52:13 guestfs.IsPartitionReadonly(core.go:219)] File system /tmp/_dev_sda1 is not readonly
[info 2024-08-20 06:52:13 kvmpart.(*SKVMGuestDiskPartition).Mount(kvmpart.go:149)] mount fs ntfs on /dev/sda1 successfully
[error 2024-08-20 06:52:13 kvmpart.(*SKVMGuestDiskPartition).IsMounted(kvmpart.go:293)] /tmp/_dev_sda1 is not a mountpoint: /tmp/_dev_sda1 is not a mountpoint

[info 2024-08-20 06:52:13 fsutils.MountRootfs(fsutils.go:468)] detect partition /dev/sda2
[error 2024-08-20 06:52:13 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda2': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:14 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda2': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda2': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

[error 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).Mount(kvmpart.go:129)] SKVMGuestDiskPartition mount error: mount failed: tried 3 times, exceeding 3, last err exit status 14
[info 2024-08-20 06:52:16 guestfs.IsPartitionReadonly(core.go:219)] File system /tmp/_dev_sda2 is not readonly
[info 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).Mount(kvmpart.go:149)] mount fs ntfs on /dev/sda2 successfully
[error 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).IsMounted(kvmpart.go:293)] /tmp/_dev_sda2 is not a mountpoint: /tmp/_dev_sda2 is not a mountpoint

[error 2024-08-20 06:52:16 fsutils.DeployGuestfs(fsutils.go:503)] Failed mounting rootfs for kvm disk: [DetectRootFs with partition /dev/sda1 no root fs found, DetectRootFs with partition /dev/sda2 no root fs found]: NotFoundError

[error 2024-08-20 06:52:17 deployserver.(*DeployerServer).DeployGuestFs(deployserver.go:114)] failed deploy guest fs: [DetectRootFs with partition /dev/sda1 no root fs found, DetectRootFs with partition /dev/sda2 no root fs found]: NotFoundError
[info 2024-08-20 06:52:17 monitor.(*HmpMonitor).write(hmp.go:125)] HMP Write : quit

[info 2024-08-20 06:52:17 monitor.(*HmpMonitor).read(hmp.go:79)] HMP Read : quit

[info 2024-08-20 06:52:17 monitor.(*HmpMonitor).read(hmp.go:91)] Scan over  ...
[error 2024-08-20 06:52:17 qemu_kvm.(*QemuX86Driver).StartGuest.func2(driver.go:695)] monitor disconnect %!s(<nil>)
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuBaseDriver).CleanGuest(driver.go:587)] kill  process kill: cannot find process "583175
"
 exit status 1
[info 2024-08-20 06:52:17 qemu_kvm.(*QemuDeployManager).Release(driver.go:126)] release QemuDeployManager

**Comment by zexi** [comment]
> [error 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Failed to mount '/dev/sda2': Operation not permitted
The NTFS partition is in an unsafe state. Please resume and shutdown
Windows fully (no hibernation or fast restarting), or mount the volume
read-only with the 'ro' mount option.

感觉是 windows 磁盘不是干净的状态，导致 ntfs mount 失败了

**Comment by maguoweng** [comment]
> > [error 2024-08-20 06:52:16 kvmpart.(*SKVMGuestDiskPartition).mount.func1.1(kvmpart.go:188)] mount fail: exit status 14 The disk contains an unclean file system (0, 0).
> > Metadata kept in Windows cache, refused to mount.
> > Failed to mount '/dev/sda2': Operation not permitted
> > The NTFS partition is in an unsafe state. Please resume and shutdown
> > Windows fully (no hibernation or fast restarting), or mount the volume
> > read-only with the 'ro' mount option.
> 
>   感觉是 windows 磁盘不是干净的状态，导致 ntfs mount 失败了

@zexi  感谢回复！ 虚拟机系统盘是创建虚拟机的时候新建的qcow2格式的磁盘，你说的磁盘不干净是指什么？我理解sda1里面应该是win10的操作系统 ntfs文件系统。安装完操作系统后，本身就干净了
我用相同的步骤创建win7的虚拟机，却没有遇到这个问题。

**Comment by swordqiu** [comment]
@maguoweng 感觉是windows 10有一个快速启动的机制，需要关闭。https://jingyan.baidu.com/article/ca00d56c7a40e6e99febcf4f.html

**Comment by maguoweng** [comment]
![屏幕截图 2024-08-20 231226](https://github.com/user-attachments/assets/ef694efd-2192-4cdd-b611-c6ca04d78851)

**Comment by swordqiu** [comment]
@maguoweng 那感觉还是因为您没有干净关机，所以磁盘数据还处于dirty状态，导致无法挂载ntfs的磁盘进行修改。请从windows系统内选择“关机”，等待机器关闭之后。然后再执行“重置密码”的操作。

下面日志清晰说明磁盘还处于dirty状态
···
The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
···

**Comment by maguoweng** [comment]
> @maguoweng 那感觉还是因为您没有干净关机，所以磁盘数据还处于dirty状态，导致无法挂载ntfs的磁盘进行修改。请从windows系统内选择“关机”，等待机器关闭之后。然后再执行“重置密码”的操作。
> 
> 下面日志清晰说明磁盘还处于dirty状态 ··· The disk contains an unclean file system (0, 0). Metadata kept in Windows cache, refused to mount. ···

@swordqiu 非常感谢，按照你的方式 我的win10系统成功修改了密码。
可能是因为我通过iso安装后，由于没耐心等待系统初始化完毕导致，不管怎样，再次感谢！
