### ISSUE TITLE
[求助/Help]

### ISSUE THREAD

**Issue by tomorrrow666** [yunionio/cloudpods#21064]
$ ./ocboot.py install ./config-k8s-ha.yml 报错：
vars:  {'onecloud_version': 'v3.11.6', 'onecloud_major_version': 'v3_11', 'extra_packages': [], 'yunion_qemu_package': 'yunion-qemu-4.2.0', 'is_controller_node': 'true'}
ansible-playbook -e @/tmp/oc_vars.yml -i /tmp/host_inventory.yml ./onecloud/install-cluster.yml

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [$MASTER_1_IP]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: hostname contains invalid characters", "unreachable": true}
fatal: [$MASTER_2_IP]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: hostname contains invalid characters", "unreachable": true}
fatal: [$PRIMARY_IP]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: hostname contains invalid characters", "unreachable": true}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
$MASTER_1_IP               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
$MASTER_2_IP               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
$PRIMARY_IP                : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by maguoweng** [comment]
是不是主机名有特殊字符？

**Comment by zexi** [comment]
@tomorrrow666 看下每台主机的 hostname ?
