### ISSUE TITLE
[求助/Help]K3S安装问题

### ISSUE THREAD

**Issue by tomorrrow666** [yunionio/cloudpods#21070]
k3s安装
TASK [mariadb : Pips for mysql/mariadb online] *********************************
fatal: [192.168.231.135]: FAILED! => {"msg": "Input version value cannot be empty"}

PLAY RECAP *********************************************************************
192.168.231.135            : ok=89   changed=33   unreachable=0    failed=1    skipped=41   rescued=0    ignored=0

error while running runtime: exit status 2
ERRO[0786] exit status 2

**Comment by fanyazhou** [comment]
apt install python3-pip -y
