### ISSUE TITLE
[求助/Help]该物理机不支持 redfish 带外控制，需要填写管理口 mac 地址

### ISSUE THREAD

**Issue by twosson** [yunionio/cloudpods#21089]
[info 2024-08-24 00:18:25 redfish.NewRedfishDriver(driver.go:110)] Found Supermicro Redfish REST Api Driver for endpoint "https://192.168.100.32"
[warning 2024-08-24 00:18:26 redfish.(*SBaseRedfishClient).GetSystemInfo(redfish.go:433)] no EthernetInterfaces info
[info 2024-08-24 00:18:26 appsrv.(*Application).ServeHTTP(appsrv.go:289)] FwNyBVaAHnDns_6_ISTCcLN-QVA= 200 99c594-291725-e40fba POST /baremetals/validate-ipmi (10.40.213.12:56042:compute_v2) 1864.61ms

**Comment by love-seeker** [comment]
![image](https://github.com/user-attachments/assets/acff38da-7c57-4fc1-aae1-b88809456ac5)
![image](https://github.com/user-attachments/assets/4d211618-6668-4ad3-8fb8-9d9f8ed1c448)
![image](https://github.com/user-attachments/assets/9ab49102-8e99-4604-be2d-ad1e50ed183e)
![image](https://github.com/user-attachments/assets/604e616e-c202-4dee-9bbf-42edacc1de27)
![image](https://github.com/user-attachments/assets/4692f21e-ede4-4ae9-ba72-9fe70a55e6c7)
你好，就是我在尝试纳管物理机的时候，无法进行ipmi配置，我的服务器是有BMC管理口的，并且可以正常用并进行访问我使用的是 这个mac地址，是BMC里面的，还是没有办法进行纳管，上面是报错以及日志处理
![image](https://github.com/user-attachments/assets/fe070b29-63de-424a-bbf5-a25287e2b38e)

**Comment by love-seeker** [comment]
thank you , i already slove this trouble.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunionio/cloudpods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月5日(星期二) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunionio/cloudpods] [求助/Help]该物理机不支持 redfish 带外控制，需要填写管理口 mac 地址 (Issue #21089)





 
If you do not provide feedback for more than 37 days, we will close the issue and you can either reopen it or submit a new issue.
 
您超过 37 天未反馈信息，我们将关闭该 issue，如有需求您可以重新打开或者提交新的 issue。
