### ISSUE TITLE
[求助/Help]物理机转宿主机,服务一直不可用, ssh无法连接

### ISSUE THREAD

**Issue by twosson** [yunionio/cloudpods#21091]
<img width="1615" alt="image" src="https://github.com/user-attachments/assets/91dffbd0-3e61-4069-9b0b-6f1f23341325">
<img width="872" alt="image" src="https://github.com/user-attachments/assets/a5b32790-2dbe-43e5-b1a4-31efe8624c89">
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/23271910-2a9b-49ee-8bd3-4e2af1322c58">
<img width="756" alt="image" src="https://github.com/user-attachments/assets/a0bbefdc-9848-41e9-aad1-393289348e07">
找不到宿主机容器

**Comment by twosson** [comment]
物理机转宿主机的时候, 是否需要连公网才行, 不知道是否需要下载容器.

**Comment by zexi** [comment]
> 物理机转宿主机的时候, 是否需要连公网才行, 不知道是否需要下载容器.

在控制节点上用 kubectl get nodes 看这个节点有没有添加进来，如果添加进来就看下这个节点上的 pod 为什么没有运行起来

**Comment by zexi** [comment]
@twosson 如果这个节点上的 default-host pod 运行起来了，就用 kubectl logs -c host 看下这个容器的日志，里面会有相关的报错，可以参考这个文档排查：https://www.cloudpods.org/docs/getting-started/onpremise/quickstart-virt#1-%E5%9C%A8-all-in-one-%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%AE%BF%E4%B8%BB%E6%9C%BA%E5%88%97%E8%A1%A8%E6%B2%A1%E6%9C%89%E5%AE%BF%E4%B8%BB%E6%9C%BA

**Comment by twosson** [comment]
<img width="848" alt="image" src="https://github.com/user-attachments/assets/b32bffc2-ebf1-4d31-be4c-3f48f0f749a0">
[host-convert-v39-20230404.qcow2](https://iso.yunion.cn/vm-images/host-convert-v39-20230404.qcow2)
这个版本不一致, 我主节点的版本是3.11.6, 不知道是否是这个问题. @zexi

**Comment by twosson** [comment]
kubectl get nodes 没有新加节点.

**Comment by shuoshadow** [comment]
我遇到了同样的问题，kubectl get node没有新的节点加入
