### ISSUE TITLE
[求助/Help]小系统不支持“FAT-fs: codepage cp437”

### ISSUE THREAD

**Issue by vincentiss** [yunionio/cloudpods#21110]
求助：
      把小系统mdadm打开后，做了raid，然后装系统 分区，更新grub的时候碰到找不到efi分区的问题，原因是挂载不上fat的分区。

```
        # mount /dev//md0p15 /mnt/boot/efi/
        mount: /mnt/boot/efi: wrong fs type, bad option, bad superblock on /dev/md0p15, missing codepage or helper 
        program, or other error.
        # dmesg |tail
        [ 1230.088079] FAT-fs (md0p15): codepage cp437 not found
```

请问buildroot的config修改哪一项能支持这个啊？？
万分感谢啊！！

**Comment by zexi** [comment]
这是 initramfs 系统里面报的错误，还是 grub shell 里面的错误？

**Comment by vincentiss** [comment]
> 这是 initramfs 系统里面报的错误，还是 grub shell 里面的错误？

是在initramfs里面

**Comment by vincentiss** [comment]
@zexi

**Comment by vincentiss** [comment]
@zexi 
用mdadm做完软raid，执行完安装操作系统脚本后
重启的话主机找不到efi分区，软raid 分区等信息也看不到了
所以猜测是不是需要更新grub，执行grub-install的时候碰到的此问题

**Comment by vincentiss** [comment]
@zexi 大佬 有什么建议吗

**Comment by Ezio-y** [comment]
> @zexi 用mdadm做完软raid，执行完安装操作系统脚本后 重启的话主机找不到efi分区，软raid 分区等信息也看不到了 所以猜测是不是需要更新grub，执行grub-install的时候碰到的此问题

在内存系统创建软raid，相关配置需要覆写到磁盘对应的系统目录下。不然机器重启后进硬盘系统怎么加载对应的软raid配置呢。而且真的有必要把系统部署在软raid创建的盘上吗？
