### ISSUE TITLE
[BUG]新建块存储里参考文档跳转链接已经失效

### ISSUE THREAD

**Issue by Lotusrootsoup** [yunionio/cloudpods#21119]
新建块存储里参考文档跳转链接已经失效了。
![微信截图_20240828173150](https://github.com/user-attachments/assets/cdb560cf-6981-4213-83d2-f9c7b455a56e)
![微信截图_20240828173219](https://github.com/user-attachments/assets/e2c5bc6d-7b48-421e-b2d5-2610c28aaf34)
![微信截图_20240828173247](https://github.com/user-attachments/assets/56fa1d80-4d7d-465b-961b-f41b739e55df)

**Comment by wanyaoqi** [comment]
@GuoLiBin6  这里需要更新一下 https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage
