### ISSUE TITLE
[求助/Help]vsphere使用v2v迁移虚拟机时遇到报错（目标为UEFI模式的虚拟机）

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21122]
bios模式虚拟机正常迁移；
uefi模式windows ubuntu 都报以下错误
错误消息:
参数错误
create converted server: db.DoCreate: {"error":{"class":"InputParameterError","code":400,"data":{"id":"UEFI boot mode requires UEFI image"},"details":"UEFI boot mode requires UEFI image"}}
错误源信息:
{
  "class": "InputParameterError",
  "code": 400,
  "details": "create converted server: db.DoCreate: {\"error\":{\"class\":\"InputParameterError\",\"code\":400,\"data\":{\"id\":\"UEFI boot mode requires UEFI image\"},\"details\":\"UEFI boot mode requires UEFI image\"}}",
  "request": {
    "body": {
      "server": {
        "target_hypervisor": "esxi"
      }
    },
    "headers": {
      "Content-Length": "39",
      "Content-Type": "application/json",
      "User-Agent": "yunioncloud-go/201708",
      "X-Auth-Token": "*",
      "X-Request-Id": "b36c57",
      "X-Yunion-Lang": "zh-CN",
      "X-Yunion-Parent-Id": "0",
      "X-Yunion-Peer-Service-Name": "apigateway",
      "X-Yunion-Remote-Addr": "default-region:30888",
      "X-Yunion-Span-Id": "0.0",
      "X-Yunion-Span-Name": "",
      "X-Yunion-Strace-Debug": "true",
      "X-Yunion-Strace-Id": "a2dbae55"
    },
    "method": "POST",
    "url": "https://default-region:30888/servers/dc309c04-96b2-4684-83e5-942f32dc5113/convert-to-kvm"
  },
  "time": "2024-08-29T21:08:59+08:00"
} 
请求:
{
  "method": "post",
  "url": "/v2/servers/convert-to-kvm",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json;charset=utf-8",
    "x-yunion-lang": "zh-CN"
  },
  "data": {
    "target_hypervisor": "esxi"
  },
  "params": {
    "id": [
      "dc309c04-96b2-4684-83e5-942f32dc5113"
    ]
  }
}

**Comment by wanyaoqi** [comment]
@nashzosi 看一下 vmware虚机对应的镜像是否设置了 UEFI引导的属性

**Comment by nashzosi** [comment]
是的，做了这样的设置，是图上这里吗？
<img width="857" alt="image" src="https://github.com/user-attachments/assets/7a87a785-98f5-4134-bb4e-67a944c8cbf7">
<img width="825" alt="image" src="https://github.com/user-attachments/assets/e41c7085-35b0-4c91-8e0e-42a054cc90cb">

**Comment by wanyaoqi** [comment]
@nashzosi 你在 cloudpods 平台点开 vmware 虚机详情查看系统镜像的引导类型是否为 UEFI呢
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/c2fe2dca-d47d-4081-8cec-6c72451589fb">

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/0ac51bb1-d0ea-4383-8d4c-387f0b7a9309">

**Comment by nashzosi** [comment]
这是虚拟机的引导方式，我的虚拟机没有系统镜像

![WeChat74a4cf7fbcd7d9e96544c8e11e88abfd](https://github.com/user-attachments/assets/ad35533e-1c79-4b0c-b311-360f9bde4aec)
能迁移的成功的虚拟机也不显示系统镜像
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/5fa3cfe8-d1fa-4158-914c-2bed18954f2f">

**Comment by nashzosi** [comment]
我的控制节点都是arm的架构 这个镜像不能运行，是否有arm版本的镜像？

**Comment by wanyaoqi** [comment]
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240830-3-arm64}]' 
试试这个

**Comment by nashzosi** [comment]
很开心收到到您的帮助，目前我的节点还是无法启动
necloud              default-region-586f4956f4-cmhln                      1/1     Running                 0          151m    10.40.23.8      node3master    <none>           <none>
onecloud              default-region-5b597567d8-ctb9k                      0/1     Init:CrashLoopBackOff   6          9m19s   10.40.23.36     node3master    <none>           <none>
我正在找原因中。。

**Comment by nashzosi** [comment]
我到对应node上使用docker logs 检查了对应 的init容器和其他相关联的容器，确认没有任何日志输出，docker应该是在启动后马上退出了，不知是否镜像存在问题

**Comment by wanyaoqi** [comment]
建议 `kubectl logs -n onecloud default-region-5b597567d8-ctb9k -c init` ，有时候要用 -p 看上一个退出容器的日志

**Comment by nashzosi** [comment]
很奇怪确实没有日志打印
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/148c6037-2ceb-4c15-b3c3-3adc10406d73">

**Comment by wanyaoqi** [comment]
@nashzosi 没有任何日志确实很奇怪，可以尝试把 deployment 的command 都改成 sleep ，然后手动执行相关命令调试一下

**Comment by wanyaoqi** [comment]
@nashzosi 更新这个吧： kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240903-1-arm64}]'

**Comment by nashzosi** [comment]
已成功启动，我来验证下最开始的问题是不是解决了 非常感谢

**Comment by nashzosi** [comment]
目前又遇到了新的问题：
1、windows迁移的时候会报错，感觉是识别成了linux
deploying=>deploy_fail: {"__reason__":"Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = [DetectRootFs with partition /dev/sda1 no root fs found, DetectRootFs with partition /dev/sda2 no root fs found, DetectRootFs with partition /dev/sda4 no root fs found]: NotFoundError","__stage__":"OnDeployGuestComplete","__status__":"error"}
<img width="825" alt="image" src="https://github.com/user-attachments/assets/1d3103e5-9cf9-48dd-a9f0-9812be561e24">
2、ubuntu 的uefi迁移过来无法启动
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/ae8da88b-53e1-454f-9a2e-0b25a191ca5e">

**Comment by nashzosi** [comment]
在cloudpods 平台查看也是widows系统，上面的图能看的出来，新创建的xxx-kvm 变成了linux

**Comment by nashzosi** [comment]
迁移完成的主机。没有系统盘只显示 数据盘
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/9f57f0f2-69b2-4ba7-b875-88532997e2b3">

**Comment by wanyaoqi** [comment]
@nashzosi 看起来是没有识别到系统盘，你在磁盘那里看下驱动使用的是什么，改成ide驱动试试

**Comment by nashzosi** [comment]
@wanyaoqi 改成ide成功启动了，widows迁移失败的事情麻烦帮忙看下

**Comment by wanyaoqi** [comment]
@nashzosi 得看下host-deployer 服务日志，目前是看起来没有找到rootfs

**Comment by nashzosi** [comment]
windows和linux 同时批量v2v时候会出现这个问题，单独v2v迁移windows的时候不会出现这个问题，目前我的问题都已经解决了，感谢支持

**Comment by wanyaoqi** [comment]
@nashzosi 有可能是 windows 磁盘部署的时候挂载超时了，可能是装换时网络IO太慢导致的，可以看host-deployer 日志

**Comment by nashzosi** [comment]
在vsphere侧正常开关机一次虚拟机即可同步成功
