### ISSUE TITLE
[求助/Help]k3s 启用物理机管理服务失败

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21120]
```shell
root@cloudpods-master01:~# ocadm baremetal enable --node cloudpods-master01 --listen-interface br0
error execution phase enable-baremetal-agent/enable-baremetl-agent: [preflight] couldn't create Kubernetes client: failed to load admin kubeconfig: open /etc/kubernetes/admin.conf: no such file or directory
```

**Comment by shuoshadow** [comment]
一直处于Pending状态
![image](https://github.com/user-attachments/assets/53eb0279-5a46-4258-96f6-861dbd9e071e)

**Comment by shuoshadow** [comment]
pv没有创建出来
![image](https://github.com/user-attachments/assets/479b16ea-561e-4497-b792-ecea77c0d043)
![image](https://github.com/user-attachments/assets/8df763a7-5c4a-4274-9786-94a947cf97d7)

**Comment by zexi** [comment]
@shuoshadow 我这边使用 k3s 的环境测试，没有复现出来这个问题，用下面命令给对应节点打了标签就创建出来了：
```
kubectl label nodes $node_name onecloud.yunion.io/baremetal=enable
```

**Comment by shuoshadow** [comment]
@zexi 
Back-off pulling image "rancher/mirrored-library-busybox:1.36.1" 是镜像没拉下来...
![image](https://github.com/user-attachments/assets/8c93175c-c6f1-42a6-a4cb-06f99ddaa3f1)

**Comment by zexi** [comment]
> @zexi Back-off pulling image "rancher/mirrored-library-busybox:1.36.1" 是镜像没拉下来... ![image](https://private-user-images.githubusercontent.com/10016360/362559304-8c93175c-c6f1-42a6-a4cb-06f99ddaa3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM1NjEsIm5iZiI6MTcyNDkxMzI2MSwicGF0aCI6Ii8xMDAxNjM2MC8zNjI1NTkzMDQtOGM5MzE3NWMtYzZmMS00MmE2LWE0Y2ItMDZmOTlkZGFhM2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA2MzQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MjdkZDk4Y2Y1YzYwOWQ1NzI3YzBmNWJjNTdlYmU4YzJhMzNhNDRlY2YzNTM3MTJkZjYzYjAzYTNlNGY3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jgfgIIdyPzuBrQ-HzKeZ1zA8EVIR4m1YlkpXxWhigAk)

@shuoshadow 那就是这个节点网络的问题了，手动用这个命令拉取试试 `k3s ctr images pull docker.io/rancher/mirrored-library-busybox:1.36.1`

**Comment by shuoshadow** [comment]
![image](https://github.com/user-attachments/assets/f58256c5-0e39-4291-8935-c061040447ce)
拉取中，可能是访问外网不稳定的原因 @zexi   这个镜像地址可以在哪里配置更改呢？

**Comment by shuoshadow** [comment]
通过代理拉镜像解决了 感谢 @zexi
