### ISSUE TITLE
[BUG] uefi 的镜像被探测成了 bios legacy 引导

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#21149]
**问题描述/What happened**:

- 导入镜像：https://iso.yunion.cn/vm-images/host-convert-uefi-v39-20230404.qcow2
- 然后平台显示：

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/085734ff-b614-4d9b-804f-a8175518c185">

**环境/Environment**:

v3.11.6 的版本

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/pull/21176
