### ISSUE TITLE
[BUG]desktop 密码重置

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#21158]
**问题描述/What happened**:
1、使用镜像 Ubuntu Desktop 22 创建虚拟机 ，初始化用户 clouduser，安装 qemu-guest-agent，使用该虚拟机创建 主机镜像
2、新建的主机展示的是 root 用户的账号跟密码（实际上 Desktop 默认是禁止 root 登录的）
![image](https://github.com/user-attachments/assets/1f583ddd-97ad-49cb-ba3c-b088fb15d7d5)
3、点击右侧功能按钮，重置 clouduser 用户名跟随机密码，列表面板中仍展示的是 root 用户的账号密码，没有地方查看 clouduser 用户生产的随机值。（可以通过 手工输入 的方式设置）

期望：通过页面中设置的用户名跟密码，最后一笔，应该更新到 列表的密码查下 中。

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
@elvizlai 目前后台只会记录创建时指定的用户名密码，只有你修改创建时的用户比如root才会记录密码。
确实存在其他用户随机生成密码无法查看的问题，这里不应该允许随机生成密码

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/7170
