### ISSUE TITLE
[BUG] 创建谷歌云虚拟机设置root管理员密码，虚拟机运行后无法使用密码ssh登录

### ISSUE THREAD

**Issue by xiezhihuan** [yunionio/cloudpods#21156]
**问题描述/What happened**:
创建谷歌云虚拟机设置root管理员密码，虚拟机运行后无法使用密码ssh登录。
```
cat /etc/ssh/sshd_config.d/60-cloudimg-settings.conf 
PasswordAuthentication no
```
发现谷歌云在sshd_config.d目录下配置了不允许密码登录。

**环境/Environment**:
cloudpods v3.10.15

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
fixed: https://github.com/yunionio/pkg/pull/136
