### ISSUE TITLE
[求助/Help]用ocboot k3s的方式安装cloudpods时，如何修改k3s的的cluster-cidr和service-cidr网段

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21162]
默认的网段和本地网络冲突了，希望能修改成其他网段，应该怎么做？

**Comment by zexi** [comment]
> 默认的网段和本地网络冲突了，希望能修改成其他网段，应该怎么做？

@shuoshadow 部署的 config-allinone-current.yml 配置文件里面可以修改，然后用： `ocboot.sh install config-allinone-current.yml`

<img width="465" alt="image" src="https://github.com/user-attachments/assets/6680bb28-3b4f-4c97-8f10-1c2c868bbf73">

需要注意的是要在集群运行起来之前修改，部署之后就该不了，只有 uninstall 后重新部署。

**Comment by shuoshadow** [comment]
执行了./scripts/uninstall-k3s.sh并删除了mysql数据库后，再执行./ocboot.sh install config-allinone-current.yml报错
![image](https://github.com/user-attachments/assets/ed8a3383-8e60-4b03-a64b-5f884a1c753e)

**Comment by shuoshadow** [comment]
重新执行了k3s的安装步骤，已解决
