### ISSUE TITLE
[求助/Help]k3s 计算节点加入集群报认证错误token.go:82] [discovery] Failed to request cluster info, will try again: [Unauthorized]

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21168]
1、计算节点机器上 /etc/sysconfig/yunionauth 文件中没有API_SREVER地址
![image](https://github.com/user-attachments/assets/9ce2f94b-feb1-4517-9702-0972a2d56568)

2、手动执行/opt/yunion/bin/ocadm join 10.10.107.14:6443 --enable-host-agent --token i0hz99.ka7c607qyyy1s1ai --discovery-token-unsafe-skip-ca-verification -v 9  报错如下
![image](https://github.com/user-attachments/assets/136d0f41-f276-4dac-9fcd-b7a15c226775)

求助如何解决这个问题？现在加的宿主机都不能用

**Comment by zexi** [comment]
@shuoshadow k3s 部署的环境目前不支持物理机转换成宿主机，可以手动用 ocboot 添加

**Comment by shuoshadow** [comment]
@zexi 明白了谢谢，后续k3s会支持物理机转宿主机吗？

**Comment by zexi** [comment]
> @zexi 明白了谢谢，后续k3s会支持物理机转宿主机吗？

会支持
