### ISSUE TITLE
[BUG] 部署了单节点模式纳管openstack连接成功后不显示云资源是什么原因

### ISSUE THREAD

**Issue by czj8888-s** [yunionio/cloudpods#21188]
**问题描述/What happened**:
目前根据3.11部署了单节点模式纳管openstack连接成功后不显示云资源是什么原因呢

**环境/Environment**: 3.11版本Ocboot;      openstack版本 3.14.2

**Comment by czj19981205** [comment]
> **问题描述/What happened**: 目前根据3.11部署了单节点模式纳管openstack连接成功后不显示云资源是什么原因呢
> 
> **环境/Environment**: 3.11版本Ocboot; openstack版本 3.14.2

**Comment by ioito** [comment]
点下云账号同步，等待云账号同步完成后，贴下 region 服务这段时间的日志

**Comment by czj19981205** [comment]
您看下这个对吗
![2](https://github.com/user-attachments/assets/fe200d5e-0604-4ac5-b53d-d525d3e59083)

**Comment by czj19981205** [comment]
![3](https://github.com/user-attachments/assets/fc431788-10ee-4239-83af-10a33d30c6e2)

**Comment by ioito** [comment]
https://www.cloudpods.org/docs/development/devtools#%E8%8E%B7%E5%8F%96%E8%B0%83%E7%94%A8%E6%A0%88 参考这个，需要拿到后端服务日志，需要有命令行基础

**Comment by czj19981205** [comment]
![1](https://github.com/user-attachments/assets/c6fa090d-61d9-4871-bc5f-794147de3975)
![2](https://github.com/user-attachments/assets/4e88c60e-efec-41e6-bb85-b3d3b80a4c20)

**Comment by ioito** [comment]
导出1小时的日志文件，贴到这里，你截图里面没有任何有用信息

**Comment by czj19981205** [comment]
是这个吗，进入到region的pod时无法执行这个操作kubectl logs -n onecloud default-region-684bbf6c44-dcjlf --tail 10 -f
![Uploading 4.png…]()

**Comment by czj19981205** [comment]
是执行这个命令kubectl logs -n onecloud default-region-684bbf6c44-dcjlf --tail 10 -f执行一小时后粘贴出来吗

**Comment by ioito** [comment]
kubectl logs -n onecloud default-region-684bbf6c44-dcjlf --since=1h > region.log
把日志收集后贴出来
后面学下命令行基础及kubectl命令行参数

**Comment by czj19981205** [comment]
[region.log](https://github.com/user-attachments/files/16928943/region.log)
好的，辛苦您看下

**Comment by ioito** [comment]
kubectl logs -n onecloud default-region-684bbf6c44-dcjlf --since=2h > region.log
越过了云账号同步那段时间了，导出前2小时的日志，再贴下日志

**Comment by czj19981205** [comment]
[region.log](https://github.com/user-attachments/files/16929016/region.log)
您看下

**Comment by czj19981205** [comment]
好的，我再试下，我这个日期好像不对，我查看操作日志写的都是9.10号的不知道是不是这个原因，最新的我还在导出中
![image](https://github.com/user-attachments/assets/e19b7c6c-defe-4e69-9dca-7d38618037da)

**Comment by czj19981205** [comment]
![image](https://github.com/user-attachments/assets/0b244848-c7cf-4a8b-b014-65491d8f88af)
zhe'g这个同步时间显示8小时后

**Comment by czj19981205** [comment]
[region.log](https://github.com/user-attachments/files/16929210/region.log)
您看下这次同步过的3小时的

**Comment by ioito** [comment]
<img width="1445" alt="image" src="https://github.com/user-attachments/assets/f0de441a-0895-42e9-a571-a2b04b929444">
openstack环境中的各个endpoint有问题，先把endpoint调对
