### ISSUE TITLE
[求助/Help]ubuntu系统安装后无法远程登陆

### ISSUE THREAD

**Issue by tocha688** [yunionio/cloudpods#21182]
我远程登陆一直提示用户密码错误，已经[配置了ubuntudebian镜像优化](https://www.cloudpods.org/docs/guides/onpremise/glance/sysimage/create/#centos%E9%95%9C%E5%83%8F%E4%BC%98%E5%8C%96)还是无法登陆，镜像是从社区镜像商店下载的

已经尝试修改root密码，还是不能远程ssh连接，但是通过远程控制进去然后su root登陆就正常

**Comment by swordqiu** [comment]
@tocha688 是不是ubuntu desktop的镜像？

**Comment by tocha688** [comment]
系统镜像->社区镜像 里面下载的

**Comment by tocha688** [comment]
不是禁止root登陆，我用系统远程控制ssh进去然后输入su root就可以登陆，但是我用FinalShell远程连接一直提示密码错误，密码是我复制的，不会有错，我都试了好几次，centos正常，ubuntu不行

**Comment by zexi** [comment]
@tocha688 看下 /etc/ssh/sshd_config 里面是不是禁止了 root login ?

**Comment by swordqiu** [comment]
@tocha688 我们验证是Ubuntu社区镜像默认lock了root账号，我们后续版本会处理这种情况。临时解决方案是通过 cloudroot  web ssh登录后，执行 passwd -u root 解锁 root

**Comment by tocha688** [comment]
> 我们验证是Ubuntu社区镜像默认锁定了root账号，我们后续版本会处理这种情况。临时解决方案是通过 cloudroot web ssh登录后，执行 passwd -u root 解锁 root

还是不行执行了passwd -u root，还是无法通过远程ssh登陆root账户，我用的finalshell
