### ISSUE TITLE
[求助/Help]能否通过Cloudpods进行SSH类型的物理机服务器托管？

### ISSUE THREAD

**Issue by devVoyagerNinja** [yunionio/cloudpods#21187]
针对已安装Linux系统并配置了SSH的物理机服务器，但未配置BMC信息且未接入IPMI。尝试通过Cloudpods进行托管时，发现需要BMC信息或IPMI接入。请问Cloudpods是否支持通过SSH进行物理机服务器的托管？或者有其他方式来跳过IPMI等必须项。

**Comment by zexi** [comment]
@devVoyagerNinja 命令行支持，前端界面目前没有支持，使用方式如下：
```bash
climc host-create--no-bmc --access-net $子网 testhost $PXE网卡MAC
```
然后把物理机 pxe 启动

**Comment by devVoyagerNinja** [comment]
@zexi 感谢您的回答。我想咨询的是，物理机已经安装好了linux操作系统并且配置了 SSH 信息，我希望通过 Cloudpods 对这些机器进行管理，这样需要如何操作或者如何注册？

**Comment by zexi** [comment]
> @zexi 感谢您的回答。我想咨询的是，物理机已经安装好了linux操作系统并且配置了 SSH 信息，我希望通过 Cloudpods 对这些机器进行管理，这样需要如何操作或者如何注册？

这种模式没有支持
