### ISSUE TITLE
[求助/Help]如何给虚拟机重新关联镜像缓存和镜像文件

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21204]
版本3.11.6
宿主机原先规划硬盘不足，经过一些列的瞎操作，把虚拟机关联的镜像和镜像缓存搞丢了
求助：如何给虚拟机重新关联镜像缓存和镜像文件，目前已经使用了一样的镜像，并且有一样的镜像缓存

原目录：/opt/cloud/workspace/disks/image_cache/  
新目录：/opt/cloud/workspace/disks2/image_cache/ 

镜像缓存的文件移动到/opt/cloud/workspace/disks2/image_cache/ 目录了，系统里的关联关系丢失了

**Comment by wanyaoqi** [comment]
把镜像拷贝到新的目录
修改 /etc/yunion/host.conf : image_cache_path 这个配置
已有的磁盘使用 qemu-img rebase 命令rebase到新的目录下的缓存

**Comment by nashzosi** [comment]
偶然发现，不用重新关联
找到镜像,系统时间长了会自己更新
<img width="789" alt="image" src="https://github.com/user-attachments/assets/04e44be5-8176-4097-8bdd-a842de1e52de">
有新的相同镜像上传后还回自己关联（待验证）

**Comment by nashzosi** [comment]
非常感谢 @wanyaoqi
