### ISSUE TITLE
[求助/Help]虚拟机迁移时候报错，鲲鹏to飞腾

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21203]
版本3.11.6
报错日志：
migrating=>migrate_failed: "get storage migrate conf: setCpuNumaPin: unmarshal cpu_numa_pin: Get: key not found"

"get storage migrate conf: setCpuNumaPin: unmarshal cpu_numa_pin: Get: key not found"

鲲鹏宿主机上的 kylinv10系统，迁移至沸腾s2500cpu宿主机时候迁移失败；

**Comment by nashzosi** [comment]
+------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      Field       |                                                                                                                             Value                                                                                                                             |
+------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| bios             | BIOS                                                                                                                                                                                                                                                          |
| boot_order       | cdn                                                                                                                                                                                                                                                           |
| cpu              | 1                                                                                                                                                                                                                                                             |
| cpu_sockets      | 1                                                                                                                                                                                                                                                             |
| description      | 张三                                                                                                                                                                                                                                                        |
| disks            | [{"aio_mode":"native","boot_index":-1,"bps":0,"cache_mode":"none","disk_id":"189b45a3-7081-4f0e-8aa2-de741c5dd694","driver":"scsi","format":"qcow2","image_path":"/opt/cloud/workspace/disks2/image_cache/37e0f40b-fabd-41c4-84bb-c18fcaafb128","index":0,"io |
|                  | ps":0,"is_ssd":true,"merge_snapshot":false,"migrating":false,"num_queues":0,"path":"/opt/cloud/workspace/disks2/189b45a3-7081-4f0e-8aa2-de741c5dd694","size":40960,"storage_id":"f9ec3545-72ce-4b0c-8e95-79c1f15ec298","storage_type":"local","template_id":" |
|                  | 37e0f40b-fabd-41c4-84bb-c18fcaafb128","throughput":0}]                                                                                                                                                                                                        |
| domain           | cloud.onecloud.io                                                                                                                                                                                                                                             |
| domain_id        | default                                                                                                                                                                                                                                                       |
| host_id          | 1b19d396-2a5c-4ea0-8f9e-c8cc308c189c                                                                                                                                                                                                                          |
| hostname         | host01                                                                                                                                                                                                                                                        |
| is_daemon        | false                                                                                                                                                                                                                                                         |
| is_volatile_host | false                                                                                                                                                                                                                                                         |
| light_mode       | false                                                                                                                                                                                                                                                         |
| machine          | pc                                                                                                                                                                                                                                                            |
| mem              | 1024                                                                                                                                                                                                                                                          |
| metadata         | {"__cpu_mode":"host","__enable_cgroup_cpuset":"true","__os_profile__":"{\"disk_driver\":\"scsi\",\"fs_format\":\"ext4\",\"hypervisor\":\"kvm\",\"net_driver\":\"virtio\",\"os_type\":\"Linux\"}","__qemu_cmdline":"$QEMU_CMD $QEMU_CMD_KVM_ARG -S -cpu host - |
|                  | chardev socket,id=hmqmondev,port=55935,host=127.0.0.1,nodelay,server,nowait -mon chardev=hmqmondev,id=hmqmon,mode=readline -chardev socket,id=qmqmondev,port=56135,host=127.0.0.1,nodelay,server,nowait -mon chardev=qmqmondev,id=qmqmon,mode=control -rtc ba |
|                  | se=utc,clock=host,driftfix=none -nodefaults -no-user-config  -machine virt,accel=kvm,gic-version=max -k en-us -smp cpus=1,sockets=2,cores=64,maxcpus=128 -name 'server1',debug-threads=on -uuid ca345d78-e6ce-44c0-8252-768ac708005f -m 1024M,slots=4,maxmem=26 |
|                  | 2144M -object memory-backend-ram,id=mem,size=1024M -numa node,memdev=mem -boot cdn -drive if=pflash,format=raw,unit=0,file=/opt/cloud/contrib/OVMF.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/opt/cloud/workspace/servers/ca345d78-e6ce-44c0-825 |
|                  | 2-768ac708005f/OVMF_VARS.fd -device virtio-gpu-pci,id=video0,bus=pcie.0,addr=0x01,max_outputs=1 -vnc :35,password -object iothread,id=iothread0 -device virtio-serial-pci,id=virtio-serial0,bus=pcie.0,addr=0x02 -device pcie-pci-bridge,id=pci.1,bus=pcie.0, |
|                  | addr=0x04 -device pci-bridge,id=pci.2,bus=pci.1,chassis_nr=2,addr=0x01 -device ioh3420,id=pci.3,chassis=3,bus=pcie.0,addr=0x05 -device ioh3420,id=pci.4,chassis=4,bus=pcie.0,addr=0x06 -device virtio-scsi-pci,id=scsi,bus=pcie.0,addr=0x03 -drive file=$DISK |
|                  | _0,if=none,id=drive_0,cache=none,aio=native,file.locking=off -device scsi-hd,serial=189b45a370814f0e8aa2de741c5dd694,drive=drive_0,bus=scsi.0,id=drive_0,rotation_rate=1 -netdev type=tap,id=vlan521-249,ifname=vlan521-249,vhost=on,vhostforce=off,script=/o |
|                  | pt/cloud/workspace/servers/ca345d78-e6ce-44c0-8252-768ac708005f/if-up-br1-vlan521-249.sh,downscript=/opt/cloud/workspace/servers/ca345d78-e6ce-44c0-8252-768ac708005f/if-down-br1-vlan521-249.sh -device virtio-net-pci,id=netdev-vlan521-249,bus=pci.2,addr= |
|                  | 0x01,netdev=vlan521-249,mac=00:22:b8:cb:44:84$(nic_speed 1000) -device qemu-xhci,id=usb,bus=pcie.0,addr=0x07 -device usb-tablet,id=input0,bus=usb.0,port=1 -device usb-kbd,id=input1,bus=usb.0,port=2 -pidfile /opt/cloud/workspace/servers/ca345d78-e6ce-44c |
|                  | 0-8252-768ac708005f/pid   -chardev socket,id=qga0,server,nowait,path=/opt/cloud/workspace/servers/ca345d78-e6ce-44c0-8252-768ac708005f/qga.sock -device virtserialport,bus=virtio-serial0.0,chardev=qga0,name=org.qemu.guest_agent.0 -object rng-random,id=rn |
|                  | g0,filename=/dev/urandom -device virtio-rng-pci,id=random0,bus=pcie.0,addr=0x08,max-bytes=1024,period=1000,rng=rng0","__qemu_version":"4.2.0","__ssh_port":"0","__vnc_password":"j6PfGV4g","__vnc_port":"35","bios":"UEFI","cls:disks_info":"“”","create_para |
|                  | ms":"{\"__count__\":1,\"__meta__\":{\"user:BU\":\"部门1\"},\"__os_profile__\":{\"disk_driver\":\"scsi\",\"fs_format\":\"ext4\",\"hypervisor\":\"kvm\",\"net_driver\":\"virtio\",\"os_type\":\"Linux\"},\"auto_start\":true,\"bios\":\"UEFI\",\"count\":1,\ |
|                  | "deploy_telegraf\":true,\"description\":\"张三\",\"disks\":[{\"backend\":\"local\",\"disk_type\":\"sys\",\"driver\":\"scsi\",\"image_id\":\"37e0f40b-fabd-41c4-84bb-c18fcaafb128\",\"image_properties\":{\"arch\":\"aarch64\",\"disk_format\":\"qcow2\",\"d |
|                  | istro\":\"Kylin\",\"installed_cloud_init\":\"false\",\"is_lvm_partition\":\"false\",\"is_readonly\":\"false\",\"os_arch\":\"aarch64\",\"os_distribution\":\"Kylin\",\"os_language\":\"\",\"os_type\":\"Linux\",\"os_version\":\"V10\",\"partition_type\":\"\" |
|                  | ,\"uefi_support\":\"false\",\"version\":\"V10\"},\"index\":0,\"iops\":0,\"medium\":\"ssd\",\"os_arch\":\"aarch64\",\"size\":40960,\"storage_id\":\"3e17e71b-9eab-4469-8ef2-0d7649fe1180\",\"throughput\":0}],\"domain\":\"default\",\"domain_id\":\"default\" |
|                  | ,\"hostname\":\"host01\",\"hypervisor\":\"kvm\",\"instance_type\":\"ecs.g1.c1m1\",\"machine\":\"virt\",\"name\":\"host01\",\"nets\":[{\"bw_limit\":1000,\"domain_id\":\"default\",\"driver\":\"virtio\",\"exit\":false,\"index\":0,\"is_default\":true,\"num_ |
|                  | queues\":0,\"private\":false,\"project_id\":\"0e3faf868d034b778b5e6ac6c9626bb4\",\"require_designated_ip\":false,\"require_ipv6\":false,\"require_teaming\":false,\"reserved\":false,\"rx_traffic_limit\":0,\"standby_addr_count\":0,\"standby_port_count\":0 |
|                  | ,\"try_teaming\":false,\"tx_traffic_limit\":0,\"vip\":false}],\"os_arch\":\"aarch64\",\"os_type\":\"Linux\",\"prefer_region\":\"default\",\"prefer_region_id\":\"default\",\"prefer_zone\":\"090c28df-5d26-4e1f-8a9c-a6f9b4d012f9\",\"prefer_zone_id\":\"090c |
|                  | 28df-5d26-4e1f-8a9c-a6f9b4d012f9\",\"project\":\"0e3faf868d034b778b5e6ac6c9626bb4\",\"project_domain\":\"default\",\"project_domain_id\":\"default\",\"project_id\":\"0e3faf868d034b778b5e6ac6c9626bb4\",\"schedtags\":[{\"id\":\"9210f371-e966-4eea-88d1-1b5 |
|                  | 89d2bcf6f\",\"resource_type\":\"hosts\",\"strategy\":\"require\",\"weight\":0}],\"secgrp_id\":\"default\",\"sku\":\"ecs.g1.c1m1\",\"tenant\":\"0e3faf868d034b778b5e6ac6c9626bb4\",\"tenant_id\":\"0e3faf868d034b778b5e6ac6c9626bb4\",\"vcpu_count\":1,\"vdi\" |
|                  | :\"\",\"vga\":\"\",\"vmem_size\":1024}","disks_info":"[{aio_mode:native,boot_index:-1,bps:0,cache_mode:none,disk_format:qcow2,disk_type:sys,driver:scsi,id:189b45a3-7081-4f0e-8aa2-de741c5dd694,image:Kylin-Server-V10-SP3-General-Release-2303,image_id:37e0 |
|                  | f40b-fabd-41c4-84bb-c18fcaafb128,index:0,iops:0,medium_type:ssd,name:vdisk-host01-1722243217342862290-1,preallocation:off,size:40960,storage_id:f9ec3545-72ce-4b0c-8e95-79c1f15ec298,storage_type:local}]","generate_name":"host##","hot_remove_nic":"enable" |
|                  | ,"hotplug_cpu_mem":"enable","last_login_key":"84gh7SbR3fRIZ9RhakOo/uutW6iX7wrMZ1dlNg==","login_account":"root","login_key":"84gh7SbR3fRIZ9RhakOo/uutW6iX7wrMZ1dlNg==","login_key_timestamp":"2024-09-10T06:54:31.864069Z","old_name":"host01","os_arch":"aarc |
|                  | h64","os_distribution":"Kylin","os_name":"Linux","os_version":"V10","start_vcpu_count":"1","start_vmem_mb":"1024","telegraf_deployed":"true","user:BU":"部门1"}                                                                                            |
| name             | server1                                                                                                                                                                                                                                                         |
| nics             | [{"bridge":"br1","bw":1000,"dns":"172.16.0.100,172.16.0.200","domain":"cloud.onecloud.io","driver":"virtio","gateway":"172.16.21.1","ifname":"vlan521-249","index":0,"interface":"enp125s0f1","ip":"172.16.21.249","is_default":true,"link_up":false,"mac":"00:22 |
|                  | :b8:cb:44:84","masklen":24,"masklen6":0,"mtu":1500,"net":"vlan521","net_id":"3ecaa2aa-8f32-40b7-800a-fdbd3e5dbf08","ntp":"172.16.0.10,172.16.0.20","num_queues":1,"rate":0,"rx_traffic_limit":0,"tx_traffic_limit":0,"virtual":false,"vlan":521,"wire_id":"8919 |
|                  | badf-9687-43d0-8c2b-a7b25e0e76e6"}]                                                                                                                                                                                                                           |
| os_name          | Linux                                                                                                                                                                                                                                                         |
| pending_deleted  | false                                                                                                                                                                                                                                                         |
| project_domain   | Default                                                                                                                                                                                                                                                       |
| secgroups        | [{"id":"default","name":"Default"}]                                                                                                                                                                                                                           |
| security_rules   | in:allow any                                                                                                                                                                                                                                                  |
| src_ip_check     | true                                                                                                                                                                                                                                                          |
| src_mac_check    | true                                                                                                                                                                                                                                                          |
| tenant           | 部门1                                                                                                                                                                                                                                                      |
| tenant_id        | bcfe25b4d21f43198367b0c1b8ca91e1                                                                                                                                                                                                                              |
| uuid             | ca345d78-e6ce-44c0-8252-768ac708005f                                                                                                                                                                                                                          |
| vdi              | vnc                                                                                                                                                                                                                                                           |
| vga              | std                                                                                                                                                                                                                                                           |
| zone             | 北京                                                                                                                                                                                                                                                  |
| zone_id          | 090c28df-5d26-4e1f-8a9c-a6f9b4d012f9                                                                                                                                                                                                                          |
+------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by nashzosi** [comment]
<img width="2265" alt="image" src="https://github.com/user-attachments/assets/d9a047dd-8692-4ddb-877e-40ec2dc2cedf">
附一个图片格式方便阅读

**Comment by wanyaoqi** [comment]
@nashzosi 再提供一下源端和目的端宿主机的信息 climc host-show <ID> |grep enable_numa_allocate

**Comment by nashzosi** [comment]
源宿主机：
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/d479b3c1-3fbb-41b3-ada8-720dda57d0ec">
目的宿主机：
<img width="965" alt="image" src="https://github.com/user-attachments/assets/c641c2cb-e91e-49e4-a632-421b4d8bf224">

**Comment by nashzosi** [comment]
@wanyaoqi 可以再帮忙看看？发现同型号的物理机迁移也会报这个错误

**Comment by wanyaoqi** [comment]
@nashzosi 更新一下region再试试 kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240913-4}]'

**Comment by nashzosi** [comment]
@wanyaoqi 老哥帮忙打个arm64的包，我是arm的环境
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/ccca2340-2c13-43b7-84ec-580ac21a6f77">

**Comment by wanyaoqi** [comment]
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240914-1-arm64}]'

**Comment by nashzosi** [comment]
<img width="1712" alt="image" src="https://github.com/user-attachments/assets/5e781cf7-02e4-4bc7-9213-2bde21935627">
@wanyaoqi 老师，无法启动，修改为debug也没有日志产生

**Comment by wanyaoqi** [comment]
kubectl patch oc -n onecloud default --type='json' -p='[{op: replace, path: /spec/regionServer/imageName, value: region},{op: replace, path: /spec/regionServer/repository, value: registry.cn-hangzhou.aliyuncs.com/d3lx},{op: add, path: /spec/regionServer/tag, value: v20240914-2-arm64}]' @nashzosi 用这个吧

**Comment by nashzosi** [comment]
鲲鹏920to鲲鹏920 确认热迁移成功，正在测试 鲲鹏920to飞腾s2500冷迁移
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/eb6abb81-d1cc-4726-b35d-4769f3e3717c">
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/97c67da3-f4c7-42e4-8092-f01da3065ab5">

**Comment by nashzosi** [comment]
@wanyaoqi 问题解决了，感谢老师！
