### ISSUE TITLE
[求助/Help] 已建虚拟机如何修改cloud-init配置

### ISSUE THREAD

**Issue by 66545shiwo** [yunionio/cloudpods#21223]
已建好的虚拟机没有找到可以修改自定义数据地方，也就是cloud-init的配置，请问下支持吗？

![Uploading 1726190348792.jpg…]()

**Comment by 66545shiwo** [comment]
![1726190348792](https://github.com/user-attachments/assets/a59d9925-50bc-4da2-90a2-dfeae9d9c4c4)

**Comment by ioito** [comment]
climc server-set-user-data 可以设置，但目前也就支持第一次启动才有效

**Comment by 66545shiwo** [comment]
@ioito 假如我修改的是`bootcmd`命令，重启会生效吧

**Comment by ioito** [comment]
cloudpods提供了访问user-data的能力，
curl http://169.254.169.254/latest/user-data 可以看到user-data的信息
更改后user-data，重启后访问也会更新
至于重启生效，需要你研究cloud-init怎么每次重启都初始化
fix: https://github.com/yunionio/cloudpods/pull/21238/files
