### ISSUE TITLE
[求助/Help]使用cloudpods虚拟机来部署k8s集群时，使用cilium cni插件的native route模式无法跨节点访问pod ip

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21237]
大家有遇到过这样的问题吗？是否是cloudpods虚拟化底层的影响呢？
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/386ba949-dd7d-40ad-9a4e-0123b2a592c1">

只有使用vxlan模式才能互通，这个有人遇到过吗？我有点怀疑是cloudpods本身虚拟主机导致的问题

**Comment by swordqiu** [comment]
@shuoshadow 需要把cloudpods虚拟机的”源和目的IP检查“关闭

**Comment by shuoshadow** [comment]
@swordqiu 感谢回复，请问这个关闭“源和目的IP检查”应该怎么操作呢？有文档或者操作方法吗？

**Comment by shuoshadow** [comment]
@swordqiu 找到了，终于解决了，非常感谢！！！

**Comment by swordqiu** [comment]
@shuoshadow ”源和目的检查“开启后，平台只允许虚拟机使用平台分配的IP地址收发报文，这样虚拟机就不能作为一个网关设备做转发。

**Comment by shuoshadow** [comment]
> @shuoshadow ”源和目的检查“开启后，平台只允许虚拟机使用平台分配的IP地址收发报文，这样虚拟机就不能作为一个网关设备做转发。

那么是通过什么方式实现的呢？想了解下原理

**Comment by shuoshadow** [comment]
> @shuoshadow 基于ovs流表实现的”源和目的地址检查“

感谢！学到了
