### ISSUE TITLE
[BUG] 使用k3s 部署完成之后，访问页面 静态资源无法找到

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#21269]
**问题描述/What happened**:

使用 `k3s` 部署完成之后，访问前端页面 `https://x.x.x.x` 页面一直显示空白，打开控制台，发现`css` 等资源都404 

![image](https://github.com/user-attachments/assets/a50cd938-40e6-4856-bfbc-c6cd10742a16)

![image](https://github.com/user-attachments/assets/4fd4d4a5-27e3-478a-99fe-60b4f828461e)

**环境/Environment**:

OS : openEuler 22.03 (SP3)
cloudpods: v3.10.8

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
> ### 这里的 `pathType` 应该使用 `Prefix` 吧？
> ![image](https://private-user-images.githubusercontent.com/54271145/368896502-6abfc9cb-ba60-455c-8818-3b1d6f64112b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzMwNTksIm5iZiI6MTcyNjczMjc1OSwicGF0aCI6Ii81NDI3MTE0NS8zNjg4OTY1MDItNmFiZmM5Y2ItYmE2MC00NTVjLTg4MTgtM2IxZDZmNjQxMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NmE4NWQyYWRmNTU4NDk2MDI5ZjY4Nzc1OTZiYjM4NzYzMDBkNzZlYzliYWU0YTBkYmNkYTE3NTRiMjk1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ed5vkgeFsQe_UHvB-68SXgg8Tm_grrW9TyZqOgibEJU)

是的，改成 Prefix 试试？

**Comment by zexi** [comment]
@huhaiqwer 我看 3.11.6 版本部署的 ingress 已经把 pathType 设置成 Prefix 了，应该是你部署的版本太老了

**Comment by huhaiqwer** [comment]
> @huhaiqwer 我看 3.11.6 版本部署的 ingress 已经把 pathType 设置成 Prefix 了，应该是你部署的版本太老了

是的 我部署的是 `v3.10.8` 版本，我修改成 `Prefix` 已经可以正常使用了

**Comment by huhaiqwer** [comment]
> @huhaiqwer 我看 3.11.6 版本部署的 ingress 已经把 pathType 设置成 Prefix 了，应该是你部署的版本太老了

这里还有一个问题 使用 `k3s` 部署完成之后 `default-etcd` 起不来，我排查了以下，应该是 `ClusterRole`  - > `system:coredns` 没有 `discovery.k8s.io` 这个的权限，我加了以下 `list` 和 `watch` 的权限 , `default-etcd` 可以正常运行了，你们有时间可以本地看看 。我使用的版本是 `v3.10.8` 不知道你们新版本有没有修复

**Comment by huhaiqwer** [comment]
@zexi  李老师，请问 部署的时候设估计内核，需要机器重启，然后机器已经重启完成了，但是ocboot 一直卡在重启这一步，这个咋解决呀？ 得等了半个多小时了，机器我可以正常 ssh
![image](https://github.com/user-attachments/assets/1344027f-50ec-4ce4-a92f-51fc8b3e5afa)

**Comment by zexi** [comment]
> @zexi 李老师，请问 部署的时候设估计内核，需要机器重启，然后机器已经重启完成了，但是ocboot 一直卡在重启这一步，这个咋解决呀？ 得等了半个多小时了，机器我可以正常 ssh ![image](https://private-user-images.githubusercontent.com/54271145/369348381-1344027f-50ec-4ce4-a92f-51fc8b3e5afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjUzNjAsIm5iZiI6MTcyNjgyNTA2MCwicGF0aCI6Ii81NDI3MTE0NS8zNjkzNDgzODEtMTM0NDAyN2YtNTBlYy00Y2U0LWE5MmYtNTFmYzhiM2U1YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNzIxMjY2YWIyNDUxZGRhNTk2NTZmMTFlN2VjMWEwNjlkNWQzNDQzMWE0MTY5YjZiY2ZhY2E3Y2NkNmYyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NV2yLQTFzKlluBIV0e0AIbVMElVl_rfLExeCUpFdLIA)

ocboot 用的那个分支的代码？

**Comment by huhaiqwer** [comment]
@zexi  3.10.14

**Comment by zexi** [comment]
> @zexi 3.10.14

建议用最新 release/3.11 代码试试

**Comment by huhaiqwer** [comment]
> > @zexi 3.10.14
> 
> 建议用最新 release/3.11 代码试试

ok

**Comment by huhaiqwer** [comment]
@zexi  李老师，可以请教一下 `ocadm` 服务怎么打成 `rpm` 包吗，我看 `.md` 上面没写。。。

**Comment by zexi** [comment]
> @zexi 李老师，可以请教一下 `ocadm` 服务怎么打成 `rpm` 包吗，我看 `.md` 上面没写。。。

k3s 部署的版本不再需要 ocadm 了，如果要打 rpm 可以参考这个脚本：https://github.com/yunionio/ocadm/blob/master/hack/make-package.sh

**Comment by huhaiqwer** [comment]
@zexi  李老师 这里是否有问题  
![image](https://github.com/user-attachments/assets/303473a2-0d3b-4c54-8d69-23b5a6addc27)
 这个 task  必须 nbd = false 并且 kernel_installed.rc = 1 的时候执行 ，如果 nbd = ok  但是 kernel_installed.rd = 1 那这个任务就会被跳过 那下面的任务  

![image](https://github.com/user-attachments/assets/8a6fce92-15cf-4c58-84ad-28d669f7810a)

test : uname -r | grep -qE '{{ kernel_regex }} 返回永远是空 这个任务就一直卡在这里了

**Comment by zexi** [comment]
release/3.11 没有这些问题了，建议用这个版本部署。
