### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hewenxiang** [yunionio/cloudpods#21267]
**问题描述/What happened**:
![image](https://github.com/user-attachments/assets/95d69f89-f240-42c8-80c4-48aa2b25141d)

![image](https://github.com/user-attachments/assets/2b73a462-46a7-40ad-813b-7e296db33e65)

获取镜像这儿取值有问题 caches[i].Id, image.Id) 两个id都是空
**环境/Environment**:
v3.11.6

**Comment by ioito** [comment]
可以sql查下这俩记录，贴下信息么

**Comment by hewenxiang** [comment]
@ioito 
![image](https://github.com/user-attachments/assets/7aedd2ed-dd22-4d82-ab4a-d554e1eb51ca)
![image](https://github.com/user-attachments/assets/5cb20c7d-0b7f-4c1d-9b49-b4befdf22125)
![image](https://github.com/user-attachments/assets/f4e17ff6-0ef5-4f3a-85ec-cc4dd93a57ae)
![image](https://github.com/user-attachments/assets/a464a61b-a894-4a6c-ad24-d0c54fed6edd)

**Comment by ioito** [comment]
image.Id不是有值么

**Comment by hewenxiang** [comment]
@ioito 但是代码那里没有取到啊

**Comment by ioito** [comment]
加下日志，打印下image的详细信息
