### ISSUE TITLE
[求助/Help] 启动虚拟机后host日志中qmp显示timeout

### ISSUE THREAD

**Issue by StartZYP** [yunionio/cloudpods#21273]
![image](https://github.com/user-attachments/assets/bd64f039-9f90-4b7a-973f-041f5862f126)
错误日志如图所示
我在宿主机用ps aux |grep qemu 查看了qemu进程会在10秒钟左右被关闭,telnet 这个qmp端口是通的

**Comment by swordqiu** [comment]
@StartZYP 可能是这个虚拟机镜像有问题，启动没多久就自动退出了
