### ISSUE TITLE
[求助/Help]更换虚拟机ip，一直卡在QGA配置网卡

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21270]
重置密码操作能成功可以一定程度证明QGA正常工作
经典网络迁移至经典网络
从vlan6迁移至vlan7时一直卡在QGA配置网卡，并且网络没有切换成功；
重新同步虚拟机状态后，web界面ip更新为更换后的IP
重启虚拟机ip还是原来的IP

查看host相关组件没有找到日志，寻求帮助

### **QGA 版本，QGA 支持的命令信息：**
[root@Node1Primary ~]# climc server-qga-command xxxxxxxxx-kvm-1 '{"execute": "guest-info"}'
supported_commands:
- enabled: true
  name: guest-get-osinfo
  success-response: true
- enabled: true
  name: guest-get-timezone
  success-response: true
- enabled: true
  name: guest-get-users
  success-response: true
- enabled: true
  name: guest-get-host-name
  success-response: true
- enabled: true
  name: guest-exec
  success-response: true
- enabled: true
  name: guest-exec-status
  success-response: true
- enabled: true
  name: guest-get-memory-block-info
  success-response: true
- enabled: true
  name: guest-set-memory-blocks
  success-response: true
- enabled: true
  name: guest-get-memory-blocks
  success-response: true
- enabled: true
  name: guest-set-user-password
  success-response: true
- enabled: true
  name: guest-get-fsinfo
  success-response: true
- enabled: true
  name: guest-set-vcpus
  success-response: true
- enabled: true
  name: guest-get-vcpus
  success-response: true
- enabled: true
  name: guest-network-get-interfaces
  success-response: true
- enabled: true
  name: guest-suspend-hybrid
  success-response: false
- enabled: true
  name: guest-suspend-ram
  success-response: false
- enabled: true
  name: guest-suspend-disk
  success-response: false
- enabled: true
  name: guest-fstrim
  success-response: true
- enabled: true
  name: guest-fsfreeze-thaw
  success-response: true
- enabled: true
  name: guest-fsfreeze-freeze-list
  success-response: true
- enabled: true
  name: guest-fsfreeze-freeze
  success-response: true
- enabled: true
  name: guest-fsfreeze-status
  success-response: true
- enabled: true
  name: guest-file-flush
  success-response: true
- enabled: true
  name: guest-file-seek
  success-response: true
- enabled: true
  name: guest-file-write
  success-response: true
- enabled: true
  name: guest-file-read
  success-response: true
- enabled: true
  name: guest-file-close
  success-response: true
- enabled: true
  name: guest-file-open
  success-response: true
- enabled: true
  name: guest-shutdown
  success-response: false
- enabled: true
  name: guest-info
  success-response: true
- enabled: true
  name: guest-set-time
  success-response: true
- enabled: true
  name: guest-get-time
  success-response: true
- enabled: true
  name: guest-ping
  success-response: true
- enabled: true
  name: guest-sync
  success-response: true
- enabled: true
  name: guest-sync-delimited
  success-response: true
version: 2.12.0
### **虚拟机内部网卡配置：**
DEVICE=eth0
NAME=eth0
ONBOOT=yes
NM_CONTROLLED=yes
USERCTL=no
MTU=1500
HWADDR=00:50:56:bc:57:c6
MACADDR=00:50:56:bc:57:c6
BOOTPROTO=dhcp
### **界面截图：**
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/3d86cbf1-6ab4-4eae-870f-58567a10257f">

**Comment by wanyaoqi** [comment]
@nashzosi 看下region日志

**Comment by nashzosi** [comment]
[change.log](https://github.com/user-attachments/files/17092704/change.log)
@wanyaoqi 老师，日志比较多，不好抓，确实有一些error，不知是不是有关系
QGA配置网卡 这个状态会一直持续，没有后续报错，另外我发现 我其他虚拟机通过dhcp拿不到地址，配置静态ip网络正常，考虑网络设备上有什么限制，目前还在查找，您看看日志有什么建议不

**Comment by wanyaoqi** [comment]
@nashzosi 这个日志看着正常，一般是看下region和host服务日志，再看看host服务日志呢

**Comment by nashzosi** [comment]
@wanyaoqi 暂时先关闭，我把全部的vsphere资源迁移到cloudpods后，删除那些重复的网络后再试，目前服务均正常
