### ISSUE TITLE
[求助/Help] K3S 部署提示拉不到镜像，我手动已经拉到镜像了

### ISSUE THREAD

**Issue by SunVdong** [yunionio/cloudpods#21286]
![image](https://github.com/user-attachments/assets/b5e3b637-5d87-4195-8785-5a78b33de0fc)
如上图所示。

**Comment by zexi** [comment]
@SunVdong 要用 k3s ctrl images pull 拉取

**Comment by SunVdong** [comment]
![image](https://github.com/user-attachments/assets/81a69605-8d76-42f5-8d96-5d2f341ea228)
还是不行

> @SunVdong 要用 k3s ctrl images pull 拉取
