### ISSUE TITLE
[求助/Help]从vSpheve迁移两个虚拟磁盘组成的lvm分区时会报错找不到root分区，怀疑是有bug

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21304]
版本：3.11.6

问题：
从vSpheve迁移两个虚拟磁盘组成的lvm分区时会报错找不到root分区
新创建的虚拟机为转换失败状态，同步状态后可以变更为已关机，开机后能正常进入到系统，再等待一段时间，会变更为：数据复制中

怀疑是有bug
报错如下：
{
    "__reason__": {
        "reason": {
            "__reason__": "Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = [DetectRootFs with partition /dev/sda1 no root fs found, DetectRootFs with partition /dev/sda2 no root fs found]: NotFoundError",
            "__stage__": "OnDeployGuestComplete",
            "__status__": "error"
        },
        "stage": "OnDeployGuestComplete"
    },
    "__stage__": "OnGuestConvertDoDeployGuest",
    "__status__": "error",
    "__task_name__": "GuestDeployTask"
}

**Comment by wanyaoqi** [comment]
@nashzosi 目前是不支持两个磁盘做Lvm的系统盘的

**Comment by nashzosi** [comment]
好滴，谢谢老师，实际上我迁移成功了
新创建的虚拟机为转换失败状态
同步状态后可以变更为已关机
开机后能正常进入到系统
再等待一段时间，会变更为：数据复制中
