### ISSUE TITLE
[BUG] 新建虚拟机 部署失败

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#21306]
**问题描述/What happened**:

新建虚拟机 部署失败 ，报错如下 
![image](https://github.com/user-attachments/assets/96ed2203-077c-4a45-87ae-e1a07f580423)

点击同步，然后再同步一下状态，就这样正常运行了，但是第一次新建的时候，必现这个报错

**环境/Environment**:
OS: `openEuler 22.03 SP3`
version: v3.10.8

**Comment by huhaiqwer** [comment]
查看日志 如下 
![image](https://github.com/user-attachments/assets/dece71d2-023f-4ef5-ade0-d316ff3da4f6)

**Comment by huhaiqwer** [comment]
![image](https://github.com/user-attachments/assets/c90e5b8b-3279-4bd9-a944-55fdd904bc67)

**Comment by wanyaoqi** [comment]
@huhaiqwer 什么版本，host-deployer 和onecloud-operator版本可能对不上

**Comment by huhaiqwer** [comment]
> @huhaiqwer 什么版本，host-deployer 和onecloud-operator版本可能对不上
host-deployer : v3.10.8
onecloud-operator: v3.10.8

**Comment by huhaiqwer** [comment]
@wanyaoqi  大佬，请问这个 22223 端口，是什么服务的，难道是 `onecloud-operator` 没有拉全所有的服务吗？

**Comment by wanyaoqi** [comment]
@wanyaoqi 你看下onecloud-operator是否有报错，这个原因是因为host-deployer 没开启 hostNetwork，需要operator更新一下 daemonset，可能是operator没更新

**Comment by huhaiqwer** [comment]
@wanyaoqi 我看了下 `host-deployer` 这个 `ds` 发现它并没有 开启 hostNetwork ，请问这个需要手动开启吗？ 我们生产环境的 `host-deployer` 也是没有开启 hostNetwork的 但是 可以正常使用。查看 `operator` 的日志，发现并没有什么明显错误 
![image](https://github.com/user-attachments/assets/c2c4fddb-11f0-4654-b84f-994879e32f1f)

**Comment by huhaiqwer** [comment]
@wanyaoqi 我在计算节点宿主机上  发现 `22223` 端口并没有在监听呀。

**Comment by wanyaoqi** [comment]
@huhaiqwer 版本不一样吧，新版本部署是通过起虚机端口连接上去部署的，要求开启hostNetwork

**Comment by huhaiqwer** [comment]
@wanyaoqi 大佬你指的是。`host-deployer` 与 `operator` 的版本不一致导致的吗？

**Comment by wanyaoqi** [comment]
> @wanyaoqi 大佬你指的是。`host-deployer` 与 `operator` 的版本不一致导致的吗？

@huhaiqwer 不是，我说生产环境和这个环境。这个环境我建议升级一下，升级到最新的3.10

**Comment by huhaiqwer** [comment]
@wanyaoqi ok,感谢大佬，还有一个问题请教以下，我这个环境部署完成之后 缺少了以下 `pods`，请问这是什么原因，这些组件主要是用来干嘛的，是否影响整体服务运行。
![image](https://github.com/user-attachments/assets/e9b680e2-b7af-440b-9cad-2d9735b2a5b7)

**Comment by wanyaoqi** [comment]
@huhaiqwer 这些是日志收集和minio相关的，不影响服务

**Comment by huhaiqwer** [comment]
@wanyaoqi 继上次的问题 现在新建虚拟机 一直卡在 分配磁盘上面，并且新建虚拟机的时候，到了分配磁盘这一步，会自动重启宿主机。我查询机器日志也没有发现 `重启的原因` 请问这个问题这么排查，大佬
![image](https://github.com/user-attachments/assets/d6abf75c-8fd3-482e-950a-2e3d51a56be2)

**Comment by wanyaoqi** [comment]
@huhaiqwer 这个理论上应该不会导致宿主机重启，你需要排查一下宿主机重启的原因，看看dmesg, 重试一下看看能否复现

**Comment by huhaiqwer** [comment]
我发现了  新建虚拟机的时候，如果 勾选 安装 `agent` 监控，就会重新上述的错误，请问，安装 agent 监控 会涉及到重启 宿主机吗 

![image](https://github.com/user-attachments/assets/362feecd-02ce-48d1-a6a1-0fed3b720368)

**Comment by huhaiqwer** [comment]
@wanyaoqi 大佬，请问计算机点拉起的虚拟机使用 vpc 网络，即 `overlay网络`后，正常情况下宿主机可以 `ping` 通虚拟机吗

**Comment by huhaiqwer** [comment]
@wanyaoqi 大佬。昨天那个宿主机重启的问题我找到必现的一个步骤了，有一个 `qcow2` 镜像，使用这个镜像拉起虚拟机，宿主机就会重启，重新上传这个镜像，宿主机也会重启。
![image](https://github.com/user-attachments/assets/009101f2-5596-44f6-9736-a4b9212078c1)

**Comment by huhaiqwer** [comment]
可以看到 上传快完成的时候， `CONNECTION_CLOSED` 了，我查询 dmesg 也没有有用的信息

![image](https://github.com/user-attachments/assets/c72b69d4-08da-4ed7-b374-42a9e6856a80)

dmesg 信息如下 
![image](https://github.com/user-attachments/assets/1fb5ae06-bf93-450c-a32c-aacf66109b45)

**Comment by wanyaoqi** [comment]
@huhaiqwer 这个镜像有什么特别吗，宿主机的配置是什么

**Comment by huhaiqwer** [comment]
@wanyaoqi  这个宿主机就是从你们官方下载的 centos7 的镜像，宿主机配置如下 没什么特别的，现在就是不知道如何排查 宿主机重启的原因 。。。
![image](https://github.com/user-attachments/assets/ccd75550-c081-4ecf-8766-a9e64c75a65e)

![image](https://github.com/user-attachments/assets/6f1bd22c-e6ab-429b-ae58-eeb5824bafde)

![image](https://github.com/user-attachments/assets/1e40b2ee-dc23-49eb-8f6e-92e0ea335c5c)

**Comment by huhaiqwer** [comment]
cloudpods版本是 v3.10.8

**Comment by huhaiqwer** [comment]
@wanyaoqi 大佬，我捕捉了一下内核日志，麻烦分析一下 这是导致宿主机重启的原因吗？ OS: openEuler 22.03 SP3 
看日志 好像是 kubelet 引起的？

![image](https://github.com/user-attachments/assets/392edcf6-c50c-4e95-bc45-3a354889abd3)

**Comment by wanyaoqi** [comment]
> @wanyaoqi 大佬，我捕捉了一下内核日志，麻烦分析一下 这是导致宿主机重启的原因吗？ OS: openEuler 22.03 SP3 看日志 好像是 kubelet 引起的？
> 
> ![image](https://private-user-images.githubusercontent.com/54271145/374845531-392edcf6-c50c-4e95-bc45-3a354889abd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTgwODIsIm5iZiI6MTcyODQ1Nzc4MiwicGF0aCI6Ii81NDI3MTE0NS8zNzQ4NDU1MzEtMzkyZWRjZjYtYzUwYy00ZTk1LWJjNDUtM2EzNTQ4ODlhYmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMzk0YWExOWZiMWU3Yjg2ZjVkZTg0OWRhNTFhNWY2OWI0NDQ1YjU4YWI3ZTIwNzhiYmFjMGU3MDA5MmQ3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VCXnFHqDGRSkGxvFjpUcxL5Rlf0MxBOjLF2HDUG7d_s)

@huhaiqwer 看起来是 kubelet 触发的，好像是读文件系统导致的

**Comment by huhaiqwer** [comment]
@wanyaoqi 大佬，那这个问题咋解决，能麻烦帮忙提供一下解决思路吗。。。 我看拉起虚拟机或者上传系统镜像的时候，有很大概率会触发重启

**Comment by wanyaoqi** [comment]
@huhaiqwer 感觉是宿主机内核有问题

**Comment by huhaiqwer** [comment]
@wanyaoqi 宿主机内核时  openEuler 22.03 SP3 5.10.0-230.0.0.132.oe2203sp3.x86_64
你们官方支持的欧拉是这个内核吗

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/cloudpods/issues/21366
