### ISSUE TITLE
[求助/Help]ubuntu22,04部署3.10版本Ocboot出现故障，是不持支ubuntu部署吗，https://iso.yunion.cn/deb-updates/x86 64/拉不下来东西

### ISSUE THREAD

**Issue by czj8888-s** [yunionio/cloudpods#21300]
![image](https://github.com/user-attachments/assets/81b3040f-342c-4ff5-8fa6-f8a69f6b9c5e)
![4d506f7eda37d69f8223b5698d1206d](https://github.com/user-attachments/assets/4cf77443-92ff-4ec7-a89e-863fbcd0389f)
![1fc6d3e0ad420c342c944cab9f57180](https://github.com/user-attachments/assets/142ec8e3-a8fa-4c2c-ad83-2866ce5a727d)
![ec02ca3987b54be81417ab3b2f1625a](https://github.com/user-attachments/assets/1a6466d6-f281-40c0-bdd4-07be1740c903)

**Comment by swordqiu** [comment]
@czj8888-s 看日志是网络问题？无法解析 mirrors.aliyun.com

**Comment by czj8888-s** [comment]
想问下咱们有离线的部署模式吗，有没有离线部署的包，我们这个边网络配置需要走代理DNS无法解析咱们的https://iso.yunion.cn/这个网址

**Comment by ioito** [comment]
离线部署仅商业版提供，开源版不提供

**Comment by czj8888-s** [comment]
好的，我们再看下
