### ISSUE TITLE
[BUG] 无法上传系统镜像  glance 报错说 资源重名

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#21303]
**问题描述/What happened**:

上传系统镜像，上传到 50+% 之后 无法上传，查看 `glance` 日志 报错如下, 每次 大概上传到 `500M` 的时候，就会报错

![image](https://github.com/user-attachments/assets/98393a00-067d-49c7-8c75-a54e12c3de6e)

![image](https://github.com/user-attachments/assets/ae6caea0-5945-47a9-ad99-f89959bdfc21)

![image](https://github.com/user-attachments/assets/25f3bab6-c8e0-473c-83fa-4075174cdde9)

**环境/Environment**:
OS: `openEuler 22.03 SP3`
cloudpods: `v3.10.8`

**Comment by huhaiqwer** [comment]
不是资源重名，是地区文件资源 EOF 这个问题在我们环境必现，请问如何排查解决？

**Comment by ioito** [comment]
换浏览器试试

**Comment by huhaiqwer** [comment]
> 换浏览器试试 
@ioito  屈老师，使用 `chrome` `edge` 都是这样 

使用上传方式 `上传镜像文件` 的时候必先

![image](https://github.com/user-attachments/assets/6c32a8fb-477f-4fde-9a35-506027c23e0f)

**Comment by ioito** [comment]
查下web的日志

**Comment by huhaiqwer** [comment]
> 查下web的日志

问题排查出来了  升级traefik的版本为 v3.1 默认的超时时间是 1min ，修改了参数可以正常使用了。
