### ISSUE TITLE
[求助/Help]物理机创建裸金属之后，裸金属的网络和正常网络并不通

### ISSUE THREAD

**Issue by love-seeker** [yunionio/cloudpods#21362]
我无法通过所分配的ip地址和mac地址，找到对应的主机，而且无法连接上罗金属
![image](https://github.com/user-attachments/assets/2a407f77-6b33-4f0b-9231-513880e03d07)
![image](https://github.com/user-attachments/assets/e9598eec-67d7-46cd-ad0f-313785925144)
有没有一个可行的解决思路，能否参考一下

**Comment by zexi** [comment]
通过带外管理远程看下有没有启动进入硬盘的操作系统？
