### ISSUE TITLE
[BUG]主机-存储-主机快照-删除panic异常

### ISSUE THREAD

**Issue by elvizlai** [yunionio/cloudpods#21361]
**问题描述/What happened**:

错误信息
```
{
    "__reason__": {
        "reason": "runtime error: invalid memory address or nil pointer dereference",
        "stage": "OnRequestSnapshot"
    },
    "__stage__": "OnKvmSnapshotDelete",
    "__status__": "error",
    "__task_name__": "SnapshotDeleteTask"
}
```

**本快照对应的虚拟机已删除，删除快照时，报以上错误**

<img width="419" alt="image" src="https://github.com/user-attachments/assets/c65d7dcd-a36c-4891-b51d-0471bd3fcc9a">

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

Get "https://172.20.1.200:30893/version": dial tcp 172.20.1.200:30893: connect: connection refused
Get "https://172.20.1.200:30892/version": dial tcp 172.20.1.200:30892: connect: connection refused
Get "https://172.20.1.200:30898/version": dial tcp 172.20.1.200:30898: connect: connection refused
Get "https://172.20.1.200:30443/version": dial tcp 172.20.1.200:30443: connect: connection refused
+---------------+--------------------------------------------+
|     Field     |                   Value                    |
+---------------+--------------------------------------------+
| ansible       | release/3.11.7(97ac72090c24100314)         |
| apimap        | release/3.11.7(97ac72090c24100314)         |
| cloudmon      | release/3.11.7(97ac72090c24100315)         |
| cloudproxy    | release/3.11.7(97ac72090c24100314)         |
| compute_v2    | release/3.11.7(97ac72090c24100315)         |
| devtool       | release/3.11.7(97ac72090c24100314)         |
| identity      | release/3.11.7(97ac72090c24100314)         |
| image         | release/3.11.7(97ac72090c24100314)         |
| k8s           | heads/v3.11.7-20241002.1(9661fc2f24100314) |
| log           | release/3.11.7(97ac72090c24100315)         |
| monitor       | release/3.11.7(97ac72090c24100315)         |
| notify        | release/3.11.7(97ac72090c24100314)         |
| scheduledtask | release/3.11.7(97ac72090c24100315)         |
| scheduler     | release/3.11.7(97ac72090c24100315)         |
| vpcagent      | release/3.11.7(97ac72090c24100315)         |
| webconsole    | release/3.11.7(97ac72090c24100314)         |
| yunionconf    | release/3.11.7(97ac72090c24100315)         |
+---------------+--------------------------------------------+

**Comment by wanyaoqi** [comment]
fixed: https://github.com/yunionio/cloudpods/pull/21367
