### ISSUE TITLE
[求助/Help] 多云主机分配给用户权限如何配置

### ISSUE THREAD

**Issue by opcache** [yunionio/cloudpods#21405]
场景：多云主机分配给用户权限，比如分配给某用户，阿里云三台机器权限（aaa,bbb,ccc），AWS两台机器权限（eee,fff），这个用户可以查看这些主机信息，可以对这些主机开机，关机操作，这个可以配置吗？能支持吗？

**Comment by ioito** [comment]
可以配置，将用户和机器放到同一个项目底下
