### ISSUE TITLE
[BUG] Package installation error during adding a new ubuntu(22.04) node to cluster

### ISSUE THREAD

**Issue by cnjack** [yunionio/cloudpods#21419]
**问题描述/What happened**:
Add new node: `./ocboot.sh add-node 192.168.10.246 192.168.10.80`. get error
```
failed: [192.168.10.80] (item=[33/37] yunion-qemu-4.2.0) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "changed": false, "item_index": 32, "msg": "No package matching 'yunion-qemu-4.2.0' is available", "package_item": "yunion-qemu-4.2.0"}
failed: [192.168.10.80] (item=[34/37] docker-ce) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "changed": false, "item_index": 33, "msg": "No package matching 'docker-ce' is available", "package_item": "docker-ce"}
failed: [192.168.10.80] (item=[35/37] kubeadm=1.15.12-00) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "changed": false, "item_index": 34, "msg": "No package matching 'kubeadm' is available", "package_item": "kubeadm=1.15.12-00"}
failed: [192.168.10.80] (item=[36/37] kubectl=1.15.12-00) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "changed": false, "item_index": 35, "msg": "No package matching 'kubectl' is available", "package_item": "kubectl=1.15.12-00"}
failed: [192.168.10.80] (item=[37/37] kubelet=1.15.12-00) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "changed": false, "item_index": 36, "msg": "No package matching 'kubelet' is available", "package_item": "kubelet=1.15.12-00"}
```

execute `apt update` on new node, get error 
```
Err:9 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ Packages
  404  Not Found [IP: 180.163.57.12 443]
Ign:10 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ Translation-en_US
Ign:11 https://iso.yunion.cn/ubuntu/22/base/x86_64 ./ Translation-en
Err:12 https://iso.yunion.cn/deb-updates/x86_64 ./ Packages
  404  Not Found [IP: 180.163.57.12 443]
Ign:13 https://iso.yunion.cn/deb-updates/x86_64 ./ Translation-en
Ign:14 https://iso.yunion.cn/deb-updates/x86_64 ./ Translation-en_US
Reading package lists... Done
E: Failed to fetch https://iso.yunion.cn/ubuntu/22/base/x86_64/./Packages  404  Not Found [IP: 180.163.57.12 443]
E: Failed to fetch https://iso.yunion.cn/deb-updates/x86_64/./Packages  404  Not Found [IP: 180.163.57.12 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- Kernel (e.g. `uname -a`):Linux scgzfw4 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
        idProduct: 0xa102
        Manufacturer: 80AD863280AD
        Manufacturer: AMD
        Manufacturer: DELL
        Manufacturer: Dell Inc.
        Manufacturer: Not Specified
        Memory Subsystem Controller Manufacturer ID: Unknown
        Memory Subsystem Controller Product ID: Unknown
        Module Manufacturer ID: Unknown
        Module Product ID: Unknown
        Product Name: 0T4KXC
        Product Name: PowerEdge R7525
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by zexi** [comment]
@cnjack 已恢复

**Comment by cnjack** [comment]
Thanks

**Comment by swordqiu** [comment]
请用v3.11.12以上版本
