### ISSUE TITLE
[求助/Help] 请教下K3S部署cloudpods如何更新版本？

### ISSUE THREAD

**Issue by Lotusrootsoup** [yunionio/cloudpods#21410]
请教两个问题：
K3S部署cloudpods如何更新版本？
cloudpods如何设置创建虚拟机不绑定硬件使用率，比如说一台主机配置十核CPU、10G内存分配给八核8G内存给一台虚拟机使用，这台虚拟机关机了，我还建同样配置副本虚拟机来使用.

**Comment by zexi** [comment]
> K3S部署cloudpods如何更新版本？
1. 参考文档升级：https://www.cloudpods.org/docs/operations/upgrading/ocboot-upgrade

> cloudpods如何设置创建虚拟机不绑定硬件使用率，比如说一台主机配置十核CPU、10G内存分配给八核8G内存给一台虚拟机使用，这台虚拟机关机了，我还建同样配置副本虚拟机来使用.
没有太理解这个问题，前端页面那里的虚拟机有创建相同配置的功能。如果虚拟机关机了，就不会使用这个宿主机的 cpu 和内存。

**Comment by Lotusrootsoup** [comment]
@zexi 就是创建相同配置虚拟机就提示配置不够，我必须删除关机虚拟机还要在回收站清空才能创建成功。

**Comment by zexi** [comment]
> @zexi 就是创建相同配置虚拟机就提示配置不够，我必须删除关机虚拟机还要在回收站清空才能创建成功。

可以看下是哪些配置不够了，然后调整对应资源的超售比
