### ISSUE TITLE
[求助/Help]高可用部署问题（v3.11.8）

### ISSUE THREAD

**Issue by yiranlianji** [yunionio/cloudpods#21435]
参考官网文档部署私有云高可用版本，部署脚本卡在了最后一步，看到的现象是服务只部署了一部分，之后就停了，尝试删除pod重建，但结果还是一样。
![1](https://github.com/user-attachments/assets/ec8b92bf-b225-45b4-ac5f-87722c121837)
![2](https://github.com/user-attachments/assets/e113c326-6cec-494d-90d4-f2d4676f17a1)

后面使用ocboot以 All in One 的方式部署私有云版本，没有问题，部署完可以访问平台。
请帮忙指导一下看是哪里的问题？

**Comment by zexi** [comment]
高可用部署的时候，用  kubectl get pods -n onecloud 看下都有哪些 pod ?

**Comment by yiranlianji** [comment]
> 高可用部署的时候，用 kubectl get pods -n onecloud 看下都有哪些 pod ?

第2张图片上就是全部的。

**Comment by zexi** [comment]
> > 高可用部署的时候，用 kubectl get pods -n onecloud 看下都有哪些 pod ?
> 
> 第2张图片上就是全部的。

需要把当时 onecloud-operator 这个 pod 的日志导出来看下，里面应该有报错信息。

**Comment by yiranlianji** [comment]
> > > 高可用部署的时候，用 kubectl get pods -n onecloud 看下都有哪些 pod ?
> > 
> > 
> > 第2张图片上就是全部的。
> 
> 需要把当时 onecloud-operator 这个 pod 的日志导出来看下，里面应该有报错信息。

定位到问题了，MinIO导致的，将true改为false，不使用MinIO作为镜像存储就好了。
```shell
# 使用 minio 作为后端虚拟机镜像存储
  enable_minio: true
```
