### ISSUE TITLE
[BUG]region镜像版本从3.10.5升级到3.11后，华为云无法更新标签

### ISSUE THREAD

**Issue by kingct33** [yunionio/cloudpods#21437]
**region镜像版本从3.10.5升级到3.11后，华为云无法更新标签**:

![e6fc7ac03cb9004707c49cbb876de97](https://github.com/user-attachments/assets/04b716fd-6722-4311-8fdb-51d117f871d7)
![7bb4b5ed36dcef313dfb2ed15fb52bd](https://github.com/user-attachments/assets/5db05ab4-2d95-404f-96aa-0019ce2712c3)

**Comment by kingct33** [comment]
我使用的是docker-compose一件部署的，用的不是kubectl

**Comment by kingct33** [comment]
您的意思是修改哪个容器镜像到哪个版本吗？

**Comment by ioito** [comment]
修改region镜像到registry.cn-beijing.aliyuncs.com/yunionio/region:v3.11-2024102118
