### ISSUE TITLE
[求助/Help]vSphere中windows服务器v2v迁移到cloudpods中，操作系统识别成为Others Linux 6.3，是否能修改？

### ISSUE THREAD

**Issue by nashzosi** [yunionio/cloudpods#21436]
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/c6136aad-56dc-46d7-822e-b1c6449a29c4">
vSphere中windows服务器v2v迁移到cloudpods中，操作系统识别成为Others Linux 6.3，目前操作系统运行正常，是否能修改这信息？

**Comment by wanyaoqi** [comment]
@nashzosi climc server-set-os-info 可以修改虚机系统信息

**Comment by nashzosi** [comment]
@wanyaoqi 已经完成修改，非常感谢支持
