### ISSUE TITLE
[BUG]Could not set up host forwarding rule 'tcp:127.0.0.1:28873-:22'\n: exit status 1

### ISSUE THREAD

**Issue by 66545shiwo** [yunionio/cloudpods#21447]
**问题描述/What happened**:
同一个宿主机并发创建虚拟机偶尔会出现以下报错：

```
{
    "__reason__": "Deploy guest fs: request deploy guest fs: rpc error: code = Unknown desc = Connect: failed start guest qemu-system-x86_64: Could not set up host forwarding rule 'tcp:127.0.0.1:28873-:22'\n: exit status 1",
    "__stage__": "OnDeployGuestComplete",
    "__status__": "error"
}
```
应该是并发导致的，重启虚机后正常。

此外，这种创建失败原因，不会释放GPU卡
**环境/Environment**:
3.10.14
- OS (e.g. `cat /etc/os-release`): ubuntu22
- Kernel (e.g. `uname -a`): cloud-node-0132 5.15.0-124-generic
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by wanyaoqi** [comment]
@66545shiwo 更新一下 host-deployer 到最新的 3.10，registry.cn-hangzhou.aliyuncs.com/d3lx/host-deployer:v20241023 可以用这个刚刚打的。
你删除虚机就可以释放GPU了

**Comment by 66545shiwo** [comment]
@wanyaoqi 好的， 谢谢，方便贴下这块改的源码吗
