### ISSUE TITLE
[求助/Help]  宿主机 资源统计数据为空 

### ISSUE THREAD

**Issue by huhaiqwer** [yunionio/cloudpods#21452]
OS： openEuler 22.03 SP3
version: v3.10.8

@wanyaoqi  大佬，我们环境宿主机的资源统计数据为空 特别是 cpu、内存、存储这些数据，我看代码好像是通过monitor服务去查的,请教一下采集数据上报数据分别流程是什么，涉及那些服务。应该怎么排查这个问题，我这边看了 host 服务好像并没有什么明显的报错

![image](https://github.com/user-attachments/assets/9ec6d324-ed3f-474b-a9ba-93b5bdd067b4)

**Comment by wanyaoqi** [comment]
@huhaiqwer 这些主要是宿主机上的 telegraf 服务采集， kubectl get pods -n onecloud -o wide -lapp=telegraf ，看下服务正常吗
