### ISSUE TITLE
[求助/Help]怎么连接时序数据库victoria-metrics

### ISSUE THREAD

**Issue by buxiangshangban1** [yunionio/cloudpods#21460]
现在时序数据为victoria-metrics，想知道怎么可以在pod中进入该数据库查看数据。或者有什么办法可以知道该数据库的监控指标，以及数据。
/api/v1/query_range?query=vm_cpu&start=2024-10-25T09:00:00.000Z 该接口查询数据结果如下：
{
    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": []
    },
    "stats": {
        "seriesFetched": "0",
        "executionTimeMsec": 0
    }
}

cloudpods环境在该时间之后连接了云账号，有虚拟机等资源

**Comment by zexi** [comment]
@buxiangshangban1 可以参考文档： https://www.cloudpods.org/docs/development/monitor/query#query-victoric-metrics-data
