### ISSUE TITLE
[BUG] v3.11.8 All in One 版本无法添加计算节点

### ISSUE THREAD

**Issue by Mrliuch** [yunionio/cloudpods#21483]
**问题描述/What happened**:
v3.11.8 All in One 部署一台节点后添加另一计算节点报错，疑似升级K3S版本后添加节点脚本没有更改
报错如下：
root@liuchen-hp:/data/ocboot/ocboot-master-v3.11.8# ./ocboot.sh add-node 192.168.10.42 192.168.10.30
de37b27c2512     *     4d25e7ebdfd0 registry.cn-beijing.aliyuncs.... buildah-ocboot
de37b27c2512a013b6ee8a96c6dc82ee570393c8d1a0044b38e20eb39da58c60
Using buildah pull registry.cn-beijing.aliyuncs.com/yunionio/ocboot:v4-k3s.4
buildah-ocboot
buildah version: 1.23.1
INFO:lib.ssh:exec_command: bash -c '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :; ls -alh /etc/kubernetes/kubelet.conf'
ssh -p 22 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -i /root/.ssh/id_rsa root@192.168.10.42 'bash -c '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :; ls -alh /etc/kubernetes/kubelet.conf''
Traceback (most recent call last):
  File "/ocboot/ocboot.py", line 45, in <module>
    sys.exit(main())
  File "/ocboot/ocboot.py", line 41, in main
    args.func(args)
  File "/ocboot/lib/add_node.py", line 15, in do_action
    cluster = construct_cluster(
  File "/ocboot/lib/cluster.py", line 25, in construct_cluster
    cluster = OnecloudCluster(cli)
  File "/ocboot/lib/cluster.py", line 45, in __init__
    k3s_cmd_placeholder = 'k3s' if self.is_using_k3s() else ''
  File "/ocboot/lib/cluster.py", line 40, in is_using_k3s
    return is_using_k3s(self.ssh_client, self.use_sudo())
  File "/ocboot/lib/k3s.py", line 72, in is_using_k3s
    raise e
  File "/ocboot/lib/k3s.py", line 64, in is_using_k3s
    ret = ssh_client.exec_command(f'ls -alh {kubelet_config}', use_sudo)
  File "/ocboot/lib/ssh.py", line 89, in exec_command
    raise StderrException(err)
lib.ssh.StderrException: ls: 无法访问 '/etc/kubernetes/kubelet.conf': 没有那个文件或目录

error while running runtime: exit status 1

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`): Ubuntu 22.04.5
- Kernel (e.g. `uname -a`): 6.8.0-47-generic
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-
| ansible       | release/3.11.8(2c25b737c924101412)                                                                                                        |
| apimap        | release/3.11.8(2c25b737c924101412)                                                                                                        |
| cloudmon      | release/3.11.8(2c25b737c924101412)                                                                                                        |
| cloudproxy    | release/3.11.8(2c25b737c924101412)                                                                                                        |
| compute_v2    | release/3.11.8(2c25b737c924101412)                                                                                                        |
| devtool       | release/3.11.8(2c25b737c924101412)                                                                                                        |
| identity      | release/3.11.8(2c25b737c924101412)                                                                                                        |
| image         | release/3.11.8(2c25b737c924101412)                                                                                                        |
| k8s           | heads/v3.11.8-20241013.0(28e38d5b24101411)                                                                                                |
| log           | release/3.11.8(2c25b737c924101412)                                                                                                        |
| monitor       | release/3.11.8(2c25b737c924101412)                                                                                                        |
| notify        | release/3.11.8(2c25b737c924101412)                                                                                                        |
| scheduledtask | release/3.11.8(2c25b737c924101412)                                                                                                        |
| scheduler     | release/3.11.8(2c25b737c924101412)                                                                                                        |
| vpcagent      | release/3.11.8(2c25b737c924101412)                                                                                                        |
| webconsole    | release/3.11.8(2c25b737c924101412)                                                                                                        |
| yunionagent   | {"error":{"class":"DNSError","code":499,"details":"Get \"https://default-yunionagent:30898/version\": dial tcp: lookup default-yunionagen |
|               | t on 10.96.0.10:53: no such host","request":{"headers":{"User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*"},"method":"GET","url":"ht |
|               | tps://default-yunionagent:30898/version"}}}                                                                                               |
| yunionconf    | release/3.11.8(2c25b737c924101412)                                                                                                        |

**Comment by Mrliuch** [comment]
补充信息：
1、k3s版本：liuchen-hp   Ready    control-plane,master   10h   v1.28.5+k3s1
2、无/etc/kubernetes目录：ls: 无法访问 '/etc/kubernetes': 没有那个文件或目录
3、上述报错中192.168.10.42为控制节点 192.168.10.30为要加入的计算节点
4、报错图片如下：
![iShot_2024-10-29_09 35 14](https://github.com/user-attachments/assets/0a744c77-f583-4919-a429-17b4439c03ab)

**Comment by zexi** [comment]
@Mrliuch 应该是中文环境的问题，这个 PR https://github.com/yunionio/ocboot/pull/1379 修复此问题，可以下载最新的 ocboot master 代码重新测试下。

**Comment by Mrliuch** [comment]
> @Mrliuch 应该是中文环境的问题，这个 PR [yunionio/ocboot#1379](https://github.com/yunionio/ocboot/pull/1379) 修复此问题，可以下载最新的 ocboot master 代码重新测试下。

已经是最新的了，master分支代码。地址：git clone https://github.com/yunionio/ocboot.git
![iTerm2 2024-10-29 09 52 15](https://github.com/user-attachments/assets/04509d3e-c075-4baa-98e5-0d2dde5ff447)

**Comment by zexi** [comment]
@Mrliuch 修复的代码刚合并，执行下面的命令后再试试：

```bash
git fetch --all
git checkout origin/master
./ocboot.sh add-node .....
```

**Comment by Mrliuch** [comment]
> @Mrliuch 修复的代码刚合并，执行下面的命令后再试试：
> 
> ```shell
> git fetch --all
> git checkout origin/master
> ./ocboot.sh add-node .....
> ```

已操作，同样的报错：
![image](https://github.com/user-attachments/assets/b761619a-ce81-47c1-b799-373096911e31)

**Comment by zexi** [comment]
@Mrliuch 再拉取最新代码试试

**Comment by Mrliuch** [comment]
> @Mrliuch 再拉取最新代码试试

添加计算节点成功，感谢！
