### ISSUE TITLE
python3: can't open file '/ocboot/ocboot.py':

### ISSUE THREAD

**Issue by LJQ1013177938** [yunionio/cloudpods#21504]
![image](https://github.com/user-attachments/assets/f5c88a81-a44b-4128-bf03-8965a1c021ee)

我按照官网（https://www.cloudpods.org/docs/getting-started/onpremise/ha-ce）的步骤安装的，执行./ocboot.sh install ./config-ha.yml后，就报了截图中的错，可以帮忙看看吗

**Comment by zexi** [comment]
ocboot 的代码版本是不是不对？

**Comment by LJQ1013177938** [comment]
我想安装一个3.11.8以下的，所以我就下载了3.11.7，是从这个地址下载的https://github.com/yunionio/ocboot/tree/release/3.11.7，您看对吗，或者您方便给我一个正确的地址吗

**Comment by zexi** [comment]
https://www.cloudpods.org/docs/getting-started/onpremise/ha-ce#%E4%B8%8B%E8%BD%BD%E9%83%A8%E7%BD%B2%E5%B7%A5%E5%85%B7

参考这个文档安装，把 ocboot 下载下来后，修改 VERSION 文件，改成对应想要的版本
<img width="474" alt="image" src="https://github.com/user-attachments/assets/b93d127f-105c-41de-9f13-4036fcbb21e4">
