### ISSUE TITLE
[求助/Help] ocboot.sh 3.11.6版本，执行命令时报错：./ocboot.sh: line 18: buildah: command not found

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21517]
我之前使用3.11.6安装集群的时候，是没有这个报错的，包括后面增加节点。不知道为什么今天执行命令的时候突然报了这个错。我记得这个版本是没有用到buildah这种方式的吧？
```
#!/bin/bash

set -e

REGISTRY=${REGISTRY:-registry.cn-beijing.aliyuncs.com/yunionio}
VERSION=${VERSION:-v3.11-buildah.1}
OCBOOT_IMAGE="$REGISTRY/ocboot:$VERSION"

CUR_DIR="$(pwd)"
CONTAINER_NAME="buildah-ocboot"

buildah_from_image() {
    if buildah ps | grep $CONTAINER_NAME; then
        buildah rm $CONTAINER_NAME
    fi
    local img="$1"
    echo "Using buildah pull $img"
    buildah from --name $CONTAINER_NAME "$img"
}

buildah_from_image "$OCBOOT_IMAGE"

mkdir -p "$HOME/.ssh"

CMD=""

is_ocboot_subcmd() {
    local subcmds="install upgrade add-node add-lbagent backup restore"
    for subcmd in $subcmds; do
        if [[ "$1" == "$subcmd" ]]; then
            return 0
        fi
    done
    return 1
}

if is_ocboot_subcmd $1; then
    CMD="ocboot.py"
fi

buildah run -t \
    -v "$HOME/.ssh:/root/.ssh" \
    -v "$(pwd):/ocboot" \
    "$CONTAINER_NAME" $CMD $@
```

**Comment by zexi** [comment]
@shuoshadow 用的哪个版本的 ocboot ?

**Comment by shuoshadow** [comment]
> @shuoshadow 用的哪个版本的 ocboot ?

3.11.6
![Uploading image.png…]()

我之前使用ocboot命名添加节点都正常

**Comment by zexi** [comment]
@shuoshadow 那应该使用 ./ocboot.py 而不是 .sh

**Comment by shuoshadow** [comment]
> @shuoshadow 那应该使用 ./ocboot.py 而不是 .sh

好像是... 看新增负载均衡的文档使用的是ocboot.sh。ocboot.py里好像也有add-lbagent命令。这两个脚本有什么区别吗？3.11.6的版本使用ocboot.py是不是就可以了？

**Comment by zexi** [comment]
> > @shuoshadow 那应该使用 ./ocboot.py 而不是 .sh
> 
> 好像是... 看新增负载均衡的文档使用的是ocboot.sh。ocboot.py里好像也有add-lbagent命令。这两个脚本有什么区别吗？3.11.6的版本使用ocboot.py是不是就可以了？

ocboot.sh v3.11.8 版本后开始使用的，需要参考部署文档那里，拉取最新的 ocboot 版本代码。
如果本地是 ocboot 3.11.6 老版本的代码，就用 ocboot.py 就行，ocboot.sh 不依赖 ansible ，会使用 buildah 命令拉取容器镜像运行安装环境，跟干净依赖少一些。

**Comment by shuoshadow** [comment]
@zexi 明白了 感谢！
