### ISSUE TITLE
[求助/Help] 部署负载均衡报错：lib.ssh.StderrException: bash: kubectl: command not found

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#21519]
ocboot版本3.11.6

执行命令：./ocboot.py add-lbagent 10.10.108.15 10.10.108.16 10.10.108.17

报错如下：
```
INFO:lib.ssh:exec_command: [ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json
ssh -p 22 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -i /root/.ssh/id_rsa root@10.10.108.15 '[ -s /etc/kubernetes/admin.conf ] && export KUBECONFIG=/etc/kubernetes/admin.conf || :;  kubectl -n onecloud get onecloudclusters default -o json'

root@10.10.108.15's password: 
Traceback (most recent call last):
  File "/usr/local/src/ocboot/./ocboot.py", line 44, in <module>
    sys.exit(main())
  File "/usr/local/src/ocboot/./ocboot.py", line 40, in main
    args.func(args)
  File "/usr/local/src/ocboot/lib/service.py", line 124, in do_action
    cluster = construct_cluster(
  File "/usr/local/src/ocboot/lib/cluster.py", line 24, in construct_cluster
    cluster = OnecloudCluster(cli)
  File "/usr/local/src/ocboot/lib/cluster.py", line 43, in __init__
    ret = ssh_client.exec_command(
  File "/usr/local/src/ocboot/lib/ssh.py", line 87, in exec_command
    raise StderrException(err)
lib.ssh.StderrException: bash: kubectl: command not found
```

![image](https://github.com/user-attachments/assets/7d0a0df4-e935-48c6-be2c-d02ee9278970)

**Comment by zexi** [comment]
10.10.108.15 上面有 kubectl 命令吗？

**Comment by shuoshadow** [comment]
> 10.10.108.15 上面有 kubectl 命令吗？

没有 这是一个新建的虚拟机，文档中的<ip_of_master_node>是指什么的ip呢？是cloudpods集群的master机器吗？

![image](https://github.com/user-attachments/assets/48aee7c6-a1ed-43a2-aaca-92adf8319e9a)

**Comment by zexi** [comment]
> 文档中的<ip_of_master_node>是指什么的ip呢？

这个是平台控制节点的 ip

**Comment by shuoshadow** [comment]
> > 文档中的<ip_of_master_node>是指什么的ip呢？
> 
> 这个是平台控制节点的 ip

明白了，我重新执行试试，感谢！

**Comment by shuoshadow** [comment]
我添加了两个lbagent节点，为什么节点加入k8s集群后，只有一个node有onecloud.yunion.io/lbagent=enable标签？
./ocboot.py add-lbagent 10.10.107.14 10.10.108.16 10.10.108.17

只有10.10.108.16这个节点d打了标签，且启动了default-lbagent服务

![image](https://github.com/user-attachments/assets/3145a4f5-ed7a-45ab-903d-6aa8fd3026c6)

![image](https://github.com/user-attachments/assets/6a360d69-66f7-4cc8-835a-a28fbc169a1a)

**Comment by shuoshadow** [comment]
直接加上label就可以了，谢谢！
