### ISSUE TITLE
[求助/Help]裸金属删除后物理服务器分配项仍然显示裸金属名字导致无法再次调度

### ISSUE THREAD

**Issue by lklkxcxc** [yunionio/cloudpods#21521]
裸金属删除后物理服务器分配项仍然显示裸金属名字导致无法再次调度，另外我直接从ubuntu官网下载的2204的qcow2镜像进行裸金属安装后无法正常引导，需要做什么操作吗？
![image](https://github.com/user-attachments/assets/92e28a4d-07a6-4ae3-82d1-391f0e26aed4)

系统版本：v3.11.8

**Comment by zexi** [comment]
@lklkxcxc 是不是回收站里面的裸金属没有释放？
另外如果物理机用了 megaraid 这些 raid 卡，需要 ubuntu 镜像里面的 initramfs 有对应驱动才行。

**Comment by lklkxcxc** [comment]
@zexi 确实回收站没有删除，第一次使用明白了。ubuntu卡在boot界面，openstack ironic制作ubuntu
裸金属镜像，有两个引导镜像vmlinuz和initrd 咱们这个不需要吗

**Comment by lklkxcxc** [comment]
用官网例子里面的qcow2启动裸金属报错，这个跟我之前openstack遇到一样，就是vm的镜像要引导裸金属不行，需要怎么处理呢？
![image](https://github.com/user-attachments/assets/c07fc54e-ff4b-484c-b0e0-433699a3e09a)
