### ISSUE TITLE
[求助/Help]最新版host  pod 日志提示找不到设备

### ISSUE THREAD

**Issue by guaguajia** [yunionio/cloudpods#21540]
![image](https://github.com/user-attachments/assets/74a9d2cb-062a-4866-afcb-6fd2ea6468a2)
我内存大页已经配置完了，为什么提示识别不到存储设备

**Comment by zexi** [comment]
应该和这个大页是相同问题：https://github.com/yunionio/cloudpods/issues/17578

试试修改/etc/yunion/host.conf
```
hugepages_option: disable
```

**Comment by wanyaoqi** [comment]
@guaguajia 配置完需要重启一下宿主机
