### ISSUE TITLE
[求助/Help] 怎么在宿主机上新增一个nvm硬盘

### ISSUE THREAD

**Issue by love-seeker** [yunionio/cloudpods#21581]
我现在有多个nvm的硬盘，同时我创建虚拟机的时候

**Comment by love-seeker** [comment]
一直提示，创建主机失败
请求数量/允许数量：1 / 0
拒绝原因
Out of resource
错误
宿主机【bms-29342435-002-192-168-0-21】磁盘不足
查看详细
no enough backend "local", mediumType "ssd" storage, req=30720(30720), free=-369759(storage "host_192.168.0.21_local_storage_0", total:449441 - used:0 - waste:0 = free:449441)

**Comment by love-seeker** [comment]
我现在应该怎么处理，或者是怎么操作呢？

**Comment by zexi** [comment]
@love-seeker
参考这个文档添加存储： https://www.cloudpods.org/docs/guides/onpremise/storage/blockstorage/add-storage  
或者把已有的存储 host_192.168.0.21_local_storage_0 磁盘介质改成 ssd 的
