### ISSUE TITLE
[求助/Help]物理机（没有IPMI）无法通过PXE引导启动

### ISSUE THREAD

**Issue by happinesslijian** [yunionio/cloudpods#21611]
背景叙述：
10.10.22.70是**服务端** [部署方式](https://www.cloudpods.org/docs/getting-started/onpremise/quickstart-virt#%E5%AE%89%E8%A3%85-cloudpods)
[已经启用了物理机管理服务](https://www.cloudpods.org/docs/getting-started/onpremise/baremetal)
10.10.22.70服务端所在网络有DHCP
问题描述：
**客户端物理机**（没有IPMI）所在网络10.10.23.x 使用**预注册**方式配置了如下网络：
![微信截图_20241115175728](https://github.com/user-attachments/assets/fd30d199-b394-4eb4-a471-3957dc0ed410)

**10.10.23.x网段里没有DHCP**,现在客户端PXE引导不起来,日志如下：
`kubectl logs -n onecloud -f default-baremetal-agent-84d9fb7c7b-lm46p`
![lQLPJwvQ0_BuoxnNAWLNB2Kw2YuYmTfZK7QHHW1mUz87AA_1890_354](https://github.com/user-attachments/assets/cd34123a-1431-4ef6-898a-6659540d6b0b)

**Comment by zexi** [comment]
@happinesslijian 可以用 tcpdump 抓包看下 baremetal-agent 服务有没有回复 dhcp？看日志应该是回复了，有可能客户端没有收到

**Comment by zexi** [comment]
@happinesslijian 
我看日志是从 10.10.22.70 relay 过来的 dhcp 请求，和对应 pxe 子网 10.10.23.x 不在同一个子网，那就需要设置对应 pxe 网段的 dhcp relay 属性为 10.10.22.70 。

**Comment by happinesslijian** [comment]
![image](https://github.com/user-attachments/assets/5077b012-d4ef-4710-bd02-7a7178caa848)
PXE网络的dhcp_relay已经是10.10.22.70 但是客户端启动还是无法通过PXE引导 并且baremetal-agent容器会频繁的出现如下：

```
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
[info 2024-11-20 05:47:19 pxe.(*DHCPHandler).ServeDHCP(dhcp.go:84)]DHCP: from relay 10.10.22.70 packet, mac: 74:86:e2:1c:4e:ef
```

**Comment by happinesslijian** [comment]
> 74:86:e2:1c:4e:ef 这个是物理机的 mac 吗？

是的，是物理机的mac地址，这是在bios里拍摄的照片  @zexi 
![lQDPKeBSFP778g3NBQDNAtCwjgl6nShNxfIHI8S5IcOgAA_720_1280](https://github.com/user-attachments/assets/a4ada32e-a7b6-4110-8e96-dac48728e5e8)

**Comment by zexi** [comment]
@happinesslijian 那再让这个服务器 pxe 启动，同时 baremetal-agent 那边 tcpdump 抓包看下

**Comment by happinesslijian** [comment]
@zexi 
执行命令`kubectl logs -f default-baremetal-agent-84d9fb7c7b-wg9g2 -n onecloud > baremetal-agent.log`输出日志
执行命令`tcpdump -i br0 port 67 or port 68 -vv > tcpdump.txt`进行抓包
两条命令都是运行在10.10.22.70服务端上的，详情见附件
添加物理机如下：
![0F266D54-88AD-4a2a-9541-92637DFA4053](https://github.com/user-attachments/assets/dc38b1bd-53eb-4246-837b-8c59f25269f1)
tcpdump抓包和baremetal-agent日志见附件
[baremetal-agent.log](https://github.com/user-attachments/files/17827695/baremetal-agent.log)
[tcpdump.txt](https://github.com/user-attachments/files/17827700/tcpdump.txt)

**Comment by happinesslijian** [comment]
[开启交换机DHCP_RELAY](https://www.cloudpods.org/docs/getting-started/onpremise/baremetal#%E7%89%A9%E7%90%86%E4%BA%A4%E6%8D%A2%E6%9C%BA%E9%85%8D%E7%BD%AEdhcp-relay) 
[不要开启host 服务DHCP Relay](https://www.cloudpods.org/docs/getting-started/onpremise/baremetal#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-host-%E6%9C%8D%E5%8A%A1%E5%90%AF%E7%94%A8-dhcp-relay)
网络配置如下图：
![76c08564e52078dc2699e3d783b9524c](https://github.com/user-attachments/assets/86ccb494-d3f7-4ebe-b82d-958573917c37)
预注册机器可以从PXE正确引导启动
