### ISSUE TITLE
[BUG] scheduletask未注册Metadata与OpsLog这2个对象

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#21618]
**问题描述/What happened**:

pkg/scheduledtask/service/handlers.go ----开源版本的scheduledtask似乎有BUG
![image](https://github.com/user-attachments/assets/902bf3a0-86c4-41c6-a191-a5b2cde32557)
需要注册这2个对象
否则无法查看定时任务状态，与 设置启用/禁用

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
closed #21819
