### ISSUE TITLE
[求助/Help] all in one 3.10版本安装报错

### ISSUE THREAD

**Issue by yandew** [yunionio/cloudpods#21654]
最小安装centos7.6后换阿里的repo，update到7.9的3.10内核后all in one安装，报错如下。
PLAY [mariadb_node] ************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.62.31.59]

TASK [mariadb : gather os specific variables] **********************************
ok: [10.62.31.59] => (item=/opt/cloudpods/ocboot/onecloud/roles/mariadb/vars/centos.yml)

TASK [mariadb : Include Pre Install tasks if any] ******************************

TASK [mariadb : Install mariadb] ***********************************************
changed: [10.62.31.59] => (item=mariadb-server)

TASK [mariadb : pips for mysql/mariadb online] *********************************
failed: [10.62.31.59] (item=PyMySQL) => {"ansible_loop_var": "pip_item", "changed": false, "cmd": ["/usr/local/bin/pip3", "install", "PyMySQL"], "msg": "\n:stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa369b93a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa369b936d8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa369ba52e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa369ba5748>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa369ba5898>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/\nERROR: Could not find a version that satisfies the requirement PyMySQL (from versions: none)\nERROR: No matching distribution found for PyMySQL\n", "pip_item": "PyMySQL"}

PLAY RECAP *********************************************************************
10.62.31.59                : ok=76   changed=29   unreachable=0    failed=1    skipped=30   rescued=0    ignored=0

目前环境pip版本如下：
[root@sdn59 ocboot]# pip show pip
Name: pip
Version: 21.3.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires:
Required-by:
[root@sdn59 ocboot]#

**Comment by wanyaoqi** [comment]
@yandew 网络问题，换个 pip 源试试

**Comment by yandew** [comment]
这个问题我通过下面这个命令预先装一下pymysql解决了，现在遇到一个问题。
python3 -m pip install pymysql
在push image的时候，我的环境里面没有ipv6的地址，日志显示在找ipv6的dns。目前docker版本是20.10.6
TASK [utils/controlplane : Ensure a cronjob that renews k8s certificates] ******
ok: [10.62.31.59]

TASK [primary-master-node/setup_k8s : Get cluster token] ***********************
changed: [10.62.31.59]

TASK [loading images] **********************************************************
skipping: [10.62.31.59]

TASK [primary-master-node/setup_k8s : Tag and push images for non-HA mode. It might take a few minutes...] ***
skipping: [10.62.31.59]

TASK [primary-master-node/setup_k8s : Pull ocadm images on node] ***************
FAILED - RETRYING: Pull ocadm images on node (3 retries left).
FAILED - RETRYING: Pull ocadm images on node (2 retries left).
FAILED - RETRYING: Pull ocadm images on node (1 retries left).
fatal: [10.62.31.59]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "docker.io/yunion", "--onecloud-version", "v3.10.15", "--operator-version", "v3.10.15"], "delta": "0:00:00.166008", "end": "2024-11-24 13:32:13.455148", "msg": "non-zero return code", "rc": 1, "start": "2024-11-24 13:32:13.289140", "stderr": "failed to pull image \"docker.io/yunion/kube-apiserver:v1.15.8\": output: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: dial udp [::1]:53: connect: no route to host\n, error: exit status 1", "stderr_lines": ["failed to pull image \"docker.io/yunion/kube-apiserver:v1.15.8\": output: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: dial udp [::1]:53: connect: no route to host", ", error: exit status 1"], "stdout": "[config/images] Pulling docker.io/yunion/kube-apiserver:v1.15.8", "stdout_lines": ["[config/images] Pulling docker.io/yunion/kube-apiserver:v1.15.8"]}

PLAY RECAP *********************************************************************
10.62.31.59                : ok=90   changed=9    unreachable=0    failed=1    skipped=37   rescued=0    ignored=0

[root@sdn59 ocboot]# docker --version
Docker version 20.10.6, build 370c289

**Comment by yandew** [comment]
补充一下，这个image的源，我试过阿里的和docker.io的，都是同一个报错。

**Comment by zexi** [comment]
>  dial udp [::1]:53: connect: no route to host

感觉本机网络 dns 解析的问题

**Comment by yandew** [comment]
可是我的host上没有ipv6的地址，所以也就没路由。
我给docker的环境加了一个代理，现在还是pull image的时候报错，但是报错信息变了。
TASK [primary-master-node/setup_k8s : Tag and push images for non-HA mode. It might take a few minutes...] ***
skipping: [10.62.31.59]

TASK [primary-master-node/setup_k8s : Pull ocadm images on node] ***************
FAILED - RETRYING: Pull ocadm images on node (3 retries left).
FAILED - RETRYING: Pull ocadm images on node (2 retries left).
FAILED - RETRYING: Pull ocadm images on node (1 retries left).
fatal: [10.62.31.59]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "docker.io/yunion", "--onecloud-version", "v3.10.15", "--operator-version", "v3.10.15"], "delta": "0:00:00.985956", "end": "2024-11-24 14:14:02.929721", "msg": "non-zero return code", "rc": 1, "start": "2024-11-24 14:14:01.943765", "stderr": "failed to pull image \"docker.io/yunion/kube-apiserver:v1.15.8\": output: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\n, error: exit status 1", "stderr_lines": ["failed to pull image \"docker.io/yunion/kube-apiserver:v1.15.8\": output: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority", ", error: exit status 1"], "stdout": "[config/images] Pulling docker.io/yunion/kube-apiserver:v1.15.8", "stdout_lines": ["[config/images] Pulling docker.io/yunion/kube-apiserver:v1.15.8"]}

PLAY RECAP *********************************************************************
10.62.31.59                : ok=90   changed=8    unreachable=0    failed=1    skipped=37   rescued=0    ignored=0

**Comment by yandew** [comment]
装完了，在daemon.json 里面加了下面这样，虽然还有报错，多装了2遍，image都下载完了，就过了这步，谢谢大家，我close了。
"insecure-registries": ["https://registry.cn-beijing.aliyuncs.com"],
