### ISSUE TITLE
[求助/Help] Go SDK 创建虚拟机失败 

### ISSUE THREAD

**Issue by YU23333** [yunionio/cloudpods#21677]
参照例子调用创建api：

```golang
type Config struct {
	AutoStart      bool   `json:"auto_start"`
	GenerateName   string `json:"generate_name"`
	Description    string `json:"description"`
	Hypervisor     string `json:"hypervisor"`
	Disks          []Disk `json:"disks"`
	Nets           []Net  `json:"nets"`
	PreferRegion   string `json:"prefer_region"`
	VCPUCount      int    `json:"vcpu_count"`
	VMemSize       int    `json:"vmem_size"`
	ProjectID      string `json:"project_id"`
	OSArch         string `json:"os_arch"`
	SKU            string `json:"sku"`
	PreferZone     string `json:"prefer_zone"`
	DeployTelegraf bool   `json:"deploy_telegraf"`
	DryRun         bool   `json:"dry_run"`
	Count          int    `json:"__count__"`
}

type Disk struct {
	DiskType string `json:"disk_type"`
	Index    int    `json:"index"`
	Backend  string `json:"backend"`
	Size     int    `json:"size"`
	ImageID  string `json:"image_id"`
	Medium   string `json:"medium"`
}

type Net struct {
	Network string `json:"network"`
}

func main() {
	client := mcclient.NewClient("https://10.10.1.22:30357/v3",
		60,
		true,
		true,
		"",
		"")
	token, err := client.Authenticate("sysadmin", "wfYrDE6mj9tEE2GX", "Default", "system", "Default")
	if err != nil {
		panic(err)
	}
	s := client.NewSession(context.Background(),
		"region0",
		"",
		"publicURL",
		token,
	)
	config := Config{
		AutoStart:    true,
		GenerateName: "lol",
		Description:  "yu",
		Hypervisor:   "kvm",
		Disks: []Disk{
			{
				DiskType: "sys",
				Index:    0,
				Backend:  "local",
				Size:     30720,
				ImageID:  "a4358295-0d7-4b49-8135-2d9485550e6e",
				Medium:   "rotate",
			},
		},
		Nets: []Net{
			{
				Network: "a85394af-74f2-4ddb-8049-06eb046a400f",
			},
		},
		PreferRegion:   "default",
		VCPUCount:      2,
		VMemSize:       2048,
		ProjectID:      "99cf895ad64b8782784aafa730bd90",
		OSArch:         "x86",
		SKU:            "ecs.g1.c2m2",
		PreferZone:     "1aa48475-5daa-4d0c-8e43-371f564b7db6",
		DeployTelegraf: true,
		DryRun:         true,
		Count:          1,
	}
	jsonData := jsonutils.Marshal(config)
	if err != nil {
		fmt.Println("Error marshaling JSON:", err)
		return
	}
	params := jsonutils.NewDict()
	params.Set("scope", jsonutils.NewString("system"))
	result, err := compute.Servers.Create(s, jsonData)
	fmt.Println(result)
}
```

打印结果：
CURL: curl -k -X 'POST' -d '{"server":{"auto_start":true,"deploy_telegraf":true ,"description":"yu","disks":[{"backend":"local","disk_type":"sys","image_id":"a4358295-0d7-4b49-8135-2d9485550e6e","index":0,"medium":"rotate","size":30720}],"dry_run":true,"generate_name":"lol","hypervisor":"kvm","nets":[{"network":"a85394af-74f2-4ddb-8049-06eb046a400f"}],"os_arch":"x86","prefer_region":"default","prefer_zone":"1aa48475-5daa-4d0c-8e43-371f564b7db6","project_id":"99cf895ad64b8782784aafa730bd90","sku":"ecs.g1.c2m2","vcpu_count":2,"vmem_size":2048}}' -H 'Accept : */*' -H 'Accept-Encoding: *' -H 'Content-Length: 519' -H 'Content-Type: application/json' -H 'User-Agent: yunioncloud-go/201708' -H 'X-Auth-Token: b4ad888dc6f2b70c27214bb6c63b56e20e1922cd21d9a044c98a5d94cbe49b3f' 'https://10.10.1.22:30888/servers' 

HTTP/1.1 404 Not Found
Content-Length: 140
Content-Type: application/json
Date: Mon, 25 Nov 2024 07:16:20 GMT
Server: Yunion AppServer/Go/2018.4
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Frame-Options: SAMEORIGIN
X-Request-Host-Id: mKkmz2cHD_W3U2lKWAKzoHSZjvs=
X-Request-Id: 48b998
X-Xss-Protection: 1; mode=block
X-Yunion-Peer-Service-Name: compute_v2
X-Yunion-Remote-Addr: 10.96.0.10:9210
X-Yunion-Span-Name: create
X-Yunion-Strace-Tag-Resource: servers

**Comment by wanyaoqi** [comment]
@YU23333 可以同时看下 region 日志，这样看不出来是哪里的问题

**Comment by YU23333** [comment]
> @YU23333 可以同时看下 region 日志，这样看不出来是哪里的问题
SDK已经成功调用了，但是cloudpods平台上面没有显示创建的虚拟机，region日志在哪里看啊

**Comment by wanyaoqi** [comment]
> 打印结果： CURL: curl -k -X 'POST' -d '{"server":{"auto_start":true,"deploy_telegraf":true ,"description":"yu","disks":[{"backend":"local","disk_type":"sys","image_id":"a4358295-0d7-4b49-8135-2d9485550e6e","index":0,"medium":"rotate","size":30720}],"dry_run":true,"generate_name":"lol","hypervisor":"kvm","nets":[{"network":"a85394af-74f2-4ddb-8049-06eb046a400f"}],"os_arch":"x86","prefer_region":"default","prefer_zone":"1aa48475-5daa-4d0c-8e43-371f564b7db6","project_id":"99cf895ad64b8782784aafa730bd90","sku":"ecs.g1.c2m2","vcpu_count":2,"vmem_size":2048}}' -H 'Accept : _/_' -H 'Accept-Encoding: *' -H 'Content-Length: 519' -H 'Content-Type: application/json' -H 'User-Agent: yunioncloud-go/201708' -H 'X-Auth-Token: b4ad888dc6f2b70c27214bb6c63b56e20e1922cd21d9a044c98a5d94cbe49b3f' 'https://10.10.1.22:30888/servers'
> 
> HTTP/1.1 404 Not Found

你这个只有404的报错，看不出来什么原因，要看region日志
https://www.cloudpods.org/docs/operations/k8s/commonops/#%E6%9F%A5%E7%9C%8B%E6%9C%8D%E5%8A%A1%E6%97%A5%E5%BF%97

**Comment by YU23333** [comment]
已解决

**Comment by YU23333** [comment]
> ###
> [Nov 26, 2024](#issuecomment-2499592233)
调用server的创建接口后还需要调用scheduler.SchedManager.DoForecast，然后再次调用创建接口。scheduler.SchedManager.DoForecast这个里面还需要改一下代码才能成功运行

**Comment by YU23333** [comment]
> @YU23333 是什么原因
调用server的创建接口后还需要调用scheduler.SchedManager.DoForecast，然后再次调用创建接口。scheduler.SchedManager.DoForecast这个里面还需要改一下代码才能成功运行
