### ISSUE TITLE
[求助/Help]在对接AWS使用私有镜像创建实例时，报错SStoragecache.Wait: SStoragecache.ImageImportStatusDeleted: InvalidStatusError

### ISSUE THREAD

**Issue by rekazer0** [yunionio/cloudpods#21778]
版本为 v3.11.8
在缓存镜像至79%时，出现磁盘分配失败的报错，具体如下：
```
{
    "__reason__": {
        "reason": {
            "image_id": "5eb1e3bc-aa2e-476f-87bc-5cad7a69fe7b",
            "reason": {
                "__reason__": "SStoragecache.Wait: SStoragecache.ImageImportStatusDeleted: InvalidStatusError",
                "__stage__": "OnImageCacheComplete",
                "__status__": "ERROR"
            }
        },
        "stage": "OnImageCacheComplete"
    },
    "__stage__": "OnDiskPrepared",
    "__status__": "error",
    "__task_name__": "StorageCacheImageTask"
}
```
<img width="1591" alt="image" src="https://github.com/user-attachments/assets/862f8322-9e26-493d-8e48-9709844f9b5f">

**Comment by ioito** [comment]
看起来是上传的镜像被aws删除了,可以手动上传下这个镜像到aws试试

**Comment by rekazer0** [comment]
> 看起来是上传的镜像被aws删除了,可以手动上传下这个镜像到aws试试

这是我本地私有云的镜像，你指的是在镜像缓存到aws后被删除了吗？

**Comment by rekazer0** [comment]
> 看起来是上传的镜像被aws删除了,可以手动上传下这个镜像到aws试试

我发现在缓存的过程中，会创建一个临时的s3存储桶用于存储缓存镜像，过一会自动删除了。

**Comment by rekazer0** [comment]
> 看起来是上传的镜像被aws删除了,可以手动上传下这个镜像到aws试试

<img width="507" alt="image" src="https://github.com/user-attachments/assets/110b951e-f39d-4de6-9609-872c7819b6d2">
界面提示缺少`head /`权限，但我已经是根用户，且在AWS中也没有找到这个权限

**Comment by rekazer0** [comment]
> 权限这个可以先忽略，aws自定义镜像创建过程就是先上传镜像到s3,然后再导入镜像，你先用要上传的这个镜像手动上传到aws看能否成功

我尝试通过https手动将qcow2格式的镜像上传到s3，是正常的。需要将raw格式的镜像上传并转换成快照再转成AMI吗？这个需要的时间比较久，我正在按照这篇最佳实践尝试。
`https://docs.redhat.com/zh-cn/documentation/red_hat_enterprise_linux/9/html/deploying_rhel_9_on_amazon_web_services/uploading-the-rhel-image-to-aws_deploying-a-virtual-machine-on-aws#importing-your-image-as-a-snapshot_deploying-a-virtual-machine-on-aws`

**Comment by rekazer0** [comment]
我尝试将上传至s3的raw镜像转换成AMI，报错
```
VM Import task failed with taskId 'import-ami-xxxxxxxx', status = 'deleted' for ARN 'arn:aws-cn:imagebuilder:xxxxxxxxxxximage/dasos211/1.0.0/1'. 'ClientError: Unsupported kernel version 4.19.90-0.240102.openeuler.x86_64'
```
是不是由于AWS不支持欧拉的内核导致的

**Comment by ioito** [comment]
看报错确实是这样的

**Comment by rekazer0** [comment]
补充，在测试过程中发现如果aws上的 vmimport已经被创建，而配置的策略与cloupods所需权限不符也会出现这个报错，需要手动删除此角色与同名策略，部署过程中cloupods 会自动新建。
