### ISSUE TITLE
[求助/Help] 如何让创建虚拟机使用 cpu 直通

### ISSUE THREAD

**Issue by loyalpartner** [yunionio/cloudpods#21814]
我接手 cloudpods 后 发现 qemu 的参数是 -cpu qemu64,
检查了 /etc/yunion/host.conf , 发现 host_cpu_passthrough 设置成了 false,

我修改成 true 后并重启了机器,  并新建了一台新的虚拟机, qemu 的 -cpu 参数 还是 qemu64

请问要怎么修改呢?

**Comment by wanyaoqi** [comment]
@loyalpartner 
需要修改configmap kubectl edit cm -n onecloud default-host , 然后重启 host服务

**Comment by loyalpartner** [comment]
> @loyalpartner 需要修改configmap kubectl edit cm -n onecloud default-host , 然后重启 host服务

非常感谢!

**Comment by loyalpartner** [comment]
> @loyalpartner 需要修改configmap kubectl edit cm -n onecloud default-host , 然后重启 host服务

抱歉， 重启 host 服务是指 重启虚拟机吗

**Comment by loyalpartner** [comment]
> > > @loyalpartner 需要修改configmap kubectl edit cm -n onecloud default-host , 然后重启 host服务
> > 
> > 
> > 抱歉， 重启 host 服务是指 重启虚拟机吗
> 
> 重启default-host相关的 pod，`kubectl rollout restart ds -n onecloud default-host`

这个会影响已经运行的虚拟吗？

**Comment by wanyaoqi** [comment]
不会
