### ISSUE TITLE
[BUG] RDS maintain_time 字段长度过短

### ISSUE THREAD

**Issue by swordqiu** [yunionio/cloudpods#21836]
**问题描述/What happened**:

[info 2024-12-17 06:36:35 models.syncRegionDBInstances(cloudsync.go:1267)] SyncDBInstances for region 华东地区(上海) result: removed 0 failed 0 updated 0 failed 0 added 0 failed 168;newFromCloudDBInstance.Insert: TxExec: Error 1406: Data too long for column 'maintain_time' at row 1

RDS导入，maintain_time 如果一周七天都设置了，字段不够长

version: 3.11.8

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by ioito** [comment]
clonse #21838
