### ISSUE TITLE
[求助/Help] 如何给已经创建的虚拟机修改cpu 的数量

### ISSUE THREAD

**Issue by loyalpartner** [yunionio/cloudpods#21837]
我通过 cloudpods web ui 新建了一台虚拟机, cpu 数量设置成16 , 但是我发现设置的少了, 我想调整cpu的核心数到32, 需要怎么操作呢?

**Comment by Dowanw0w** [comment]
![image](https://github.com/user-attachments/assets/3988a338-8c03-47f6-8f04-e5d3a882bdee)
