### ISSUE TITLE
创建机器是磁盘使用默认存储时,不应该默认使用local

### ISSUE THREAD

**Issue by ioito** [yunionio/cloudpods#4667]
**What happened**:
创建vmware指定network时，使用默认存储创建失败，指定nas存储会成功
**What you expected to happen**:
创建vmware指定network时 使用默认存储可以创建成功
**How to reproduce it**:
network关联的vmwre宿主机使用的是nas存储，创建时使用默认存储
**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by rainzm** [comment]
> /cc @rainzm 看下这个问题修复了吗？

Got. 我搞个有vsan存储的vmware环境测试一下。

**Comment by rainzm** [comment]
这是因为 EsxiGuestDriver 会自填上一个 DefaultSysDiskBackend，然后DataDiskBackend如果为空，就会跟着SysDiskBackend走。正确的做法应该是让调度器去做选择，为了降低改动的影响，解决方案为：
EsxiGuestDriver 的 DefaultSysDiskBackend 为空，交由调度器去做选择。
