### ISSUE TITLE
如果创建了 user ，但是没有加入项目，前端登陆界面会一直 loading

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#8914]
**What you expected to happen**:

预期是跳转到一个页面，提示用户说没有加入项目，请求管理员给该用户加入项目

**How to reproduce it**:

```bash
$ climc user-create demo --password demo123A --enabled
```
然后使用该用户登陆前端

/cc @houjiazong

**Comment by zexi** [comment]
截图如下：

![image](https://user-images.githubusercontent.com/10767027/125065755-cbb90e00-e0e4-11eb-9d7d-153e1e11c22e.png)

**Comment by Easy-MJ** [comment]
已解决，https://github.com/yunionio/dashboard/pull/575
