### ISSUE TITLE
前端是否可以有多租户管理和全局配置管理的界面？

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#9500]
- 多租户管理是大家比较想要的一个东西
- 全局配置管理是因为有些配置在 config file 里面已经不生效了，需要前端有个统一的界面管理 global 的配置

**Comment by zexi** [comment]
3.8.4 已经提供了多租户管理界面

**Comment by GuoLiBin6** [comment]
https://github.com/yunionio/dashboard/pull/1270 增加认证与安全-多租户
